### ISSUE TITLE
Need to update hash sum of Steam

### ISSUE THREAD

**Issue by yangl1996** [Winetricks/winetricks#1002]
Steam installer has been updated and the current hash sum is no longer correct. The new one is `3bc6942fe09f10ed3447bccdcf4a70ed369366fef6b2c7f43b541f1a3c5d1c51`.

Could someone confirm this new hash sum? I'm happy to submit a PR to fix it.

**Comment by alex9099** [comment]
For me changing the checksum on winetricks script works fine, i'll try to install steam and see if everything works

**Comment by yangl1996** [comment]
@alex9099 thanks!

Just noticed that there has been a PR (#1000). So I'm closing this issue. Sorry for the duplicate.
