### ISSUE TITLE
MT4 installs  MT5 Instead

### ISSUE THREAD

**Issue by toor11** [Winetricks/winetricks#1009]
When trying to install mt4 it downloads and installes mt4

Please update the download URL

**Comment by austin987** [comment]
Do you (or anyone) know of a working mt4 URL?

**Comment by toor11** [comment]
they have stopped the develop[ement of MT4 you can download only MT5 from the website.
Here is the answer.
So I guess it is needed to update winetricks to show mt5 from now on :)

You can download MetaTrader 4 from your broker's website. Please, notice that:

All our resources are allocated for the development of MetaTrader 5 and MQL5 lanquage. Regarding MetaTrader 4 can say that its further development is not part of our plans.

Please, read these articles:

https://www.mql5.com/en/articles/81

https://www.mql5.com/en/articles/66

**Comment by bputrapajakio** [comment]
api not working anymore

<img width="501" height="408" alt="Image" src="https://github.com/user-attachments/assets/27a32bc2-002f-4389-91f5-f1f5808d5be3" />
