### ISSUE TITLE
Cache URL for w2ksp4_en.exe not available

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#1026]
When downloading `w2ksp4_en.exe` (during installation of `winhttp`) from `ftp.twaren.net`, when the connection fails, the fallback URL is:

> https://web.archive.org/web/2000/ftp://ftp.twaren.net/pub/cpatch/msupdate/win2000/en/w2ksp4_en.exe

However, this URL doesn't exist.

As example, check [build 389046675](https://travis-ci.org/EA31337/FX-MT-VM/jobs/389046675#L619).

Is it possible to ignore downloading from web.archive.org for this particular file, so it's less confusing?

**Comment by austin987** [comment]
No, disabling the fallback per verb is not currently possible (and I don't think it's worth the complexity).

**Comment by austin987** [comment]
Note that the original URL being down would be a valid bug, but that appears to have been a transient issue (worked for me just now).

**Comment by kenorb** [comment]
For the issue with original URL not being downloaded I've reported at: travis-ci/travis-ci/issues/9732

As for workaround, I've set:

    WINETRICKS_DOWNLOADER_RETRIES=20

then it seems to go through.

**Comment by kakurasan** [comment]
Could you test `http://ftp.upf.br/pub/win2k/w2ksp4_en.exe`? The URL works for me in Travis CI.

If it works, we can replace current URL with it.

**Comment by kenorb** [comment]
@kakurasan I've tested it and it works fine (it got also archived version which works). I've opened the new issue at GH-1029 for the suggestion.
