### ISSUE TITLE
Downloading `w2ksp4_en.exe` file via FTP unstable

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#1029]
Downloading of `w2ksp4_en.exe` file via FTP (when installing `winhttp`) is very unstable when running in Travis CI. Related bug: travis-ci/travis-ci/issues/9732

Here is the example of [build 390216041](https://travis-ci.org/kenorb/travis-test/builds/390216041) where it took 19 retries to download the file.

It seems that `winetricks` got only 3 retries by default (see: [build 389046675](https://travis-ci.org/EA31337/FX-MT-VM/jobs/389046675#L593)), which is too few.
Secondly, this file [has no archived version](https://github.com/Winetricks/winetricks/issues/1026). 
As workaround, I could set: `WINETRICKS_DOWNLOADER_RETRIES=20` which mostly will work for this case.

### Suggestion

The suggested solution by @kakurasan (as per [comment](https://github.com/Winetricks/winetricks/issues/1026#issuecomment-396049390)) is to update the endpoint to: <http://ftp.upf.br/pub/win2k/w2ksp4_en.exe>

I've tested two endpoints at [build 390520271](https://travis-ci.org/kenorb/travis-test/jobs/390520271) and the new one was slower (1MB/s vs 18.8MB/s), but it was not dropping the connections. The old one took [6 retries](https://travis-ci.org/kenorb/travis-test/jobs/390520270) to download (where 3 is maximum for `winetricks`). Another advantage for using the new endpoint, is that, it got the fallback to the archived version (which exists).

----

Another suggestion for the installation of `winhttp` could be adding the ability to override the URL with own mirror URL of choice, or by providing two above endpoints (previous and the new one) in case one of it is down.

----

Related: Winetricks/winetricks/issues/1026

**Comment by kakurasan** [comment]
There are still many mirrors for `w2ksp4_en.exe` and we can use one of them instead (e.g. `https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE`).

Alternatively, we can use current server via HTTP: `http://ftp.twaren.net/cpatch/msupdate/win2000/en/w2ksp4_en.exe`

I think:
* It's enough to replace FTP URL with HTTP(S) URL in this case
* There are a lot of other FTP URLs in Winetricks and we need to replace them too

**Comment by kenorb** [comment]
Yep, changing the current server to HTTP is even quicker without dropping the connections.

Test: [build 390793614](https://travis-ci.org/kenorb/travis-test/builds/390793614)
