### ISSUE TITLE
Missing sound verbs

### ISSUE THREAD

**Issue by ThePooN** [Winetricks/winetricks#1031]
It looks like the sound verbs were removed in the latest Winetricks release.  
The commit in which this change occured doesn't make it clear whether this was an intentional change or not: https://github.com/Winetricks/winetricks/commit/f5677f88a6d2fa1009a21f5feb582054cfb9fa07. I can't find any discussion related to this in issues/PRs neither.

Whether this was intentional or not, I think these verbs should stay. They are often used for debugging purposes, especially in programs where audio is crucial, such as in rhythm games. The `sound=alsa` verb is actually used by [one of the most popular guide to get osu! running on Linux](https://osu.ppy.sh/community/forums/topics/367783).

**Comment by austin987** [comment]
No, not intentional. Currently traveling, will look when I get back (though I suspect someone will send a pr quicker than that ;))
