### ISSUE TITLE
[Windows DLL] dxsdk_jun2010 - dotnet20 not needed anymore

### ISSUE THREAD

**Issue by Sethox** [Winetricks/winetricks#1034]
Using winetricks it tries to install dotnet20, dotnet20 does not work on 64-bit wineprefix. But running/installing the ".exe" acquired in winetricks script ( https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe ) manually it works.

I noticed the script mentions:
[line 6599] `# Without dotnet20, install aborts halfway through`

Note:
Wine-staging 3.10

**Comment by austin987** [comment]
That doesn't seem to be the case in upstream wine. With plain wine, it tries to install dotnet20 on its own. Staging must have a fix for that in place.
