### ISSUE TITLE
'flash' winetrick not working properly; one of the URLs is now broken

### ISSUE THREAD

**Issue by vitor251093** [Winetricks/winetricks#1040]
More specifically, that one:
https://download.macromedia.com/pub/flashplayer/updaters/14/flashplayer_14_sa.exe

Accessing it now leads to a 'Not Found' page instead of the file. I didn't had the file with me, but I've looked for it in the internet until I found it in a torrent. It matches the hash in the winetricks file, so I guess it can be considered legitimate. 

I've hosted it in the Porting Kit website. This is the URL in case you want to use it, or at least if you want to download it to host somewhere else:
http://portingkit.com/wineskin/winetricks/flash/flashplayer_14_sa.exe

**Comment by kakurasan** [comment]
The standalone flash player is available from Adobe as of version 29.0.0.171: `https://fpdownload.macromedia.com/pub/flashplayer/installers/archive/fp_29.0.0.171_archive.zip` contains `flashplayer29_0r0_171_win_sa.exe`.

I think we don't need your file if we switch to newer version.

**Comment by CitrusAlex** [comment]
I get "File Not Found" error dialog when installing flash with this patched winetricks. Wineprefix is 64 bit and is set to Win7.

**Comment by kakurasan** [comment]
@CitrusAlex Thanks for testing, I confirmed the issue: The "File not found." dialog appears only when wineprefix is 64bit.
Wine says `wine: cannot find L"C:\\windows\\system32\\Macromed\\Temp\\{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}\\InstallFlashPlayer.exe"` when the dialog appears.

I added a workaround for it: `https://raw.githubusercontent.com/kakurasan/winetricks/415b62b5c7d7e483b3054e905e6a51adfb490649/src/winetricks`. Could you test this?

**Comment by CitrusAlex** [comment]
Works wonderfully!

**Comment by kakurasan** [comment]
I removed the workaround because I found that it's enough to set OS version to XP before running the installers: `https://raw.githubusercontent.com/kakurasan/winetricks/a10cc8af351553f6511fd64a3b91d7088b043c52/src/winetricks`
