### ISSUE TITLE
xact installation fails in 64-bit prefix

### ISSUE THREAD

**Issue by shmerl** [Winetricks/winetricks#1046]
Is winetricks supporting 64-bit prefixes?

When trying to install xact, I got this (using freshly built Wine master):
```
Executing /opt/wine-master/bin/wine64 regsvr32 xactengine2_0.dll
regsvr32: Failed to load DLL 'xactengine2_0.dll'
------------------------------------------------------
Note: command /opt/wine-master/bin/wine64 regsvr32 xactengine2_0.dll returned status 3. Aborting.
```

**Comment by austin987** [comment]
Works fine here. Did you compile a 32-bit wine, or just wine64? The latter won't work.

**Comment by shmerl** [comment]
> or just wine64? The latter won't work.

Ah, may be that's the reason. I'll test again.

**Comment by austin987** [comment]
Upstream Wine (and Winetricks) expect either a win32 or a wow64 build, win64 alone is not supported. win64 will only work in limited circumstances (strictly 64-bit windows or winelib apps will work). Most 64-bit apps still  have 32-bit components.
