### ISSUE TITLE
winetricks aint installing dxvk

### ISSUE THREAD

**Issue by rawfoxDE** [Winetricks/winetricks#1047]
hello,
winetricks dxvk results with

`sha256sum mismatch! Rename /home/rawfox/.cache/winetricks/dxvk60/dxvk-0.60.tar.gz and try again.
`

This was not happening on vulkan-0.54 as that was installing properly.
Problems emerged when i deleted the winetricks cache at ~/.cache/winetricks/* to upgrade to latest vulkan drivers, so the script ordered a new download and can not handle it.

**Comment by MEXAHOTABOP** [comment]
0.60 was rebuilded and now have other checksum

**Comment by rawfoxDE** [comment]
Ok, thanks for your reply, how should i deal with that ?

**Comment by MEXAHOTABOP** [comment]
just wait for https://github.com/Winetricks/winetricks/pull/1048
or update sha sum mannualy to 27d6f700241d3ec3b6c002c3d739bb0e3f210ec916ecb5a62d9204e9e50f2c4a

**Comment by austin987** [comment]
You'd have to edit the shasum in winetricks (or remove it). I plan to push a fix tonight or tomorrow.

**Comment by rawfoxDE** [comment]
Thanks a ton, ill wait for somewhat later then :)
Cheers \m/

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/fe470df1abc7f840a158dd4e4612cbb5e5680af0
https://github.com/Winetricks/winetricks/commit/3389d2a8fea1577ed080e3da73a74124e7573160
https://github.com/Winetricks/winetricks/commit/c423a85b3cfda1e6181fc8164b089842964a0794
