### ISSUE TITLE
Andale missing - any reason for this?

### ISSUE THREAD

**Issue by Lantizia** [Winetricks/winetricks#1051]
Hey,

So just looking over the corefonts verb and comparing it to the msttcorefonts installer from my distro (see [here](https://packages.ubuntu.com/source/bionic/msttcorefonts))...

Noticed that Andale Mono is missing from the verb, a quick check of the original MS 'Core fonts for the Web' project confirms it is a part of it...

[https://web.archive.org/web/20020124085641/http://www.microsoft.com/typography/fontpack/default.htm](https://web.archive.org/web/20020124085641/http://www.microsoft.com/typography/fontpack/default.htm)

At the moment the corefonts verb downloads all of them from [https://mirrors.kernel.org/gentoo/distfiles/](https://mirrors.kernel.org/gentoo/distfiles/) and that also has andale32.exe so not sure why it is missing off the list of downloads in the verb?

There is a [pull request](https://github.com/Winetricks/winetricks/pull/888) which mentions it isn't distributed by Windows any more... but since it was in the past it is still useful for running older software in Wine that expects to find it.

Also it can be found here, which I believe is the project the msttcorefonts package for my system is based off...
https://sourceforge.net/projects/corefonts/files/the%20fonts/final/

**Comment by Lantizia** [comment]
Made a pull request...

https://github.com/Winetricks/winetricks/pull/1053

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/aef662678aa37bf39e708ca0f67157f8591cb10f
