### ISSUE TITLE
Split the huge source file

### ISSUE THREAD

**Issue by mk-pmb** [Winetricks/winetricks#1058]
Hi! I'm trying to hack on `src/winetricks` but its hugeness (20182 lines atm) strains my editor immensely, also Firefox trying to render the file's github page. What would you think of splitting that file into smaller ones, then `source`-ing (or `.`-ing in `sh`) all of them from a loder script?

**Comment by austin987** [comment]
I'm not a fan of the idea currently. It would break the current assumption that one can wget one file (similar for updating, e.g., with winetricks self-update).

FYI, vim handles it fine ;).

Perhaps in the future as part of a larger refactor, but nothing planned for now.

**Comment by mk-pmb** [comment]
We could have a git hook generate a combined file for the wget users.
Thanks for the feedback anyway. This way I know I have to roll my own tooling for now, next time I want to work with the source.
