### ISSUE TITLE
Winetricks list empty

### ISSUE THREAD

**Issue by iblowmymind** [Winetricks/winetricks#1065]
Hey,
I have a Winetricks shipped with [WineBottler](http://winebottler.kronenberg.org), and recently I get nothing in the list. Except for Adobe AIR. Can you help, please?
![ekran resmi 2018-08-05 08 40 51](https://user-images.githubusercontent.com/28228415/43682970-a2008204-988b-11e8-8751-0fc2c9e93f6f.png)

**Comment by austin987** [comment]
That GUI isn't part of winetricks, it's something that winebottler is doing. You'll have to ask them.
