### ISSUE TITLE
kindle download dead

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#1069]
https://s3.amazonaws.com/kindleforpc/44025/KindleForPC-installer-1.16.44025.exe

Returns
`AccessDeniedAccess Denied4F36F0D8D54035F7hZ/pFVZEkE2a8ZD2BMZKc+6Wrrb7tLyQseasg/psII/efoJseULorzkCPAFi1JfmaOOHnARO7Z0=`

Haven't found a working link. Hoping someone that cares about kindle knows of one.

**Comment by gverm** [comment]
This web.archive link works for me, but I'm not sure if that's acceptable: [link](https://web.archive.org/web/20160817182927/https://s3.amazonaws.com/kindleforpc/44025/KindleForPC-installer-1.16.44025.exe)

**Comment by austin987** [comment]
Archive.org works as a last resort, as their mirrors aren't very reliable. If you would send a pr, I'd appreciate it (unless someone finds a better link ;)).

**Comment by gverm** [comment]
@austin987 Done, sent in PR #1071

**Comment by austin987** [comment]
Thanks!
