### ISSUE TITLE
dotnet is a mess

### ISSUE THREAD

**Issue by testman42** [Winetricks/winetricks#1080]
I am slightly annoyed by the fact that if I try to install either `dotnet45` or `dotnet452` and that installation fails, then I can't do anything because I get a message that the version I am trying to install, and I quote, `conflicts with dotnet40, which is already installed.`.

And then if I try to do `winetricks dotnet40` the install wizard says `Same or higher version of .NET Framework 4 has already been installed on this computer.`

How hard would it be to fix this mess and make installation or upgrades of dotnet versions less confusing?

**Comment by Chiitoo** [comment]
Which versions of Wine and Winetricks?

You may need a 32-bit prefix due to https://bugs.winehq.org/show_bug.cgi?id=45537 if using Wine 3.13.

You might try the '--force' option for Winetricks, but often it's better to start with a clean prefix in such cases.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/6320033a760814c33f7c1547d195be946e95f5d3 informs the user that `--force` can be used to ignore w_conflicts().
