### ISSUE TITLE
Add option to install only the "Arial" font.

### ISSUE THREAD

**Issue by tannisroot** [Winetricks/winetricks#1083]
It would be really nice for users who have limited or slow data connection to have an option to install just the "Arial" font, since it's usually the only one actually required by the applications, and getting a whole bunch of others with "corefonts" is often unnecessary.

**Comment by austin987** [comment]
Confirming, I'll try to get to it this week.

**Comment by austin987** [comment]
Note: if anyone plans to beat me to it, we should add individual verbs for everything in corefonts, then make it a metaverb around those.
