### ISSUE TITLE
msxml3 not installing

### ISSUE THREAD

**Issue by IvanDSM** [Winetricks/winetricks#1086]
I've tried to install msxml3 on Wine Staging 3.13 and Wine 3.14, but the installer always ends prematurely. Here's the log for msxml3 on a clean 32-bit wine prefix:

```ivan@Eldorado ~ $ winetricks msxml3
Using winetricks 20180815-next - sha256sum: 762a612d72192fd189c274d28de9e98f30063daa925d386819544a5054af743d with wine-3.14 and WINEARCH=win32
Executing w_do_call msxml3
Executing load_msxml3 
Using native override for following DLLs: msxml3
Executing wine regedit C:\windows\Temp\_msxml3\override-dll.reg
0041:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 18/02/2018, dlt (d/m/y): 4/11/2018
Executing cd /home/ivan/.cache/winetricks/msxml3
Executing wine msiexec /i msxml3.msi
0043:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 18/02/2018, dlt (d/m/y): 4/11/2018
0045:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 18/02/2018, dlt (d/m/y): 4/11/2018
0043:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0043:err:richedit:ReadStyleSheet skipping optional destination
0043:err:richedit:ReadStyleSheet skipping optional destination
0043:fixme:msi:event_spawn_wait_dialog doing nothing
004b:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for -03, bias 180, std (d/m/y): 18/02/2018, dlt (d/m/y): 4/11/2018
0043:err:msi:execute_script Execution of script 0 halted; action L"[C:\\users\\ivan\\Temp\\msod51c.tmp\00015\0001C:\\Program Files\\Common Files\\Microsoft Shared\\SFPCA Cache\\\0001msxmlx.inf\0001EOF_LIST\0001<=>S-1-5-21-0-0-0-1000<=>{D642E38E-0D24-486C-9A2D-E316DD696F4B}]Wdsfpca_DoInstallWFPFile.C8C0673E_50E5_4AC4_817B_C0E4C4466990" returned 1603
0043:err:msi:ITERATE_Actions Execution halted, action L"InstallFinalize" returned 1603
0043:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0043:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0043:err:msi:ITERATE_Actions Execution halted, action L"ExecuteAction" returned 1603
------------------------------------------------------
Note: command wine msiexec /i msxml3.msi returned status 67. Aborting.
------------------------------------------------------
ivan@Eldorado ~ $ ```

**Comment by austin987** [comment]
This is almost certainly a regression in Wine's MSI. @zfigura are you aware of this one already?

**Comment by zfigura** [comment]
This is a weird bug, and seems to have to do with target path resolution, which isn't one of the things I've touched recently. Are we sure it's a regression?

It works with `winetricks -q msxml3`.

**Comment by zfigura** [comment]
This looks like WineHQ bug 26925. I don't know why this would only start showing up now.

**Comment by ssergio-ll** [comment]
Hello. Some know if this bug is fix? I need for install photoshop. Thanks!

**Comment by zfigura** [comment]
As stated, you can use `winetricks -q msxml3`.

**Comment by masternetra** [comment]
Suffer the same issue. It seems to install just fine, from the GUI installer, but clicking the finish button on the installer results in the "Note: command wine msiexec /i msxml3.msi returned status 67. Aborting." and the claim it was aborting when in fact it was simply finished.

**Comment by masternetra** [comment]
Swithed over to a 32bit prefix and winetricks -q does not work for it. Getting a abort status 5.

Executing w_do_call msxml3
Executing load_msxml3 
rm: cannot remove '/home/<censored>/.wine/dosdevices/c:/windows/system32/msxml3.dll': No such file or directory
Using native override for following DLLs: msxml3
Executing wine regedit /S C:\windows\Temp\_msxml3\override-dll.reg
Executing cd /home/<censored>/.cache/winetricks/msxml3
Executing wine msiexec /i msxml3.msi /q
0033:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
wine: Unhandled page fault on read access to 0x00000000 at address 0x1331a82 (thread 0033), starting debugger...
Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x01331a82).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:01331a82 ESP:0033f388 EBP:001e04ec EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:00000000 EBX:001dfd30 ECX:ffffffff EDX:00000000
 ESI:001dfb00 EDI:00000000
Stack dump:
0x0033f388:  0033f408 001dfd30 001dfb00 7ec2b000
0x0033f398:  00000000 7eba4240 001dfd30 7ec737b8
0x0033f3a8:  00000000 00000000 7eba3940 00000000
0x0033f3b8:  0033f458 7eba4722 0016c818 00000004
0x0033f3c8:  7eb5e799 7eba4722 00110000 00000000
0x0033f3d8:  0033f458 0016c818 00000000 00000001
Backtrace:
=>0 0x01331a82 in cabinet (+0x1a82) (0x001e04ec)
0x01331a82: repne scasb	%es:(%edi)
Modules:
Module	Address			Debug info	Name (77 modules)
PE	 1330000- 1347000	Export          cabinet
PE	71590000-71617000	Deferred        comctl32
ELF	7b400000-7b7ec000	Deferred        kernel32<elf>
  \-PE	7b420000-7b7ec000	\               kernel32
ELF	7bc00000-7bcfd000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bcfd000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d25e000-7d27c000	Deferred        libgcc_s.so.1
ELF	7d29a000-7d3e4000	Deferred        libx11.so.6
ELF	7d4b3000-7d4ba000	Deferred        libxfixes.so.3
ELF	7d4ba000-7d4c6000	Deferred        libxcursor.so.1
ELF	7d4c6000-7d4d9000	Deferred        libxi.so.6
ELF	7d4d9000-7d4dd000	Deferred        libxcomposite.so.1
ELF	7d4dd000-7d4ea000	Deferred        libxrandr.so.2
ELF	7d4ea000-7d4f6000	Deferred        libxrender.so.1
ELF	7d4f6000-7d4fd000	Deferred        libxxf86vm.so.1
ELF	7d4fd000-7d501000	Deferred        libxinerama.so.1
ELF	7d501000-7d50b000	Deferred        librt.so.1
ELF	7d50b000-7d526000	Deferred        libbsd.so.0
ELF	7d526000-7d52d000	Deferred        libxdmcp.so.6
ELF	7d52d000-7d531000	Deferred        libxau.so.6
ELF	7d531000-7d55d000	Deferred        libxcb.so.1
ELF	7d55d000-7d572000	Deferred        libxext.so.6
ELF	7d574000-7d58e000	Deferred        sxs<elf>
  \-PE	7d580000-7d58e000	\               sxs
ELF	7d590000-7d620000	Deferred        winex11<elf>
  \-PE	7d5a0000-7d620000	\               winex11
ELF	7d620000-7d644000	Deferred        imm32<elf>
  \-PE	7d630000-7d644000	\               imm32
ELF	7d6db000-7d70d000	Deferred        libexpat.so.1
ELF	7d70d000-7d758000	Deferred        libfontconfig.so.1
ELF	7d758000-7d792000	Deferred        libpng16.so.16
ELF	7d792000-7d84f000	Deferred        libfreetype.so.6
ELF	7d84f000-7d872000	Deferred        libtinfo.so.5
ELF	7d872000-7d898000	Deferred        libncurses.so.5
ELF	7d898000-7d8d3000	Deferred        ws2_32<elf>
  \-PE	7d8a0000-7d8d3000	\               ws2_32
ELF	7d8d3000-7d8fb000	Deferred        mpr<elf>
  \-PE	7d8e0000-7d8fb000	\               mpr
ELF	7d8fb000-7d91a000	Deferred        libz.so.1
ELF	7d938000-7d9b4000	Deferred        wininet<elf>
  \-PE	7d940000-7d9b4000	\               wininet
ELF	7d9b4000-7da2a000	Deferred        shlwapi<elf>
  \-PE	7d9c0000-7da2a000	\               shlwapi
ELF	7da2a000-7e3e9000	Deferred        shell32<elf>
  \-PE	7da40000-7e3e9000	\               shell32
ELF	7e3e9000-7e51b000	Deferred        oleaut32<elf>
  \-PE	7e400000-7e51b000	\               oleaut32
ELF	7e51b000-7e59c000	Deferred        rpcrt4<elf>
  \-PE	7e530000-7e59c000	\               rpcrt4
ELF	7e59c000-7e6ca000	Deferred        gdi32<elf>
  \-PE	7e5b0000-7e6ca000	\               gdi32
ELF	7e6ca000-7e8d2000	Deferred        user32<elf>
  \-PE	7e6e0000-7e8d2000	\               user32
ELF	7e8d2000-7e94b000	Deferred        advapi32<elf>
  \-PE	7e8e0000-7e94b000	\               advapi32
ELF	7e94b000-7eaa5000	Deferred        ole32<elf>
  \-PE	7e960000-7eaa5000	\               ole32
ELF	7eaa5000-7eb44000	Deferred        urlmon<elf>
  \-PE	7eab0000-7eb44000	\               urlmon
ELF	7eb44000-7ec74000	Deferred        msi<elf>
  \-PE	7eb50000-7ec74000	\               msi
ELF	7ec74000-7ec99000	Deferred        msiexec<elf>
  \-PE	7ec80000-7ec99000	\               msiexec
ELF	7ee99000-7eead000	Deferred        libnss_files.so.2
ELF	7eead000-7eec8000	Deferred        libnsl.so.1
ELF	7eec8000-7eed6000	Deferred        libnss_nis.so.2
ELF	7eed6000-7eee0000	Deferred        libnss_compat.so.2
ELF	7eee0000-7efe2000	Deferred        libm.so.6
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7b0a000-f7b0f000	Deferred        libdl.so.2
ELF	f7b0f000-f7ceb000	Deferred        libc.so.6
ELF	f7ceb000-f7d0a000	Deferred        libpthread.so.0
ELF	f7d28000-f7edf000	Dwarf           libwine.so.1
ELF	f7ee1000-f7f09000	Deferred        ld-linux.so.2
ELF	f7f0c000-f7f0e000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000023    0
	00000020    0
	0000001b    0
	00000015    0
	00000014    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000026    0
	00000022    0
	00000021    0
	0000001f    0
00000024 explorer.exe
	00000029    0
	00000028    0
	00000027    0
	00000025    0
00000032 (D) C:\windows\system32\msiexec.exe
	0000003b    0
	0000003a    0
	00000039    0
	00000034    0
	00000033    0 <==
00000035 msiexec.exe
	00000040    0
	0000003f    0
	00000036    0
System information:
    Wine build: wine-3.15
    Platform: i386
    Version: Windows 5.1 (0)
    Host system: Linux
    Host version: 4.15.0-33-generic
0036:err:msiexec:custom_action_server Failed to read from custom action server pipe: 109
------------------------------------------------------
Note: command wine msiexec /i msxml3.msi /q returned status 5. Aborting.

**Comment by SGmuwa** [comment]
win32
```
sgmuwa@sgmuwa-HP-Pavilion-dv7-Notebook-PC:~$ winetricks -q msxml3
Using winetricks 20190912 - sha256sum: 669617710f27ac714338ad98a6ae90034d41e05b697dd9489b190b65e2b824b7 with wine-4.0.2 (Ubuntu 4.0.2-1) and WINEARCH=win32
Executing w_do_call msxml3
Executing load_msxml3 
rm: невозможно удалить '/home/sgmuwa/.wine32/dosdevices/c:/windows/system32/msxml3.dll': Нет такого файла или каталога
Using native override for following DLLs: msxml3
Executing wine regedit /S C:\windows\Temp\_msxml3\override-dll.reg
Executing cd /home/sgmuwa/.cache/winetricks/msxml3
------------------------------------------------------
Обход ошибки 26925 -- Forcing quiet install
------------------------------------------------------
Executing wine msiexec /i msxml3.msi /q
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:msi:execute_script Execution of script 0 halted; action L"[C:\\users\\sgmuwa\\Temp\\mso3d62.tmp\00012\0001C:\\Program Files\\Common Files\\Microsoft Shared\\SFPCA Cache\\\0001msxmlx.inf\0001EOF_LIST\0001<=>S-1-5-21-0-0-0-1000<=>{D642E38E-0D24-486C-9A2D-E316DD696F4B}]Wdsfpca_DoInstallWFPFile.C8C0673E_50E5_4AC4_817B_C0E4C4466990" returned 1603
0009:err:msi:ITERATE_Actions Execution halted, action L"InstallFinalize" returned 1603
0044:err:ole:TLB_ReadTypeLib Loading of typelib L"C:\\windows\\system32\\msxml3.dll" failed with error 2
------------------------------------------------------
Важно: команда wine msiexec /i msxml3.msi /q вернула статус 67. Прерывание.
------------------------------------------------------
```

**Comment by IvanDSM** [comment]
@SGmuwa Здравствуйте! Не могли бы вы предоставить вывод команды на английском языке? Таким образом, разработчикам будет проще понять, какие ошибки происходят, поскольку большинство из них не говорят по-русски. Вы можете запустить эту команду, чтобы получить вывод команды на английском языке:
`env LC_ALL=C winetricks -q msxml3`

**Comment by SGmuwa** [comment]
The bug disappeared after the commands:
```
sgmuwa@Notebook:~$ rm -r ~/.wine32
sgmuwa@Notebook:~$ WINEPREFIX=~/.wine32 WINEARCH=win32 LC_ALL=C wineboot
```

**Comment by austin987** [comment]
What locale are you normally using to install? ru_RU.utf8 works for me.
