### ISSUE TITLE
dotnet20sp2 needs to be installed 2 times

### ISSUE THREAD

**Issue by tannisroot** [Winetricks/winetricks#1089]
Hi. I've noticed that in order to actually get dotnet20sp2 installed properly, the installer needs to be run 2 times. The first time it will always fail, but the second time it will pretty much always succeed (I never experienced it failing to install the second time). 
It would be very nice if this was be done by default for this verb.

**Comment by austin987** [comment]
What wine/winetricks version? Very likely a wine bug, fyi.

**Comment by tannisroot** [comment]
The latest. Ran —self-update first, still works.

**Comment by austin987** [comment]
Annual version numbers please, for posterity...

**Comment by tannisroot** [comment]
Sure, sorry! The version is 20180815-next.

**Comment by tannisroot** [comment]
And yeah, it's most definitely a wine bug, but it would be nice if winetricks could work around it.

**Comment by austin987** [comment]
Could you retest in recent wine? I think this fallout was from the msi rewrite in 3.13-3.17. 3.18+ should work fine.
