### ISSUE TITLE
Stuck installing dotnet45 on fresh wine-staging 3.13 win32

### ISSUE THREAD

**Issue by Gooberpatrol66** [Winetricks/winetricks#1091]
After a while, it gets stuck printing 
0053:err:ntdll:RtlpWaitForCriticalSection section 0x7bcf26e0 "/var/tmp/portage/app-emulation/wine-staging-3.13-r1/work/wine-3.13/dlls/ntdll/virtual.c: csVirtual" wait timed out in thread 0053, blocked by 0130, retrying (60 sec)
0151:err:ntdll:RtlpWaitForCriticalSection section 0x7bcf26e0 "/var/tmp/portage/app-emulation/wine-staging-3.13-r1/work/wine-3.13/dlls/ntdll/virtual.c: csVirtual" wait timed out in thread 0151, blocked by 00c3, retrying (60 sec)
02e5:err:ntdll:RtlpWaitForCriticalSection section 0x7bcf26e0 "/var/tmp/portage/app-emulation/wine-staging-3.13-r1/work/wine-3.13/dlls/ntdll/virtual.c: csVirtual" wait timed out in thread 02e5, blocked by 01de, retrying (60 sec)
01ad:err:ntdll:RtlpWaitForCriticalSection section 0x7bcf26e0 "/var/tmp/portage/app-emulation/wine-staging-3.13-r1/work/wine-3.13/dlls/ntdll/virtual.c: csVirtual" wait timed out in thread 01ad, blocked by 01c9, retrying (60 sec)
0110:err:ntdll:RtlpWaitForCriticalSection section 0x7bcf26e0 "/var/tmp/portage/app-emulation/wine-staging-3.13-r1/work/wine-3.13/dlls/ntdll/virtual.c: csVirtual" wait timed out in thread 0110, blocked by 0101, retrying (60 sec)
It can't be killed. It continues to spam the terminal until the computer is rebooted.

**Comment by PietJankbal** [comment]
There were some regressions in wine, but I think this should work again in wine-3,17. Could you try?

**Comment by Gooberpatrol66** [comment]
It installs now.
