### ISSUE TITLE
`winetricks directx9` overrides DirectShow dlls (devenum, msdmo, qcap, quartz) as native but doesn't install them

### ISSUE THREAD

**Issue by zfigura** [Winetricks/winetricks#1097]
As the title says.

The quartz dlls are provided in dxnt.cab but not installed; I'm not immediately sure why.

**Comment by austin987** [comment]
Wine-Bug: https://bugs.winehq.org/show_bug.cgi?id=45775

**Comment by zfigura** [comment]
As far as I see, winetricks should either not register these DLLs, or attempt to install them somehow. Which approach do we want to take?

**Comment by austin987** [comment]
Makes sense to me, thanks for looking into it, I had overlooked it before and was hoping to look this week, but always glad when someone beats me to it :)
