### ISSUE TITLE
wine loader frozen, winetricks error message

### ISSUE THREAD

**Issue by executiveOutlaw732** [Winetricks/winetricks#1099]
I am drudging through the process of setting up wine on my new linux mint 19 OS. It wasn't working at all first but I am making progress. I am using playonlinux and i'm trying to install firefox for windows so I can use my Xfinity stream and netflix accounts without switching to windows.

So first playonlinux was giving me error messages saying that Wine had crashed everytime I started the installation. I fixed this by running some commands and enabling 32 bit version.

Next the installer started to run and wine opened like, I assume, it was supposed to. However, the winemonoinstaller and the other wine processes were frozen, the bar didn't go up at all even overnight. Meanwhile, the firefox installer continued to run as if everything was going to plan.

I did some more research and learned about wine tricks and the different packages and .dll files needed for it to work. I ran some commands to install wine tricks. Now when I try to open winetricks I get this message:

`wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: /home/outlaw/.wine is not owned by you" `

Im not sure what to do as I am new to linux. Im wondering if maybe the directory isn't installed correctly? Something to do with dpkg command? 

If youre willing do help and would need more information, please give me a quick rundown on how to copy the debug file to a text log so that I can include it. Thanks!

**Comment by austin987** [comment]
My guess is you ran wine/winetricks with `sudo` at some point, and the directory isn't owned by your user.

You can use `sudo rm -rf ~/.wine` to get rid of it (which will delete any files in there, but sounds like you don't have anything important in there).

https://wiki.winehq.org/FAQ
https://forum.winehq.org/

may be helpful resources.
