### ISSUE TITLE
Some minor changes in dotnet>3.5 requested

### ISSUE THREAD

**Issue by PietJankbal** [Winetricks/winetricks#1111]
Hi,

Issue1:
As far as I can tell dotnet35sp1 installs fine in 64-bit prefix in current wine-3,17.
 Yet, winetricks tells me that it doesn`t work. I think this warning/blocker can be removed.
See also https://bugs.winehq.org/show_bug.cgi?id=45680

Issue2:
After install of dotnet452 (and other dotnet4.5.*) the windowsversion should be set back to win7 (and not remain on win2003 as now happens)
See also https://bugs.winehq.org/show_bug.cgi?id=45680#c12 at the end.

Regards,
Louis Lenders

**Comment by austin987** [comment]
Keep in mind that winetricks didn't just support latest development version, stable (and ideally earlier) should also work.

In other words, these fixes need to be behind wine version checks. For issue one that's trivial, but for issue 2, Focht gave no indication of when that was fixed (or relevant bug report).

**Comment by PietJankbal** [comment]
>Keep in mind that winetricks didn't just support latest development version, stable (and ideally earlier) >should also work.

Yeah, I overlooked that, I guess in stable it should work, setting to win7 will probably break apps when running in stable.

**Comment by austin987** [comment]
For that, I need to know what wine version moved to win7

**Comment by bobwya** [comment]
> For that, I need to know what wine version moved to win7

[Wine 2.2 Released](https://www.winehq.org/news/2017021701)
I.e. a pretty long time ago ;-)

**Comment by austin987** [comment]
Sorry, I meant what wine version should use 7 instead of 2k3 for .net. I assumed there was a relevant wine bug that was fixed..

**Comment by austin987** [comment]
Give this a try:
https://github.com/austin987/winetricks/commit/64ef44b245e9ff2fcf2644126459e97a54d98a28

that's only the dotnet35 changes; I plan to look at the rest of .Net over the next week or so.

This works for me with 3.0.1 and 3.18 (32/64, though 3.0.1+win64 doesn't work, and gives a warning to upgrade to 3.18+)

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/1771a95b8fd7466df8b069adb18510dd082d5ca3
