### ISSUE TITLE
SH path #!/usr/bin/sh incorrect on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Eonfge** [Winetricks/winetricks#1118]
By my knowledge, I did not move anything this critical, so that would imply that the default path is different. On 18.04, SH is in `/bin/sh`

Nice learning moment for me, cause I was not actually aware what #! did and where it came from. Don't now how to fix it though, my shell knowledge is virtually none.

**Comment by austin987** [comment]
Nothing in winetricks uses /usr/bin/sh.

**Comment by Eonfge** [comment]
https://github.com/Winetricks/winetricks/commit/541d23116d0165aa5eb17d406b161cf5721ae080#diff-04c6e90faac2675aa89e2176d2eec7d8

Yeah, had to specify better. The update-script in the readme. It was updated 3 days ago.

**Comment by Eonfge** [comment]
@austin987 In case you read closed issues. It's the update script i'm referring to.

**Comment by austin987** [comment]
Ah, my bad, I hadn't git pull recently on this machine. Fixed by https://github.com/Winetricks/winetricks/commit/e58f7e0962d87aa9e7b77b93a95db25e73a331b8
