### ISSUE TITLE
Age of Empires III is broken

### ISSUE THREAD

**Issue by ryao** [Winetricks/winetricks#1121]
When helping out my cousin setup Age of Empires III on his new Linux installation, I discovered that the protontricks compatibility fix for it are broken. Steam did not like the 32-bit prefix and the 32-bit prefix itself is entirely unnecessary, as I had installed it in a 64-bit prefix using proton tricks:

https://github.com/ValveSoftware/Proton/issues/17#issuecomment-423592026

I don't have time to test out ideas to fix the protontricks script until the weekend, but I wanted to report this sooner rather than later.

Edit: To be clear, he was using Proton 3.7-8.

**Comment by austin987** [comment]
I'm not sure how this is a winetricks issue, afaict protontricks isn't using winetricks to install AoE III (after all, winetricks only supports the trial, not the full version).

What is the problem in winetricks here?

**Comment by ryao** [comment]
@austin987 The game crashes with the current workarounds. I used protontricks to fix the proton prefix manually using the commands that I posted on the Proton issue tracker in the past. I did not use winetricks to try to install it.

**Comment by ryao** [comment]
@austin987 I just realized that I posted this issue to the wrong tracker. I meant for it to go on the protonfixes tracker. Sorry about that.
