### ISSUE TITLE
Rise of Nations needs SkipIntroMovies=1 in rise2.ini

### ISSUE THREAD

**Issue by ryao** [Winetricks/winetricks#1122]
When installing Rise of Nations: Extended Edition on my cousin's new Linux installation via Steam Family Sharing, I noticed that Rise of Nations has some introduction movies that are not playing, which causes a long pause at start with a black screen.

Rather than fix the introduction movies, it is possible to disable them entirely by putting SkipIntroMovies=1 `~/.local/share/Steam/steamapps/compatdata/287450/pfx/drive_c/users/steamuser/Application Data/Microsoft Games/Rise of Nations/rise2.ini`. That file won't exist until first run, but in theory, the game should add any missing entries during first run, so it should be okay to create with just SkipIntroMovies=1 in it. This of course needs testing.

I don't have time to test out ideas to fix the protontricks script until the weekend, but I wanted to report this sooner rather than later.

**Comment by austin987** [comment]
Again, not sure how this is a winetricks issue. Winetricks has Rise of Nations Demo, but not Rise of Nations: Extended Edition.

I think this belongs in protontricks.

**Comment by ryao** [comment]
I thought I had been posting this to the protonfixes tracker. Sorry for the mixup.

**Comment by austin987** [comment]
No worries.
