### ISSUE TITLE
dotnet462 fails - sha256 mismatch on dotNetFx462_Full_x86_x64_Slim.exe

### ISSUE THREAD

**Issue by nl255** [Winetricks/winetricks#1124]
Attempting to install dotnet462 will immediately fail with the error 

> sha256sum mismatch! Rename /home/user1/.cache/winetricks/dotnet462/dotNetFx462_Full_x86_x64_Slim.exe and try again.

**Comment by jvandrew** [comment]
I have the same issue. I've updated winetricks and it does not solve the issue.

**Comment by austin987** [comment]
I was afraid this would happen. This is why I didn't want to put a dropbox link in...

In theory we can just use the official installer now, though that will support less wine versions (and I'll need to narrow down where it works.

**Comment by austin987** [comment]
Those affected can try https://github.com/austin987/winetricks/commit/24ec901cd81fc6c3c23192a4fe5515c33d060b6b; if it fails, please list your wine version (but note I probably can't do much other than block it from installing there)

**Comment by RoadTrain** [comment]
austin987@24ec901 worked for me.

**Comment by RoadTrain** [comment]
@austin987 Will you pull it to master?

**Comment by austin987** [comment]
Yes; sometime this week. Thanks for testing.

**Comment by michuvon** [comment]
I also have this same problem..
`Checksum for /home/user/.cache/winetricks/dotnet462/dotNetFx462_Full_x86_x64_Slim.exe did not match, retrying download
------------------------------------------------------
Executing cd /home/user/.cache/winetricks/dotnet462
Downloading https://web.archive.org/web/2000/https://www.dropbox.com/s/1bdocgbate8hc8z/dotNetFx462_Full_x86_x64_Slim.exe?dl=1 to /home/user/.cache/winetricks/dotnet462
--2018-11-17 16:57:46--  https://web.archive.org/web/2000/https://www.dropbox.com/s/1bdocgbate8hc8z/dotNetFx462_Full_x86_x64_Slim.exe?dl=1
Resolving web.archive.org (web.archive.org)... 207.241.224.26
Connecting to web.archive.org (web.archive.org)|207.241.224.26|:443... connected.
HTTP request sent, awaiting response... 403 FORBIDDEN
2018-11-17 16:57:48 ERROR 403: FORBIDDEN.

------------------------------------------------------
Downloading https://web.archive.org/web/2000/https://www.dropbox.com/s/1bdocgbate8hc8z/dotNetFx462_Full_x86_x64_Slim.exe?dl=1 failed
`
but..  ..what I'm I supposed to do? (I newly came over from OS X and have never used GitHub and Wine so far.) (I'm on Ubuntu 18.04)

**Comment by michuvon** [comment]
I also have this same problem..

<pre>Checksum for /home/michael/.cache/winetricks/dotnet462/dotNetFx462_Full_x86_x64_Slim.exe did not match, retrying download
------------------------------------------------------
Executing cd /home/michael/.cache/winetricks/dotnet462
Downloading https://web.archive.org/web/2000/https://www.dropbox.com/s/1bdocgbate8hc8z/dotNetFx462_Full_x86_x64_Slim.exe?dl=1 to /home/michael/.cache/winetricks/dotnet462
--2018-11-17 16:57:46--  https://web.archive.org/web/2000/https://www.dropbox.com/s/1bdocgbate8hc8z/dotNetFx462_Full_x86_x64_Slim.exe?dl=1
Resolving web.archive.org (web.archive.org)... 207.241.224.26
Connecting to web.archive.org (web.archive.org)|207.241.224.26|:443... connected.
HTTP request sent, awaiting response... 403 FORBIDDEN
2018-11-17 16:57:48 ERROR 403: FORBIDDEN.

------------------------------------------------------
Downloading https://web.archive.org/web/2000/https://www.dropbox.com/s/1bdocgbate8hc8z/dotNetFx462_Full_x86_x64_Slim.exe?dl=1 failed
------------------------------------------------------
</pre>

but..  ..what I'm I supposed to do? (I newly came over from OS X and have never used GitHub and Wine so far.) (I'm on Ubuntu 18.04)

**Comment by RoadTrain** [comment]
@michuvon use the patched version:
`cd ~/Downloads
wget https://raw.githubusercontent.com/austin987/winetricks/dotnet462-noslim/src/winetricks
chmod +x winetricks`

**Comment by galvarez3d** [comment]
What seems to get pass that for me (MacOS 10.12.6, brew installed wine: stable 3.0.3 (bottled), HEAD) is to get the patched winetricks but also place the .net installer manually:

First:
cd ~/Downloads
wget https://raw.githubusercontent.com/austin987/winetricks/dotnet462-noslim/src/winetricks
chmod +x winetricks
sudo mv -v winetricks /usr/local/bin

And then:
cd /Users/gerardoalvarezleon/.cache/winetricks/dotnet462
wget https://www.dropbox.com/s/1bdocgbate8hc8z/dotNetFx462_Full_x86_x64_Slim.exe

And last:
cd
env WINEPREFIX=$HOME/winedotnet462 /usr/local/bin/winetricks --unattended dotnet462 corefonts

At least this way it has started installing, will let you know how it goes

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/02fd7301034a82c4554cace9b02fe0f935c56b0b
