### ISSUE TITLE
Failed to install flash in winehq staging 3.19

### ISSUE THREAD

**Issue by Nick-Alam** [Winetricks/winetricks#1127]
input : `WINEARCH=win32 WINEPREFIX=~/.wine/wine32 LC_ALL=zh_CN.utf8 winetricks flash `
output : `Note: command wine flashplayer29_0r0_171_winax.exe returned status 235. Aborting`
Then winetricks opened winebrowser to address `https://www.flash.cn/?activex&source=2680`

**Comment by austin987** [comment]
I can't reproduce this in wine-3.19 / wine-staging-3.19 (with en_US.utf8).

Does this only occur with a Chinese locale? I don't have Chinese support installed, so I can't test. Based on the link you posted, it sounds like Chinese locales need to use a different installer.

**Comment by Axen1314** [comment]
Open the folder`/home/[user]/.cache/winetricks/flash`;
Find the  `fp_xxxxxx_archive.zip`and unzip it,  you can find all flash installers.
There are two kinds of WIndows installers: `xxxxx.msi` and `xxxxx.exe`，choose the `xxxxx.msi`
Run the Windows installer with the following command:
`wine msiexec \i xxxxx.msi`.

**Comment by austin987** [comment]
Flash is no longer supported.
