### ISSUE TITLE
Installing dotnet462 fails (404)

### ISSUE THREAD

**Issue by nsrosenqvist** [Winetricks/winetricks#1143]
The file is removed from the wayback machine and I had to find the file hosted on dropbox manually and add it to the .cache folder

**Comment by ShannonVanWagner** [comment]
Are you using the latest winetricks from the link below?
https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

The dotnet462 verb has a working URL in the newer version there. See the line below or search the script for dotnet462 for example:
https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L8157

**Comment by nsrosenqvist** [comment]
I first installed it from Ubuntu repos, when it didn't work I ran the script in the README to install from master but perhaps something went wrong overwriting the executable. That URL in the source is correct, so it should probably be fixed in master then
