### ISSUE TITLE
psdkwin71 can't install because dotnet40 hangs on install

### ISSUE THREAD

**Issue by ShannonVanWagner** [Winetricks/winetricks#1144]
dotnet40 install gets stuck.. see
https://bugs.winehq.org/show_bug.cgi?id=46227
Microsoft .NET 4 Framework: fails to install (hangs) 32-bit WINEPREFIX

UPDATE: Hmm.. dotnet40 will install all by itself. Looking for other issue.

**Comment by ShannonVanWagner** [comment]
Hmm.. dotnet40 will install all by itself. Looking for other issue.

**Comment by ShannonVanWagner** [comment]
Seems I have old wine too... Anyone have a cheat sheet for installing latest wine on Ubuntu 18.04?
I have the source cloned with git but the ole wine-deps script doesn't work with this distro apparently.
https://github.com/dankegel/winezeug/blob/master/install-wine-deps.sh

**Comment by gverm** [comment]
@ShannonVanWagner Take a look at the wine wiki. Instructions for ubuntu can be found [here.](https://wiki.winehq.org/Ubuntu)

**Comment by austin987** [comment]
The upstream bug was resolved invalid, assuming this is as well. Reopen if not.
