### ISSUE TITLE
dotnet30 installation still fails with status 8

### ISSUE THREAD

**Issue by lucmp** [Winetricks/winetricks#1145]
I am running Wine Staging 3.21.0 and I have this problem when trying to install dotnet with winetricks:

Note: command wget -q -O - http://ipinfo.io/Executing wget -q -O - http://ipinfo.io/ip
[MY_ACTUAL_IP] returned status 8. Aborting.

The problem is VERY OLD and has been reported here, but there is this weird, confusing culture in Linux communities that frowns upon reopening old issues even if they're still pending, they're still the same and they're still relevant, because blindly hating everything that's old is a strict requirement for anyone who wants to use computer technology. So I brought it up in one of the old threads but was told not to do it because the issue is "closed" although it's still very there although no solution is there at all as Google can attest. So here I am opening yet another issue when the exact same issue has been reported before and my comments could simply be added to them since it is for-crying-out-loud the same.

I was also told to "run with --country=unknown" whatever that means. I just did what I think that means and this is the result:

    $ winetricks --gui --country=unknown
    unknown option --country=unknown
    $ winetricks --country=unknown
    unknown option --country=unknown

I believe the problem might be outdated download URIs:

    $ set env WINEPREFIX ~/wine32
    $ winetricks dotnet35
    ------------------------------------------------------
    You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
    ------------------------------------------------------
    Using winetricks 20170101 - sha1sum: ed7e0c2cbdfc606aeb5d0e381c0d9eb97eda7e2b with wine-3.21 (Staging) and WINEARCH=win64
    Executing w_do_call dotnet35
    Executing load_dotnet35 
    ------------------------------------------------------
    dotnet35 does not yet fully work or install on wine.  Caveat emptor.
    ------------------------------------------------------
    Executing mkdir -p /home/wnix/.cache/winetricks/dotnet35
    Executing cd /home/wnix/.cache/winetricks/dotnet35
    Downloading http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe to /home/wnix/.cache/winetricks/dotnet35
    --2018-12-03 10:07:27--  http://download.microsoft.com/download/6/0/f/60fc5854-3cb8-4892-b6db-bd4f42510f28/dotnetfx35.exe
    Resolving download.microsoft.com (download.microsoft.com)... 23.214.204.201
    Connecting to download.microsoft.com (download.microsoft.com)|23.214.204.201|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 206692864 (197M) [application/octet-stream]
    Saving to: \u2018dotnetfx35.exe\u2019
    
    dotnetfx35.exe                              100%[=========================================================================================>] 197.12M  1.55MB/s    in 2m 0s   
    
    2018-12-03 10:09:28 (1.64 MB/s) - \u2018dotnetfx35.exe\u2019 saved [206692864/206692864]
    
    Executing cd /home/wnix
    Executing w_do_call remove_mono
    Executing load_remove_mono 
    000b:fixme:winediag:start_process Wine Staging 3.21 is a testing version containing experimental patches.
    000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
    000f:fixme:service:scmdatabase_autostart_services Auto-start service L"iqoptionupdater" failed to start: 2
    ------------------------------------------------------
    Mono does not appear to be installed.
    ------------------------------------------------------
    Executing w_do_call dotnet30sp1
    Executing load_dotnet30sp1 
    Executing mkdir -p /home/wnix/.cache/winetricks/dotnet30sp1
    Executing cd /home/wnix/.cache/winetricks/dotnet30sp1
    Downloading http://download.microsoft.com/download/8/F/E/8FEEE89D-9E4F-4BA3-993E-0FFEA8E21E1B/NetFx30SP1_x86.exe to /home/wnix/.cache/winetricks/dotnet30sp1
    --2018-12-03 10:09:32--  http://download.microsoft.com/download/8/F/E/8FEEE89D-9E4F-4BA3-993E-0FFEA8E21E1B/NetFx30SP1_x86.exe
    Resolving download.microsoft.com (download.microsoft.com)... 23.214.204.201
    Connecting to download.microsoft.com (download.microsoft.com)|23.214.204.201|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 26253832 (25M) [application/octet-stream]
    Saving to: \u2018NetFx30SP1_x86.exe\u2019
    
    NetFx30SP1_x86.exe                          100%[=========================================================================================>]  25.04M  1.79MB/s    in 14s     
    
    2018-12-03 10:09:47 (1.77 MB/s) - \u2018NetFx30SP1_x86.exe\u2019 saved [26253832/26253832]
    
    Executing cd /home/wnix
    Executing cd /home/wnix/.cache/winetricks/dotnet30sp1
    Downloading http://download.microsoft.com/download/2/5/2/2526f55d-32bc-410f-be18-164ba67ae07d/XPSEP%20XP%20and%20Server%202003%2032%20bit.msi to /home/wnix/.cache/winetricks/dotnet30sp1
    --2018-12-03 10:09:47--  http://download.microsoft.com/download/2/5/2/2526f55d-32bc-410f-be18-164ba67ae07d/XPSEP%20XP%20and%20Server%202003%2032%20bit.msi
    Resolving download.microsoft.com (download.microsoft.com)... 23.214.204.201
    Connecting to download.microsoft.com (download.microsoft.com)|23.214.204.201|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 7839232 (7.5M) [application/octet-stream]
    Saving to: \u2018XPSEP XP and Server 2003 32 bit.msi\u2019
    
    XPSEP XP and Server 2003 32 bit.msi         100%[=========================================================================================>]   7.48M  1.74MB/s    in 4.4s    
    
    2018-12-03 10:09:51 (1.68 MB/s) - \u2018XPSEP XP and Server 2003 32 bit.msi\u2019 saved [7839232/7839232]
    
    Executing cd /home/wnix
    Executing w_do_call remove_mono
    Executing load_remove_mono 
    000b:fixme:winediag:start_process Wine Staging 3.21 is a testing version containing experimental patches.
    000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
    000f:fixme:service:scmdatabase_autostart_services Auto-start service L"iqoptionupdater" failed to start: 2
    ------------------------------------------------------
    Mono does not appear to be installed.
    ------------------------------------------------------
    Executing w_do_call dotnet30
    Executing load_dotnet30 
    Executing mkdir -p /home/wnix/.cache/winetricks/dotnet30
    Executing cd /home/wnix/.cache/winetricks/dotnet30
    Downloading http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe to /home/wnix/.cache/winetricks/dotnet30
    --2018-12-03 10:09:54--  http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
    Resolving download.microsoft.com (download.microsoft.com)... 23.214.204.201
    Connecting to download.microsoft.com (download.microsoft.com)|23.214.204.201|:80... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2018-12-03 10:09:54 ERROR 404: Not Found.
    
    Executing cd /home/wnix/.cache/winetricks/dotnet30
    Downloading https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe to /home/wnix/.cache/winetricks/dotnet30
    --2018-12-03 10:09:54--  https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
    Resolving web.archive.org (web.archive.org)... 207.241.224.26
    Connecting to web.archive.org (web.archive.org)|207.241.224.26|:443... connected.
    HTTP request sent, awaiting response... 302 FOUND
    Location: https://web.archive.org/web/20180413015051/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe [following]
    --2018-12-03 10:09:55--  https://web.archive.org/web/20180413015051/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
    Reusing existing connection to web.archive.org:443.
    HTTP request sent, awaiting response... 404 Not Found
    2018-12-03 10:09:56 ERROR 404: Not Found.
    
    ------------------------------------------------------
    Downloading https://web.archive.org/web/http://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe failed
    ------------------------------------------------------

Is there a solution to this ancient problem somewhere? Apparently, old threads are anathema but old bugs are not.

Thank you for your attention.

**Comment by lucmp** [comment]
It's what Debian distributes as current.

**Comment by gverm** [comment]
@lucmp You could either contact the Debian maintainer and ask them to update the package or use the info in the README.

**Comment by austin987** [comment]
Or get it from Buster/Stretch:
https://packages.debian.org/buster/winetricks
