### ISSUE TITLE
Completions fetching country codes on every invocation

### ISSUE THREAD

**Issue by anowlcalledjosh** [Winetricks/winetricks#1149]
Is there any particular reason the completions fetch a list of ISO country codes from the internet every time they're sourced? Presumably the list of valid country codes doesn't change *that* often – couldn't you just update the completions if a new country appears? I suspect most users don't expect their completions to download a file from the internet (potentially taking up to 30 seconds!) every time they open a shell...

https://github.com/Winetricks/winetricks/blob/af538d663a177007f72e199b3152790923dd2f63/src/winetricks.bash-completion#L262-L277

**Comment by bobwya** [comment]
Yeah, I wasn't very happy with that hack either... I'll strip it out in a Pull request. It would be easier just to update the static value in the script... E.g. once countries start flooding out of existence, etc.
