### ISSUE TITLE
Xact broken, possible every verb extracting directx_jun2010

### ISSUE THREAD

**Issue by MagicRB** [Winetricks/winetricks#1152]
I have noticed that xact will fail like this 

`------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
Your version of wine tkg-fo4-3.21-1-gc5dedc1 is no longer supported upstream. You should upgrade to 3.x
------------------------------------------------------
Using winetricks 20181203-next - sha256sum: 749fcd145eb04a05ccb3fda2af91dc31e0663f503f675bf43499d6b3b63cab6e with tkg-fo4-3.21-1-gc5dedc1 ( Staging Esync ) and WINEARCH=win64
Executing w_do_call xact
Executing load_xact 
Executing cabextract -q -d /Fallout4/dosdevices/c:/windows/temp/_xact -L -F *_xact_*x86* /.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /Fallout4/dosdevices/c:/windows/temp/_xact -L -F *_x3daudio_*x86* /.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /Fallout4/dosdevices/c:/windows/temp/_xact -L -F *_xaudio_*x86* /.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /Fallout4/dosdevices/c:/windows/syswow64 -L -F xactengine*.dll /Fallout4/dosdevices/c:/windows/temp/_xact/apr2006_xact_x86.cab
/Fallout4/dosdevices/c:/windows/temp/_xact/apr2006_xact_x86.cab: WARNING; file possibly truncated by 1208291 bytes.
/Fallout4/dosdevices/c:/windows/temp/_xact/apr2006_xact_x86.cab: no valid cabinets found
------------------------------------------------------
Note: command cabextract -q -d /Fallout4/dosdevices/c:/windows/syswow64 -L -F xactengine*.dll /Fallout4/dosdevices/c:/windows/temp/_xact/apr2006_xact_x86.cab returned status 1. Aborting.
------------------------------------------------------
` something similar happens when I tried installing another verb related to directx_jun2010. My current theory is that Microsoft changed the installer on their webpage. I have tested this on Arch and Debian, I tested it with winetricks, 20181203-next, on Debian, and I tried to directly run the command that fails on Arch to see if perhaps cabextract is botched on Debian. I have exhausted all my know-how and I don't really know what to do next. If you guys need any more information, I'll gladly provide.

**Comment by Chiitoo** [comment]
Which version of 'cabextract' are you using?

Most likely same issue as here: https://github.com/Winetricks/winetricks/issues/1120

**Comment by MagicRB** [comment]
1.9

**Comment by MagicRB** [comment]
I tried 1.6 from Debian's repositories. same issue

**Comment by MagicRB** [comment]
maybe specifically Debian's cabextract is broken?

**Comment by MagicRB** [comment]
yup, just copied over from arch....

**Comment by MagicRB** [comment]
I'm closing this as this is not a problem caused by winetricks, tho warning Debian users of this would be good, maybe in the FAQ?
