### ISSUE TITLE
Don't remove mscoree.dll if another dotnet package is already installed.

### ISSUE THREAD

**Issue by ShapeShifter499** [Winetricks/winetricks#1167]
I'm coming across this issue. If I installed dotnet20 then later install something newer like dotnet45 I get the below errors. It seems that winetricks is setup to remove mono if you try to install any dotnet package. But since mscoree.dll can come from mono and dotnet, winetricks ends up removing the wrong version of mscoree.dll. Winetricks should not try to remove mscoree.dll if another dotnet package is already installed.

Seems to be related to this change: https://github.com/Winetricks/winetricks/issues/972  https://github.com/Winetricks/winetricks/pull/976

I'm able to fix this by running the "dotnetfx_cleanup_tool" (https://blogs.msdn.microsoft.com/astebner/2008/08/28/net-framework-cleanup-tool-users-guide/) and reinstalling dotnet20 with winetricks. If I want dotnet40 or newer and dotnet20 I have to manually install dotnet40 without winetricks.

```
000b:fixme:winediag:start_process Wine Staging 4.0-rc7 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
0014:err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscorsvw.exe") not found
0014:err:module:LdrInitializeThunk Importing dlls for L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"clr_optimization_v4.0.30319_32" failed to start: 1053
0016:err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
0016:err:module:LdrInitializeThunk Importing dlls for L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
```

**Comment by austin987** [comment]
Hi @ShapeShifter499,

Sorry about that. Looking at that code again, I definitely meant to bail out if it wasn't mono, but evidently didn't do that. Can you try https://github.com/austin987/winetricks/blob/remove-mono/src/winetricks please?

Also, does it make a difference if you use a 32-bit prefix (and/or vanilla wine)?

**Comment by austin987** [comment]
Hopefully fixed by https://github.com/Winetricks/winetricks/commit/b1fd81d5115ad17da2504c746d82e6ac1bc87211; let me know if it's not.
