### ISSUE TITLE
Installing Allfonts  sha1=256sum mismatch

### ISSUE THREAD

**Issue by Verontrix** [Winetricks/winetricks#1173]
I am trying to install winetricks All Font packages. However every time I try I receive this error:

`winetricks allfonts
Using winetricks 20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924 with wine-4.0 and WINEARCH=win32
Executing w_do_call allfonts
Executing load_allfonts 
Executing w_do_call baekmuk
baekmuk already installed, skipping
Executing w_do_call calibri
Executing load_calibri 
Executing cd /home/verontrix/.cache/winetricks/PowerPointViewer
Downloading https://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe to /home/verontrix/.cache/winetricks/PowerPointViewer
--2019-02-02 12:38:10--  https://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe
Resolving download.microsoft.com (download.microsoft.com)... 23.43.240.195, 2001:428:3801:6aa::e59, 2001:428:3801:686::e59
Connecting to download.microsoft.com (download.microsoft.com)|23.43.240.195|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-02 12:38:10 ERROR 404: Not Found.

Executing cd /home/verontrix/.cache/winetricks/PowerPointViewer
Downloading https://web.archive.org/web/2000/https://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe to /home/verontrix/.cache/winetricks/PowerPointViewer
--2019-02-02 12:38:11--  https://web.archive.org/web/2000/https://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe
Resolving web.archive.org (web.archive.org)... 207.241.233.214
Connecting to web.archive.org (web.archive.org)|207.241.233.214|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://web.archive.org/web/20101225094622/http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe [following]
--2019-02-02 12:38:11--  https://web.archive.org/web/20101225094622/http://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe
Reusing existing connection to web.archive.org:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘PowerPointViewer.exe’

PowerPointViewer.     [    <=>     ]  60.28M  2.67MB/s    in 27s     

2019-02-02 12:38:38 (2.26 MB/s) - ‘PowerPointViewer.exe’ saved [63204984]

Executing cd /home/verontrix/.cache/winetricks/PowerPointViewer
------------------------------------------------------
sha256sum mismatch! Rename /home/verontrix/.cache/winetricks/PowerPointViewer/PowerPointViewer.exe and try again.`

I am using the winetricks from the 18.4 ubuntu repo.
The current version is 20180217 -sha256sum: 1b15c616174f41df79d72a90c52eb2b1

**Comment by austin987** [comment]
You should file a bug with Ubuntu to update winetricks (and/or get a newer version yourself manually); this was fixed in May by 76f5fdf0
