### ISSUE TITLE
vcrun2008 aborting with error code 5.

### ISSUE THREAD

**Issue by mallgrab** [Winetricks/winetricks#1180]
`Note: command 'wine vcredist_x86.exe' returned status 5.  Aborting.`

Will not install if Windows Version isn't set to Windows XP.

**Comment by austin987** [comment]
I can't reproduce this with `Using winetricks 20181203-next - sha256sum: fe47f162a523433d19bd58ef66ced97cb5c9d6c3ba1340c03e6910b93f8c1e06 with wine-3.14-214-g96a6053fed and WINEARCH=win32`

`wineserver -k ; rm -rf ~/.wine ; winetricks -q win7 ; wineserver -w ; winetricks  vcrun2008`

Do you have instructions to reproduce?

**Comment by accela** [comment]
I also got hit by this, wine-4.2, wine-staging-4.2, wine-git (last night) in both win32 and win64, all give

`004b:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x4553b6
Note: command wine vcredist_x86.exe returned status 5. Aborting.`

Going back to wine-4.1 seems to install just fine. All tried with clean prefixes as win7.

**Comment by austin987** [comment]
I can't reproduce this in wine-4.2 or wine-4.2-118-g812d03129d. Sounds like a wine regression, in any case. If you can build wine, a regression test would be useful (but ultimately, this should be reported at https://bugs.winehq.org).

**Comment by accela** [comment]
whatever regression it was, seems to work fine again with wine-4.3 and vcrun2008 installs as usual.
