### ISSUE TITLE
Internet Explorer 7 - w_metadata dxsdk_nov2006 corrupt, might need forward slashes?

### ISSUE THREAD

**Issue by tapwag** [Winetricks/winetricks#1185]
Hello everyone,

I am running openSUSE "Tumbleweed" and tried the following. Could you take a look into this please?

mwagner@localhost:~$ winetricks ie7
Using winetricks 20181203 - sha256sum: 2e32c987b5dd0ddd3e0836290d9561e7f251ca080248f53050cc84c27d4bbd18 with wine-4.1 and WINEARCH=win32
installed_file1="C:\Program Files
------------------------------------------------------
bug: w_metadata dxsdk_nov2006 corrupt, might need forward slashes?
------------------------------------------------------

**Comment by austin987** [comment]
Works fine for me. Two things:
A) Just be certain, can you download a fresh copy of winetricks and try? I.e.,:
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks && sh winetricks ie7
B) If that also fails, run with -v and attach the log, please.

**Comment by tapwag** [comment]
Also works fine for me with the command you have indicated… Bug can be closed as Invalid.
