### ISSUE TITLE
Please update faudio verb to latest please

### ISSUE THREAD

**Issue by lemonzest79** [Winetricks/winetricks#1189]
Just noticed this is pulling a version from 17th of Jan 2019, the latest is 19.03 released 1st March 2019, noticed this when I did a fresh install of a new prefix earlier, could this be fixed please?

**Comment by austin987** [comment]
Here you go:
https://github.com/Winetricks/winetricks/commit/ce3e2413724d5b6505fc96c696356c899a4016b2

it's now like dxvk, 'winetricks faudio' will get the latest release, or you can use faudio1901/faudio1902/faudio1903/faudio1904 to get a specific version.

**Comment by lemonzest79** [comment]
Many thanks :)
