### ISSUE TITLE
Would like a verb to install peverify

### ISSUE THREAD

**Issue by i30817** [Winetricks/winetricks#1197]
The mono version apparently can't verify any dll from unity games and the windows one is buried somewhere in the depths of the windows sdk.

**Comment by austin987** [comment]
Looks like it's part of the dotnet20sdk, which would mean you'd have to download ~350MB

**Comment by i30817** [comment]
I tried to install it that way but only got the dll but not the executable, but maybe i'm missing something.

PEVerify is a nightmare to install in linux because it's aways bundled with the sdk or visual studio, which either don't install, are web apps that don't install or the above happens.

**Comment by i30817** [comment]
I opened a issue on mono in the hope they can help make this work on their version of peverify, but i'm not very hopeful because it appears that that version of System.Core isn't supported on purpose (it's apparently the first silverlight version, even if the game(s) don't actually use it).

**Comment by austin987** [comment]
@i30817 please give this branch a try:
https://github.com/austin987/winetricks/tree/peverify

**Comment by i30817** [comment]
Worked, even if (as usual) running a c# executable produces a lot of logger trash after the program finishes because it insists in creating a 'optimizer' process.

**Comment by i30817** [comment]
Though i think it broke my already-installed-dotnet461 prefix, oh well, i just need to remember to keep them separate.

**Comment by austin987** [comment]
Yeah, I'm not sure of the best way to handle this. I've never used this tool, but I assume it should work with dotnet20+? If so, we could see if something >=dotnet20 is installed, and if not, install dotnet20. What do you think?

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/e3961e2cdbd55805e5520c5f4010bcc74f58e6d3
