### ISSUE TITLE
Update to DXVK 1.0.2 release

### ISSUE THREAD

**Issue by lemonzest79** [Winetricks/winetricks#1200]
Hi

As title, the standard winetricks dxvk is not fetching the new release.

Many Thanks

**Comment by bobwya** [comment]
This is an Upstream problem.

The release tag file:  [RELEASE](https://github.com/doitsujin/dxvk/blob/master/RELEASE)  ; hasn't been updated by Philip Rebohle:

In fact none of the version tags, scattered throughout the project have been updated. This applies  throughout the project... They're all still stuck on **1.0.1**

So you should be filing an issue on:  [dxvk: Issues](https://github.com/doitsujin/dxvk/issues)  ; if you want this problem fixed.

**Comment by gverm** [comment]
@bobwya As far as I can see, it is updated on the release-1.0 branch.
See [here.](https://github.com/doitsujin/dxvk/blob/release-1.0/RELEASE)
