### ISSUE TITLE
galliumnine - Download broken while using aria2c

### ISSUE THREAD

**Issue by varris1** [Winetricks/winetricks#1207]
winetricks version: 20190310-next - sha256sum: 908b1820d942393c188e4a714478b43f2d61f8ff8f914dcc0ee582a575241e56
[winetricks output](https://github.com/Winetricks/winetricks/files/3063504/output.log)

While winetricks is using aria2c, downloading gallium nine is broken because aria2c tries to download g9 standalone from: `https://github.com/iXit/wine-nine-standalone/releases/download/https://api.github.com/repos/iXit/wine-nine-standalone/releases/16375260/gallium-nine-standalone-https://api.github.com/repos/iXit/wine-nine-standalone/releases/16375260.tar.gz
`

Using wget seems to work fine.

**Comment by austin987** [comment]
Looks like an aria2c bug; it corrupts the release.json when it downloads. I tested downloading it manually with aria2c/curl/wget; curl/wget match, aria2c doesn't:

```
austin@laptop:/tmp/tmp.3EPAPPKzKn$ sha256sum *
393191249b9eb6fc60d63cc3f2a78b013b3c2ec23167ea7c0ffa902cbc2482b3  aria2c
11dd932af3e03e36745e99bc6639c625e7e83a8ab68a2bcb1e2346ce0efe1c95  curl
11dd932af3e03e36745e99bc6639c625e7e83a8ab68a2bcb1e2346ce0efe1c95  wget
```

I'd suggest filing a bug with them, as there's not much I can do (other than maybe warn that it's broken). Their tracker is at https://github.com/aria2/aria2/issues

**Comment by austin987** [comment]
Actually, it doesn't corrupt it, it compresses the json, whereas wget/curl leave it as is. The current code assumes it isn't compressed.

Ideally aria2c wouldn't do that, but the code could probably be refactored to handle that.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/ef270d9769d3dbe130c102e81e091dd64bccce4e
