### ISSUE TITLE
msxml6 service pack 2 support

### ISSUE THREAD

**Issue by Jaystified** [Winetricks/winetricks#1219]
AFAIK, winetricks offers msxml6, but not msxml6sp2

From a cursory investigation earlier, it seems sp2 might be necessary for getting some MS Office applications to work, but installing it is not straightforward (attempting to do so results in an "Installation Interrupted" type error)

**Comment by austin987** [comment]
What bug does it workaround? Is there a free download this helps with?

`cabextract` can extract the exe and inner msi from https://www.microsoft.com/en-us/download/details.aspx?id=9774, so that may be a feasible path.

**Comment by tbussmann** [comment]
The new download URL does give a 404 for me, despite the download is linked from https://support.microsoft.com/en-us/help/973686/description-of-an-update-for-msxml-core-services-6-0-service-pack-2 - is there any alternative source available? MSXML6SP1 seem to download still fine.
