### ISSUE TITLE
D9VK support

### ISSUE THREAD

**Issue by t14462** [Winetricks/winetricks#1220]
D9VK is based on DXVK and now it works fine.

Stuttering in Fallout New Vegas lower than on Gallium-Nine, and D9VK supports DX9 for WPF apps (if d3dcompiler installed)

But building it as winelib causing problems such a crashes of launcher-configators of Bethesda games.

So please, add D9VK option to winetricks

**Comment by mozo78** [comment]
It would be great!

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/91911c70bf9abced8959e87947e48eee98fad6e3
https://github.com/Winetricks/winetricks/commit/644a72001c4ee921d3b61604518c51a2f74c3cb6
https://github.com/Winetricks/winetricks/commit/05dbc02cdad4a7c07304670a671b3ff3e9bad70a
https://github.com/Winetricks/winetricks/commit/05dbc02cdad4a7c07304670a671b3ff3e9bad70a
