### ISSUE TITLE
Kenton Spin Doctor Editor need msvcrt40.dll with mfc40.dll

### ISSUE THREAD

**Issue by bda65** [Winetricks/winetricks#1229]
Hi,

Some software like the Kenton Spin Doctor Editor ([https://www.kentonuk.com/downloads/cf_editors.shtml](https://www.kentonuk.com/downloads/cf_editors.shtml)) needs msvcrt40.dll.
Described here: [https://forum.winehq.org/viewtopic.php?f=8&t=32396](https://forum.winehq.org/viewtopic.php?f=8&t=32396)
After registering manually mfc40 and msvcrt40, the software work perfectly.
Please re-add it to mfc40 verb or add another verb specifically for msvcrt40.

**Comment by austin987** [comment]
Does this work for you?
https://github.com/austin987/winetricks/commit/425600dfeb5e025bb7c809b90986dd5f10e9f04f

**Comment by bda65** [comment]
No. Apparently the mfc40.dll downloaded is not working. 
wine regsrv32.exe /i mfc40.dll report  "unable to load the dll".
This error appear when installing the Spin Doctor Editor:
002e:err:module:import_dll Loading library MFC40.DLL (which is needed by L"C:\\Program Files\\Common Files\\VCS\\VSLIDE32.OCX") failed (error c000012f).

**Comment by austin987** [comment]
Are you running `winetricks msvcrt40` or `winetricks mfc40`? You'll need to run mfc40, which also includes msvcrt40 (if using that branch I gave you).

I can reproduce what you're seeing, but only if I instlal msvcrt40. Installing mfc40 works fine. After that, the app starts fine.

**Comment by bda65** [comment]
No, it's with winetricks mfc40:
Creating a new, fresh wine config:

`WINEARCH=win32 WINEPREFIX=~/.wine32 winecfg
wine: created the configuration directory '/home/bruno/.wine32'
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
0019:err:mscoree:LoadLibraryShim error reading registry key for installroot
0019:err:mscoree:LoadLibraryShim error reading registry key for installroot
0019:err:mscoree:LoadLibraryShim error reading registry key for installroot
0019:err:mscoree:LoadLibraryShim error reading registry key for installroot
wine: configuration in '/home/bruno/.wine32' has been updated. `

Installing mfc40 with your patch:
`WINEARCH=win32 WINEPREFIX=~/.wine32 ./winetricks mfc40
Using winetricks 20190310-next - sha256sum: 3458374590f63b711081751217b94a4a66a5ec2bdfc0d82759a48b2af3ee3542 with wine-4.2 (Debian 4.2-4+b1) and WINEARCH=win32
Executing w_do_call mfc40
Executing load_mfc40
Executing cabextract -q -d /home/bruno/.wine32/dosdevices/c:/windows/temp/_mfc40 -L -F x86_microsoft-windows-mfc40_31bf3856ad364e35_6.1.7601.17514_none_5c06580240091047/mfc40.dll /ho
me/bruno/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe
Executing cp /home/bruno/.wine32/dosdevices/c:/windows/temp/_mfc40/x86_microsoft-windows-mfc40_31bf3856ad364e35_6.1.7601.17514_none_5c06580240091047/mfc40.dll /home/bruno/.wine32/dos
devices/c:/windows/system32/mfc40.dll
Executing cabextract -q -d /home/bruno/.wine32/dosdevices/c:/windows/temp/_mfc40 -L -F x86_microsoft-windows-mfc40u_31bf3856ad364e35_6.1.7601.17514_none_f51a7bf0b3d25294/mfc40u.dll /
home/bruno/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe
Executing cp /home/bruno/.wine32/dosdevices/c:/windows/temp/_mfc40/x86_microsoft-windows-mfc40u_31bf3856ad364e35_6.1.7601.17514_none_f51a7bf0b3d25294/mfc40u.dll /home/bruno/.wine32/d
osdevices/c:/windows/system32/mfc40u.dll
Executing w_do_call msvcrt40
Executing load_msvcrt40
Executing cabextract -q -d /home/bruno/.wine32/dosdevices/c:/windows/temp/_msvcrt40 -L -F i386/msvcrt40.dl_ /home/bruno/.cache/winetricks/winxpsp3/WindowsXP-KB936929-SP3-x86-ENU.exe
Executing cabextract -q --directory=/home/bruno/.wine32/dosdevices/c:/windows/system32 /home/bruno/.wine32/dosdevices/c:/windows/temp/_msvcrt40/i386/msvcrt40.dl_ `

Installing v_spindoc.exe:
` WINEARCH=win32 WINEPREFIX=~/.wine32 wine v_spindoc.exe
002c:err:menubuilder:Process_Link unable to load L"C:\\users\\bruno\\Start Menu\\Programs\\StartUp\\ST6UNST Uninstaller.LNK"
002c:err:menubuilder:wWinMain failed to build menu item for L"C:\\users\\bruno\\Start Menu\\Programs\\StartUp\\ST6UNST Uninstaller.LNK"
002e:err:module:import_dll Loading library MFC40.DLL (which is needed by L"C:\\Program Files\\Common Files\\VCS\\VSLIDE32.OCX") failed (error c000012f).`

`cd ~/.wine32/drive_c/windows/system32
WINEARCH=win32 WINEPREFIX=~/.wine32 wine regsvr32.exe /i mfc40.dll
regsvr32 : Impossible de charger la DLL « mfc40.dll »`

**Comment by bda65** [comment]
Hi,
I don't know what happened but if i install mfc40 with the winetricks gui it work perfectly. But not with ./winetricks mfc40.
Thanks for your help :)

**Comment by austin987** [comment]
Hopefully fixed by https://github.com/Winetricks/winetricks/commit/95a0c910a1af6e4743e6ceea4d753d92667a9cc5

I suspect your issue may have been that a wine process was open, potentially interfering with a registry edit. Make sure that no wine processes are running after install before trying again.
