### ISSUE TITLE
Please add oleaut32 verb

### ISSUE THREAD

**Issue by DarkShadow44** [Winetricks/winetricks#1232]
This dll is sometimes useful to work around issues with wine's oleaut32. It's present in the win7sp1 winetricks already uses.

**Comment by austin987** [comment]
Do you have an example application? Is oleaut32 enough on its own, or are there other dependencies?

**Comment by DarkShadow44** [comment]
For example the RoX Level Editor, see https://bugs.winehq.org/show_bug.cgi?id=43766. oleaut32 on its own is enough.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/51a845bffae4c6986ccbdf2c303135085060dcf1

**Comment by DarkShadow44** [comment]
Perfect, thank you!
