### ISSUE TITLE
Please add urlmon verb

### ISSUE THREAD

**Issue by DarkShadow44** [Winetricks/winetricks#1233]
Some programs who need native wininet also need native urlmon. It's present in the win7sp1 winetricks already uses.

**Comment by austin987** [comment]
Do you have an example program? IIRC native urlmon doesn't work too well with wine, but I could be mistaken.

**Comment by DarkShadow44** [comment]
I ran into https://bugs.winehq.org/show_bug.cgi?id=47197 using Tobit Radio.fx. Native urlmon helps, but that also required iertutil.

**Comment by qwertychouskie** [comment]
FYI: Native `urlmon` is installed with `ie8`.  May be a bit overkill to install IE8 whenever `urlmon` is needed, but at least that way that whole set of DLLs is the most likely to be compatible with each other.

**Comment by austin987** [comment]
Could you try https://github.com/austin987/winetricks/tree/urlmon?

**Comment by DarkShadow44** [comment]
This works fine, thanks!

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/dab7573c877aec7c26fe104c14c9e85c5495d257
