### ISSUE TITLE
vcrun2015 DLLs are an older version of vcrun2017, and are replaced by vcrun2017 during installation

### ISSUE THREAD

**Issue by Valmar33** [Winetricks/winetricks#1234]
Was looking at the FIXME for load_vcrun2017, and when I tried to install to Windows 10, it turns out that vcrun2017 is simply an upgrade for vcrun2015. This is why the DLL names are the same.

That is, vcrun2017 cleanly installs over vcrun2015.

Therefore, maybe load_vcrun2017 should simply call vcrun2017, and install that instead, for legacy instructions that ask for it?

**Comment by austin987** [comment]
I assume you mean 'maybe load_vcrun2017 should simply call vcrun2015'.

The product versions are different (you can use the recently added `filever` to verify that):
```
-       FileVer:        000e0000:59f20000 (14.0:23026.0)
-       ProdVer:        000e0000:59f20000 (14.0:23026.0)
+       FileVer:        000e0010:69900001 (14.16:27024.1)
+       ProdVer:        000e0010:69900001 (14.16:27024.1)
```

I think it's important to have both, like we do for dotnet service packs. That said, it could be argued that vcrun2017 shouldn't conflict with but rather should update and overwrite vcrun2015...

What do you think?

**Comment by Valmar33** [comment]
> That said, it could be argued that vcrun2017 shouldn't conflict with but rather should update and overwrite vcrun2015...

That seems like the better solution.

If 2015 is installed, load_vcrun2017 can happily install over it. If 2017 is installed, load_vcrun2015 can exit with a note that 2017 is the most up-to-date version or something.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/5292a7bb4bfba7f0cab25f7a355124323dccab85
