### ISSUE TITLE
Add support for .NET 4.8

### ISSUE THREAD

**Issue by vadi2** [Winetricks/winetricks#1239]
Could support for .NET 4.8 (final release, all further dev on .NET Core) be added?

Thanks!

**Comment by austin987** [comment]
In theory. It's not listed on the AppDB, so may take some time to figure out.

I'm busy for the next week or so, will try to look after that if someone else doesn't first.

**Comment by Faalagorn** [comment]
You should be able to install 4.8 from here in the meantime: https://github.com/Tk-Glitch/PKGBUILDS/tree/master/winetricks-tkg-git

**Comment by vadi2** [comment]
Could we get that in? 😊

**Comment by austin987** [comment]
I'll take a look. It would be nice if the author sent PRs instead of forking..

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/5cc04aaef319977c8bd604bd9937d023aab16551
