### ISSUE TITLE
Can't install dotnet40 on Wine 4.9 because it thinks it's already installed

### ISSUE THREAD

**Issue by aaronfranke** [Winetricks/winetricks#1245]
The installer starts but comes up with the error message:

>Your installation will not occur. See below for reasons why.

>Details
>Same or higher version of .NET Framework 4 has already been installed on this computer.

This happens even with a clean Wineprefix. I tried deleting `~/.wine` and running the installer manually and with "`winetricks dotnet40`" yet it still has this error message.

​I tried changing the Windows version in the Wine prefix to Windows XP and Windows 2003 as suggested by others, it did not work.

I tried using `--force` on the installer as suggested, it did not work.
​
Ubuntu 18.04 LTS 64-bit Linux, Wine 4.9 installed from WineHQ repos via the "winehq-devel" package with 64-bit prefix (just located in `~/.wine` as per default).

I also tried installing manually, same problem. File is "dotNetFx40_Full_setup.exe" with MD5 hash 53406e9988306cbd4537677c5336aba4​ 

The terminal output is similar to this: https://github.com/Winetricks/winetricks/issues/677

**Comment by Maccraft123** [comment]
You might have Mono already installed, try clean Wine prefix

**Comment by austin987** [comment]
Works for me in 4.9 with clean 32-bit and 64-bit prefixes.

What's in `$WINEPREFIX/winetricks.log`?

**Comment by aaronfranke** [comment]
`winetricks.log`:

```
w_workaround_wine_bug-42701
w_workaround_wine_bug-34803
remove_mono
winxp
dotnet40
```

Why should I have to remove Mono from my distro's packages? I need Mono installed for development work, without it I'd have to remove MonoDevelop.

**Comment by austin987** [comment]
wine-mono, not linux mono. Your log implies it was removed, but you could chec `wine uninstaller` to see if it was installed again later (i.e., with a wine upgrade).

**Comment by aaronfranke** [comment]
Indeed, it was present inside of `wine uninstaller` and I removed it manually, then `winetricks dotnet40` worked just fine. Perhaps the bug then is that it's not being removed even though it says `remove_mono` in the Winetricks log? Also, can wine-mono safely be reinstalled after dotnet40 is installed?

**Comment by austin987** [comment]
I don't suppose you know what wine versions you used in that prefix? I couldn't reproduce in a quick test, but I will try more later.

No, wine-mono cannot be reinstalled after native .Net, nor should you try. wine-mono is meant to be a replacement for .Net, but is incomplete. They cannot both be installed in the same prefix.

**Comment by aaronfranke** [comment]
A clean prefix (created from deleting `~/.wine`) looks like this in the Wine uninstaller:

![Screenshot from 2019-06-06 22-52-23](https://user-images.githubusercontent.com/1646875/59078570-c954ac00-88ad-11e9-9504-7d3a44a0da54.png)

This is after I uninstalled "Wine Mono Runtime" on a previous prefix, and `winetricks dotnet40` does not work on this new prefix. So in addition to `winetricks dotnet40` not being able to remove Mono, it seems that Mono is persistent on new prefixes even when previously removed. So it's not a configuration outside of `~/.wine`, it's something that gets copied into new prefixes.

**Comment by austin987** [comment]
What winetricks version?

**Comment by aaronfranke** [comment]
Sorry, I should have included that in the original post...

    20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924

 `apt policy winetricks` says it's from http://us.archive.ubuntu.com/ubuntu (but note that I installed Wine itself from the repo at https://dl.winehq.org/wine-builds/ubuntu)

**Comment by aaronfranke** [comment]
I just tried the latest version of Winetricks and it works fine:

    20190310-next - sha256sum: 0e8498d962e365da6ece94b739798635fc3af14fdceaff59ce94655c5dccf4da

I don't suppose there's a way to encourage the Ubuntu devs to update? If not, it would be nice if Winetricks was shipped with Wine itself in their repos, or if there was a Winetricks repo available.

**Comment by austin987** [comment]
I'd guess file a bug on launchpad.

Wine won't include it for various reasons, namely that it's mostly proprietary software (and I agree with that).

I have no plans to make a repo, but someone else could. There's also --self-update, if Ubuntu doesn't patch it out, that is.

**Comment by jre-wine** [comment]
ftr:
I reenabled the --self-update in winetricks 0.0+20181203-3.
So bionic (18.04LTS) doesn't support it, but starting with disco (19.04) it is there.
I'm not planning to add Ubuntu backports for it, but am absolutely fine with someone else doing it.

**Comment by austin987** [comment]
Cool. Fyi, this particular issue was likely fixed by https://github.com/Winetricks/winetricks/commit/b18fae574f80968580084444c95e208ae3cbed3f

I'm working in getting a release out so other benefit.

**Comment by NSThy** [comment]
find a solution
uninstall wine-mono package
rm -rf ~/.wine/
winecfg
install dot net 4.0 file

**Comment by Saman-Safaei-Dev** [comment]
how to do this on bottles ?

**Comment by NSThy** [comment]
> how to do this on bottles ?

crossover?
