### ISSUE TITLE
ProtectionId not available

### ISSUE THREAD

**Issue by jre-wine** [Winetricks/winetricks#1261]
Protection Id (ProtectionId.685.December.2016.rar) is not available on https://pid.gamecopyworld.com/  any more.  That domain redirects now.

According to http://archive.is/xFASH the latest version there was ProtectionId.690.December.2017.rar.

According to https://www.reddit.com/r/REGames/comments/asvetl/does_anyone_have_news_about_cdkiller_tippex_the/ the lost domain is known, and the app is still being developed.

I didn't find a download link for 6.8.5 matching the known checksum, or a legit official new home.  Emailing the author might be the best way to go ahead.  (I won't continue here - I just wanted to verify if unrar-free works, which it does for at least 6.4.0).

**Comment by austin987** [comment]
Thanks, sent an email.

**Comment by wefalltomorrow** [comment]
Thankfully I still had v0.6.9.0 DECEMBER on my PC before the site went down, I've uploaded it to Mega for anyone looking for it: https://mega.nz/#!vFwgiSZB!3ND1dGS4-HB1qoe0J_-hClUQQX7wUmZTGbIHB3rot0M

**Comment by pipboy96** [comment]
Better download from Web Archive copy. It's much less risky.

https://web.archive.org/web/20180921050146/https://pid.gamecopyworld.com/

**Comment by austin987** [comment]
Thanks for the tip:
https://github.com/Winetricks/winetricks/commit/60d700f581ae02f969e9184814bc8fb7f2b6ceb3

**Comment by MarianoMatera** [comment]
I've found last version in my download and uploaded it :)
[http://www.easybytez.com/yulov6pb13pt](http://www.easybytez.com/yulov6pb13pt)
