### ISSUE TITLE
d9vk_master prefers cached downloads over newer online copies

### ISSUE THREAD

**Issue by CartoonFan** [Winetricks/winetricks#1270]
Hello! I just wanted to let you know that winetricks is preferring cached downloads over newer online versions, effectively freezing the software at a particular version/release/commit. This mainly seems to affect verbs that get the "latest" or "master" version of dlls or utilities without changing the filename, such as d9vk_master. Thanks!

**Comment by austin987** [comment]
As far as I can tell, only d9vk_master is affected, as faudio/dxvk save the file with a version number, whereas d9vk_master always saves to `d9vk_master.zip`.

**Comment by CartoonFan** [comment]
I agree. I didn't check the others until after I posted the bug.
