### ISSUE TITLE
vcrun2012 does not support - q mode

### ISSUE THREAD

**Issue by 7thCore** [Winetricks/winetricks#1272]
vcrun2012 x86 dosen't work with -q mode. Exits with code 120. If you need any more info I will be happy to provide it.

Did find this if it helps:
http://asawicki.info/news_1597_installing_visual_c_redistributable_package_from_command_line.html

**Comment by austin987** [comment]
Works fine here:
```
austin@austin2:~/wine-git$ wineserver -k ; rm -rf ~/.wine ; WINE=$PWD/wine winetricks -q vcrun2012 ; echo $?
Using winetricks 20190615-next - sha256sum: 47304e177f259d6f9c05af01ab42c06531fd8a9716e2751d2fadcd664130feea with wine-4.12.1 and WINEARCH=win32
Executing w_do_call vcrun2012
Executing load_vcrun2012 
Using native,builtin override for following DLLs: atl110 msvcp110 msvcr110 vcomp110
Executing /home/austin/wine-git/wine regedit /S C:\windows\Temp\_vcrun2012\override-dll.reg
Executing cd /home/austin/.cache/winetricks/vcrun2012
Executing /home/austin/wine-git/wine vcredist_x86.exe /q
0048:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0048:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0050:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0050:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
0050:fixme:advapi:DecryptFileW (L"C:\\users\\austin\\Temp\\{33d1fd90-4274-48a1-9bc1-97e33d9c2d6f}\\", 00000000): stub
0048:fixme:ole:CoInitializeSecurity (0033F81C,-1,00000000,00000000,6,2,00000000,12288,00000000) - stub!
0055:fixme:shell:SHAutoComplete stub
0055:err:richedit:ReadStyleSheet skipping optional destination
0055:err:richedit:ReadStyleSheet skipping optional destination
0055:err:richedit:ReadStyleSheet skipping optional destination
0055:err:richedit:ReadStyleSheet skipping optional destination
0050:fixme:advapi:DecryptFileW (L"C:\\users\\austin\\Temp\\{33d1fd90-4274-48a1-9bc1-97e33d9c2d6f}\\", 00000000): stub
0048:fixme:wuapi:automatic_updates_Pause 
0048:fixme:sfc:SRSetRestorePointW 0033F6EC 0033F8FC
0054:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0054:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.30"
0054:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.28"
0054:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.30"
0054:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.28"
0048:fixme:wuapi:automatic_updates_Resume 
0
```

wine/winetricks version? terminal output?

**Comment by 7thCore** [comment]
Wine version: wine-staging 4.11-1
Winetricks version: winetricks 20190615-1

`[user@Pathfinder ~]$ env WINEARCH=win32 WINEPREFIX=/home/user/server winetricks -q vcrun2012
Using winetricks 20190615 - sha256sum: b6e465841d1d7bf473d8ecd32ed7a18e0add817444bf54ec25e6c9465584c6e9 with wine-4.11 (Staging) and WINEARCH=win32
Executing w_do_call vcrun2012
Executing load_vcrun2012 
Using native,builtin override for following DLLs: atl110 msvcp110 msvcr110 vcomp110
Executing wine regedit /S C:\windows\Temp\_vcrun2012\override-dll.reg
No protocol specified
Executing cd /home/interstellar_rift/.cache/winetricks/vcrun2012
Executing wine vcredist_x86.exe /q
0036:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0039:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0039:fixme:advapi:DecryptFileW (L"C:\\users\\interstellar_rift\\Temp\\{33d1fd90-4274-48a1-9bc1-97e33d9c2d6f}\\", 00000000): stub
003c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003c:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
003b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
003b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0036:fixme:ole:CoInitializeSecurity (0033F80C,-1,00000000,00000000,6,2,00000000,12288,00000000) - stub!
------------------------------------------------------
Note: command wine vcredist_x86.exe /q returned status 120. Aborting.
------------------------------------------------------
`

**Comment by austin987** [comment]
You didn't originally specify this was headless.

The installer itself requires a DISPLAY, that's not a bug. Most windows apps do. That's not a winetricks bug. This particular installer will work with Xvfb, but not everything does, fyi.
