### ISSUE TITLE
Cannot install dotnet20sp1 

### ISSUE THREAD

**Issue by rarealphacat** [Winetricks/winetricks#1273]
Clean 32prefix with wine 4.11

`0049:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
0027:fixme:msvcrt:__clean_type_info_names_internal (0x64083a50) stub
Executing cd /home/bbbf-6/.cache/winetricks/dotnet20sp1
wine: cannot find L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\mscorsvw.exe"
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"clr_optimization_v2.0.50727_32" failed to start: 2
0009:fixme:clusapi:GetNodeClusterState ((null),0033ECC4) stub!
0009:fixme:advapi:DecryptFileA ("y:\\b9cf59e2160935fa19fd\\", 00000000): stub
002d:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
002d:fixme:ole:CoInitializeSecurity (00000000,-1,00000000,00000000,0,3,00000000,0,00000000) - stub!
002d:fixme:advapi:LsaOpenPolicy ((null),0x32f034,0x00000001,0x32f02c) stub
002d:fixme:advapi:LsaClose (0xcafe) stub
002d:fixme:advapi:LsaOpenPolicy ((null),0x32e6a4,0x00000001,0x32e698) stub
002d:fixme:advapi:GetWindowsAccountDomainSid (0x32e624 0x17a5f4 0x32e620): semi-stub
002d:fixme:secur32:GetComputerObjectNameW NameFormat 7 not implemented
002d:fixme:advapi:LsaClose (0xcafe) stub
0031:fixme:ngen:wmain stub: L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\ngen.exe" L"queue" L"pause"
0017:fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d0c00 (device=2d access=0 func=300 method=0)
0017:fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d0c00 (device=2d access=0 func=300 method=0)
002d:fixme:advapi:LsaOpenPolicy ((null),0x32de14,0x00000001,0x32de08) stub
002d:fixme:advapi:GetWindowsAccountDomainSid (0x32dd94 0x19680c 0x32dd90): semi-stub
002d:fixme:secur32:GetComputerObjectNameW NameFormat 7 not implemented
002d:fixme:advapi:LsaClose (0xcafe) stub
002d:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
002d:fixme:msi:MsiGetFeatureValidStatesW 1 L"NetFx20_SP1_enu_x86_net_SETUP" 0032AA40 stub returning 8
0017:fixme:mountmgr:harddisk_ioctl Unsupported ioctl 70c00 (device=7 access=0 func=300 method=0)
0017:fixme:mountmgr:harddisk_ioctl Unsupported ioctl 70c00 (device=7 access=0 func=300 method=0)
002d:fixme:msi:determine_patch_sequence patch ordering not supported
002d:err:msi:MSI_OpenDatabaseW unknown flag 00000000
002d:err:msi:msi_apply_patch_package failed to open patch collection L"y:\\b9cf59e2160935fa19fd\\wcu\\dotnetframework\\dotnetfx20\\ASPNET.msp"
002d:err:msi:ITERATE_Actions Execution halted, action L"CA_ScheduleCacheGACAssembly.3643236F_FC70_11D3_A536_0090278A1BB8" returned 1627
0037:fixme:ngen:wmain stub: L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\ngen.exe" L"queue" L"pause"
0039:fixme:ngen:wmain stub: L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\ngen.exe" L"queue" L"pause"
003b:fixme:ngen:wmain stub: L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\ngen.exe" L"queue" L"pause"
003d:fixme:ngen:wmain stub: L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\ngen.exe" L"queue" L"pause"
0041:fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
0041:fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
0034:err:ole:CoRevokeClassObject called from wrong apartment, should be called from 2c0000002d
0043:fixme:ngen:wmain stub: L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\ngen.exe" L"queue" L"continue"
------------------------------------------------------
exit status 91 - dotnet20sp1 installation failed
------------------------------------------------------

`

I tried download dotnet20sp1 from MS and install it manually without success too.

**Comment by Faalagorn** [comment]
Isn't this one related to this bug? https://bugs.winehq.org/show_bug.cgi?id=47484 If so, you can try applying #1271 manually I guess or wait until this PR get merged.

**Comment by masternetra** [comment]
Same issue, setting ngen, mscorsvw, regsvcs to native or native then builtin doesn't solve it.

My Error log before setting the natives: https://pastebin.com/DsyNFgbi
My Error log after trying #1271 native fix: https://pastebin.com/H7fNDNqk

**Comment by austin987** [comment]
Does install winbind (in native package manager) help?

**Comment by austin987** [comment]
Please try with latest winetricks, https://github.com/Winetricks/winetricks/commit/710c154225358e10964968ddbae7dd9679f8cb2f may help as well.

**Comment by 4llan** [comment]
I was getting these errors trying to install SP3 to Office 2007
```
0009:err:msi:MSI_OpenDatabaseW unknown flag 00000000
0009:err:msi:msi_apply_patch_package failed to open patch collection ...
```

It's an issue since Wine 4.11, and I reported it here:
https://bugs.winehq.org/show_bug.cgi?id=47724
