### ISSUE TITLE
Error message after installing dotnet40

### ISSUE THREAD

**Issue by iDjay** [Winetricks/winetricks#1275]
Hey, I'm new to this whole thing. Here are the errors I get:
dotnet40 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
/Applications/Stronghold Crusader HD.app/Wineskin.app/Contents/Resources/winetricks: line 1720: test: wine-2.16: integer expression expected
------------------------------------------------------
Working around wine bug 30707 -- Need to get gacutil.exe

at the end:
x gacutil.exe
x gacutil.exe.config
err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\temp\\_dotnet40\\gacutil.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\temp\\_dotnet40\\gacutil.exe" failed, status c0000135
err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\temp\\_dotnet40\\gacutil.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\temp\\_dotnet40\\gacutil.exe" failed, status c0000135
err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\temp\\_dotnet40\\gacutil.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\temp\\_dotnet40\\gacutil.exe" failed, status c0000135
err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\temp\\_dotnet40\\gacutil.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\temp\\_dotnet40\\gacutil.exe" failed, status c0000135
err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\temp\\_dotnet40\\gacutil.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\temp\\_dotnet40\\gacutil.exe" failed, status c0000135
err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\temp\\_dotnet40\\gacutil.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\temp\\_dotnet40\\gacutil.exe" failed, status c0000135

**Comment by austin987** [comment]
wine-2.16 is no longer supported, I'd start by using a modern version of Wine.
