### ISSUE TITLE
Avoid Interactive Question "Running /usr/bin/wineserver -w"

### ISSUE THREAD

**Issue by tk421** [Winetricks/winetricks#1281]
I am trying to test software with Wine and I want to install all the fonts. 

I selected all the fonts and started the process. However, before each font I have a warning message "Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/xyz/.wine terminate" and is making this process very tedious. 

Is there any way to remove this message from being displayed ?

**Comment by tk421** [comment]
I missed the option "-q, --unattended      Don't ask any questions, just install automatically"

**Comment by olejorgenb** [comment]
Sorry for gravedigging, but IMO the -q should really be default or something else being done with these dialogs. Installing all fonts without this option is excruciating boring. It also trick you into clicking on the "cancel" button for the download dialogs.

I'm willing to bet some coins the dialogs have stolen _much_ more time than saved (for the user which actually had some apps running)
