### ISSUE TITLE
winetricks -q windowscodecs sets the windows version back to windows2000

### ISSUE THREAD

**Issue by bitranox** [Winetricks/winetricks#1283]
winetricks -q windowscodecs sets the windows version back to windows2000 - 
and not back to was it was before
I dont know if it is even neccessary to set it to win2k3 at the first place, because that happens after installing and registering windowscodecs

**Comment by austin987** [comment]
The dll is overridden at that point, native hasn't been installed yet, that's done in the 32859 workaround clause.

In any case, fixed by  https://github.com/Winetricks/winetricks/commit/93696c8a2fc297c62ee9b9c76e571ed3b3e62908

Thanks for the report.
