### ISSUE TITLE
dotnet installation not possible on proton containers (assumes .net is already installed)

### ISSUE THREAD

**Issue by jarrard** [Winetricks/winetricks#1284]
Just thought I notify you guys that the latest release breaks dotnet for proton containers, if anyone wants to get around this install v20190310.

Not sure how this was overlooked with 20190615 ??????

**Comment by austin987** [comment]
I don't test with proton, so I had no way to overlook it.

Anyway, how does it break? What versions of dotnet break? What wine version? Can you run a git bisect?

**Comment by jarrard** [comment]
It breaks by somehow telling dotnet that its already installed but winetricks does note afterwards it can't find the core file for it. 

This affects all dotnet versions, and all recent wine versions.  I'll work on a bisect for you in the meanwhile.

**Comment by austin987** [comment]
Please try with latest winetricks, https://github.com/Winetricks/winetricks/commit/710c154225358e10964968ddbae7dd9679f8cb2f may help.

**Comment by mirh** [comment]
I didn't get any such error now, so I would guess this has been fixed.
