### ISSUE TITLE
Sandbox issue

### ISSUE THREAD

**Issue by SubrataM3** [Winetricks/winetricks#1285]
I think the double slash in the following code is an error.
https://github.com/Winetricks/winetricks/blob/fd2fb248b1016ecb25e4112d9ef736cc1c55c14c/src/winetricks#L21047
Note this:
`\\Software\\`

**Comment by austin987** [comment]
Nice catch.

Fixed by https://github.com/Winetricks/winetricks/commit/a607031a2ec9251db2f5af8bd59e770cb8eef06e
