### ISSUE TITLE
Can't run winetricks

### ISSUE THREAD

**Issue by ivonenchev** [Winetricks/winetricks#1286]
On a fresh installation of OpenSuse Tumbleweed I try to run winetricks and the result was issue with following text :

WINEPREFIX INFO:
Drive C: общо 0
drwxr-xr-x 1 ivonenchev users 24  4 авг 02:15 .
drwsrwsrwt 1 ivonenchev users 70  4 авг 08:36 ..
drwxr-xr-x 1 ivonenchev users 20  4 авг 02:15 users
drwxr-xr-x 1 ivonenchev users 46  4 авг 02:10 windows

Registry info:
/home/ivonenchev/.wine/system.reg:#arch=win64
/home/ivonenchev/.wine/user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned unexpanded string '%ProgramFiles%' ... this can be caused by a corrupt wineprefix (`wineboot -u` may help), by an old wine, or by not owning /home/ivonenchev/.wine.

How can I fix it, because I need to use wine.

**Comment by austin987** [comment]
I'd start by trying a clean prefix:
$ WINEPREFIX=~/.wine-winetricks-test winetricks -q good

if that fails, attach the _full_ output (which should show wine/winetricks/prefix info, etc.)

**Comment by JPT77** [comment]
Hi
same problem with wine-staging-4.12
(I wait for update until ubuntu 19.10 is out because this will deliver the libfaudio which newer wine needs)

	$ WINEPREFIX=~/wine/winetricks-test winetricks -q good
	grep: /home/jan/wine/winetricks-test/*.reg: No such file or directory
	------------------------------------------------------
	WINEPREFIX INFO:
	Drive C: total 20
	drwxrwxr-x 4 jan jan 4096 Sep 27 15:39 .
	drwxrwxr-x 4 jan jan 4096 Sep 27 15:39 ..
	drwxrwxr-x 3 jan jan 4096 Sep 27 15:39 users
	drwxrwxr-x 4 jan jan 4096 Sep 27 15:39 windows
	-rw-rw-r-- 1 jan jan    9 Sep 27 15:39 .windows-serial

	Registry info:
	/home/jan/wine/winetricks-test/*.reg:
	------------------------------------------------------
	------------------------------------------------------
	wine cmd.exe /c echo '%ProgramFiles%' returned unexpanded string '%ProgramFiles%' ... this can be caused by a corrupt wineprefix (`wineboot -u` may help), by an old wine, or by not owning /home/jan/wine/winetricks-test
	------------------------------------------------------

**Comment by Kreyren** [comment]
@JPT77 Try suggested:

```bash
# This is going to update wineprefix
WINEPREFIX="/home/jan/wine/winetricks-test" wineboot -u

# This is going to fix permissions if they are not set on your current user (or user that is expected to execute it, root is not recommended)
chown -R "$USER:${USER}" "/home/jan/wine/winetricks-test"
```

**Comment by JPT77** [comment]
Old prefixes work yes. But any empty fails. 

Odd. first I deleted the dir, then I tried your command. and it crashed. How can I find more info on that?
is there a way to call winedbg on that?
so is something wrong with wineboot / wine setup in general in this version? 

	$ WINEPREFIX="/home/jan/wine/winetricks-test" wineboot -u
	wine: created the configuration directory '/home/jan/wine/winetricks-test'
	000b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
	000b:fixme:winediag:start_process Wine Staging 4.12 is a testing version containing experimental patches.
	000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
	wine: Unhandled page fault on write access to 0x00000090 at address 0x4024e5 (thread 000b), starting debugger...
	000b:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 10 96") (2)
	Read the Wine Developers Guide on how to set up winedbg or another debugger
