### ISSUE TITLE
Can't install fonts: "Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/user/.wine terminate 

### ISSUE THREAD

**Issue by wonx** [Winetricks/winetricks#1288]
I tried installing fonts using winetricks, but the message in the title appears all the time, and it seems that I can't go forward and the installation never completes. Even if I manually kill all wine processes (those just created by winetricks), the problem persists.

For instance, when trying to run: winetricks allfonts

I am using winetricks (updated today), with wine 3.0 and Ubuntu 18.04

**Comment by Chiitoo** [comment]
Aside from Wine 3.0 being quite outdated (latest versions are 4.0.1 stable, and 4.13 development), just to be sure, what version is your Winetricks actually?  Depending on how one updates these things, one may or may not get an actually up-to-date version due to how some distributions do things.  :]

Doing 'winetricks --version' will help with that.  It should hopefully return at least '20190615'.

The full terminal output may also be helpful.

One thing to perhaps try, is passing the '-q' (--unattended) option to Winetricks.  I don't remember if 'allfonts' produces any windows when ran via the CLI, but I've seen this help at least one user not so long ago ( https://github.com/Winetricks/winetricks/issues/1281 ).

**Comment by FlorianMeissner** [comment]
I just ran into the same issue with Wine 3.0. It seems updating to Wine 4.0.1 and Winetricks 20190617 solved the issue.

**Comment by austin987** [comment]
You can manually run `wineserver -k` in the prefix. `wine taskmgr` or `ps` may also give more detail.

The fonts may not get registered properly until wineserver restarts, which means that all running apps must stop.

**Comment by wonx** [comment]
Sorry for not answering before. I ended up upgrading my wine version (yep, mine was outdated) and somehow managed to install the fonts, although I don't recall if the winetricks script ended up working (I think I installed them manually).

**Comment by QXR9** [comment]
Still cant install no any font. Wine-9.15 (Staging). smt like:

```
------------------------------------------------------
warning: Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
------------------------------------------------------
------------------------------------------------------
warning: You are running winetricks-20230212, latest upstream is winetricks-20240105!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212 - sha256sum: e882a17654b1138109ed0211ae9726839683c91cf13dff24a012f6712375ebf2 with wine-9.15 (Staging) and WINEARCH=win64
winetricks GUI enabled, using zenity 4.0.2

(zenity:31687): Gtk-CRITICAL **: 22:02:57.005: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:31687): Gtk-CRITICAL **: 22:03:02.200: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:31740): Gtk-CRITICAL **: 22:03:02.658: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:31740): Gtk-CRITICAL **: 22:03:07.355: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:31740): Gtk-CRITICAL **: 22:03:08.026: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:31911): Gtk-CRITICAL **: 22:03:08.811: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:31911): Gtk-CRITICAL **: 22:03:10.996: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
Executing w_do_call allfonts
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------

(zenity:32089): Gtk-CRITICAL **: 22:03:13.916: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:32089): Gtk-CRITICAL **: 22:03:14.371: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
Executing load_allfonts 
Executing w_do_call andale
/tmp/winetricks.iCecnyqO/no_win64_warnings exists, not issuing 64-bit prefix warning
Executing load_andale 
grep: warning: stray \ before /
Executing mkdir -p /root/.cache/winetricks/corefonts
Executing cd /root/.cache/winetricks/corefonts
Downloading https://mirrors.kernel.org/gentoo/distfiles/andale32.exe to /root/.cache/winetricks/corefonts

(zenity:32247): Gtk-CRITICAL **: 22:03:18.139: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
chmod: cannot access 'andale32.exe': No such file or directory
Executing cd /home/pkk-buker3000
------------------------------------------------------
warning: /root/.cache/winetricks/corefonts/andale32.exe is not a regular file, not checking sha256sum
------------------------------------------------------

(zenity:32291): Gtk-CRITICAL **: 22:03:19.161: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
------------------------------------------------------
SHA256 mismatch!

URL: https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
Downloaded: 
Expected: 0524fe42951adc3a7eb870e32f0920313c71f170c859b5f770d82b4ee111e970

This is often the result of an updated package such as vcrun2019.
If you are willing to accept the risk, you can bypass this check.
Alternatively, you may use the --force option to ignore this check entirely.

Continue anyway?
------------------------------------------------------

(zenity:32326): Gtk-CRITICAL **: 22:03:24.822: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:32326): Gtk-CRITICAL **: 22:03:27.167: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
------------------------------------------------------
warning: Operation cancelled, quitting.
------------------------------------------------------

(zenity:32359): Gtk-CRITICAL **: 22:03:27.617: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(zenity:32359): Gtk-CRITICAL **: 22:03:28.119: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
```

idk what's going on my setup but I can see that error. Still don't know what does it mean.

**Comment by austin987** [comment]
> Still can't install no any font. Wine-9.15 (Staging). smt like:

This issue is closed, next time, open your own issue. That said, this looks like user error (see below..).

> ------------------------------------------------------
> warning: Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F

Don't do that unless you know what you're doing.

> warning: You are running winetricks-20230212, latest upstream is winetricks-20240105!

winetricks is out of date. Always update before reporting issues.

> Executing mkdir -p /root/.cache/winetricks/corefonts
> Executing cd /home/pkk-buker3000

Looks like a mismatch between your normal user/root.

> URL: https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
> Downloaded: 
> Expected: 0524fe42951adc3a7eb870e32f0920313c71f170c859b5f770d82b4ee111e970

Outdated winetricks..

**Comment by QXR9** [comment]
> > Still can't install no any font. Wine-9.15 (Staging). smt like:
> 
> This issue is closed, next time, open your own issue. That said, this looks like user error (see below..).
> 
> > warning: Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
> 
> Don't do that unless you know what you're doing.
> 
> > warning: You are running winetricks-20230212, latest upstream is winetricks-20240105!
> 
> winetricks is out of date. Always update before reporting issues.
> 
> > Executing mkdir -p /root/.cache/winetricks/corefonts
> > Executing cd /home/pkk-buker3000
> 
> Looks like a mismatch between your normal user/root.
> 
> > URL: https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
> > Downloaded:
> > Expected: 0524fe42951adc3a7eb870e32f0920313c71f170c859b5f770d82b4ee111e970
> 
> Outdated winetricks..

thanks. I will.
