### ISSUE TITLE
[Fedora 30] Can't Install dotnet 46

### ISSUE THREAD

**Issue by ArmagdoGaming** [Winetricks/winetricks#1290]
Using Fedora 30.
I tried installing Vortex via Protontricks GUI. It started by installing dotnet 4.0 and it says that a version of dotnet 4.0 or higher is installed, 4.5 gives an Invalid Function error. It tries to install 4.6 and it just fails. No error messages. Nothing. I tried 

> winetricks dotnet46 --force

 but got no results. Just an error.
Mono isn't installed.
![Screenshot from 2019-08-08 03-00-14](https://user-images.githubusercontent.com/52860974/62667931-1c201200-b98a-11e9-832d-8e5b94b45a45.png)
![Screenshot from 2019-08-08 03-05-39](https://user-images.githubusercontent.com/52860974/62667932-1c201200-b98a-11e9-97ed-c5da45b9631f.png)
![Screenshot from 2019-08-08 03-06-00](https://user-images.githubusercontent.com/52860974/62667933-1cb8a880-b98a-11e9-8501-38eb39fd8a48.png)
![Screenshot from 2019-08-08 03-06-08](https://user-images.githubusercontent.com/52860974/62667934-1cb8a880-b98a-11e9-910a-1ad17aa98918.png)

**Comment by bobwya** [comment]
@ArmagdoGaming 

What's the output from:

    WINEDEBUG=-all wine uninstaller --list

**Comment by ArmagdoGaming** [comment]
> @ArmagdoGaming
> 
> What's the output from:
> 
> ```
> WINEDEBUG=-all wine uninstaller --list
> ```

`{BB9BDB97-C247-4F20-B710-8B6765F67105}|||Wine Gecko (32-bit)
{3AD83002-EEB7-4EB9-BDCB-A533EE281826}|||Wine Gecko (64-bit)
{A183C2D2-A80E-5701-9A35-36B46C1BEA4D}|||Wine Mono Windows Support
`

**Comment by bobwya** [comment]
@ArmagdoGaming 

As I suspected... Awesome thanks!

**Comment by austin987** [comment]
This should be fixed by https://github.com/Winetricks/winetricks/commit/710c154225358e10964968ddbae7dd9679f8cb2f
