### ISSUE TITLE
Cannot install dotnet anymore

### ISSUE THREAD

**Issue by Evernow** [Winetricks/winetricks#1291]
Hello there!

Unfortunately I am unable to install dotnet anymore, I used to be able to but I can no more, this is what I get when I try, it also happens with winetricks unfortunately.

https://gist.github.com/Evernow/9a76e74288a4bb71f87507eec3d45b00

Any help is greatly appreciated

**Comment by edintomato** [comment]
+1 to this, although I might have found a quirk. Specifying dotnet40 by itself seems to work, but trying to install dotnet472 gives me the same errors as Evernow. What's really strange is that dotnet40 complains that Mono is not installed, but still installs itself anyways.
I'd attach a log, but my terminal only scrolls back so far. Here's what I have left: https://gist.github.com/edintomato/c768f0707b72c5bb6b1b8ecaa30ca04a

**Comment by bobwya** [comment]
@edintomato @Evernow 

Please can you post the output from:

    WINEDEBUG=-all wine uninstaller --list

Ta

**Comment by edintomato** [comment]
@bobwya [Here's the output from that command.](https://gist.github.com/edintomato/b0a03a740785672dd1f580d8a7db2757)

**Comment by austin987** [comment]
That output is after installing dotnet, I believe @bobwya wanted the output from before .net was installed.

In any case, could you try a clean prefix and latest winetricks, https://github.com/Winetricks/winetricks/commit/710c154225358e10964968ddbae7dd9679f8cb2f, will hopefully help.
