### ISSUE TITLE
VC2017 redist hashes need update

### ISSUE THREAD

**Issue by davidgtmp** [Winetricks/winetricks#1296]
Microsoft updated the VC2017 redistributable packages from their download links (https://aka.ms/vs/15/release/vc_redist.x86.exe and https://aka.ms/vs/15/release/vc_redist.x64.exe)

The new hashes need to be updated in src/winetricks or we cannot install them since the sha256sum fails.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/69b78faf9a4c48c90a1e3d151d8404ed42fa7078
