### ISSUE TITLE
Dotnet20sp2 fails to install

### ISSUE THREAD

**Issue by chroniceel93** [Winetricks/winetricks#1299]
The dotnet2.0 SP2 installer fails repeatedly through winetricks.
Installing twice does not fix the problem.
Setup exits gracefully (no crash), rolls back all changes, it detects a problem

This pops up in the installers error log

`[08/20/19,22:11:19] Microsoft .NET Framework 2.0a: [2] Error: Installation failed for component Microsoft .NET Framework 2.0a. MSI returned error code 1627`

`[08/20/19,22:11:28] WapUI: [2] DepCheck indicates Microsoft .NET Framework 2.0a is not installed.`

I'm using Manjaro (unstable), trying to install into a clean, 32-bit prefix.
Wine version 4.14
Latest winetricks from git.

Terminal log attached
[dotnet20installlog.txt](https://github.com/Winetricks/winetricks/files/3523407/dotnet20installlog.txt)

Feel free to ignore the xrandr stuff, unless of course, that is actually causing this problem

**Comment by austin987** [comment]
Please try with latest winetricks, https://github.com/Winetricks/winetricks/commit/710c154225358e10964968ddbae7dd9679f8cb2f may help.

**Comment by lucifertdark** [comment]
I can confirm the newest winetricks enables dotnet20sp2 to install without complaint. Thanks austin987. :)

**Comment by chroniceel93** [comment]
For my part, I still can't install donet20sp2 into a fresh 32-bit prefix with latest winetricks with wine 1.14.

**Comment by lucifertdark** [comment]
Ah apologies, I've been using a 64bit prefix, not 32bit.

**Comment by chroniceel93** [comment]
... It works in a _64 bit_ prefix? Well, the program I need can run with wine's wow64 mode, so this may soon be a non-issue for me.
I'm also starting to suspect that the installer failing in 32 bit prefixes is less of a winetricks issue, and more of a wine issue.

**Comment by chroniceel93** [comment]
Yeah, still didn't work. Going over system config for the umpteenth time to see if I'm doing anything stupid on my end.

**Comment by austin987** [comment]
Wine 1.14 is extremely old and unsupported.

**Comment by chroniceel93** [comment]
I know. I'm running 4.14 stable. Typo on my part.

**Comment by Esux** [comment]
Doesn't work for me either using latest winetricks. (Pulled it straight from github to make sure)
Using wine-4.14.
Tried new wine prefixes. 32 and 64 bit. Nothing works

```
002e:err:msi:MSI_OpenDatabaseW unknown flag 00000000
002e:err:msi:msi_apply_patch_package failed to open patch collection L"y:\\15ab84d51e2d10d6654df2b938bc\\wcu\\dotnetframework\\dotnetfx20\\ASPNET_64.msp"
002e:err:msi:ITERATE_Actions Execution halted, action L"CA_ScheduleCacheGACAssembly.3643236F_FC70_11D3_A536_0090278A1BB8" returned 1627
0033:err:ole:CoRevokeClassObject called from wrong apartment, should be called from 2d0000002e
------------------------------------------------------
exit status 91 - dotnet20sp2 installation failed
------------------------------------------------------
```

**Comment by chroniceel93** [comment]
Do you use arch, or a derivative of arch? (e.g manjaro, antergos)

**Comment by Esux** [comment]
> Do you use arch, or a derivative of arch? (e.g manjaro, antergos)

I'm using Arch, yes.

**Comment by chroniceel93** [comment]
I've been looking into it, and the installer seems to be working on literally every other flavor of linux, from Nix, to Ubuntu, to Fedora. I'm thinking it's a library issue somewhere, and I've submitted a bug report to the wine bugzilla tracker accordingly. I suppose I should close this bug report, as it's not a problem that is caused by winetricks itself?

**Comment by austin987** [comment]
What wine bug is that?

We can keep it open for now, but yeah, it's likely a distro/wine bug.

**Comment by austin987** [comment]
Looks like https://bugs.winehq.org/show_bug.cgi?id=47740

**Comment by bengris32** [comment]
> I've been looking into it, and the installer seems to be working on literally every other flavor of linux, from Nix, to Ubuntu, to Fedora. I'm thinking it's a library issue somewhere, and I've submitted a bug report to the wine bugzilla tracker accordingly. I suppose I should close this bug report, as it's not a problem that is caused by winetricks itself?

The exact same issue happens on Pop!_OS(an ubuntu based distro)

`002e:err:msi:MSI_OpenDatabaseW unknown flag (nil)
002e:err:msi:msi_apply_patch_package failed to open patch collection L"c:\\95b93a5f0a495a08086a056a6d12\\wcu\\dotNetFramework\\dotnetfx20\\ASPNET.msp"
002e:err:msi:ITERATE_Actions Execution halted, action L"CA_ScheduleCacheGACAssembly.3643236F_FC70_11D3_A536_0090278A1BB8" returned 1627`

**Comment by x0nn** [comment]
upstream bug is closed.

**Comment by mirh** [comment]
Upstream bug is closed, and presumably all the other ones in the "wine 5.0 .net installer nightmare saga" too now.
