### ISSUE TITLE
--self-update does not work on macOS

### ISSUE THREAD

**Issue by gverm** [Winetricks/winetricks#1301]
```
Gijss-MacBook-Pro:~ gverm$ ./winetricks.sh --self-update
Executing cd /var/folders/2k/06b9qjs56_b_480f06bkyxnw0000gn/T//winetricks.sh.XwiiENTg
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks to /var/folders/2k/06b9qjs56_b_480f06bkyxnw0000gn/T//winetricks.sh.XwiiENTg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  786k  100  786k    0     0  1868k      0 --:--:-- --:--:-- --:--:-- 1864k
Executing cd /Users/gverm
Unknown file type: /var/folders/2k/06b9qjs56_b_480f06bkyxnw0000gn/T//winetricks.sh.XwiiENTg/winetricks.sh: cannot open `/var/folders/2k/06b9qjs56_b_480f06bkyxnw0000gn/T//winetricks.sh.XwiiENTg/winetricks.sh' (No such file or directory)
```
Tested on a 2015 MacBook Pro running macOS 10.13 High Sierra.

**Comment by gverm** [comment]
@austin987 Here you go: [log.txt](https://github.com/Winetricks/winetricks/files/3545740/log.txt)

**Comment by gverm** [comment]
@austin987 Seems like this was caused by me naming the file winetricks.sh instead of just winetricks. Removing the extension fixed the issue.

Does that make this issue invalid or is there still a bug here?

**Comment by austin987** [comment]
I'd say so, especially since it's an easy fix.

Could you verify that https://github.com/austin987/winetricks/commit/1837687854294ef92b476b2db68fe90c3b7b1c64 works for you?

**Comment by gverm** [comment]
@austin987 that works, thanks

**Comment by austin987** [comment]
Great, thanks for testing.

Committed as https://github.com/Winetricks/winetricks/commit/1837687854294ef92b476b2db68fe90c3b7b1c64
