### ISSUE TITLE
dotnet40 applications stuck in infinite loop 

### ISSUE THREAD

**Issue by yshui** [Winetricks/winetricks#1314]
If a dotnet40 application is running with Windows version set to Windows 7 or up, it seems to enter an infinite loop on startup, spamming logs like this:

```
0009:fixme:path:parse_url failed to parse L"[...].resources"
```

(the log turns out to be irrelevant, but is the most visible symptom).

I haven't figured out the root cause, what I understand right now is that the app is looking for files with my **locale** (e.g. v4.0_4.0.0.0_**zh-CN**_b03f5f7f11d50a3a) in the path, and cannot find them. because those files are installed at a path without the locale part (e.g `v4.0_4.0.0.0__b03f5f7f11d50a3a`).

If I run the application with `LC_ALL=C`, everything seems to work.

Does winetricks reset the locale when installing dotnet40?

Upstream bug report: https://bugs.winehq.org/show_bug.cgi?id=47277

**Comment by austin987** [comment]
As far as I can tell, not for dotnet40. Some other dotnet versions (and other verbs) do:
e.g., dotnet35/dotnet35sp1/dotnet461/dotnet462/dotnet471/dotnet48 all force an English locale for installation.

**Comment by rmi1974** [comment]
This is a bug in Wine, see my analysis here: https://bugs.winehq.org/show_bug.cgi?id=47277#c9

**Comment by demonidios** [comment]
user@user-VirtualBox:~$ winetricks
------------------------------------------------------
Вы используете 64-битный WINEPREFIX. Важно: многие ветки устанавливают только 32-битные версии пакетов. Если у вас возникли проблемы, пожалуйста, проверьте еще раз на чистом 32-битном WINEPREFIX до отправки отчета об ошибке.
------------------------------------------------------
Using winetricks 20191224-next - sha256sum: ad7e49675d0a0a1c375e28c43b5c923165fb1950f423d1d8ddbfb48248c99c6d with wine-5.0 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0
Executing w_do_call dotnet45
------------------------------------------------------
Вы используете 64-битный WINEPREFIX. Важно: многие ветки устанавливают только 32-битные версии пакетов. Если у вас возникли проблемы, пожалуйста, проверьте еще раз на чистом 32-битном WINEPREFIX до отправки отчета об ошибке.
------------------------------------------------------
Executing load_dotnet45 
------------------------------------------------------
Данный пакет может работать не полностью в 64-битном окружении. 32-битные префиксы могут работать лучше.
------------------------------------------------------
Executing w_do_call remove_mono
------------------------------------------------------
Вы используете 64-битный WINEPREFIX. Важно: многие ветки устанавливают только 32-битные версии пакетов. Если у вас возникли проблемы, пожалуйста, проверьте еще раз на чистом 32-битном WINEPREFIX до отправки отчета об ошибке.
------------------------------------------------------
Executing load_remove_mono 
0035:err:module:import_dll Library crypt32.dll (which is needed by L"C:\\windows\\system32\\msi.dll") not found
0035:err:module:import_dll Library crypt32.dll (which is needed by L"C:\\windows\\system32\\wintrust.dll") not found
0035:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc78af6
0039:err:module:import_dll Library crypt32.dll (which is needed by L"C:\\windows\\system32\\msi.dll") not found
0039:err:module:import_dll Library crypt32.dll (which is needed by L"C:\\windows\\system32\\wintrust.dll") not found
0039:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc78af6
------------------------------------------------------
Обход ошибки 34803 
------------------------------------------------------
reg: не удалось найти указанный раздел реестра или значение
reg: не удалось найти указанный раздел реестра или значение
reg: не удалось найти указанный раздел реестра или значение
Executing rm -f /home/user/.wine/dosdevices/c:/windows/system32/mscoree.dll
Executing rm -f /home/user/.wine/dosdevices/c:/windows/syswow64/mscoree.dll
Executing w_do_call dotnet40
------------------------------------------------------
Вы используете 64-битный WINEPREFIX. Важно: многие ветки устанавливают только 32-битные версии пакетов. Если у вас возникли проблемы, пожалуйста, проверьте еще раз на чистом 32-битном WINEPREFIX до отправки отчета об ошибке.
------------------------------------------------------
Executing load_dotnet40 
------------------------------------------------------
Данный пакет может работать не полностью в 64-битном окружении. 32-битные префиксы могут работать лучше.
------------------------------------------------------
------------------------------------------------------
dotnet40 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
Current Wine does not have Wine bug 42701, so not applying workaround
Executing w_do_call remove_mono
------------------------------------------------------
Вы используете 64-битный WINEPREFIX. Важно: многие ветки устанавливают только 32-битные версии пакетов. Если у вас возникли проблемы, пожалуйста, проверьте еще раз на чистом 32-битном WINEPREFIX до отправки отчета об ошибке.
------------------------------------------------------
Executing load_remove_mono 
0035:err:module:import_dll Library crypt32.dll (which is needed by L"C:\\windows\\system32\\msi.dll") not found
0035:err:module:import_dll Library crypt32.dll (which is needed by L"C:\\windows\\system32\\wintrust.dll") not found
0035:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc78af6
0039:err:module:import_dll Library crypt32.dll (which is needed by L"C:\\windows\\system32\\msi.dll") not found
0039:err:module:import_dll Library crypt32.dll (which is needed by L"C:\\windows\\system32\\wintrust.dll") not found
0039:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc78af6
------------------------------------------------------
Обход ошибки 34803 
------------------------------------------------------
reg: не удалось найти указанный раздел реестра или значение
reg: не удалось найти указанный раздел реестра или значение
reg: не удалось найти указанный раздел реестра или значение
Executing rm -f /home/user/.wine/dosdevices/c:/windows/system32/mscoree.dll
Executing rm -f /home/user/.wine/dosdevices/c:/windows/syswow64/mscoree.dll
Executing w_do_call winxp
------------------------------------------------------
Вы используете 64-битный WINEPREFIX. Важно: многие ветки устанавливают только 32-битные версии пакетов. Если у вас возникли проблемы, пожалуйста, проверьте еще раз на чистом 32-битном WINEPREFIX до отправки отчета об ошибке.
------------------------------------------------------
Executing load_winxp 
Операция успешно завершена
Setting Windows version to winxp
Executing wine regedit C:\windows\Temp\set-winver.reg
Executing wine64 regedit C:\windows\Temp\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/user/.wine terminate
------------------------------------------------------
Executing cd /home/user/.cache/winetricks/dotnet40
001b:err:module:DelayLoadFailureHook failed to delay load hid.dll.HidD_GetHidGuid
wine: Call from 0x7b00fc5e to unimplemented function hid.dll.HidD_GetHidGuid, aborting
001b:err:seh:call_stack_handlers invalid frame 5c44e0 (0x762000-0x960000)
001b:err:seh:raise_exception Exception frame is not in stack limits => unable to dispatch exception.
000f:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"winebus" failed to start: 1053
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:seh:_abnormal_termination (void)stub
0009:fixme:ole:NdrCorrelationInitialize (0032A560, 0032A04C, 1024, 0x0): semi-stub
0009:fixme:ole:NdrCorrelationFree (0032A560): stub
0009:fixme:wintrust:WinVerifyTrust unimplemented for 4
0009:fixme:wintrust:WinVerifyTrust unimplemented for 4
0009:fixme:wintrust:WinVerifyTrust unimplemented for 4
0009:fixme:wintrust:WinVerifyTrust unimplemented for 4
0009:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0009:fixme:process:SetProcessDEPPolicy (3): stub
0009:fixme:clusapi:OpenCluster ((null)) stub!
0009:fixme:clusapi:ClusterOpenEnum (DEADBEEF, 4) stub!
0009:fixme:clusapi:ClusterEnum (DEADBEEF, 0, 0032F920, 00627848, 261) stub!
0009:fixme:clusapi:ClusterCloseEnum (DEADBEEF) stub!
0009:fixme:clusapi:CloseCluster (DEADBEEF) stub!
0009:fixme:advapi:DecryptFileW (L"C:\\03ac21470810233480b2a513\\", 00000000): stub
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:seh:_abnormal_termination (void)stub
002f:fixme:ole:NdrCorrelationInitialize (0032A4E0, 00329FCC, 1024, 0x0): semi-stub
002f:fixme:ole:NdrCorrelationFree (0032A4E0): stub
002f:fixme:wintrust:WinVerifyTrust unimplemented for 4
002f:fixme:wintrust:WinVerifyTrust unimplemented for 4
002f:fixme:wintrust:WinVerifyTrust unimplemented for 4
002f:fixme:wintrust:WinVerifyTrust unimplemented for 4
002f:fixme:ntdll:EtwRegisterTraceGuidsW (0x6cd15f38, 0x6cd20180, {e2821408-c59d-418f-ad3f-aa4e792aeb79}, 1, 0x32e6d0, (null), (null), 0x6cd20188): stub
002f:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2821408-c59d-418f-ad3f-aa4e792aeb79}
002f:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
002f:fixme:process:SetProcessDEPPolicy (1): stub
002f:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
002f:fixme:reg:RegOpenUserClassesRoot (000000A8, 0x0, 0x2000000, 0032F334) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F340) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F2F4) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F2E0) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
002a:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F388) semi-stub
002f:fixme:reg:RegOpenUserClassesRoot (000000AC, 0x0, 0x2000000, 0032F0C4) semi-stub
002f:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
002f:fixme:advapi:LsaOpenPolicy ((null),0x32f518,0x00000001,0x32f50c) stub
002f:fixme:security:GetWindowsAccountDomainSid (0032F498 00D2C1CC 0032F494): semi-stub
002f:fixme:secur32:GetComputerObjectNameW NameFormat 7 not implemented
002f:fixme:advapi:LsaClose (0xcafe) stub
002f:fixme:reg:RegOpenUserClassesRoot (000000B0, 0x0, 0x2000000, 0032F270) semi-stub
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0030:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
0031:fixme:wintrust:WinVerifyTrust unimplemented for 4
