### ISSUE TITLE
Function w_steam_install_game() is not usable

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1323]
Issues with `w_steam_install_game()`:
- Asks for ID + PW from TUI, but then refuses to parse it
- Requires to input authentification multiple time (3x) before it allows game download
- Won't save credentials
- Appears to halt while game is downloading -> Some output required
- Won't open the game once the download is finished and won't output anything to indicate that the game finished downloading causing indefinite loop (waited 50 mins  for game that downloads in 7 mins max)
- Won't fill Parent Controll Access 
- Possible interpretation with Keepass?
- `steam://run/373100` (https://developer.valvesoftware.com/wiki/Steam_browser_protocol) can be used to install game

**Comment by austin987** [comment]
Yeah, that code has bitrotted over the years. Given that no one has really complained/taken it up, I think it's better to simply remove it.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/ebc5dd568d8e395140006154cade1da2426745bd
