### ISSUE TITLE
Problems installing d9vk and dxvk

### ISSUE THREAD

**Issue by OnikenX** [Winetricks/winetricks#1327]
Using:
 archlinux
   wine 4.15-1
   winetricks 20190912-1 
   linux 5.2.14.arch2-1

created multiple wineprefixes and the problem consists

https://paste.ubuntu.com/p/RKjs9YxWVS/

dont know how more can help
thx for the work and help

**Comment by austin987** [comment]
What version of cabextract?

**Comment by OnikenX** [comment]
ho sorry forgot to to mention, its cabextract 1.9.1-1

**Comment by jre-wine** [comment]
@austin987 if you are thinking about the big cabextract issue from half a year ago: the bug itself was in libmspack 0.8, and fixed there in 0.9.1-1.

**Comment by Kreyren** [comment]
@OnikenX Couldn't this be corrupted cache? 

Try removing/renaming `$HOME/.cache/winetricks/` and reproduce ideally report back with shasum for files at question since i don't think that winetricks performs any checks for what was downloaded.
