### ISSUE TITLE
riched30 fetch url is dead

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1329]
> Can't access riched30: http://ftp.tw.vim.org/cpatch/msupdate/msi/source/instmsia.exe . It looks like server is not responding

I have same issue on my end

```console
kreyren@dreamon:~$ ping http://ftp.tw.vim.org
ping: http://ftp.tw.vim.org: Name or service not known
```

_Originally posted by @Kreyren in https://github.com/Winetricks/winetricks/pull/1030#issuecomment-533539694_

### Possible solution
Would this be a sufficient replacement?
http://www.bitron.ch/downloads/riched30.exe

---

Referencing: https://github.com/Winetricks/winetricks/pull/1030/files#diff-90b1fb64c3f0a6c10d15531fb2008296R9207

**Comment by Kreyren** [comment]
ping @realgsong

**Comment by Kreyren** [comment]
Assuming that we need `riched20.dll` and `msls31.dll` we could get them from https://www.dll-files.com/

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/5c99449fc6810ee0dedb5c7f06d0a7b10f009266
