### ISSUE TITLE
Add FiveM (tracking)

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1356]
FiveM is singleplayer backend for multiplayer in Grand Theft Auto V where previously it was impossible to get it running due to the DXVK/winevulkan missing shared resources 

referencing https://github.com/doitsujin/dxvk/issues/1033#issuecomment-520196055

/+ Relevant for battleeye anti-cheat 

Seems that there is a development in terms of workaround so this issue is created to track it for compatibility in winetricks.

**Comment by Kreyren** [comment]
RESERVED

**Comment by Kreyren** [comment]
apparently sujin considers DXVK as not related to Vulkan and gets offended for some reason even when the project is literally wrapper from DirectX to Vulkan (https://github.com/doitsujin/dxvk/issues/899#issuecomment-548491912)

tracking moved here for wine patch/hack or workaround in winetricks prioritized over dxvk solution.

**Comment by Kreyren** [comment]
Referencing original https://github.com/PhoenicisOrg/scripts/issues/914

**Comment by tannisroot** [comment]
i don't understand, why is this a winetricks issue?

**Comment by Kreyren** [comment]
@tannisroot afaik this is a modification that requires a process to make work (workaround various winebugs and then importing the mods to GTA V) which to me seems like perfect usecase for winetricks assuming that Phoenicis is not usable and lutris doesn't have sufficient backend for this kind of runtime.

**Comment by tannisroot** [comment]
> afaik this is a modification that requires a process to make work 
what?
> which to me seems like perfect usecase for winetricks
what? no. To support shared resources, somebody will need to add support for in Wine by actually coding it. You can't just workaround it by replacing some components with native ones.
Since this is not in any way related winetricks, it would be nice to close this issue.

**Comment by Kreyren** [comment]
> what?

> what? no. To support shared resources, somebody will need to add support for in Wine by actually coding it. You can't just workaround it by replacing some components with native ones.
Since this is not in any way related winetricks, it would be nice to close this issue.

Codeweavers and sujin are working on it so me messing with wine for this purpose would only be counter productive and untill that is implemented the game needs a workaround to make working atm.

but fair enough to close it here

**Comment by tannisroot** [comment]
> untill that is implemented the game needs a workaround to make working atm. 
this can't be workarounded unfortunately, it an issue that affects wine on a quite low level.

**Comment by Kreyren** [comment]
@tannisroot WFM on kreytricks but it is unreliable

**Comment by tannisroot** [comment]
??? what's WFM

**Comment by Kreyren** [comment]
@tannisroot WFM - Works For Me

**Comment by tannisroot** [comment]
What does?

**Comment by Kreyren** [comment]
@tannisroot i'm working on that atm it is not published yet bcs it's not reliable.. feel free to try it for yourself with info provided in this and referenced issues

**Comment by tannisroot** [comment]
oh, you made it up, got it.

**Comment by Kreyren** [comment]
what?

**Comment by lorenzo12floxy** [comment]
is there any progress/solution yet? and if so can someone tell me how to use it

**Comment by tannisroot** [comment]
FiveM requires an implementation of shared resources both in Wine and in DXVK, which would be a enormous task that can't be just fixed with by ripping out some Windows component and installing it with Winetricks. There is no current activate development in that area and it's unlikely that there will be in near future.

**Comment by lorenzo12floxy** [comment]
R.I.P

**Comment by DrewRidley** [comment]
https://www.reddit.com/r/linux_gaming/comments/t07q1g/shared_texture_resources_will_be_coming_to_proton/

Yall should definitely try FiveM out because theres a slight chance it will work now!
