### ISSUE TITLE
Vulkan Runtime changes that will require winetricks modifications

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [Winetricks/winetricks#1368]
I exchanged email offline with @austin987 but wanted to document here in the issue tracker to make sure this doesn't get lost.

In the future, the Vulkan SDK for windows as downloaded from vulkan.lunarg.com will no longer include the Vulkan Runtime Installer (which was used to install the Vulkan Loader on the system). The reason for this is that the Vulkan Loader is included with IHV driver packages on Windows and is the recommended method to get the Vulkan Loader. 

Although the Vulkan Loader install will no longer be part of the Windows SDK, a separate Vulkan Runtime installer package (for the latest version only) will still be made available on vulkan.lunarg.com for solutions such as Wine. A permament link already exists for this package:  https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/latest/windows/vulkan-runtime.exe

Winetricks is currently hard wired to use an older version of the Vulkan SDK to get the loader (by installing an SDK). Should Winetricks want to move ahead to a newer version, they should not install the Vulkan SDK to get the loader but rather install the Vulkan Runtime Installer that will be at vulkan.lunarg.com

**Comment by Kreyren** [comment]
Info required for contrib:

Which verbs should be updated and how?

- Deduced that `vulkanSDK` verb is affected by this

- is `vulkanrt` also affected or any other verb?

> In the future, the Vulkan SDK for windows as downloaded from vulkan.lunarg.com will no longer include the Vulkan Runtime Installer 

So downloading `VulkanSDK-1.1.73.0-Installer.exe` and  https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/latest/windows/vulkan-runtime.exe is required for one verb?

**Comment by KarenGhavam-lunarG** [comment]
> Although the Vulkan Loader install will no longer be part of the Windows SDK, a separate Vulkan Runtime installer package (for the latest version only) will still be made available on vulkan.lunarg.com for solutions such as Wine. 

Permalinks have been updated on vulkan.lunarg.com for the Vulkan Runtime and Vulkan SDK packages:

Windows SDK: https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe
Windows SDK SHA: https://sdk.lunarg.com/sdk/sha/latest/windows/vulkan-sha.txt

Windows RT: https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-rt.exe
Windows RT SHA: https://sdk.lunarg.com/sdk/sha/latest/windows/vulkan-RT-sha.txt

**Comment by austin987** [comment]
First, thanks @KarenGhavam-lunarG!  Sorry for letting this slip through the cracks.

I was just looking at this, and noticed that the sha for vulkan-rt.exe is wrong. vulkan-RT-sha.txt says it's `2e495f94badff3016e5ec7b50bc808272b56fdd3fc3ae5dcdd892fdb48bf6328`. The sha256 is actually `0375a6a31a65d8c17b0f817835aed6cdc651783a24c37b51f8ca76cc33e37579`. Coincidentally, that matches what's on https://vulkan.lunarg.com/sdk/home for the 1.2.141.0 SDK.

vulkan-sdk/uvlkan-sha.txt match.

BTW I tried to report this on https://vulkan.lunarg.com/issue/; I made an account and activated it, but when trying to report an issue logging in just asks me to login again.

A related suggestion: if you use format that sha256 outputs ($sha256  $filename), it's a bit easier to verify the file later:
```
austin@laptop /tmp/tmp.E6LQ7BSOHp $ sha256sum vulkan-rt.exe > vulkan-rt.exe.sha256

austin@laptop /tmp/tmp.E6LQ7BSOHp $ cat vulkan-rt.exe.sha256 
0375a6a31a65d8c17b0f817835aed6cdc651783a24c37b51f8ca76cc33e37579  vulkan-rt.exe

austin@laptop /tmp/tmp.E6LQ7BSOHp $ sha256sum -c vulkan-rt.exe.sha256 
vulkan-rt.exe: OK
```

**Comment by KarenGhavam-lunarG** [comment]
Evidently the system is not updating the sha file correctly and I will submit an issue for that to be resolved. I take it that you have not been using this permalink yet. Or did it work previously?

**Comment by austin987** [comment]
I had not tried before, so I'm unsure if it previously worked, sorry.

**Comment by KarenGhavam-lunarG** [comment]
@austin987 A change to LunarXchange has been pushed that should be working. However I personally don't know how to test it. Could you attempt it again and provide feedback?

**Comment by austin987** [comment]
@KarenGhavam-lunarG thanks. The binary is now correct, but the shasum files need a slight change. To reproduce:
```
#!/bin/bash
set -ex

wget -c https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe
wget -c https://sdk.lunarg.com/sdk/sha/latest/windows/vulkan-sha.txt

wget -c https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-rt.exe
wget -c https://sdk.lunarg.com/sdk/sha/latest/windows/vulkan-RT-sha.txt

sha256sum *txt
```

That fails:
```
+ sha256sum -c ./vulkan-RT-sha.txt ./vulkan-sha.txt
vulkan-RT-sha.txt: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
vulkan-sha.txt: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

The shas are correct, but needs to have the filename of the file it corresponds to. I.e., currently, you have:
```
austin@laptop /tmp/tmp.4uycKh3VEm $ cat *txt
bf5050ead980e66fdd7b8eb5664d2b92e037ec5c400f75c2dc209a595828aaf7 vulkan-RT-sha.txt
d732eaee50c5f924ee64c9408bec7073b7a230464f1636f346833727c9bbddd0 vulkan-sha.txt
```

They should be:
```
austin@laptop /tmp/tmp.4uycKh3VEm $ cat *txt
bf5050ead980e66fdd7b8eb5664d2b92e037ec5c400f75c2dc209a595828aaf7  vulkan-rt.exe
d732eaee50c5f924ee64c9408bec7073b7a230464f1636f346833727c9bbddd0  vulkan-sdk.exe
```

In addition, the files lack a newline. Doesn't seem to break `sha25sum -c` but a newline does make it more readable if someone `cat`s the file.

I would also suggest having the filenames match. I.e., currently, you have:
```
vulkan-rt.exe <> vulkan-RT-sha.txt
vulkan-sdk.exe <> vulkan-sha.txt
```

If possible, I would suggest instead doing:
```
vulkan-rt.exe <> vulkan-rt.txt
vulkan-sdk.exe <> vulkan-sdk.txt
```

Or alternatively, to make it more explicit that it's a sha256sum:
```
vulkan-rt.exe <> vulkan-rt.exe.sha256
vulkan-sdk.exe <> vulkan-sdk.exe.sha256
```

**Comment by dfitzpat** [comment]
I updated the SHA URLs:

```
https://sdk.lunarg.com/sdk/sha/latest/windows/vulkan-rt.exe.sha256
https://sdk.lunarg.com/sdk/sha/latest/windows/vulkan-sdk.exe.sha256
```

Test: 
```
wget -c https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-rt.exe
wget -c https://sdk.lunarg.com/sdk/sha/latest/windows/vulkan-rt.exe.sha256
sha256sum -c vulkan-rt.exe.sha256
#-> vulkan-rt.exe: OK
```

Let me know if this works for you.

**Comment by austin987** [comment]
@dfitzpat yep, working as expected now, thanks for your help (and @KarenGhavam-lunarG).

**Comment by austin987** [comment]
Fixed locally*, haven't pushed it yet.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/8418d3c32e1fad024ef463b5a930a509b0d7b07b
