### ISSUE TITLE
Missing vcrun2015 DLL called in new version of Battle.net

### ISSUE THREAD

**Issue by codyf86** [Winetricks/winetricks#1369]
Wine Staging 4.12.1
Ubuntu 19.04

When updating to the newest version of Battle.net there is a call to a missing dll. I've seen similar issues with other games that were solved a few years ago, but sorry if this is the wrong place to post this, the actual call is.

'Call from 0x7b451923 to unimplemented function api-ms-win-crt-private-l1-1-0.dll._o_getenv'

After installing vcrun2015 the dll does not appear in the libraries section of winetricks.

**Comment by Kreyren** [comment]
Does it prevent any wineapp from working? 

yes -> make a winebug and it will be investigated with priority and we will try to make a workaround in winetricks for affected versions

no -> make a winebug and it will be investigates with kiw priority

**Comment by Kreyren** [comment]
relevant: https://github.com/Winetricks/winetricks/issues/597

**Comment by Kreyren** [comment]
relevant: https://github.com/wine-mirror/wine/search?q=api-ms-win-crt-private-l1-1-0.dll&type=Commits

Seems to be stub dll in wine so it would require a patch based on available info

**Comment by austin987** [comment]
> Does it prevent any wineapp from working?

Obviously, that's why the bug report was filed.
 
> no -> make a winebug and it will be investigates with kiw priority

I'm not sure what you mean by 'kiw', but it's absolutely a valid bug.

Both the 32 and 64 bit redistributable files ship this dll, so it shouldn't be hard to fix.

Please, don't make comments like that without actually investigating the bug. Misinformation is much worse than no information.

**Comment by Kreyren** [comment]
> I'm not sure what you mean by 'kiw', but it's absolutely a valid bug.

Edit: `high` priority, sorry 

> Please, don't make comments like that without actually investigating the bug. Misinformation is much worse than no information.

Sorry if I miss represent it, but I I meant to encourage filing a winebug and if it prevents something from working to get info what is not working to make a contrib since wine has lots of unimplemented features that are harmless ~~and winedevs call them nitpicking when I report them~~

**Comment by snake007v** [comment]
any ideas on how to temporarily workaroung this bug?

**Comment by mrAndersen** [comment]
Same issue here
```wine: Call from 0x7b453c5c to unimplemented function api-ms-win-crt-private-l1-1-0.dll._o_getenv, aborting```

**Comment by Kreyren** [comment]
@mrAndersen @snake007v What exactly is the issue? Battle.net won't open?

Possible solution:
> Both the 32 and 64 bit redistributable files ship this dll, so it shouldn't be hard to fix. (https://github.com/Winetricks/winetricks/issues/1369#issuecomment-540874848)

Willing to make MR once info is provided

**Comment by mrAndersen** [comment]
@Kreyren Ye, battle net won't open on wine 4.9, used wine 4.16 - and problem gone, i assume blizz just used some code that was not implemented in 4.9 version. All this happened via lutris if this matters...

**Comment by Kreyren** [comment]
This works on my end: https://github.com/Winetricks/winetricks/pull/1373/commits/581e95419cc843dd913e3f4542aaeb2208e180ac 

Please test :)

**Comment by codyf86** [comment]
Yes that commit fixed it, thank you! :)

**Comment by codyf86** [comment]
Please merge / commit this.

**Comment by Kreyren** [comment]
Do not close the issue untill commit is merged please o.O

its using `Fixes:..` So the commit will close this issue automatically on merge
