### ISSUE TITLE
REQUEST: Add z0z0z's mf patch

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1380]
Using this 'winehack?' https://github.com/z0z0z/mf-install fixes Children of Morta and simmilar games.

without it the game won't go past the initial video.

Should be implemented in verb?

Possible legal issue? https://github.com/z0z0z/mf-install/issues/1

These seems to be libraries from M$ -> Implement in `mf` verb?

Relevant: https://github.com/Winetricks/winetricks/issues/1132

TODO: File a winebug these should be implemented in WINE

Notice: Wine won't output anything helpful for unimplemented features for mf

Relevant: https://github.com/austin987/winetricks/commit/5d653bfd9f2282a1d77edd3e4ed71205be1c4894

**Comment by Chiitoo** [comment]
As a user, I don't think it's a good idea to add things that come from unofficial sources like this.  You could end up installing who knows what into a user's system.

Indeed, there are the possible legal issues, too, even though we're not packaging/hosting the files.  As such, it's no surprise that references to it were removed from Valve's GitHub issues/pull requests as well.

Up to Austin in the end of course.  ^^

**Comment by Kreyren** [comment]
> As a user, I don't think it's a good idea to add things that come from unofficial sources like this. You could end up installing who knows what into a user's system.

I checked the libs and they seem sane to me + checksum is used in case upstream changes them

> Indeed, there are the possible legal issues, too, even though we're not packaging/hosting the files. As such, it's no surprise that references to it were removed from Valve's GitHub issues/pull requests as well.

Most of the libraries used in winetricks are from 3rd party mirror or archive i don't see why would this be different assuming that using link to illegal? content is not illegal for the party that is using the link in Central Europe to my knowledge. 

Referencing Czech pirate party's statement: https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwiki.pirati.cz%2Fprojekty%2Fodkaz_neni_zlocin
Referencing: https://torrentfreak.com/pirate-party-prosecuted-for-operating-a-pirate-site-160125/
Referencing: https://arstechnica.com/tech-policy/2011/07/linking-is-not-a-crime-czech-pirate-party-declares-war-on-anti-piracy-unionlinking-is-not-a-crime-czech-pirate-party-declares-war-on-big-content/

In canada: https://news.softpedia.com/news/Supreme-Court-of-Canada-Linking-Is-Not-a-Crime-228825.shtml

---

If you have better mirror i'm willing to add it to the code.

**Comment by austin987** [comment]
In general, winetricks uses dlls from redistributables (i.e., Microsoft or others have said it's okay to share them).

Sometimes those files aren't on microsoft.com anymore, but third parties have them (again, with Microsoft's permission).

Taking binaries from windows and then checking them into github doesn't suddenly make them okay to distribute, legally. And as @Chiitoo pointed out, there's also a risk of malware.

**Comment by Kreyren** [comment]
@austin987 What do you suggest then?

I try to get review from whitehat for these files.

If @Microsoft is willing to share license to redistribution then what prevents us from making winetricks mirror?

---

Also why closing? This is attempt to resolve https://github.com/Winetricks/winetricks/issues/1132 using z0z0z's files.

**Comment by austin987** [comment]
Honestly, I'm not sure this is worth fixing, given that there isn't a redist from microsoft for this and it can end up making things worse (much like IE).

That said, there's a suggestion at https://github.com/Winetricks/winetricks/issues/1132#issuecomment-531486639 you could try.

**Comment by Kreyren** [comment]
@austin987 The z0z0z script works meaning it makes game children of morta working on wine, but it seems that winetricks does something differently when I adapt it. In logic for the registry z0z0z has them in his repository
