### ISSUE TITLE
sanitycheck: Make packages standalone from winetricks

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1387]
Proposing adapting a function that is fetching package instructions in system cache to be processed by winetricks and other package managers.

### Reasoning: 
winetricks is huge matrix of nightmare + more functionality assuming that `winetricks --self-update` would be for winetricks core only

### Example:

End-user downloads winetricks (much smaller script then current) and invokes `winetricks --update` to fetch all available packages in `/var/db/winetricks` for winetricks to be used

### Possibiliies:
Gentoo eclass -> Fetches winetricks packages using portage
Exherbo exheres - Fetches winetricks packages using exheres
apt -> Fetches winetricks packages using .deb
and other package managers..

Core of winetricks written in C++/Rustlang 

Allows third-party repositories

### Issues
Requires lots of rewriting (working on that atm)

Backend for MacOS

**Comment by Kreyren** [comment]
RESERVED

**Comment by KenSharp** [comment]
> Core of winetricks written in C++/Rustlang

Really? Is this really wanted? Right now I know how to send a patch because it uses a shell script. I'm not willing to learn C++ for this. It would also mean compiling for each platform, rather than just download a POSIX-compliant script.

**Comment by Kreyren** [comment]
@KenSharp This is just a concept the scripts would stay as POSIX sh, but winetricks_init and core related could be written in different lang for faster runtime.

or we could have both methods since winetricks's core is simple. The main point is the ability to have repositories in system that are standalone from winetricks (wr can make backend for portage, paludis, pacman, etc.. that way.

**Comment by austin987** [comment]
Yeah, I don't see this happening. If you're going to do this, fork the project and do it there.

**Comment by Kreyren** [comment]
> Yeah, I don't see this happening. If you're going to do this, fork the project and do it there.

could you provide more info? I'm planning to do this in fork, but If it's helpful here I would make a merge request

**Comment by austin987** [comment]
I don't like the idea in general, and I don't think the complexity of reimplementing in C/C++ would be worth the relatively minor gains.
