### ISSUE TITLE
QA: Prioritize cabextract over wine for dlls?

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1394]
Why are we not using cabextract to extract dlls from `foo.exe`? It seems to make everything faster and doesn't bother end-user with pop-ups..

**Comment by austin987** [comment]
Installer can do more than just extract dlls. There may be manifests or registry entries that we miss by just using cabextract.

What extra pops are you talking about?

**Comment by Kreyren** [comment]
> Installer can do more than just extract dlls. There may be manifests or registry entries that we miss by just using cabextract.

Why do we need manifests? 

for registry I guess that we could use current and then adapt changes in the cabextract method?

> What extra pops are you talking about?

For example for dotnet40+ it takes forever to install and it requires constant input from an end-user (main motivation since it's super annoying for debugging)

**Comment by austin987** [comment]
I'm not in a position to explain the winapi to you, you can Google that or look at wine bugzilla for past examples (in particular, msvc runtime).

Re: registry, that is a massive hack and impractical to replicate installers by hand if not needed.

For dotnet40, it doesn't use cabextract, so I fail to see your point.

**Comment by Kreyren** [comment]
Thanks for sanitycheck

**Comment by Kreyren** [comment]
@austin987 Apparently we can use 7-Zip from windows:
```console
kreyren@dreamon:~/.cache/winetricks/vcrun2015$ wine /home/kreyren/.wine/drive_c/Program\ Files\ \(x86\)/7-Zip/7z.exe x vc_redist.x86.exe 

7-Zip 19.00 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 13767776 bytes (14 MiB)

Extracting archive: vc_redist.x86.exe
         
[0]
WARNINGS:
There are data after the end of archive

--
Path = vc_redist.x86.exe
Type = PE
Physical Size = 13767776
CPU = x86
Characteristics = Executable 32-bit RemovableRun NetRun
Created = 2015-02-13 21:42:32
Headers Size = 1024
Checksum = 13774667
Image Size = 413696
Section Alignment = 4096
File Alignment = 512
Code Size = 234496
Initialized Data Size = 144896
Uninitialized Data Size = 0
Linker Version = 10.0
OS Version = 5.1
Image Version = 0.0
Subsystem Version = 5.1
Subsystem = Windows GUI
DLL Characteristics = Relocated NX-Compatible TerminalServerAware
Stack Reserve = 1048576
Stack Commit = 4096
Heap Reserve = 1048576
Heap Commit = 4096
Image Base = 4194304
Comment = 
{
FileVersion: 14.0.23026.0
ProductVersion: 14.0.23026.0
InternalName: setup
}
----
Path = [0]
Size = 13371304
Packed Size = 13371304
Virtual Size = 13371304
Offset = 380416
--
Path = [0]
Type = Cab
WARNINGS:
There are data after the end of archive
Physical Size = 133942
Tail Size = 13237362
Method = MSZip
Blocks = 1
Volumes = 1
Volume Index = 0
ID = 0

Everything is Ok

Archives with Warnings: 1

Warnings: 1
Files: 33
Size:       461518
Compressed: 13767776
kreyren@dreamon:~/.cache/winetricks/vcrun2015$ ls
0   u1	 u11  u13  u15	u17  u19  u20  u22  u24  u26  u28  u3	u31  u5  u7  u9			vc_redist.x86.exe
u0  u10  u12  u14  u16	u18  u2   u21  u23  u25  u27  u29  u30	u4   u6  u8  vc_redist.x64.exe
```

Investigating..

**Comment by Kreyren** [comment]
We also have `sqmapi.dll` which is required for `mf` verb

**Comment by zfigura** [comment]
In some cases only the DLL is needed (or at least, we *think* so), such as DirectShow DLLs. In other cases the installer adds all manner of other support infrastructure and it needs that all to exist. In the case of something like .NET it's simply impractical to correctly replicate.
