### ISSUE TITLE
REQUEST: Generate shortcut for Application Launcher

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1396]
End-user requested adapting function which generates a shortcut for application launcher (placing shortcut in /usr/share/applications).

Issue: Permission access from non-root in /usr/share/applications

Possible solution: Winetricks to request making a group in /usr/share/applications and assigning end-user in said group so that they have access?

**Comment by austin987** [comment]
I don't understand why this is needed. Wine itself will generate shortcuts (if the installer makes one).

In any case, there's  $WINETRICKS_SUDO.
