### ISSUE TITLE
QA: Use `ed` instead of `sed`  for file changes 

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1397]
Referencing:

```
<greybot> Some sed(1)s have -i which claims to "modify" files. It does not: sed is not a FILE editor. The -i flag re-writes the entire file and replaces the original with the new. This breaks open handles and hard-link sets, and fails to follow symlinks. -i is also unportable: valid sed on one system will write broken files on another. Use ed(1) or ex(1) instead: eg. ex -sc '%s/a/b/|wq' file
```

### Example use: 
```bash
printf '%s\n' 's%/1/2/g' w | ed -s "foo"
```

### instead of:
```shell
sed 's/1/2/g' foo > out
mv out foo
```

Recommends making a test to force usage of ed this way

**Comment by austin987** [comment]
A) Do you have an actual example of breakage?

B) you can run the tests yourself; don't depend on others to do so.

**Comment by Kreyren** [comment]
> B) you can run the tests yourself; don't depend on others to do so.

I did the tests based on which i'm proposing this QA

> A) Do you have an actual example of breakage?

It doesn't break anything both are valid, this is more of a code quality issue reasoning being:

- `sed` is stream editor so it should be used only for stream manipulation of variables and functions within the code since it requires two step process to make changes in file where we are manipulating stream to be then overwritten in the file which i believe is not ideal.

- `ed` Is file editor made for this usage which is changing the content in the file directly.

Pros: Less lines in the code doing the same thing

Cons: Requires loading another library where load time seems negligible (i don't know what would be the best way to benchmark this, willing to investigate if required)
