### ISSUE TITLE
`winetricks dlls list` requires a WINEPREFIX

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#1409]
```
austin@laptop ~ $ winetricks dlls list
ls: cannot access '/home/austin/.wine/drive_c': Not a directory
grep: /home/austin/.wine/*.reg: Not a directory
------------------------------------------------------
WINEPREFIX INFO:
Drive C: 

Registry info:
/home/austin/.wine/*.reg:
------------------------------------------------------
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: /home/austin/.wine is not a directory" 
```

might be related to #717

**Comment by Kreyren** [comment]
What is the expected outcome for this then? Afaik `winetricks_init()` and code section under (as "winetricks_init") it is called prior to `w_metadata()` to generate them.. Afaik it would require:
- assigning these `w_metadata()` and `winetricks_init` to be called after script reads all the functions
- Or spliting winetricks in sections for arguments to be grabbed at the top assuming that script can't read all the functions to get the metadata

Sidenote: i'm trying to resolve this in https://github.com/Winetricks/winetricks/pull/1359 where locally i have around 65K lines which doesn't work and requires more work..

**Comment by austin987** [comment]
https://github.com/austin987/winetricks/tree/wineprefix-cleanup handles this, but doesn't fix #717; I suspect that the refactor will make it easier though, looking at that next.

**Comment by Kreyren** [comment]
@austin987 assuming that you are willing to discuss this, how do you plan to handle metadata assuming that it seems that these sre saved in wineprefix itself. 

(I'm working on function that would use metadata to uninstall verbs)

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/7c102c46aeeaf3f693573ad7e323bf564b343d0b
