### ISSUE TITLE
dotnet452 fails

### ISSUE THREAD

**Issue by KenSharp** [Winetricks/winetricks#1410]
Running dotnet452 in quiet mode fails in a vague way.

    ------------------------------------------------------
    exit status 236 - dotnet452 installation failed
    ------------------------------------------------------

Running it in GUI mode, is, erm, not much more clear...

![dotnet452](https://user-images.githubusercontent.com/13607576/68023407-ecd62400-fc9e-11e9-8fee-147f1bfd68df.png)

I definitely do have more than 64u MB available (whatever that means).

At this point I don't know where the issue is so cannot fathom a workaround. Indeed the disk space calculation is a bit wrong so there's probably a Wine bug there.

[dotnet452.log](https://github.com/Winetricks/winetricks/files/3797795/dotnet452.log)

    $ wine --version
    wine-4.18
    $ winetricks --version
    20190912-next - sha256sum: 192dadb0ef20e6925552c6ac6e43b5ea4956ee1ff401948686ca929b54f5660e

**Comment by Kreyren** [comment]
Works on my system(tm)

<img width="267" alt="image" src="https://user-images.githubusercontent.com/11302521/68252352-96157500-0025-11ea-930d-32e56376c50c.png">

FWIW I remember this dotnet issue from before where i'm confident that it was ubuntu as well, maybe try staging?

**Comment by austin987** [comment]
I can't reproduce in 4.18/4.19/4.20 with/without mingw.

That said, could you try with 4.20? https://source.winehq.org/git/wine.git/commitdiff/cce9a5f124ae6d3fffcc7772cab6523f09a1e3d1 fixed issues with (at least) dotnet20sp2 and dotnet35sp1, maybe it helps here.

**Comment by llde** [comment]
works for me with 5.0 rc1.
Just installed it for MTGA Launcher

**Comment by austin987** [comment]
@KenSharp please retest with 5.0-rc* (which fixes https://bugs.winehq.org/show_bug.cgi?id=48277) and winetricks-20191224 (which has miscellaneous dotnet improvements).

**Comment by KenSharp** [comment]
Tested in Wine 5.0 and winetricks-20191224 and it fails in the same way.

However, Wine Staging 5.0 does not have this issue.

Turns out (I think) it's down to how Wine (mis-)handles TMPFS mounts, which I should have realised straight away, but alas... Completes fine on BTRFS mount.

So `tis a Wine bug. Not sure if it is logged though I did find some bugs that I couldn't say for certain are related. Anyway, that's for another day.

**Comment by austin987** [comment]
FWIW wine-5.0-144-g9a9a1821a3 works for me in ext4 and tmpfs. But yeah, it's a wine bug.

We could add a warning to the user that it will fail if their prefix is tmpfs, but I'd like to know that's actually why it's failing..

**Comment by KenSharp** [comment]
It works for you in a tmpfs? Okay, I'll have to look at this a little more later, but I just can't right now.

Just for reference: I found that very rarely the dotnet452 installer hangs after extraction, consuming two cores and apparently doing nothing. It's very rare but there could be something there too. That's for a Wine bug report of course, one day...
