### ISSUE TITLE
Attempt to educate the community to contribute in winetricks

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1412]
i've made a new wikipage https://github.com/Winetricks/winetricks/wiki/I'm-noob-and-i-want-to-help! which attempts to educate the community in contributing in winetricks

### Reasoning:
Based on my experience with wine users there is lots of users/developers who are willing to contribute in winetricks, but don't know how i want to attempt to change this and educate them so that they are able to make a contribution that is up to standard and i'm willing to invest my time in these users/developers.

Would this be acceptable for winetricks and is proposed method sufficient?

**Comment by tannisroot** [comment]
That guide just covers basics of Git and Github (and not even fully, it's missing some key steps). I am sure there plenty of guides online that cover the same things and in more detail.
So why does it have to be a part of Winetricks wiki?
Btw, maintainers might want to lock up Wiki to be edited only by members of the project to prevent vandalism.

**Comment by Kreyren** [comment]
@tannisroot Some people doesn't know how to use git to make a sufficient merge request so that page is expected to be referenced for those interested in contribution assuming that previous wikipage "How to make a side-fork" doesn't explain this in detail and that this wikipage is expected to provide explanation for basics for those who are not familiar with them.

**Comment by Kreyren** [comment]
referencing https://github.com/Winetricks/winetricks/pull/1413 which is first attempt for this kind of mentoring from me in winetricks.

**Comment by austin987** [comment]
Apparently it can't be locked down. Given there was only one page that was the usage, I'd rather just disable it.

**Comment by Kreyren** [comment]
@austin987 Well it proved to be helpful for debugging, but i move these in kreytricks then..
