### ISSUE TITLE
StarCitizen 3.7.1 - Textures are not loaded and stay black, except interactive elements (screens, mirrors...)

### ISSUE THREAD

**Issue by Manumerique** [Winetricks/winetricks#1416]
Hello ! I'm trying to launch StarCitizen 3.7.1, under Ubuntu 18.04, wine-staging 4.19, kernel 5.3.8, mesa 19.3 (oibaf), dxvk 1.4.4 on an AMD RX580. The game launches correctly, but most textures are not loaded and stay full black, except interactive elements (screens, mirrors...). Some people with nvidia dGPU seems to have more luck. I tried uninstalling dxvk (but was not 100% sure to succeed), and the got the same problem without DXVK (with 4x less FPS). Dont know if it's a mesa, dxvk, wine bug. Any workarounds to try ? I can help and investigate further if you could explain to me how to get the usefull debug infos.
![Capture d’écran de 2019-11-05 15-19-29](https://user-images.githubusercontent.com/29778631/68215653-e4078a00-ffdf-11e9-9b3a-ca3266000a01.png)
![Capture d’écran de 2019-11-05 15-20-32](https://user-images.githubusercontent.com/29778631/68215654-e4078a00-ffdf-11e9-91e3-e47cb488e981.png)

**Comment by Kreyren** [comment]
@Manumerique How did you install this game on wine?

**Comment by Manumerique** [comment]
I downloaded the installer from RSI website, then the installer installed the game. Everything works except the rendering issue (sound ok, hotas ok, movements and interactions ok)

**Comment by Kreyren** [comment]
From https://appdb.winehq.org/objectManager.php?sClass=version&iId=37903

```
Windows Version = Windows 10
Recommended Settings -
    nvapi & nvapi64 = disabled
    DXVK_HUD = 1
    __GL_SHADER_DISK_CACHE = true *
    __GL_SHADER_DISK_CACHE_PATH = /path/to/shader/location **
    __GL_SHADER_DISK_CACHE_SKIP_CLEANUP = true
```

Could you try these settings?

---

>  RSI website

provide link

**Comment by Kreyren** [comment]
Also attach wine log from the wineapp's runtime

**Comment by Manumerique** [comment]
Yes, I set Windows 10 and disabled nvapi64 in winecfg (I dont have nvapi) and tried this exact command in terminal, with same result :
`DXVK_HUD=1 __GL_SHADER_DISK_CACHE=true __GL_SHADER_DISK_CACHE_PATH=/home/manumerique/.scshaders __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=true wine RSI\ Launcher.exe`

/home/manumerique/.scshaders remains empty

**Comment by Kreyren** [comment]
@Manumerique waiting for requested info:
- Wine log
- RSI website from where you downloaded the game

**Comment by Manumerique** [comment]
The installer can be downloaded here, but you need an account and have a starter pack (50$) :+1: 
[https://robertsspaceindustries.com/](https://robertsspaceindustries.com/)

**Comment by Manumerique** [comment]
Here is the wine output from the above command line up to the time where the screenshot was taken
[sc.log](https://github.com/Winetricks/winetricks/files/3809507/sc.log)

**Comment by Kreyren** [comment]
> sc.log

Try to make a "paste" next time alike: https://gist.githubusercontent.com/Kreyren/b1b45cbdafe75ade9137b9b7a0e13cc7/raw/1ee6b29f79ab1729ef36e7fb9fad52ba18401719/gistfile1.txt

Which can be generated on `pastebin.com` or `gists.github.com`, `dpaste.com` or simmilar so that i don't have to download the file :p

**Comment by Kreyren** [comment]
@Manumerique 

> 006b:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0x1.

is mensioned in your log, but i don't know if it's related, try using dxvk and report back with another wine log

**Comment by Manumerique** [comment]
Ok, I'll remember :)
Also tried with RADV_PERFTEST=aco (tip from #dri-devel), with same result.

**Comment by Manumerique** [comment]
@Kreyren I'm already using DXVK.
I downloaded the last one from [https://github.com/doitsujin/dxvk/releases/tag/v1.4.4](https://github.com/doitsujin/dxvk/releases/tag/v1.4.4)
Then in the right folder I executed `./setup_dxvk.sh install`
It altered my winecfg like that 
![Capture du 2019-11-05 15-57-17](https://user-images.githubusercontent.com/29778631/68218677-064fd680-ffe5-11e9-95c9-dc88bbcd2fae.png)

**Comment by Kreyren** [comment]
>  RADV_PERFTEST=aco (tip from #dri-devel)

Context? What is that supposed to do?

**Comment by Manumerique** [comment]
> > RADV_PERFTEST=aco (tip from #dri-devel)
> 
> Context? What is that supposed to do?

I'm not sure. I guess it is supposed to use ACO as a shader compiler ? Worth the try

**Comment by Kreyren** [comment]
>  I'm already using DXVK.

The DXVK libs are not called in the log which is unexpected.. Can you provide output of `glxinfo | grep OpenGL` ? I suspect that your vulkan is not configured correctly

**Comment by Manumerique** [comment]
`glxinfo | grep OpenGL`
```
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.8-050308-generic, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.0-devel (git-ff6e148 2019-10-29 bionic-oibaf-ppa)
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.0-devel (git-ff6e148 2019-10-29 bionic-oibaf-ppa)
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.0-devel (git-ff6e148 2019-10-29 bionic-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

My DXVK_HUD (from the above pictures) says that vulkan is used, but I could be wrong

**Comment by Manumerique** [comment]
Related topic : [Reddit](https://www.reddit.com/r/starcitizen/comments/ddyldv/the_vulkan_api_switch_cant_come_soon_enough/)

**Comment by Manumerique** [comment]
Trying this solution : [Reddit](https://www.reddit.com/r/starcitizen/comments/ddyldv/the_vulkan_api_switch_cant_come_soon_enough/f3epbot/?context=3)

**Comment by austin987** [comment]
This isn't a winetricks issue.

**Comment by Kreyren** [comment]
> This isn't a winetricks issue.

would agree looks like dxvk issue, but dxvk libs are not called so this seems to run on winelibs

**Comment by Manumerique** [comment]
> > This isn't a winetricks issue.
> 
> would agree looks like dxvk issue, but dxvk libs are not called so this seems to run on winelibs

DXVK was used in my previous tests ! See the screenshot and clearly, there was 3x/4x more performance when using it.

**Comment by Manumerique** [comment]
Ok, so with Lutris, it worked without any modifications !
The texture problem is because of some recent changes in StarCitizen 3.7 where vcrun2017 is needed.
I tried installing vcrun2017 with winetricks under wine-staging 4.19,
`./winetricks -q vcrun2017`
but it didn't work (I may have forgot something).
Lutris does the job anyway, but can't post a report on WineHQ, since I now use Lutris.
Still, was an interesting walkthrough, I hope informations in this issue could help someone.

**Comment by Kreyren** [comment]
> DXVK was used in my previous tests ! 

Yes but if DXVK is used it should output in winelog it's init which didn't happend.. but you have the HUD in game so i guess it runs.. 

This is lutris installer: https://lutris.net/games/install/10872/view

It doesn't seem to be using something major so it may not be a DXVK issue.

I would try making an installer for winetricks in kreytricks (so that austin doesn't complain about inbox spam) assuming that you are willing to test it

**Comment by Manumerique** [comment]
Hello ! I agree it's probably not a DXVK issue, as Lutris uses the same version I did (1.4.4)
I made this issue after you asked me to on freenode, so I don't understand why it is considered as spam.
I would be glad to test your installer, as my first goal was to post a review on winehq :)

**Comment by Kreyren** [comment]
> I made this issue after you asked me to on freenode

austin doesn't want these kind of issues in winetricks so i transfer it in kreytricks. Sorry about that.
