### ISSUE TITLE
Warcraft-III-Setup.exe fails with Bnet Desktop App

### ISSUE THREAD

**Issue by AtreusX** [Winetricks/winetricks#1417]
Working with 32 bit wine install, I install battle.net app and then run the classic game installer for Warcraft III (only newer games are directly installable in the app, older games you use an installer). Installer downloads game but fails when asking for CD Key.

Steps: 
1) Download and install battle.net desktop app.
2) Download and run Warcraft-III-Setup.exe
3) After it downloads which takes awhile run 
         wine .wine32/drive_c/Program\ Files/Warcraft\ III/Warcraft\ III\ Launcher.exe 

(Make sure bnet app is running or it won't work e.g. wine .wine32/drive_c/Program\ Files/Battle.net/Battle.net\ Launcher.exe)
------------------------------------------------------
Using winetricks 20190912-next - sha256sum: f7c62144ed37ff64001724e5ea0cc41e7a861414d4e9cf4d665c694ec078894c with wine-4.19 and WINEARCH=win32
-------------------------------------------------------
https://www.blizzard.com/en-gb/apps/battle.net/desktop
https://us.battle.net/download/getInstallerForGame?os=win&locale=enGB&version=LIVE&gameProgram=WARCRAFT_3
[war3.log](https://github.com/Winetricks/winetricks/files/3812369/war3.log)

**Comment by Kreyren** [comment]
iirc from IRC it seems that dotnet libs interfiere with battle.net runtime, if so they probably needs to be disabled per wineapp.

@AtreusX Can you verify if BattleNet  works without dotnet? (my installer in winetricks requires only vcrun2012 on my system)

**Comment by Kreyren** [comment]
Transfered in kreytricks on @austin987's demand: https://github.com/Kreytricks/kreytricks/issues/14
