### ISSUE TITLE
Regression introduced by f40b465

### ISSUE THREAD

**Issue by Kreyren** [Winetricks/winetricks#1431]
Referencing https://github.com/Winetricks/winetricks/pull/1429

My contribution caused a regression which we weren't aware about at the time of merge and so I'm trying to adapt my/upstream workflow to prevent this code in upstream. 

To prevent regression alike I'm proposing adding a test for travis would that be a sufficient? 

I'm asking here since I'm not sure if winetricks's travis has processing power for such test assuming that it's already hitting timeout on macos. 

btw. thanks bobwya for the fix

**Comment by austin987** [comment]
Yes, a test would be very welcome.
