### ISSUE TITLE
Art2kmin Checksum Mismatch

### ISSUE THREAD

**Issue by masternetra** [Winetricks/winetricks#1432]
Attempting to install art2kmin results in a sha256sum mismatch. Have tried deleting the download in cache and trying again with same result.

Prefix Architecture: 32bit 
Wine Version: 4.20
Winetricks Version: 20190912

**Comment by Kreyren** [comment]
@masternetra Provide a log

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/f12e7cdfaf16617c7848a868435c535c351a8ab3
