### ISSUE TITLE
Winetricks counting fonts & Components as installed acrossed all prefixs

### ISSUE THREAD

**Issue by masternetra** [Winetricks/winetricks#1433]
I created a new prefix with winetricks for testing and found that it refuses to install any fonts or components/DLLs that I have installed in another prefix. I swapped to my 64bit prefix, to which I have nothing installed into it as of yet and tried installing the same things with it refusing to do it claiming it was already installed.

Wine Version: 4.20
Winetricks Version: 20190912 (Commit: f12e7cd)

Console output for the new 32bit test prefix;

```
censored@censored:~$ winetricks
Using winetricks 20190912-next - sha256sum: a862faa213164b154a4b01a2933ddb063c41e3a4ed4fcc5cfb91d0f5c7f20b7d with wine-4.20 and WINEARCH=win32
winetricks GUI enabled, using zenity 3.28.1
Gtk-Message: 13:42:42.735: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 13:42:50.917: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 13:43:02.065: GtkDialog mapped without a transient parent. This is discouraged.
Executing w_do_call corefonts
corefonts already installed, skipping
Gtk-Message: 13:43:10.311: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 13:43:14.675: GtkDialog mapped without a transient parent. This is discouraged.
Executing w_do_call d3dx9
d3dx9 already installed, skipping
Gtk-Message: 13:45:26.586: GtkDialog mapped without a transient parent. This is discouraged.
```

Console output when attempting to install the same to things to my fresh and unused 64bit prefix.

```
censored@censored:~$ winetricks
Using winetricks 20190912-next - sha256sum: a862faa213164b154a4b01a2933ddb063c41e3a4ed4fcc5cfb91d0f5c7f20b7d with wine-4.20 and WINEARCH=win32
winetricks GUI enabled, using zenity 3.28.1
Gtk-Message: 13:44:52.658: GtkDialog mapped without a transient parent. This is discouraged.

You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

Gtk-Message: 13:44:58.190: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 13:45:00.607: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 13:45:06.068: GtkDialog mapped without a transient parent. This is discouraged.
Executing w_do_call corefonts
corefonts already installed, skipping
Gtk-Message: 13:45:13.455: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 13:45:17.744: GtkDialog mapped without a transient parent. This is discouraged.
Executing w_do_call d3dx9
d3dx9 already installed, skipping
Gtk-Message: 13:45:26.586: GtkDialog mapped without a transient parent. This is discouraged.
```
Again I have those things installed in my normal 32bit prefix but not in my test or 64bit prefixes

**Comment by austin987** [comment]
Can you try with HEAD? https://github.com/Winetricks/winetricks/commit/9992bfc64626a8ae222277b6762cea99de355570 should help with this.

**Comment by masternetra** [comment]
> Can you try with HEAD? [9992bfc](https://github.com/Winetricks/winetricks/commit/9992bfc64626a8ae222277b6762cea99de355570) should help with this.

I'm using winetricks as of f12e7cd which you did 2 hours ago, wouldn't 9992bfc be included?

**Comment by masternetra** [comment]
Yea changes of 9992bfc are and have been there.

**Comment by masternetra** [comment]
Nevermind I see what's it doing. It's installing to all the prefixs and cloning everything to new prefixes, which I don't want and would like to disable if possible...

**Comment by austin987** [comment]
executables are run in an individual prefix, I don't see how things could be copied to everything.

Could you give more clear instructions please? I.e., what prefixes (path/arch) is used, and what winetricks commands you ran? Does it occur with cli as well, or just gui?

**Comment by masternetra** [comment]
I've been just been using the gui. To setup prefixes and install stuff. Switching to silent mode (in the gui) at times. I've just wiped everything and going to try again to see if the issue persists. brb

**Comment by masternetra** [comment]
From fresh, launched winetricks (gui, and from terminal) created "wine32" 32bit prefix, and "wine64" 64bit prefix.
- selected wine32 
- installed corefonts, Getting 64bit warning?? (despite selecting 32 for architecture when making it)
- backed out to first winetricks menu
- selected wine64
- attempted to install corefonts, claimed it was already installed.
- went back to winetrick's main menu
- selected wine32
- attempted to install dotnet1.1 - failed claimed prefix was 64bit and couldn't do it.
- went back to wine32 and deleted prefix (winetricks closes out, checked .local/share/wineprefixes and it's folder was successfully removed).
- launched winetricks again, created a new wine32, triple check to ensure 32 was selected for architecture.
- went to wine32 
- attempted to install corefonts, got 64bit warning again, and it refused again claiming it was already installed.
- went back to wine32
- installed quicktime 7.6 (got 64bit warning)
- quit winetricks after it was done.
- went into .local/share/wineprefixes
- Didn't find quicktime.
- went into .wine, found quicktime.
Just a semi-educated guess but looks like it's installing into and only look at default but somehow was duplicating stuff into other prefixes later on??? I honestly don't know what else to take from all this and the prior experiences...

**Comment by masternetra** [comment]
hmm haven't been able to reproduce the duplication thing, a weird quark??

**Comment by austin987** [comment]
I guess, I didn't see how this could happen to begin with :p.
