### ISSUE TITLE
dotnet35 fails on wine 4.20 (normal or staging)

### ISSUE THREAD

**Issue by llde** [Winetricks/winetricks#1441]
Hi, trying to install dotnet35 (but also 30) is failing with a exit status 67 - dotnet35 installation failed
This is with wine staging but also normal wine is failing
New wineprefix, 32 or 64bit arch.
ArchLinux x86_64

Attach a gist with the wine log:
https://gist.github.com/llde/b88e3c7828d7f63eb11692e41df75dfd

In particular these lines seems important (they are not consecutive in wine log):
01f7:err:eventlog:ReportEventW L"WMI classes are not installed."

01f7:err:eventlog:ReportEventW L"System.ComponentModel.Win32Exception: Chiamata non implementata\r\n   at System.ServiceModel.Install.HttpNamespaceReservationInstallComponent.get_IsInstalled()\r\n   at System.ServiceModel.Install.HttpNamespaceReservationInstallComponent.Uninstall(OutputLevel outputLevel)\r\n   at System."...

0030:err:msi:execute_script Execution of script 0 halted; action L"[C:\\windows\\Microsoft.NET\\Framework\\v3.0\\Windows Communication Foundation\\ServiceModelReg.exe /r /x /y /v;dummy;C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\<=>S-1-5-21-0-0-0-1000<=>{2BA00471-0328-3743-93BD-FA813353A783}]DD_CA_InstallXwsRegExe_X86.3643236F_FC70_11D3_A536_00902"... returned 1603
0030:err:msi:ITERATE_Actions Execution halted, action L"InstallExecute" returned 1603

**Comment by austin987** [comment]
Thanks for the report. There are a few interrelated upstream issues. I'm looking into it.

**Comment by austin987** [comment]
Minor update: https://source.winehq.org/git/wine.git/commitdiff/280bfb58b5162be6d8cee8827307721d7624ac0d fixes things if wine is compiled without mingw support.

If mingw is enabled, there's a conflict between native and builtin ngen.exe that will require a change to winetricks. I'm working on a patch, but it'll take a bit of time to test the various combinations (wine versions, mingw/no mingw).

**Comment by llde** [comment]
I tested with wine 5.0 rc1 (staging-TKG) and dotnet35 install succesfully again. (It seems to work but I haven't test it extensively)

**Comment by austin987** [comment]
It was an upstream issue, now fixed (https://bugs.winehq.org/show_bug.cgi?id=48277). Winetricks (as of winetricks-20191224) will bail out with an error if using an unsupported version.
