### ISSUE TITLE
Winetricks installs components into incorrect (default) prefix

### ISSUE THREAD

**Issue by OzFalcon** [Winetricks/winetricks#1442]
Wine Version: wine-4.0.2
Winetricks Version: 20190912-next

When I run winetricks: `WINEARCH=win32 ./winetricks`
Then create/select a new wineprefix and install any components (Fonts or DLL) then winetricks installs said component into the DEFAULT wineprefix `/home/user/.wine` instead of the selected wineprefix.
Note: The top of the GUI shows the correct prefix - But winetricks doesn't use it.

The only way to install components into a specific prefix is to start winetricks with WINEPREFIX=
`WINEPREFIX=/home/user/someprefix ./winetricks`
Note: This opens up the "Choose a wineprefix" dialog - When has no effect, As the command line WINEPREFIX overrides ANY selection (Default, New or otherwise).

**Comment by OzFalcon** [comment]
Perhaps my version of Wine needs to be updated???
./winetricks --help shows
```
arch=32|64 ...
prefix=foobar ...
```
Which don't seem to work for me (Only WINEARCH & WINEPREFIX seem to work)

**Comment by OzFalcon** [comment]
Update: I looked at installing Wine 4.20 via the instructions here: https://wiki.winehq.org/Debian
But decided against it because it wanted to change (& remove) so many packages from my system.

**Comment by masternetra** [comment]
Pretty sure this correlates to my issue: https://github.com/Winetricks/winetricks/issues/1433

**Comment by austin987** [comment]
Reported working; in any case, winetricks-20191224 has a fix for this.
