### ISSUE TITLE
winetricks ie7 fails to overide wineie

### ISSUE THREAD

**Issue by Techwolf** [Winetricks/winetricks#1445]
After using winetricks ie7, using wine 'C:\Program Files\\Internet Explorer\\iexplore' only brings up wine internet explorer, not the real ie7 that I need to use on OEM website that uses a plugin not aviable for anything but ie6-8.

wine-4.20 (Staging)

**Comment by austin987** [comment]
Similar to #1423, it now needs an explicit setting for native ieframe.

Fixed by https://github.com/Winetricks/winetricks/commit/9831e4cc74538c70fc9e9a5f3bdbde090be02f42

**Comment by Techwolf** [comment]
Just tested it, setting ieframe to native, builtin fixed it on my end. :-)
