### ISSUE TITLE
winamp dead link

### ISSUE THREAD

**Issue by MrIcedTea** [Winetricks/winetricks#1446]
hi there, 

i am just trying out some of your autoinstallers, work very grate, but ive found one that dosnt download do to dead link, so please replace https://winampplugins.co.uk/Winamp/winamp5666_full_all_redux.exe with https://web.archive.org/web/20150913043127if_/http://winampplugins.co.uk/Winamp/winamp5666_full_all_redux.exe or something else that is working.

thanks and keep up the good work

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/75ef86e5273e791673b28496f0df693fc4a6c5bc
