### ISSUE TITLE
Possible error in expansion of W_PROGRAMS_UNIX

### ISSUE THREAD

**Issue by PietJankbal** [Winetricks/winetricks#1451]
Hi , after applying patch below to show what  W_PROGRAMS_X86_UNIX and  W_PROGRAMS_UNIX expand to I get this:
command ran:
WINEPREFIX=~/.winetmp WINE=/opt/wine-staging/bin/wine ./winetricks winxp

console output:
W_PROGRAMS_UNIX is equal to /home/louis/.winetmp/dosdevices/c:/Program Files (x86)
W_PROGRAMS_X86_UNIX is equal to /home/louis/.winetmp/dosdevices/c:/Program Files (x86)
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------

Shouldn`t W_PROGRAMS_UNIX  expand to Program Files (and not Program Files (x86))?
Or am I missing something/ understanding things wrong?
This issue blocks me finishing my new verb ie8_server script...

applied patch:
--- ./winetricks.orig	2019-12-16 22:44:07.845329337 +0100
+++ winetricks	2019-12-16 22:42:24.679437284 +0100
@@ -4883,6 +4883,9 @@
         W_PROGRAMS_X86_UNIX="${W_PROGRAMS_UNIX}"
     fi
 
+    echo "W_PROGRAMS_UNIX is equal to "$W_PROGRAMS_UNIX""
+    echo "W_PROGRAMS_X86_UNIX is equal to "$W_PROGRAMS_X86_UNIX""
+
     W_APPDATA_WIN="$(w_expand_env AppData)"
     # shellcheck disable=SC2034
     W_APPDATA_UNIX="$(w_pathconv -u "$W_APPDATA_WIN")"**

**Comment by austin987** [comment]
It depends on how wine was started. In a 64-bit build, you should have `wine` and `wine64`.

Running `wine` will start a 32-bit process, which gives you `c:/Program Files (x86)`. If you instead run `wine64`, you should get `c:/Program Files`.

You can override what winetricks uses with `WINE=...`. Note that there was a recently reported issue about setting WINE and WINE64 (#1454) that I haven't looked into as I'm currently travelling.

**Comment by PietJankbal** [comment]
Thanks for your answer. 

I can invoke the installer both with wine or wine64, it both works when i run it without winetricks script. How would i know how a user invokes winetricks?

And maybe the problem I have is this:
file ~./cache/ie8_server2003/IE8-WindowsServer2003-x64-ENU.exe: PE32 executable (GUI) Intel 80386, for MS Windows

So that looks like 32-bit exe, but it contains both 32- and 64-bit stuff that has to be installed in Program\ Files and Program Files x86 i.e. the installer contains:
file iexplore.exe
iexplore.exe: PE32+ executable (GUI) x86-64, for MS Windows

file wow/wiexplore.exe
wow/wiexplore.exe: PE32 executable (GUI) Intel 80386, for MS Windows

The installer has to put the first one in Program\ Files , and the last one (after renaming) in Program Files (x86) (and it does that ok) but i have to manually copy stuff in those two directories and  both W_PROGRAMS_UNIX and W_PROGRAMS_X86_UNIX resolve to :Program Files (x86)

You have an idea how to tackle this? Thanks

**Comment by austin987** [comment]
I won't be able to look/test for a couple weeks, but I suspect that we'll need to refactor the definitions of W_PROGRAMS_X86_UNIX. Something like (untested):

```
if [ "$W_ARCH" = "win64" ]; then
    # Force using wine64 so we get the 64-bit rather than 32-bit dir
    W_PROGRAMS_WIN="$(WINE=\"$WINE64\" w_expand_env ProgramFiles)"
    W_PROGRAMS_UNIX="$(w_pathconv -u "$W_PROGRAMS_WIN")"
    W_PROGRAMS_X86_WIN="${W_PROGRAMS_WIN} (x86)"
    W_PROGRAMS_X86_UNIX="${W_PROGRAMS_UNIX} (x86)"
else
    W_PROGRAMS_X86_WIN="${W_PROGRAMS_WIN}"
    W_PROGRAMS_X86_UNIX="${W_PROGRAMS_UNIX}"
fi
```

feel free to beat me to that ;)

**Comment by PietJankbal** [comment]
Hi,

I think it`s after all not really an error in winetricks script. When you check env. variables in cmd I get  this:
 with wine:
ProgramFiles=C:\Program Files (x86)
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files

and with wine64:
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files

So what I really need AFAICT is some variable that gives me the unix path to ProgramW6432
I see that there is already something like that for CommonProgramW6432 but i don`t 100% get the code there. Do you have an idea how to tackle this?

Note: maybe i should close this issue and continue discussion in the ie8_server2003 issue?
Regards

**Comment by austin987** [comment]
Try https://github.com/austin987/winetricks/commit/05aaadca486073076b9e824a9b4edcf2599e6cc8

**Comment by PietJankbal** [comment]
Yes thanks that works!

I finished script and it works ok, both when invoked by wine or wine64 ,
 see diff at https://raw.githubusercontent.com/PietJankbal/temporary_stuff/master/log

I`ll do a pull request when my other pull request is settled down.

Regards

PS shall i close this issue? Tiltle is not reflecting what it`s really about

**Comment by PietJankbal** [comment]
script is at https://raw.githubusercontent.com/PietJankbal/temporary_stuff/master/ie8_server2003.txt
