### ISSUE TITLE
Provide other mfc* verbs

### ISSUE THREAD

**Issue by gverm** [Winetricks/winetricks#1455]
It would be nice to have the mfc1* dlls in separate verbs. Mostly for debugging purposes (as to only install/override the things you absolutely need).

I might have a look at this myself if I have time, but anyone can feel free to have a go at it.

**Comment by rmi1974** [comment]
I can support this request. When triaging bugs I always need to clean up the msvcrt runtimes bits (removing overrides/manifest data) afterwards to only get the MFC part. When testing you don't want any native msvcr*/msvcp* overrides unless there is another bug related directly related to it.

**Comment by austin987** [comment]
@rmi1974 the newer vcruntimes also have a few more mfc* dlls:
```
src/winetricks:    title="Visual C++ 2003 libraries (mfc71,msvcp71,msvcr71)" \
src/winetricks:    title="Visual C++ 2005 libraries (mfc80,msvcp80,msvcr80)" \
src/winetricks:    title="Visual C++ 2008 libraries (mfc90,msvcp90,msvcr90)" \
src/winetricks:    title="Visual C++ 2010 libraries (mfc100,msvcp100,msvcr100)" \
src/winetricks:    title="Visual C++ 2012 libraries (atl110,mfc110,mfc110u,msvcp110,msvcr110,vcomp110)" \
src/winetricks:    title="Visual C++ 2013 libraries (mfc120,mfc120u,msvcp120,msvcr120,vcomp120)" \
src/winetricks:    title="Visual C++ 2015 libraries (concrt140.dll,mfc140.dll,mfc140u.dll,mfcm140.dll,mfcm140u.dll,msvcp140.dll,vcamp140.dll,vccorlib140.dll,vcomp140.dll,vcruntime140.dll)" \
```

i.e., mfc110u, mfc120u, msfc140u,mfcm140, mfcm140u, do you want those included as part of mfc110/mfc120/mfc140, or as separate verbs?

**Comment by gverm** [comment]
@austin987 Are you working on this? If not, you can assign this to me. (I can't seem to do that myself, even though it's my issue)

**Comment by austin987** [comment]
I haven't started yet. Happy to give work away ;).
