### ISSUE TITLE
Missing cabextract not reported on CLI

### ISSUE THREAD

**Issue by calllib** [Winetricks/winetricks#1467]
When using winetricks to install dotnet, cabextract is required. If this is missing, the GUI will issue a pop up saying so. However, when using the CLI to install dotnet, the fact that cabextract is missing is not mentioned. The installation terminates without error and without success.

(winetricks 20191224-next)

**Comment by gverm** [comment]
@calllib What version of dotnet were you trying to install?

**Comment by austin987** [comment]
dotnet35/dotnet35sp1/dotnet45/dotnet452 all verify that cabextract is available, fwiw.

Can't do much without knowing what you were trying.
