### ISSUE TITLE
Why no winetricks on RHEL EPEL?

### ISSUE THREAD

**Issue by jatin-cbs** [Winetricks/winetricks#1470]
On RHEL EPEL we dont have winetricks. We have other packages of wine but no winetricks :( Any manual installation guide if you dont want to provide it for CentOS/RHEL.

**Comment by austin987** [comment]
That's a question for Redhat; I don't package it for any distro, distro maintainers do.

Manual instructions are in the readme, https://github.com/Winetricks/winetricks/.

Note that they say Debian/Ubuntu, but everything after `apt-get remove winetricks` is distro agnostic.
