### ISSUE TITLE
(macOS) winetricks wineserver not found

### ISSUE THREAD

**Issue by The-SamminAter** [Winetricks/winetricks#1478]
I've installed winetricks on macOS 10.12, by following [these](https://wiki.winehq.org/Winetricks#Getting_winetricks) instructions. I have Wine Devel v5.0~rc6 installed.
Here is what happens:
```
$ sh winetricks
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
wineserver not found!
------------------------------------------------------
```
I've also tried installing winetricks via homebrew, but that gave me the same error.

**Comment by Gcenx** [comment]
This isn’t a winetricks issue.

On macOS the winehq packages are not added to PATH, you need to ether launch the “Wine Devel” app bundle or follow [these instructions](https://wiki.winehq.org/MacOS_FAQ#How_to_launch_wine_from_terminal_instead_of_the_wine_application.3F) I’d added these a while back.
