### ISSUE TITLE
Exit code 1 when cancel Winetricks windows

### ISSUE THREAD

**Issue by danger89** [Winetricks/winetricks#1479]
Hi,

Small issues, but non the less irritating when Winetricks is used for automation within scripts. 

Reproduction: When you open Winetricks GUI, and select the current bottle in the menu.  Then you cancel the Window and later just cancel Winetricks all together. For some reason the exit code will be put to '1'. Which indicates something went wrong.

This is a flaw in the design in my opinion! I would only except non-zero exit codes when something is really wrong.

For example: Let's say some installation of a package abc or DLLs overrides goes wrong. Than I would except the command to exit a non-zero value.

However in good weather behaviors, like just closing Winetricks, to **always** have an exit code of zero (0). 

Thank you so much!

Ps. Of-course I'm using the latest winetrick version from Github.

Regards,
Melroy van den Berg

**Comment by danger89** [comment]
If you need more info, let me know!

**Comment by austin987** [comment]
I'm not seeing that with zenity-3.30.0. I.e.,
$ winetricks
# select default prefix
# cancel; cancel
$ echo $?
0

same if I select an existing non-default prefix. Are you using something other zenity, or a different set of steps?

**Comment by danger89** [comment]
Maybe try clicking default bottle -> install windows dlls. Cancel, cancel and cancel.

**Comment by austin987** [comment]
Nope; fine here.

**Comment by danger89** [comment]
https://www.youtube.com/watch?v=7Tkit-Bipko&feature=youtu.be

**Comment by danger89** [comment]
Extra logging:

```
(zenity:12534): Gtk-WARNING **: 20:16:06.883: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12534): Gtk-WARNING **: 20:16:06.883: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12534): Gtk-WARNING **: 20:16:06.883: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12534): Gtk-WARNING **: 20:16:06.883: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: 20:16:07.119: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:12544): Gtk-WARNING **: 20:16:09.178: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12544): Gtk-WARNING **: 20:16:09.178: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12544): Gtk-WARNING **: 20:16:09.178: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12544): Gtk-WARNING **: 20:16:09.178: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: 20:16:09.366: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:12558): Gtk-WARNING **: 20:16:10.728: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12558): Gtk-WARNING **: 20:16:10.729: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12558): Gtk-WARNING **: 20:16:10.729: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(zenity:12558): Gtk-WARNING **: 20:16:10.729: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: 20:16:10.920: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by danger89** [comment]
Same issue with sha256sum: 673776e16c5272116a828a8d13fb36af171b930c7c1caeffd578314e3f0e9ae5

**Comment by danger89** [comment]
**Zenity version:** 3.28.1-1. Any more info you need?

**Comment by austin987** [comment]
A log with -v (or sh -x winetricks) would be useful; though to be honest if I can't reproduce this it's likely going to be a PITA to track down via logs. You'll likely have better luck doing so yourself.

**Comment by danger89** [comment]
Non-zero (by clicking on the default bottle and than cancel, cancel, ..) log:
[wine_clicking_default_bottle_causing_non_zero_exit_code.log](https://github.com/Winetricks/winetricks/files/4110967/wine_clicking_default_bottle_causing_non_zero_exit_code.log)

Zero exit (as it should be), by NOT clicking on the default bottle option in the menu:
[wine_reference_run_NOT_clicking_default_bottle_zero_exit_code.log](https://github.com/Winetricks/winetricks/files/4110968/wine_reference_run_NOT_clicking_default_bottle_zero_exit_code.log)

**Comment by danger89** [comment]
Damm*t I just gonna debug this issue via VS Code Bash debugger..

![image](https://user-images.githubusercontent.com/628926/73109205-cd980d00-3f02-11ea-9032-7dc1eac7b562.png)

**Comment by danger89** [comment]
I replaced all "exit 1" pieces in winetricks to "exit 0". Problem still happens.. meaning the exit caused by something else!? :confused:

**Comment by danger89** [comment]
I found something! Its stated in your code... Line 267: `# If user cancels, exit status is 1`

Line 278: `# Zenity has no cancel button, but will set status to 1 if you click the go-away X`

**Comment by danger89** [comment]
OK found it! Since it also happened when I pressed on other buttons and even when I disabled the second submenu (winetricks_mainmenu). I though it was to be something later in the program...

Conclusion: It's because of the winetricks_stats_report() call! Line 22445. What a line number.. the technical debt worse then I thought :cactus:

**Comment by danger89** [comment]
Root-cause: `test -f "$WINETRICKS_WORKDIR"/breadcrumbs || return`. Line 22111.

**Comment by danger89** [comment]
This line causes the `test` command to set the exit code for the whole script.

I propose the following alternative (how test should be used within a shell script).

Within the winetricks_stats_report() function:
```
    BREADCRUMBS_FILE="$WINETRICKS_WORKDIR"/breadcrumbs
    if test -f "$BREADCRUMBS_FILE"; then
        WINETRICKS_STATS_BREADCRUMBS=$(tr '\012' ' ' < "$BREADCRUMBS_FILE")
        echo "You opted in, so reporting '$WINETRICKS_STATS_BREADCRUMBS' to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  Use --optout to disable future reports."

            .... the rest .....
        else
            w_die "Here be dragons"
        fi
    fi
```

**Comment by danger89** [comment]
This root-cause triggers me, that you may want to look for other misuses of the test command directly. Line the following methods in your winetricks script:

* winetricks_metadata_exists() => `test -f "$WINETRICKS_METADATA"/*/"${1}.vars"`
* load_ie6() => `test -f "$W_SYSTEM32_DLLS"/$dll.dll &&`
* load_ie7()
* load_ie8()
* w_download_to() => `test -f "$_W_file" && rm "$_W_file"`

**Comment by danger89** [comment]
As you can see.. created a PR :+1:

**Comment by danger89** [comment]
Setting a new virtual desktop in a separate thread also returns error exit code (1). I think this has to do with this part of the code:

```
        # Hack..
        if test "$cmd" = vd; then
            load_vd "$arg"
            _W_status=$?
            test "$W_OPT_NOCLEAN" = 1 || rm -rf "$W_TMP"
            mkdir -p "$W_TMP"
            return $_W_status
        fi
```
The `load_vd` method does not set an explicit exit code when successful (only in error cases). So do not know what is   `_W_status=$?` is doing.. But I think it will get the exit code of `test "$cmd" = vd`, causing issues.

**Comment by austin987** [comment]
_W_status would be set to the exit value of the last command, i.e., w_try_regedit(). You can test that by putting 'false' after w_try_regedit(), _W_status will then be 1, even though there wasn't an explicit return 1 from the function.
