### ISSUE TITLE
Consider another font for fakechinese

### ISSUE THREAD

**Issue by huupoke12** [Winetricks/winetricks#1490]
As I see, the [WenQuanYi](https://sourceforge.net/projects/wqy/) project is basically dead since there are no new release for nearly 10 years, and no update for 7 years. I noticed bugs in the Micro Hei font for the Vietnamese characters but I can't create a new ticket for it.

**Comment by austin987** [comment]
Do you have a suggestion for what to use instead?

**Comment by huupoke12** [comment]
I suggest using Noto CJK/Source Hans Sans because of its quality. We can even consider using this for Japanese (and Korean) instead of the current Takao which was not updated since 2015.
And I'm trying to write the new verb, I will make the PR when done.

**Comment by huupoke12** [comment]
I have created the PR, could you look at it?

**Comment by huupoke12** [comment]
Should I create separate new issues and PRs for Japanese and Korean or should I add all of them to that PR?

**Comment by austin987** [comment]
Sorry, I just haven't had a chance to test it. You don't need to do anything at this time, other than be patient :).

I'll try to look in next day or two.

**Comment by austin987** [comment]
@huupoke12 hi, sorry for the delay. So, I tried setting up ibus (on gentoo), which didn't go well(Gentoo..).

Then, I added Korean locale support:
https://wiki.gentoo.org/wiki/Localization/Guide

but that didn't seem to work for notepad/notepad++.

Anyway, the point is that ideally I'd like to test this first, but I'm not sure how, since I don't speak any CJK languages. So, if you can suggest how, I'd love to hear it, otherwise, I'll just have to trust you and review the code itself :).

(TL:DR, I'm going to give it a few days to figure out a way to reproduce, and if not, review and merge.)

**Comment by huupoke12** [comment]
I think the problem with Notepad++ is much more complicated than this. I even have chosen many CJK Fonts in Notepad++ Style Config, with Global Override (nothing to do with `fakechinese`..., just depends on your installed font list)  but it didn't work either.

But it worked fine with Wine's built-in `notepad` (and you can try this in Notepad++ by creating a file with CJK filename, and try open file system picker and see its name).

And I wanted to ask if I should also replace `fakejapanese`, and `fakekorean` with this Source Han Sans Fonts, and delete `fakejapanese_vlgothic` from `cjkfonts`?

**Comment by austin987** [comment]
I was hoping Notepad++ would support Korean text without changing the locale, but alas, it doesn't.

Using `export LANG=ko_KR.UTF-8` before running notepad let me test, thanks for the suggestion.

**Comment by austin987** [comment]
You can update `fakejapanese` and `fakekorean`, but please leave `fakejapanese_vlcgothic`.

**Comment by huupoke12** [comment]
I'm asking this because if I add Meiryo fonts into the replacement registry of `fakejapanese`, it will conflict with `meiryo` and `fakejapanese`. And since `cjkfonts` calls both of `fakejapanese` and `fakejapanese_vlgothic`, it will be inconsistent because `fakejapanese_vlgothic` will override those entries.
So should I add Meiryo in `fakejapanese` replacement registry?

And btw, I don't think you need to add a locale to display/read a language. You only need it when making the system use it (set as date/time format; set as system display language...).

**Comment by mirh** [comment]
Speaking of wqy-microhei.. I'm currently getting either 302 errors or timeouts when trying to download it. 
[Launchpad](https://launchpadlibrarian.net/160801909/fonts-wqy-microhei_0.2.0-beta.orig.tar.gz) works as a mirror.

**Comment by huupoke12** [comment]
The problem is on your network, I can download it just fine.
