### ISSUE TITLE
winetricks maintainer pronoun

### ISSUE THREAD

**Issue by MareinK** [Winetricks/winetricks#1492]
When installing a winetrick, the following text is shown:

> You opted in, so reporting [winetrick name] to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  

Does this refer to a particular person with known male pronouns? If not, would it be better to use a neutral pronoun (e.g. 'they')?

**Comment by austin987** [comment]
It does, the previous maintainer (whom I know in real life) and myself both identify as male.

That said, if you want to change it to gender neutral, send a pr ;).
