### ISSUE TITLE
Winetricks always installs in the default prefix

### ISSUE THREAD

**Issue by mirh** [Winetricks/winetricks#1500]
Even when I select 32 bit in the GUI

**Comment by austin987** [comment]
Works fine here with winetricks-20191224, I'm gonna need some instructions to reproduce.

**Comment by mirh** [comment]
I just create a new prefix in the GUI, with 32 bit arch
Then I proceed to install dotnet20. And I get a "you are using 64 bit bla bla" warning. And *NetFx64* is used and installed.

**Comment by austin987** [comment]
Please open a terminal and run:
`winetricks -v &> log.txt`

then do as you did before and attach log.txt here.

**Comment by mirh** [comment]
[Here you are](https://github.com/Winetricks/winetricks/files/4377488/log.txt)

**Comment by mirh** [comment]
Uh, or I wonder if the bug isn't with *detection* in the first place?
Could it be that winetricks always ever stick with the bitness of the default prefix?

Because I don't see syswow64 anywhere in the new prefixes I create, yet that warnings sticks.

**Comment by mirh** [comment]
Wtf, it had actually installed dotnet40 on the default prefix, despite the fact I had selected another one.

**Comment by austin987** [comment]
Please try in git, https://github.com/Winetricks/winetricks/commit/e58973e215eef260a5b42acebba57fe5d109a2c9 should help here.

**Comment by mirh** [comment]
Works, danke.
