### ISSUE TITLE
New release (Ubuntu 20.04 is coming)

### ISSUE THREAD

**Issue by jre-wine** [Winetricks/winetricks#1505]
Hi Austin,

Ubuntu 20.04 is coming soon. I'm not familiar with their exact release plan, but I think we can get new versions in until early April. Do you want to make a release soon?

Greets
jre

**Comment by austin987** [comment]
Howdy jre,

I'm hoping to make a release in the next few days/week; I'm cleaning up various branches PRs I've got laying around.

LMK if you get a better idea of when the cutoff is. If there's not a tag by the end of the month, please ping me.

**Comment by jre-wine** [comment]
I've been told now that the ultimate latest date is April 23rd (I seriously want to avoid a last minute upload though). So your plan sounds good to me.

**Comment by jre-wine** [comment]
Gentle ping

**Comment by austin987** [comment]
Thanks; I've got most of the tests sorted out; there's a few more things I hope to look this weekend (primarily the mingw detection), plan to tag probably Sunday/Monday.

**Comment by austin987** [comment]
FYI @jre-wine got most of I wanted sorted other than the mingw issue. I need to compile builds on laptop first, so a day or two more.

I don't plan to cut it close, worst case I'll tag before so you can get other fixes in first, just wanted to keep you in the loop.

**Comment by austin987** [comment]
A bit late, but 20200412 is out (with tests passing on 32/64 wine, with/without mingw):
https://github.com/Winetricks/winetricks/commit/f23083c2f1c2884c939e183dcee190ec319f6f79
