### ISSUE TITLE
Add possibility to run --verify <verb> separately with verb already installed

### ISSUE THREAD

**Issue by rmi1974** [Winetricks/winetricks#1506]
Currently running `--verify` separately doesn't work because winetricks detects the verb already installed and exits.

``` 
$ winetricks -q --verify dotnet35
...
------------------------------------------------------
dotnet35 already installed, skipping
```

It would be useful to run `verify` retroactively on existing install without the need to force an install again.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/6aa7f3388c7101d622161a8cc818c710eb8c8165
