### ISSUE TITLE
error /usr/local/bin/wine: Bad CPU type in executable sh winetricks corefonts

### ISSUE THREAD

**Issue by daron4ever** [Winetricks/winetricks#1508]
I tried to install corefonts using `sh winetricks corefonts` command.
I got the following error.

> wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "/usr/local/bin/winetricks: line 3280: /usr/local/bin/wine: Bad CPU type in executable" 

It seems it doesn't support 64bit since mac is no longer support using `wine` command.

**Comment by austin987** [comment]
That's a wine bug; there's nothing winetricks can do here.

IAUI that Codeweavers has support for newer OSX, that effort should go upstream at some point, but I don't know when that will be.

**Comment by joshuah345** [comment]
i know i'm a bit late here, but a workaround is to just symlink wine64 to wine. the old 32 bit one can just be thrown away honestly.
