### ISSUE TITLE
Useless workaround

### ISSUE THREAD

**Issue by joaopa00** [Winetricks/winetricks#1514]
Hello

to install dotnet 4.0, winetricks uses a workaround for bug 34803. Since this bug is closed since April 2019, is this workaround still needed?

**Comment by gverm** [comment]
Just as a clarification: it's `remove_mono` that has this workaround, not `dotnet40`.

**Comment by rmi1974** [comment]
Not directly related to the actual problem, but please to phrase your summary line more precisely. Imagine if everyone just uses one or two generic words. Issue lists will be literally *useless* /s

Something like this: `dotnet40 verb uses potentially obsolete workaround for bug 34803`
