### ISSUE TITLE
Problem with the detected string "unknown" in AppData

### ISSUE THREAD

**Issue by Ski-lleR** [Winetricks/winetricks#1515]
Hi,

Somewhere in the script, it check if AppData contain the value "unknown", and raise an error if found. (wine cmd.exe /c echo '%AppData%' returned a string containing the word 'unknown', as if a voice had cried out in terror, and was suddenly silenced.)

The problem is if your actual linux username is the string "unknown" (that's my case), you can't launch the script.

**Comment by Ahmed-E-86** [comment]
I have the same issue.

**Comment by JetPro55** [comment]
i also

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/e875d5ab8ec54284053bbbe2bb786d8d33dfc0c8

**Comment by Ahmed-E-86** [comment]
I tried to update winetricks using `sudo winetricks --self-update`, and I still gets the same error message.

**Comment by Ahmed-E-86** [comment]
I created a bug report in WineHQ Bugzilla https://bugs.winehq.org/show_bug.cgi?id=49141

**Comment by Ahmed-E-86** [comment]
I removed wine-staging, and installed wine instead, and winecfg works fine now, but I don't know if installing wine-staging again will affect winecfg again, or not.

**Comment by Ahmed-E-86** [comment]
Installing wine-staging again triggered the same issue with winecfg, and winetricks.

**Comment by austin987** [comment]
That's not a winetricks problem, use your distro support or some other support forum for that.

**Comment by Ahmed-E-86** [comment]
I figured out that this problem is related to wine-staging, and I reported in WineHQ Bugzilla, but you closed it as invalid. Anyway, I will use wine-devel.

**Comment by Ahmed-E-86** [comment]
> That's not a winetricks problem, use your distro support or some other support forum for that.

How can you explain that the same issue happens also with Protontricks?

**Comment by Ahmed-E-86** [comment]
> That's not a winetricks problem, use your distro support or some other support forum for that.

The same issue also happens with Protontricks.

**Comment by austin987** [comment]
Presumably protontricks has an old copy of winetricks. I don't know, it's a separate project, ask them.
