### ISSUE TITLE
speechsdk verb for SAPI 5.1 should not restore default WinVer to Windows 7 

### ISSUE THREAD

**Issue by rmi1974** [Winetricks/winetricks#1517]
A rather lengthy analysis here:

https://bugs.winehq.org/show_bug.cgi?id=48919

I've also mentioned it in:

https://bugs.winehq.org/show_bug.cgi?id=43841

In short: 

SAPI 5.1 doesn't exist on Windows Vista+ or later because it's shipped as part of OS.

* SAPI 5.3 = shipped with Windows Vista
* SAPI 5.4 = shipped with Windows 7 or later

There are apps that check the Windows version and automatically assume SAPI 5.3 or later. I've tracked/analyzed one of these in bug 48919 ("Balabolka (TTS app) reports SAPI Error Code 0x80045004 since Wine 2.18 with native SAPI 5.1 via 'winetricks -q speechsdk'").

'Windows XP' should be safe as compromise.

----

Side issue: when using Wine < 2.18, the recipe fails because `c:/windows/syswow64/Speech/Common` doesn't exist before 2.18 which magically fixes apps because due to winetricks abort the Windows version remains at Windows 2000 (used to install SAPI 5.1). The recipes should have a check for older Wine versions and not fail.

----

Follow-up issue: Consider if it's possible to extract SAPI 5.3 from Windows SDK.

**Comment by gverm** [comment]
@rmi1974 The first two issues should be taken care of in #1519
