### ISSUE TITLE
signature file is missing for release 20200412

### ISSUE THREAD

**Issue by jre-wine** [Winetricks/winetricks#1520]
I found no https://github.com/Winetricks/winetricks/releases/download/20200412/20200412.tar.gz.asc
Can you still provide it?

**Comment by austin987** [comment]
Weird. The original signature is deleted as part of the release:
https://github.com/Winetricks/winetricks/blob/master/src/release.sh#L111

I've manually regenerated and pushed it; please retry.

(If that's not good, I can retag after I finish updates for newer shellcheck/travis).

**Comment by jre-wine** [comment]
That worked, thanks.
