### ISSUE TITLE
Issue #1015 doesn't seem to have been resolved. Eve-Online does not install 

### ISSUE THREAD

**Issue by jimapplecore** [Winetricks/winetricks#1521]
14 April 2020
Installed the latest winehq winetricks on 64 bit ubuntu 18.04.
Attempting to install Eve-Online---

This error message precedes failure and exit:
*********************************************************** 
Error at line 3.
(Line Text: # FIXME: doesn't work with latest update, button names don't appear in AHK?)
Error: This line does not contain a recognized action.
The program will exit.
***********************************************************
The problem is described HERE as a misplaced "#"
https://github.com/Winetricks/winetricks/issues/1015

Although the issue #1015 is closed, the problem still exists in the latest version available at winetricks (14 April 2020)

**Comment by austin987** [comment]
I can't reproduce. If you're seeing that text, I don't know how to explain it other than your copy of winetricks is out of date.

That said, the installer isn't currently automated, as the FIXME says..

What does `winetricks -q --version` say?

**Comment by jimapplecore** [comment]
Thank you Austin.  The version downloaded from Ubuntu seems to be 20180217.
I installed winetricks through the Ubuntu software center after installing wine on 14 April 2020 .

winetricks -q --version
20180217 - sha256sum: 1b************************08924
------My installation procedure:--------
    9  sudo dpkg --add-architecture i386
   10  wget -nc https://dl.winehq.org/wine-builds/winehq.key
   11  sudo apt-key add winehq.key
   12  sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main' 
   13  sudo apt update

   16  sudo apt-key add Release.key
   17  sudo apt-add-repository 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./'
   18  sudo apt update
   19  sudo apt install --install-recommends winehq-stable

My System:
uname -a
Linux Aspire-7552 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Am I correct in assuming winetricks is a single script?
Thank you.
jim

**Comment by jimapplecore** [comment]
Hello Austin.
I downloaded winetricks directly from the winehq link.
Winetricks -q --version now reports "20200412-next"
The installation begins with some 
QtWebEnginProcess.exe problem. I am not sure if this is trivial or not. I will report back with further data later. Thanks again.

**Comment by austin987** [comment]
Check that wine is 5.x

**Comment by jimapplecore** [comment]
Thank you Austin.
Wine --version reports 5.0
Internet advice suggests downloading the Eve Launcher from CCP instead of relying on the Wine version. When I get this running, I will write up a full tutorial and post it somewhere appropriate.

Using the most up to date winetricks script (20200412-next) has solved the "error at line 3" problem. It seems the latest ubuntu 18.04 has not updated their version of winetricks on the official package manager repository.

I am now working on solving the QtWebEngineProcess.exe error. I do not think this has anything to do with winetricks. 
Winetricks is an excellent tool. Thank you sir.
