### ISSUE TITLE
How to assign winetricks a specific wine version?

### ISSUE THREAD

**Issue by Golddouble** [Winetricks/winetricks#1522]
I am new in Linux. In man I found this:
ENVIRONMENT VARIABLES: WINE

So I have tried this:
`winetricks WINE=/home/VM-Konto/.PlayOnLinux/wine/linux-x86/2.22/bin`
and this:
`winetricks WINE=/home/VM-Konto/.PlayOnLinux/wine/linux-x86/2.22/bin/wine`
and this:
`winetricks WINE=/home/VM-Konto/.PlayOnLinux/wine/linux-x86/2.22/bin/`

Nothing does work:

> Unknown arg wine=/home/VM-Konto/.PlayOnLinux/wine/linux-x86/2.22/bin/wine

Thank you.

(I also did not find to do this with the GUI version of winetricks. Did I miss it?)

**Comment by Chiitoo** [comment]
The WINE environment variable takes an executable, not just a path to Wine, though the executable can be on the user's PATH, so to speak (meaning things that work without specifying the path at all (like 'wine' and 'wine64' usually).

These variables are also set before the command, so for example:

```
WINE="/path/to/executable" winetricks blah
```

They can also be 'exported' so you don't need to specify it every time.  I'm sure you can find a lot of information regarding that out there.  :]
