### ISSUE TITLE
w_detect_mingw broken due to broken 'winepath' in Wine 5.6 release

### ISSUE THREAD

**Issue by rmi1974** [Winetricks/winetricks#1524]
See my analysis here:

https://bugs.winehq.org/show_bug.cgi?id=48937#c3

The use-case is very narrow and the impact not critical.

* Wine 5.6
* Winetricks 20200412
* 32-bit WINEPREFIX (WINEARCH=win32)
* run 'winetricks -q dotnet30sp1'

Introduced here:

https://github.com/Winetricks/winetricks/issues/1461

https://github.com/Winetricks/winetricks/blob/1937853444257ca004e2a419a7e2e0f2260fe5b5/src/winetricks#L332

-> two times 'winepath' directly used.

Also consider adding another bug reference: https://bugs.winehq.org/show_bug.cgi?id=48937 to `winetricks_early_wine` at https://github.com/Winetricks/winetricks/blob/1937853444257ca004e2a419a7e2e0f2260fe5b5/src/winetricks#L3325 to document Wine releases which need these workarounds.

The `tr -d '\r'` part of the pipeline works around in this case, stripping CR characters.
Thanks to the usage of the wrapper everywhere else, there is no high impact on `winetricks` for end users.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/12986a5ad724050edcdf8089807535dc9c3d04f4
