### ISSUE TITLE
vb6run fails, spurious quotes?

### ISSUE THREAD

**Issue by spoon0042** [Winetricks/winetricks#1526]
WINETRICKS_VERSION=20200412-next

Without -q a dialog pops up from the installer saying 'Command line option syntax error.' I probably wouldn't have thought the problem was spurious quotes but I diffed winetricks with an older version and saw a bunch of added quotes in the changes. (commit 30c2040c7d6c34628d392bd6aa5bcffae86ae91b) Checked that running ' wine vbrun60sp6.exe "" ' gets the same error. If I'm right this likely affects many other things. For one when installing corefonts regedit complains: The file '' was not found.

With -q wine quickly exits with status 43 which is its own issue. (ed: or is that normal, idk)

**Comment by austin987** [comment]
Whoops, sorry about that. I'll take a look this weekend.

**Comment by austin987** [comment]
Should be fixed now, please reopen if not.
