### ISSUE TITLE
msxml6 is broken

### ISSUE THREAD

**Issue by mirh** [Winetricks/winetricks#1529]
As also reported in #1219
Either use the internet archive, or switch back to SP1. 

Also.. I'm not really sure, am I supposed to get this at the end of the installation?
```
Using native,builtin override for following DLLs: msxml6
Executing wine regedit  C:\windows\Temp\_3dmark\override-dll.reg
regedit: The file '' was not found.
Executing wine64 regedit  C:\windows\Temp\_3dmark\override-dll.reg
regedit: The file '' was not found.
```

**Comment by Chiitoo** [comment]
The 'was not found' issue is probably related to 1526 [1].

1. https://github.com/Winetricks/winetricks/issues/1526

**Comment by mirh** [comment]
Mhh nope, [it's](https://download.microsoft.com/download/1/5/8/158F681A-E595-472B-B15E-62B649B1B6FF/msxml6-KB973686-enu-amd64.exe) a dead link.

**Comment by gverm** [comment]
You can still get it through archive.org, but it will be very slow.

So now it's just a matter of deciding what's best, have a speedy link for SP1 or keep SP2 but have it be a lot slower.

**Comment by mirh** [comment]
Well, it's just 2MB thankfully.

**Comment by Chiitoo** [comment]
I meant the 'regedit: The file '' was not found.'.  :]

**Comment by mirh** [comment]
Uh yes sorry you are right. Even because that error seems to appear kind of everywhere.

**Comment by austin987** [comment]
The regedit file not found should be fixed now (blame the Ballmer curve for that one) ;).
