### ISSUE TITLE
Destination folder for new wine prefixes

### ISSUE THREAD

**Issue by moonshaadow** [Winetricks/winetricks#1530]
Hi there.
**winetricks** installs new prefixes into ~/.local/share/wineprefixes, and if we have already some wineprefixes in ~ , **winetricks** doesn't find them. Is there a good reason to keep prefixes there instead of in ~ ? And how can I make **winetricks** to see a wineprefix in another place (if it is not a bad idea?)

**Comment by Chiitoo** [comment]
One advantage I can think of, is that it keeps user specified things separate from program specified things, so neither will mess with each other.  :]

You can use the 'WINEPREFIX' environment variable to tell Winetricks which prefix to use, just as you would for Wine itself.

**Comment by austin987** [comment]
Well, ~/.local/share/wineprefixes is dedicated to the purpose; i.e., it's known that each directory (should) be/is a wineprefix. $HOME generally contains a lot of other stuff.

As @Chiitoo pointed out, it keeps things separate, but totally your call. You can use WINEPREFIX to set an individual prefix, or WINE_PREFIXES to override ~/.local/share/wineprefixes (it defaults to "$XDG_DATA_HOME/wineprefixes, fyi).

**Comment by moonshaadow** [comment]
OK, it makes sense. Thanks for the tips.
