### ISSUE TITLE
winetricks broken

### ISSUE THREAD

**Issue by linuxgirl22** [Winetricks/winetricks#1534]
(Can't use code quotes, as some text appearing very large/bold)

Hello
Using Anarchy linux, Mate desktop, latest kernel, and have done usual installs, including wine-staging, and then winetricks. When I try to use the terminal to install some items with winetricks, this is the error:

_winetricks vcrun6sp6 xact d3dx9 

Github down? version '' doesn't appear to be a valid version

/usr/bin/winetricks: line 3280: /tmp/winetricks.dWYlo0x0/early_wine.err.txt: No such file or directory
/usr/bin/winetricks: line 3280: /tmp/winetricks.dWYlo0x0/early_wine.err.txt: No such file or directory

WINEPREFIX INFO:
Drive C: total 32
drwxr-xr-x  7 wellspring wellspring 4096 Apr 23 13:37 .
drwxr-xr-x  4 wellspring wellspring 4096 Apr 23 13:39 ..
drwxr-xr-x  3 wellspring wellspring 4096 Apr 23 13:37 ProgramData
drwxr-xr-x  6 wellspring wellspring 4096 Apr 23 13:37 Program Files
drwxr-xr-x  6 wellspring wellspring 4096 Apr 23 13:37 Program Files (x86)
drwxr-xr-x  4 wellspring wellspring 4096 Apr 23 13:37 users
drwxr-xr-x 18 wellspring wellspring 4096 Apr 23 13:39 windows
-rw-r--r--  1 wellspring wellspring    9 Apr 23 13:36 .windows-serial

Registry info:
/home/wellspring/.wine/system.reg:#arch=win64
/home/wellspring/.wine/userdef.reg:#arch=win64
/home/wellspring/.wine/user.reg:#arch=win64

cat: /tmp/winetricks.dWYlo0x0/early_wine.err.txt: No such file or directory

wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message ""_ 

Really not sure what's happening, so would be grateful for advice.

**Comment by Chiitoo** [comment]
Which version of Winetricks are you actually using?

Also, are you still experiencing the issue?  GitHub was having issues earlier today, though it might not explain everything here (perhaps just the 'Github down?' part).

I just tried 'winetricks vcrun6sp6 xact d3dx9' here, and could not see what you see when using either current Winetricks master or version 20200412.

By the by, to format code blocks, you can open and close them using three backticks (I'm so not a fan).

Just one tick is generally used for in-line things like `here`.

**Comment by linuxgirl22** [comment]
Thank you for your message @Chiitoo :-) It's 20191224-2 that installed, and I think you're right that it was Github issues, as it's working now. Thanks for advice about code blocks; the giant bold text had been quite a surprise, lol, so it's good to know alternatives.
