### ISSUE TITLE
How can I check, what tricks winetricks has performed?

### ISSUE THREAD

**Issue by Golddouble** [Winetricks/winetricks#1538]
I want to find out, what the difference is for a particular program (for example MS Office pro 2003), between 
a) a manual installation directly in wine without winetricks and without applying any additional manual tricks, only start the install.exe in wine-explorer and install the program itself, 
and
b) taking a built-in verb from winetricks and install it with winetricks.

Is it then enough, to check all the following things after the installation with winetricks:

(I always speak from the GUI-Winetricks-version.)
1. Choose the prefix
2. Go to "install windows DLL's"
3. Check which DLL-packet is ticked
4. Go to "install font"
5. Check which font-packages are ticked
6. Go to "change wine settings"
7. Check, which settings are ticked

Or do I have to check some other things to? If yes, what do I have to check in addition?

Thank you.

**Comment by huupoke12** [comment]
You can inspect the winetricks script to see it yourself.

**Comment by Golddouble** [comment]
Thank you. But this was a question thought for not well skilled users. 
I wonder, if this (see first post) could be an easy way, to get the information what the verb makes, for a not well skilled person. Isn't it?

**Comment by austin987** [comment]
There's a logfile at `$WINEPREFIX/winetricks.log` with what verbs have run in the prefix.

You can use `winetricks list-installed` to display that file for you.

**Comment by Golddouble** [comment]
Thank you @austin987 

When I perform:
`winetricks prefix=PrefixNameWithoutPath list-installed`

It gives me the content of "/home/user/.local/share/wineprefixes/PrefixNameWithoutPath\winetricks.log" And indeed, there are entries in this list, that I do not see, when I proceed as described in post #1.

But I found out, when ...

I want to find out, what the difference is for a particular program (for example MS Office pro 2003), between
a) a manual installation directly in wine without winetricks and without applying any additional manual tricks, only start the install.exe in wine-explorer and install the program itself,
and
b) taking a built-in verb from winetricks and install it with winetricks.

... it would not be enough only to type in "winetricks prefix=PrefixNameWithoutPath list-installed", because in this log I can not see the "DLL Overrides-rules".

So my question again: Would it be enough to look into the winetricks.log and in addition have a look into winecfg? Or is thee something else?

**Comment by austin987** [comment]
Sorry, It wasn't clear what level of detail you wanted.

No, there's nothing that will summarize that for you wtihin winetrickcs. Depending on your usecase, you might considering dumping the registry/checksumming, then diffing, btrfs/zfs snapshots, etc. Or may native Windows solutions for comparing WIndows system states. For winetricks, setting -v when installing is your best bet (along with reading the code), but that's still misleading. I.e., running `wine foo.exe` can do a TON of stuff that's not visible to you on the console/winecfg, if you really care you need to dig deeper.

**Comment by Golddouble** [comment]
Thank you.
