### ISSUE TITLE
Unable to download PowerPointViewer.exe

### ISSUE THREAD

**Issue by dabrain34** [Winetricks/winetricks#1540]
The new address http://www.business.uwm.edu/gdrive/Dietenberger_E/PowerPointViewer.exe is not available anymore.

The former address https://archive.org/download/PowerPointViewer_201801/PowerPointViewer.exe is working

**Comment by rmi1974** [comment]
Indeed very bad idea to use someone's public google drive for getting PPT viewer in first place. It was introduced here:

https://github.com/Winetricks/winetricks/commit/76f5fdf0a7ad3f83ebd0ec85c2daf302dd9cea05

Internet Archive is definitely way to go, even though their CDNs seem to be slow sometimes. But it's not a large download.

**Comment by loopyd** [comment]
As a temporary workaround until this is fixed:

  sudo sed -i 's/http\:\/\/www\.business\.uwm\.edu\/gdrive\/Dietenberger\_E\/PowerPointViewer\.exe/https\:\/\/archive\.org\/download\/PowerPointViewer\_201801\/PowerPointViewer\.exe/g' /usr/bin/winetricks

**Comment by dabrain34** [comment]
Shall I create a PR ?

**Comment by austin987** [comment]
Please.

**Comment by austin987** [comment]
@dabrain34 I went ahead and did this since I had some time while reviewing other PRs. Thanks for offering.

**Comment by dabrain34** [comment]
@austin987 thx ! I was stuck with something else, sorry too :)

**Comment by MagicPoulp** [comment]
I would recommend to install the official microsoft Powerpoint viewer using wine.
And then winetricks would find it in the installed wine folder.

Maybe winetricks will need changes.

https://www.microsoft.com/en-us/download/details.aspx?id=56523

**Comment by austin987** [comment]
@MagicPoulp I'd recommend understanding how winetricks uses the fonts (I say that after seeing your reply to the debian bug).

Winetricks doesn't depend on powerpoint viewer being installed, it's extracting the fonts from the binary and inserting them into the wineprefix. The viewer is never installed, nor does it need to be.

Debian doesn't need to ship a binary for that to work. I don't see what winetricks would gain from your suggestion.

**Comment by TokieSan** [comment]
This won't work right now since web archive is down (& would probably be for days at least). I think the URL for it should change again to a more persistent place

**Comment by acook** [comment]
While not exactly a reputable source, this does appear to contain the correct file, for anyone looking for a workaround:

- https://www.fileeagle.com/software/EN/download/546/8c54c2

I was able to extract its contents using @ap's [script](http://plasmasturm.org/log/457/) and it validated as safe on VirusTotal.

**Comment by ap** [comment]
I have a copy of PowerPointViewer.exe as originally downloaded in March 2007. It is not identical in any respect to this alleged 2015 version (it contains substantially fewer files, and the TTF files it contains differ in content from the ones in the newer installer), but the archive structures match and the newer archive contains files with almost all of the same names as the older one (which is why my script processes it successfully).

**Comment by ap** [comment]
(That is to say, the newer copy looks legit, I just can’t confirm that it’s in any respect identical to the confirmed-original one I’ve kept.)

**Comment by acook** [comment]
Good to know, thanks @ap!

**Comment by seisdr** [comment]
The former address ain't working!
