### ISSUE TITLE
Winetricks font installer closes after PowerPointViewer.exe cannot be downloaded.

### ISSUE THREAD

**Issue by Gamerexde** [Winetricks/winetricks#1544]
Winetricks font installer closes after a failure in the download of PowerPointViewer.exe on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/18222681/81356339-f5b90f80-909e-11ea-8286-0afb35077e7a.png)

**Comment by Gamerexde** [comment]
![image](https://user-images.githubusercontent.com/18222681/81356577-7f68dd00-909f-11ea-907b-0b962eb8616f.png)

**Comment by rmi1974** [comment]
Hi,

the problem is known. The download site is no longer available.
Dupe of https://github.com/Winetricks/winetricks/issues/1540

Regards

**Comment by austin987** [comment]
Closing.
