### ISSUE TITLE
The ie8 installation window can not be displayed

### ISSUE THREAD

**Issue by hillwoodroc** [Winetricks/winetricks#1549]
wine version: 5.8
winetricks version: 20200412
In fact, the installation window is very small, so that all widgets can not be displayed. The installation is not able to be continued.
![2020-05-14 14-57-58 的屏幕截图](https://user-images.githubusercontent.com/1880237/81903324-36131300-95f4-11ea-853e-8cafe4718b18.png)

**Comment by austin987** [comment]
I can't reproduce here, works fine in wine-5.8 with XFCE, it's likely a window manager issue (and should be filed upstream in wine).

Note that ie8 supports quiet mode, which would avoid that problem.
