### ISSUE TITLE
Update physx

### ISSUE THREAD

**Issue by mirh** [Winetricks/winetricks#1550]
Putting aside that I'm not sure if you actually even need this in winetricks (maybe some dll has to be set to native or whatnot for CUDA acceleration to work in staging?)
Version 9.14.0702 is just so old. You should offer [latest one](https://www.nvidia.com/object/physx_system_software.html) (and maybe [legacy](https://www.nvidia.com/object/physx-9.13.0604-legacy-driver.html) too, but idk).

**Comment by austin987** [comment]
It was popular to use in some games around a decade ago (Mass Effect 2 and Bulletstorm come to mind, and looking at winetricks looks like Dragon Age, Darkness 2 and Unreal Tournament 3 all use it as well).

Do you actually have something that needs/uses the latest version? If not, I don't see any reason to update it.

**Comment by mirh** [comment]
Yes, I know what it was used for. 
I don't understand what you are gaining by sticking with an older version, if not bugs.

**Comment by austin987** [comment]
Changing the version introduces the possibility of regressions. Not to mention that it then invalidates the cache for anyone that already has it downloaded, and takes developer time to do.

I don't mind doing that if there's actually a gain (i.e., it fixes an app). But doing it just for the sake of updating it doesn't make sense IMO.

**Comment by mirh** [comment]
?? Nvidia doesn't update stuff just because they think higher numbers looks cooler?
(or nobody else other than browser vendors anyway, for as much as I know)

Now, I didn't personally have problems, but you can [check](https://www.nvidia.com/en-us/drivers/physx/9_14_0702/physx-9-14-0702-driver/) [all](https://www.nvidia.com/en-us/drivers/physx/9_15_0428/physx-9-15-0428-driver/) [the](https://www.nvidia.com/en-us/drivers/physx/9_16_0318/physx-9-16-0318-driver/) [changelogs](https://www.nvidia.com/en-us/drivers/physx/9_17_0329/physx-9-17-0329-driver/) [to](https://www.nvidia.com/en-us/drivers/physx/9_17_0524/physx-9-17-0524-driver/) [see](https://www.nvidia.com/en-us/drivers/physx/9_18_0907/physx-9-18-0907-driver/) [why](https://www.nvidia.com/en-us/drivers/physx/physx-9-19-0218-driver/) it matters.

**Comment by austin987** [comment]
I didn't say nvidia updated for no reason. But the fact that you're proposing updating it, without knowing why it's even in winetricks, and without an example of a game or application that uses it, makes me wary.

**Comment by mirh** [comment]
At a quick glance, and after having checked how the staging patch works, I would guess it's in winetricks because at least once upon a time some game installer was borked, so you needed to install its dependencies separately. 
Idk how the situation is now - what I know is that physx is famous for pesky bugs that eventually just required updating.

**Comment by mirh** [comment]
This was actually fixed in #1796 and eventually #1879. 
But now that I think to it (I don't know what kind of idiot ball took me) adding legacy is ***really*** necessary. 
There are games that don't even start without it.
