### ISSUE TITLE
Font not loaded on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by hopefullToo** [Winetricks/winetricks#1552]
I want to load the font consolas and get the following error message. 
I renamed the file as requested but it does not help.
What should I do now ?

message:
sha256sum mismatch! Rename /home/xxx/.cache/winetricks/PowerPointViewer/PowerPointViewer.exe and try again.

version winetricks: 20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d
version wine : wine-5.0 (Ubuntu 5.0-3ubuntu1)
Ubuntu version: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-29-generic x86_64)

**Comment by austin987** [comment]
It's fixed in git: https://github.com/Winetricks/winetricks/commit/ac51cdb363284bb498fdd20c7a7241df1219d72c

you can update with `winetricks --self-update`
