### ISSUE TITLE
w_wine_version_in doesn't work correctly

### ISSUE THREAD

**Issue by gverm** [Winetricks/winetricks#1560]
Found while testing jet40 and ddr=gdi. I tested on a wine-git build and someone else tested a Staging 5.9 build for me.

In jet40's case, msado15 is not overridden and odbcccp32 is still overridden because of this and in the case of ddr=gdi, the old registry key is used instead of the new (correct) one.

**Comment by gverm** [comment]
Sorry for changing the title so much, but after looking a bit, it seems like w_compare_wine_version works correctly.

This is what it outputs in the jet40 case:
```true: known_wine_version=4.22, comparison=-ge, stripped wine=5.9, expected_pos=, pos_known=
Wine version comparison is true
false: known_wine_version=4.22, comparison=-le, stripped wine=5.9, expected_pos=, pos_known=
Wine version comparison is false```
But for some reason it goes inside the if-statement if the comparison is false, and doesn't go inside when the comparison is true.

I'm definitely missing something here, since my bash knowledge is very very limited.

**Comment by spoon0042** [comment]
Oh good I might not be crazy. I think either the tests are backwards or it should be 'if ! wine_version_in ...'. Not sure if there's a difference. And yeah it's kind of a bash thing having to take care with things returning 0 (like /bin/true) vs. 0 meaning false.

Hopefully that's right and ends the headaches people have been having with their db apps.

**Comment by spoon0042** [comment]
Also somewhat related, mdac28 (and mdac27 I guess) bomb out on 64-bit because they try to w_set_winver nt40.

**Comment by austin987** [comment]
Thanks for the report. I can replicate the issue (I'm surprised no one's noticed/reported it).

w_wine_version_in() has always been pretty fragile. That's why I added a bunch of tests when I reworked it (but obviously not well enough). Looking at the tests, I see that I wrapped them through w_workaround_wine_bug(), which I suspect is hiding the issue.

Anyway, I'll look more this weekend.

**Comment by austin987** [comment]
FYI haven't yet, but haven't forgotten.

**Comment by spoon0042** [comment]
To further confuse things: https://forum.winehq.org/viewtopic.php?f=8&t=34123

With wine-devel 5.12 GedStarPro only works with odbccp32 native,builtin. msado15 setting doesn't matter.

**Comment by gverm** [comment]
@austin987 Is there anything I can do to help with this? Getting jet40/mdac{27,28}/ddr=gdi to work properly again would be nice, since I've seen a couple reports about jet40/mdac in particular.

**Comment by austin987** [comment]
No, I've just been procrastinating it :/. But the recent dotnet stuff makes this more important, so hoping to look after day job next days/this week.

**Comment by ferion11** [comment]
Hi! @austin987
I'm trying to fix some winetricks bugs, but there is some basic thing that need some refactoring first. Then let me recommend that you change the script usage of numbers 0 and 1 to variables TRUE and FALSE, like this:
https://gist.github.com/ferion11/40fa8104c54ce472268d9ee7cef04e9e

**Comment by austin987** [comment]
This needs testing/splitting up, but this should improve things:
https://github.com/austin987/winetricks/commit/f477f28e3dcf425005e0da56c9fff3d72852b4ff

**Comment by gverm** [comment]
@austin987 I tested a rebased version of your patch and it works here, thanks!

**Comment by austin987** [comment]
I'm still splitting/testing, but if you're able, please test with:
https://raw.githubusercontent.com/austin987/winetricks/wip/src/winetricks

branch is at:
https://github.com/austin987/winetricks/tree/wip

There's still work to be done on the w_package_broken* bits before I push any of it, but it's close to ready, so I'd like others to test before I push anything.

**Comment by gverm** [comment]
@austin987 Sorry I missed that one, but I just tested with latest master and ddr=gdi, jet40 and mdac27/28 seem to work for me, thanks! Since I can only really test ddr=gdi fully, I'll wait for more confirmations until I close.

(CC @spoon0042)

**Comment by austin987** [comment]
No worries, thanks for testing and sorry for the breakage!

**Comment by gverm** [comment]
@austin987 It seems `w_workaround_wine_bug` is broken and I suspect it might be related to this bug/the changes that fixed it. It can be reproduced in a 64bit prefix with either dotnet40 or vcrun2008. In both cases the workaround should not be triggered with a newer wine version, but currently they are.

**Comment by Valmar33** [comment]
Here's hoping this can be fixed, somehow.

**Comment by gverm** [comment]
Since most workarounds were reworked/removed, I'll close this one.
