### ISSUE TITLE
winetricks in 20.04 focal fails with wine cmd.exe /c echo '%AppData%' returned empty string, error message ""

### ISSUE THREAD

**Issue by RezoApio** [Winetricks/winetricks#1561]
Hi there,

New install of ubuntu 20.04.
install of wine-staging leads to version 5.9 got this error.  Got some info that version 5.8 was more stable so I have tried with 5.8 but still the same.

WINEPREFIX="/home/william/WineInstall/BNet2" winetricks --gui
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/william/WineInstall
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 12
drwxrwxr-x 3 william william 4096 juin   7 14:53 .
drwxrwxr-x 4 william william 4096 juin   7 14:53 ..
drwxrwxr-x 4 william william 4096 juin   7 14:53 windows

Registry info:
/home/william/WineInstall/BNet2/system.reg:#arch=win64
/home/william/WineInstall/BNet2/user.reg:#arch=win64
------------------------------------------------------
This option is not available. Please see --help for all possible usages.
------------------------------------------------------
wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------

What is interesting is that the correspondng prefix made in 19.10 and than just copied over my previous HDD, works like a charm in both wine-staging 5.9 and 5.8
Is there a problem specific to ubuntu 20.04?

Found one issue here but seemed linked to docker rather than ubuntu itself.

Let me know if I can do some more troubleshooting to help.

**Comment by RezoApio** [comment]
It works now with the 5.10 staging.

**Comment by SmallJoker** [comment]
Broken with 5.10 "vanilla" devel version.

**Comment by MrBrain295** [comment]
> Hi there,
> 
> New install of ubuntu 20.04. install of wine-staging leads to version 5.9 got this error. Got some info that version 5.8 was more stable so I have tried with 5.8 but still the same.
> ## WINEPREFIX="/home/william/WineInstall/BNet2" winetricks --gui
> winetricks GUI enabled, using zenity 3.32.0
> Executing mkdir -p /home/william/WineInstall
> ## You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> 
> WINEPREFIX INFO: Drive C: total 12 drwxrwxr-x 3 william william 4096 juin 7 14:53 . drwxrwxr-x 4 william william 4096 juin 7 14:53 .. drwxrwxr-x 4 william william 4096 juin 7 14:53 windows
> ## Registry info:
> /home/william/WineInstall/BNet2/system.reg:#arch=win64
> /home/william/WineInstall/BNet2/user.reg:#arch=win64
> ## This option is not available. Please see --help for all possible usages.
> ## wine cmd.exe /c echo '%AppData%' returned empty string, error message ""
> 
> What is interesting is that the correspondng prefix made in 19.10 and than just copied over my previous HDD, works like a charm in both wine-staging 5.9 and 5.8 Is there a problem specific to ubuntu 20.04?
> 
> Found one issue here but seemed linked to docker rather than ubuntu itself.
> 
> Let me know if I can do some more troubleshooting to help.

I'm having the same issue.
