### ISSUE TITLE
Where is the help?

### ISSUE THREAD

**Issue by manen** [Winetricks/winetricks#1568]
When I open winetricks and click View help, it takes me to this repo's home page.

Where do I get an actual help message?

**Comment by Chiitoo** [comment]
It's probably trying to get to 'https://github.com/Winetricks/winetricks/wiki', which is no more, so for the time being one should either use the CLI method: 'winetricks --help', or point their browser to 'https://wiki.winehq.org/Winetricks' (the latter may get out-of-date at times).
