### ISSUE TITLE
vcrun2019 vc_redist.x86.exe SHA256sum mismatch

### ISSUE THREAD

**Issue by MrPhantom** [Winetricks/winetricks#1569]
Using `winetricks vcrun2019` using version 20200412 on Void Linux, winetricks attempts to download from ` https://aka.ms/vs/16/release/vc_redist.x86.exe` and fails with `sha256sum mismatch! Rename /home/rmkb/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again.`
Downloading manually from the URL and running sha256sum returns `a06aac66734a618ab33c1522920654ddfc44fc13cafaa0f0ab85b199c3d51dc0`
attached is my output when running `winetricks -q -v vcrun2019` [log.txt](https://github.com/Winetricks/winetricks/files/4834956/log.txt)

**Comment by austin987** [comment]
Already fixed.

**Comment by happysmash27** [comment]
So... to get the fix, I need to update winetricks with the git version instead of release? I am using the current release version of winetricks (20200412) and still get the error.

**Comment by happysmash27** [comment]
After doing so, it does indeed fix this issue. Maybe it's time for a version bump? The only way I could tell a fix was available was by actually going to GitHub and looking through the closed issues. My package manager still shows the outdated version as the latest, so one would have no easy way to know they need to update.
