### ISSUE TITLE
winetricks won't allow me to install anything

### ISSUE THREAD

**Issue by ntzjef** [Winetricks/winetricks#1573]
I'm using Ubuntu 18.04 with wine version 5.0.1. I'm trying to download the necessary dll for .exe video games. Many of the ones I want to play use DirectX. I'm trying to install packages, and no matter which one I try, I always get this error:
> Note: command wine64 regedit C:windowsTemp_d3dx9override-dll.reg returned status 1. Aborting.

Can you please tell me if I've done something wrong?

**Comment by lucifertdark** [comment]
Looks like you have a broken installer downloaded in the winetricks cache folder, it's in Home/.cache/winetricks, delete everything in that folder then try again.

**Comment by ntzjef** [comment]
@lucifertdark Okay, I did that but got the same error.

**Comment by ntzjef** [comment]
Okay, so I moved my 64 bit wine to another folder, and install wine 32 bit with export WINEARCH=win32. Now, I am to download some, but not all packages. I guess it's a solution of some kind.

**Comment by austin987** [comment]
You didn't give much output, so hard to say. All that error indicates is that wine64 failed to run regedit.

My guess is a broken wine install (i.e., you may be missing wine64 package).

**Comment by ntzjef** [comment]
@austin987 Here's the entire output whenever I try to install a dll on my 64-bit wineprefix from winetricks: 
`~$ winetricks
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924 with wine-5.0.1 and WINEARCH=win64

(zenity:9921): dbind-WARNING **: 18:43:38.742: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jDkYo3vloK: Connection refused
Gtk-Message: 18:43:38.805: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:9971): dbind-WARNING **: 18:43:57.817: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jDkYo3vloK: Connection refused
Gtk-Message: 18:43:57.898: GtkDialog mapped without a transient parent. This is discouraged.

(zenity:10728): dbind-WARNING **: 18:44:08.678: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jDkYo3vloK: Connection refused
Gtk-Message: 18:44:08.771: GtkDialog mapped without a transient parent. This is discouraged.
Executing w_do_call d3drm
Executing load_d3drm 
Executing cabextract -q -d /home/ntzjef/.wine/dosdevices/c:/windows/temp/_d3drm -L -F dxnt.cab /home/ntzjef/.cache/winetricks/directx9/directx_feb2010_redist.exe
Executing cabextract -q -d /home/ntzjef/.wine/dosdevices/c:/windows/syswow64 -L -F d3drm.dll /home/ntzjef/.wine/dosdevices/c:/windows/temp/_d3drm/dxnt.cab
/home/ntzjef/.wine/dosdevices/c:/windows/temp/_d3drm/dxnt.cab: WARNING; possible 5960 extra bytes at end of file.
Using native override for following DLLs: d3drm
Executing wine regedit C:\windows\Temp\_d3drm\override-dll.reg
Executing wine64 regedit C:\windows\Temp\_d3drm\override-dll.reg
wine client error:0: version mismatch 595/608.
Your wineserver binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
------------------------------------------------------
Note: command wine64 regedit C:\windows\Temp\_d3drm\override-dll.reg returned status 1. Aborting.
------------------------------------------------------

(zenity:10808): dbind-WARNING **: 18:44:19.774: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jDkYo3vloK: Connection refused
Gtk-Message: 18:44:19.867: GtkDialog mapped without a transient parent. This is discouraged.`

**Comment by austin987** [comment]
So a wineserver, mismatch. You upgraded wine while some wine process is still running. Kill all wine processes in the prefix (wineserver -k) and retry.

**Comment by ntzjef** [comment]
@austin987 I tried that and it returned the same error. So I tried removing wine and winetricks and everything with wine in name with grep. Then I reinstalled only following the steps on the official site. Still same error with 64-bit. So in winetricks I selected the 32-bit. Now I got a another error:

Executing w_do_call d3drm
Executing load_d3drm 
Executing cabextract -q -d /home/ntzjef/.local/share/wineprefixes/wine32/dosdevices/c:/windows/temp/_d3drm -L -F dxnt.cab /home/ntzjef/.cache/winetricks/directx9/directx_feb2010_redist.exe
Executing cabextract -q -d /home/ntzjef/.local/share/wineprefixes/wine32/dosdevices/c:/windows/system32 -L -F d3drm.dll /home/ntzjef/.local/share/wineprefixes/wine32/dosdevices/c:/windows/temp/_d3drm/dxnt.cab
/home/ntzjef/.local/share/wineprefixes/wine32/dosdevices/c:/windows/temp/_d3drm/dxnt.cab: WARNING; possible 5960 extra bytes at end of file.
Using native override for following DLLs: d3drm
Executing wine regedit C:\windows\Temp\_d3drm\override-dll.reg
------------------------------------------------------
d3drm install completed, but installed file /home/ntzjef/.local/share/wineprefixes/wine32/dosdevices/c:/windows/syswow64/d3drm.dll not found
------------------------------------------------------

(zenity:22329): dbind-WARNING **: 19:24:34.279: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jDkYo3vloK: Connection refused
Gtk-Message: 19:24:34.408: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by ntzjef** [comment]
So I've been finding many issues trying to play games with 18.04. Trying lutris, playonlinux, and steam, I failed to load any games. I couldn't even play linux games through steam. Winetricks is still giving me trouble even having tried removing 5.0 wine and using 3.0-1ubuntu1. Now, I'm just going to try upgrading to 20.04, and I'm going to close this.
