### ISSUE TITLE
Skip winetricks.log

### ISSUE THREAD

**Issue by keybreak** [Winetricks/winetricks#1574]
Is there a way to skip writing to **winetricks.log** while installing something?
If not, then i'd like to make feature request for option :smile:

**Comment by austin987** [comment]
What's the usecase for this?

**Comment by keybreak** [comment]
Well, maybe it's little personal case, but for example:
I use custom scripts for managing Wine, and for me winetricks.log usecase is more like what's installed, rather than logging order, so i'd like to keep it clean from repeating items.

For example each time i update Wine version in custom prefixes i use those options with winetricks to keep prefix portable:
isolate_home
mimeassoc=off

And they clutter **winetricks.log** by repeating multiple times

**Comment by austin987** [comment]
As you pointed out, if you want a proper list of what's installed, run winetricks.log through `sort -u`. Disabling logging will break conflicts checks.

That said, if you're using custom scripts, I would think you'd adjust your scripts rather than need to adjust winetricks internal behavior..
