### ISSUE TITLE
Can't install dotnet 4.8

### ISSUE THREAD

**Issue by awesomepandata** [Winetricks/winetricks#1577]
In a clean prefix

`WINEARCH=win32 WINEPREFIX=/home/user/.local/share/wineprefixes/myprefix winetricks dotnet48 ie8`

The problem is after install dotnet40, there an infinite log on console and can't start anything.

I'm using Arch linux.

**Comment by spoon0042** [comment]
There is a bug (or three) reported on winehq that is similar, loop or other failure on a dotnet install. It's already been regression tested so you can try a build without that patch to verify if you want.

https://bugs.winehq.org/show_bug.cgi?id=49532

**Comment by awesomepandata** [comment]
> There is a bug (or three) reported on winehq that is similar, loop or other failure on a dotnet install. It's already been regression tested so you can try a build without that patch to verify if you want.
> 
> https://bugs.winehq.org/show_bug.cgi?id=49532

Thanks for the info! I just downgraded and works :)

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/4f7cba5ecd9cf2b0623eb105386282cef95a324d
