### ISSUE TITLE
Idea for installing old pdh.dll for NT 4.0

### ISSUE THREAD

**Issue by WheezyE** [Winetricks/winetricks#1579]
Hi,

I was recently getting [VARA 4.0.3](https://rosmodem.wordpress.com/) (released July 1, 2020) to work in Wine 5.0.1 - which is part of [Winlink Express](https://winlink.org/WinlinkExpress) (aka RMS Express).  I needed pdh, which winetricks installed dutifully with "winetricks pdh". But I found that I actually was getting errors with this version of pdh.dll and needed an older version of pdh to get VARA working - then it worked perfectly with no wine errors.  The old Win NT dll I used is downloadable direct from Microsoft.  I don't know how common of a use-case this is, but I wrote this command to auto-install it:

```
sudo apt install unzip -y && cd ~/Downloads && wget http://download.microsoft.com/download/winntsrv40/update/5.0.2195.2668/nt4/en-us/nt4pdhdll.exe && unzip nt4pdhdll.exe && cp pdh.dll ~/.wine/drive_c/windows/system32
```

I didn't end up needing to set the dll override in winecfg, but I'm sure it wouldn't hurt - and copying the code segment in winetricks from the other pdh to set the dll override would probably not take too much doing.

Anyway, I just wanted to submit the info in case it was helpful, or if you wanted to implement like a "pdhNT4" command or something.

--------------------------------------------
EDIT:
The error message I get with VARA (when the "winetricks pdh" dll is installed) before VARA crashes is: 
```
0009:fixme:advapi:RegisterEventSourceW ((null),L"PDH"): stub
wine: Call from 0x7bc73f39 to unimplemented function ADVAPI32.dll.PerfEnumerateCounterSet, aborting
wine: Unimplemented function ADVAPI32.dll.PerfEnumerateCounterSet called at address 7BC73F39 (thread 0009), starting debugger...
```
If you want to try to replicate the error: I installed these components 
`winetricks -q dotnet35sp1 corefonts vb6run vcrun2015 sound=alsa win7 ie6`
(and mono and gecko) and the old (NT 4) pdh.dll to get VARA to run.

**Comment by austin987** [comment]
Feel free to s
