### ISSUE TITLE
Latest commit breaks docker build based on a debian with wine

### ISSUE THREAD

**Issue by felfert** [Winetricks/winetricks#1581]
This https://github.com/Winetricks/winetricks/commit/2c5cc509ff8f1345941567db36893a79bb7cf0c4 commit breaks
this build (public, but apparently one needs a docker account to view the build log): https://hub.docker.com/repository/registry-1.docker.io/felfert/wix/builds/cede01a6-4535-406e-af3f-d4bb7c849d87

The docker build installs wine and then uses winetricks to install dotnet40.

Please notify me, if you don't have a docker account and I can paste the build log here.

The source of that docker build is here: https://github.com/felfert/docker-wix

**Comment by austin987** [comment]
I don't have a docker account, so yes, please attach the log. Does it occur if you run dotnet20 by itself?

In any event, I was planning to revert that change soon. I didn't read the upstream bug report (https://bugs.winehq.org/show_bug.cgi?id=41727#c5) closely enough; there's a registry key that can be set instead that accomplishes the same task without installing dotnet20 (i.e., quicker and less prone to breakage). Please try https://github.com/austin987/winetricks/commit/9ddbe6755f78d695bb4181204bb25c09a75cc9f8

Anyway, the original log (and checking dotnet20 itself) may be useful data for #1525 / #1543

**Comment by felfert** [comment]
This is the build log: [builderr.log](https://github.com/Winetricks/winetricks/files/5021549/builderr.log)
The actual execution of wine / winetricks is logged starting at line **1110** (before is just apt-get install stuff, fetching winetricks and providing a small helper script which waits for wineserver to terminate). 

I also tried  austin987@9ddbe67 locally and can confirm that it fixes the issue.

Cheers
 -Fritz

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/1131bf0b2235628fdec050983a96808108e0554b

Thanks for testing.

**Comment by felfert** [comment]
> [1131bf0](https://github.com/Winetricks/winetricks/commit/1131bf0b2235628fdec050983a96808108e0554b)
> 
> Thanks for testing.

Sorry, but that does **NOT** fix it (It only contains half of the changes in the tested branch - the call to the dotnet 20 installation is not removed)

**Comment by austin987** [comment]
I'm not sure what you're referring to, both diffs are the same: removing 4 lines (dotnet20) and adding 3 (registry entry).
https://github.com/austin987/winetricks/commit/9ddbe67
https://github.com/Winetricks/winetricks/commit/1131bf0b2235628fdec050983a96808108e0554b

**Comment by felfert** [comment]
Oops. forget my remark about the missing change. Still, using

https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

instead of

https://raw.githubusercontent.com/austin987/winetricks/9ddbe6755f78d695bb4181204bb25c09a75cc9f8/src/winetricks

fails the docker build. Looks strage to me. No error message from wine tricks, but returns with exit code 99 now.

**Comment by felfert** [comment]
Ok, in the meantime, I diffed the above two links and it turns out, that there are multiple unrelated changes.
Apparently one of the new w_package_broken() calls triggers this. So I can work around using --force. Unfortunately the actual reason remains unknown, because no errors/warnings are shown. Looking at w_warn(), I think
there should be some "last resort fallback" to show a message on stderr if WINETRICKS_GUI is none.

**Comment by felfert** [comment]
Debugged that further and found out, that there **ARE** warnings. They are just not clearly recognizable as such
````
------------------------------------------------------
--force was used, so trying anyway. Caveat emptor.
------------------------------------------------------
------------------------------------------------------
dotnet40 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
Executing mkdir -p /home/wix/.cache/winetricks/dotnet40
Executing cd /home/wix/.cache/winetricks/dotnet40
Downloading https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe to /home/wix/.cache/winetricks/dotnet40
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48.1M  100 48.1M    0     0  26.5M      0  0:00:01  0:00:01 --:--:-- 26.5M
Executing cd /
Executing w_do_call remove_mono
Executing mkdir -p /home/wix
Executing load_remove_mono 
------------------------------------------------------
Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call winxp
Executing mkdir -p /home/wix
Executing load_winxp 
Setting Windows version to winxp
Executing wine regedit /S C:\windows\Temp\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/wix/.wine terminate
------------------------------------------------------
````
Suggestion: Print "WARNING:" in front of a warning message

**Comment by austin987** [comment]
Good idea! Honestly surprised no one's suggested that before.. :). I've made a fix for that:
https://github.com/Winetricks/winetricks/commit/bfee443cb5af1dfc47e3fd7218878952b66702ba

In GUI mode the dialog should already be more obvious (it passes --error to zenity/kdialog).
