### ISSUE TITLE
w_package_broken calls _w_force_continue_check unconditionally

### ISSUE THREAD

**Issue by bernhardu** [Winetricks/winetricks#1585]
Hello, I am not sure if I understand how that function is supposed to work,
but I found that `sh winetricks --no-isolate -q dotnet46` with wine-5.0.1 was
not giving a warning but also did not install the package.

In `load_dotnet46` got a `w_package_broken` added for wine-5.12,
therefore I would guess it should install without force flag on wine-5.0.1?

As far as I see this is caused by `w_package_broken` calling `_w_force_continue_check` unconditionally.
Shouldn't the call to `_w_force_continue_check` just happen when we have an affected wine version?
Therefore just take place when one of the three "broken" warnings are actually printed?

**Comment by mirh** [comment]
See #1599 I guess?

**Comment by austin987** [comment]
I'm still splitting/testing, but if you're able, please test with:
https://raw.githubusercontent.com/austin987/winetricks/wip/src/winetricks

branch is at:
https://github.com/austin987/winetricks/tree/wip

There's still work to be done on the w_package_broken* bits before I push any of it, but it's close to ready, so I'd like others to test before I push anything.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/d8b0c53992d8dcdf6d1ddaad6f4f600c7349780b
