### ISSUE TITLE
Quick fix on the installation script

### ISSUE THREAD

**Issue by ShironCat** [Winetricks/winetricks#1586]
I just installed winetricks on my machine and, in doing so, I've faced a small problem with the script. The systemd service created gives an error 203.

After searching a bit, I figured the problem is in this line:
```
ExecStart=/usr/bin/update_winetricks
```

According to [this post on StackOverflow](https://stackoverflow.com/questions/45776003/fixing-a-systemd-service-203-exec-failure-no-such-file-or-directory), this line should be `ExecStart=/bin/bash /usr/bin/update_winetricks` instead.

I am aware that a rewrite of the README install section is being discussed on #1192, but since this problem has such an easy solution, I'll submit a PR to fix this while that is done.

**Comment by austin987** [comment]
Fixed.
