### ISSUE TITLE
dotnet4xx does nothing

### ISSUE THREAD

**Issue by ghost** [Winetricks/winetricks#1596]
Trying to install any version of dotnet4xx seems to do nothing.

Distro: Fedora Thirty-Two (also tried in Arch and Clear Linux, same result.)
Arch: x86_64

```
[bengris32@localhost ~]$ WINEARCH=win32 winetricks dotnet472
Executing mkdir -p /home/bengris32
Using winetricks 20200412-next - sha256sum: d06570e39877f3548cd2f8daed750717ee342ad7a9aeb7bb854be2543b91b4d8 with wine-5.0.2 and WINEARCH=win32
Executing w_do_call dotnet472
Executing mkdir -p /home/bengris32
Executing load_dotnet472 
[bengris32@localhost ~]$ 
```

**Comment by YihaoPeng** [comment]
Same issue, any package marked w_package_broken cannot be installed, even if the wine version is good.

I think there is a logic error in the `w_package_broken()` function, and `_w_force_continue_check` will inevitably be executed, even if the wine version is good. So when the wine version is good, `winetricks` will exit without any prompt.

Currently, adding the `--force` parameter is the only way to install these packages.

https://github.com/Winetricks/winetricks/blob/66f5122b39d50e0103b7a5d5852a199065e8c95d/src/winetricks#L340

```
w_package_broken()
{
    # FIXME: test cases for this

    bug_link="$1"
    bad_version="$2"
    good_version="$3"

    if [ -z "$bug_link" ] ; then
        w_die "Bug report link required!"
    fi

    if [ -n "$good_version" ]; then
        if ! w_wine_version_in "${bad_version},${good_version}"; then
            w_warn "This package ($W_PACKAGE) is broken in ${_wine_version_stripped}. Upgrade to >=${good_version}. See ${bug_link} for more info."
        fi
    elif [ -n "$bad_version" ]; then
        if ! w_wine_version_in "${bad_version}"; then
            w_warn "This package ($W_PACKAGE) is broken in ${_wine_version_stripped}. Broken since ${bad_version}. See ${bug_link} for more info."
        fi
    else
        w_warn "This package ($W_PACKAGE) is broken. See ${bug_link} for more info."
    fi

    _w_force_continue_check
}
```

**Comment by SwimmingTiger** [comment]
This PR can fix it:
https://github.com/Winetricks/winetricks/pull/1599

**Comment by frostworx** [comment]
I noticed the same problem [some days ago](https://www.reddit.com/r/linux_gaming/comments/ibrsfb/installing_net_461_with_winetricks_hangs/g2hvbkl/?utm_source=reddit&utm_medium=web2x&context=3) while working on [steamtinkerlaunch](https://github.com/frostworx/steamtinkerlaunch)
and looks like wine upstream bug is [here](https://bugs.winehq.org/show_bug.cgi?id=49532)
[dotnet3.5 bug ](https://bugs.winehq.org/show_bug.cgi?id=49690)maybe related(?)

**Comment by austin987** [comment]
I'm still splitting/testing, but if you're able, please test with:
https://raw.githubusercontent.com/austin987/winetricks/wip/src/winetricks

branch is at:
https://github.com/austin987/winetricks/tree/wip

There's still work to be done on the w_package_broken* bits before I push any of it, but it's close to ready, so I'd like others to test before I push anything.

**Comment by mtfurlan** [comment]
I tested with your branch, it seems to work here on debian 10 with `wine-4.0 (Debian 4.0-2)`

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/d8b0c53992d8dcdf6d1ddaad6f4f600c7349780b.
