### ISSUE TITLE
404 for helper_win7sp1_x64 (windows6.1-KB976932-X64.exe)

### ISSUE THREAD

**Issue by frostworx** [Winetricks/winetricks#1601]
Looks like MS removed the file from
https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X64.exe

archive.org has a copy though:
https://web.archive.org/web/20200106134132if_/https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X64.exe

**Comment by frostworx** [comment]
via https://forums.wsusoffline.net/viewtopic.php?p=31156&sid=24727d52f483ea2239c7be0bf8f5657e#p31156

EDIT:
MS actually removed SP1 from the Download Center.
These are working links extracted from wsusscn2.cab:

Code: Select all
    http://download.windowsupdate.com/msdownload/update/software/svpk/2011/02/windows6.1-kb976932-x86_c3516bc5c9e69fee6d9ac4f981f5b95977a8a2fa.exe
    http://download.windowsupdate.com/msdownload/update/software/svpk/2011/02/windows6.1-kb976932-x64_74865ef2562006e51d7f9333b4a8d45b7a749dab.exe

**Comment by gverm** [comment]
These should already be fixed in master, use --self-update to update winetricks.

**Comment by frostworx** [comment]
oh, thx, only checked for issues and haven't found one.
waiting for packagemanagement though :)
*closing here*
