### ISSUE TITLE
dotnet35 doesn't reset Windows version to default

### ISSUE THREAD

**Issue by CodingKoopa** [Winetricks/winetricks#1602]
I notice that the dotnet verbs change the Windows version to `winxp` while installing, and most of them reset the version back to `default` after installing. However, `dotnet30` (but not `dotnet30sp1`), `dotnet35`, and `dotnet35sp1` leave the Windows version as Windows XP, which can produce undesirable results in applications.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/9c13464c4a948a2598f28d1b8c5ef9e084030cbf
https://github.com/Winetricks/winetricks/commit/9f1045af077a75e8c42cda1a9c7356a8af04d512
https://github.com/Winetricks/winetricks/commit/50627d4133202d5f1f17e233a0cae6127ff23f9c
