### ISSUE TITLE
"wine: Access denied" error whenever using winetricks

### ISSUE THREAD

**Issue by michael-ziedalski** [Winetricks/winetricks#1606]
Hello, all. So, I hope this is the best place to report a winetricks error occurring within Wineskin.

Whenever I run *any* sort of winetricks command from within a Wineskin bottle (usually to fix a gui/sound issue in a game), it will fail and display this on the bottom:

`wine: Access denied.`

This occurs to me on my Mac 10.11.6, with multiple Wineskin Winery versions, Engine versions, and after numerous `brew` wine reinstallations. Is there any idea on where this permissions error could be coming from?

**Comment by austin987** [comment]
The message comes from wine, not winetricks.

I'm not familiar with wineskin, but I'd suggest filing a bug there.
