### ISSUE TITLE
[UI] Allow users to run unsupported/unofficial applications through the "Install an application" menu

### ISSUE THREAD

**Issue by grenvol** [Winetricks/winetricks#1607]
Installing an application through winetricks is a pain and confusing. It's easy to install official and support applications and games through the "install a game" menu or "install an application", but It's very hard, complicated or impossible to install unsupported/unofficial apps through winetricks.

Solution: Allow users to install third party apps through the "install an application" menu

**Comment by austin987** [comment]
This is really outside the scope of winetricks. It's not meant to handle installing random applications. You probably want something like Lutris/PlayOnLinux/Q4Wine/etc.
