### ISSUE TITLE
Installing mdac28 does not provide 64bit msado15, solution attached

### ISSUE THREAD

**Issue by Kepsz** [Winetricks/winetricks#1611]
While trying to get Altium Designer working with wine, Louise Lenders wrote an addition to winetricks. That addition allows winetricks to install 64bit version of msado15, that is required for AD.

Related wine bugreport: [https://bugs.winehq.org/show_bug.cgi?id=46107](https://bugs.winehq.org/show_bug.cgi?id=46107)
[64bit_msado15_dlls.txt](https://github.com/Winetricks/winetricks/files/5212535/64bit_msado15_dlls.txt)

**Comment by austin987** [comment]
This looks like a hack IMO. Native mdac28 installs quite a few more binaries:
```
msader15.dll:   PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
msado15.dll:    PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
msado20.tlb:    PE32 executable (DLL) (console) Intel 80386, for MS Windows
msado21.tlb:    PE32 executable (DLL) (console) Intel 80386, for MS Windows
msado25.tlb:    PE32 executable (DLL) (console) Intel 80386, for MS Windows
msado26.tlb:    PE32 executable (DLL) (console) Intel 80386, for MS Windows
msado27.tlb:    PE32 executable (DLL) (console) Intel 80386, for MS Windows
msadomd.dll:    PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
msador15.dll:   PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
msadox.dll:     PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
msadrh15.dll:   PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
msjro.dll:      PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
```

(that said, I haven't checked a real 64-bit windows box).

The patch only handles msdart.dll and msado15.dll (and would break on 32-bit prefixes..)

**Comment by Kepsz** [comment]
Altium can now be launched with wine. So this issue is solved.
