### ISSUE TITLE
New verb: vstools2019

### ISSUE THREAD

**Issue by romanbtl** [Winetricks/winetricks#1615]
Visual Studio Build Tools 2019 may be useful in CI/test environments so here is my proposal for a new verb: vstools2019

Tested with Wine 5.17, should be completely ok when the dotnet bug (freeze during installation) is resolved.
 
[vstools2019.txt](https://github.com/Winetricks/winetricks/files/5271761/vstools2019.txt)

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/78046c91806be6bb5f78a2fcf5e1048550023e7e
