### ISSUE TITLE
How to compile a new version?

### ISSUE THREAD

**Issue by tellts** [Winetricks/winetricks#1618]
Hello. I want to compile the bug fix version in Lubuntu 20.04.
.NET 4.0 and higher fixed error https://bugs.winehq.org/show_bug.cgi?id=49532

I copied the files to my computer like this. Please tell me which command (or commands) to enter next?

`
cd /home/ia/soft/winetricks2

ia@PC:~/soft/winetricks2

$ git clone https://github.com/Winetricks/winetricks

`

**Comment by Chiitoo** [comment]
Winetricks does not need to be compiled, rather you just need the file [1], and run it as a shell script.

The README.md [2] has directions and a helper script for doing this as well.

1. https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
2. https://github.com/Winetricks/winetricks/blob/master/README.md#installing

**Comment by tellts** [comment]
Sorry for bothering you, but how do I install a non-bogged version that was released many months ago, and a revised version for successful work there is NET platform?

**Comment by austin987** [comment]
I don't understand the question.

As @Chiitoo said, it's a single shell script. You can run the latest version by downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks, or if you want a previous version, check the releases page, https://github.com/Winetricks/winetricks/releases.

**Comment by tellts** [comment]
You have written that the latest version was released on April 13, but I installed it recently, and a few days later in September, people wrote that they had come up with a way to prevent the 4+ NET platform from being installed successfully. So I don't need the version released in April.

**Comment by Chiitoo** [comment]
If you download the file linked here, with 'master' in its URL, you'll get the most recent (current) unreleased version.

**Comment by tellts** [comment]
Thanks! Bat I have next problem.

warning: This package (dotnet45) is broken in wine-5.18. Broken since 5.18. See https://bugs.winehq.org/show_bug.cgi?id=49897 for more info. Use --force to try anyway.

I don't understand where to substitute this:
--force

**Comment by Chiitoo** [comment]
That would be an argument for Winetricks, so, for example: 'winetricks --force dotnet45' if installing 'dotnet45'.

See also: 'winetricks --help'
