### ISSUE TITLE
sha256sum mismatch on Ubuntu 20.04

### ISSUE THREAD

**Issue by etairi** [Winetricks/winetricks#1619]
Whenever I try to install something, there is "sha256sum mismatch error". I tried to install `winetricks` both using the official repository for Ubuntu, and manually via the script provided, but both throw the same error. For example, when I try to install the `corefonts` I get the following: 

```
------------------------------------------------------
warning: Github down? version '' doesn't appear to be a valid version
------------------------------------------------------
Executing mkdir -p /home/etairi
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 776f4df5a7b659b351355706266de74e2e3362045c911d152ba0a7c649b55085 with wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0
Executing w_do_call corefonts
Executing mkdir -p /home/etairi
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_corefonts 
Executing w_do_call andale
Executing mkdir -p /home/etairi
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_andale 
Executing mkdir -p /home/etairi/.cache/winetricks/corefonts
Executing cd /home/etairi/.cache/winetricks/corefonts
Downloading https://mirrors.kernel.org/gentoo/distfiles/andale32.exe to /home/etairi/.cache/winetricks/corefonts
Executing cd /home/etairi
------------------------------------------------------
warning: sha256sum mismatch! Rename /home/etairi/.cache/winetricks/corefonts/andale32.exe and try again.
------------------------------------------------------
```

Just renaming the file does not help. When I check the `sha256sum` of the `andale32.exe` file I get the following:
```
etairi@dell:~/.cache/winetricks/corefonts$ sha256sum andale32.exe
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  andale32.exe
```

 Any ideas what the issue might be and how to solve it?

**Comment by austin987** [comment]
It's either a transient issue, or something on your end (note that the latest release check failed as well, which could be from a network issue).

Downloading here shows the sha is correct:
```
austin@laptop /tmp $ wget https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
--2020-10-01 23:39:23--  https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
Resolving mirrors.kernel.org... 2001:4f8:4:6f:0:1994:3:14, 149.20.37.36
Connecting to mirrors.kernel.org|2001:4f8:4:6f:0:1994:3:14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 198384 (194K) [application/octet-stream]
Saving to: 'andale32.exe'

andale32.exe        100%[===================>] 193.73K   734KB/s    in 0.3s    

2020-10-01 23:39:24 (734 KB/s) - 'andale32.exe' saved [198384/198384]

austin@laptop /tmp $ sha256sum andale32.exe 
0524fe42951adc3a7eb870e32f0920313c71f170c859b5f770d82b4ee111e970  andale32.exe
```

**Comment by etairi** [comment]
Apparently the issue was that `wget` was failing for some downloads due to certificate check. 
I just needed to globally disable it as: `echo "check_certificate = off" >> ~/.wgetrc`

**Comment by denyo86** [comment]
I'm getting this issue and not sure how to fix it. Getting the same (incorrect?) sha256sum and got a 404 when trying to get it

```
linden@linden-metabox-u22:~/.cache/winetricks/corefonts$ sha256sum andale32.exe
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  andale32.exe

linden@linden-metabox-u22:~/.cache/winetricks/corefonts$ wget https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
--2024-07-31 16:06:09--  https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
Resolving mirrors.kernel.org (mirrors.kernel.org)... 139.178.88.99, 2604:1380:45e3:2400::1
Connecting to mirrors.kernel.org (mirrors.kernel.org)|139.178.88.99|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-07-31 16:06:10 ERROR 404: Not Found.
```
I've tried disabling the wget check but not change `echo "check_certificate = off" >> ~/.wgetrc`

**Comment by Chiitoo** [comment]
> I'm getting this issue and not sure how to fix it. Getting the same (incorrect?) sha256sum and got a 404 when trying to get it
> 
> ```
> linden@linden-metabox-u22:~/.cache/winetricks/corefonts$ sha256sum andale32.exe
> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  andale32.exe
> 
> linden@linden-metabox-u22:~/.cache/winetricks/corefonts$ wget https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
> --2024-07-31 16:06:09--  https://mirrors.kernel.org/gentoo/distfiles/andale32.exe
> Resolving mirrors.kernel.org (mirrors.kernel.org)... 139.178.88.99, 2604:1380:45e3:2400::1
> Connecting to mirrors.kernel.org (mirrors.kernel.org)|139.178.88.99|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2024-07-31 16:06:10 ERROR 404: Not Found.
> ```
> 
> I've tried disabling the wget check but not change `echo "check_certificate = off" >> ~/.wgetrc`

The URL for that file on that mirror has changed, and the source URL in Winetricks has changed, and indeed, the SHA has changed as well, so that seems about right.  :]

I couldn't find 'andale32.exe' with that SHA going back as far as 2016 or so.  What version of Winetricks are you running with (`winetricks --version`)?

Please try the latest release (20240105) or a copy from `git master`.

**Comment by denyo86** [comment]
Thanks I'm somewhat new to Linux tbh. Took it from the Ubuntu snap installer, and just realised in the readme you say it's often outdated. I'll try to get the latest release running :)
