### ISSUE TITLE
Error Manjaro XFCE 64bits, download repository 32bits

### ISSUE THREAD

**Issue by datacryptoanalytics** [Winetricks/winetricks#1620]
I'm downloading by adding / removing programs from manjaro xfce 64bits, and when I open winetricks it gives a compatibility error warning saying that the installed package is 32bits, and I can't choose 64bits to download.

Version: winetricks 20200412-1

**Comment by austin987** [comment]
It's a warning, not an error. Without any more info, there's no bug here to fix.
