### ISSUE TITLE
How to make a successful installation by your own example NET fremwork based on the example of a group of other people?

### ISSUE THREAD

**Issue by tellts** [Winetricks/winetricks#1622]
By clicking on the link
https://bugs.winehq.org/show_bug.cgi?id=49532
you can find out some sample code that other people have contributed to the code thread to make it start and run successfully NET freework (Dotnet 4+).
When I wanted to know how to do this on my computer, they told me that I could wait for the new version of winetricks to be released or make changes to the code myself. I think that the new version of winetricks will not be released for a long time and I want to make this revision on my computer myself (I'm studying programming), but I don't understand what exactly needs to be done step by step. Please help.

**Comment by austin987** [comment]
Why did you open a second bug for this? You were already linked to the documentation on installing.
https://github.com/Winetricks/winetricks/issues/1618#issuecomment-702082302
