### ISSUE TITLE
Winetricks on Fedora Requires Uninstall of Wine-Staging

### ISSUE THREAD

**Issue by ThisNekoGuy** [Winetricks/winetricks#1628]
After installing Wine-staging for Fedora 32, attempting to install Winetricks warns the user that Wine-Staging conflicts with Wine-common and suggests uninstalling Wine-Staging to do so.

Screenshot:
![Screenshot_20201006_003247](https://user-images.githubusercontent.com/28468662/95266698-4b821700-07f9-11eb-8510-faf810e5153d.png)

**Comment by austin987** [comment]
I don't provide any fedora packaging for winetricks, this should be reported to Fedora.
