### ISSUE TITLE
quartz broken or missing

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [Winetricks/winetricks#1629]
There is an issue when trying to install `quartz` in a WINE prefix.

```
sha256sum mismatch! Rename /home/xiaolong/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe and try again.
```

And it mentions the download URL before that:

```
Downloading https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe to /home/xiaolong/.cache/winetricks/win7sp1
```

When I try to download it anyway, ignoring the checksum:

```
wget https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe
--2020-10-08 19:35:36--  https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe
Resolving download.microsoft.com (download.microsoft.com)... 2a02:26f0:fe00:1ba::e59, 2a02:26f0:fe00:1a2::e59, 2a02:26f0:fe00:1b5::e59, ...
Connecting to download.microsoft.com (download.microsoft.com)|2a02:26f0:fe00:1ba::e59|:443... failed: Connection refused.
Connecting to download.microsoft.com (download.microsoft.com)|2a02:26f0:fe00:1a2::e59|:443... failed: Connection refused.
Connecting to download.microsoft.com (download.microsoft.com)|2a02:26f0:fe00:1b5::e59|:443... failed: Connection refused.
Connecting to download.microsoft.com (download.microsoft.com)|2a02:26f0:fe00:1a8::e59|:443... failed: Connection refused.
Connecting to download.microsoft.com (download.microsoft.com)|2a02:26f0:fe00:1af::e59|:443... failed: Connection refused.
Connecting to download.microsoft.com (download.microsoft.com)|92.122.255.148|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-08 19:35:41 ERROR 404: Not Found.
```

So it seems the download is gone. I tried to find it and saw <https://answers.microsoft.com/en-us/windows/forum/all/downloading-windows-7-service-pack-1-manually/04726857-9257-491b-9f1d-607d45cfdef2>, but the link there (<http://www.microsoft.com/downloads/en/details.aspx?FamilyID=c3202ce6-4056-4059-8a1b-3a9b77cdfdda>) does not work either and I am redirected to simply <https://www.microsoft.com/en-us/download/>.

I need `quartz` for an application and cannot start it without that thing installed.

What can I do to get the installer or fix the problem?

**Comment by gverm** [comment]
@ZelphirKaltstahl Your winetricks is outdated, this issue is already fixed. Use `winetricks --self-update` to update your winetricks.

**Comment by ZelphirKaltstahl** [comment]
@gverm Thanks for such a quick reply! I'll try that. One question first though: Will this self update influence any other components? I installed winetricks through the system package manager (Linux Mint), not by building it or anything.

**Comment by gverm** [comment]
> @gverm Thanks for such a quick reply! I'll try that. One question first though: Will this self update influence any other components? I installed winetricks through the system package manager (Linux Mint), not by building it or anything.

It shouldn't as winetricks is just a shell script.
