### ISSUE TITLE
[QUESTION] Is it posible to install dotnet silently or pass a silent flag when using winetricks?

### ISSUE THREAD

**Issue by FilBot3** [Winetricks/winetricks#1632]
Is it possible to use `/silent` or `/q` when using winetricks such as installing dotnet? When I use the following command

```bash
winetricks --force dotnet472 corefonts
```

I am presented with the GUI prompts for .NET to install.

**Comment by Chiitoo** [comment]
See 'winetricks --help':

```
[...]
-q, --unattended      Don't ask any questions, just install automatically
[...]
```

**Comment by FilBot3** [comment]
Thank you
