### ISSUE TITLE
load_native_mdac not loading odbccp32.dll or setting a native,builtin

### ISSUE THREAD

**Issue by fargodwe** [Winetricks/winetricks#1637]
I am running a program called GedStar Pro using wine.  Thanks to some very knowledgable people on the Wine forums it has run ok for several releases now.  I am currently running Mint 20 and it is using the stable branch - 5.0.2.  In the past this program has run fine.  Starting back in, I *think* July 2020 something changed and it now has required manually adding odbccp32.dll as native, builtin.  I searched through the winetricks script and it appears that in load_native_mdac it only loads odbccp32.dll now if the wine version (?) is 4.22.  I commented out the "if" and "fi" and recreated my prefix, loaded (order for some reason is important) mdac28 and jet40 as was only needed before.  With the if commented out it now automatically loads odbcco32.dll as needed and as it used to.

I am a COMPLETE novice at all of this but I did some searching on the net and there was a link to https://github.com/Winetricks/winetricks/issues/1448 which has something to do with mdac28 and made if sound like odbccp32.dll was no longer needed and had a link to the source code.  Obviously this can't be the case.

Thank you.
David Eaton

**Comment by rmi1974** [comment]
yes, it's still needed for various application installers that create DSNs. It might not be needed for the MDAC installer itself but the override is certainly needed for applications/installers.

**Comment by rmi1974** [comment]
Hello folks,

pinging here since there is now a bug report in Wine: https://bugs.winehq.org/show_bug.cgi?id=50460

Regards

**Comment by rmi1974** [comment]
On a second thought ...

I think for Wine to mature more, it might be indeed better to have builtin preferred. Otherwise no bugs are reported anymore with ODBC/ADO applications due to native overrides. The override change gave Wine project a chance to be aware of missing / faulty behaviour. Hence bugs should be created in Wine bugzilla to implement the missing functionality.
Meanwhile you could just work around by manually setting native override.

**Comment by austin987** [comment]
Mixed this one in the search, but fixed by https://github.com/Winetricks/winetricks/commit/094a4d8552587fca12a101b6a1104833dad4043f
