### ISSUE TITLE
error install usp10

### ISSUE THREAD

**Issue by zirill** [Winetricks/winetricks#1639]
error install usp10:
404: https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe

**Comment by rmi1974** [comment]
Well, you could raise a PR to change the broken URL to one from Internet Archive (archive.org):
They have hundreds of snapshots of the file in multiple years.

https://web.archive.org/web/20200803205215/https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/windows6.1-KB976932-X86.exe

**Comment by austin987** [comment]
The URL was already changed, to http://download.windowsupdate.com/msdownload/update/software/svpk/2011/02/windows6.1-kb976932-x86_c3516bc5c9e69fee6d9ac4f981f5b95977a8a2fa.exe
