### ISSUE TITLE
art2kmin verb breaks app expecting older 32-bit 'Jet' ODBC driver (Access 2000 vs. 2007 runtime installer)

### ISSUE THREAD

**Issue by rmi1974** [Winetricks/winetricks#1641]
Found this when looking at https://bugs.winehq.org/show_bug.cgi?id=7955 checking some unrelated issue while using 'winetricks art2kmin'.

https://web.archive.org/web/20160419173100/http://www.kbld.de/fileadmin/default/downloads/testversionen/shoai13-kompakt.exe

https://web.archive.org/web/20201110085755/https://www.kbld.de/fileadmin/default/downloads/testversionen/testversionshoai13.exe

There is a caveat with MS Access ODBC drivers installation.
The app installer will display an error dialog when registering its ODBC data source (part of post install).

There are two different Access ODBC drivers from Microsoft:

* "Microsoft Access Driver (.mdb)" = older 32-bit 'Jet' ODBC driver. It is included as a standard part of a Windows install. It is officially deprecated.

* "Microsoft Access Driver (.mdb,.accdb)" - the newer 'ACE' ODBC driver. It is not included with Windows, but it is normally included as part of a Microsoft Office install.

Manually running the tool, simulating the problem:

```
$ pwd
/home/focht/.wine/drive_c/KOBOLD/shoai.13/admin/client-installation/tools/makedsn

$ WINEDEBUG=+msgbox wine ./MakeDSN.exe 
...
0024:trace:msgbox:MSGBOX_OnInit L"Folgende DSN konnte(n) nicht angelegt werden:\rshoai_access\r\n"
```

```
$ cat MakeDSN.ini 

[shoai_access]
; die folgenden Einträge sollten immer da sein
Driver=Microsoft Access Driver (*.mdb)
DSNType=System
DSN=shoai13
DESCRIPTION=S-HOAI 13.0 Access
DBQ=C:\KOBOLD\shoai.13\data\kobold13.mdb
FIL=MS Access;
```

The tool will try to open **HKEY_LOCAL_MACHINE\Software\ODBC\ODBCINST.INI\Microsoft Access Driver (*.mdb)** which doesn't exist with the ACE ODBC driver installed from Access 2007 runtime. Only the older Access 2000 runtime ODBC drivers will create it.

Older Access 2000 runtime from here (also referenced by old winetricks)

http://download.microsoft.com/download/office2000dev/art2kmin/1/win98/en-us/art2kmin.exe

It was changed in very old winetricks in 2009:

https://github.com/Winetricks/winezeug/commit/5114f2affa625f7c229662b0cfd15e295e62d461 ("winetricks: bump artk2min to 2007 Access runtime ")

If you look at the old commit, an alias **art2k7min** was added while changing the original **art2kmin** as well.

----

I don't mind if you close this as WONTFIX if there is a risk that changing **art2kmin** back to the ancient times where it really meant "Access 2000 runtime" and separating current **art2kmin** verb content into **art2k7min**. Maybe it's not worth because many apps rely on .accdb support as well. It's just one old app the is broken because of this.

**Comment by gverm** [comment]
@rmi1974 Could you check if #1670 fixes this completely for you? I checked that it installs correctly in both "loud" and quiet mode.
