### ISSUE TITLE
sha256sum mismatch! Rename /home/username/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again.

### ISSUE THREAD

**Issue by desmond27** [Winetricks/winetricks#1642]
I was running the mod organizer lutris installer from [here](https://github.com/rockerbacon/lutris-skyrimse-installers) and I have been getting this error.

I have tried the following to no avail:

- Installed latest winetricks from https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

- Deleted the prefix.

- Deleted the path in the title.

- Renaming the file to all caps.

The winetricks version I am using is as follows:
`20200412-next - sha256sum: 8e180b094e9cde430a89ee98ca63855bfacf3479b030b9bd4fe24bbd261ee04a`

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/d3bdc0058740dfddd2aadf58aea0b52e2b89b3ea

**Comment by desmond27** [comment]
Thanks for the fix, I haven't tested it yet but still.

Could you also elaborate on why this happens, does Microsoft update their binaries from time to time resulting in different checksums?

**Comment by austin987** [comment]
Precisely.

They used to make service pack updates, now they just update the binary in place.

**Comment by platyple** [comment]
it seems the binary was updated again and the new checksum is `4521ed84b9b1679a706e719423d54ef5e413dc50dde1cf362232d7359d7e89c4`

is there a workaround or would i have to wait for another update?
