### ISSUE TITLE
Setting to re-enable telemetry

### ISSUE THREAD

**Issue by emreovus33** [Winetricks/winetricks#1646]
I was installing something to my default wineprefix today, but after I selected the "Use the default wineprefix" option, I always say "yes" to the question of sending operation information to the project to aid the development, but this time I accidentally clicked on "no", and then it told me that it won't ask me the same question again. I tried looking around in registry settings for my prefix to find anything that I can use to re-enable that prompt but I have no results. I also looked in my .local and .config folders for a possible winetricks config I can use to re-enable the prompt, but no luck there as well.

I suppose that prompt works on basis of wineprefix, so my default wineprefix is now locked out of sending telemetry data to the winetricks project, and I can't find a way to re-enable that prompt.

I am not a developer nor a wine expert, but I still want to contribute to the project by at least sending usage data. How do I enable the prompt again without having to wipe my prefix?

**Comment by austin987** [comment]
It's stored in `$XDG_CACHE_HOME/winetricks/track_usage`, which is usually `~/.cache/winetricks/track_usage`
