### ISSUE TITLE
Dbghelp Component Doesn't Install

### ISSUE THREAD

**Issue by ThisNekoGuy** [Winetricks/winetricks#1649]
https://gist.github.com/ThisNekoGuy/886f6a840de900dbfb6559c54dfaa2d7

Tried installing the Dbghelp component for something (wasn't sure if it was necessary or not but tried it anyway) and noticed that this doesn't install at all. Attached a log in the gist link above.

**Comment by Chiitoo** [comment]
Seems to work for me.

I suspect a bit too out-of-date Winetricks is being used (it doesn't seem to even print the version string yet).

The latest release is '20200412'.

**Comment by ThisNekoGuy** [comment]
I seem to have the same version?

`neko-san@NASA ~> winetricks --version
20200412-next - sha256sum: b32e46f689e28f1d4a368887458708eacd0422d4ddcb3d17b00741f742fce9d5
neko-san@NASA ~> winetricks --self-update
------------------------------------------------------
warning: You don't have the proper permissions to run this command. Try again with sudo or as root.
------------------------------------------------------
neko-san@NASA ~> sudo winetricks --self-update
[sudo] password for neko-san: 
Executing cd /tmp/winetricks.TgKgXc5E
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks to /tmp/winetricks.TgKgXc5E

11/24 17:47:15 [NOTICE] Downloading 1 item(s)

11/24 17:47:15 [NOTICE] Download complete: /tmp/winetricks.TgKgXc5E/winetricks

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
037bc0|OK  |   3.4MiB/s|/tmp/winetricks.TgKgXc5E/winetricks

Status Legend:
(OK):download completed.
Executing cd /home/neko-san
Executing mv /tmp/winetricks.TgKgXc5E/winetricks /usr/bin/winetricks.update
Executing rmdir /tmp/winetricks.TgKgXc5E
Executing cp /usr/bin/winetricks /usr/bin/winetricks.bak
Executing chmod -x /usr/bin/winetricks.bak
Executing mv /usr/bin/winetricks.update /usr/bin/winetricks
Executing chmod +x /usr/bin/winetricks
------------------------------------------------------
warning: Update finished! The current version is 20200412-next - sha256sum: 556389c6dc075e86b78b45dcd44824c14004a888f95a8a418ea8c059f04c1c3d. Use 'winetricks --update-rollback' to return to the previous version.
------------------------------------------------------
neko-san@NASA ~> winetricks --self-update
------------------------------------------------------
warning: You don't have the proper permissions to run this command. Try again with sudo or as root.
------------------------------------------------------
neko-san@NASA ~> winetricks --version
20200412-next - sha256sum: 556389c6dc075e86b78b45dcd44824c14004a888f95a8a418ea8c059f04c1c3d
neko-san@NASA ~> 
`

**Comment by Chiitoo** [comment]
Odd.

I'd expect to see something like this:

```
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: b32e46f689e28f1d4a368887458708eacd0422d4ddcb3d17b00741f742fce9d5 with wine-5.21 and WINEARCH=win64
Executing w_do_call dbghelp
```

Notice the 'Using winetricks 20200412-next', which is absent in the gist.

**Comment by ThisNekoGuy** [comment]
Yeah, it's weird

**Comment by austin987** [comment]
Looks like #1659, does `WINETRICKS_DOWNLOADER=wget winetricks -q dbghelp` work?

**Comment by ThisNekoGuy** [comment]
@austin987 Doing what you suggested with ```Winetricks 20201206-next``` made it work, somehow

**Comment by austin987** [comment]
The problem is then in aria2c, not winetricks.
