### ISSUE TITLE
Why use Zenity on KDE Plasma instead of kdialog?

### ISSUE THREAD

**Issue by ryu-ketsueki** [Winetricks/winetricks#1654]
This is more of an annoyance because Steam forces the instalation of zenity for their dialogue windows and does not use kdialog in any way. I imagine that for winetricks offer an option to use kdialog, shouldn't it be priorized in KDE Plasma? It integrates better. I can't find anything on command line that gives the option to run winetricks with kdialog if zenity is installed. Zenity will always be installed if Steam is installed. It's a hard dependency.

**Comment by austin987** [comment]
The logic isn't that smart, it just looks to see which of those helpers is in $PATH, and it seems zenity gets checked for first.

The logic could be improved, i.e., similar to what is done for WINETRICKS_DOWNLOADER, where one can specify aria2c/curl/fetch/wget, to override the selection order.

Patches welcome. I don't have time/motivation for GUI issues.

**Comment by Ruedii** [comment]
The main reason is that Zenity is widely used in almost every distro, and hence likely installed.  

Allowing the use of an external GUI plugin script might be a better way to handle this, though.

**Comment by hikagura99** [comment]
In openSUSE it seems to use Kdialog, i think it depends on the distro

**Comment by ryu-ketsueki** [comment]
> In openSUSE it seems to use Kdialog, i think it depends on the distro

I am using openSUSE Tumbleweed and it is prioritizing Zenity over Kdialog if Zenity is installed because of Steam

**Comment by austin987** [comment]
As I said (https://github.com/Winetricks/winetricks/issues/1654#issuecomment-735284624), it's based on what you have installed. If you have both, zenity will get used.

**Comment by ryu-ketsueki** [comment]
> As I said ([#1654 (comment)](https://github.com/Winetricks/winetricks/issues/1654#issuecomment-735284624)), it's based on what you have installed. If you have both, zenity will get used.

I know, I only wanted to point out for @austin987 that it's not distro dependent.

**Comment by ThisNekoGuy** [comment]
Even after that supposed fix (https://github.com/Winetricks/winetricks/pull/1680), I get this inconsistency as well.

**Comment by JoseskVolpe** [comment]
I agree it should priorize kdialog over zenity if the user is using KDE

**Comment by ThisNekoGuy** [comment]
Waiting on https://github.com/Winetricks/winetricks/pull/1867 to fix this now; I found the issue and fixed it.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/86978c45c36f9cb17ba98ddb6ab4d1d4644da6a5
