### ISSUE TITLE
W2KSP4_EN.EXE checksum mismatch

### ISSUE THREAD

**Issue by Teascade** [Winetricks/winetricks#1655]
I'm aware that this has been an issue in the past, multiple times with different files, and because of the amount of issues related to this I could not bare to just choose one and re-open it, so I'm making a new issue.

When running `winetricks msxml6 riched20` on the latest version of winetricks from master, `20200412-next - sha256sum: a9b29ba26439b2193ae8144d629a97d3501104081510088ab0e7a3bbd9f222af`, I get the following errors:

```
------------------------------------------------------
warning: Checksum for /home/furret/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE did not match, retrying download
------------------------------------------------------
Executing cd /home/furret/.cache/winetricks/win2ksp4
Downloading https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /home/furret/.cache/winetricks/win2ksp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   295  100   295    0     0    546      0 --:--:-- --:--:-- --:--:--   546
Executing cd /home/furret
------------------------------------------------------
warning: sha256sum mismatch! Rename /home/furret/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE and try again.
------------------------------------------------------
```

Deleting the files, or even the whole winetricks`.cache` folder does not help, and I've also encountered this problem with the package available from current ArchLinux repositories

Additional information about my system:
 ```
uname --all
Linux celebi 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux
```

**Comment by austin987** [comment]
Thanks for the report; fixed by
