### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by stefson** [Winetricks/winetricks#1658]
hello, thank you so much for all your efforts with this tool. But can you please add a new tag snapshot? My distro only pulls in those tagged versions, and with the old snapshot from April this happens: 

2020-12-06 14:20:28 (10,4 MB/s) - »vc_redist.x86.exe« saved [14337656/14337656]
sha256sum mismatch! Rename /home/tim/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again.

I think this commit should be included https://github.com/Winetricks/winetricks/commit/d3bdc0058740dfddd2aadf58aea0b52e2b89b3ea

thank you

**Comment by austin987** [comment]
I tagged winetricks-20201206, the gpg signature didn't get generated, see #1660.
