### ISSUE TITLE
Winetricks or winetricks?

### ISSUE THREAD

**Issue by faultycode** [Winetricks/winetricks#1663]
Hello, I was just wondering, throughout the project, even in the man-page it's either winetricks, and then all suddenly Winetricks, yes the command name certainly is with lowercase but which is the actual name? All in all, whether it is with uppercase or lowercase, seems completely random.

**Comment by austin987** [comment]
Much like 'Wine' versus 'wine', it's not a hard and fast rule; the command/program is 'winetricks', but the first word of an English sentence is capitalized, so 'Winetricks' is used a lot.

Time spent formalizing rules about which one to use it is better spend on coding ;).
