### ISSUE TITLE
Verb for 'd3dcompiler_46'

### ISSUE THREAD

**Issue by rmi1974** [Winetricks/winetricks#1672]
Hello folks,

as it says. For details please visit:

https://bugs.winehq.org/show_bug.cgi?id=50350#c13

Summary of information needed to write a recipe:

---

**32-bit x86 d3dcompiler_46.dll**

Download: http://download.microsoft.com/download/F/1/3/F1300C9C-A120-4341-90DF-8A52509B23AC/standalonesdk/Installers/2630bae9681db6a9f6722366f47d055c.cab

CAB filename:   fil47ed91e900f4b9d9659b66a211b57c39

Destination path (WoW64):  'c:\\windows\\syswow64\\d3dcompiler_46.dll'

---

**64-bit x86_64 d3dcompiler_46.dll**

Download:  http://download.microsoft.com/download/F/1/3/F1300C9C-A120-4341-90DF-8A52509B23AC/standalonesdk/Installers/61d57a7a82309cd161a854a6f4619e52.cab

CAB filename:  fil8c20206095817436f8df4a711faee5b7

Destination path (WoW64):  'c:\\windows\\system32\\d3dcompiler_46.dll'

---

Regards

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/pull/1682/commits/a4c9b6fee79fc61ab168439986b85b9a562f26f0
