### ISSUE TITLE
psdkwin7 is broken (Microsoft removed files)

### ISSUE THREAD

**Issue by gverm** [Winetricks/winetricks#1686]
The link is broken, but even with a "working" link from archive.org the setup exits with an error. It's probably because Microsoft removed files that the installer tries to access.

Not sure if there is even a way to fix this, probably not, in which case it would probably be better to remove this verb.
Luckily psdkwin71 still works.

**Comment by austin987** [comment]
Thanks, removed in https://github.com/Winetricks/winetricks/commit/6511820e180ca0d89b24b7412d6971249035afcd
