### ISSUE TITLE
sha256sum mismatch rename xnafx40_redist.msi and try again.

### ISSUE THREAD

**Issue by Ste-Mich** [Winetricks/winetricks#1692]
There seems to be a problem when trying to install xna40.

It throws me this error warning:
warning: sha256sum mismatch! Rename /home/myusername/.cache/winetricks/xna40/xnafx40_redist.msi and try again.

Tried with both 64 and 32 bit.

**Comment by Ste-Mich** [comment]
Also, sorry if I'am doing something incorrectly in here. This is my second day on Linux.
Feel free to correct me.

**Comment by austin987** [comment]
What does `winetricks --version` say?

The link is broken, but it should fall back to archive.org (so it should work, just slowly).

**Comment by Ste-Mich** [comment]
20201206-next - sha256sum: ae1766e0b9335b4676cff5618f111d92d0c579ade852c5d6dbe0a986c31c862b

I'am not using an older version, am I?

**Comment by austin987** [comment]
No, that's current.

Could you run 'winetricks -q -v xna40 &> log.txt` and attach log.txt?

**Comment by Ste-Mich** [comment]
Here it is. Took me a while to find.
[log.txt](https://github.com/Winetricks/winetricks/files/5906991/log.txt)

**Comment by austin987** [comment]
FYI, that log indicates that xna40 did install okay (you got a warning that the download was missing, it then fell back and got it from archive.org)

That said, the download was fixed by https://github.com/Winetricks/winetricks/commit/5992c659ff0d34eb4fdc01897bf360217a0db386
