### ISSUE TITLE
msxml3.dll MANUAL installation?

### ISSUE THREAD

**Issue by DwarfFighterCleric** [Winetricks/winetricks#1693]
Winetricks is not being able to install msxml3 to me.  
Installation fails, that same "I/O xyz not implemented yet" error from 10-years-ago, it must be well-known at this point.  
I was able to extract the MSI using Cabextract manually.  
It leaves me with 3 files on the output directory. Can anyone confirm the filesizes or even the md5sum checksums of these files? Just to know if these are the DLL files that I need? Because Linux is not showing them as DLL file types to me, Thunar says they are Cabinet files themselves. Is it just a matter of renaming the files to DLL and put them inside system32?  
5fefd614bbd3ffa3712b172f70b1fde2 .... msxml3a.dll .... 24.0KB  
4f99145ef64d7076709a14ac8b17d2bd .... msxml3.dll .... 1.00MB  
fd2ac44f545ae9f8018cf694a54d6303 .... msxml3r.dll .... 43.0KB original modified dates early 2005  
Are these the files I need?  
I copy to system32 and register DLL's as (native, builtin)? Anything else I should do? Regedit?

**Comment by austin987** [comment]
How does it fail to install?

I'm not going to offer support for how to manually install it, I'd suggest reading the current source for tips/starting points.
