### ISSUE TITLE
Winrar on winetricks?

### ISSUE THREAD

**Issue by craggles17** [Winetricks/winetricks#1694]
Would it be feasible to add winrar to winetricks?

**Comment by austin987** [comment]
What does it provide that 7zip doesn't?

**Comment by ctr26** [comment]
The lutris install of nexus mod manager uses it (vortex)

**Comment by austin987** [comment]
Could someone provide a link?

I'm not familiar with Nexus Mod Manager (I don't use it myself), but I've seen it mentioned, so if someone wants to work on adding Winrar, I'd consider it.
