### ISSUE TITLE
GUI doesn't work properly

### ISSUE THREAD

**Issue by ffoxD** [Winetricks/winetricks#1698]
When I use the GUI, and choose to do anything, the command prompt spits this error:

./winetricks: 4284: .: Can't open /tmp/winetricks.zrTiLOQE/w.ivan.258459/metadata/WINDOW DECORATIONS RELOADED
apps/*.vars
Unknown arg WINDOW

And, after it gives this error, the GUI is just a blank window. I can't install applications using the GUI, or do anything really. I will post a screenshot of the application installer menu, but essentially anything I do, always gives me a similiar window.
![image](https://user-images.githubusercontent.com/67541651/107024292-27831200-67a8-11eb-9331-4a014081087f.png)
Only the main menu works. Selecting the "select defauld wineprefix" option closes winetricks. All the other options give the error in the terminal and give a blank windo, except "view help".

**Comment by ffoxD** [comment]
Using winetricks 20201206-next - sha256sum: 1ba111805ae101a349e9ceef1b3d15c4403c826928d8d34bf3fb0aef5f698197 with wine-6.0 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0

**Comment by LastTrainToLondon** [comment]
This is a bug by plasma5-kde-gtk-config https://bugs.kde.org/show_bug.cgi?id=431365
