### ISSUE TITLE
DirectX package very slow download

### ISSUE THREAD

**Issue by mozo78** [Winetricks/winetricks#1701]
Since some time the DirectX package download is very slow. I have 100M/bit internet connection but rarely download with 200-300Kb/sec or more. It even sometimes drop to 25Kb/sec and downloading the whole DX package is a pain. It used to work fine some time ago and I could download with full speed of 10MB/sec.

**Comment by austin987** [comment]
Microsoft removed the download, so unless you know of another high speed mirror for it, nothing we can do.

**Comment by mozo78** [comment]
Oh, I didn't know that, I'm sorry. Can't we upload it somewhere on a trusted host?

**Comment by austin987** [comment]
Maybe, but I don't have one. See #1696

**Comment by mozo78** [comment]
Thanks :)
