### ISSUE TITLE
vcrun2008 installation fails

### ISSUE THREAD

**Issue by rahmanlar** [Winetricks/winetricks#1702]
I'm using Debian Unstable with 5.10.0-14.1-liquorix-amd64 kernel
winetricks: 20210206
wine: wine-5.0.3 (Debian 5.0.3-3)

When I try to install the vcrun2008 it raises the error in the image
![image](https://user-images.githubusercontent.com/64320256/107323684-cadd6b00-6ab7-11eb-9250-be1b86b0ed8a.png)

Full log: https://paste.ubuntu.com/p/TvrXm758QX/

PS: I installed winbind, here's the new log: https://paste.ubuntu.com/p/RvByyMJmR9/

**Comment by austin987** [comment]
I can't reproduce this with 5.0.3 compiled locally. It may be debian's package (though if you installed winbind after making that prefix, I'd first make a clean prefix and try again).

**Comment by rahmanlar** [comment]
> though if you installed winbind after making that prefix, I'd first make a clean prefix and try again

Thanks! It worked.
