### ISSUE TITLE
load_dotnet35sp1() fails to add overrides for mscoree and mscorwks

### ISSUE THREAD

**Issue by hackomatic** [Winetricks/winetricks#1704]
winetricks --version
20210206-next - sha256sum: e7322b753c706f59ebb3efb72b32963b976f06b2a9820956ffbc7f7acc264eb4

Unlike other .NET installer helpers 'winetricks dotnet35sp1' load_dotnet35sp1() fails to add overrrides for mscoree and mscorwks. As a result installed dotnet35sp1 is broken.

The following simple patch unifies load_dotnet35sp1() with other similar functions:

$ cat winetricks.diff 
--- winetricks	2021-02-09 19:11:37.447078571 +0300
+++ winetricks.new	2021-02-09 12:11:56.181956160 +0300
@@ -9231,6 +9231,9 @@ load_dotnet35sp1()
 
     w_set_winver winxp
 
+    w_override_dlls native mscoree mscorwks
+    w_wineserver -w
+
     w_try_cd "${W_CACHE}/${W_PACKAGE}"
     w_try_ms_installer "${WINE}" dotnetfx35.exe /lang:ENU ${W_OPT_UNATTENDED:+/q}

**Comment by austin987** [comment]
Could you submit that as a pull request, please (note that I pushed a change to dotnet35sp1 recently, so make sure you've rebased)?

**Comment by hackomatic** [comment]
It would be much easier for me if you could apply this trivial change on your own.

Thanks in advance.

**Comment by austin987** [comment]
Sure (FYI I have it staged, running tests, but had some unrelated issues delaying it).

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/0dbe6f2ee96430d49c32d0626a34a0be44f6e5e3

**Comment by hackomatic** [comment]
Thanks!
