### ISSUE TITLE
tahoma sha256sum mismatch

### ISSUE THREAD

**Issue by version2013** [Winetricks/winetricks#1705]

**Comment by austin987** [comment]
Works fine here..and without any input to go on, nothing to fix here.

**Comment by version2013** [comment]
winetricks allfonts

...snip...

Executing load_tahoma 
------------------------------------------------------
warning: Checksum for /root/.cache/winetricks/tahoma/IELPKTH.CAB did not match, retrying download
------------------------------------------------------
Executing cd /root/.cache/winetricks/tahoma
Downloading https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB to /root/.cache/winetricks/tahoma
--2021-02-17 00:38:21--  https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [40]: Handshake failed
Unable to establish SSL connection.
Executing cd /root/.cache/winetricks/tahoma
Downloading https://web.archive.org/web/2000/https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB to /root/.cache/winetricks/tahoma
--2021-02-17 00:38:22--  https://web.archive.org/web/2000/https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB
Resolving web.archive.org (web.archive.org)... 207.241.237.3
Connecting to web.archive.org (web.archive.org)|207.241.237.3|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://web.archive.org/web/20191010230056/https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB [following]
--2021-02-17 00:38:24--  https://web.archive.org/web/20191010230056/https://downloads.sourceforge.net/corefonts/OldFiles/IELPKTH.CAB
Reusing existing connection to web.archive.org:443.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://web.archive.org/web/20191010230056/https://sourceforge.net/projects/corefonts/files/OldFiles/IELPKTH.CAB/download?use_mirror=master [following]
--2021-02-17 00:38:25--  https://web.archive.org/web/20191010230056/https://sourceforge.net/projects/corefonts/files/OldFiles/IELPKTH.CAB/download?use_mirror=master
Reusing existing connection to web.archive.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 353525 (345K) [text/html]
Saving to: ‘IELPKTH.CAB’

...snip...

warning: sha256sum mismatch! Rename /root/.cache/winetricks/tahoma/IELPKTH.CAB and try again.

**Comment by austin987** [comment]
A) Don't snip that extra info, it's important.
B) The problem is your system:
```
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [40]: Handshake failed
Unable to establish SSL connection.
```

winetricks can't do anything about that. Check with your distro support.

**Comment by version2013** [comment]
Is there a minimum gnutls version that winetricks requires?

**Comment by austin987** [comment]
No; winetricks itself doesn't use gnutls itself at all (it's used by wget/aria2c).


Again, take it up with your distro. This isn't a problem in winetricks.
