### ISSUE TITLE
Busybox needs to be updated soon

### ISSUE THREAD

**Issue by rmyorston** [Winetricks/winetricks#1710]
Thanks for including [busybox-w32](https://github.com/rmyorston/busybox-w32) in Winetricks.

The release you link to, FRP-2121-ga316078ad, is nearly three years old.  In line with my stated policy the binaries will be deleted from my website on 2021-04-09.

A quick fix is to switch to FRP-3025-gc01300361. It's a drop-in replacement but only buys another year of life. (It also happens to be the first release with [release notes](https://frippery.org/busybox/release-notes/FRP-3025.html)).

Beyond that there are issues with features that don't work in Wine. The current release, FRP-3902-g61e53aa93, needs workarounds for two issues:

- Wine bug [49780](https://bugs.winehq.org/show_bug.cgi?id=49780) can be avoided by setting the environment variable ```BB_SKIP_ANSI_EMULATION=0```
- There's an issue with alternate screen buffers. I don't know if the problem is with what I'm doing or in Wine. There doesn't seem to be a Wine bug for this. The workaround is to set the environment variable ```BB_ALT_BUFFER=0```

**Comment by austin987** [comment]
Thanks for the report @rmyorston (and, you know, busybox ;)). And of course, this bug report :).

I also appreciate you pointing out the known issues, very helpful. I'm curious though about the BB_ALT_BUFFER issue..I don't see any references on either project:
https://bugs.winehq.org/buglist.cgi?quicksearch=BB_ALT_BUFFER
https://github.com/rmyorston/busybox-w32/issues?q=is%3Aissue+is%3Aopen+BB_ALT_BUFFER

**Comment by rmyorston** [comment]
I found the issue with alternate screen buffers in my own testing on Wine. It was fixed in commit [1ade2225d](https://github.com/rmyorston/busybox-w32/commit/1ade2225d2d6bf44399b37fd8411cd44a7fea99a#diff-2c0568a0f86566bae82574fb0cfdf06ee39214392367d6ea975f5dc144cbd0a7) without an issue being raised.

I haven't yet figured out where the problem lies, in my code or Wine, so I haven't reported the issue to the Wine project.

**Comment by austin987** [comment]
Okay.

Would you mind opening an issue on your github to track that? I'm fine with adding the workaround, just would like to have something to point to for why it's needed. If not, I could point to the commit, but it sounds like you might keep digging into it?

**Comment by rmyorston** [comment]
Right, new [issue](https://github.com/rmyorston/busybox-w32/issues/210).

If the problem is in Wine it may take a while to track down.

**Comment by austin987** [comment]
1dbeaf8
