### ISSUE TITLE
Sha256sum vcrun2019 has changed (again)

### ISSUE THREAD

**Issue by jkfloris** [Winetricks/winetricks#1713]
The new sha256sums
```
f299953673de262fefad9dd19bfbe6a5725a03ae733bebfec856f1306f79c9f7  vc_redist.x64.exe
4521ed84b9b1679a706e719423d54ef5e413dc50dde1cf362232d7359d7e89c4  vc_redist.x86.exe
```

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/19df518b16d246ee05f219425d0cae9864baee17

**Comment by 0nlin33** [comment]
what do i do with this? can any1 add a bit more please?

**Comment by ACH1980** [comment]
Wouldn't it be a good idea to store those things online and check it regularly with a script? I guess there are many libs where this would be needed in winetricks for the whole, but I guess not all change at the same frequency, so maybe it would be an option to define a expire-date and an expire-interval (and everytime it checks it sets expiry-date to interval)...
