### ISSUE TITLE
Can't install DirectPlay

### ISSUE THREAD

**Issue by rahmanlar** [Winetricks/winetricks#1715]
Hello, I'm using Void Linux with kernel 5.10.22_1 and when I try to install DirectPlay module it throws an error `"warning: Note: command wine64 regedit C:\windows\Temp\override-dll.reg returned status 1. Aborting."
`
The full log is here:
https://paste.ubuntu.com/p/k9rTXdDsMd/

**Comment by gverm** [comment]
I can't reproduce this on Arch Linux with current winetricks-git and wine-git or wine-staging 6.3.
Try updating winetricks (`winetricks --self-update), creating a fresh prefix or deleting winetricks cache (for me this is ~/.cache/winetricks).

**Comment by rahmanlar** [comment]
> I can't reproduce this on Arch Linux with current winetricks-git (tried both with and without GUI) and wine-git or wine-staging 6.3.
> Try updating winetricks (`winetricks --self-update`), creating a fresh prefix or deleting winetricks cache (for me this is ~/.cache/winetricks).

Tried, same error.

https://paste.ubuntu.com/p/dcM4V9jdcd/

**Comment by austin987** [comment]
I can't reproduce this either. I suspect it's a wine regression, could you try an older version of wine (i.e., 6.0 or 5.x)?

**Comment by AndrewSmart** [comment]
From my experience regsvr32 error 3 means the dll wasn't found on disk. Does ~/.wine/drive_c/windows/syswow64/dpnet.dll exist and look reasonable? Run:
```bash
$ls -l ~/.wine/drive_c/windows/syswow64/dpnet.dll
```

**Comment by rahmanlar** [comment]
Sorry, but I deleted my Void Linux and installed Fedora, Also I can't reproduce now. Should I close the issue?

**Comment by austin987** [comment]
Yeah, I think this was a problem in your wine build. If someone else could reproduce then maybe it would be worth keeping open, but..
