### ISSUE TITLE
gfwlivesetupmin.exe [bug]

### ISSUE THREAD

**Issue by bsodcat** [Winetricks/winetricks#1719]
The link for gfwlivesetupmin.exe has either been taken down again by Microsoft or the link was moved.

Tried to find a gfw and install manually but the checksum didn't match maybe wrong program version.

![Screenshot_2021-03-20_19-27-05](https://user-images.githubusercontent.com/54751617/111889851-46351500-89b2-11eb-9ed2-4b1637fb6af9.png)

![Screenshot_2021-03-20_19-25-11](https://user-images.githubusercontent.com/54751617/111889517-05d59700-89b2-11eb-889a-5b1fe49d2ae3.png)

**Comment by CirkuitBreaker** [comment]
This issue is breaking some lutris installers

**Comment by gverm** [comment]
This was already fixed with https://github.com/Winetricks/winetricks/commit/c2772a76d2e0f832b78562f62b5079b0ee668d41.
Update your winetricks. (`winetricks --self-update`)
