### ISSUE TITLE
[Feature Request] Being able to run winecmd

### ISSUE THREAD

**Issue by SlushThorsten** [Winetricks/winetricks#1720]
That would be useful for batch scripts

**Comment by austin987** [comment]
That's already a thing.

**Comment by Toadfield** [comment]
How?
I can't find that option
![image](https://user-images.githubusercontent.com/68649672/112653288-8e3eb680-8e4e-11eb-9ca4-caf0bd0f8fa6.png)

**Comment by austin987** [comment]
My mistake, commandline shell runs a native shell, not winecmd.
