### ISSUE TITLE
[Question] Why the gui of winetricks look like that on KDE neon?

### ISSUE THREAD

**Issue by Ahmed-E-86** [Winetricks/winetricks#1723]
I installed winetricks on KDE neon, and updated it to the latest version using `sudo winetricks --self-update`, but it looks like that:

![Screenshot_20210325_141002](https://user-images.githubusercontent.com/29783425/112472244-9545c600-8d75-11eb-8ce3-6e6703bff301.png)

I can not identify which package are installed. That only happens on KDE neon. I installed winetricks on Kubuntu 20.10, and it looks normal.

I am sorry if that is the wrong place for these kinds of questions.

**Comment by Chiitoo** [comment]
What is 'normal'?

That is, how does it look different?  Is it perhaps using 'zenity' instead of 'kdialog' on Kubuntu?

**Comment by Ahmed-E-86** [comment]
> What is 'normal'?

Like in this picture:

![winetricks3](https://user-images.githubusercontent.com/29783425/112478234-772f9400-8d7c-11eb-87f1-f43f8e80a3c4.png)

> That is, how does it look different? Is it perhaps using 'zenity' instead of 'kdialog' on Kubuntu?

How to force using `zenity` on KDE neon.

**Comment by Ahmed-E-86** [comment]
Thanks for your reply. I installed zenity, and winetricks works fine now.
