### ISSUE TITLE
xna31 sha256sum mismatch

### ISSUE THREAD

**Issue by fastrizwaan** [Winetricks/winetricks#1724]
`warning: sha256sum mismatch! Rename /home/rizvan/.var/app/org.winehq.wine-x86_64/cache/winetricks/xna31/xnafx31_redist.msi and try again.`

instead changing the sha256sum itself fixes the issue.

`409173b3a4f4ee6ff4e6910eece26f95af8073efae2c9fa4c0f8dad24f7774de  /home/rizvan/.var/app/org.winehq.wine-x86_64/cache/winetricks/xna31/xnafx31_redist.msi`

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/95dc6433ecec0ff0131797d2ba85402471be499e
