### ISSUE TITLE
[Question] Is it possible to edit multiple prefixes at once?

### ISSUE THREAD

**Issue by Toadfield** [Winetricks/winetricks#1731]
So for example if I wanna change the winecfg or what programs are installed for the prefix for multiple or all prefixes,is that possible?
Cause I have many prefixes and want to change the settings for them all at once.

**Comment by austin987** [comment]
No, but you could write a for loop to do that for you..

**Comment by Toadfield** [comment]
What do you mean?
How can I do that?
