### ISSUE TITLE
SHA256-Mismatch vc_redist.x64.exe

### ISSUE THREAD

**Issue by albinalm** [Winetricks/winetricks#1732]
Hello!
The SHA256 of vc_redist.x64.exe has been updated to "015edd4e5d36e053b23a01adb77a2b12444d3fb6eccefe23e3a8cd6388616a16".

Current value in winetricks is: "b6c82087a2c443db859fdbeaae7f46244d06c3f2a7f71c35e50358066253de52".
I updated the SHA256 myself and I could continue installation.
Location: Line 12918 in winetricks.

Thanks!

**Comment by frostworx** [comment]
I can confirm the issue and the new checksum for `vcrun2019` _(using winetricks 20210206-next)_

**Comment by austin987** [comment]
I have a fix staged (with some others..), waiting on the tests.

**Comment by gverm** [comment]
@austin987 whoops, I just opened a PR for this as well, I'll close it.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/43934f60fe9bf402488112aa3e0dba0f402376e2

Additionally, https://github.com/Winetricks/winetricks/commit/fb824722d731cd8dfad6610d6449746e763d81ad now allows using --force to ignore the shasum check.
