### ISSUE TITLE
sha256sum mismatch! Rename /home/joao/.cache/winetricks/xna40/xnafx40_redist.msi and try again.

### ISSUE THREAD

**Issue by jhgames1024** [Winetricks/winetricks#1734]
After Celeste updated, when trying to play it again using wine trough Heroic Games Launcher (To play Epic games on Linux), it was requiring .NET Framework 4.0.XXXXX, I installed dotnet40 alright, but when trying to get xna40, it gets this error. 

~$ winetricks xna40
Executing mkdir -p /home/joao
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d with wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win64
Executing w_do_call xna40
Executing mkdir -p /home/joao
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_xna40 
------------------------------------------------------
Working around wine bug 30718 
------------------------------------------------------
------------------------------------------------------
xna40 may not install properly in Wine yet
------------------------------------------------------
Executing w_do_call dotnet40
Executing mkdir -p /home/joao
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
dotnet40 already installed, skipping
------------------------------------------------------
Checksum for /home/joao/.cache/winetricks/xna40/xnafx40_redist.msi did not match, retrying download
------------------------------------------------------
Executing cd /home/joao/.cache/winetricks/xna40
Downloading https://download.microsoft.com/download/A/C/2/AC2C903B-E6E8-42C2-9FD7-BEBAC362A930/xnafx40_redist.msi to /home/joao/.cache/winetricks/xna40
--2021-04-02 20:19:26--  https://download.microsoft.com/download/A/C/2/AC2C903B-E6E8-42C2-9FD7-BEBAC362A930/xnafx40_redist.msi
Resolving download.microsoft.com (download.microsoft.com)... 2.22.80.85, 2001:1291:5:b3::e59, 2001:1291:5:87::e59, ...
Connecting to download.microsoft.com (download.microsoft.com)|2.22.80.85|:443... connected.
The HTTP request was sent, waiting for a response... 200 OK
Size: 7054848 (6,7M) [application/octet-stream]
Saving to: “xnafx40_redist.msi”

xnafx40_redist.msi  100%[===================>]   6,73M  10,0MB/s    in 0,7s    

2021-04-02 20:19:26 (10,0 MB/s) - “xnafx40_redist.msi” saved [7054848/7054848]

Executing cd /home/joao
------------------------------------------------------
sha256sum mismatch! Rename /home/joao/.cache/winetricks/xna40/xnafx40_redist.msi and try again.
------------------------------------------------------

I tried installing on a 32-bit prefix and still gets the same error.

**Comment by austin987** [comment]
Your copy of winetricks is out of date. This is already fixed.
