### ISSUE TITLE
dotnet20 doesn't install

### ISSUE THREAD

**Issue by jrmuizel** [Winetricks/winetricks#1739]
I get "Extracting file failed. It is most likely caused by low memory (low disk space for swapping file) or corrupted Cabinet file."

wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win32

**Comment by austin987** [comment]
Note that 5.0 is no longer supported. You didn't list your winetricks version, but I suspect it may be out of date as well.

That said, do you have free disk space?

**Comment by jrmuizel** [comment]
My winetricks is https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks from today.

I tried wine 5.5 with same result.

I'm running in docker on macos, so perhaps there's something funny going on there. There should be enough disk space.

I'll see if I can reproduce the problem in a more traditional environment.

**Comment by austin987** [comment]
There are unknown issues with docker, see #1525 / #1543.
