### ISSUE TITLE
vcrun2005 and vcrun2008 needed for games like driver: san franscisco

### ISSUE THREAD

**Issue by fastrizwaan** [Winetricks/winetricks#1742]
found working vcrun2005 and vcrun2008 for the game driver: sf, 
winetricks vcrun2005 vcrun2008 does not let the game run

Kindly include these:
https://archive.org/details/vcredist_x86_2008_202104

**Comment by austin987** [comment]
Where did those binaries come from?

**Comment by fastrizwaan** [comment]
redist folder

**Comment by austin987** [comment]
Presumably the app should've installed those redist themselves..

I'd like to see where they came from on microsoft.com before considering it.

**Comment by fastrizwaan** [comment]
Right, vcrun 2005 and 2008
https://www.microsoft.com/en-us/download/details.aspx?id=26347
https://www.microsoft.com/en-ie/download/details.aspx?id=29

Yup, winetricks vcrun2005 vcrun2008 works with wine-6.6.
