### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by fastrizwaan** [Winetricks/winetricks#1745]
Hi,

There are many updates to winetricks. Could you please release a new version?

Thanks.

**Comment by austin987** [comment]
There have been a few, yes, but honestly not that many.

That said, I'm not planning to make a release until I (or someone else) fixes #1660 (unless there is a critical problem).

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/releases/tag/20220411
