### ISSUE TITLE
[Question] Is there any way to update the additional software of multiple prefixes at once?

### ISSUE THREAD

**Issue by Toadfield** [Winetricks/winetricks#1748]
I have many prefixes and the additional software is outdated,so I want to update them,but doing it for each one separately would take too long,so how can I do it with let's say all prefixes that are stored in one folder?
Cause I didn't create those prefixes with winetricks,is it still possible to to just update their additional software?

**Comment by austin987** [comment]
No, it's not possible via winetricks itself. You could write a short shell script to do that, but that is outside of the scope of winetricks.

**Comment by Toadfield** [comment]
How can I make a script like that?

**Comment by austin987** [comment]
Something like:
```
#!/bin/bash
cd /path/to/prefixes
for prefix in */; do
    WINEPREFIX="$prefix" winetricks -q nocrashdialog
done
```

If you need further help, I'd suggest trying your distro's support forum. This tracker is for winetricks issues, not general shell scripting support..
