### ISSUE TITLE
New DLLs not in the supported list

### ISSUE THREAD

**Issue by tkocou** [Winetricks/winetricks#1753]
I attempted to install a new Windows program in WINE (32 bit version) and was using winetricks to install the needed DLLs. Missing DLLs are:
version.dll
user32.dll
imm32.dll
combase.dll
netapi32.dll

While it needed comctl32.dll and this DLL is listed, there is a spelling error in winetricks as it attempts to install comctl32.dll
An intermediate DLL starts with **CC32....** and winetricks invokes **cc32...**. Linux halts as it is unable to find the intended dll to install.

**Comment by austin987** [comment]
At least user32 can't be overridden. The others may or may not be able, but it's not clear adding them would be helpful on their own.

I don't understand your comment about comctl32, it works fine here.

**Comment by tkocou** [comment]
[winetrick-dialog.txt](https://github.com/Winetricks/winetricks/files/6387751/winetrick-dialog.txt)

A dialog captured with 'script' tool and with the 'fluff' removed

**Comment by tkocou** [comment]
As far as the other DLLs go, I found out that my copy of WINE had somehow gotten skewed and was spewing out bogus errors. A restoration from a backup plus an update fixed that issue.

**Comment by austin987** [comment]
Thanks for the log. This didn't matter before, but recent changes in wine made the casing matter. Fixed by https://github.com/Winetricks/winetricks/commit/fb0c3df62f9b677a5ec0f187d1e3ca779a68242f

FYI, recent wine development versions (6.x) have had several regressions / required changes in winetricks.
