### ISSUE TITLE
vb6run is broken

### ISSUE THREAD

**Issue by gverm** [Winetricks/winetricks#1756]
There are currently 2 issues:

1. MS removed yet another link. archive.org is probably the best option as the file isn't that big;
2. Due to the recent upstream loader changes, removing files is not an option anymore. I currently see 2 ways to fix this:
    - Use the new WINEBOOTSTRAPMODE env variable, as explained [here.](https://bugs.winehq.org/show_bug.cgi?id=50905#c8)
    - Manually extract/register the problematic files, like we do in the vcrun* verbs.

**Comment by paulwratt** [comment]
url has changed, checksum is the same, see #1752 for fix

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/82e226799f1de5575be0c140e1a86575169efb90
