### ISSUE TITLE
[Feature Request] Being able to make template prefixes

### ISSUE THREAD

**Issue by Toadfield** [Winetricks/winetricks#1757]
What I mean is that I can create a prefix template where I set which additional software and which winecfg settings it uses.
And then I wanna be able to create a prefix from this template every time I want.
I would find this feature cool,cause I don't like the default winecfg settings and additional software and I hate it that I have to change the settings and installing additional software manually after creating a prefix every time.

**Comment by austin987** [comment]
I don't plan on adding it, but if you want to send a PR, I'll consider it.
