### ISSUE TITLE
[Feature Request] Being able to edit multiple winecfg's and install additional software for multiple prefixes at once

### ISSUE THREAD

**Issue by Toadfield** [Winetricks/winetricks#1758]
I create many prefixes,cause I want a different prefix for each game,so my games aren't broken if one prefix gets a virus.
The problem is that things like dxvk and mono are outdated and I want to update the version of those software for all the prefixes at ones.
I also want to edit the winecfg of all prefixes at once,cause I don't like the size of the text and the theme of the current configuration,and it would take long to change that for each prefix manually.
And also I want to enable smooth fonts for all prefixes at once.

**Comment by austin987** [comment]
As mentioned in #1749, this is outside the scope of winetricks.
