### ISSUE TITLE
[Feature Request] Being able to set that additional software gets auto updated

### ISSUE THREAD

**Issue by Toadfield** [Winetricks/winetricks#1759]
I hate it to manually update all the additional software,I want that I can set that it gets auto updated for a specific prefix or for all.
And also,it would be cool if you can update all the additional software with one button.

**Comment by Toadfield** [comment]
> though you can force it with --force

Where do I have to put that `--force` in?

**Comment by austin987** [comment]
When calling winetricks (i.e., run `winetricks --force dxvk` instead of `winetricks dxvk`).

It can't be done via the GUI (and no, I'm not going to add that. If someone else wants to send a PR though, I'll review it).
