### ISSUE TITLE
SHA256 mismatch - vc_redist.x86.exe

### ISSUE THREAD

**Issue by Unser395** [Winetricks/winetricks#1762]
Hello,

I'm not able to install vcrun2019 due to the sha256 mismatch error.
I've tried to update winetricks with --self-update and tried to use the --force option but I couldn't make it work.
With the updated winetricks, I also get this warning instead of the mismatch error: `warning: Note: command wine regedit C:\windows\Temp\override-dll.reg returned status 53. Aborting`. It doesn't seem to download vcrun2019.

Thank you very much for your help.

**Comment by Alexandr1322** [comment]
> Hello,
> 
> I'm not able to install vcrun2019 due to the sha256 mismatch error.
> I've tried to update winetricks with --self-update and tried to use the --force option but I couldn't make it work.
> With the updated winetricks, I also get this warning instead of the mismatch error: `warning: Note: command wine regedit C:\windows\Temp\override-dll.reg returned status 53. Aborting`. It doesn't seem to download vcrun2019.
> 
> Thank you very much for your help.

Hello, edit file winetricks, new strings
12928:
`    # 2021/05/10: ac96016f1511ae3eb5ec9de04551146fe351b7f97858dcd67163912e2302f5d6`
12932:
`    
w_download https://aka.ms/vs/16/release/vc_redist.x86.exe ac96016f1511ae3eb5ec9de04551146fe351b7f97858dcd67163912e2302f5d6`

**Comment by Unser395** [comment]
Hello, thank you very much for taking the time to answer! I'm still not able to install vcrun2019 though.

On the "20210206" winetrick release, once the lines are added/edited, I still get a mismatch error.
I've noticed that the checksum you wrote is the same as the one from 2020/03/23. I'm not knowledgeable on these kind of things, so I thought it was worth mentioning.

On the "20210206-next" release, I still get the `warning: Note: command wine regedit C:\windows\Temp\override-dll.reg returned status 53. Aborting.` error.
Here is the full output : https://0x0.st/-Bnz.txt

On another note, when I download the .exe directly from microsoft and check its checksum it seems to be `14563755ac24a874241935ef2c22c5fce973acb001f99e524145113b2dc638c1`, it's the latest mentioned by default in the winetricks file in /usr/bin .

Thanks again!

**Comment by MartinX3** [comment]
Same issue here
sha256sum mismatch
Seems that Winetricks need an update.

**Comment by LDS1** [comment]
same, also for vcrun2010

**Comment by paulwratt** [comment]
I found _all_ the broken "sha mismatch" in the DLL section. The url has usually changed, not the SHA for the download (#1752) - beware of SHA changes for windows downloads, could quite easily be repacked with malware

**Comment by paulwratt** [comment]
> On another note, when I download the .exe directly from microsoft and check its checksum it seems to be 14563755ac24a874241935ef2c22c5fce973acb001f99e524145113b2dc638c1, it's the latest mentioned by default in the winetricks file in /usr/bin .

what has changed is the actual url that was used to download the file, if you could post that, then a fix can be made. Note that the SHA checksum is the same as alternate winetricks versions

**Comment by paulscottrobson** [comment]
vc2005run doesn't work either, same problem, though it is not the URL, the file downloads okay, just the SHA256.

**Comment by linuxgirl22** [comment]
Anarchy linux/Mate. Tried moving from wine-staging to wine, thinking it may be that at first, but hit same status 53 errors with winetricks. 

Can't install vcredists, corefonts, msxm14, tahoma ... also, "warning: vcrun6sp6 installation failed" and the same for vcrun6. 

Winetricks version ... 20210206-next - sha256sum: 7cc2f1a44854b8449270cb46890d6cf3c9dff190ac40729ae4eb817b290df8f5

Not able to run art software use, and not very tech, so unfortunately don't understand how to edit winetricks strings.  Normally runs great, so would welcome advice.

**Comment by Nexa88** [comment]
Manjaro KDE is the same Problem with the vcredist2008. I am like linuxgirl and don´t know how to put some codings into an activ program.
Some helpful advices weren´t bad.

Best Greetings,
Nexa88

**Comment by ruhend** [comment]
I had the same issue, I had a quick fix of replacing the sha256sum values in the /usr/bin/winetricks.
Somthing similar to: https://askubuntu.com/a/1090064

run sha256 on the file.exe, and replace this output with the value in the winetricks file.

### TODO
1. `sha256sum <filename>`
2. `sudo gedit /usr/bin/winetricks`
2. Ctrl+F -> 'filename or download url'
3. replace the sha256sum following the URL, with the one you gathered.


Worked for me!
_I had issues with vcredist_x64.exe and vcredist_x86.exe. Doing this solved the issues._

**Comment by linuxgirl22** [comment]
@ruhend Thanks for explanation and link. Challenging stuff! Had managed to --force all but 2 or 3 packages; games are running, and able to instead use krita successfully with art tablet, so will leave it to those able to mend things, but thanks for offering help.

**Comment by paulwratt** [comment]
> Can't install vcredists, corefonts, msxm14, tahoma ... also, "warning: vcrun6sp6 installation failed" and the same for vcrun6.

#1752 provides solutions to some of those

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/b90e0c4e7cea9acc2c9e89bc4afe873086bbd8a1
https://github.com/Winetricks/winetricks/commit/9699aeafc12e0a928f6fd57f4d72f61b032cb631

**Comment by linuxgirl22** [comment]
Thank you very much for these two fixes!

**Comment by SeanRamey** [comment]
Ok, so I think this needs to be opened again, or I need to create a new issue. I can't install vcrun2008 because of a sha256 mismatch.

**Comment by linuxgirl22** [comment]
@SeanRamey When this was happening before, I saw something online that said to go to .cache/winetricks and try double-clicking on the exe within the folder. That worked recently about vcrun2008. Thankfully other things are installing okay, including vcrun2015. .

**Comment by toni20k5267** [comment]
> I had the same issue, I had a quick fix of replacing the sha256sum values in the /usr/bin/winetricks. Somthing similar to: https://askubuntu.com/a/1090064
> 
> run sha256sum on the file.exe, and replace this output with the value in the winetricks file.
> ### TODO
> 
>     1. `sha256sum <filename>`
> 
>     2. `sudo gedit /usr/bin/winetricks`
> 
>     3. Ctrl+F -> 'filename or download url'
> 
>     4. replace the sha256sum following the URL, with the one you gathered.
> 
> 
> Worked for me! _I had issues with vcredist_x64.exe and vcredist_x86.exe. Doing this solved the issues._

which one do i replace @himudigonda ? there is like a milionn of vcredist_x86.EXE and a milion of sha256sum, what do i do?

**Comment by eamanola** [comment]
bump.
not show stopper, but same error:

```
URL: https://aka.ms/vs/17/release/vc_redist.x64.exe
Downloaded: 8f9fb1b3cfe6e5092cf1225ecd6659dab7ce50b8bf935cb79bfede1f3c895240
Expected: 4dfe83c91124cd542f4222fe2c396cabeac617bb6f59bdcbdf89fd6f0df0a32f
```
