### ISSUE TITLE
dotnet452 can't install on wine 6.9

### ISSUE THREAD

**Issue by 932340583** [Winetricks/winetricks#1765]
The installation process is always stuck here.
![image](https://user-images.githubusercontent.com/17899509/119312358-db9ba080-bca4-11eb-8d95-551029de6af9.png)

winetricks's version: 20210206-next - sha256sum: 7cc2f1a44854b8449270cb46890d6cf3c9dff190ac40729ae4eb817b290df8f5
wine's version: 6.9, install from https://dl.winehq.org/wine-builds/debian/ buster main
arch: win32
os: debian 10.7
install command: env WINEARCH=win32 WINEPREFIX=~/.dotnet winetricks --force dotnet452

how can I resolve this problem? thank you.

**Comment by austin987** [comment]
Sorry for the late reply, but this was almost certainly an upstream issue. It works here in 7.0. In 7.5, it fails because of wine-7.4-185-g47b02e8c1ea.

Unfortunately, .Net often regresses. It _generally_  isn't a winetricks issue (i.e., it should be reported upstream.
