### ISSUE TITLE
I can't install vcrun2005

### ISSUE THREAD

**Issue by Toadfield** [Winetricks/winetricks#1774]
When I try to install it,then I just get this error
![image](https://user-images.githubusercontent.com/68649672/120937284-0528e300-c70d-11eb-9379-2a06ee35de93.png)

**Comment by Toadfield** [comment]
The same happens for other vcrun versions.

**Comment by gverm** [comment]
You need to update winetricks. Try `winetricks --self-update`. I tested vcrun2005 all the way to 2019 and only 2019 is currently broken (#1770).

**Comment by Ruedii** [comment]
I ran self update and it still doesn't work.

A whole bunch of the Microsoft redistributables broke recently.  Microsoft changed the files AGAIN.  

On any of the redistributables that licensing permits us to archive, we need to do so.
