### ISSUE TITLE
vcrun2008 not installing mfc90.dll

### ISSUE THREAD

**Issue by reezer** [Winetricks/winetricks#1776]
To my understanding `winetricks -q vcrun2008` should install mfc90.dll. I tried the latest master of winetricks and wine-6.10 (both staging and non-staging, both 32bit and 64bit). Installing mfc90 directly using `winetricks -q mfc90` works though.

**Comment by gverm** [comment]
With latest winetricks and current wine-git + [32bit hotfix](https://source.winehq.org/patches/data/207642) I can't reproduce this.

It installs mfc90 in these locations for me:
./winsxs/amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef/mfc90.dll
./winsxs/x86_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_none_deadbeef/mfc90.dll

**Comment by reezer** [comment]
No it also did not exist there (ran find in the prefix and after installing vcrun2008 there was none), but I just updated wine to 6.11, which fixed the issue.
