### ISSUE TITLE
Build Winetricks with the latest master source folder. Some question....

### ISSUE THREAD

**Issue by Special-Niewbie** [Winetricks/winetricks#1779]
Hello everyone, because on the latest Master Source Files there are the fix/corrections that I was looking for.... So, I'm on Ubuntu, I have the machine and Enviroments well set , but I don't get how I could install Winetricks. Usually I build many projects, but I cannot get this one how to do? Now, I have the Os that I have to re-install and re-prepare everything, but this project need the command `sudo make `and then `sudo make install`? Or I can use the shell script section in the main page and just write `./name_of_the_file.sh` to install it in the system? I really don't get on the main page how to build it. Excuse me for this silly moment from my side....

**Comment by gverm** [comment]
Winetricks is just a shell script. You can download the latest version [here.](https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks)
Use `winetricks --self-update` to update automatically.

**Comment by Special-Niewbie** [comment]
@gverm thanks a lot for your nice info, so it's complitely different approach as I was thinking about.......Really thanks.

Last thing, the shell script file `winetricks` if I have already Winetricks installed by Terminal in Ubuntu like the latest v. **20210206** , this new file script from the Master Source, I need/have to replace the existing file from the system folders like `/etc/` and so on, so I should place in some right sub-folder System? If yes where?
Or if I have a new OS installation, without Winetricks installed into the the system, I can place this shell script in some specific folder and call `winetricks` by terminal from anywhere?

And the function `winetricks --self-update` it takes the updates from the Master Source Folder or winetriks will looking for the updates as normal realise update?

This it's important for me because If I want experiment some new branch, at least I know what it's modified and where I have to go to modify.....

**Comment by austin987** [comment]
winetricks doesn't put any files in /etc/. If you've installed from a package manager, it's likely in `/usr/bin/` (verify with `which winetricks`). You can put winetricks anywhere in $PATH (though you should avoid having more than one copy in $PATH unless you know what you're doing), or put it anywhere and call it via the full path (i.e., /path/to/winetricks).

`winetricks --self-update` grabs the latest copy from github and replaces the currently running copy.

**Comment by Special-Niewbie** [comment]
@austin987 , thanks to reply the /etc/ example was just one example to understand where I should looking for the winetricks principal PATH. Anyway, I will finish a fresh Ubuntu installation and I will give you the results guy......

**Comment by Special-Niewbie** [comment]
Well, I was waiting to install Wine anxiously to test everything again.....but Wine it has the broken installation with Ubuntu 21.04 for caused of some unmet dependencies. So, I need to wait on that ...

**Comment by Special-Niewbie** [comment]
Thank you guys @gverm @austin987 , just then I finished to install almost everything and Winetricks works like charm :+1:  .
I have installed Winetrics by Terminal and then I went to `/usr/bin/` and open `winetricks` file to watch if I activate `winetricks --self-update` by Terminal it will upgrade by it-self the file from the Source Github file and it works perfectly without that I will do manually. I will go ahead with testing and if anything will report here. Thanks for this amazing project.....
