### ISSUE TITLE
Migration to travis-ci.com required now !!

### ISSUE THREAD

**Issue by bobwya** [Winetricks/winetricks#1783]
@austin987 

Referring to: [travis-ci.org/Winetricks/winetricks](https://travis-ci.org/Winetricks/winetricks)

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by gverm** [comment]
Don't want to hijack this issue, but maybe to make integration a little nicer this could be a good time to switch to Github Actions.

**Comment by austin987** [comment]
@gverm yeah, I agree. I plan to look in a couple weeks when I'm back from vacation.
