### ISSUE TITLE
Selection of wine_64

### ISSUE THREAD

**Issue by CountOmega** [Winetricks/winetricks#1787]
Hi all,

I did an install of wine, winbind and winetricks. For a 64-bit program I nedd the msxml6 dll from winetricks. But I can't seem to force winetricks to use the /home/.wine64 directory. Instead, a .wine64 folder is created in  /home/user/.local/.share/wineprefixes . Is there some way I can force winetricks to use the 64 bit wine?

**Comment by Chiitoo** [comment]
From a CLI, you can do something like this: `WINEPREFIX="/home/.wine64" winetricks [...]`

The GUI isn't too well maintained at this time, and may have some issues lurking within.

**Comment by CountOmega** [comment]
ah ok, thanks . I'll try this

**Comment by CountOmega** [comment]
would be nice if the ui supported this.
