### ISSUE TITLE
VCRUN2005 installation fails with checksum error

### ISSUE THREAD

**Issue by shag00** [Winetricks/winetricks#1788]
winetricks ver: 20210206
wine vers: wine-6.0.1 and wine-6.9 (Staging) each on a different machine
host machines: Kubuntu 21.04

`warning: Checksum for /home/scott/.cache/winetricks/vcrun2005/vcredist_x86.EXE did not match, retrying download` and
`warning: Checksum for /home/anj/.cache/winetricks/vcrun2005/vcredist_x86.EXE did not match, retrying download`

each machine also receives multiple connection messages:
`Connecting to download.microsoft.com (download.microsoft.com)|2404:c800:8203:19c::e59|:443... failed: Connection timed out.`

Same result observed over a multi day period and multiple attempts using new 32 bit prefixes with a mix of Windows versions of XP and Windows 7.

**Comment by CountOmega** [comment]
try winetricks --selfupdate.

**Comment by Travelbacon** [comment]
You mean, to check if the latest version has been installed?

To give a quickly an answer, I have exact the same problem with version 20210206

**Comment by Travelbacon** [comment]
With the winetricks --selfupdate your winetricks will be updated to the version where this bug has been fixed.

**Comment by shag00** [comment]
Wonderful
