### ISSUE TITLE
[Feature request] Add option to install (msu) update packages to custom prefix

### ISSUE THREAD

**Issue by stixholder** [Winetricks/winetricks#1790]
In the winetricks menu (manjaro, v. 20210206-1), I miss an option which enables installation of KB/MSU update packages from Microsoft to an existing custom wine prefix (whether for default or custom wine prefix location). AFAIK, installing .msu updates should be supported by recent wine versions. Also, running any arbitrary executable from the context of a default or custom prefix would be helpful, e. g. to install patches.

**Comment by lorn10** [comment]
This is really an interesting topic. Were there any improvements regarding this? It looks that the msu support in Wine became meanwhile even better. :+1: 

Some basic msu support was added back in [Wine 5.0](https://www.winehq.org/announce/5.0), as of 2022 we have [Wine 7.0](https://www.winehq.org/announce/7.0). It is confirmed that the available msu support works quite good for several applications like .NET Framework 4.5.x/4.6.x/Win Vista+, IE8/Win Vista+, IE10 in Win7 mode. 

However, this is most likely not the case for more system related msu packages which updates system components or core system dll files in Windows.

An option in winetricks to select a specific Windows KB *.msu file and "hack it into" a Wine prefix would be really great. :wink:

**Comment by xevilstar** [comment]
+1 I'd love to install WindowsTH-KB2693643-x64.msu on my wine64

**Comment by rnz** [comment]
> +1 Я бы хотел установить WindowsTH-KB2693643-x64.msu на свой wine64
Same. Installing Windows just to run RSAT (Microsoft Remote Server Administration Tools) is tedious.

**Comment by austin987** [comment]
Please test https://github.com/Winetricks/winetricks/pull/2061

In particular, it would be helpful if someone can test on KDE; I don't have a kde setup handy and I've got limited space for a VM on my current laptop.

**Comment by JackNine** [comment]
Cool, I just want to install IE11 on my wine64, but some msu files are depended.

**Comment by stixholder** [comment]
Thanks, I'll do as soon as I've got time.

**Comment by stixholder** [comment]
@austin987: to test this feature, I'd have to checkout and build from branch
[branch issue-1790](https://github.com/austin987/winetricks/tree/issue-1790-misc-exe) 
myself, there is no precompiled version from a CD pipeline, I presume?

**Comment by austin987** [comment]
@stixholder No, there's no .deb/.rpm. But winetricks is just a shell script, so you can download/run it without any building/compiling:

$ wget https://raw.githubusercontent.com/austin987/winetricks/e93d1f1aa1bd321d03512cf33f9b6ae770fb1889/src/winetricks
$ bash winetricks
