### ISSUE TITLE
Package Request: Windows Package Manager (winget)

### ISSUE THREAD

**Issue by vanillajonathan** [Winetricks/winetricks#1791]
The Windows Package Manager (aka winget)

https://github.com/microsoft/winget-cli/

**Comment by tiziodcaio** [comment]
I think at the moment you cannot install APPX in wine

**Comment by austin987** [comment]
I don't think this is likely to ever work on wine. If someone has instructions on how to get it to work, we can reconsider.

**Comment by upintheairsheep** [comment]
> I think at the moment you cannot install APPX in wine

Almost all WinGet packages are Win32 (exe and msi)
