### ISSUE TITLE
its not turning on

### ISSUE THREAD

**Issue by CharpieMarpie** [Winetricks/winetricks#1797]
so i have been have no problems with wine tricks but today its giving me this error message:wine cmd.exe /c echo '%AppData%' returned empty string, error message "system.reg is not a valid registry file
userdef.reg:4: Mismatched architecture '#arch=win64'
userdef.reg is not a valid registry file
user.reg:4: Mismatched architecture '#arch=win64'
user.reg is not a valid registry file
wine: could not load kernel32.dll, status c0000135"  

How do i fix this

**Comment by austin987** [comment]
Looks like a corrupt wineprefix.

**Comment by CharpieMarpie** [comment]
but how do i fix this

**Comment by austin987** [comment]
It's a bug in wine, you could try updating to 6.15 (latest release) or downgrading to an earlier version (i.e., 6.0) to avoid it.

To fix the current prefix, you could try `wineboot -u` to force an update of the prefix, but that may or may not work.

If there's no data in the prefix you care about, then just delete the prefix and try again (winetricks will create it if it's missing).

If you need further help with that, please use the wine forums https://forum.winehq.org/, as this is not a winetricks problem, but a wine one.

**Comment by Etaash-mathamsetty** [comment]
> but how do i fix this

it is a bit late, but I do have a fix, just delete the registry files. 
This is probably a worse solution than starting fresh with a new wine prefix, but at least existing data won't be lost
