### ISSUE TITLE
IE7 Fails to Install in Wine 6.14, Wine 7.0

### ISSUE THREAD

**Issue by giardn** [Winetricks/winetricks#1803]
```
When I create a empty new prefix (win32) and set it to WinXP, I attempt to install IE7 and I get this:

`winetricks GUI enabled, using zenity 3.32.0
Executing w_do_call ie7
Executing mkdir -p /home/giardn
Executing load_ie7 
Using native,builtin override for following DLLs: ieproxy ieframe itircl itss jscript mshtml msimtf shdoclc shdocvw shlwapi urlmon wininet xmllite
Executing wine regedit C:\windows\Temp\override-dll.reg
Using native override for following DLLs: iexplore.exe
Executing wine regedit C:\windows\Temp\override-dll.reg
Using builtin override for following DLLs: updspapi
Executing wine regedit C:\windows\Temp\override-dll.reg
Executing cp -f /home/giardn/.cache/winetricks/ie7/winetest.cat /home/giardn/.wine32//dosdevices/c:/windows/system32/catroot/{f750e6c3-38ee-11d1-85e5-00c04fc295ee}/oem0.cat
Executing cd /home/giardn/.cache/winetricks/ie7
Executing wine winecfg -v winxp
01ac:err:module:import_dll Library shlwapi.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") not found
01ac:err:module:import_dll Library shell32.dll (which is needed by L"C:\\windows\\system32\\start.exe") not found
01ac:err:module:LdrInitializeThunk Importing dlls for L"C:\\windows\\system32\\start.exe" failed, status c0000135
------------------------------------------------------
warning: Note: command wine winecfg -v winxp returned status 53. Aborting.
`

IE7 via winetricks still works currently with Wine6.0.1.
Regards.
```

**Comment by giardn** [comment]
Edit:

If you delete shlwapi from below IE7 will install.

From load_IE7:

# Change the override to the native so we are sure we use and register them
    w_override_dlls native,builtin ieproxy ieframe itircl itss jscript mshtml msimtf shdoclc shdocvw **shlwapi** urlmon wininet xmllite

**Comment by cuppettcj** [comment]
Please note that removing shlwapi from the line @giardn highlighted above will not allow IE7 to install unless you also delete shlwapi from this line below.

`
for dll in itircl itss jscript mshtml msimtf shdoclc shdocvw **shlwapi** urlmon; do
    test -f "${W_SYSTEM32_DLLS}"/${dll}.dll &&
    mv "${W_SYSTEM32_DLLS}"/${dll}.dll "${W_SYSTEM32_DLLS}"/${dll}.dll.bak
done
`

**Comment by giardn** [comment]
Just wanted to confirm that the workaround is still needed in the latest stable build.

**Comment by lilmike** [comment]
Any news on this issue? It still seems to be present in latest wine on void linux, and it seems to not have been picked up :-).
-Michael.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/b3c9f00c0cbb906c53b5add2df9ff5208c6c2649
