### ISSUE TITLE
Add lavfilters to add verb?

### ISSUE THREAD

**Issue by RAMChYLD** [Winetricks/winetricks#1805]
For some games, lavfilters (https://github.com/Nevcairiel/LAVFilters/releases) is preferable to xvid as it has support for more than H.264 codecs. However, winetricks does not recognize lavfilters. Is it possible to add lavfilters verb to winetricks?

**Comment by austin987** [comment]
Do you have some example games that it helps with?

In general, I'm open to it. Would you be interested in sending a PR?

**Comment by bsdf** [comment]
there is already a `lavfilters` verb and a `lavfilters702` verb (last xp supported version). see https://github.com/Winetricks/winetricks/pull/1645
