### ISSUE TITLE
WINE environmental variable not set correctly?

### ISSUE THREAD

**Issue by Supreeeme** [Winetricks/winetricks#1808]
Using `winetricks-git-20210206.r68.gfa11b11a-1` from the AUR.
If I run `winetricks` in a terminal by itself, I get this error:
```warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message ""```

I quickly glanced through the code and it seemed like the WINE env var was never properly set. So then I run 
```WINE=/usr/bin/wine winetricks```
and it works flawlessly. How is this variable supposed to be set?

**Comment by austin987** [comment]
See winetricks_wine_setup().

TL;DR: if WINE is set, it uses that value. If not, it looks in $PATH and a few other known places for a suitable binary.

I'd suggest looking at the output of `which wine` on your system (and/or, you may have a broken WINEPREFIX).

**Comment by Supreeeme** [comment]
The problem seems to be this line:
`WINE="${WINE:-wine}"` (line 5445)
If I run winetricks anywhere but `/usr/bin`, `if test -x "${x}"` is going to be false. If I change line 5445 to `WINE="${WINE:-$(which wine)}"` it works fine. Does the original actually work on other machines?
