### ISSUE TITLE
32-bit Office 365+latest WINE stable+Winetricks not working in Ubuntu

### ISSUE THREAD

**Issue by penalvch** [Winetricks/winetricks#1821]
Hi all, I'm attempting to install Office 365 in a 32-bit prefix, and am blindly following instructions of folks who said they got it to work.
Specifically:

1) Install latest wine-stable as per:
https://wiki.winehq.org/Ubuntu

2) Installed winetricks from default Ubuntu repository.

3) Downloaded offline installer from office.com (filename downloaded 16.0.14026.20302.img).

4) Setup 32-bit wine prefix and installed via winetricks:
WINEARCH=win32 WINEPREFIX=~/.local/share/wineprefixes/32bitprefix winetricks msxml6 riched20

5) Setup two registry entries in 32-bit wine prefix:
Add to registry DWORD "HKCU/Software/Wine/Direct2D/max_version_factory" with value "0"
Add to registry DWORD "HKCU/Software/Wine/Direct3D/MaxVersionGL" with value "30002" (hexadecimal)

6) Attempted to install 32-bit version of Office and got below error message and no successful install:
WINEARCH=win32 WINEPREFIX=~/.local/share/wineprefixes/32bitprefix wine Setup32.exe

Any idea if this is actually a pure wine issue, winetricks, combo, or something else? Thanks!

apt-cache policy wine-stable
wine-stable:
  Installed: 6.0.1~focal-1
  Candidate: 6.0.1~focal-1
  Version table:
 *** 6.0.1~focal-1 500
        500 https://dl.winehq.org/wine-builds/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     6.0.0~focal-1 500
        500 https://dl.winehq.org/wine-builds/ubuntu focal/main amd64 Packages
     5.0.4~focal-1 500
        500 https://dl.winehq.org/wine-builds/ubuntu focal/main amd64 Packages
     5.0.3~focal 500
        500 https://dl.winehq.org/wine-builds/ubuntu focal/main amd64 Packages
     5.0.2~focal 500
        500 https://dl.winehq.org/wine-builds/ubuntu focal/main amd64 Packages
     5.0.1~focal 500
        500 https://dl.winehq.org/wine-builds/ubuntu focal/main amd64 Packages
     4.0.4~focal 500
        500 https://dl.winehq.org/wine-builds/ubuntu focal/main amd64 Packages
     3.0.1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal/universe i386 Packages

apt-cache policy winetricks
winetricks:
  Installed: 0.0+20200412-1
  Candidate: 0.0+20200412-1
  Version table:
 *** 0.0+20200412-1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal/universe i386 Packages
        100 /var/lib/dpkg/status

lsb_release -rd
Description:	Ubuntu 20.04.3 LTS
Release:	20.04

WINEARCH=win32 WINEPREFIX=~/.local/share/wineprefixes/32bitprefix wine Setup32.exe
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:ntdll:EtwEventRegister ({8736922d-e8b2-47eb-8564-23e77e728cf3}, 0042052A, 009D3EB0, 009D3EB0) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 0, 00000000, 0) stub
00c0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00c0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0024:fixme:ntdll:EtwEventRegister ({a019725f-cff1-47e8-8c9e-8fe2635b6388}, 0042052A, 009D40A0, 009D40A0) stub.
0024:fixme:ntdll:EtwEventRegister ({f50d9315-e17e-43c1-8370-3edf6cc057be}, 00505A0A, 009D3EE8, 009D3EE8) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 0, 00000000, 0) stub
0024:fixme:ntdll:EtwEventRegister ({e6aec961-a5e0-5560-a860-15edd6b70f6c}, 00401000, 009D3FB8, 009D3FD0) stub.
0024:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0098BA99, 56) stub
0024:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0024:fixme:ver:GetCurrentPackageId (0031F81C 00000000): stub
0024:fixme:nls:get_dummy_preferred_ui_language (0x8 0031F36C 00000000 0031F368) returning a dummy value (current locale)
0024:fixme:nls:get_dummy_preferred_ui_language (0x8 0031F36C 00A01AD0 0031F368) returning a dummy value (current locale)
0024:fixme:ntdll:EtwEventRegister ({559a5658-8100-4d84-b756-0a47a476280c}, 0042052A, 009D3F68, 009D3F68) stub.
0024:fixme:ntdll:EtwEventRegister ({02fd33df-f746-4a10-93a0-2bc6273bc8e4}, 0042052A, 009D6460, 00A02540) stub.
00f8:fixme:xmllite:xmlreader_SetProperty Unimplemented property (18)
0024:fixme:sync:SetWaitableTimerEx (000000B8, 0031F808, 0, 00000000, 00000000, 00000000, 10744570) semi-stub
00f8:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00f8:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
00f8:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
00f8:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
00f8:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
0024:fixme:exec:SHELL_execute flags ignored: 0x00000100
010c:fixme:powershell:wmain stub: L"C:\\windows\\system32\\WindowsPowershell\\v1.0\\powershell.exe" L"-NoProfile" L"$package = Get-AppxPackage Microsoft.Office.Desktop -allUsers; if (!$package) { $Error.Add(\"Package is not installed\")}; if ($error.Count -eq 0) { Out-File -FilePath 'C:\\users\\moniker\\Temp\\Office.ValidateResult.scratch' -InputObject '1' -Encoding ascii; } else { Out-File -FilePath '"...
0114:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0114:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.28"
0100:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0100:fixme:powrprof:PowerDeterminePlatformRole stub
0058:fixme:mountmgr:query_property Unsupported property 0x7
0100:fixme:ntdll:NtQuerySystemInformation (0x000000c9,0x217f750,0x00000004,(nil)) stub
0100:fixme:bcrypt:BCryptCreateHash ignoring object buffer
0024:fixme:exec:SHELL_execute flags ignored: 0x00000100
0128:fixme:powershell:wmain stub: L"C:\\windows\\system32\\WindowsPowershell\\v1.0\\powershell.exe" L"-NoProfile" L"$package = Get-AppxPackage Microsoft.Office.Desktop -allUsers; if (!$package) { $Error.Add(\"Package is not installed\")}; if ($error.Count -eq 0) { Out-File -FilePath 'C:\\users\\moniker\\Temp\\Office.ValidateResult.scratch' -InputObject '1' -Encoding ascii; } else { Out-File -FilePath '"...
0130:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0130:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.28"
0024:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId=(null)
0144:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0144:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0144:fixme:ntdll:EtwEventRegister ({8736922d-e8b2-47eb-8564-23e77e728cf3}, 00698FF7, 00AEF440, 00AEF440) stub.
0144:fixme:ntdll:EtwEventSetInformation (deadbeef, 0, 00000000, 0) stub
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031FDE4 1 C) semi-stub
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031FDEC 1 C) semi-stub
0144:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0144:fixme:ntdll:EtwEventRegister ({a019725f-cff1-47e8-8c9e-8fe2635b6388}, 00698FF7, 00AF0B28, 00AF0B28) stub.
0144:fixme:ntdll:EtwEventRegister ({f50d9315-e17e-43c1-8370-3edf6cc057be}, 0072BCCC, 00AF0AF0, 00AF0AF0) stub.
0144:fixme:ntdll:EtwEventSetInformation (deadbeef, 0, 00000000, 0) stub
0144:fixme:ntdll:EtwEventRegister ({e6aec961-a5e0-5560-a860-15edd6b70f6c}, 004019F6, 00AF0AB8, 00AF0AD0) stub.
0144:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 009D94F9, 56) stub
0144:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0144:fixme:ver:GetCurrentPackageId (0031F588 00000000): stub
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031EFFC 1 C) semi-stub
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031EE9C 1 C) semi-stub
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031EE0C 1 C) semi-stub
0144:fixme:nls:get_dummy_preferred_ui_language (0x8 0031F180 00000000 0031F17C) returning a dummy value (current locale)
0144:fixme:nls:get_dummy_preferred_ui_language (0x8 0031F180 00B1FD28 0031F17C) returning a dummy value (current locale)
0144:fixme:ntdll:EtwEventRegister ({559a5658-8100-4d84-b756-0a47a476280c}, 00698FF7, 00AF0A78, 00AF0A78) stub.
0144:fixme:ntdll:EtwEventRegister ({02fd33df-f746-4a10-93a0-2bc6273bc8e4}, 00698FF7, 00AF0B80, 00B21010) stub.
0144:fixme:sync:SetWaitableTimerEx (000000BC, 0031F600, 0, 00000000, 00000000, 00000000, 10744320) semi-stub
0148:fixme:xmllite:xmlreader_SetProperty Unimplemented property (18)
0148:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0148:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
0148:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
0148:fixme:ver:GetFileVersionInfoSizeExW flags 0x2 ignored
0148:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
0144:fixme:reg:NtSetInformationKey (0x144,0x00000002,0x31ec30,0x00000004) stub
0144:fixme:rpc:RpcServerRegisterIf3 Unsupported SecurityDescriptor argument.
0150:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0164:fixme:ntdll:EtwEventRegister ({8736922d-e8b2-47eb-8564-23e77e728cf3}, 036C9435, 0380E230, 0380E230) stub.
0164:fixme:ntdll:EtwEventSetInformation (deadbeef, 0, 00000000, 0) stub
0164:fixme:ver:GetCurrentPackageId (0365E918 00000000): stub
0164:fixme:nls:get_dummy_preferred_ui_language (0x8 0365E850 00000000 0365E84C) returning a dummy value (current locale)
0164:fixme:nls:get_dummy_preferred_ui_language (0x8 0365E850 03817EB8 0365E84C) returning a dummy value (current locale)
0150:fixme:powrprof:PowerDeterminePlatformRole stub
0058:fixme:mountmgr:query_property Unsupported property 0x7
0150:fixme:ntdll:NtQuerySystemInformation (0x000000c9,0x200f60c,0x00000004,(nil)) stub
0150:fixme:bcrypt:BCryptCreateHash ignoring object buffer
0064:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETTASKBARPOS, hwnd=00000000): stub
0174:fixme:rpc:RpcBindingSetAuthInfoExW unsupported AuthnSvc 10
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031F1AC 1 C) semi-stub
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031F02C 1 C) semi-stub
017c:fixme:combase:RoGetActivationFactory (L"Windows.Networking.Connectivity.NetworkInformation", {5074f851-950d-4165-9c15-365619481eea}, 0117F574): semi-stub
017c:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Networking.Connectivity.NetworkInformation"
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031ECFC 1 C) semi-stub
0144:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0031ED5C 1 C) semi-stub
0144:fixme:file:NtLockFile I/O completion on lock not implemented yet
0144:fixme:combase:RoGetActivationFactory (L"Windows.Security.Authentication.OnlineId.OnlineIdSystemAuthenticator", {85047792-f634-41e3-96a4-5164e902c740}, 0031F0DC): semi-stub
0144:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Security.Authentication.OnlineId.OnlineIdSystemAuthenticator"
0144:fixme:reg:NtQueryLicenseValue License key L"Microsoft-Windows-Container-License-Mode" not found
0144:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0144:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0144:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0144:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0144:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
018c:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0024:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0024:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0024:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0024:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0024:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031FE98

**Comment by austin987** [comment]
I've never used Office 365 myself, so can't advise more specifically, but I'd definitely recommend fixing:
`00f8:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.`

You'll want to install winbind _then_ install Office in a clean prefix to see if it helps (at least, for the other related winbind/office issues I've seen).

Beyond that, I'd suggest looking at https://forum.winehq.org/ or https://appdb.winehq.org/ for help. Best of luck!

**Comment by Davidos533** [comment]
Same problem, winbind installed, but it not works

**Comment by melroy89** [comment]
combase.dll from Wine didn't implement these methods too bad. It's really a shame, since I believe this is the last thing sppc.dll and combase.dll should implement in Wine, in order to get MS Office working on Wine.

```sh
0200:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Security.Authentication.Web.Core.WebAuthenticationCoreManager"
01fc:err:rpc:I_RpcReceive we got fault packet with status 0xc004f015
01fc:err:rpc:I_RpcReceive we got fault packet with status 0xc004f015
01fc:err:rpc:I_RpcReceive we got fault packet with status 0xc004f002
01fc:err:rpc:I_RpcReceive we got fault packet with status 0xc004f015
01fc:err:rpc:I_RpcReceive we got fault packet with status 0xc004f002
01fc:err:sync:RtlLeaveCriticalSection section 0A9DF108 (null) is not acquired
0254:err:sync:RtlpWaitForCriticalSection section 6F4DAE70 (null) wait timed out in thread 0254, blocked by 01fc, retrying (60 sec)
0254:err:sync:RtlpWaitForCriticalSection section 6F4DAE70 (null) wait timed out in thread 0254, blocked by 01fc, retrying (60 sec)
0254:err:sync:RtlpWaitForCriticalSection section 6F4DAE70 (null) wait timed out in thread 0254, blocked by 01fc, retrying (60 sec)
0254:err:sync:RtlpWaitForCriticalSection section 6F4DAE70 (null) wait timed out in thread 0254, blocked by 01fc, retrying (60 sec)
```
