### ISSUE TITLE
20210825 release reports wrong --version

### ISSUE THREAD

**Issue by tgurr** [Winetricks/winetricks#1822]
https://github.com/Winetricks/winetricks/archive/refs/tags/20210825.tar.gz

$ winetricks --version
20210206-next - sha256sum: 0769bbcdbd92c407f4eacaa85acc1339f607dbeafe2febd1be0912034c7af3a1

https://github.com/Winetricks/winetricks/blob/20210825/src/winetricks#L9

**Comment by austin987** [comment]
This should be fixed in 20220411
