### ISSUE TITLE
vb6run install too old msvbvm60.dll

### ISSUE THREAD

**Issue by malikumaliku** [Winetricks/winetricks#1824]
The vb6run verb uses a KB designed for XP SP3, and install a quite old version of msvbvm60.dll 
It also install ole32 dlls.

The modern wine is targeted Windows 7 by default.

From my experience the msvbvm60.dll from vb6run ends up in some applications having memory access violation happening within this library.

I recommend instead of this verb use KB983234.EXE designed for Win7 SP1 and installing msvbvm60.dll 6.0.98.21
This solve all my problems of memory access violation

**Comment by austin987** [comment]
Can you point to an example application that's affected by this?

**Comment by rokejulianlockhart** [comment]
@austin987, is there any benefit to using an older version, though? https://www.dll-files.com/msvbvm60.dll.html#:~:text=Description-,6.0.98.32,-32 has a version that works for my needs.

**Comment by austin987** [comment]
@rokejulianlockhart We need a legitimate source (i.e., one that Microsoft allows), and from a reputable source. If there's a microsoft.com download that has it, it's possible, but dlls-files.com isn't going to fly.

Also, fyi, generally, comments in closed issues are ignored :).

**Comment by rokejulianlockhart** [comment]
@austin987, I doubt we'll find a better source, since [`msvbvm60.dll` is included with Windows.](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/visual-basic-6-support-policy#:~:text=msadcor.dll-,msvbvm60.dll,-ole2.dll)
