### ISSUE TITLE
dotnet20 verb is removing redistributable librarires

### ISSUE THREAD

**Issue by malikumaliku** [Winetricks/winetricks#1825]
Current wine versions are able to install 2008 redistributables without issues.
It seems that the dotnet20 verb is removing these libraries as a legacy workaround.
This is no longer needed.

Also this verb should regenerate the assembly optimization for 64 bits, and not only for 32

**Comment by austin987** [comment]
> Current wine versions are able to install 2008 redistributables without issues. It seems that the dotnet20 verb is removing these libraries as a legacy workaround. This is no longer needed.

Please clarify, I don't see where any libraries are removed, nor do you explain how that's problematic.

> Also this verb should regenerate the assembly optimization for 64 bits, and not only for 32

Please open a separate issue for that (and if you have an actual problem related, please link/describe it).
