### ISSUE TITLE
release 20210825 misses gpg signature

### ISSUE THREAD

**Issue by josch** [Winetricks/winetricks#1828]
Hi,

in earlier releases, there was a `tar.gz.asc` alongside the `tar.gz`. Please consider adding a signature to the latest release as well. Thanks!

**Comment by jre-wine** [comment]
That was blocked by #1660 
Hopefully soon to be fixed now :)

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/releases/tag/20220411 has a signature again :)
