### ISSUE TITLE
crash: Unimplimented function 

### ISSUE THREAD

**Issue by 15hayden** [Winetricks/winetricks#1830]
I installed the latest version of [Cosmoteer](https://cosmoteer.net/history.html) (version 0.15.16a), but it seems the devs used a function which WINE hasn't implemented yet:

KERNEL32.dll.InitializeContext

[full log](https://pastebin.com/dE5HpuAj)
The game starts up, but fairly early in the loading process it crashes.

**Comment by austin987** [comment]
That has nothing to do with winetricks. It would be a bug in upstream wine, but it's already fixed (since wine-5.17).

**Comment by 15hayden** [comment]
Cool! I just have to update then, thanks!
