### ISSUE TITLE
W2KSP4_EN.EXE no longer available

### ISSUE THREAD

**Issue by vasyugan** [Winetricks/winetricks#1834]
Same as in issue #600 

------------------------------------------------------
```
Executing load_riched20 
Executing cd /home/jr/.cache/winetricks/win2ksp4
Downloading https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE to /home/jr/.cache/winetricks/win2ksp4
Executing cd /home/****
------------------------------------------------------
sha256sum mismatch! Rename /home/****/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE and try again.
------------------------------------------------------

```

The reason is that https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE gets a 404

The entire subdirectory /pub/security doesn't exist any longer.

**Comment by exeter-matthew-wakeling** [comment]
This URL works: https://web.archive.org/web/20130329134722/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE

For an immediate fix, download this file and put it in ~/.cache/winetricks/win2ksp4/

**Comment by gverm** [comment]
@vasyugan @exeter-matthew-wakeling The gnome url is not the url currently used for that package. This means you're running an old winetricks version. Use `winetricks --self-update` to update.
