### ISSUE TITLE
vcrun2019 sha256sum mismatch

### ISSUE THREAD

**Issue by FireRacing** [Winetricks/winetricks#1836]
I tried downloading using both force and non force options. But both of them didn't work.
here is the log:
winetricks vcrun2019
Executing mkdir -p /home/tarun
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206-next - sha256sum: f543edcc89729647fb2226d70fe6efd0dc5ac61e237eaa207a0d461a61b2e229 with wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win64
Executing w_do_call vcrun2019
Executing mkdir -p /home/tarun
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_vcrun2019 
------------------------------------------------------
warning: ucrtbase.dll is no longer included in vcrun2019. For details see: https://github.com/Winetricks/winetricks/issues/1770
------------------------------------------------------
Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcp140_1 msvcp140_2 msvcr140 vcomp140 vcruntime140
Executing wine regedit C:\windows\Temp\override-dll.reg
Executing wine64 regedit C:\windows\Temp\override-dll.reg
------------------------------------------------------
warning: Checksum for /home/tarun/.cache/winetricks/vcrun2019/vc_redist.x86.exe did not match, retrying download
------------------------------------------------------
Executing cd /home/tarun/.cache/winetricks/vcrun2019
Downloading https://aka.ms/vs/16/release/vc_redist.x86.exe to /home/tarun/.cache/winetricks/vcrun2019
--2021-10-22 15:11:41--  https://aka.ms/vs/16/release/vc_redist.x86.exe
Resolving aka.ms (aka.ms)... 23.9.67.140
Connecting to aka.ms (aka.ms)|23.9.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.visualstudio.microsoft.com/download/pr/73b58d04-0049-47d1-9f54-1784792c71cd/80C7969F4E05002A0CD820B746E0ACB7406D4B85E52EF096707315B390927824/VC_redist.x86.exe [following]
--2021-10-22 15:11:42--  https://download.visualstudio.microsoft.com/download/pr/73b58d04-0049-47d1-9f54-1784792c71cd/80C7969F4E05002A0CD820B746E0ACB7406D4B85E52EF096707315B390927824/VC_redist.x86.exe
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 192.229.232.200, 2606:2800:147:ff8:129b:22eb:20b:1347
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|192.229.232.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13780552 (13M) [application/octet-stream]
Saving to: ‘vc_redist.x86.exe’

vc_redist.x86.exe   100%[===================>]  13.14M  12.1MB/s    in 1.1s    

2021-10-22 15:11:43 (12.1 MB/s) - ‘vc_redist.x86.exe’ saved [13780552/13780552]

Executing cd /home/tarun
------------------------------------------------------
warning: sha256sum mismatch! Rename /home/tarun/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again. Alternatively, use --force to ignore this check.
------------------------------------------------------

winetricks vcrun2019 --force
Executing mkdir -p /home/tarun
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206-next - sha256sum: f543edcc89729647fb2226d70fe6efd0dc5ac61e237eaa207a0d461a61b2e229 with wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win64
Executing w_do_call vcrun2019
Executing mkdir -p /home/tarun
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_vcrun2019 
------------------------------------------------------
warning: ucrtbase.dll is no longer included in vcrun2019. For details see: https://github.com/Winetricks/winetricks/issues/1770
------------------------------------------------------
Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcp140_1 msvcp140_2 msvcr140 vcomp140 vcruntime140
Executing wine regedit C:\windows\Temp\override-dll.reg
Executing wine64 regedit C:\windows\Temp\override-dll.reg
------------------------------------------------------
warning: Checksum for /home/tarun/.cache/winetricks/vcrun2019/vc_redist.x86.exe did not match, retrying download
------------------------------------------------------
Executing cd /home/tarun/.cache/winetricks/vcrun2019
Downloading https://aka.ms/vs/16/release/vc_redist.x86.exe to /home/tarun/.cache/winetricks/vcrun2019
--2021-10-22 13:48:13--  https://aka.ms/vs/16/release/vc_redist.x86.exe
Resolving aka.ms (aka.ms)... 23.9.67.140
Connecting to aka.ms (aka.ms)|23.9.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.visualstudio.microsoft.com/download/pr/73b58d04-0049-47d1-9f54-1784792c71cd/80C7969F4E05002A0CD820B746E0ACB7406D4B85E52EF096707315B390927824/VC_redist.x86.exe [following]
--2021-10-22 13:48:14--  https://download.visualstudio.microsoft.com/download/pr/73b58d04-0049-47d1-9f54-1784792c71cd/80C7969F4E05002A0CD820B746E0ACB7406D4B85E52EF096707315B390927824/VC_redist.x86.exe
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 192.229.232.200, 2606:2800:147:ff8:129b:22eb:20b:1347
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|192.229.232.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13780552 (13M) [application/octet-stream]
Saving to: ‘vc_redist.x86.exe’

vc_redist.x86.exe   100%[===================>]  13.14M  5.16MB/s    in 2.5s    

2021-10-22 13:48:17 (5.16 MB/s) - ‘vc_redist.x86.exe’ saved [13780552/13780552]

Executing cd /home/tarun
------------------------------------------------------
warning: sha256sum mismatch! Rename /home/tarun/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again. Alternatively, use --force to ignore this check.

**Comment by CrezyDud** [comment]
`sudo winetricks --self-update`
