### ISSUE TITLE
winetricks mdac28 does not install ODBC data source manager to Control panel (previous version does)

### ISSUE THREAD

**Issue by bikeridercz** [Winetricks/winetricks#1841]
Dear Friends,

current version of winetricks (20210206) does not install ODBC Data source manager into Control panel. Older version of winetricks (20190912) works fine. So it seems to me as a bug somewhere ...

I always do my test in an empty .wine space and I used following command sequence ...

#1 - following sequence leads to warning (_warning: This package (mdac28) does not work on a 64-bit installation. You must use a prefix made with WINEARCH=win32_) and ODBC data source manager is NOT installed in Control panel (checked with _wine control_)
```
cd
rm -rf .wine
winetricks mdac28
```

#2 - following sequence seems to install mdac28 successfully however still ODBC data source manager is NOT installed in Control panel (checked with _wine control_)
```
cd
rm -rf .wine
WINEARCH=win32 winetricks mdac28
```

Running older version of winetricks (20190912) installs ODBC data source manager successfully in both cases (#1 and #2)

Thanks for help & fix

**Comment by austin987** [comment]
Thanks for the report.

It looks like it was removed in https://github.com/Winetricks/winetricks/issues/1448, which references https://source.winehq.org/git/wine.git/?a=commit;h=8f0057699e141a90f7ed4bb00b14aafe5753b6b9 for it no longer being needed.

@alesliehughes what do you think? Wine doesn't provide a control panel for ODBC connections afaict, perhaps continuing to use native odbccp32 makes sense?

**Comment by alesliehughes** [comment]
Here a two bugs that would apply.
https://bugs.winehq.org/show_bug.cgi?id=3158
https://bugs.winehq.org/show_bug.cgi?id=3161

Since these bugs haven't been updated in some time,  to wont hurt too much.  Except it will only be for 32bit prefix.

**Comment by austin987** [comment]
Good point, though I just noticed there's a 64-bit dll in win7sp1:
`misc/filelists/win7sp1_x64.txt:    163840 | 20.11.2010 05:27:24 | amd64_microsoft-windows-m..-odbc-installer-dll_31bf3856ad364e35_6.1.7601.17514_none_eb5109e36bd44af6/odbccp32.dll`

haven't tried it though..

**Comment by austin987** [comment]
Actually, both mdac27/mdac28 are currently 32bit only, so not an issue.

**Comment by bikeridercz** [comment]
@austin987 I do not understand the reason why you closed this bug. The problem still persists, the ODBC datasource manager is missing in control panel, so configuration of ODBC datasource is not possible. Thanks for explanation or suggesting a workaround how to do that without ODBC datasource manager. Thank you.

**Comment by austin987** [comment]
Works here in 8.0 and a 32-bit prefix.

If you have a problem in current wine/winetricks, open a new issue, don't comment on closed ones; the comments may not get seen.
