### ISSUE TITLE
box86/wine (Paspberry Pi OS): warning: bug: w_metadata art2kmin corrupt, might need forward slashes?

### ISSUE THREAD

**Issue by Xiderpunk** [Winetricks/winetricks#1844]
pi@applepi:~/.wine/drive_c $ winetricks corefonts
Executing mkdir -p /home/pi
Using winetricks 20210206-next - sha256sum: 35438443042d8c140e5981a0921c0e8d3b4a0e8f820d3c8b2ba76776d48d54c6 with Box86 with Dynarec v0.2.3 cb9698a5 built on Oct 31 2021 00:05:17
wine-5.13 and WINEARCH=win32
installed_file1="Box86 with Dynarec v0.2.3 cb9698a5 built on Oct 31 2021 00:05:17
------------------------------------------------------
warning: bug: w_metadata art2kmin corrupt, might need forward slashes?

First time using wine and winetricks.. Am running on Raspberry Pi 4 with latest Raspberry Pi OS 32.

**Comment by clort81** [comment]
I got this too with box86
I had to mv /usr/local/bin/wine to /usr/local/bin/wine.orig
then i created a file /usr/local/bin/wine
which contained
```
box86 /usr/local/bin/wine.orig
```
then i chmod uog+x the /usr/local/bin/wine script

Now anytime I, winetricks or any other program tries to execute wine, it launches the i386 /usr/local/bin/wine.orig with box86.

**Comment by clort81** [comment]
I'd hyst completely forgotten my own advice and found this hint again in a websearch :P

**Comment by huangguiniab** [comment]
@clort81 
I am using winetricks downloaded from github.
But I set the environment variable like this and it still doesn't work
````
pi$ BOX86_NOBANNER=1
pi$ winetricks
````
But using the **export** command to set the variable can works
````
pi$ export BOX86_NOBANNER=1
pi$ winetricks
````
I think it's the problem here

**Comment by austin987** [comment]
If someone running box86 wants to send a patch, I'd be happy to review it. I don't use wine/winetricks there, so don't have time to spend on it :).

**Comment by austin987** [comment]
That said, I don't think this can easily be fixed in winetricks, from a quick look (other than maybe a compromise of detecting if box86 is running, and exiting with a gui/cli warning that it won't work without that variable set).

I'm going to close this, as IMO it's not a winetricks bug. If someone provides a PR, we can reopen this.

**Comment by DocMAX** [comment]
Same problem on termux with box64.
`warning: bug: w_metadata art2kmin corrupt, might need forward slashes?`
