### ISSUE TITLE
Cannot download `dotnet472`: 404 Not Found

### ISSUE THREAD

**Issue by iDawer** [Winetricks/winetricks#1845]
```
winetricks dotnet472
Executing mkdir -p /home/dawer
Using winetricks 20210206-next - sha256sum: 0769bbcdbd92c407f4eacaa85acc1339f607dbeafe2febd1be0912034c7af3a1 with wine-6.20 and WINEARCH=win32
Executing w_do_call dotnet472
Executing mkdir -p /home/dawer
Executing load_dotnet472
Executing cd /home/dawer/.cache/winetricks/dotnet472
Downloading https://download.microsoft.com/download/6/E/4/6E48E8AB-DC00-419E-9704-06DD46E5F81D/NDP472-KB4054530-x86-x64-AllOS-ENU.exe to /home/dawer/.cache/winetricks/dotnet472
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1213  100  1213    0     0   2718      0 --:--:-- --:--:-- --:--:--  2719
Executing cd /home/dawer/.wine6_osu/drive_c
------------------------------------------------------
warning: sha256sum mismatch! Rename /home/dawer/.cache/winetricks/dotnet472/NDP472-KB4054530-x86-x64-AllOS-ENU.exe and try again. Alternatively, use --force to ignore this check.
------------------------------------------------------
```

The downloaded `NDP472-KB4054530-x86-x64-AllOS-ENU.exe` is basically "404 Not Found" html file.
Winetricks version: 20210825

**Comment by jamieernest** [comment]
Same, its been the case for a while already... hopefully there is a solution soon

**Comment by some-username-here1** [comment]
After a quick lookup, web archive has a captured webpage dating back to May 5th, 2020:
https://web.archive.org/web/20210505025123/http://download.microsoft.com/download/6/E/4/6E48E8AB-DC00-419E-9704-06DD46E5F81D/NDP472-KB4054530-x86-x64-AllOS-ENU.exe
Can this work as a replacement?

**Comment by jamieernest** [comment]
I think Microsoft uploaded the file to another link, its just up to the devs to update the site. https://download.visualstudio.microsoft.com/download/pr/1f5af042-d0e4-4002-9c59-9ba66bcf15f6/089f837de42708daacaae7c04b7494db/ndp472-kb4054530-x86-x64-allos-enu.exe

I think this is the same file.
