### ISSUE TITLE
Unable to install some packages

### ISSUE THREAD

**Issue by Joe23232** [Winetricks/winetricks#1851]
Hi guys, I am using Arch-based distro. I am running `wine_staging`. I am having some issues:

```
0324:err:module:import_dll Library msvcrt.dll (which is needed by L"C:\\windows\\syswow64\\advapi32.dll") not found
0324:err:module:import_dll Library advapi32.dll (which is needed by L"C:\\windows\\syswow64\\gdi32.dll") not found
0324:err:module:import_dll Library gdi32.dll (which is needed by L"C:\\windows\\syswow64\\user32.dll") not found
0324:err:module:import_dll Library msvcrt.dll (which is needed by L"C:\\windows\\syswow64\\advapi32.dll") not found
0324:err:module:import_dll Library advapi32.dll (which is needed by L"C:\\windows\\syswow64\\setupapi.dll") not found
0324:err:module:import_dll Library msvcrt.dll (which is needed by L"C:\\windows\\syswow64\\advapi32.dll") not found
0324:err:module:import_dll Library advapi32.dll (which is needed by L"C:\\windows\\syswow64\\rpcrt4.dll") not found
0324:err:module:import_dll Library rpcrt4.dll (which is needed by L"C:\\windows\\syswow64\\setupapi.dll") not found
0324:err:module:import_dll Library setupapi.dll (which is needed by L"C:\\windows\\syswow64\\user32.dll") not found
0324:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\syswow64\\start.exe") not found
0324:err:module:LdrInitializeThunk Importing dlls for L"C:\\windows\\syswow64\\start.exe" failed, status c0000135
------------------------------------------------------
warning: vcrun6 installation failed
------------------------------------------------------
```
I got this when I attempt to run `winetricks` to install some packages (after running `winecfg`)

Here are the packages I am trying to install via winetricks:

```text
vb6run
vcrun6
wsh57
corefonts
```

Any ideas why this is happening? This would work last year for this one particular game but this year when I attempt to install it for the exact same game, it wouldn't work.

(Note I did not post the entire output)

**Comment by Chiitoo** [comment]
I've seen similar output for broken Wine prefixes in recent times.

Does this happen with a new, clean prefix?

Generally it's best to include the complete output (if it's huge, then maybe via a 'gist' or a 'pastebin').

Also, please include some version numbers (these verbs seem to work for me, using Wine Staging 6.22-336-g6282718c73bd and Winetricks 20210206-next - sha256sum: 10d6518a92035512f9d5a20fcd8eab0b15dedb8a3c42eb7b6ad703ce909482a2).

**Comment by Joe23232** [comment]
@Chiitoo 

Yes it happens on new prefix mate.

> Generally it's best to include the complete output (if it's huge, then maybe via a 'gist' or a 'pastebin').

Yeah I should do this but what is gist? Never heard of that?

> Also, please include some version numbers (these verbs seem to work for me, using Wine Staging 6.22-336-g6282718c73bd and Winetricks 20210206-next - sha256sum: 10d6518a92035512f9d5a20fcd8eab0b15dedb8a3c42eb7b6ad703ce909482a2).

I just ran `wine --version` and I get this

```cmd
wine-6.22 (Staging)
```

But I am not too sure how do I get the rest of the other information?

**Comment by Chiitoo** [comment]
You can create gists in GitHub via the '+' sign on top of the pages for example, with the terminal output saved in one and then share the link to it.

Winetricks knows the '--version' option too.

**Comment by Chiitoo** [comment]
Oh, at least for 'vcrun6', it looks like it could probably be the same issue as what is mentioned here:

https://github.com/Winetricks/winetricks/issues/1778

If indeed it is the same issue, it looks like the fix happened after the latest release, meaning you'd need to get the script updated manually by, for example, downloading it directly from the GitHub repository.

**Comment by Joe23232** [comment]
Ok so I have to manually download `vcrun6`? I can't just get it from `winetricks` currently?

If this is the case, where would I download `vcrun6` and how would I exactly use it with `wine`/`winetricks`?

**Comment by Chiitoo** [comment]
You can get the 'git master' version of Winetricks and use that.

If you normally install Winetricks via your package manager, I'd probably recommend manually downloading it and use that directly when needed.

If you have manually installed it previously, you could use '--self-update'.

For the manual route, you can download Winetricks from here:

https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

Then simply run it directly, instead of the one installed system-wide.  For example, while in the directory you downloaded it to:

``` bash
$ chmod +x winetricks
$ ./winetricks vcrun6
```

The './' there is important, because otherwise you'll run the system-wide installed version again (you could also run it via 'sh' instead of making it an executable).

**Comment by Joe23232** [comment]
@Chiitoo Thanks mate, do you though when it will be updated for the AUR so that when I do a full system upgrade, then it will also automatically update `winetricks` when it is there?

**Comment by Chiitoo** [comment]
I can't see a 'git master' package in Arch packages/AUR, and I'm not too familiar with their packaging, but I imagine it will indeed appear there quite soon after there is a Winetricks release.

That is, there is no more up to date version right now, anywhere, aside from 'git master'.

**Comment by Joe23232** [comment]
@Chiitoo I ran that command anyways and it works now, thanks anyways mate.

**Comment by Chiitoo** [comment]
Thanks for reporting back!

With that I'll go ahead and close this issue up.

**Comment by Joe23232** [comment]
@Chiitoo No worries mate :)

**Comment by Sartharian** [comment]
for me the command `$ sudo apt-get upgrade` solves the issue (According to winetricks version mismatch conflict)

**Comment by Joe23232** [comment]
Yes it works mate :)
