### ISSUE TITLE
Ubuntu aria2c installed with snap: permission denied

### ISSUE THREAD

**Issue by rizno** [Winetricks/winetricks#1854]
Hi

### Problem
Yesterday I tried to install corefonts with winetricks, but it failed.

### The reason
The reason is the default rights set to the snap version of aria2c with apparmor.
Specifically, apparmor denied write access to the `$HOME/.cache` directory (all top level hidden files and directory in reality).
and winetricks downloads to `$HOME/.cache/winetricks` by default, with aria2c as a default option.

Here the relevant content I found for it `/var/lib/snapd/apparmor/profiles/snap.aria2c.aria2c`:
```
# Allow read/write access to all files in @{HOME}, except snap application
# data in @{HOME}/snap and toplevel hidden directories in @{HOME}.
owner @{HOME}/[^s.]**             rwklix,
```
#### Workaround
One possible workaround is to set the `WINETRICKS_DOWNLOADER` env var to wget for example.

#### Possible way to fix
It would probably be better if winetricks didn't try to use aria2c by default, when it was installed as a snap package.
A simple check with the aria2c program path can do the trick.
```bash
$ which aria2c
/snap/bin/aria2c
```
Detecting if the path start with `/snap` then choose another method like wget, will be a good idea I think.

### System info
- CPU: Intel(R) Core(TM) i7 CPU  920  @ 2.67GHz
- OS: Ubuntu 20.04.3 LTS 64bits

**Comment by austin987** [comment]
I don't think this sort of hack belongs in winetricks. The proper fix would be either to set `WINETRICKS_DOWNLOADER`, or add an apparmor policy that isn't as restrictive.
