### ISSUE TITLE
Unhandled exception: unimplemented function api-ms-win-crt-multibyte-l1-1-0._mbslwr_s_l called in 32-bit code (0x7b032f82).

### ISSUE THREAD

**Issue by synalice** [Winetricks/winetricks#1861]
An error I get when trying to run one program. What can be an issue?

https://pastebin.com/nQRjgFyW

**Comment by austin987** [comment]
It's a missing function in wine (not a winetricks problem).

You should open a bug at https://bugs.winehq.org. While in general you should test in a more recent release, I checked and that function is still unimplemented in 7.0-rc3.

You could try a native dll to work around it; but again, this is outside the scope of winetricks.
