### ISSUE TITLE
WMP9 Successful Install.

### ISSUE THREAD

**Issue by ThePillenwerfer** [Winetricks/winetricks#1865]
After trying on-and-off for years I have finally managed to get Windows Media Player Series 9 installed and working after following these instructions: https://forum.winehq.org/viewtopic.php?t=35626&p=134223#p134240

I was wondering if it would make sense to make this change to winetricks as distributed.

**Comment by austin987** [comment]
It already is, see 80e77bab6fe01d0662e0e20af57b962ecf787719.

**Comment by jkfloris** [comment]
I think ThePillenwerfer is talking about the 32-bit part

```
@@ -16709,7 +16709,10 @@
         w_try "${WINE}" setup_wm.exe ${W_OPT_UNATTENDED:+/Quiet}
         w_warn "wm9codecs is not supported in win64 prefixes. If you need those codecs, reinstall wmp9 in a 32-bit prefix."
     else
-        w_try "${WINE}" MPSetup.exe ${W_OPT_UNATTENDED:+/q}
+        w_try cabextract -d "${W_TMP}" ./MPSetup.exe
+        w_try_cd "${W_TMP}"
+        w_try "${WINE}" setup_wm.exe ${W_OPT_UNATTENDED:+/Quiet}
+
         load_wm9codecs
     fi

```

**Comment by Leebre** [comment]
@jkfloris  I have opened a new issue [here](https://github.com/Winetricks/winetricks/issues/1997) for the problem with wmp9 not installing in a 32-bit prefix.
