### ISSUE TITLE
Can't run winetricks after updating on Debian using self-update

### ISSUE THREAD

**Issue by tomcass240** [Winetricks/winetricks#1878]
I Can't run winetricks after updating on Debian since I used the self-update. Running winetricks gives the following error message:

Using winetricks 20210206-next - sha256sum: 69d9742c1755969e50877216d5f1a2dbd59d6177cb52fdaf1c46bd945cb0c56c with wine-7.0 and WINEARCH=win32
./winetricks: 3539: test: KDE: unexpected operator
winetricks GUI enabled, using none

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/79b10213508ca74eede9d347ab056272c652b080
