### ISSUE TITLE
Kdialog is being used instead of Zenity

### ISSUE THREAD

**Issue by Ahmed-E-86** [Winetricks/winetricks#1881]
Kdialog does not render checkboxes at all, so after updating Winetricks to the latest version, I had to remove **kdialog** because winetricks keeps using it by default instead of **Zenity**.

I use Kubuntu 21.10

**Comment by austin987** [comment]
That was done intentionally, see https://github.com/Winetricks/winetricks/pull/1867

You can override the gui choice with `--gui zenity`, if you want.

I'd suggest filing a bug with KDE for deficiencies with kdialog.

**Comment by Ahmed-E-86** [comment]
Why do I prefer using a longer command line? Winetricks is not good of doing the simplest things.

**Comment by austin987** [comment]
Well, I don't use either GUI.

While kdialog isn't as fully featured as zenity, KDE users generally prefer to use native tools. I don't use either GUI, so I have no opinion on it, but am happy to support both environments, within reason.

Given that you seem to think you know better, what would you recommend? I don't use either, but you seem to think you know better, so please, suggest a better solution, particularly, with code/a pull request.

As an aside, if winetricks isn't helpful for you, feel free to not use it.

**Comment by austin987** [comment]
> That is how winetricks looks with kdialog
Again,  that is a bug for kdialog.

> ![winetricks_bug](https://user-images.githubusercontent.com/29783425/152777894-a1124bdb-6c7d-40b4-b4ee-c7f32f49b40a.png)
> 
> Could you tell which ones are selected?
> 
> I have used winetricks for quite some time, but it is not hard to use an alternative, or to create an alternative for it if I want, and I will probably do that.

Either do that, or submit a patch.

**Comment by mirh** [comment]
> Could you tell which ones are selected?

You meant *installed* perhaps? Selection of individual entries still work fine here. 
And yeah, I agree it's a fairly big regression (there's also this odd spamming of the window coordinates in the terminal)
I don't know whose fault this is then, but I'd rather have this be opt-in rather than opt-out. Look shouldn't come before functionality.
