### ISSUE TITLE
Cannot select existing WINEPREFIX

### ISSUE THREAD

**Issue by Thyssenkrupp234** [Winetricks/winetricks#1882]
I have created a WINEPREFIX in a spot in my $HOME folder, (using grapejuice), how do I select this prefix from Winetricks?

**Comment by austin987** [comment]
As @Chiitoo said, you can use the WINEPREFIX variable if calling via CLI.

In the GUI, selecting the default WINEPREFIX will use ~/.wine. Alternatively, you can select from prefixes under "${XDG_DATA_HOME}/wineprefixes" (or set the environmental variable WINE_PREFIXES to override the prefix parent directory).
