### ISSUE TITLE
vcrun2017 broken with Wine 7.3

### ISSUE THREAD

**Issue by kelppo** [Winetricks/winetricks#1885]
```
SSL_INIT
Executing mkdir -p /home/ketsui/.local/share/wine
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206-next - sha256sum: fa8e1cac62953f13f0964441eac40097d7054a78852ab5a35c925c78a6e89a65 with wine-7.3 and WINEARCH=win64
Executing w_do_call vcrun2017
Executing mkdir -p /home/ketsui/.local/share/wine
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_vcrun2017
Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcp140_1 msvcp140_2 msvcr140 ucrtbase vcomp140 vcruntime140
Executing wine regedit C:\windows\Temp\override-dll.reg
0144:err:module:load_apiset_dll failed to load apiset: c0000482
014c:err:module:load_apiset_dll failed to load apiset: c0000482
0154:err:module:load_apiset_dll failed to load apiset: c0000482
015c:err:module:load_apiset_dll failed to load apiset: c0000482
Executing wine64 regedit C:\windows\Temp\override-dll.reg
0198:err:module:load_apiset_dll failed to load apiset: c0000482
01a0:err:module:load_apiset_dll failed to load apiset: c0000482
01a8:err:module:load_apiset_dll failed to load apiset: c0000482
------------------------------------------------------
warning: Working around wine bug 50894 -- Working around failing wusa.exe lookup via C:\windows\SysNative
------------------------------------------------------
Executing wine winecfg -v winxp64
01b0:err:module:load_apiset_dll failed to load apiset: c0000482
01b8:err:module:load_apiset_dll failed to load apiset: c0000482
01c0:err:module:load_apiset_dll failed to load apiset: c0000482
01c8:err:module:load_apiset_dll failed to load apiset: c0000482
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/ketsui/.local/share/wine/dark_souls terminate
------------------------------------------------------
Executing cabextract -q --directory=/home/ketsui/.local/share/wine/dark_souls/dosdevices/c:/windows/temp/win32 /home/ketsui/.cache/winetricks/vcrun2017/vc_redist.x86.exe -F a10
Executing cabextract -q --directory=/home/ketsui/.local/share/wine/dark_souls/dosdevices/c:/windows/syswow64 /home/ketsui/.local/share/wine/dark_souls/dosdevices/c:/windows/temp/win32/a10 -F ucrtbase.dll
/home/ketsui/.local/share/wine/dark_souls/dosdevices/c:/windows/temp/win32/a10: WARNING; possible 16776 extra bytes at end of file.
Executing cd /home/ketsui/.cache/winetricks/vcrun2017
Executing wine vc_redist.x86.exe
002c:err:module:load_apiset_dll failed to load apiset: c0000482
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
003c:err:module:load_apiset_dll failed to load apiset: c0000482
0048:err:module:load_apiset_dll failed to load apiset: c0000482
0068:err:module:load_apiset_dll failed to load apiset: c0000482
008c:err:module:load_apiset_dll failed to load apiset: c0000482
00a4:err:module:load_apiset_dll failed to load apiset: c0000482
0024:err:module:load_apiset_dll failed to load apiset: c0000482
0024:err:module:import_dll Library api-ms-win-core-string-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-errorhandling-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-timezone-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-file-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-namedpipe-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-handle-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-file-l2-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-heap-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-libraryloader-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-synch-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-processthreads-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-processenvironment-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-datetime-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-localization-l1-2-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-sysinfo-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-synch-l1-2-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-console-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-debug-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-processthreads-l1-1-1.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-file-l1-2-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-profile-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-memory-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-util-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-rtlsupport-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library api-ms-win-core-interlocked-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found
0024:err:module:import_dll Library ucrtbase.dll (which is needed by L"C:\\windows\\system32\\sechost.dll") not found
0024:err:module:import_dll Library sechost.dll (which is needed by L"C:\\windows\\system32\\ADVAPI32.dll") not found
0024:err:module:import_dll Library ADVAPI32.dll (which is needed by L"Y:\\vcrun2017\\vc_redist.x86.exe") not found
```
```
$ winetricks -V
20210206-next - sha256sum: fa8e1cac62953f13f0964441eac40097d7054a78852ab5a35c925c78a6e89a65
```
I noticed that /usr/lib/wine/x86_64-windows/api-ms*.dll are gone in 7.3, might be related?

**Comment by kelppo** [comment]
I tried downgrading to 7.2 and it worked.

**Comment by SSUPII** [comment]
Can confirm this issue happening on 7.3, and reverting to 7.2 fixes it.

**Comment by bearcatjamboree** [comment]
is there a similar issue with 7.0?  i can't get and winetricks to install on mac os

**Comment by SSUPII** [comment]
> Is there a similar issue with 7.0?  i can't get any winetricks to install on Mac OS Monterey.  This is the version I have installed:
> 
> ```
> % wine64 --version
> wine-7.0
> ```
> 
> ```
> % winetricks -V
> 20210206-next - sha256sum: 0769bbcdbd92c407f4eacaa85acc1339f607dbeafe2febd1be0912034c7af3a1
> ```
> 
> ```
> % winetricks vcrun2010
> warning: taskset/cpuset not available on your platform!
> ------------------------------------------------------
> warning: Your version of wine  is no longer supported upstream. You should upgrade to 5.x
> ------------------------------------------------------
> Executing mkdir -p /Users/cboxgo
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> Using winetricks 20210206-next - sha256sum: 0769bbcdbd92c407f4eacaa85acc1339f607dbeafe2febd1be0912034c7af3a1 with  and WINEARCH=win64
> Executing w_do_call vcrun2010
> Executing mkdir -p /Users/cboxgo
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> Executing load_vcrun2010 
> Using native,builtin override for following DLLs: msvcp100 msvcr100 vcomp100 atl100
> Executing wine regedit C:\windows\Temp\override-dll.reg
> /opt/homebrew/bin/winetricks: line 572: /Applications/Wine Stable.app/Contents/Resources/wine/bin/wine: Bad CPU type in executable
> ------------------------------------------------------
> warning: Note: command wine regedit C:\windows\Temp\override-dll.reg returned status 126. Aborting.
> ------------------------------------------------------
> ```
> 

Yours is a different issue from the one in this thread. Running winetricks is broken on Catalina and newer as there is no 32-bit support (it launches `wine`, that is built for 32-bit). Look for  `wine32on64`

**Comment by gverm** [comment]
This is probably [this bug](https://bugs.winehq.org/show_bug.cgi?id=52614), which was fixed by [this commit.](https://source.winehq.org/git/wine.git/commit/603130cc3837524b3c2f6d4338261c3b8ea802ad) It would probably be a good idea to retest with wine-git.

**Comment by bearcatjamboree** [comment]
> > Is there a similar issue with 7.0?  i can't get any winetricks to install on Mac OS Monterey.  This is the version I have installed:
> > ```
> > % wine64 --version
> > wine-7.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > % winetricks -V
> > 20210206-next - sha256sum: 0769bbcdbd92c407f4eacaa85acc1339f607dbeafe2febd1be0912034c7af3a1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > % winetricks vcrun2010
> > warning: taskset/cpuset not available on your platform!
> > ------------------------------------------------------
> > warning: Your version of wine  is no longer supported upstream. You should upgrade to 5.x
> > ------------------------------------------------------
> > Executing mkdir -p /Users/cboxgo
> > ------------------------------------------------------
> > warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> > ------------------------------------------------------
> > Using winetricks 20210206-next - sha256sum: 0769bbcdbd92c407f4eacaa85acc1339f607dbeafe2febd1be0912034c7af3a1 with  and WINEARCH=win64
> > Executing w_do_call vcrun2010
> > Executing mkdir -p /Users/cboxgo
> > ------------------------------------------------------
> > warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> > ------------------------------------------------------
> > Executing load_vcrun2010 
> > Using native,builtin override for following DLLs: msvcp100 msvcr100 vcomp100 atl100
> > Executing wine regedit C:\windows\Temp\override-dll.reg
> > /opt/homebrew/bin/winetricks: line 572: /Applications/Wine Stable.app/Contents/Resources/wine/bin/wine: Bad CPU type in executable
> > ------------------------------------------------------
> > warning: Note: command wine regedit C:\windows\Temp\override-dll.reg returned status 126. Aborting.
> > ------------------------------------------------------
> > ```
> 
> Yours is a different issue from the one in this thread. Running winetricks is broken on Catalina and newer as there is no 32-bit support (it launches `wine`, that is built for 32-bit). Look for `wine32on64`

Thanks for the response.  Unfortunately, the latest version of wine doesn't have wine32on64.  Any ideas where to get it?

**Comment by SSUPII** [comment]
> Thanks for the response. Unfortunately, the latest version of wine doesn't have wine32on64. Any ideas where to get it?

I don't have any experience with Wine on Mac. Maybe take a look here? https://github.com/Gcenx/wine-on-mac

**Comment by kelppo** [comment]
> This is probably [this bug](https://bugs.winehq.org/show_bug.cgi?id=52614), which was fixed by [this commit.](https://source.winehq.org/git/wine.git/commit/603130cc3837524b3c2f6d4338261c3b8ea802ad) It would probably be a good idea to retest with wine-git.

Yep. I just tested again with Wine 7.4 which contains this commit and it works.
