### ISSUE TITLE
returned status 123. Aborting.

### ISSUE THREAD

**Issue by mgarfe** [Winetricks/winetricks#1886]
Hi, i would like to know why these happens and why it happens.
warning: Note: command /usr/local/bin/wine64 dotNetFx40_Full_x86_x64.exe returned status 123. Aborting.
i am getting these message but can not find info about it. Thanks.

**Comment by austin987** [comment]
In short, installing .Net 4.0 failed for some reason. 123 is ERROR_INVALID_NAME (which could be referring to any number of things).

The terminal output may give a hint, but in general, if .Net doesn't work, I'd suggest trying a clean wineprefix. If that fails, it may be a wine bug.
