### ISSUE TITLE
busybox-w32: improved support for Wine

### ISSUE THREAD

**Issue by rmyorston** [Winetricks/winetricks#1887]
I'm no closer to figuring out the issues with busybox-w32 in Wine, previously mentioned in issue #1710.

In the latest release, FRP-4621-gf3c5e8bc3, busybox-w32 detects if it's being run with Wine and adjusts its defaults to suit. No workarounds required!

It would be nice if winetricks could pick up this version.

**Comment by austin987** [comment]
Thanks for the release/letting me know :).

(obligatory comment as an upstream wine person: https://wiki.winehq.org/Developer_FAQ#How_can_I_detect_Wine.3F)

*Quick dogfood testing, vi works*

Ship it, works on me machine :+1: 

https://github.com/Winetricks/winetricks/commits/master
