### ISSUE TITLE
 Wine can't find ALL the DLLs! (wine-7.3)

### ISSUE THREAD

**Issue by cryinkfly** [Winetricks/winetricks#1890]
With the newest version of wine i [can't install any programs](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/202) on my system (openSUSE Tumbleweed)!

What could be the reason that it suddenly stopped working?

Because this problem only started appearing after the release of Wine 7.3 with winetricks.

**Comment by gverm** [comment]
Might be a dupe of #1885. Have you tried with wine-7.4?

**Comment by cryinkfly** [comment]
> Might be a dupe of https://github.com/Winetricks/winetricks/issues/1885. Have you tried with wine-7.4?

Yes, I tried it today and the appeared!
