### ISSUE TITLE
winetricks corefonts returns code 256

### ISSUE THREAD

**Issue by ozanbaba** [Winetricks/winetricks#1892]
I got the latest version from git repo to test this. When I run winetricks corefonts it fails right at the end (even thou it actually install corefonts successfully.) The error is below. 
`warning: impact install completed, but installed file /home/ozan/.wine/dosdevices/c:/windows/Fonts/impact.ttf not found`
The full installation log is attached.
[winetricks.log](https://github.com/Winetricks/winetricks/files/8237255/winetricks.log)
Because it returns error message, it causes the automatic installation scripts to fail.

**Comment by ozanbaba** [comment]
I checked the wine prefix and found impact.ttf in the below folder:
`./drive_c/windows/Fonts/Impact.ttf`
That is a capital i

**Comment by austin987** [comment]
Thanks for the extra info; that made it much easier to find the problem :).

Can you try the referenced commit (https://github.com/austin987/winetricks/commit/a61f6a708d4f5e48c342c11d1e0c7403f9aeb919)?

**Comment by ozanbaba** [comment]
I tested the patch and it worked out without a problem. Thank you for the fix.

**Comment by austin987** [comment]
Great, thanks for the report/debugging/testing :)
