### ISSUE TITLE
dotnet35sp1 is falsely reported as broken

### ISSUE THREAD

**Issue by XandrosDarkstorm** [Winetricks/winetricks#1894]
Winetricks falsely reports .net 3.5 sp1 broken, while accoding to the linked page (https://bugs.winehq.org/show_bug.cgi?id=49690) the issue has been fixed years ago (wine 6.0-rc2).
I use an updated version i got using --self-update command line argument.

**Comment by austin987** [comment]
Thanks; fixed by https://github.com/Winetricks/winetricks/commit/71b2fb4408f3aeaa1c4b2c8962154064c8f43d52
