### ISSUE TITLE
`winetricks nocrashdialog` no longer fully works with Wine 7.5

### ISSUE THREAD

**Issue by qarmin** [Winetricks/winetricks#1897]
In Wine 7.4 I disabled crash dialog by `winetricks nocrashdialog` command and when app crashed, then silently it just exit.
In Wine 7.5 I see that now is visible console window which exit after while

![Screenshot from 2022-03-27 09-49-26](https://user-images.githubusercontent.com/41945903/160272294-dd272f8b-710d-490a-a931-135e3698146b.png)

Steps to reproduce:
- Download https://github.com/qarmin/Win32Fuzzer/releases/download/1.1.0/reproducer_64 (require at least Ubuntu 21.10 or similar)
- Download https://github.com/qarmin/Win32Fuzzer/releases/download/1.1.0/win_project_64.exe
- Run command `./reproducer win_project_64.exe linux`

**Comment by austin987** [comment]
This should be filed upstream, ideally after running a regression test. A quick look through git log doesn't show anything that should require a change in winetricks, but I could be wrong.

**Comment by austin987** [comment]
Also, does `autostart_winedbg=disabled` (in addition to `nocrashdialog`) make any difference?

**Comment by qarmin** [comment]
Looks that this is fixed in wine 7.8
