### ISSUE TITLE
winetricks starts ok from xterm but not from .desktop file nor app launcher nor desktop menu

### ISSUE THREAD

**Issue by aabill2** [Winetricks/winetricks#1901]
This occurred recently, error is "wine cmd.exe /c echo '%AppData%' returned empty string, error message ""

OpenSUSE Tumbleweed 
Wine 7.5
Winetricks latest from tumbleweed and latest from here.

I have inserted echo statements in winetricks which show that W_APPDATA_WIN is indeed empty when winetricks is started from the desktop and "C:\users\aabill\AppData\Roaming" when run from a terminal. As far as I can see from env command runs there is no relevant difference between the desktop and terminal environments - but there must be otherwise there would be no error. I've run within strace in both environments but so far that has not given me a lead.

I should be grateful for suggestions as to what to look for. 

Regards
Bill A.

**Comment by austin987** [comment]
Sounds like https://bugs.winehq.org/show_bug.cgi?id=52773

If you can reliably reproduce it, running a regression test would be helpful:
https://wiki.winehq.org/Regression_Testing

**Comment by aabill2** [comment]
Thanks for prompt response. Regarding reproduce, fault is permanent not intermittent, so that will help. Yep, likely commonality with 52773. Interesting that he's on same OS as I.

I've never had to do regression testing until now, so learning opportunity. 

The fault appeared in just the past few days. I update frequently and my update log shows that winetricks was updated on 20200402 and wine on 20200404. I suspect the latter is the culprit - should I move this to WineHQ?

**Comment by austin987** [comment]
Yes, it's almost certainly a Wine bug. If it's not, I'll be happy to look at it from the winetricks side.

Feel free to CC me on it.

**Comment by moonshaadow** [comment]
Hi, 
I can confirm this issue with wine-staging 7.6 on manjaro.
No issue with wine-staging 7.3.

**Comment by italoghost** [comment]
Can confirm the same error on Arch Linux, Wine-Stagin 7.6

**Comment by italoghost** [comment]
It is working now on Wine Staging 7.7
