### ISSUE TITLE
Can't install .net 4.7.2.

### ISSUE THREAD

**Issue by Rafael000000** [Winetricks/winetricks#1902]
I don't know if this is a wine or a winetricks problem.

When I try to install .net 4.7.2 with the following command:
`WINEARCH=win32 WINEPREFIX=/home/$USER/GarminExpress winetricks dotnet472`

I get the following error:

```
0608:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime Optimization Service"): stub
0608:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x0000044d,00000000,0x0002,0x00000000,01A2F2C8,00000000): stub
0608:err:eventlog:ReportEventW L".NET Runtime Optimization Service (clr_optimization_v4.0.30319_32) - 1>Failed to compile: System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 . Error code = 0x80070003 \n"
0608:err:eventlog:ReportEventW L"System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
0608:fixme:advapi:DeregisterEventSource (CAFE4242) stub
0318:err:ole:CoReleaseMarshalData StdMarshal ReleaseMarshalData failed with error 0x8001011d
0188:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0188:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0188:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0608:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime Optimization Service"): stub
0608:fixme:advapi:DeregisterEventSource (CAFE4242) stub
0188:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 79140000) stub
01bc:err:ole:CoGetContextToken apartment not initialised
0188:fixme:nls:LCIDToLocaleName unsupported flags 8000000
0188:fixme:virtual:NtFlushProcessWriteBuffers stub
```

This error keeps flying and flying down my screen and it doesn't stop.

edit:
OS = ArchLabs Linux

Installed packages:
community/vkd3d 1.3-1 [installed]
community/wine-gecko 2.47.2-3 [installed]
community/wine-mono 7.1.1-1 [installed]
multilib/lib32-vkd3d 1.3-1 [installed]
multilib/wine-staging 7.5-1 [installed]
multilib/winetricks 20220328-1 [installed]

Is there something I am doing wrong?

**Comment by austin987** [comment]
Sounds like https://bugs.winehq.org/show_bug.cgi?id=52722 (which may be fixed in today's git, I'm currently building to test it..).

**Comment by Rafael000000** [comment]
Okay, good to know. Good luck with the testing!!

**Comment by austin987** [comment]
Yep, fixed in git (which was released today as wine-7.6). Please try with that.

**Comment by Rafael000000** [comment]
It works perfectly now!! Thank you!

**Comment by austin987** [comment]
Great. I've marked the upstream bug as fixed in https://github.com/Winetricks/winetricks/commit/29dcd9d304a779134b643c1cfdf6af0b4a791191
