### ISSUE TITLE
How to Install only the specified package?

### ISSUE THREAD

**Issue by marcussacana** [Winetricks/winetricks#1903]
A pain in install dotnet in the winetricks is his recursive dependecies, dotnet462 installs the dotnet461, and the dotnet461 install the dotnet460 and etc...

Sometimes the wine has already installed the dotnet and fails to detect that, then when we try install a certain dotnet version he tries reinstall all versions one by one, I want know if is there a way to skip any 'dependecies' and make the winetricks install only the package that I want to install.

**Comment by austin987** [comment]
It's checking winetricks.log and the `installed_file1` metadata, if set. You'd have to manually make those changes.

However, if those dependencies weren't installed by winetricks, things may break. If they do, you get to keep the pieces :).
