### ISSUE TITLE
Winetricks should show an error or warning when cabextract doesn't exist

### ISSUE THREAD

**Issue by tati1454** [Winetricks/winetricks#1906]
I was trying to use winetricks from source, and when trying to install dotnet45 I spend some time trying to know why it will just not install it, until I used the verbose flag and noted that  it exits on `w_try_cabextract`, after that I just installed cabextract with `sudo dnf install cabextract` and everything worked.

I think it will be nice if winetricks gives you a warning or error telling you that you need cabextract.

**Comment by austin987** [comment]
That should already be the case:
https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L697
![image](https://user-images.githubusercontent.com/464648/164952302-457b28b9-cfdd-4139-816b-71aac7df1061.png)

That said, in local testing, seems it doesn't work in CLI mode, only GUI.

Anyway, next time, please include the terminal output/winetricks version when reporting issues.

**Comment by austin987** [comment]
Could you try with: https://github.com/austin987/winetricks/commit/5f2580cf4ef72466805604288a0a272d8007a301 / https://github.com/austin987/winetricks/tree/issue-1906-cabextract please?

**Comment by tati1454** [comment]
Yep, now it shows the warning.
