### ISSUE TITLE
Problem run winetricks on 5.15.32-1-MANJARO GNOME 41.5 

### ISSUE THREAD

**Issue by rightyhandcream** [Winetricks/winetricks#1907]
First alert pop up:
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

Then this: 
wine cmd.exe /c echo '%AppData%' returned empty string, error message ""

**Comment by austin987** [comment]
What wine/winetricks version? Please attach the terminal output.

This is likely an upstream wine issue, fyi..(try upgrading/downgrading to stable).

**Comment by rightyhandcream** [comment]
This is the terminal output:

Executing mkdir -p /home/rightyhandcream
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 311c8c223bb83a7558b9e51197a9ccf7182bbd63849c64827b87bbc5f627f5cb with wine-7.5 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.42.0
Executing mkdir -p /home/rightyhandcream/.local/share/wineprefixes
------------------------------------------------------
Creating WINEPREFIX "/home/rightyhandcream/.local/share/wineprefixes/linuxconfig" with WINEARCH=win32
------------------------------------------------------
wine: created the configuration directory '/home/rightyhandcream/.local/share/wineprefixes/linuxconfig'
002c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0048:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0050:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:start_rpcss Failed to open RpcSs service
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0048:fixme:imm:ImeSetActiveContext (0x49f300, 0): stub
0048:fixme:imm:ImmReleaseContext (00010020, 0049F300): stub
002c:fixme:imm:ImeSetActiveContext (0x4704b8, 1): stub
002c:fixme:imm:ImmReleaseContext (0001004E, 004704B8): stub
0088:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
0088:fixme:file:NtLockFile I/O completion on lock not implemented yet
0088:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0088:err:mscoree:LoadLibraryShim error reading registry key for installroot
0088:err:mscoree:LoadLibraryShim error reading registry key for installroot
0088:err:mscoree:LoadLibraryShim error reading registry key for installroot
0088:err:mscoree:LoadLibraryShim error reading registry key for installroot
0088:err:mscoree:LoadLibraryShim error reading registry key for installroot
0088:err:mscoree:LoadLibraryShim error reading registry key for installroot
0088:err:mscoree:LoadLibraryShim error reading registry key for installroot
0088:err:mscoree:LoadLibraryShim error reading registry key for installroot
0088:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0088:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0098:fixme:imm:ImeSetActiveContext (0x4adf78, 1): stub
0098:fixme:imm:ImmReleaseContext (0002007A, 004ADF78): stub

**Comment by austin987** [comment]
Yeah, 7.5 was broken in a few ways, particularly for bootup race conditions; Try downgrading to 7.0, or upgrading to 7.7.
