### ISSUE TITLE
Is there a way to set the tempdir location for winetricks?

### ISSUE THREAD

**Issue by n8marti** [Winetricks/winetricks#1908]
running ```winetricks dotnet*``` uses my mounted SD card as a tempdir location, as evidenced by random folders with long, multi-character names that show up at the root level of my SD card during the install process, then disappear when each dotnet installation is complete. Is there an env variable I can pass to winetricks so that it will use my system disk instead? Or some other way to change this behavior? This is causing unnecessary wear and tear on my poor SD card.

**Comment by austin987** [comment]
TMPDIR https://github.com/Winetricks/winetricks/blob/f7f702f270728dce780773445f0e189645f8a836/src/winetricks#L177

**Comment by n8marti** [comment]
If I'm following the winetricks script right, then it looks like the location to unpack to is actually chosen by the wine executable rather than winetricks:
https://github.com/Winetricks/winetricks/blob/f7f702f270728dce780773445f0e189645f8a836/src/winetricks#L9210
```
    WINEDLLOVERRIDES=fusion=b w_try_ms_installer "${WINE}" dotNetFx40_Full_x86_x64.exe ${W_OPT_UNATTENDED:+/q /c:"install.exe /q"}
```
Is this more of a wine issue than winetricks?

**Comment by austin987** [comment]
No, it's a .Net issue :). You'd need to report that to Microsoft.
