### ISSUE TITLE
Wine freezes during vc_redist.x64.exe setup installation

### ISSUE THREAD

**Issue by seisdr** [Winetricks/winetricks#1911]
```
wine --version
wine-5.0.3 (Ubuntu 5.0.3-3ubuntu2)
```
Same problem with wine staging 7.8 latest 
![IMG_٢٠٢٢٠٥١٢_١٣٣٢٤٩](https://user-images.githubusercontent.com/45742462/168051569-f23c8ecb-b1f2-450a-92ca-9d86c7a57548.jpg)

It stays like that

**Comment by seisdr** [comment]
I can't even cancel , after that whenever i try to run wincfg ,or any other application the same installation window keeps popping up

**Comment by seisdr** [comment]
Trying to install that minimum runtime ,it says 
```
root@localhost:~/.wine/drive_c/windows/temp/{369499B1-4D4F-44D8-8A7F-4CA72904782B}#
root@localhost:~/.wine/drive_c/windows/temp/{369499B1-4D4F-44D8-8A7F-4CA72904782B}# wine msiexec /i vcRuntimeAdditional_x64
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
0009:err:mscoree:LoadLibraryShim error reading registry key for installroot
```
![IMG_٢٠٢٢٠٥١٢_١٣٤٠٢٩](https://user-images.githubusercontent.com/45742462/168052919-f2210fb0-1e43-4d45-8b15-dd7b6d332594.jpg)

**Comment by austin987** [comment]
Works fine here. I'd suggest trying a clean WINEPREFIX. If it persists, try https://forum.winehq.org/, this is almost certainly not a winetricks problem.
