### ISSUE TITLE
Incorrectly implemented older Windows versions

### ISSUE THREAD

**Issue by danger89** [Winetricks/winetricks#1913]
Hi,

During testing with [WineGUI](https://gitlab.melroy.org/melroy/winegui), which is using winetricks under the hood in some cases. Setting some older WIndows versions actually is causing issues. 

**Disclaimer:** I'm the developer of WineGUI.

If you don't believe my code maybe you believe another tool called `winecfg`? 😆 . Winecfg has also trouble detected the Windows version when winetricks was used to change it.

The following Windows versions are effecting when using `winetricks` (example of setting a different win version: `winetricks win30`).

- Windows NT 4.0 - `nt40`
- Windows NT 3.51 - `nt351`
- Windows 3.1 - `win31`
- Windows 3.0 - `win30`
- Windows 2.0 - `win20`

Please take a look at the source code of Winecfg how they implemented setting WIndows versions of both NT releases as well as Windows 2 and Windows 3.x: 

* https://github.com/wine-mirror/wine/blob/master/programs/winecfg/appdefaults.c#L430 (NT code)
* https://github.com/wine-mirror/wine/blob/master/programs/winecfg/appdefaults.c#L454 (Winecfg Windows v2 / v3.x code)

The last line (`set_reg_key(config_key, keypath(L""), L"Version"`) is setting the windows version for Windows 2.0 and WIndows 3.x according to the string (`szVersion`) in the enum struct: https://github.com/wine-mirror/wine/blob/master/programs/winecfg/appdefaults.c#L51

Related issue in my GitLab: https://gitlab.melroy.org/melroy/winegui/-/issues/26

If you have further questions, please let me know. 

Regards,
Melroy van den Berg

**Comment by austin987** [comment]
It works fine here (verified with winecfg):
```
austin@hyrule:~$ wineserver -k ; rm -rf ~/.wine ; winetricks -q win20 ; wine winecfg /v
Executing mkdir -p /home/austin
Using winetricks 20220411-next - sha256sum: 4838f1f5e7f3552d4f2dcdd5679d4abebe6980dbb4dd38557093e88ad51932b8 with wine-7.8 and WINEARCH=win32
Executing w_do_call win20
Executing mkdir -p /home/austin
Executing load_win20 
Executing wine winecfg -v win20
------------------------------------------------------
warning: Running /usr/local/bin/wineserver -w. This will hang until all wine processes in prefix=/home/austin/.wine terminate
------------------------------------------------------
win20
```

Unless you're using a really old wine version (<5.7) which would trigger the old code path (which, coincidentally doesn't support win20 at all, it would just bail out).

I don't see any instructions on how to reproduce on the linked issue either..

**Comment by danger89** [comment]
AH, I'm indeed using the default wine version from Linux Mint (based on Ubuntu LTS). `winecfg` does support switching all Windows versions.

https://packages.ubuntu.com/focal/wine

I but guess you already gave the answer, `winetricks` doesn't support wine v5.

**Comment by danger89** [comment]
Again thank you so much for your fast reply.

**Comment by austin987** [comment]
Note that most windows versions will work, just not the the ones you pointed out, in old wine.


Also note if you plan to stick to that old wine version, you should pin/fork winetricks, as things will break at some point..

**Comment by danger89** [comment]
> Also note if you plan to stick to that old wine version, you should pin/fork winetricks, as things will break at some point..

Nah. I think I will provide an automated way for users to install the latest winehq stable version depending on their distro. Winegui should support the user and make wine as easy as possible. Which should include the latest stable release of wine itself.
