### ISSUE TITLE
ie8 doesn't install

### ISSUE THREAD

**Issue by polkoav** [Winetricks/winetricks#1915]
user@astra:~$ winetricks ie8
Executing mkdir -p /home/user
Using winetricks 20220411-next - sha256sum: 918989a44c3442e1eb84f38746253ab099fa36746468af95f28d089548fb53f2 with wine-7.9 (Staging) and WINEARCH=win32
Executing w_do_call ie8
Executing mkdir -p /home/user
Executing load_ie8 
Executing wine winecfg -v winxp

warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/user/.wine terminate

Executing w_do_call msls31
Executing mkdir -p /home/user
Executing load_msls31 
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/temp /home/user/.cache/winetricks/msls31/InstMsiW.exe
Executing cp -f /home/user/.wine/dosdevices/c:/windows/temp/msls31.dll /home/user/.wine/dosdevices/c:/windows/system32/msls31.dll
Using native,builtin override for following DLLs: ieframe ieproxy itircl itss jscript msctf mshtml shdoclc shdocvw shlwapi urlmon wininet xmllite
Executing wine regedit C:\windows\Temp\override-dll.reg
Using native override for following DLLs: iexplore.exe
Executing wine regedit C:\windows\Temp\override-dll.reg
Using builtin override for following DLLs: updspapi
Executing wine regedit C:\windows\Temp\override-dll.reg
Executing cp -f /home/user/.cache/winetricks/ie8/winetest.cat /home/user/.wine/dosdevices/c:/windows/system32/catroot/{f750e6c3-38ee-11d1-85e5-00c04fc295ee}/oem0.cat
Executing mv /home/user/.wine/dosdevices/c:/Program Files/Internet Explorer/iexplore.exe /home/user/.wine/dosdevices/c:/Program Files/Internet Explorer/iexplore.exe.bak
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/browseui.dll /home/user/.wine/dosdevices/c:/windows/system32/browseui.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F browseui.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/inseng.dll /home/user/.wine/dosdevices/c:/windows/system32/inseng.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F inseng.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/itircl.dll /home/user/.wine/dosdevices/c:/windows/system32/itircl.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F itircl.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/itss.dll /home/user/.wine/dosdevices/c:/windows/system32/itss.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F itss.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/jscript.dll /home/user/.wine/dosdevices/c:/windows/system32/jscript.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F jscript.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/mshtml.dll /home/user/.wine/dosdevices/c:/windows/system32/mshtml.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F mshtml.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/shdoclc.dll /home/user/.wine/dosdevices/c:/windows/system32/shdoclc.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F shdoclc.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/shdocvw.dll /home/user/.wine/dosdevices/c:/windows/system32/shdocvw.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F shdocvw.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/shlwapi.dll /home/user/.wine/dosdevices/c:/windows/system32/shlwapi.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F shlwapi.dll
Executing mv /home/user/.wine/dosdevices/c:/windows/system32/urlmon.dll /home/user/.wine/dosdevices/c:/windows/system32/urlmon.dll.bak
Executing cabextract -q --directory=/home/user/.wine/dosdevices/c:/windows/system32 /home/user/.cache/winetricks/ie8/IE8-WindowsXP-x86-ENU.exe -F urlmon.dll
Executing cd /home/user/.cache/winetricks/ie8
01e8:fixme:imm:ImeSetActiveContext (003484E0, 1): stub
01e8:fixme:imm:ImmReleaseContext (00010062, 003484E0): stub
01d0:fixme:imm:ImeSetActiveContext (0074A7F8, 0): stub
01d0:fixme:imm:ImmReleaseContext (0002003A, 0074A7F8): stub
01e4:fixme:clusapi:GetNodeClusterState ((null),0021EC44) stub!
01e4:fixme:advapi:DecryptFileA ("c:\\1cbd57c9bb41004d4353413239\\", 00000000): stub
01f0:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2821408-c59d-418f-ad3f-aa4e792aeb79}
01f0:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01f0:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01f0:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01f0:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01f0:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId=(null)
01f0:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01f0:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01f0:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01f0:fixme:cryptasn:CRYPT_GetBuiltinDecoder Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
01f0:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
01f0:fixme:richedit:editor_handle_message EM_SETMARGINS: stub
01f0:fixme:imm:ImeSetActiveContext (00407890, 1): stub
01f0:fixme:imm:ImmReleaseContext (00010084, 00407890): stub
01f0:fixme:wuapi:update_session_put_ClientApplicationID 00403100, L"Windows Internet Explorer 8 Setup Utility"
01f8:fixme:wuapi:automatic_updates_Pause 
01f0:fixme:wuapi:update_searcher_BeginSearch 
0204:fixme:setupapi:pSetupGetGlobalFlags stub
wine: Unhandled exception 0x00000000 in thread 204 at address 7BC25C98 (thread 0204), starting debugger...
Can't attach process 0200: error 5
020c:fixme:imm:ImeSetActiveContext (0077FBF8, 1): stub
020c:fixme:imm:ImmReleaseContext (00010148, 0077FBF8): stub
0214:fixme:imm:ImeSetActiveContext (00741680, 0): stub
0214:fixme:imm:ImmReleaseContext (00020110, 00741680): stub
01f0:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x10000000
0228:fixme:winhttp:session_set_option 0 (null) (null)
0228:fixme:winhttp:request_set_option 0 (null) (null)
0258:fixme:imm:ImeSetActiveContext (00757350, 1): stub
0258:fixme:imm:ImmReleaseContext (0004006E, 00757350): stub

warning: Обход ошибки 25648 -- Setting TabProcGrowth=0 to avoid hang

Executing wine regedit C:\windows\Temp\set-tabprocgrowth.reg
Executing cp -f /home/user/.wine/dosdevices/c:/Program Files/Internet Explorer/ieproxy.dll /home/user/.wine/dosdevices/c:/windows/system32/ieproxy.dll
cp: не удалось выполнить stat для '/home/user/.wine/dosdevices/c:/Program Files/Internet Explorer/ieproxy.dll': Нет такого файла или каталога

warning: Важно: команда cp -f /home/user/.wine/dosdevices/c:/Program Files/Internet Explorer/ieproxy.dll /home/user/.wine/dosdevices/c:/windows/system32/ieproxy.dll вернула статус 1. Прерывание.
![Screenshot_20220602_105846](https://user-images.githubusercontent.com/106730509/171583765-4ff12337-f62b-443c-999e-0390a256b417.png)

**Comment by austin987** [comment]
It looks like it's a regression upstream:
https://bugs.winehq.org/show_bug.cgi?id=53103

I don't think there's anything winetricks can do to work around it; it will (likely) need a fix upstream.
