### ISSUE TITLE
gdiplus+ cabextract aborted

### ISSUE THREAD

**Issue by khughitt** [Winetricks/winetricks#1916]
Greetings!

I'm attempting to use winetricks to install `gdiplus+`:

```
winetricks --force --verbose gdiplus
```

But `cabextract` fails with a return status of "1":

```
warning: Note: command cabextract -q -d /home/<user>/.wine-tmp/dosdevices/c:/windows/temp -L -F amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_2b24536c71ed437a/gdiplus.dll /home/<user>/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe returned status 1. Aborting.
```

Verbose output: [winetricks-gdiplus-cabextract-error.txt](https://github.com/Winetricks/winetricks/files/8846067/winetricks-gdiplus-cabextract-error.txt)

I've tried several times, including using a clean wine prefix, but run into the same issue.

Any ideas what the issue could be?

**System info**

- Arch linux (5.18.1)
- wine-staging (7.8)
- winetricks (20220411 - sha256sum: 69856050cfe9d97902dfd68c1ad42a10a4be0fe76660744126d7e3ed75610495)

**Comment by picobyte** [comment]
it probably means that gdiplus.dll is no longer in the cab archive.

**Comment by austin987** [comment]
@khughitt works fine here. What does `cabextract --version` say? I'm running `cabextract version 1.9`.

@picobyte that's a different verb (so theoretically it should be it's own issue). gdiplus_winxp also works here with 1.9. That said, is that a symlink or is there something else that is atypical about your environment?

The sha256 checked out for the original issue, so the cabinet file itself is fine.

**Comment by austin987** [comment]
In either case, try running cabextract manually (without -q):
`cabextract -d /tmp/ -L -F amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_2b24536c71ed437a/gdiplus.dll`

and see if that gives more helpful information

**Comment by khughitt** [comment]
@austin987 Thanks!

I was able to figure out the issue after trying your suggestion of `cabextract` separately. (version 1.9.1, btw..)

It turns out the version of `windows6.1-KB976932-X64.exe` in the winetricks cache was corrupted.

I had tried to re-download it in the past with no luck, but perhaps there was in issue with my connection (or worse, memory), that was corrupting the file repeatedly.

I wiped it from the cache and re-ran the `winetricks` command just now though and it seems to have worked fine.

Closing this as a non-issue.

Thanks for the feedback and suggestions. 



 for the suggestions! I'm using `cabextract version 1.9.1`, but I actually tracked it down, after following you

**Comment by austin987** [comment]
> @austin987 Thanks!
> 
> It turns out the version of `windows6.1-KB976932-X64.exe` in the winetricks cache was corrupted.
> 
> I had tried to re-download it in the past with no luck, but perhaps there was in issue with my connection (or worse, memory), that was corrupting the file repeatedly.
> 
> I wiped it from the cache and re-ran the `winetricks` command just now though and it seems to have worked fine.

Thanks for following up! I think this has affected others, but it slipped through the cracks. There's been a longstanding hack that prevented checksums over 500MB (because it annoyed users). win7sp1 is over 500MB, so it's checksum check never triggered.

Given that many/most have migrated to SSDs (and that it hid a _real_ problem), I'm going to remove the size check. Not to mention that most stuff is under 500MB (other than the games that aren't yet removed, but they're not my priority).

Fix incoming, running through tests.
