### ISSUE TITLE
Ubuntu - winetricks fails to install dotnet with sbrk() error

### ISSUE THREAD

**Issue by stubkan** [Winetricks/winetricks#1919]
I'm making this issue as I cannot find a single mention on the internet that references the sbrk() error I'm constantly getting. 

Whenever I try to install dotnet48 into a proton prefix with winetricks it throws errors and aborts.  If I change the proton or eggroll proton version, wine version, winetricks version, install method etc - it will output different dotnet abort error codes but each time there are sbrk() errors that say.

sbrk() failure while processing tunables

Sometimes it says it once, sometimes it says it 5 times.  There are also some other errors that come up, but they seem normal - as I've seen them on other peoples logs.

![image](https://user-images.githubusercontent.com/34361592/177666806-8132132a-d358-4b9c-92f5-0156c4a58618.png)

I've tried for a few days, with various different driver versions, proton versions, wine/winetricks versions - I've updated my system, updated graphics drivers,  At a loss now, cos I have absolutely no idea what is wrong.

**Comment by austin987** [comment]
Something is broken on your system. Maybe bad ram? Try running memtest.

**Comment by stubkan** [comment]
I do have Visual Studio Code and Unreal Engine on the system and have been compiling c# for various games, I might have changed the glibc/libc version while getting those things working

**Comment by stubkan** [comment]
![image](https://user-images.githubusercontent.com/34361592/177873338-8bb1e79d-d3ba-4fc3-976c-f627c4cbc5c5.png)

It seems Ive got 2.31 installed, though thats from 2020, and it is up to v2.35 now.  According to this post

https://askubuntu.com/questions/1389796/how-to-install-a-libc6-version-newer-than-2-31-on-ubuntu-20-04-focal-fossa

Updating it is a bad idea...  Not sure what to do then.

**Comment by Chiitoo** [comment]
Generally updating glibc is okay, but only if everything else in the system will be fine with it, which probably isn't the case with Ubuntu-like distros (older things often break with new glibc).

Going backwards is what will even more easily break things though!

With Ubuntu and such I think it's best to stick to what you get from the supported repositories, so if you're not using any weird "ppa" sources and are up-to-date, this should be re-produceable pretty easily with knowing the version of the distribution and all, unless it's a hardware issue.

**Comment by stubkan** [comment]
Yeah I got some scary messages but I carefully downgraded each package to the main distro version, seems like it is back to official repo packages now...

I followed this

>      Install the following packages:                                            
>      libc-bin:i386 [2.31-0ubuntu9.9 (focal-updates)]                          
>      libc-dev-bin:i386 [2.31-0ubuntu9.9 (focal-updates)]                      
> 
>      Keep the following packages at their current version:                      
>      libcrypt-dev [1:4.4.10-10ubuntu4 (focal, now)]                           
>      locales [2.31-0ubuntu9.9dso1 (now)]                                      
> 
>      Downgrade the following packages:                                          
>      libc6 [2.31-0ubuntu9.9dso1 (now) -> 2.31-0ubuntu9.9 (focal-updates)]     
>     libc6:i386 [2.31-0ubuntu9.9dso1 (now) -> 2.31-0ubuntu9.9 (focal-updates)]
>      libc6-dev [2.31-0ubuntu9.9dso1 (now) -> 2.31-0ubuntu9.9 (focal-updates)] 
> 
>      Leave the following dependencies unresolved:                               
>      gdb recommends libc-dbg    

Bad news is, sbrk errors are still there.
![image](https://user-images.githubusercontent.com/34361592/177885036-5f26b4ec-9fca-4c6f-9e72-017537699f31.png)

Do I have to reinstall other software such as wine from scratch, because they were compiled when installed with the non-official glibc?

**Comment by austin987** [comment]
@stubkan, if you have another partition/hdd/usb, it would be worth trying a stock install of whatever version of ubuntu you're running, so that you can try a clean setup on the same hardware, to narrow down if it's a hardware/software issue.

**Comment by stubkan** [comment]
Well, that took a long dang time, but I got a USB live usb set up of the system - Ubuntu Mint 20.1 and installed wine64 7.0 then winetricks.

It installed dotnet 4.0 successfuly but after several hours of non stop scrolling errors I figured something was off and stopped it, winetricks was the 2020 version so I self updated it and did it again.

It installed dotnet 48 successfully with no fuss.  I dont think it's a hardware issue.

**Comment by stubkan** [comment]
I could use the liveusb to install dotnet into the one prefix I need it in and copy it over and hope that is enough..  Though this sbrk thing bugs me and may be causing problems elsewhere...  I'd like the system to be clean.

I suspect in newer glibc versions they have removed the sbrk function and use another method - Maybe I can run the newer glibc somehow and see if that error still comes up, though I have no idea how to go about setting that up.

**Comment by austin987** [comment]
Well, one thing is clear, it's not a winetricks issue, but an issue with your system.

Your distro or whoever provided the PPA that you got gliibc from may be able to provide better help.

**Comment by stubkan** [comment]
There was a line in .profile that said

export GLIBC_TUNABLES=glibc.rtld.dynamic_sort=2

Removing the line fixed the issue.  I think it was a line that went in to fix Unreal Engine issues.

**Comment by Chiitoo** [comment]
A-ha!

Good to know.  Thank you for sharing!

**Comment by austin987** [comment]
> There was a line in .profile that said
> 
> export GLIBC_TUNABLES=glibc.rtld.dynamic_sort=2
> 
> Removing the line fixed the issue. I think it was a line that went in to fix Unreal Engine issues.

Glad you got it fixed.

If it's still needed for Unreal, I'd suggest removing it from ~/.profile, and instead make a wrapper script, so that you only export that variable when running Unreal, and avoid affecting the rest of your system.
