### ISSUE TITLE
vcrun2010 issue

### ISSUE THREAD

**Issue by hsghost** [Winetricks/winetricks#1921]
```
Executing mkdir -p /Users/hsghost/Applications/C C Red Alert 2 2.app/Contents/SharedSupport
Using winetricks 20220411-next - sha256sum: 9c7a56cfca32c7c06bdfd7e7646266b404381ef26c268ea88f1b6fa3acfbc27c with wine-21.1.0-21-g86686222 and WINEARCH=win32
Executing w_do_call vcrun2010
Executing mkdir -p /Users/hsghost/Applications/C C Red Alert 2 2.app/Contents/SharedSupport
Executing load_vcrun2010 
Using native,builtin override for following DLLs: msvcp100 msvcr100 vcomp100 atl100
Executing wine C:\windows\system32/regedit /S C:\windows\Temp\override-dll.reg
Executing cd /Users/hsghost/.cache/winetricks/vcrun2010
Executing wine vcredist_x86.exe /q
------------------------------------------------------
warning: Note: command wine vcredist_x86.exe /q returned status 87. Aborting.
------------------------------------------------------

```

Don't know what does the status 87 mean. Spotted problem when installing RA2 through Origin, it failed with the vcredist_x86.exe reporting a "language not supported" error. So I tried with this winetrick but fails too.

**Comment by austin987** [comment]
`Using winetricks 20220411-next - sha256sum: 9c7a56cfca32c7c06bdfd7e7646266b404381ef26c268ea88f1b6fa3acfbc27c with wine-21.1.0-21-g86686222 and WINEARCH=win32`

Where did you get your wine build from?

Anyway, it's a bug in the wine build. Try in 7.0/7.12.

**Comment by Gcenx** [comment]
> `Using winetricks 20220411-next - sha256sum: 9c7a56cfca32c7c06bdfd7e7646266b404381ef26c268ea88f1b6fa3acfbc27c with wine-21.1.0-21-g86686222 and WINEARCH=win32`
> 
> Where did you get your wine build from?

That’s one of mine that’s WineCX21.1.0 that’s based on crossover-sources-21.1.0 so winw-6.0

> Anyway, it's a bug in the wine build. Try in 7.0/7.12.

Unless there running macOS Mojave that’s currently not possible until CX22 lands along with its sources (based on wine-7.6?)

**Comment by Gcenx** [comment]
```
Executing mkdir -p /Users/gcenx/Applications/Wineskin/CX21.1.0.app/Contents/SharedSupport
Using winetricks 20220411-next - sha256sum: 9c7a56cfca32c7c06bdfd7e7646266b404381ef26c268ea88f1b6fa3acfbc27c with wine-21.1.0-21-g86686222 and WINEARCH=win32
Executing w_do_call vcrun2010
Executing mkdir -p /Users/gcenx/Applications/Wineskin/CX21.1.0.app/Contents/SharedSupport
Executing load_vcrun2010 
Using native,builtin override for following DLLs: msvcp100 msvcr100 vcomp100 atl100
Executing wine C:\windows\system32/regedit /S C:\windows\Temp\override-dll.reg
Executing cd /Users/gcenx/.cache/winetricks/vcrun2010
Executing wine vcredist_x86.exe /q



 Winetricks Commands Finished!!

```

Just tried this on my own system and `vcrun2010` installed without issue.

**Comment by austin987** [comment]
FYI, Error 87 is ERROR_INVALID_PARAMETER.

> > `Using winetricks 20220411-next - sha256sum: 9c7a56cfca32c7c06bdfd7e7646266b404381ef26c268ea88f1b6fa3acfbc27c with wine-21.1.0-21-g86686222 and WINEARCH=win32`
> > Where did you get your wine build from?
> 
> That’s one of mine that’s WineCX21.1.0 that’s based on crossover-sources-21.1.0 so wine-6.0

That may be confusing in ~14 years when wine catches up to version 21 ;). Maybe you have it report the wine version as 'winecx' a la what wine-staging does.

It also installs fine here in wine-6.0:
```
austin@hyrule:~$ wineserver -k ; rm -rf ~/.wine ; WINE=/opt/oldwine/wine-6.0/bin/wine winetricks -q vcrun2010
Executing mkdir -p /home/austin
Using winetricks 20220411-next - sha256sum: 106f9ed668d592cb44aa48e8bcb86f4123c1e55e638b6d2216c5b746fd840071 with wine-6.0 and WINEARCH=win32
Executing w_do_call vcrun2010
Executing mkdir -p /home/austin
Executing load_vcrun2010 
Using native,builtin override for following DLLs: msvcp100 msvcr100 vcomp100 atl100
Executing /opt/oldwine/wine-6.0/bin/wine regedit /S C:\windows\Temp\override-dll.reg
Executing cd /home/austin/.cache/winetricks/vcrun2010
Executing /opt/oldwine/wine-6.0/bin/wine vcredist_x86.exe /q
01f4:fixme:clusapi:GetNodeClusterState ((null),0031EC44) stub!
01f4:fixme:advapi:DecryptFileA ("c:\\ffc11d8d20a98d341fb016f52df85e72\\", 00000000): stub
021c:fixme:ntdll:EtwRegisterTraceGuidsW (00335F38, 00340180, {e2821408-c59d-418f-ad3f-aa4e792aeb79}, 1, 0031ED10, (null), (null), 00340188): stub
021c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2821408-c59d-418f-ad3f-aa4e792aeb79}
021c:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
021c:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
021c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
021c:fixme:advapi:LsaOpenPolicy ((null),0031F518,0x00000001,0031F50C) stub
021c:fixme:security:GetWindowsAccountDomainSid (0031F384 001C424C 0031F380): semi-stub
021c:fixme:secur32:GetComputerObjectNameW NameFormat 7 not implemented
021c:fixme:advapi:LsaClose (0000CAFE) stub
0220:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.25"
0220:fixme:file:NtLockFile I/O completion on lock not implemented yet
0220:fixme:wintrust:SOFTPUB_VerifyImageHash Cannot verify hash for pszObjId="1.3.6.1.4.1.311.2.1.30"
021c:fixme:advapi:LsaOpenPolicy ((null),0031F368,0x00000001,0031F35C) stub
021c:fixme:security:GetWindowsAccountDomainSid (0031F1D4 001C095C 0031F1D0): semi-stub
021c:fixme:secur32:GetComputerObjectNameW NameFormat 7 not implemented
021c:fixme:advapi:LsaClose (0000CAFE) stub
021c:fixme:ntdll:EtwUnregisterTraceGuids deadbeef: stub
```

I don't have the crossover source built to test that. The problem may be elsewhere on the system, but since it was a strange version I suspect it may have been some change in it.

Given that it works on your system with the same version, I suspect it may something on @hsghost's system. Or, more simply, an issue with the WINEPREFIX? What happens if you try it in a new WINEPREFIX?

**Comment by hsghost** [comment]
Just had the time to test it again. The culprit I found at last, is the locale setting. My macOS is set to display in Chinese, and I have to `export LANG=zh_CN.UTF-8` to make it to work, finally. No more complaint of `status 87`. The wrapper seems to interpreting the host locale in some erroneous manner, so I have to set it manually like this.

Anyway, I feel that the winetrick should not be interrupted by such locale settings. Although from my discovery this could largely be a bug on the `vcredist_x86.exe` side, some way to circumvent this bug should be devised.

**Comment by Gcenx** [comment]
> Just had the time to test it again. The culprit I found at last, is the locale setting. My macOS is set to display in Chinese, and I have to `export LANG=zh_CN.UTF-8` to make it to work, finally. No more complaint of `status 87`. The wrapper seems to interpreting the host locale in some erroneous manner, so I have to set it manually like this.

WineskinLauncher doesn’t do any locale detection that’s all handled by wine so if it’s wrong that’s on wine.

For winetricks Wineskinlauncher sets the following;
- `PATH`
- `WINEPREFIX`
- `WINETRICKS_FALLBACK_LIBRARY_PATH`
- Whatever env the user has set in the UI

> Anyway, I feel that the winetrick should not be interrupted by such locale settings. Although from my discovery this could largely be a bug on the `vcredist_x86.exe` side, some way to circumvent this bug should be devised.

The problem is due to wine not correctly detecting your locale, to “circumvent this bug” would mean winetricks would need to have a fallback locale that’s always set when one isn’t already set in the environment.

**Comment by austin987** [comment]
@hsghost thanks for the info.

What is your LANG normally set to?

There are a few examples of this currently in winetricks (i.e., dotnet40/lhp_demo).

It may not be fixable, but winetricks could at least issue a warning, if I know what locales are broken.
