### ISSUE TITLE
having problems installing zenity

### ISSUE THREAD

**Issue by LittleSammy** [Winetricks/winetricks#1929]
I'm using macOS 10.14.6, and I'm trying to install both atk and gtk+3 dependencies, but I keep getting this error
>==> meson --prefix=/usr/local/Cellar/atk/2.38.0 --libdir=/usr/local/Cellar/atk/2
Last 15 lines from /Users/sam/Library/Logs/Homebrew/atk/01.meson:
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -fvisibility=hidden: YES 
Checking for function "bind_textdomain_codeset" : NO 
Found pkg-config: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.72.3
Run-time dependency gobject-2.0 found: YES 2.72.3
Configuring config.h using configuration
Configuring atkversion.h using configuration
Found pkg-config: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config (0.29.2)
Program glib-genmarshal found: NO

>../atk/meson.build:90:0: ERROR: Program 'glib-genmarshal' not found or not executable

>A full log can be found at /private/tmp/atk-20220725-36261-1fjfabt/atk-2.38.0/build/meson-logs/meson-log.txt

>Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by austin987** [comment]
While I'm sympathetic that you have a problem (and that Homebrew told you not to report it there), this definitely isn't a winetricks problem, nor am in any position to help.

I'd suggest seeing what package provides 'glib-genmarshal' and try installing that, or reach out to homebrew forums/chat/user support.
