### ISSUE TITLE
Office 2013 pro installation broken

### ISSUE THREAD

**Issue by alex9434** [Winetricks/winetricks#1940]
Unfortunately the office 2013 installation seems to be broken. It stops with the error message:
```
------------------------------------------------------
warning: msls31 install completed, but installed file /home/alex/.local/share/wineprefixes/office2013/dosdevices/c:/windows/syswow64/msls31.dll not found
------------------------------------------------------
```
Installation in a 32bit environment on Ubuntu 22.04 with wine-stable. The 32bit system does not have a \windows\syswow64 directory. The file msls31.dll is instead in the directory:
`\windows\system32`

**Comment by austin987** [comment]
winetricks version? Is your default ~/.wine prefix a 64-bit prefix?

**Comment by alex9434** [comment]
```
$ winetricks --version
20220411-next - sha256sum: 9a5752b3d6682aef719e3a3cf1f7f400f870426577a4ebefff073b76fe82db30
```
```
uname --all
Linux inspiron 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
wine --version
wine-6.0.3 (Ubuntu 6.0.3~repack-1)
```
Default wine prefix is 64bit but I created a 32bit prefix with Winetricks for this installation

**Comment by austin987** [comment]
This is the same root issue as #1970 (even though it's a different verb they're using).

If you run it from the command line instead, it should work.
