### ISSUE TITLE
mdac27 source

### ISSUE THREAD

**Issue by jonasgit** [Winetricks/winetricks#1944]
verb mdac27 downloads from https://web.archive.org/web/20060718123742/http://ftp.gunadarma.ac.id....

Maybe the mirror from Microsoft would be better?
https://web.archive.org/web/20070313224246/https://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa0d76/mdac_typ.exe
(This is the archived from winetricks mentioned original URL).

**Comment by austin987** [comment]
In the end, it's

**Comment by austin987** [comment]
In the end, it's downloading from archive.org, and the checksum matches. It's a cosmetic difference.

That said, if you feel strongly, feel free to send a PR and I'll merge it, but I don't think it's worth the effort.
