### ISSUE TITLE
suppress: warning: You are using a 64-bit WINEPREFIX. 

### ISSUE THREAD

**Issue by fastrizwaan** [Winetricks/winetricks#1949]
Hi, 
Could we have an option to `--ignore-win64` or `--wine64-prefix` or something to stop the warning. Esp. when the user knows and wants to use  win64 prefix. Thanks!

![image](https://user-images.githubusercontent.com/1161682/185271036-b9d660d9-89be-456d-bbcc-55b499b3c409.png)

**Comment by austin987** [comment]
See #1730; this will now only show once per prefix/session. If you want to ignore, you can touch a file in the appropriate place.

I don't plan to add a command line warning, as this really only affects GUI users (CLI users will get more output in terminal, no popup). If you feel strongly about it, send a PR and I'll review it.

**Comment by Torrekie** [comment]
kinda want this feature, I'm using [Wine Crossover](https://github.com/Gcenx/homebrew-wine) on Apple Silicon which actually supporting win32 programs since it implemented x86 runtime on x64 (`wine32on64`)
