### ISSUE TITLE
How to specify/change path to wine executable when using winetricks

### ISSUE THREAD

**Issue by leylaso** [Winetricks/winetricks#1953]
I have both my distributions package of wine and the wine-stable branch installed on my system. I cannot figure out how to get winetricks to use the wine-stable branch. This feels like a documentation issue, but I am likely overlooking something simple.

**Comment by leylaso** [comment]
Clarification - I am aware I can change the order of my path variable, I am looking for info on whether there is a way to directly specifiy to winetricks which wine executable it should use

**Comment by gverm** [comment]
@leylaso Use the 'WINE' and 'WINESERVER' env vars to specify the path to the desired wine and wineserver executables.
