### ISSUE TITLE
msls31 is 404

### ISSUE THREAD

**Issue by nolocus** [Winetricks/winetricks#1954]
09/03 21:52:13 [NOTICE] Downloading 1 item(s)
[#b27798 0B/0B CN:1 DL:0B]                                                                                   
09/03 21:52:58 [ERROR] CUID#7 - Download aborted. URI=https://web.archive.org/web/2000/https://web.archive.org/web/20160710055851if_/http://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe

cant download this file, the source is 404

**Comment by austin987** [comment]
Can you please retry?  It seems archive.org was having some downtime, looks fine now?
