### ISSUE TITLE
Restore original windows-version after vcrun2019 installation.

### ISSUE THREAD

**Issue by roidal** [Winetricks/winetricks#1956]
When running

`winetricks -q vcrun2019`

the configured windows-version ist changed to winxp64 during the installation, and later to win7 instead of the previous configured value.
This breaks newer games, which requires >win7.

**Comment by austin987** [comment]
Your winetricks is outdated, this was fixed long ago by 9e5dba2f683427543f78c2789fe535021fdae89d

**Comment by austin987** [comment]
I thought this was already handled, but apparently not..Yes, it will currently reset it to win7.

Fixing it shouldn't be too hard now that winecfg can report the current version (`winecfg -v`).
