### ISSUE TITLE
Update vcrun2015 to install VC++ 2015 Update 3 ?

### ISSUE THREAD

**Issue by Lantizia** [Winetricks/winetricks#1957]
I'm not sure if this should be a different verb or if the existing vcrun2015 verb should be updated... but I'm finding some applications needs the 'Update 3' version of Visual C++ Runtime 2015 (version 14) in order to run... and vcrun2015 presently doesn't satisfy that.

I've made a pull request... https://github.com/Winetricks/winetricks/pull/1958

I'm not sure if it'll be as simple as the changes I've made in that above... but it at least has the correct links and SHA256 sums in it.  The date in the pull request of "2022/09/16" is simply today's date (as I wasn't sure why a date was being put into the comment on that line anyway... presumably to just confirm that on that arbitrary date... the SHA256 hash was witnessed to be as stated?).

**Comment by austin987** [comment]
> I'm not sure if this should be a different verb or if the existing vcrun2015 verb should be updated

I agree that updating the current verb is the right solution here.

> ... but I'm finding some applications needs the 'Update 3' version of Visual C++ Runtime 2015 (version 14) in order to run... and vcrun2015 presently doesn't satisfy that.

Out of curiosity, what applications are those?
 
> I've made a pull request... #1958

Great!

> I'm not sure if it'll be as simple as the changes I've made in that above... but it at least has the correct links and SHA256 sums in it.

Yeah, that should be all that's required (assuming the update doesn't install extra dlls/need other workarounds.

Did you test that it works for the applications that needed it?

> The date in the pull request of "2022/09/16" is simply today's date (as I wasn't sure why a date was being put into the comment on that line anyway... presumably to just confirm that on that arbitrary date... the SHA256 hash was witnessed to be as stated?).

Precisely. Ideally the date would match when the release was made, if known, but really, it's to keep a record of known hashes. I.e., sometimes when looking at bugs it helps to know that the hash matches an old version of something, at a glance.

**Comment by Lantizia** [comment]
It's the "Tensor.NET Enterprise" client from [tensor.co.uk](https://tensor.co.uk)... unfortunately it is nothing that is publicly available, and I only know of it because I've been required to use it at my place of work.  

The old version used to be happy with "winetricks -q secur32 vcrun2005 vcrun2010 dotnet40" on a much older version of Wine.  

But the newer version (that I'm still battling with) seems to want "winetricks -q vcrun2010 vcrun2015 dotnet472" (at the very least, maybe more).  Still haven't got it completely working, but I have got it past the point where it is satisfied that the "VC++ 2015 Update 3" system requirement is satisfied (once the updated verb is used, but not using the vcrun2015 verb as it stands today).

**Comment by austin987** [comment]
Thanks for the PR/extra info!
