### ISSUE TITLE
Winetricks is refusing to create 32bit prefix

### ISSUE THREAD

**Issue by jelabarre59** [Winetricks/winetricks#1960]
I have started winetricks with both the winetricks switches (arch=32 prefix=ftw7) as well as prefixing the command with the settings (winearch=win32 WINEPREFIX="/home/jelabarre/.local/share/wineprefixes/ftw7" winetricks), yet when it starts up it still insists I am using a 64-bit prefix.

Even tried a regular install calling     winearch=win32 WINEPREFIX="/home/jelabarre/.local/share/wineprefixes/ftw7" wine32 ftw7/SETUP.EXE, then after the install completed I ran the same winearch/WINEPREFIX command for wineprefix.  It still complains that I am in a 64bit prefix.

this is running the latest wineprefix from this site (20220411-next)

**Comment by austin987** [comment]
A few things:

* could you please post the output of `ls -al /home/jelabarre/.local/share/wineprefixes/ftw7`
* if using the `WINEARCH` environment variable (i.e., if you're putting it _before_ `winetricks`, it needs to be UPPER CASE (i.e., `WINEARCH=win32 winetricks ...` not `winearch=win32 winetricks ...`).

Finally, please post the _full_  terminal command and output you're getting.
