### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by Talhazzers** [Winetricks/winetricks#1973]
When I enter a few commands to fix Wine's bad font, I get the errors in the screenshot. Can someone help me please?

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/57840480/198588332-c3018a9a-8e91-46e0-afe7-1a9ae0d90489.png">

**Comment by austin987** [comment]
That's a problem with your wine installation, not winetricks. https://github.com/Gcenx/homebrew-wine may be helpful, but this isn't a winetricks issue.

**Comment by Talhazzers** [comment]
Unable to operate with wine from command line with macOS Ventura & Macbook M2. It can only be processed with wine64. This error occurs when winetricks tries to use the wine command which is 32bit.

**Comment by daslicht** [comment]
> That's a problem with your wine installation, not winetricks. https://github.com/Gcenx/homebrew-wine may be helpful, but this isn't a winetricks issue.

is there somewhere a documentaion how to use homebrew-wine? the wine command has no useful doc ~ please
