### ISSUE TITLE
Winetricks Discover Version 20220411-1 Won't Open

### ISSUE THREAD

**Issue by serenova** [Winetricks/winetricks#1982]
I'm using Discover to install Winetricks

It _seems_ to install just fine. However when I then go to launch Winetricks, nothing. No window, no interface, nothing. The logo pops up in my task manager panel for a split second and then... just.... nothing.

I've installed Wine itself per the instructions here: https://wiki.winehq.org/Ubuntu - and I've installed a couple of windows programs and run them just fine. So I know _Wine_ itself is working.

But I simply cannot get Winetricks to open. I will try to install it manually and will report back on whether that solves this issue or not.

System Info
> Operating System: Kubuntu 22.10
> KDE Plasma Version: 5.25.5
> KDE Frameworks Version: 5.98.0
> Qt Version: 5.15.6
> Kernel Version: 5.19.0-23-generic (64-bit)
> Graphics Platform: X11
> Processors: 16 × Intel® Core™ i9-9880H CPU @ 2.30GHz
> Memory: 31.2 GiB of RAM
> Graphics Processor: NVIDIA GeForce RTX 2080/PCIe/SSE2

**Comment by serenova** [comment]
Okay, in all honesty, I'm not a programmer, and still fairly new to Linux.

I tried to follow the manual build instructions for Ubuntu here: https://github.com/Winetricks/winetricks 

But I got nowhere

Making the updating script is where I got stuck because I've never done that before and have no idea HOW to do it, and the instructions aren't something I can follow with my no-knowledge skill set.

Is there any particular _reason_ why the Discover version isn't being updated for the Debian/Ubuntu releases?

**Comment by austin987** [comment]
I have no idea what 'Discover' is, so you'd have to ask them.

As for your issue, do you have kdialog installed? If not, try installing it first.

If it is installed, try opening a terminal and simply run 'winetricks'. That should pop up a kdialog menu for you. If not, please attach the output you get.

**Comment by serenova** [comment]
Discover is the built in application explorer for Kubutnu. It's literally where I can find everything from Gimp to plasma desktop widgets. It's the built in software repository. 

I haven't heard of kdialog. It popped up when I searched for it in my programs, howevern when I click "Run kdialog" litearlly nothing happens. According to Discover it's what allows me to view dialog boxes from shell scripts? It says it's installed.

![image](https://user-images.githubusercontent.com/96950336/201552194-9524e944-2b57-417a-81ea-c2b096a4c239.png)
This is my Discover window. When I click the indicated "Launch" button, the Winetricks logo pops up in my Task Manager and then nothing, it just disappears. I literally reinstalled it via discovery _just_ to take that screenshot.

I downloaded the standalone script for Winetricks and can run it that way, so that's something at least, but it's not "installed" on my system.

At least I've found a workaround though.

**Comment by austin987** [comment]
I'm not involved with KDE/Discover. If their version is buggy, you need to report it to them.

If you have winetricks downloaded, you can install it by:
$ chmod +x winetricks
$ sudo mv winetricks /usr/local/bin/
(or somewhere else in your $PATH)

**Comment by sonic2kk** [comment]
> Discover is the built in application explorer for Kubutnu. It's literally where I can find everything from Gimp to plasma desktop widgets. It's the built in software repository

Discover is a front-end for installing packages across distros. By default, it'll install packages using your distributions repositories. It is **not** its own repository, it is just a front-end for installing packages, in this case a front-end for apt. On Arch, it's a front-end for Pacman.

Discover also supports installing Flatpaks, generally on distributions (e.g. SteamOS) this is defaulted to Flathub.

In this case, given your screenshot and who it was distributed by, I think this is from the Ubuntu / Kubuntu repos.

When installed from Discover, does Winetricks work from the command line? If not, does it output anything?

If Winetricks does not work from Discover, the chances are it won't work with a "manual" install, but if you install Winetricks with apt does it still fail to open? 

In my experience it is not common to launch Winetricks using a button, generally it is launched from the command line (and pointed at a specific Wineprefix). Perhaps however Discover is trying to launch it is just invalid? So trying the command line might work or give more hints on why it is not working.
