### ISSUE TITLE
Reason for `Executing mkdir -p /home/user`

### ISSUE THREAD

**Issue by Souravgoswami** [Winetricks/winetricks#1989]
Every time I run winetricks, I get the annoying message saying:

```
$ winetricks 
Executing mkdir -p /home/sourav
  ```

My question is what's the point of creating home directory? Not sure what happens for users without home directory, but in general, this `mkdir -p /home/sourav`  looks so silly.

**Comment by austin987** [comment]
Fixed by acef23e09d291453e740584e30d7c2b46dad8a92
