### ISSUE TITLE
how to find what package to install from "missing dll"

### ISSUE THREAD

**Issue by alien999999999** [Winetricks/winetricks#1993]
like, a game complains that X3Daudio1_7.dll is missing, but there was no easy way to find it, eventually i found that xact seemed to have this...
It would be great to have like a `find x3daudio` command that would says `xact`.

**Comment by austin987** [comment]
It's an interesting request, but I don't think this would scale very well/it would be a pain to maintain. Thinks like native  .Net install a lot of files, any of which a user might search for. IIRC some vcrun verbs install _different_ files based on what windows version is emulated. There are likely other edge cases that would need to be considered.

FWIW, `winetricks list-all` or `winetricks dlls list` will list the dll names for some verbs. It's not feasible to list all dlls/components, but feel free to send a patch updating those descriptions.

**Comment by alien999999999** [comment]
IC, well, i was kinda hoping this would automagically detect it or something (maybe when doing unit testing or something) and it generates a list for filenames (or dll names or something) automagically... I agree that manual maintenance is not doable.
