### ISSUE TITLE
weird c000007b issue for some dlls

### ISSUE THREAD

**Issue by alien999999999** [Winetricks/winetricks#1994]
So, this 64bit game complains about `x3daudio1_7.dll` ; I eventually find out i need **xact**, so i install it, and checking, it is actually in a `SysWOW64` directory. but the same says "**not found**"; when i cp these files into the current directory, i get error `c000007b` ... so it's not "**not found**" anymore...

I'm missing something stupid here...

**Comment by austin987** [comment]
You (maybe) broke the prefix, xact installs 32-bit dlls. They won't work for a 64-bit game.

You can try 'winetricks xact_64', but it may or may not work.

**Comment by alien999999999** [comment]
So, I found out that 64bit dlls are in system32 ; and 32bit libs are in syswow64 ??? this kinda blew my mind... windows is so stupid...
Then i did find a xact_x64 and installing that did the trick... (and removing any local copies i tried to put in the dir)

**Comment by Chiitoo** [comment]
Indeed, I'm not sure about how official it is, but I believe the WOW64 means 'Windows on Windows 64', or in other words, 'Windows 32-bit on Windows 64-bit'.

Not sure if anyone has ever, or will ever figure that out the first time they see it.  :]
