### ISSUE TITLE
winetricks xact not overriding xactengineX_X.dll

### ISSUE THREAD

**Issue by Leebre** [Winetricks/winetricks#1996]
When using winetricks to install xact, it installs the files, but doesn't seem to add the overrides for xactengineX_X. However, the overrides work if done 'manually' in winecfg.

I am using winetricks 20220411-1 from the Arch repo.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/c7949d3b9fbd10a0e62fa50e77b1ca4fe0b6f5e5
https://github.com/Winetricks/winetricks/commit/4d2619433265c4b592e3afe99879beaa7ba7be17
