### ISSUE TITLE
[Feature] Option to select different wine prefix from GUI

### ISSUE THREAD

**Issue by peter099** [Winetricks/winetricks#1998]
There is only option to select the default wine prefix when you start winetricks gui. A option to select a different wine prefix will be useful.

**Comment by sonic2kk** [comment]
I think you can do this from the command line very easily with `WINEPREFIX="/path/to/prefix" winetricks"

**Comment by peter099** [comment]
Yes, i know i know i can select the prefix from the command line, but i mean selecting the prefix from winetricks gui, which works for prefixes created using winetricks, but not for prefixes created without using winetricks. Anyway, i don't think this is a big deal.
