### ISSUE TITLE
how about automatically creating user Temp directory?

### ISSUE THREAD

**Issue by tmvkrpxl0** [Winetricks/winetricks#2000]
I tried to install dotnet35 today, but it repeatedly failed as `C:\users\tmvkrpxl0/Temp` directory did not exist. I was able to fix it by creating that directory myself, but I think it would be nice if winetricks created it itself just in case.

For more detail on how it initially failed. it firstly set my wineprefix to windows xp environment itself. Setting it to other environment and running `dotnetfx35.exe` showed different setup process, and just failed after few seconds. I'm not sure if other environments would use the same temp directory.

**Comment by austin987** [comment]
That directory is made by Wine itself. Something had to have removed it, and I don't think it was winetricks (I don't see anywhere in the code that would at least). Nothing in winetricks uses that directory (it uses C:\windows\temp instead, which *does* automatically get created if it's not there).

Do you have a clear set of instructions that can reproduce the problem?

**Comment by tmvkrpxl0** [comment]
I don't think so, sorry. It just happened randomly.

**Comment by austin987** [comment]
Okay. If you can find a way to consistently reproduce it, please reopen with instructions.
