### ISSUE TITLE
Incorrect language for graphical prompt window during installation.

### ISSUE THREAD

**Issue by rokejulianlockhart** [Winetricks/winetricks#2003]
I followed https://wiki.winehq.org/Winetricks. A window appeared with Ja and Nein as possible options. The rest of the text of it was also foreign.

**Comment by austin987** [comment]
What is `$LANG` set to on your system? What language did you expect to see (English, I'm guessing)?

**Comment by rokejulianlockhart** [comment]
Yeah, English.
```
PS $HOME> $ENV:LANG                                 
en_GB.UTF-8
```

**Comment by austin987** [comment]
Are you running this under powershell?

Could I get a log with `winetricks -v`?

**Comment by rokejulianlockhart** [comment]
@austin987, yes, I ran all of this via `pwsh-preview`, because it is configured as my login shell by `chsh -s /usr/bin/pwsh-preview`.

`winetricks -v >> $HOME/winetrickslog.log` produced:
```
PS $HOME> cat winetrickslog.log                                     
Executing mkdir -p /home/BEEDELLROKEJULIANLOCKHART
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411 - sha256sum: e96c664316387b3e000ec13f0b9a71758cc47cf49a0143af2cb1c3ba1250239a with wine-7.22 (Staging) and WINEARCH=win64
winetricks GUI enabled, using kdialog 22.12.0
```

**Comment by austin987** [comment]
I'm not sure how powershell behaves in this regard, but please capture STDERR, something like:
$ winetricks -v > winetrickslog.txt 2>&1

Could I also get a screenshot of the dialog/error you're seeing? Looking at the source, I'm not sure where this could've come from..

**Comment by rokejulianlockhart** [comment]
@austin987, I'd have to reinstall winetricks to provide a screenshot of the window again. Do you know how I might go about that?

This occurred when installing from the script rather than Fedora's RPM package, although both are currently installed.

**Comment by austin987** [comment]
> @austin987, I'd have to reinstall winetricks to provide a screenshot of the window again. Do you know how I might go about that?

I'm not 100% sure, since the full text wasn't included, but try moving `~/.cache/winetricks/track_usage` out of the way / removing it. If that doesn't work, move/remove ~/.cache/winetricks and retry.

**Comment by rokejulianlockhart** [comment]
I'm not gonna try to reproduce this issue, and I'm using an entirely new system anyway. If ever I install `winetricks` again and the same occurs, I'll reopen the issue and provide a screenshot and `script` `.log`s.
