### ISSUE TITLE
can you please add d8vk? 

### ISSUE THREAD

**Issue by stefson** [Winetricks/winetricks#2004]
hello everyone, 

d8vk is a fork of dxvk, with a focus on directx8 and directx9. 

It offers `d3d8.dll` and `d3d9.dll`, and is certainly very helpfull for anyone stuck with low performance of d3d8 on modern hardware drivers. 

this is the homepage: https://github.com/AlpyneDreams/d8vk

and this is the release page: https://github.com/AlpyneDreams/d8vk/releases

current release is `0.10` 

I did a quick copy and paste of the dxvk-2.0 code, only thing I don't understand is the `helper_dxvk` line. And I don't know the real name of the person who publishes this. 

```

w_metadata d8vk0010 dlls \
    title="Vulkan-based D3D8/D3D9 implementation for Linux / Wine (0.10)" \
    publisher=" AlpyneDreams " \
    year="2022" \
    media="download" \
    file1="d8vk-v0.10.tar.gz" \
    installed_file1="${W_SYSTEM32_DLLS_WIN}/d3d8.dll" \
    installed_file2="${W_SYSTEM32_DLLS_WIN}/d3d9.dll" 

load_d8vk0010()
{
    # https://github.com/AlpyneDreams/d8vk/
    w_download "https://github.com/AlpyneDreams/d8vk/releases/download/d8vk-v0.10/d8vk-v0.10.tar.gz" 43e3d1051b31d91541fba1a6c59d0991208869203e66779bfab8a861eb545eb1
    helper_dxvk "${file1}" "7.1" "1.3.204" "dxgi,d3d9,d3d10core,d3d11"
}

```

**Comment by austin987** [comment]
helper_dxvk() is used to validate the needed Wine/Vulkan API versions. It looks like d8vk needs similar? https://github.com/doitsujin/dxvk/wiki/Driver-support

I'd suggest looking at extending helper_dxvk() to also allow overriding d3d8 for d8vk.

FYI @bobwya

**Comment by sonic2kk** [comment]
I don't think anyone was looking at this yet? If not, I poked around and got an implementation working and hope to get a PR out soon for review :-)
