### ISSUE TITLE
Please add support for proot 

### ISSUE THREAD

**Issue by Saikatsaha1996** [Winetricks/winetricks#2010]
Please add support for proot..
When i am trying to use in proot with box64 & box86 i am getting error `wine` comment not found..

And the problem is i am on `proot android`.. in android directly wine cmd will not work.. need to add box64 or box86 than wine will work... 

So i was edited in somthing in winetricks just was added `box64 or box86` than `wine`
Now some problem will solved.. but i don't have skills for edit bash script ..

So if you just add support for box86 & box64 with wine so it can be very helpful for us..

**Comment by austin987** [comment]
I don't see think this is in the scope of winetricks.
