### ISSUE TITLE
winetricks xna31 wrong link and more

### ISSUE THREAD

**Issue by TheK0tYaRa** [Winetricks/winetricks#2013]
the link it tries is [https://web.archive.org/web/2000/https://web.archive.org/web/20210329003118/http://download.microsoft.com/download/c/6/e/c6e88215-0178-4c6c-b5f3-158ff77b1f38/NetFx20SP2_x86.exe](url)
the actual one is [https://web.archive.org/web/20210329003118/http://download.microsoft.com/download/c/6/e/c6e88215-0178-4c6c-b5f3-158ff77b1f38/NetFx20SP2_x86.exe](url)

**Comment by TheK0tYaRa** [comment]
Literally can't play magicka xD

**Comment by TheK0tYaRa** [comment]
Ok, there is not only the link broken.
winetricks 20220411
wine 8.0
WINEARCH win32

broken dlls include xna31 dotnet2sp2 dotnet30sp1 and probably their dependents

**Comment by austin987** [comment]
Please try with  latest upsteam (winetricks --self-update).

**Comment by TheK0tYaRa** [comment]
It's the latest release though

**Comment by TheK0tYaRa** [comment]
dotnet30sp1 fails to install returning 1603 and doesn't undo it's install after failing it, as a result xna31 installs and doesn't work.

**Comment by TheK0tYaRa** [comment]
also `warning: xna31 install completed, but installed file /mnt/FILEDUMP/gamehub/custom/_gamehub/compat/wine_win32/dosdevices/c:/windows/assembly/GAC_32/Microsoft.Xna.Framework.Game/3.1.0.0__6d5c3888ef60e27d/Microsoft.Xna.Framework.Game.dll not found`

**Comment by TheK0tYaRa** [comment]
The exact command for the results i'm getting so far is:
`WINEPREFIX="/mnt/SHORTENED/wine_win32" WINEARCH=win32 winetricks dlls dotnet35sp1 xna31`
exact current versions are the following:
wine 8.0
winetricks 20220411-next - sha256sum: 6dac3c9c3a037ac4be41ac5ba631c503510c9ddf54a26c8e2a022a37cf910cbd

**Comment by austin987** [comment]
Really it's a bug in the xna installer; if it bails if a newer .Net is installed.

I can add a conflict for it, is that what you're looking for? I'm curious why you're installing dotnet35sp1 before xna31 anyway?

**Comment by TheK0tYaRa** [comment]
dotnet35sp1 seemed to not install with dotnet20sp2 installed, just that.

**Comment by fastrizwaan** [comment]
Hi, kindly make a new release with tag. as wine 8.0 can't install dotnet20 with old release 20220411. 

With latest git version, it properly installs dotnet20 needed for xna31.
