### ISSUE TITLE
I have packaged winetricks-20230212-1 for debian x86_64

### ISSUE THREAD

**Issue by xevilstar** [Winetricks/winetricks#2022]
Dear Maintainers,

I have packaged the latest winetricks for debian (already posted to mentors.debian) and I am trying to send it to experimental

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031232

please sponsor me 

Thanks

**Comment by austin987** [comment]
I'm not a Debian maintainer, I can't help you there.

Note that there already is Debian package/maintainer, it just needs to be updated:
https://packages.debian.org/source/sid/winetricks
