### ISSUE TITLE
Release 20230212 fails to verify

### ISSUE THREAD

**Issue by jre-wine** [Winetricks/winetricks#2024]
Hi Austin,

thanks for the latest release! Perfectly timed :)

Unfortunately the [tar.gz](https://github.com/Winetricks/winetricks/archive/refs/tags/20230212.tar.gz) from the [release page](https://github.com/Winetricks/winetricks/releases/tag/20230212) fails to verify (bad signature).

However a tar.gz created with the same "git archive" command [1] as you do in release.sh successfully verifies. I then checked both tarballs with diffoscope and their content is identical. So I assume github changed something in their tarball creation like compression parameters. (In the past the tarball created with git archive was bit-by-bit identical to the one provided by github, so signing worked.)

Any idea how to fix that? Or did I download the wrong file?

I'll also look into this further. No worries, if we don't get this solved I still may push the unsigned tarball to Debian.

Greets!
jre

[1] git archive --prefix=winetricks-20230212/ -o 20230212.tar.gz 20230212

**Comment by xevilstar** [comment]
be fast before it's gone ...

https://mentors.debian.net/debian/pool/contrib/w/winetricks/winetricks_20230212-1.dsc

**Comment by austin987** [comment]
> Any idea how to fix that? Or did I download the wrong file?

Sorry, unfortunately I don't. I used my usual upload process (`./src/release.sh`).

> I'll also look into this further. No worries, if we don't get this solved I still may push the unsigned tarball to Debian.

Please let me know. I'm more than happy to help things that affect downstream/packaging (particularly Debian ;) ).

**Comment by jre-wine** [comment]
Turns out git switched its default to an internal gzip implementation and github (which seems to generate the tarballs on demand without storing them permanently) reverted this for now to keep the existing behaviour.

Please try this git archive command which also uses the external gzip:
```
git -c tar.tar.gz.command='gzip -cn' \
    archive --format=tar.gz --prefix="winetricks-20230212/" \
    -o "/tmp/20230212.tar.gz" 20230212
```

This should give a bit-by-bit identical tarball to the [tar.gz](https://github.com/Winetricks/winetricks/archive/refs/tags/20230212.tar.gz) from the [release page](https://github.com/Winetricks/winetricks/releases/tag/20230212).

Then sign it:
`gpg --armor --default-key 0x267BCC1F053F0749 --detach-sign /tmp/20230212.tar.gz
`

Then download the  [tar.gz](https://github.com/Winetricks/winetricks/archive/refs/tags/20230212.tar.gz) from the [release page](https://github.com/Winetricks/winetricks/releases/tag/20230212) and test if you can verify it with this local signature:
`gpg --verify /tmp/20230212.tar.gz.asc /path/to/githubs/winetricks-20230212.tar.gz
`

Then replace the 20230212.tar.gz.asc on github with this new signature.

I'll follow up with a pull request for release.sh (and a new release in Debian :))

**Comment by austin987** [comment]
Thanks @jre-wine. Sorry for the delay. I've regenerated and reuploaded the signature.
