### ISSUE TITLE
support for clean x86_64 setup on winetricks

### ISSUE THREAD

**Issue by neofeo** [Winetricks/winetricks#2032]
Hi! so, it seems to me that when I ask winetricks to install a lib and I am on a x86_64 prefix on an x86_64 system, it should be possible to force winetricks to only download x86_64 stuff. I don't wont the x86 libs (for some reasons).
like for example, gdiplus, there are tons of x86_64 releases. I cant install those. it default to the old gdiplus x86.

there is any workaround or todo regarding this topic?

**Comment by austin987** [comment]
> Hi! so, it seems to me that when I ask winetricks to install a lib and I am on a x86_64 prefix on an x86_64 system, it should be possible to force winetricks to only download x86_64 stuff. I don't wont the x86 libs (for some reasons).

What are those reasons?

> like for example, gdiplus, there are tons of x86_64 releases. I cant install those. it default to the old gdiplus x86.

A lot of verbs don't have support for 64-bit at all. Either because there isn't one publicly available, or more generally, because no one has put the work in to make one available.
 
> there is any workaround or todo regarding this topic?

Not currently, no.

**Comment by neofeo** [comment]
So if I use photoshop and it's  x86_64 then I can't  install gdiplus x86_64 (available). Just an example. But I have other reasons, closing

**Comment by austin987** [comment]
gdiplus does install a 64-bit dll..
