### ISSUE TITLE
unable to install dll's like GDI plus and xmlite on a 32bit wineprefix 

### ISSUE THREAD

**Issue by izerotwo** [Winetricks/winetricks#2034]
whenever i try to install them on a 32 bit prefix i get an error stating installation was completed  but the file was found in syswow64 of all places . "xmllite install completed, but installed file /home/zerotwo/.local/share/wineprefixes/Musicbee/dosdevices/c:/windows/syswow64/xmllite.dll not found"

Executing w_do_call xmllite
Executing load_xmllite 
grep: warning: stray \ before /
Executing cabextract -q -d /home/zerotwo/.local/share/wineprefixes/Musicbee/dosdevices/c:/windows/temp/_Musicbee -L -F x86_microsoft-windows-servicingstack_31bf3856ad364e35_6.1.7601.17514_none_0b66cb34258c936f/xmllite.dll /home/zerotwo/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe
Executing cp -f /home/zerotwo/.local/share/wineprefixes/Musicbee/dosdevices/c:/windows/temp/_Musicbee/x86_microsoft-windows-servicingstack_31bf3856ad364e35_6.1.7601.17514_none_0b66cb34258c936f/xmllite.dll /home/zerotwo/.local/share/wineprefixes/Musicbee/dosdevices/c:/windows/system32/xmllite.dll
Using native,builtin override for following DLLs: xmllite
Executing wine C:\windows\regedit.exe C:\windows\Temp\_Musicbee\override-dll.reg
------------------------------------------------------
warning: xmllite install completed, but installed file /home/zerotwo/.local/share/wineprefixes/Musicbee/dosdevices/c:/windows/syswow64/xmllite.dll not found
------------------------------------------------------
this is the full output it gave out, due to an earlier issue of cabextract 1.10 not functioning properly i have downgraded that to 1.9.7 but other than that everything is stock from opensuse's repos.

i am running on opensuse tumbleweed 
wine version 8.2 stable
winetricks version 20230212

(this is my first issue reporting so i still dont know all the best practices sorry in advance if i missed something)

**Comment by austin987** [comment]
What does `cabextract --version` say?

**Comment by izerotwo** [comment]
zerotwo@localhost:~> cabextract --version
cabextract version 1.9
On a different note -
after trying  musicbee which was the application which i tried to install gdiplus, on the 32bit prefix even with the error message it seems to be working. So it seems to me that  a 32bit prefix winetricks  is seen as  a 64bit prefix.

**Comment by austin987** [comment]
Your original comment mentioned cabextract 1.9.7 (which isn't a a version that exists upstream). The issue you're experiencing looks like the same issue you saw in (upstream) cabextract 1.10.

To me, this looks like a an OpenSUSE/cabextract packaging bug. To my knowledge, upstream 1.9.1 and 1.11 work. 1.10 is broken. But if a distribution is applying patches themselves, this may not apply.

**Comment by izerotwo** [comment]
yes originally my system did come with cabextract 1.10 where the issue it gave out is was different, but after going back to cabextract 1.9.7 (i had installed it from fedoras packages instead of opensuse's packages) the DLLs mentioned did install but it did give out a a different error, which i have  copied above.
 The thing is that it gives out an error mentioning syswow64 tho the prefix i installed the DLLs in question were a 32bit prefix and hence should not have syswow64 anyway. 

But yes it could very well be a distro package related issue, but i doubt if its still related to cabextract as from what i have seen in other reports cabextract would not allow the installation of the package at all, but here the installation does take place and the DLLs in question  can even be found in said prefix folders. 

Also to note is that after the install of the DLLs,even with the errors the apps dependant on them seem to be working.

**Comment by austin987** [comment]
> yes originally my system did come with cabextract 1.10 where the issue it gave out is was different, but after going back to cabextract 1.9.7 (i had installed it from fedoras packages instead of opensuse's packages) the DLLs mentioned did install but it did give out a a different error, which i have copied above. The thing is that it gives out an error mentioning syswow64 tho the prefix i installed the DLLs in question were a 32bit prefix and hence should not have syswow64 anyway.

Are you running winetricks from the GUI? Sounds like this may be #1970.

> But yes it could very well be a distro package related issue, but i doubt if its still related to cabextract as from what i have seen in other reports cabextract would not allow the installation of the package at all, but here the installation does take place and the DLLs in question can even be found in said prefix folders.
> 
> Also to note is that after the install of the DLLs,even with the errors the apps dependant on them seem to be working.

So, things are working? I'm not clear what the problem you're currently facing is, as the situation seems to have changed a few times.

**Comment by izerotwo** [comment]
Yes I was running wine tricks on gui. 
Yes atleast right now after reverting to cabextract 1.9.7 the app that required the DLLs did work fine, my situation has changed as earlier when I made the bug report, i was yet to get the app working as i was in the process of trying to get rid of the error post installation of the DLLs.

 Currently the app does work but trying to install something like gdi plus or xmlite on a 32 bit prefix gives out an error which should be only applicable to a 64bit prefix(though after checking the prefix in question the prefix was infact a 32 bit prefix and lacked the syswow64 folder entirely) .

Yes it appears the error faced by #1970  seems to be identical. But it's also to be noted the apps that rely on the dependency do work if installed within the prefix.

**Comment by austin987** [comment]
It's a warning, not an error.

Since things are working, I'm going to close this. For the 32/64bit issue, check #1970 for updates.

**Comment by LoneFenris** [comment]
It may be just a warning, but on my system it does seem to cause winetricks to immediately exit. This makes installing components like directmusic (which is multiple installs) rather annoying as it requires each component to be installed separately and will close after each one. I notice that the 32bit prefix also doesn't keep track of installed components like the 64-bit prefix does.
