### ISSUE TITLE
quartz broken?

### ISSUE THREAD

**Issue by tartoci** [Winetricks/winetricks#2036]
Hi all,
I was trying to install quartz, and I got the following error (quartz.dll is missing)
I got the same error with directshow (amstream.dll is missing)
No error with dirac and directmusic btw

    $ WINEPREFIX="$HOME/.wine32test" WINEARCH=win32 sh winetricks quartz
    Using winetricks 20230212-next - sha256sum: 5d955265d81816ec804ab54107c923da802e69fd4f182a69bded5719c8d5c8a2 with wine-8.2 and WINEARCH=win32
    Executing w_do_call quartz
    Executing load_quartz
    grep: warning: stray \ before /
    Executing cabextract -q -d /home/ben/.wine32test/dosdevices/c:/windows/temp -L -F x86_microsoft-windows-directshow-core_31bf3856ad364e35_6.1.7601.17514_none_a877a1cc4c284497/quartz.dll /home/ben/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe
    /home/ben/.wine32test/dosdevices/c:/windows/temp/x86_microsoft-windows-directshow-core_31bf3856ad364e35_6.1.7601.17514_none_a877a1cc4c284497/quartz.dll: No such file or directory
    ------------------------------------------------------
    warning: Note: command cabextract -q -d /home/ben/.wine32test/dosdevices/c:/windows/temp -L -F x86_microsoft-windows-directshow-core_31bf3856ad364e35_6.1.7601.17514_none_a877a1cc4c284497/quartz.dll /home/ben/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe returned status 1. Aborting.

**Comment by austin987** [comment]
What does `cabextract --version` show?

**Comment by tartoci** [comment]
$ cabextract --version
    cabextract version 1.10

Version 1.11 came out a few days ago to fix a bug introduced in 1.10
I updated to 1.11 and it solved my issue
Thanks!
