### ISSUE TITLE
"warning: Note: command wine winecfg -v win2003 returned status 126. Aborting." when installing IE8 on macOS

### ISSUE THREAD

**Issue by eduardomozart** [Winetricks/winetricks#2041]
Hello,
When attempting to install IE8 on a Wine64 preffix (because macOS didn't support 32-bit preffix anymore), the following error are being thrown:

````
warning: Note: command wine winecfg -v win2003 returned status 126. Aborting.
````

I believe it's happening because ``wine`` didn't work on newer macOS, the following error is thrown on Terminal when attempting to run it directly:

````
zsh: bad CPU type in executable: wine
```
`

Winetricks on macOS should use ``wine64`` instead.

**Comment by austin987** [comment]
Again, please don't open multiple issues for the same thing.
