### ISSUE TITLE
Question: Init without Mono installation in no-GUI environment

### ISSUE THREAD

**Issue by Andrewknackstedt** [Winetricks/winetricks#2050]
I'm working on creating a docker image that bundles wine and some wine apps that I know _can_ work.
I'm struggling at this point: 
When I run `wineboot --init`, it can't find a display (for clear reasons, docker build).
I'd like to disable the display, and _not_ install mono alongside it, since the apps like to fail catastrophically with Mono for whatever reason.

Can someone help me fix my wineboot command or work-around it in the cleanest way possible? I know I can use the good ol' zip up folders and deploy them trick, but that doesn't seem like a great plan. 

Thanks!

**Comment by carlosbet** [comment]
Today I'm working in a similar project. Simply, you should unzip mono in the correct directory where Wine expects to find it. 
This is part of my Dockerfile:

```
FROM i386/alpine:3.17
...

# Wine-Mono
RUN mkdir -p /opt/wine/mono && \
wget "https://dl.winehq.org/wine/wine-mono/7.4.0/wine-mono-7.4.0-x86.tar.xz" -P /opt/wine/mono && \
tar -xf /opt/wine/mono/wine-mono-7.4.0-x86.tar.xz -C /opt/wine/mono && \
rm /opt/wine/mono/wine-mono-7.4.0-x86.tar.xz
```

And works like a charm ;-)

**Comment by Andrewknackstedt** [comment]
Well, I need to use .Net Framework and not Mono, because the app is really unstable with Mono and crashes. I suppose I can just omit running Winetricks or I could prepare a packaged Wine installation fully set up

**Comment by carlosbet** [comment]
I think that **Wine** uses mono by default. In my case, after initialize Wine, I install .NET Framework 3.5 and .NET Framework 4.8 using winetricks and -q option to make unattended installation.
Caution! Not run Wine as root. Change user first.

```
...
USER wine
...
# Install VB6, .NET 3.5 and .NET 4.8
RUN winetricks -q vb6run comctl32ocx comdlg32ocx dotnet35sp1 dotnet48
```

**Comment by austin987** [comment]
This isn't a winetricks issue.

For help with wine, use the wine forums:
https://forum.winehq.org/
