### ISSUE TITLE
Problem with opensymbol

### ISSUE THREAD

**Issue by jiiiijiij** [Winetricks/winetricks#2067]
When I try to install opensymbol winetrick give me back this error: 

warning: Note: command ar x /home/jiji/.cache/winetricks/opensymbol/fonts-opensymbol_102.10+LibO6.1.5-3+deb10u4_all.deb data.tar.xz returned status 1. Aborting.

**Comment by austin987** [comment]
Please attach the full output.

Is this Linux, or some other OS? If Linux, what verison of binutils do you have?

**Comment by jiiiijiij** [comment]
> Please attach the full output.
> 
> Is this Linux, or some other OS? If Linux, what verison of binutils do you have?

Sorry I forgot about it. I'm using linux and binutils version is 2.40-5.

Winetricks pull the download that have diffrent expected checksum and then that message appear when I keep trying to install it

**Comment by austin987** [comment]
> > Please attach the full output.
> > Is this Linux, or some other OS? If Linux, what verison of binutils do you have?
> 
> Sorry I forgot about it. I'm using linux and binutils version is 2.40-5.
> 
> Winetricks pull the download that have diffrent expected checksum and then that message appear when I keep trying to install it

Well, yeah, if the checksum doesn't match, then things may very well break.

That's why you should include the _full_ output when reporting the issue..

Winetricks should fall back to archive.org to get your download, but again, without the output, hard to say what went wrong there.

In any event, the link is broken. This should be fixed by https://github.com/Winetricks/winetricks/commit/84fe491b2d17e991efc9aa2c602813ce865030d5

**Comment by jiiiijiij** [comment]
> > > Please attach the full output.
> > > Is this Linux, or some other OS? If Linux, what verison of binutils do you have?
> > 
> > 
> > Sorry I forgot about it. I'm using linux and binutils version is 2.40-5.
> > Winetricks pull the download that have diffrent expected checksum and then that message appear when I keep trying to install it
> 
> Well, yeah, if the checksum doesn't match, then things may very well break.
> 
> That's why you should include the _full_ output when reporting the issue..
> 
> Winetricks should fall back to archive.org to get your download, but again, without the output, hard to say what went wrong there.
> 
> In any event, the link is broken. This should be fixed by [84fe491](https://github.com/Winetricks/winetricks/commit/84fe491b2d17e991efc9aa2c602813ce865030d5)

Thank you
