### ISSUE TITLE
What componento I need to install for locale, HID.dll and libcef.dll

### ISSUE THREAD

**Issue by jiiiijiij** [Winetricks/winetricks#2069]
Currently I ran to a problem in wine which tell me 

`
0110:err:module:import_dll Library HID.DLL (which is needed by L"D:\\home\\jiji\\.wine\\drive_c\\Quantower\\TradingPlatform\\v1.130.11\\bin\\Native\\Windows\\libcef.dll") not found
0110:err:module:import_dll Library libcef.dll (which is needed by L"D:\\home\\jiji\\.wine\\drive_c\\Quantower\\TradingPlatform\\v1.130.11\\bin\\Native\\Windows\\CefSharp.BrowserSubprocess.Core.dll") not found
`

`
0468:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000002548A9B8, 40) stub
0468:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
0468:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000318002A8330, 16) stub
[0506/043019.836:WARNING:resource_bundle.cc(450)] locale_file_path.empty() for locale
[0506/043019.836:ERROR:alloy_main_delegate.cc(539)] Could not load locale pak for en-US
0468:fixme:seh:RaiseFailFastException (000000000091D420, 000000000091CF30, 0) stub
`

I have install the hid but it still say missing and I don't know which component include libcef.dll. I have in install most of the component that didn't break wine

**Comment by austin987** [comment]
winetricks doesn't provide hid.dll, this isn't a winetricks issue.
