### ISSUE TITLE
Hello! I have issued problem with "Spore" game.

### ISSUE THREAD

**Issue by WinkRussian** [Winetricks/winetricks#2071]
When i try download spore there is an error that says "Please insert volume 'SPORE' (required for package 'spore')" (multiply of them when i try to close it by clicking "OK")
Also, errors that occurs when i try to close it by X button: "Important: The w_warn_cancel command Please Insert Volume 'SPORE' (required for package 'spore') returned status 1. Abort." (or something like that) Please help! 
![Снимок экрана от 2023-05-14 03-05-21](https://github.com/Winetricks/winetricks/assets/133536423/06ad7d2b-680b-458c-b358-e14fea48c249)
![Снимок экрана от 2023-05-14 03-05-35](https://github.com/Winetricks/winetricks/assets/133536423/ee3ee31a-f9ea-48ad-818f-0b1ccbe2669d)

**Comment by austin987** [comment]
Two things:
1) spore (and other games) were removed in https://github.com/Winetricks/winetricks/commit/66af4adb7c22955277aec34e89f12825b6ca75b7 (i.e., it won't be in the next release).
2) It's not a download, you have to have the DVD for this to work.
