### ISSUE TITLE
remove_mono breaks dotnet40 on subsequent dotnet* installs

### ISSUE THREAD

**Issue by deriamis** [Winetricks/winetricks#2072]
On every call to `remove_mono`, the script checks to see whether Mono is actually installed. If it's not, the function is supposed to bail out before the end where it removes the registry keys and `mscoree.dll`. However, that check has a subtle bug - if dotnet40 is installed (which installs its own `mscoree.dll`) and then, for example `dotnet48` is installed, the `elif` is skipped and the `dotnet40` installation gets broken. Moving the registry key and file removals inside the `if` block fixes the problem for me.

**Comment by ChaoticPumpkin** [comment]
I'm having the same problem, could you elaborate on what exactly you edited in the script to fix it? I looked over parts of the code that looked relevant but bash has some weird syntax. 0_o

**Comment by austin987** [comment]
So, I took a look at this. I quickly noticed that `winetricks --verify dotnet` is broken (see above / #2093).

Moving on, I tried the change that @deriamis suggested (https://github.com/Winetricks/winetricks/commit/31c6ba937b9573debc6866b3c476c80e3de74fb5), but that doesn't work for me (granted, that may be an issue on my system / with the new WoW setup). I seem to recall seeing this years ago though, so I don't think ti's as simple as always removing native mscoree.dll.

@deriamis did you use your 'fixed' script for both installing dotnet40 and dotnet48? What wine version? Did you do something different from what I did above? I get an infinite loop when installing dotnet48.

**Comment by deriamis** [comment]
@austin987 Sorry for disappearing for a while. Lots of life happened. I did install both `dotnet40` and `dornet48`, and what I changed worked for me. I think your diff doesn't look like mine did, though. I didn't have time back when I opened this issue to do a PR, but I do now. I'll create one for you.

**Comment by skryvel** [comment]
Hey. I also stumbled on this and vouch for a fix here. I left a suggestion there in the other PR. Friendly ping to @austin987 as a `+1`
