### ISSUE TITLE
Feature Request: Install WinGet manifests

### ISSUE THREAD

**Issue by upintheairsheep** [Winetricks/winetricks#2085]
Please add support for installing Win32/non-msix-appx packages from WinGet's community repository, via a search API, and using the provided flags or portable package executable(s) to run the setup package.

**Comment by upintheairsheep** [comment]
The vast majority of all WinGet packages do not use appx, msix, or appinstaller.

**Comment by austin987** [comment]
> Please add support for installing Win32/non-msix-appx packages from WinGet's community repository, via a search API, and using the provided flags or portable package executable(s) to run the setup package.

I'm not very familiar with winget, so some explanation / more details would be helpful (or, preferably, a pull request ;)).

The first hit I get on google is https://learn.microsoft.com/en-us/windows/package-manager/winget/, which gives a .msixbundle file. Similarly, if I look at the github page (https://github.com/microsoft/winget-cli), that's what's on their download page.

Wine doesn't appear to be able to run that. I.e., 
* wine Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
* wine msiexec /i Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
* wine start Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

All fail.

**Comment by upintheairsheep** [comment]
> > Please add support for installing Win32/non-msix-appx packages from WinGet's community repository, via a search API, and using the provided flags or portable package executable(s) to run the setup package.
> 
> I'm not very familiar with winget, so some explanation / more details would be helpful (or, preferably, a pull request ;)).
> 
> The first hit I get on google is https://learn.microsoft.com/en-us/windows/package-manager/winget/, which gives a .msixbundle file. Similarly, if I look at the github page (https://github.com/microsoft/winget-cli), that's what's on their download page.
> 
> Wine doesn't appear to be able to run that. I.e.,
> 
> * wine Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
> * wine msiexec /i Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
> * wine start Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
> 
> All fail.

MSIX, APPX, etc should be ignored for winetricks.

**Comment by austin987** [comment]
Okay...so what is the request here if not to install winget?

**Comment by Piroro-hs** [comment]
What the author want is Winetricks to parse package manifests from https://github.com/microsoft/winget-pkgs.

**Comment by austin987** [comment]
> What the author want is Winetricks to parse package manifests from https://github.com/microsoft/winget-pkgs.

IMO that's outside the scope of winetricks. Supporting this properly would be quite an effort, and would be better suited as a dedicated project.
