### ISSUE TITLE
What does alldlls=default do? Why run it?

### ISSUE THREAD

**Issue by kekkoudesu** [Winetricks/winetricks#2088]
Sorry; I wasn't sure where to ask this question. I looked for winetricks documentation and related questions elsewhere but couldn't find much.

`winetricks list-all` says:

```
alldlls=builtin          Override most common DLLs to builtin
alldlls=default          Remove all DLL overrides
```

So I started reading about DLL overrides on the WINE wiki here: https://wiki.winehq.org/Wine_User's_Guide#DLL_Overrides

> There are of course DLLs that Wine does not currently implement very well (or at all). [...] Redistributable packages which install the necessary runtimes can be obtained through the use of [winetricks](https://wiki.winehq.org/Winetricks).

I'm specifically thinking about installing Visual C++ Runtimes with winetricks. My understanding is that WINE's built-in replacement DLLs are incomplete (particularly the Media Foundation parts), so it's worthwhile installing some of the native `vcrun` DLLs with winetricks.

Alright, so let's say I install `vcrun2022` in winetricks, which installs the DLLs for vc2015-2022. What happens if I then run `alldlls=default`? It says it will remove all DLL overrides, so my understanding is it will remove the native `vcrun` DLL overrides winetricks installed and use builtin DLLs instead. Is that different from `alldlls=builtin`, which will go back to using the builtin DLLs for the Visual C++ Runtimes and for anything else WINE has builtin DLLs for? There's this part in the wiki that says "By default the new load order will be native Windows libraries before Wine builtin ones", so my understanding is `alldlls=builtin` is non-standard. But then, does WINE even ship with any native DLLs? So isn't the default...to have them all builtin?

Is there any point to running `alldlls=default` after installing a bunch of DLLs with winetricks? Wouldn't the DLLs I just installed in my wineprefix be overridden by the builtin DLLs, then, thus undoing all of that work?

**Comment by austin987** [comment]
Those options are mostly meant for debugging/advanced usage.

`alldlls=builtin          Override most common DLLs to builtin`

Winetricks has a list of most dlls that are in Wine. When using this option, all of those dlls are explicitly set to builtin.

`alldlls=default          Remove all DLL overrides`

This will remove all DLL overrides from the registry (it deletes the entire key from the registry).

> There's this part in the wiki that says "By default the new load order will be native Windows libraries before Wine builtin ones", so my understanding is `alldlls=builtin` is non-standard. But then, does WINE even ship with any native DLLs?

No, Wine doesn't ship any native DLLs. They are proprietary and often require a Windows license to use.

> So isn't the default...to have them all builtin?

Yes.

> Is there any point to running `alldlls=default` after installing a bunch of DLLs with winetricks?

Generally no, but if you're debugging something, maybe. Setting `alldlls=builtin` can also be useful for debugging to ensure that even if an application installs vcrun20XX itself, that Wine's builtin version is used (i.e., if you want to avoid running Microsoft binaries, or you want to look for bugs in Wine's code).

> Wouldn't the DLLs I just installed in my wineprefix be overridden by the builtin DLLs, then, thus undoing all of that work?

Correct.

**Comment by kekkoudesu** [comment]
Thank you for this great response! I have a much better understanding of how WINE and winetricks work now.

For context, I came across a tutorial using winetricks that included `alldlls=default` after a command for installing several DLLs. They didn't explain why they did this, and after reading your response, I can only conclude it was an error. There's no reason to go to the effort of installing all those DLLs if they're set to never be used immediately afterward.

> `alldlls=default` will remove all DLL overrides from the registry (it deletes the entire key from the registry).

As a clean wineprefix does not include DLL overrides by default, this might be useful for recovering a wineprefix by resetting it to the defaults after overriding the default DLLs with ones installed by winetricks. And then, the user might manually add overrides in `winecfg`. I've seen this as a recommendation in some places on the web.

`alldlls=builtin` wouldn't work for this because winetricks may have installed a DLL that WINE does not have a builtin implementation for.

> No, Wine doesn't ship any native DLLs. They are proprietary and often require a Windows license to use.

I thought so. Thanks for clarifying! It makes sense to have `native,builtin` as a default then, because WINE doesn't ship with native DLLs, but if the user is using winetricks, they would want to take advantage of native DLLs.

**Comment by austin987** [comment]
Glad I could help!
