### ISSUE TITLE
install sysmon in wine failed

### ISSUE THREAD

**Issue by a1boyband** [Winetricks/winetricks#2099]
dump:
Unhandled exception: unimplemented function wevtapi.dll.EvtOpenPublisherMetadata called in 64-bit code (0x0000007b0138ad).
Register dump:
 rip:000000007b0138ad rsp:000000000011be80 rbp:000000000011c0e0 eflags:00000202 (   - --  I   - - - )
 rax:000000000011bea0 rbx:0000000080000100 rcx:000000000011bea0 rdx:000000000011bec0
 rsi:000000000011bf90 rdi:000000000011bed0  r8:0000000000000002  r9:000000000011bf80 r10:000000000027bb80
 r11:0000000000000002 r12:0000000000000000 r13:0000000000000000 r14:0000000000000000 r15:0000000000000000
Stack dump:
0x0000000011be80:  000000000011bea0 0000000000000000
0x0000000011be90:  0000000000000000 0000000000000000
0x0000000011bea0:  0000000180000100 0000000000000000
0x0000000011beb0:  000000007b0138ad 0000000000000002
0x0000000011bec0:  000000006ea04000 000000006ea04294
0x0000000011bed0:  000000000011bfa0 000000007b61865c
0x0000000011bee0:  0000000000000000 0000000000000000
0x0000000011bef0:  0000000000000000 0000000000000000
0x0000000011bf00:  0000000000000000 000000006ea01cb0
0x0000000011bf10:  0000000000090008 000000014022d258
0x0000000011bf20:  0000000000000000 000000006ea00000
0x0000000011bf30:  0000000000000000 000000007b617bb5
Backtrace:
=>0 0x0000007b0138ad RaiseException+0x65(code=<internal error>, flags=<internal error>, count=<is not available>, args=<internal error>) in kernelbase (0x0000000011c0e0)
  1 0x0000006ea02754 __wine_spec_unimplemented_stub+0x34(module=<internal error>, function=<internal error>) in wevtapi (0x0000000011c0e0)
  2 0x0000006ea012b7 in wevtapi (+0x12b7) (0x0000000011c0e0)
0x0000007b0138ad RaiseException+0x65 in kernelbase: nop	
Modules:
Module	Address					Debug info	Name (105 modules)
PE	0000000000740000-00000000007d1000	Deferred        iphlpapi
PE	00000000007e0000-0000000000a3c000	Deferred        rpcrt4
PE	0000000000a40000-0000000000f79000	Deferred        user32
PE	0000000000f80000-0000000001420000	Deferred        comctl32
PE	0000000001420000-000000000225d000	Deferred        shell32
PE	0000000002260000-00000000026c5000	Deferred        oleaut32
PE	00000000026d0000-00000000029d1000	Deferred        crypt32
PE	0000000061fc0000-000000006201a000	Deferred        mpr
PE	0000000062240000-00000000622d2000	Deferred        ws2_32
PE	0000000063080000-0000000063110000	Deferred        winex11
PE	0000000063680000-00000000637c0000	Deferred        shlwapi
PE	00000000641c0000-000000006442b000	Deferred        comdlg32
PE	0000000064680000-00000000646ae000	Deferred        compstui
PE	0000000064a00000-0000000064a54000	Deferred        imm32
PE	0000000065040000-00000000650f8000	Deferred        winspool
PE	0000000065c00000-0000000065c9d000	Deferred        netapi32
PE	0000000065e80000-0000000065eaa000	Deferred        wtsapi32
PE	00000000662c0000-00000000662e6000	Deferred        userenv
PE	0000000067880000-00000000678c1000	Deferred        dnsapi
PE	0000000068680000-00000000686d2000	Deferred        win32u
PE	0000000068740000-0000000068a44000	Deferred        ucrtbase
PE	0000000069580000-000000006981e000	Deferred        msvcrt
PE	0000000069f80000-000000006a089000	Deferred        advapi32
PE	000000006c240000-000000006c2f1000	Deferred        sechost
PE	000000006c380000-000000006c593000	Deferred        gdi32
PE	000000006cb40000-000000006d01a000	Deferred        ole32
PE	000000006d480000-000000006d49f000	Deferred        nsi
PE	000000006d500000-000000006d5b8000	Deferred        uxtheme
PE	000000006d8c0000-000000006da36000	Deferred        combase
PE	000000006ea00000-000000006ea1d000	Dwarf-4         wevtapi
PE	000000006ef00000-000000006ef1f000	Deferred        version
PE	000000006f100000-000000006f14c000	Deferred        shcore
PE	000000006f900000-000000006f947000	Deferred        bcrypt
PE	000000006fa40000-000000006fa68000	Deferred        kerberos
PE	0000000070440000-0000000070459000	Deferred        tdh
PE	00000000711c0000-000000007125e000	Deferred        secur32
PE	000000007b000000-000000007b52f000	Dwarf-4         kernelbase
PE	000000007b600000-000000007b768000	Deferred        kernel32
ELF	000000007d000000-000000007d004000	Deferred        <wine-loader>
PE	0000000140000000-0000000140422000	Deferred        sysmon64
PE	0000000170000000-00000001702e9000	Deferred        ntdll
ELF	00007f5f8e59b000-00007f5f8e7a2000	Deferred        kerberos.so
ELF	00007f5f8e7a2000-00007f5f8e9ab000	Deferred        secur32.so
ELF	00007f5f8e9ab000-00007f5f8ebb0000	Deferred        crypt32.so
ELF	00007f5f8ebb0000-00007f5f8edba000	Deferred        bcrypt.so
ELF	00007f5f8edba000-00007f5f8efcf000	Deferred        libgpg-error.so.0
ELF	00007f5f8efcf000-00007f5f8f2eb000	Deferred        libgcrypt.so.20
ELF	00007f5f8f2eb000-00007f5f8f507000	Deferred        liblz4.so.1
ELF	00007f5f8f507000-00007f5f8f72d000	Deferred        liblzma.so.5
ELF	00007f5f8f72d000-00007f5f8f9b1000	Deferred        libsystemd.so.0
ELF	00007f5f8f9b1000-00007f5f8fbb9000	Deferred        libffi.so.6
ELF	00007f5f8fbb9000-00007f5f8fdbd000	Deferred        libkeyutils.so.1
ELF	00007f5f8fdbd000-00007f5f9000a000	Deferred        libdbus-1.so.3
ELF	00007f5f9000a000-00007f5f9028b000	Deferred        libgmp.so.10
ELF	00007f5f9028b000-00007f5f904c1000	Deferred        libhogweed.so.4
ELF	00007f5f904c1000-00007f5f906f7000	Deferred        libnettle.so.6
ELF	00007f5f906f7000-00007f5f9090a000	Deferred        libtasn1.so.6
ELF	00007f5f9090a000-00007f5f90c88000	Deferred        libunistring.so.2
ELF	00007f5f90c88000-00007f5f90ea5000	Deferred        libidn2.so.0
ELF	00007f5f90ea5000-00007f5f911d4000	Deferred        libp11-kit.so.0
ELF	00007f5f911d4000-00007f5f913df000	Deferred        libkrb5support.so.0
ELF	00007f5f913df000-00007f5f915e3000	Deferred        libcom_err.so.2
ELF	00007f5f915e3000-00007f5f91815000	Deferred        libk5crypto.so.3
ELF	00007f5f91815000-00007f5f91aeb000	Deferred        libkrb5.so.3
ELF	00007f5f91aeb000-00007f5f91cfc000	Deferred        libavahi-client.so.3
ELF	00007f5f91cfc000-00007f5f91f08000	Deferred        libavahi-common.so.3
ELF	00007f5f91f08000-00007f5f9226e000	Deferred        libgnutls.so.30
ELF	00007f5f9226e000-00007f5f924b9000	Deferred        libgssapi_krb5.so.2
ELF	00007f5f924b9000-00007f5f92745000	Deferred        libcups.so.2
ELF	00007f5f92763000-00007f5f92967000	Deferred        winspool.so
ELF	00007f5f929ad000-00007f5f92bb3000	Deferred        libxfixes.so.3
ELF	00007f5f92bb3000-00007f5f92dbd000	Deferred        libxcursor.so.1
ELF	00007f5f92dbd000-00007f5f92fcd000	Deferred        libxi.so.6
ELF	00007f5f92fcd000-00007f5f931d0000	Deferred        libxcomposite.so.1
ELF	00007f5f931d0000-00007f5f933db000	Deferred        libxrandr.so.2
ELF	00007f5f933db000-00007f5f935e5000	Deferred        libxrender.so.1
ELF	00007f5f935e5000-00007f5f937eb000	Deferred        libxxf86vm.so.1
ELF	00007f5f937eb000-00007f5f939ee000	Deferred        libxinerama.so.1
ELF	00007f5f939ee000-00007f5f93c00000	Deferred        libnss_files.so.2
ELF	00007f5f93c00000-00007f5f93e08000	Deferred        librt.so.1
ELF	00007f5f93e08000-00007f5f9401d000	Deferred        libbsd.so.0
ELF	00007f5f9401d000-00007f5f94223000	Deferred        libxdmcp.so.6
ELF	00007f5f94223000-00007f5f94427000	Deferred        libxau.so.6
ELF	00007f5f94427000-00007f5f9464f000	Deferred        libxcb.so.1
ELF	00007f5f9464f000-00007f5f94987000	Deferred        libx11.so.6
ELF	00007f5f94987000-00007f5f94b99000	Deferred        libxext.so.6
ELF	00007f5f94bb7000-00007f5f94e42000	Deferred        winex11.so
ELF	00007f5f94eb8000-00007f5f950ea000	Deferred        libexpat.so.1
ELF	00007f5f950ea000-00007f5f9532f000	Deferred        libfontconfig.so.1
ELF	00007f5f9532f000-00007f5f9554c000	Deferred        libz.so.1
ELF	00007f5f9554c000-00007f5f9577e000	Deferred        libpng16.so.16
ELF	00007f5f9577e000-00007f5f95a32000	Deferred        libfreetype.so.6
ELF	00007f5f95a32000-00007f5f95dd0000	Deferred        libm.so.6
ELF	00007f5f95dd0000-00007f5f96184000	Deferred        win32u.so
ELF	00007f5f96184000-00007f5f96389000	Deferred        netapi32.so
ELF	00007f5f96389000-00007f5f9658e000	Deferred        ws2_32.so
ELF	00007f5f9658e000-00007f5f967a8000	Deferred        libresolv.so.2
ELF	00007f5f967a8000-00007f5f969ab000	Deferred        dnsapi.so
ELF	00007f5f96aab000-00007f5f96e20000	Dwarf           libwine.so.1
ELF	00007f5f973b3000-00007f5f975cb000	Deferred        libgcc_s.so.1
ELF	00007f5f975cb000-00007f5f97890000	Deferred        ntdll.so
ELF	00007f5f97893000-00007f5f97c84000	Deferred        libc.so.6
ELF	00007f5f97c84000-00007f5f97e88000	Deferred        libdl.so.2
ELF	00007f5f97e88000-00007f5f980a7000	Deferred        libpthread.so.0
ELF	00007f5f980c7000-00007f5f982f3000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	00000054    0     wine_rpcrt4_io
	00000058    0     wine_threadpool_worker
	00000064    0     wine_rpcrt4_io
	0000007c    0     wine_rpcrt4_io
	00000088    0     wine_rpcrt4_io
	000000ac    0     wine_rpcrt4_io
	000000cc    0     wine_rpcrt4_io
	000000d0    0     wine_threadpool_worker
	000000e8    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	0000005c    0     
	00000060    0     wine_sechost_service
	00000068    0     
	0000006c    0     
	00000070    0     
	000000dc    0     
0000004c explorer.exe
	00000050    0     
	000000a8    0     
	000000c4    0     wine_rpcrt4_server
00000074 winedevice.exe
	00000078    0     
	00000080    0     
	00000084    0     wine_sechost_service
	0000008c    0     
	00000090    0     
	00000094    0     
	00000098    0     
	0000009c    0     
000000a0 plugplay.exe
	000000a4    0     
	000000b0    0     
	000000b4    0     wine_sechost_service
	000000b8    0     wine_rpcrt4_server
000000bc svchost.exe
	000000c0    0     
	000000d4    0     
	000000d8    0     wine_sechost_service
000000e0 rpcss.exe
	000000e4    0     
	000000ec    0     
	000000f0    0     wine_sechost_service
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_server
	000000fc    0     wine_rpcrt4_io
	00000100    0     wine_threadpool_worker
00000104 conhost.exe
	00000108    0     
0000010c Sysmon64.exe
	00000110    0     
0000011c (D) C:\windows\Sysmon64.exe
	00000120    0 <== 
	0000012c    0     
System information:
    Wine build: wine-8.0.1
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.4.0-144-generic

**Comment by austin987** [comment]
This isn't a winetricks issue. It should be reported https://bugs.winehq.org/
