### ISSUE TITLE
winetricks 64bit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#210]
```
Sorry, I don't know where can I ask this question:

How about winetricks 64bit for wine 64bit?
Does it exist or just in development?

Thank you. I apologize for my behavior.
```

Original issue reported on code.google.com by `knockdow...@gmail.com` on 14 May 2012 at 4:07
- Blocked on: #222, #272, #362

**Comment by mirh** [comment]
Couldn't this be closed?

**Comment by austin987** [comment]
Yeah, not everything works on 64-bit, but those should get their own issues.

**Comment by mirh** [comment]
Would it be possible to do away with the ever present 64-bit WINEPREFIX w_warn then?
