### ISSUE TITLE
 Wine-8.11 wine64 cannot install  .net40

### ISSUE THREAD

**Issue by zmtong1988** [Winetricks/winetricks#2100]
Wine-8.11 64 bit container, with Mono 8.0 installed, cannot install. net40. The prompt is shown in the following figure.
![322](https://github.com/Winetricks/winetricks/assets/22734355/3ff98047-6fcf-423c-9d1b-f0149f18b856)

How can I fix it ?

**Comment by KenSharp** [comment]
Providing the winetricks log would help.
