### ISSUE TITLE
Sorry if not properly issue an unsuitable problem but can't help

### ISSUE THREAD

**Issue by abdulbadii** [Winetricks/winetricks#2111]
How to solve this to run shamela.exe (maktabah shamilah) a viewer of arabic text in sql .db form
`
...:err:module:import_dll Library Qt5Pdf.dll (which is needed by L"C:\\.....
`
not solved by
winetricks qt5pdf

Any expert give guidance or hint by good hunch ?

**Comment by austin987** [comment]
That's part of QT; the application should ship it (or provide instructions on how to get it); it's not part of windows as far as I know.

I'd suggest contacting the developer of the application and asking them.
