### ISSUE TITLE
Error when i try to install any version of vcrun (return status 17)

### ISSUE THREAD

**Issue by Skiez6055** [Winetricks/winetricks#2114]
This might sound odd to some of you. I am currently using a Hacked Nintendo Switch using Switchroot's Linux Ubuntu Bionic port. Also using box64. 

I installed wine via pi-apps. (it was bundled in their own megascript) with winetricks included.

Wine works successfully. But getting winetricks to install vcrun just doesn't work. i tried asking in the "linux 4 switch" discord server and nobody given me a solution. I tried killing wineserver. Nothing i did worked.

debug log:

`Warning, function gnutls_x509_spki_set_rsa_pss_params not found in lib libgnutls.so.30
Look for gnutls_x509_spki_set_rsa_pss_params in loaded elfs
Warning, function gnutls_x509_spki_set_rsa_pss_params not found in lib libgnutls.so.30
Look for gnutls_x509_spki_set_rsa_pss_params in loaded elfs
Warning, function gnutls_x509_spki_set_rsa_pss_params not found in lib libgnutls.so.30
Look for gnutls_x509_spki_set_rsa_pss_params in loaded elfs
Warning, function gnutls_x509_spki_set_rsa_pss_params not found in lib libgnutls.so.30
Using emulated /opt/wine-8.14/lib/wine/x86_64-unix/crypt32.so
Using emulated /opt/wine-8.14/lib/wine/x86_64-unix/ws2_32.so
0024:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111 for dll L"C:\\windows\\system32\\msxml2.dll"
0024:err:ole:com_get_class_object no class object {f5078f1b-c551-11d3-89b9-0000f81fe221} could be created for context 0x1
0024:fixme:ver:GetCurrentPackageId (001EFE94 00000000): stub
`

**Comment by austin987** [comment]
Looks like your gnutls setup is broken (which wine depends on).

I'm not sure what the fix is, that's something you'll need to fix on the linux/box64 side, it's not a winetricks problem.
