### ISSUE TITLE
need help with launching winetricks. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [Winetricks/winetricks#2116]
hi, im on arch linux and im trying to load winetricks. it won't launch.

**Comment by austin987** [comment]
We can't help without more detail. A screenshot/terminal output for example, showing what went wrong. What did you try to do, and what happened instead?

FYI you may have better luck with arch support channels.

**Comment by DOOMMARINE117** [comment]
> We can't help without more detail. A screenshot/terminal output for example, showing what went wrong. What did you try to do, and what happened instead?
> 
> FYI you may have better luck with arch support channels.

ok, so when installed winetricks. i type in sudo pacman -S winetricks. i thought i installed it correctly.

i tried clicking on it. nothing happens. 

is there a command to see what i can find?

**Comment by DOOMMARINE117** [comment]
![IMG_20230904_124742](https://github.com/Winetricks/winetricks/assets/64376960/13d7e4b9-4a4a-4d7e-93e0-c3f36357ed90)

**Comment by vic-bay** [comment]
the solution is in the last three lines of the message. install zenity or kdialog.

**Comment by Chiitoo** [comment]
Or/and 'winetricks --help' to see the command-line usage.  :]

**Comment by DOOMMARINE117** [comment]
> the solution is in the last three lines of the message. install zenity or kdialog.

that works, thanks.

**Comment by DOOMMARINE117** [comment]
just have an issue.

You are running winetricks-20220521. latest upstream is winetricks-20230212!

how to fix it?

**Comment by DOOMMARINE117** [comment]
ok i installed winetricks again and it says: "cinepak install completed, but installed file /home/talion/.local/share/wineprefixes/Age Of Mythology/dosdevices/c:/windows/syswow64/iccvid.dll not found".

**Comment by DOOMMARINE117** [comment]
nevermind, looks an update fix it.

**Comment by DOOMMARINE117** [comment]
still issues.

**Comment by DOOMMARINE117** [comment]
even updating itself cause issues with winetricks. but it still launches. thoguh certain programs liek microsoft visual studio wont show a checkmark when installed.

when installing a dvd game age of mythology with lutris.  it wont update it.

**Comment by DOOMMARINE117** [comment]
it seems even lutris wont update winetricks.

**Comment by DOOMMARINE117** [comment]
ly unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BE53B0, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BE5390, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BD5EB0, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BD5E90, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BD1458, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BD1438, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BE00D0, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BE00B0, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BE5F90, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BE5F70, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BD1E38, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BD1E18, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BCFFD0, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BCFFB0, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BCDC18, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BCDBF8, 10002, 01DDF09C: stub
010c:fixme:oleacc:find_class_data unhandled window class: L"#32770"
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BEAA08, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BEA9E8, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BE1448, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BE1428, 10002, 01DDF09C: stub
0114:fixme:imm:ime_ui_notify himc 0002007E, hwnd 00000000, wparam IMN_CLOSESTATUSWINDOW, lparam 0 stub!
010c:fixme:oleacc:find_class_data unhandled window class: L"#32770"
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BCE7E8, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BCE7C8, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BD7918, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BD78F8, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BCF7B0, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BCF790, 10002, 01DDF09C: stub
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BD2818, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BD27F8, 10002, 01DDF09C: stub
0114:fixme:imm:ime_ui_notify himc 0002007E, hwnd 00000000, wparam IMN_CLOSESTATUSWINDOW, lparam 0 stub!
010c:fixme:oleacc:find_class_data unhandled window class: L"#32769"
010c:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
010c:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:uia_element_GetCurrentPropertyValueEx Default property values currently unimplemented
010c:fixme:uiautomation:msaa_provider_GetPatternProvider Unimplemented patternId 10002
010c:fixme:uiautomation:nc_provider_GetPatternProvider 00BE53B0, 10002, 01DDF09C: stub
010c:fixme:uiautomation:base_hwnd_provider_GetPatternProvider 00BE5390, 10002, 01DDF09C: stub
