### ISSUE TITLE
Stuff such for like fonts are gone from mirrors.kernel.org/gentoo

### ISSUE THREAD

**Issue by Alexander88207** [Winetricks/winetricks#2118]
Hello,

i just wanted to install corefonts or arial fonts then saw that there is a mismatch.

When you browse the url then you get an 404 message.

Some mirror suggestion: https://github.com/pushcx/corefonts

**Comment by rayanmargham** [comment]
Yea this is a big issue I experienced this as well

**Comment by rayanmargham** [comment]
cannot install corefonts

**Comment by rayanmargham** [comment]
@austin987 please look into this issue! outdated broken mirror

**Comment by rayanmargham** [comment]
I fixed it and purposed a pull request #2124

**Comment by Chiitoo** [comment]
The files are still there, but organised under different directories since 2019 or so, and the compatibility symlinks were recently removed [1], and for example, 'andale32.exe' can be found under '7d' [2] now.

1. https://bugs.gentoo.org/914092
2. https://mirrors.kernel.org/gentoo/distfiles/7d/

**Comment by illegalcoding** [comment]
Yep, just experienced this. I could fix it by downloading them from the wayback machine and quietly swapping out the executable while it was waiting for a response on if it should continue with an invalid hash
It was getting an invalid hash since it downloaded a 404 page and put it into the exe file

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/afd1782abe2f2ac7c480292d73049667faebb77f
