### ISSUE TITLE
weird dialog box appears on win64

### ISSUE THREAD

**Issue by reigneil** [Winetricks/winetricks#2120]
desktop shortcut execution winetricks --gui -q:
![Screenshot from 2023-09-18 23-22-58](https://github.com/Winetricks/winetricks/assets/9740000/fb92df54-7d30-4307-adcc-8c1423a656fa)

terminal execution:

```
winetricks
od: wine: No such file or directory
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.`
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: cf1e17a69db4126779e597def9facdecbb0703a20ed7172dd877b1f7824d66ec with wine-8.0.2 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.42.1
```

every time i start winetricks it shows this dialog box even if i use -q
i use linux mint 21.2 cinnamon distro
on a 32bit winearch this dialog didn't appear along side with that warning

**Comment by austin987** [comment]
This should be fixed by https://github.com/Winetricks/winetricks/commit/8e2cc52e5a54dbab19b8ab2e2aca1e0959517419, sorry about that
