### ISSUE TITLE
W_OPT_NOCLEAN is being used incorrectly in winetricks_cleanup()

### ISSUE THREAD

**Issue by gnab-gib-se** [Winetricks/winetricks#2121]
```
--no-clean) W_OPT_NOCLEAN=1 ;;
```

In most places in the script W_OPT_NOCLEAN is used (correctly, albeit confusingly for people not versed in shell scripting) as so:
```
test "${W_OPT_NOCLEAN}" = 1 || rm -rf "${WINETRICKS_WORKDIR}"
```

But then in winetricks_cleanup() we have this:
```
    if [ "${W_OPT_NOCLEAN}" = 1 ]; then
        rm -rf "${WINETRICKS_WORKDIR}"
        rm -rf "${W_TMP_EARLY}"
        rm -rf "${WINEPREFIX}/wrapper.cfg"
        rm -rf "${WINEPREFIX}/no_win64_warnings"
    fi
```

As a result you get a bunch of this:
```
drwx------ 2 x x     40 Sep 18 23:36  winetricks.ogInw2Nq/
drwx------ 2 x x     40 Sep 18 23:36  winetricks.DT2ukQS5/
drwx------ 2 x x     40 Sep 18 23:36  winetricks.KsW5ScWf/
drwx------ 3 x x    120 Sep 18 23:37  winetricks.bsoeLz7p/
```

And `--no-clean` has the exact opposite effect for this subset of items; it causes these things to be deleted.

The amazing thing is that it's been like this for a year and a half and I guess no one has noticed?  lol
```
87f7cb8f src/winetricks       (Austin English            2022-03-14 16:43:03 -0500  4963)     if [ "${W_OPT_NOCLEAN}" = 1 ]; then
```

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/ac14c2f82ef24633af39e2d5ab13bc3f097286d6; thanks!
