### ISSUE TITLE
Broken link for 'winetricks vb6run'

### ISSUE THREAD

**Issue by SwissGipfel** [Winetricks/winetricks#2133]
Hello

While installing vb6run with winetricks (`winetrick -q vb6run`) I got the error message

> warning: Downloading https://web.archive.org/web/2000/https://web.archive.org/web/20070204154430/https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd
-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe failed

This looked like a weird link to me, so I tried to fetch the runtime installer myself:

```sh
mkdir -p $HOME/.cache/winetricks/vb6run/
wget https://web.archive.org/web/20070204154430/https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe -P $HOME/.cache/winetricks/vb6run/
winetricks -q vb6run
```

With this, the installation succeeded, which lead me to think, that the URL winetricks gets is wrong.

I'm sorry for wasting your time, if it's an error/misunderstanding on my side.

**Edit:** 

If that's any help, my version:

```sh
winetricks --version
20230212-next - sha256sum: fe0550e0d843214f87dcb0f4aa591be0046fa93db7b8330217dd926258e628fc
```

**Comment by DarkShadow44** [comment]
Are you sure it wasn't just a spurious error? For me it works just fine, same error. It could happen that, for some reason, it just didn't work in that exact moment. Can you retry please?

**Comment by SwissGipfel** [comment]
You're right.

Tried it just now, and `winetrick -q vb6run` ran withouth a problem.
Sorry for troubling you. I'll close this issue.

**Comment by ptsmonteiro** [comment]
Having the same problem:

> % sh winetricks -q vb6run
> 
> Executing w_do_call vb6run
> Executing load_vb6run
> Downloading http://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe to /Users/pedro/.cache/winetricks/vb6run
> --2024-07-12 22:23:28--  http://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe
> Resolving download.microsoft.com (download.microsoft.com)... 23.57.80.95
> Connecting to download.microsoft.com (download.microsoft.com)|23.57.80.95|:80... connected.
> HTTP request sent, awaiting response... 302 Moved Temporarily
> Location: https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe [following]
> --2024-07-12 22:23:28--  https://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe
> Connecting to download.microsoft.com (download.microsoft.com)|23.57.80.95|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2024-07-12 22:23:28 ERROR 404: Not Found.
> 
> ------------------------------------------------------
> Downloading http://download.microsoft.com/download/5/a/d/5ad868a0-8ecd-4bb0-a882-fe53eb7ef348/VB6.0-KB290887-X86.exe failed
>

**Comment by austin987** [comment]
You're using an out of date winetricks.
