### ISSUE TITLE
w_call opensymbol fails due to 404

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#2137]
When a [.verb file](https://github.com/EA31337/ansible-role-metatrader/blob/9cbf10456a22aa343acb4f1fe685cbcd70a8c2f4/templates/mt5_install.verb.j2) has the following section, it fails to access some endpoints (with 404) when calling `opensymbol`:

    if w_workaround_wine_bug 7156 "${title} needs wingdings.ttf, installing opensymbol"
    then
        w_call opensymbol
    fi

as per https://github.com/Winetricks/winetricks/issues/1357#issuecomment-1763371984.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/8f8ea24576c8f81481a9b57a93ce57a8acbbecb0

**Comment by kenorb** [comment]
Still fails at <https://cdn-aws.deb.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.10+LibO6.1.5-3+deb10u4_all.deb> link which gives 404.

```
  Executing w_do_call opensymbol
  ------------------------------------------------------
  warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
  ------------------------------------------------------
  Executing load_opensymbol 
  Executing mkdir -p /root/.cache/winetricks/opensymbol
  Executing cd /root/.cache/winetricks/opensymbol
  Downloading https://cdn-aws.deb.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.10+LibO6.1.5-3+deb10u4_all.deb to /root/.cache/winetricks/opensymbol
  Executing cd /
  ------------------------------------------------------
  SHA256 mismatch!
  
  URL: https://cdn-aws.deb.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.10+LibO6.1.5-3+deb10u4_all.deb
  Downloaded: 56e752b41841458771a9f178070daef7b0b90e83f4d2a22fadeac5218df1cefd
  Expected: 1b2ab1e8eeb9a3a4a07e4a1c9bf539bb721734bf8b9881f4d0b8e71e822cecde
```

**Comment by Chiitoo** [comment]
Which version of Winetricks are you running with?  Seems to be missing certain messages there, and this expected hash was changed back in May 2023 (and the version is behind too):

> ```
>   Downloaded: 56e752b41841458771a9f178070daef7b0b90e83f4d2a22fadeac5218df1cefd
>   Expected: 1b2ab1e8eeb9a3a4a07e4a1c9bf539bb721734bf8b9881f4d0b8e71e822cecde
> ```

- https://github.com/Winetricks/winetricks/commit/84fe491b2d17e991efc9aa2c602813ce865030d5

If you can't get a more recent version via your package manager, you can simply download Winetricks and run it as an executable or a shell script.

**Comment by kenorb** [comment]
Can't reproduce this the version from the latest `master`.

```
docker run -it solarkennedy/wine-x11-novnc-docker bash
```

```
install -v <(wget -qO- https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks) /usr/local/bin/winetricks
/usr/bin/supervisord &
echo w_call opensymbol > test.verb
wineserver -k
winetricks -q test.verb
```

It's probably I've used fork with the other fix, but it broke this issue.
Thank you.
