### ISSUE TITLE
Some fonts fail to install (arial32.exe, times32.exe...)

### ISSUE THREAD

**Issue by rvdbergh** [Winetricks/winetricks#2142]
There are issues with downloading some of the fonts using winetricks.
Steps to reproduce: 
On Ubuntu 22.04 LTS with Wine (tested on devel and staging) installed, install winetricks using
`sudo apt-get install winetricks `.
Open winetricks and click "select the default wine prefix"
Click install a font and click OK
Click the checkmark for all fonts and click OK
After seconds a dialog box will pop up saying `sha256sum mismatch! Rename /home/rick/.cache/winetricks/corefonts/arial32.exe and try again.`
The same happens for the Comic Sans font.
The files do appear in the /.cache/ folder in my home dir, but appear to be 0 bytes.

**Comment by Chiitoo** [comment]
Greetings!

Installing Winetricks via apt tends to get you a pretty old release (try running `winetricks --version`), and many issues will have already been fixed.

You can simply download Winetricks [1] (use 'wget' for example, or open the link in a browser and 'save page as'), then run it using bash:

`bash path/to/winetricks`

That said, 'arial32.exe' in particular may still be problematic, but you can manually download it from the archive [2], and place it into the cache directory, then re-run Winetricks.

See also the following issues:

- https://github.com/Winetricks/winetricks/issues/2132
- https://github.com/Winetricks/winetricks/issues/2136

1. https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
2. https://web.archive.org/web/20180219204401/https://mirrors.kernel.org/gentoo/distfiles/arial32.exe

**Comment by rvdbergh** [comment]
Thanks for the help!
I have installed the latest version of winetricks from the repo after first removing the apt installed version. Then manually downloading arial32 and replacing it in the correct place in the cache directory worked. The same also worked for times32.exe, which I got from the same URL you provided, by simply replacing the last part of the URL.

**Comment by Chiitoo** [comment]
Glad to see it was indeed that being the issue, and that you got it working!

I think we can leave this open for the fonts that are still being an issue, though there is some overlap with the the web archive one.

**Comment by mid-kid** [comment]
@Chiitoo why are the fonts fetched from gentoo distfiles rather than directly from https://corefonts.sourceforge.net/ ? This would bypass the need of archive.org for the fonts that gentoo extracts from EUupdate.EXE these days.

**Comment by Chiitoo** [comment]
Probably historical reasons of sorts.

It looks like sourceforge was originally used, or at least since the first import to git [1], but it was later changed to something else, eventually ending up with the Gentoo mirrors [2][3][4].

I remember there being some dismay in general over changes at sourceforge, not specific to Winetricks, but I forget the details, and I don't know if that was the reason for the change here.

1. https://github.com/Winetricks/winetricks/commit/c48d6b1c79ea7ae6a1e9e50d87997a90c949d033#diff-e0fd78cbea37cee354dd1d2de7fafbe41a5d3b57b6980bb5ff772f29bbce374aR4899
2. https://github.com/Winetricks/winetricks/commit/dae31e4074ee115a6ed0da5a2f57fb169537ea58
3. https://github.com/Winetricks/winetricks/commit/8762f1417ae1aaa221eeaa99e279b21be9a75712
4. https://github.com/Winetricks/winetricks/commit/1ccac4084182f9ede6a9af8f6e389753f0b60c81

**Comment by Chiitoo** [comment]
Somewhat confusingly I get successful downloads for 'corefonts' from the archive without any changes, even with the archive URLs having the '5e' in them.

I wonder if Ubuntu 22.04 LTS uses 'wget2' as the wget provider (I have 'aria2' installed, which Winetricks prefers over 'wget', and don't have 'wget2' installed aside from some testing recently), which is a whole different flavour of an issue ( https://github.com/Winetricks/winetricks/pull/2130 ).

**Comment by mid-kid** [comment]
I was using gentoo, which still uses wget1, and the problems were intermittent (failed SSL handhake), maybe it was just a yesterday thing, or my connection.

**Comment by Kodehawa** [comment]
I'm having this issue on most fonts I've tried, even on the latest version. Any ideas?

**Comment by Chiitoo** [comment]
> I'm having this issue on most fonts I've tried, even on the latest version. Any ideas?
> 
> Links seem to all just be dead.

Yes, at least the URL in your image is quite dead.

By "latest version" I assume a little that you mean the latest release?  Try downloading a copy of the latest git master state, which will point to the new URL for 'andale32.exe'.

There are some that need some fixing still, but those should end up downloading from the archive instead.

**Comment by taras-rosa** [comment]
I can confirm the issue. Links to the following fonts seem to be dead in the current Winetricks version in the master branch [f3531c5]:
https://mirrors.kernel.org/gentoo/distfiles/5e/arial32.exe
https://mirrors.kernel.org/gentoo/distfiles/fe/times32.exe
https://mirrors.kernel.org/gentoo/distfiles/fa/trebuc32.exe
https://mirrors.kernel.org/gentoo/distfiles/a1/verdan32.exe
