### ISSUE TITLE
winetricks_get_file_arch path - od: wine: No such file or directory / Unknown file arch

### ISSUE THREAD

**Issue by randallpittman** [Winetricks/winetricks#2143]
From the change made in #2030, the call

```bash
_W_wine_binary_arch="$(winetricks_get_file_arch "${WINE}")"
```

on line [5057](https://github.com/Winetricks/winetricks/blob/07c6d38913433c6318c4d5358ea75987b9a419f1/src/winetricks#L5057) doesn't work because `WINE==wine`, so in `winetricks_get_file_arch`, `od` fails with

```text
od: wine: No such file or directory
```

I'm not sure it's a sane workaround, but for me I just changed line 5057 to

```bash
_W_wine_binary_arch="$(winetricks_get_file_arch $(which "${WINE}"))"
```

ETA:
@theofficialgman posted perhaps a more robust solution on Issue 2023: <https://github.com/Winetricks/winetricks/issues/2030#issuecomment-1705755913>

**Comment by GuillaumeCisco** [comment]
I can confirm too this patch fixes the issue.

**Comment by kenorb** [comment]
Same errors:

```
#14 13.04 wine: configuration in L"/home/ubuntu/.wine" has been updated.
#14 13.05 Installing winhttp...
#14 13.25 od: wine: No such file or directory
#14 14.22 od: wine: No such file or directory
...
#14 23.35 Installing .NET...
#14 23.54 od: wine: No such file or directory
#14 24.50 od: wine: No such file or directory
```

**Comment by Fuckingnameless** [comment]
same here, how can i fix it?

**Comment by seisdr** [comment]
Jesus

**Comment by DropTable69** [comment]
Nothin' more exciting than three-hundred and forty five popups while installing fonts.

**Comment by Chiitoo** [comment]
> same here, how can i fix it?

You could try the changes from this pull request:

https://github.com/Winetricks/winetricks/pull/2147

> Nothin' more exciting than three-hundred and forty five popups while installing fonts.

You can avoid those by not using the GUI.

> Winetricks still broken

Yes, there are issues, though at least for me things still work even if I do get this error message as well.

I know not for how long things may remain as they are.  I have not seen any of the usual activity from the project owner, nor do I know of anyone else who knows their status.

I just hope they are okay... or better.

While I try to help around, I will not be merging any changes to 'master' or create releases, since we never agreed on that.

At most I might create my own branch where I fix things that I can, but a fork would lilkely be better still...

**Comment by ActuallyTheOwner** [comment]
Still broken?
This happens on Gentoo

**Comment by Chiitoo** [comment]
@ActuallyTheOwner,

> Still broken? This happens on Gentoo

Please open a new issue with steps you are re-producing the issue.

I do believe this particular issue should be no longer there since almost a year ago, and I don't think I have seen it since (on Gentoo LInux).

**Comment by hezd1** [comment]
Im also experiencing this right now.

**Comment by thisIsLoading** [comment]
same here, ubuntu 24.04 just installed via `apt install wine winetricks`

**Comment by rubin55** [comment]
Arch, still issue! Will this get fixed?

**Comment by lord-asmo** [comment]
![image](https://github.com/user-attachments/assets/71a7b609-25f3-40cc-8c1e-6549194a9bd0)

**Comment by austin987** [comment]
winetricks-20250102 has been released. If you're still seeing an issue with that version, please open a new issue (and include the terminal output).

**Comment by attilasztraka53-beep** [comment]
Run winecfg.
Follow the instructions there.

**Comment by melroy89** [comment]
ok.. I fixed it here: https://github.com/Winetricks/winetricks/pull/2457 when using -q.. its still not resolved under Debian Trixie for example.
