### ISSUE TITLE
"Unknown file arch" error message

### ISSUE THREAD

**Issue by Yehh22** [Winetricks/winetricks#2145]
Why does the error message "unknown file arch" appear everytime I try to install a dll/fonts? It is happening on both Linux and macOS. The error can be ignored but it's quite annyoing

![image](https://github.com/Winetricks/winetricks/assets/127546925/18dc7f51-2027-4685-bf09-38206ce934db)

In the output, it ends with `od: wine: No such file or directory`

```
vm@vm-virtual-machine:~$ ./winetricks
od: wine: No such file or directory
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: fe0550e0d843214f87dcb0f4aa591be0046fa93db7b8330217dd926258e628fc with wine-8.18 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.42.1
Executing w_do_call cmd
od: wine: No such file or directory
```

**Comment by Chiitoo** [comment]
This looks like:

https://github.com/Winetricks/winetricks/issues/2143

Closing as a duplicate.

Thank you for the report!
