### ISSUE TITLE
Feature Req / Issue - Dotnet70 Unknown Arg

### ISSUE THREAD

**Issue by ImKringle** [Winetricks/winetricks#2150]
#2053 - This still doesn't seem valid under Winetricks and just gives an unknown arg error. Re-posting as that was closed a while ago
- https://dotnet.microsoft.com/en-us/download/dotnet/7.0

Tested using Wine Staging / Devel / Latest - no dice.

Specifically* 7.0.11+ if possible - dotnet7 itself works but its missing a solid chunk of the new additions

**Comment by ImKringle** [comment]
> Greetings!
> 
> Which version of Winetricks are you running with (`winetricks --version`)?
> 
> There has been no release after the commit that added `dotnet70`, so one would need to get a new enough copy manually, unless their Linux distribution for example maintains some kind of a snapshot, or provides a "build" straight from the git repository.

Hello!

Its all containered but its running off the yolks over at parkervcp - https://github.com/parkervcp/yolks/blob/master/wine/latest/Dockerfile#L22-L23
This just pulls right off the github here so it should be the latest release

**Comment by Chiitoo** [comment]
Hmmm, yeah, that would get Winetricks from 'git master', that is, the most recent unreleased development state.

Hmhm... after another look, the verb seems to be named 'dotnet7' instead of 'dotnet70'.

Does 'dotnet7' work for you?

**Comment by ImKringle** [comment]
dotnet7 installs 7.0.5 it seems - Assuming this isn't editable? Without it in the egg im using it boots w/o a script error, now it just breaks scripting if I use 7.0.5 (files call for 7.0.4)

**Comment by Chiitoo** [comment]
Right, you could of course edit a local copy to try it out until we get it up to date on this side.  : ]

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/90d1c6915cec6b2c6113d6187fda60d43c443b7b bumps it to 7.0.14.
