### ISSUE TITLE
New releases more frequently?

### ISSUE THREAD

**Issue by bmx666** [Winetricks/winetricks#2157]
Thank you for maintaining this project. I was wondering if it's possible to release new updates more frequently, focusing on minor bug fixes such as fixing broken URLs and updating outdated projects.

I've noticed numerous pull requests for refactoring, which could introduce side effects and require extensive testing. However, minor patches that address issues with broken projects could be integrated into the mainline more regularly. This is important as many third-party projects rely on the release version of Winetricks. I often advise people to use the latest version from the master branch to avoid problems like checksum mismatches or inaccessible URLs.

What are your thoughts on this approach?

**Comment by austin987** [comment]
Hi @bmx666, thanks for the feedback.

I'm aware of a few downstream projects; but I don't know their release cadence. Do you happen to know how often they release / what cadence would be useful for them?

I've been busy with other projects lately, but hope to have more time in the future. Of course I can't guarantee that, as this is something I do in my free time..

PS, 20240105 was just released ;)

**Comment by bmx666** [comment]
Hi @austin987 , thanks for your feedback. I will close this issue.
