### ISSUE TITLE
vcrun 2015 won't install

### ISSUE THREAD

**Issue by Simper-Channel** [Winetricks/winetricks#2160]
### wine vcrun 2015
`Executing mkdir -p /home/simper
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206 - sha256sum: 0f21da98811e0bfda16a7d6d6b8e860a9cedbd4e836c7dd9b02f068d3092ee2e with wine-6.0.3 (Ubuntu 6.0.3~repack-1) and WINEARCH=win64
Executing w_do_call vcrun2015
Executing mkdir -p /home/simper
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_vcrun2015 
Executing mkdir -p /home/simper/.cache/winetricks/vcrun2015
Executing cd /home/simper/.cache/winetricks/vcrun2015
Downloading https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe to /home/simper/.cache/winetricks/vcrun2015
--2023-12-21 16:34:39--  https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe
Resolving download.microsoft.com (download.microsoft.com)... 2.22.81.101, 2a02:26f0:b80:297::317f, 2a02:26f0:b80:29c::317f
Connecting to download.microsoft.com (download.microsoft.com)|2.22.81.101|:443... connected.                                   
HTTP request sent, awaiting response... 200 OK                                                                                 
Length: 13767776 (13M) [application/octet-stream]                                                                              
Saving to: ‘vc_redist.x86.exe’                                                                                                 

vc_redist.x86.exe               100%[======================================================>]  13.13M  1.51MB/s    in 8.8s    

2023-12-21 16:34:48 (1.49 MB/s) - ‘vc_redist.x86.exe’ saved [13767776/13767776]

Executing cd /home/simper
Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-convert-l1-1-0 api-ms-win-crt-environment-l1-1-0 api-ms-win-crt-filesystem-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-multibyte-l1-1-0 api-ms-win-crt-process-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-string-l1-1-0 api-ms-win-crt-utility-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcr140 ucrtbase vcomp140 vcruntime140
Executing wine regedit C:\windows\Temp\override-dll.reg
Executing wine64 regedit C:\windows\Temp\override-dll.reg
00fc:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for EET, bias -120, std (d/m/y): 27/10/2023, dlt (d/m/y): 28/04/2023
0104:fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for EET, bias -120, std (d/m/y): 27/10/2023, dlt (d/m/y): 28/04/2023
00fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0104:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0104:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Executing wine winecfg -v winxp64
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/simper/.wine terminate
------------------------------------------------------
Executing rm -f /home/simper/.wine/dosdevices/c:/windows/syswow64/ucrtbase.dll
Executing cd /home/simper/.cache/winetricks/vcrun2015
Executing wine vc_redist.x86.exe
0024:err:ole:com_get_class_object class {f6d90f11-9c73-11d3-b32e-00c04f990bb4} not registered
0024:err:ole:com_get_class_object no class object {f6d90f11-9c73-11d3-b32e-00c04f990bb4} could be created for context 0x1
------------------------------------------------------
warning: Note: command wine vc_redist.x86.exe returned status 84. Aborting.
`
Is the problem from date? or what and if it already from Timezone how to fix that

**Comment by Chiitoo** [comment]
> Is the problem from date? or what and if it already from Timezone how to fix that

Most likely something like that...

> Using winetricks 20210206

That is pretty old.  : ]

You can download Winetricks in its most recent state here:

https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

Then 'cd' to the directory in a terminal, and run it from there:

``` shell
sh winetricks vcrun2015
```

Or without the 'vcrun2015' if you want to use the GUI.

Closing as obsolete due to the old version.

Feel free to re-open if the problem persists after trying with the most recent changes applied, as the problem might of course be something new or unresolved still.

Thank you!
