### ISSUE TITLE
How to select a different mirror?

### ISSUE THREAD

**Issue by RPMYT** [Winetricks/winetricks#2162]
The default `holarse-linuxgaming.de` has _incredibly_ slow download speed - on the order of <50kb/s.
How do I force it to use a better one?

FWIW verb is `dxvk` which in turn downloads `directx9` even if previously installed.

**Comment by austin987** [comment]
There's no support for this. If you know of a different server that has the file you need, you can either manually edit winetricks to use that URL, or download the artifacts yourself and put it in the appropriate place in `~/.cache/winetricks`.
