### ISSUE TITLE
vcrun6sp6 borked, fails

### ISSUE THREAD

**Issue by Baerbeisser** [Winetricks/winetricks#2167]
This vcrun seem(ed) to be needed to make kenshi run in wine.

[winetricks.log](https://github.com/Winetricks/winetricks/files/13851215/winetricks.log)

**Comment by austin987** [comment]
> warning: You are running winetricks-20230212, latest upstream is winetricks-20240105!

Please upgrade to the latest release before reporting issues.

**Comment by Baerbeisser** [comment]
Done, installation still fails. Same for vcrun 2010 (error 96) btw.
Ignore the proton-ge warning, i'm using wine here.
[winetricks-1.log](https://github.com/Winetricks/winetricks/files/13862861/winetricks-1.log)

Why was this closed?

**Comment by Chiitoo** [comment]
I can not re-produce this behaviour here.

What is your `cabextract` version and source for it, and what shell are you using?

While `cabextract --help` does state

```
Usage: cabextract [options] [-d dir] <cabinet file(s)>
```

it does still work for me in the order Winetricks uses it (version 1.11 from https://www.cabextract.org.uk/).

**Comment by Chiitoo** [comment]
It is quite mysterious since it works for me both, manually used like it is in Winetricks, and via Winetricks itself.  >.<

**Comment by Baerbeisser** [comment]
Well, since the manpage says
`cabextract [-ddir] [-eencoding] [-f] [-Fpattern] [-h] [-i] [-k] [-l] [-L] [-n] [-p] [-q] [-s] [-t] [-v]  cabinet files ...`
translation: `cabextract [options] exe`
i say, better go with that.
Might affect other scripts as well.

**Comment by austin987** [comment]
Nice find, thanks @Baerbeisser. Just to verify, https://github.com/austin987/winetricks/commit/ec809c4c6fc01e15c9997a32d10a95265c81630a fixes this for you, right?

There are definitely other offenders, if that's the issue. I also have cabextract-1.11 (on debian) and either way works. Interestingly, the Arch package doesn't seem to be applying a custom patch: https://gitlab.archlinux.org/archlinux/packaging/packages/cabextract/-/blob/main/PKGBUILD?ref_type=heads

I'm going to try the Arch VM from https://www.osboxes.org/arch-linux/, hopefully that can reproduce it..

**Comment by Baerbeisser** [comment]
> Just to verify, austin987@ec809c4 fixes this for you, right?

Yes, looks like. Thanks for digging!

Btw, how to update winetricks installer scripts? I used the wget line from the frontpage to get the uptodate binary but that's only the binary.

**Comment by austin987** [comment]
> Btw, how to update winetricks installer scripts? I used the wget line from the frontpage to get the uptodate binary but that's _only_ the binary.

I'm not sure what installer scripts you're referring to. If you clone the repo you could use the Makefile, but there's not an installer script, per se. Most of the other files in the repo are for development (aside from the manpage/bash completion, which aren't updated very frequently).

**Comment by Baerbeisser** [comment]
The script/definitions winetricks uses to know where to get VS6SP6.EXE, what to do with it, etc.

**Comment by austin987** [comment]
Yup.

**Comment by Baerbeisser** [comment]
Wow. :)

Well, i downloaded winetricks again
`curl https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -o $XDG_BIN_HOME/winetricks`
and tried `winetricks vcrun6sp6` in a fresh prefix but i still get the cabextract error.
