### ISSUE TITLE
dotnet35 is broken in wine/winetricks

### ISSUE THREAD

**Issue by caiot5** [Winetricks/winetricks#2169]
Regarding bug #1860 , dotnet is not broken on proton, it is broken in wine and winetricks is not capable of installing it. 
Have already tried creating a fresh wineprefix and nothing helped. I have the same kind of error that the guy from the #1860 had.

"0154:err:msi:execute_script Execution of script 2 halted; action L"[\"C:\\windows\\Microsoft.NET\\Framework64\\v2.0.50727\\RegSvcs.exe\" /bootstrapu;14<=>S-1-5-21-0-0-0-1000<=>{C09FB3CD-3D0C-3F2D-899A-6A1D67F2073F}]CA_ComregEnterpriseServicesRB.3643236F_FC70_11D3_A536_0090278A1BB8" returned 1603"

**Comment by austin987** [comment]
Please attach the full terminal output.

**Comment by caiot5** [comment]
Attached
[das-terminal-output.txt](https://github.com/Winetricks/winetricks/files/13894822/das-terminal-output.txt)

**Comment by austin987** [comment]
That's not a clean WINEPREFIX

**Comment by caiot5** [comment]
Ok, I told that I tried ALSO in a clean wineprefix but if you won't take my word for granted, here's the log of it.
[das-clean-wineprefix.txt](https://github.com/Winetricks/winetricks/files/13894899/das-clean-wineprefix.txt)

**Comment by austin987** [comment]
> Ok, I told that I tried ALSO in a clean wineprefix but if you won't take my word for granted, here's the log of it. [das-clean-wineprefix.txt](https://github.com/Winetricks/winetricks/files/13894899/das-clean-wineprefix.txt)

There's no need to be snarky. It's not a matter of 'your word', the output could change. Anyway, I can't exactly take you at your word, since your bug report says 'dotnet35' is broken, but you're clearly installing 'dotnet35sp1'.

Your second log is using root, not a normal user (though I don't think that's the issue).

You're using a 2 year old of winetricks, update to latest. I can't reproduce this in latest with wine-8.0/wine-8.0.2/wine-9.0-rc4.

**Comment by caiot5** [comment]
Yes, I already tried it with a regular user before I tried with root, so that's also not a matter of privileges of whatsoever.
Regarding the dotnet35, I didn't knew that it would be any difference between regular dotnet35 or sp1 installation, but, yes I have tried with just the dotnet35sp1, not the regular one, I can test that for sure but regarding the newer versions, it doesn't seems that any update for winetricks is available for me using the same repositories that I'm using at the momment, I will look into that.

**Comment by caiot5** [comment]
Unfortunately, it didn't worked... Even with the latest version I found, the error persists.
[DAS-NEW-VER.txt](https://github.com/Winetricks/winetricks/files/13931885/DAS-NEW-VER.txt)

**Comment by austin987** [comment]
> Unfortunately, it didn't worked... Even with the latest version I found, the error persists. [DAS-NEW-VER.txt](https://github.com/Winetricks/winetricks/files/13931885/DAS-NEW-VER.txt)

You're still using your broken WINEPREFIX.

**Comment by caiot5** [comment]
Hey man, you don't like me to be snarky but hey... You're simply wrong my man.
Did you noticed the line below? 
wine: created the configuration directory '/home/t5/.vsphere'

That's a brand new WINEPREFIX my man, I don't know why you're so doubtful of the people, you did that with that other guy that reported and now you're doing with me but come on... 
If you want me to do anything else, type the commands man and I will be glad to copy and paste it on my system so you will be sure that I'm not making anything up okay? Can we proceed that way? We are not going to get any progress here by you denying everyone else's test.

**Comment by caiot5** [comment]
If you're referring to the line below regarding the wineprefix on ~/.wine , even after setting the ENV_VAR of a brand new wineprefix like you could see at the line that I highlighted in the previous comment, it still complains about other processes running on this other WINEPREFIX, but I have not changed the ENV_VAR. It might even be another bug to behave this way because I made sure that the VAR WINEPREFIX was set to ~/.vsphere , which was a brand new prefix.

**Comment by caiot5** [comment]
Looks like it succeeded.... 
Something is definitely wrong with my current wineprefix.
Thanks.

**Comment by austin987** [comment]
Please avoid editing comments (aside from typos/minor edits). I generally read the comments from email, and it's very confusing when they don't match what's on the site.

> Looks like it succeeded.... Something is definitely wrong with my current wineprefix. Thanks.

As I said :). Maybe don't doubt me next time, especially when the logs clearly show it ;).

**Comment by austin987** [comment]
> EDIT: I tried to set the WINEPREFIX VAR, but now I see that winetricks needs me to do it explicitly (it doesn't read the WINEPREFIX variable, is it expected?) I will test again specifying explicitly and (I will) bring back the results.

You either need to set it on the same command line as winetricks, or use 'export'.
