### ISSUE TITLE
.cache/winetricks/d3dcompiler_47/FirefoxSetup62.0.3-win64.exe: Win.Virus.Expiro-9947081-0 FOUND

### ISSUE THREAD

**Issue by Yanestra** [Winetricks/winetricks#2170]
ClamAV found these two files, and if they actually belong to winetricks, somebody should check the download URL. On Virustotal, only Jiangmin also detects these as Trojan.PSW.MSIL.cvwv.

.cache/winetricks/d3dcompiler_47/FirefoxSetup62.0.3-win64.exe: Win.Virus.Expiro-9947081-0 FOUND
.cache/winetricks/d3dcompiler_47/FirefoxSetup62.0.3-win32.exe: Win.Virus.Expiro-9947081-0 FOUND

**Comment by austin987** [comment]
They came directly from Mozilla:
https://github.com/Winetricks/winetricks/commit/07c6d38913433c6318c4d5358ea75987b9a419f1

It's likely a false positive, but if not, should be reported to Mozilla.
