### ISSUE TITLE
Can't install dotnet46

### ISSUE THREAD

**Issue by rraphii** [Winetricks/winetricks#2196]
Hi Everyone,

I installed brew and wintricks successfully (at least I hope) but I can install dotnet using "winetricks -q dotnet46"

I get the following errors:

/opt/homebrew/bin/winetricks: line 5722: dirname: command not found
/opt/homebrew/bin/winetricks: line 5738: grep: command not found
/opt/homebrew/bin/winetricks: line 5738: grep: command not found
/opt/homebrew/bin/winetricks: line 5300: id: command not found
/opt/homebrew/bin/winetricks: line 5306: rm: command not found
/opt/homebrew/bin/winetricks: line 635: mkdir: command not found

appreciate any help, since I have no idea what I'm doing. (btw. using ventura 13.5 on m1pro)

**Comment by scroll44** [comment]
Good evening,

I read on the internet that vc_redist.x86.exe (vcrun family) requires wine32 to run.

I tried to install wine, wine32 and wine64 which were not installed on my computer. Wine and Wine64 are in conflict.

So I installed wine and wine32.

Well, vcrun2019 installed without any problem.

Perhaps a solution for you ...

**Comment by austin987** [comment]
As @Gcenx said; this is clearly a problem with your setup. Basic POSIX commands are missing from your $PATH.
