### ISSUE TITLE
A powershell verb would be nice

### ISSUE THREAD

**Issue by DarkShadow44** [Winetricks/winetricks#2201]
Seeing how some programs depend on powershell being present, it would be nice if that would be installable with winetricks.

Not sure how doable the native powershell is, but maybe something like [powershell-wrapper-for-wine](https://github.com/PietJankbal/powershell-wrapper-for-wine) that uses pwsh (powershell core) could be useful.

**Comment by ProjectSynchro** [comment]
I forked this repository for fun and worked it into some custom winetricks verbs if anyone is interested in trying it out:
https://github.com/projectsynchro/powershell-wrapper-for-wine

I looked into how to remove the dependency on ComEmu, however with [winebug 49780](https://bugs.winehq.org/show_bug.cgi?id=49780) still being around, PowerShell Core will output a lot of garbase ANSI colour values that wineconsole doesn't support (but reports that it does). If you run pwsh.exe directly in a newer console like Konsole, the colour values are at least displayed correctly.

Additionally, Powershell Core does support [`NO_COLOR`](https://no-color.org/), however not all parts of powershell seem to respect it. See: https://github.com/PowerShell/PowerShell/issues/21160 and https://github.com/PowerShell/PSReadLine/issues/3918.

I think we can get around the issues in PSReadLine by outright removing the troublesome module.

Let me know if any of this is wanted upstream and I can drop a PR.

**Comment by ProjectSynchro** [comment]
See progress on this here: https://github.com/Winetricks/winetricks/pull/2211

**Comment by ProjectSynchro** [comment]
This should be available on the master branch now (as of https://github.com/Winetricks/winetricks/commit/eeaed1f4651a4b19d56891e588a881936ea7a159).

**Comment by DarkShadow44** [comment]
Cool, thanks!
