### ISSUE TITLE
Can not select a prefix

### ISSUE THREAD

**Issue by u0-a63** [Winetricks/winetricks#2212]
Hi,

Whenever I try to select a prefix in Winetricks (I'm using Debian 12.5.0, fully updated)  it gives me this error: `warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "" `.

How do I fix this?

**Comment by greisch** [comment]
Same problem in Debian SID using wine 9.0~repack-4
winetricks in old versions of wine use "wine64" when WINEARCH=win64 is detected ; but in this version of wine there is no more "wine64" program, and instead a only one "wine" program. wintricks adds code to detect this case but for some reason its fail....

work around:
$ WINE64=wine winetricks

**Comment by greisch** [comment]
See #2035 
Debian use a wrapper script "wine" that run /usr/lib/wine/wine (ELF 32bits) or /usr/lib/wine/wine64 (ELF 64bits)

**Comment by jre-wine** [comment]
Thanks for the workaround @greisch, I didn't think about that yet! You may optimize it to:
`WINE64=/usr/lib/wine/wine64 winetricks`

**Comment by austin987** [comment]
Can you try this with current winetricks (from git). I believe @jre-wine fixed this a while back.

**Comment by greisch** [comment]
fixed in 13becaf04fd630cc386c43e9eb943f16b2f2c035 by @jre-wine 
and still works in last commit in branch master
Tested in Debian sid
