### ISSUE TITLE
Problems installing Steam with winetricks in a fresh prefix using wine 9.7

### ISSUE THREAD

**Issue by tapwag** [Winetricks/winetricks#2216]
Hello everyone from Germany,

I originally wanted to reproduce a wine bug happening with mouse input in Unity-based games and started a wine 9.7 installation on my Slackware 9.7 box and did a 

# winetricks --self-update 

which also worked fine.

I then created a directory

mkdir /home/mwagner/WineApps/Steam

and did an

EXPORT WINEPREFIX=/home/mwagner/WineApps/Steam

in the same console before I ran

winetricks steam

Font-installation and Steam-Update seamed to run fine but I couldn't get to the login menu and had the impression that the process resulted in an endless loop so I had to abort the process.

I also had a look in the AppDB but the latest report was from wine version 7.15.

Would you mind looking into this please?

**Comment by tapwag** [comment]
20240105-next - sha256sum: 18dd9047ec70d923f1990531a11a3d388476bd8825dacb241f618fe3a0e6d1bb

**Comment by austin987** [comment]
I can confirm that Steam is broken in wine-9.7 (works for me in wine-9.0). This isn't a winetricks issue though, it should be reported upstream at https://bugs.winehq.org.

Since it's a regression, it would be helpful if you could run a regression test:
https://wiki.winehq.org/Regression_Testing

**Comment by tapwag** [comment]
Thanks for reproducing @austin987 - it encouraged me to post this bug on wine's bugzilla at: https://bugs.winehq.org/show_bug.cgi?id=56624 - it has also been confirmed in the meantime. Thanks again!
