### ISSUE TITLE
Add framework 2.0 64bit to winetricks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#222]
```
Please, I have a wine 64bit installation and i can´t install framework 32bit 
in winetricks. Can you add 64bit to winetricks?
Thanks you
```

Original issue reported on code.google.com by `pompir...@gmail.com` on 23 Jun 2012 at 12:35
- Blocking: #210

**Comment by qwertychouskie** [comment]
Did this patch ever get merged?  If not, can it be?

**Comment by austin987** [comment]
It did not. It can't currently, as it's broken/can't really be tested (it's an outstanding wine bug).

**Comment by austin987** [comment]
https://bugs.winehq.org/show_bug.cgi?id=24196 was fixed in 1.7.2 (a long time ago), this needs to be rechecked.

**Comment by ryao** [comment]
@austin987 We still need this. I had to install .NET 2.0 from `http://download.microsoft.com/download/a/3/f/a3f1bf98-18f3-4036-9b68-8e6de530ce0a/NetFx64.exe` for ValveSoftware/Proton#17.

**Comment by ryao** [comment]
@austin987 Sorry for not getting back to you sooner, but this seems to work fine.

**Comment by gverm** [comment]
@austin987 Any chance of that getting merged? It would help to make some games (e.g. The Sims 3) usable in a 64bit prefix.
