### ISSUE TITLE
Error 404 when downloading fonts-opensymbol_102.12+LibO24.2.0-1~bpo12+1_all.deb

### ISSUE THREAD

**Issue by alexhenrie** [Winetricks/winetricks#2236]
[`winetricks opensymbol`](https://github.com/Winetricks/winetricks/blob/e4dcd5fe2895ea823ec59e0f8224c1701576fdd8/src/winetricks#L15214) depends on [fonts-opensymbol_102.12+LibO24.2.0-1~bpo12+1_all.deb](http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.12+LibO24.2.0-1~bpo12+1_all.deb), which is no longer available. There are several newer versions available at <http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/>, any of which would be fine:

* [fonts-opensymbol_102.12+LibO24.2.3-1~bpo12+1_all.deb](http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.12+LibO24.2.3-1~bpo12+1_all.deb)
* [fonts-opensymbol_102.12+LibO24.2.3-2_all.deb](http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.12+LibO24.2.3-2_all.deb)
* [fonts-opensymbol_102.12+LibO24.2.4-1_all.deb](http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.12+LibO24.2.4-1_all.deb)
* [fonts-opensymbol_102.12+LibO24.8.0~alpha1-1_all.deb](http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.12+LibO24.8.0~alpha1-1_all.deb)

**Comment by jre-wine** [comment]
All these links will be invalid sometime in the future if the package itself gets an update or if the whole Debian release reaches its end of life. I don't know if it's more important to have the current version of these fonts (then stick with your links) or to have URLs that are stable permanently. For the latter there are 2 options:

When Debian releases reach their end of life they are archived at https://archive.debian.org. The latest version of fonts-opensymbol I found there is https://archive.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.11+LibO7.0.4-4+deb11u4~bpo10+1_all.deb

And there's a snapshot service at https://snapshot.debian.org/ where you may search for a binary package name. So I found the exact version of fonts-opensymbol:
https://snapshot.debian.org/archive/debian/20240206T163351Z/pool/main/libr/libreoffice/fonts-opensymbol_102.12%2BLibO24.2.0-1~bpo12%2B1_all.deb
The snapshot service had some issues lately, but afaik only for adding new snapshots, not for delivering them. So it still should be fine for winetricks' use case.

**Comment by kenorb** [comment]
```
Downloading https://web.archive.org/web/2000/http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.12+LibO7.6.4~rc1-1~bpo12+1_all.deb to /root/.cache/winetricks/opensymbol
------------------------------------------------------
warning: Downloading https://web.archive.org/web/2000/http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.12+LibO7.6.4~rc1-1~bpo12+1_all.deb failed
```

```
$ curl -I https://web.archive.org/web/2000/http://ftp.us.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.12+LibO7.6.4~rc1-1~bpo12+1_all.deb
HTTP/2 503 
```

**Comment by austin987** [comment]
> When Debian releases reach their end of life they are archived at https://archive.debian.org. The latest version of fonts-opensymbol I found there is https://archive.debian.org/debian/pool/main/libr/libreoffice/fonts-opensymbol_102.11+LibO7.0.4-4+deb11u4~bpo10+1_all.deb

Nice find, I think for winetricks use case, the older release is likely fine.
