### ISSUE TITLE
Switch to curl by default?

### ISSUE THREAD

**Issue by shmerl** [Winetricks/winetricks#2245]
`wget` keeps creating stuff in home directory like its history file instead of following XDG base dirs spec. curl doesn't do it and would be a cleaner downloader tool.

They now even ship a `wcurl` script that simplifies its usage for simple wget like downloading, but you can as well use it with same parameters directly.

**Comment by austin987** [comment]
You can adjust your default download tool by setting WINETRICKS_DOWNLOADER=curl, if you prefer that.

Personally I don't think a dotfile is a reason to change the defaults for everyone.
