### ISSUE TITLE
Samsung Remote Studio App

### ISSUE THREAD

**Issue by amvzo** [Winetricks/winetricks#2249]
Hello,

I am trying to get the Samsung Remote Studio App made for windows, running and working on Mac. I have been successful in installing wine and getting the app up and running. But I have not been able to get it to recognize the camera through USB which is something it would be able to do inside of Windows. This would allow the sort of screen capture of the video output of the camera to potentially use with OBS software. I was hoping it would work but it seems to just not detect the camera. 

Any idea as to what would be preventing the app from working in full functionality? I have tried various options in wine tricks but have not really been able to narrow any DLL that would help make it work. 

Any help would be greatly appreciated. 

Here is the app on question 
It also uses this secondary app called ilauncher to work.

https://nxfiles.nx.tc/files/Software-Windows/SamsungRemoteStudio/

https://nxfiles.nx.tc/files/Software-Windows/iLauncher/

**Comment by austin987** [comment]
This isn't a winetricks issue. For support with Wine itself, use https://forums.winehq.org/ or https://appdb.winehq.org/
