### ISSUE TITLE
hi again, it seems installing directshow from wientricks is having issues. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [Winetricks/winetricks#2251]
it gives me this error: Note: command cabextract -q -d /home/talion117/.wine32/dosdevices/c:/windows/temp -L -F x86_microsoft-windows-directshow-other_31bf3856ad364e35_6.1.7601.17514_none_0f58f1e53efca91e/amstream.dll /home/talion117/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe returned status 1. Aborting.

how do you sovle this?

**Comment by austin987** [comment]
Please attach the full output.

**Comment by DOOMMARINE117** [comment]
> Please attach the full output.

where do i find that?

**Comment by austin987** [comment]
Open a terminal, then run:
$ winetricks -q directshow &> log.txt

Then attach log.txt here.

**Comment by DOOMMARINE117** [comment]
[Uploading log.txt…]()

**Comment by DOOMMARINE117** [comment]
[log.txt](https://github.com/user-attachments/files/16464400/log.txt)

**Comment by austin987** [comment]
From that output, it looks like something interrupted the process:
```
    50K .......... .......... .......... .......... ..........  0%  938K 23m59s
   100K .......... .......... .....
SIGHUP received.Hangup

Redirecting output to ‘wget-log’.
```

**Comment by DOOMMARINE117** [comment]
> From that output, it looks like something interrupted the process:
> 
> ```
>     50K .......... .......... .......... .......... ..........  0%  938K 23m59s
>    100K .......... .......... .....
> SIGHUP received.Hangup
> 
> Redirecting output to ‘wget-log’.
> ```

thoguht so, i was trying to figure dit out why it wont install. it did once before. now i cant. my arch distro im using is corrupted. but things still work. many programs ar ein conflict. 

i wonder what interupted the first time?

**Comment by DOOMMARINE117** [comment]
though alot of the corruption was my fault installed kde discover on gnome distro, lol. lesson learned, lol.

**Comment by DOOMMARINE117** [comment]
So what to do?

**Comment by austin987** [comment]
If your system is corrupted, you need to fix that. I'd suggest asking on an Arch support forum.

**Comment by DOOMMARINE117** [comment]
> If your system is corrupted, you need to fix that. I'd suggest asking on an Arch support forum.

could that be causing the wientricks cabextract issue?cause i dont really know what to do at this point.

**Comment by DOOMMARINE117** [comment]
plus, i already tried explaining once on the distro i used for octopi packages. they didnt believe me.

**Comment by DOOMMARINE117** [comment]
what can i do to fix cab extract and winetricks issue? at least i can try and fix that. but, i need to know how to do that.

**Comment by Chiitoo** [comment]
So far there does not seem to be a Winetricks or a cab extract issue here.

If you re-try and you still get the same output, could try the steps manually in a terminal emulator:

```
cd /home/talion117/.cache/winetricks/win7sp1
```

then

```
wget "http://download.windowsupdate.com/msdownload/update/software/svpk/2011/02/windows6.1-kb976932-x64_74865ef2562006e51d7f9333b4a8d45b7a749dab.exe"
```

**Comment by DOOMMARINE117** [comment]
> So far there does not seem to be a Winetricks or a cab extract issue here.
> 
> If you re-try and you still get the same output, could try the steps manually in a terminal emulator:
> 
> ```
> cd /home/talion117/.cache/winetricks/win7sp1
> ```
> 
> then
> 
> ```
> wget "http://download.windowsupdate.com/msdownload/update/software/svpk/2011/02/windows6.1-kb976932-x64_74865ef2562006e51d7f9333b4a8d45b7a749dab.exe"
> ```

i got it downlaod. whats next install it?

**Comment by DOOMMARINE117** [comment]
ok taht worked. awsome thats sovled.

**Comment by DOOMMARINE117** [comment]
what about for xvid?

**Comment by Chiitoo** [comment]
> what about for xvid? how to get d3dx9_24 to d3dx9_43 files? what are they part of?

Perhaps try something like:

```winetricks dlls list```

And then for anything specific you want:

```winetricks d3dx9_43```

**Comment by DOOMMARINE117** [comment]
> > what about for xvid? how to get d3dx9_24 to d3dx9_43 files? what are they part of?
> 
> Perhaps try something like:
> 
> `winetricks dlls list`
> 
> And then for anything specific you want:
> 
> `winetricks d3dx9_43`

got those to install, all ist left is xvid.

**Comment by DOOMMARINE117** [comment]
trying to isntall lord of the rinsg war of the ring rts pc game. says restartizer error? what does taht mean?

**Comment by Chiitoo** [comment]
This is getting a bit off-topic for this issue tracker.  :]

If you have an issue with a specific application, when running it via Wine, I'd suggest you check the Wine AppDB for that application, and if you need help with it, post a comment there, or on the Wine forums.

This place here is for Winetricks things only, really, so I will close this issue at this time.

If you do encounter another issue when using Winetricks, please do open a new issue here!

Thank you!
