### ISSUE TITLE
Cannot update on Bazzite atomic

### ISSUE THREAD

**Issue by ticklemyIP** [Winetricks/winetricks#2257]
I have been having issues with Lutris on Universal Blue's Bazzite OS which is an atomic distro (similar to Fedora Kionite or Silverblue) however running `sudo winetricks --self-update` does not work. Neither does running it as root.

It gives me `warning: You don't have the proper permissions to run this command. Try again with sudo or as root.` error every time

I took the liberty of including bash logs:

```
$ /bin/sh -x $(command -v winetricks)  --self-update
+ WINETRICKS_VERSION=20230212
+ TRUE=0
+ FALSE=1
+ XDG_DATA_HOME=/home/<USERSTRINGSREPLACED>/.local/share
+ XDG_CACHE_HOME=/home/<USERSTRINGSREPLACED>/.cache
+ W_COUNTRY=
+ W_PREFIXES_ROOT=/home/<USERSTRINGSREPLACED>/.local/share/wineprefixes
++ command -v mktemp
+ '[' -x /usr/bin/mktemp ']'
++ mktemp -d /tmp/winetricks.XXXXXXXX
+ W_TMP_EARLY=/tmp/winetricks.lYrA8JTS
+ W_TEXT_LINE=------------------------------------------------------
+ '[' -d /tmp/winetricks.lYrA8JTS ']'
+ '[' -w /tmp/winetricks.lYrA8JTS ']'
+ test ''
++ dirname /usr/bin/winetricks
+ WINETRICKS_SRCDIR=/usr/bin
++ w_try_cd /usr/bin
++ w_try cd /usr/bin
++ export WINEDLLOVERRIDES
++ '[' -z '' ']'
++ printf '%s\n' 'Executing cd /usr/bin'
++ case "$1" in
++ cd /usr/bin
++ status=0
++ en_ms_5='exit status 0 - user selected '\''Cancel'\'''
++ en_ms_105='exit status 0 - normal, user selected '\''restart now'\'''
++ en_ms_194='exit status 0 - normal, user selected '\''restart later'\'''
++ en_ms_236='exit status 0 - newer version detected'
++ en_abort='Note: command cd /usr/bin returned status 0. Aborting.'
++ pl_abort='Informacja: poelcenie cd /usr/bin zwróciło status 0. Przerywam.'
++ pt_abort='Nota: comando cd /usr/bin retornou o status 0. Cancelando.'
++ ru_abort='Важно: команда cd /usr/bin вернула статус 0. Прерывание.'
++ '[' -n '' ']'
++ case ${status} in
++ pwd
+ WINETRICKS_SRCDIR='Executing cd /usr/bin
/usr/bin'
+ WINETRICKS_GUI=none
+ WINETRICKS_OPT_SHAREDPREFIX=1
+ winetricks_handle_option --self-update
+ case "$1" in
+ winetricks_selfupdate
+ winetricks_check_update_availability
+ test -d ../.git
+ test -r /usr/bin/winetricks
+ test -w /usr/bin/winetricks
+ w_warn 'You don'\''t have the proper permissions to run this command. Try again with sudo or as root.'
+ '[' -z '' ']'
+ printf '%s\nwarning: %b\n%s\n' ------------------------------------------------------ 'You don'\''t have the proper permissions to run this command. Try again with sudo or as root.' ------------------------------------------------------
------------------------------------------------------
warning: You don't have the proper permissions to run this command. Try again with sudo or as root.
------------------------------------------------------
+ test ''
+ case ${WINETRICKS_GUI} in
+ unset _W_timeout
+ exit
```

**Comment by austin987** [comment]
Could you attach logs running with sudo?

I suspect that the file isn't writable by root because the distro is atomic..

**Comment by ticklemyIP** [comment]
These are already running with sudo hence the `$`, I just deleted the username and path. I tried sudo and root, neither work. Bazzite.gg is a dedicated gaming focused distro, winetricks wouldn't start because the system is atomic?

**Comment by austin987** [comment]
> These are already running with sudo hence the `$`, I just deleted the username and path. I tried sudo and root, neither work. 

`$ /bin/sh -x $(command -v winetricks)  --self-update`

I don't see sudo there?

> Bazzite.gg is a dedicated gaming focused distro, winetricks wouldn't start because the system is atomic?

I'm not sure, I haven't tested it before and to my knowledge no one has reported on it. But based on the log you provided, the winetricks file isn't writeable, which would cause this to fail.

**Comment by ticklemyIP** [comment]
I don't remember how I copied the output, but trust me I used sudo.

If atomic is causing this, is there a way to work around it, fix it? Nobody, not even Silverblue users reported it before?

**Comment by austin987** [comment]
> I don't remember how I copied the output, but trust me I used sudo.

I'm not trying to gaslight you, but it would be good to retry and explicitly use sudo.

> If atomic is causing this, is there a way to work around it, fix it?

You could try doing:
`$ chmod +w $(which winetricks)`

first, but I'm not sure if atomic distros make /usr/bin writable or not.

> Nobody, not even Silverblue users reported it before?

Not in this issue tracker, maybe they did to Fedora and it wasn't forwarded here.

**Comment by ticklemyIP** [comment]
I will try again in the coming days.

Aug 21, 2024, 00:57 by ***@***.***:

**Comment by austin987** [comment]
I installed Bazzite in a VM to test; the issue is that / and /usr are mounted read only. If you remount /usr as read/write, you can update winetricks, but that obviously defeats the point of using an immutable installation.

**Comment by KyleGospo** [comment]
> I installed Bazzite in a VM to test; the issue is that / and /usr are mounted read only. If you remount /usr as read/write, you can update winetricks, but that obviously defeats the point of using an immutable installation.

I'm the maintainer of this project, popping into confirm you're absolutely correct.

We ship the build of winetricks packaged for the Fedora project, it's a dependency of Lutris which we also ship.
