### ISSUE TITLE
cannot install vcrun2008 afetr i switched from arch to zorin os. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [Winetricks/winetricks#2258]
it gives vcrun2008 install completed, but installed file /home/talion117/.wine/dosdevices/c:/Program Files (x86) (x86)/Common Files/Microsoft Shared/VC/msdia90.dll not found

what you do to fix this error? 

im on zorin os core version. a ubuntu distro. i switched from arch to zorin now. 

what to do?

**Comment by austin987** [comment]
Start by attaching the terminal output, without that, we have no idea what's going on ;).

**Comment by DOOMMARINE117** [comment]
> Start by attaching the terminal output, without that, we have no idea what's going on ;).

where would the output file be again at for zorin os?

**Comment by DOOMMARINE117** [comment]
[winetricks.txt](https://github.com/user-attachments/files/16683662/winetricks.txt)

**Comment by austin987** [comment]
> 0264:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

Can you install winbind and try again? If it still fails, attach a log with `winetricks -q -v`

**Comment by DOOMMARINE117** [comment]
> > 0264:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
> 
> Can you install winbind and try again? If it still fails, attach a log with `winetricks -q -v`

winbin?

**Comment by DOOMMARINE117** [comment]
ok i installed winbind.

**Comment by DOOMMARINE117** [comment]
just realized, i dont ahve wine-gecko and wine-mono. could be that my problem? 

how do i isntall those?

**Comment by DOOMMARINE117** [comment]
got somehow all vcrun can install now. onto vb5run. 

trying to get that to work. kept aborting.

**Comment by DOOMMARINE117** [comment]
how to solve the dxinstall.exe error? i got all the programs from wientricks i need xcept for vb5run.

some reason i cannot install lord of the rings ware of the ring.

it gives me a dxinstall.exe error.

**Comment by DOOMMARINE117** [comment]
[backtrace.txt](https://github.com/user-attachments/files/16706992/backtrace.txt)
