### ISSUE TITLE
i cannot install allfonts. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [Winetricks/winetricks#2270]
the error i get is sha256sum mismatch! Rename /home/talion117/.cache/winetricks/corefonts/andale32.exe and try again. 

how do i fix it? 
[log.txt](https://github.com/user-attachments/files/17037647/log.txt)

**Comment by Chiitoo** [comment]
I don't see the error in the log file, but I do see that the Winetricks version is `20210206`, which is pretty old and will most certainly hit this kind of mismatch issues.

If your package manager does not provide a more recent version, you can download the currently most recent release '20240105' from here:

- https://raw.githubusercontent.com/Winetricks/winetricks/20240105/src/winetricks

Or the current "git master" state here:

- https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

Or you can also try `winetricks --self-update`.

If you continue having issues with an up-to-date version, do open a new issue for it.

Thanks!

**Comment by DOOMMARINE117** [comment]
that seem to worked this time. that never happened before.
