### ISSUE TITLE
ok new issue for vcrun2008. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [Winetricks/winetricks#2271]
her eis a new issue. looks like its related to msdia90.dll. 

[log.txt](https://github.com/user-attachments/files/17048144/log.txt)

**Comment by austin987** [comment]
> 0254:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

Install winbind

> warning: vcrun2008 install completed, but installed file /home/talion117/.wine/dosdevices/c:/Program Files (x86) (x86)/Common Files/Microsoft Shared/VC/msdia90.dll not found

That program files directory is wrong, which is very suspcious.

> Using winetricks 20240105-next - sha256sum: f0edc844169086d7070cc642ab2ed8360d09ce7b2d51739caf0336dee5177d6c with wine-9.0 (Ubuntu 9.0~repack-4+zorin1) and WINEARCH=win64

Not sure what that build is, may be related to the wrong Program Files directory.

**Comment by DOOMMARINE117** [comment]
> > 0254:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
> 
> Install winbind
> 
> > warning: vcrun2008 install completed, but installed file /home/talion117/.wine/dosdevices/c:/Program Files (x86) (x86)/Common Files/Microsoft Shared/VC/msdia90.dll not found
> 
> That program files directory is wrong, which is very suspcious.
> 
> > Using winetricks 20240105-next - sha256sum: f0edc844169086d7070cc642ab2ed8360d09ce7b2d51739caf0336dee5177d6c with wine-9.0 (Ubuntu 9.0~repack-4+zorin1) and WINEARCH=win64
> 
> Not sure what that build is, may be related to the wrong Program Files directory.

that explains the issues. how to fix it?

**Comment by austin987** [comment]
I don't know. I'd start by filing a bug with whoever built the package you're using / trying to compile wine yourself and see if that has the same problem.

**Comment by DOOMMARINE117** [comment]
though i am using zorin os version

**Comment by austin987** [comment]
> though i am using zorin os version

Try reporting the bug there (feel free to link it here).

**Comment by DOOMMARINE117** [comment]
i switched over tp anduin os the i solved.

now i cant install qsaf.dll

**Comment by austin987** [comment]
Please open a new issue for that problem.

Given that no one else has reported issues with it though, I suspect it's something specific to your setup, so may be better to open a bug with your distribution.
