### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by bbkmg256** [Winetricks/winetricks#2281]
I know the problem with "Internet Archive", but is this link wrong or am I wrong?

I mean, there are 2 "https" statements in that link, isn't that right?

![wrong-link](https://github.com/user-attachments/assets/0b1bdf94-84be-4d66-b6e2-19c7723fb322)

**Comment by austin987** [comment]
It's expected. There are several links like that, try `grep http.*archive.org.*http  src/winetricks`

**Comment by bbkmg256** [comment]
Sorry, I just saw that the links used by "archive.org" work like this, I didn't know that hehe
