### ISSUE TITLE
Downloaded vc_redist.x86.exe not matching the hash

### ISSUE THREAD

**Issue by jhuang-concertai** [Winetricks/winetricks#2282]
In function load_vcrun2017()
It is trying to download vc_redist.x86.exe
w_download https://aka.ms/vs/15/release/vc_redist.x86.exe 54ad46ae80984aa48cae6361213692c96b3639e322730d28c7fb93b183c761da

but when I downloaded the same file, 
the hash is 251640E8039D34290133B2C6E3E6FE098E61E2756D5A4C45FDCEC9E4DEE6C187
which is not matching above.
It needs update.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/a06ea8795482d2f49a5461ab5f23e0036e38d12b
