### ISSUE TITLE
warning: wineserver not found!

### ISSUE THREAD

**Issue by JustCauseWhyNot** [Winetricks/winetricks#2283]
I am only seeing `warning: wineserver not found!` when I try to launch winetricks. Both gui, and in cli. I've tried using the live build from the most updated commit through portages live package build, but it didn't change the error I'm getting. I'm not sure what other logs to upload lmk if there are any.

**Comment by JustCauseWhyNot** [comment]
Actually it's fixed now. I think it was fixed by me restarting my pc.

**Comment by Chiitoo** [comment]
Assuming Gentoo Linux, you need to re-log in the user after installing Wine the first time, or run

`source /etc/profile`

or

`. /etc/profile`

to have Wine on the user's PATH.

You should have seen a warning about it from 'eselect-wine' [1] when installing, but I know those are easy to miss.  :]

1. https://gitweb.gentoo.org/repo/gentoo.git/tree/app-eselect/eselect-wine/eselect-wine-2.0.2-r2.ebuild#n72

**Comment by JustCauseWhyNot** [comment]
Appreciate the explanation! Thank you.
