### ISSUE TITLE
Winetricks are not loaded. Can't connect to the internet. MacOS Sequoia

### ISSUE THREAD

**Issue by RHimadiiev** [Winetricks/winetricks#2286]
The message is: Connection to the website failed. The site is either down currently, or there is a problem with your internet connection.

**Comment by austin987** [comment]
Please attach the full output from `winetricks $COMMAND`.

There's a decent chance it's due to the archive.org downtime..

**Comment by RHimadiiev** [comment]
winetricks $COMMAND
warning: taskset/cpuset not available on your platform!


пт, 18 жовт. 2024 р. о 11:14 Austin English ***@***.***> пише:

**Comment by RHimadiiev** [comment]
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
warning: wineserver not found!

**Comment by austin987** [comment]
Sounds like wineserver/wine isn't on your $PATH, Is Wine installed? It needs to be available in $PATH for winetricks to work (or specify the paths via WINE=/path/to/wine winetricks $COMMAND.

**Comment by RHimadiiev** [comment]
> Sounds like wineserver/wine isn't on your $PATH, Is Wine installed? It needs to be available in $PATH for winetricks to work (or specify the paths via WINE=/path/to/wine winetricks $COMMAND. 

I am not an expert in all this. I have Wineskin Winery installed and existing wrappers work fine. But I can't create the new ones because it can't connect to the server. I guess I don't have wine installed

**Comment by austin987** [comment]
I'd suggest reporting it to Wineskin then, I don't know how their packages are set up, or what their wrappers do.
