### ISSUE TITLE
xna40 & vcrun2019 crashing during install

### ISSUE THREAD

**Issue by andwan0** [Winetricks/winetricks#2291]
However I also want to run Red Alert 2 & mod Mental Omega in WINE.

They say I need winetricks:
dotnet40, dotnet45, dotnet452, dotnet46, xna40, cnc_ddraw, directplay and vcrun2019
(because Mental Omega & Red Alert 2 Yuri's Revenge Launcher were written in XNA4)

I can install most winetricks components via virtual desktop (for the installer popups, etc).

The only 2 that crashes winetricks is xna40 & vcrun2019. These 2 I can never seem to install successfully.

XNA4.0 pastebin: https://pastebin.ubuntu.com/p/BZfYDbknHF/

vcrun2019 pastebin: https://pastebin.ubuntu.com/p/fN26MhfqGQ/

**Comment by Chiitoo** [comment]
This appears to be **Protontricks**, not **Winetricks**, and it appears to be using a very out-of-date Winetricks as its source, meaning this is most likely about old file hashes (which the log also suggests).

Perhaps see if you can get Protontricks updated, or try using an up-to-date version of actual Winetricks.

If you have an issue with actual Winetricks, please do open a new issue for that.

Thank you!

**Comment by andwan0** [comment]
Protontricks says it's just a wrapper to winetricks.
Since am on SteamDeck, it's Steam's version of WINE I guess. (I know I can install a separate WINE install...)
Okay, I'll try asking on Steam's forums...

**Comment by Chiitoo** [comment]
Yeah, SteamDeck would most likely normally be using Proton, which uses a fork of Wine, with additional changes on top.

In any case, the issue here most likely is just that the Winetricks being used is from 2023 (from the log: "Using winetricks 20230212-next (protontricks"), and lots of the files have changed since then.
