### ISSUE TITLE
Add exceptions  for 0174:err:winediag:nodrv_CreateWindow

### ISSUE THREAD

**Issue by Zorono** [Winetricks/winetricks#2292]
please add exceptions for the error `0174:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.` since it always fail to install anything when this error occurs (please add option to continue installations in case of any error)

**Comment by zmtong1988** [comment]
Take a look at the graphics card driver

**Comment by austin987** [comment]
@Zorono I'm unclear on the ask here. Could you please give instructions on how to reproduce the issue?

winetricks isn't checking terminal output anywhere that I can recall, so I'm not sure what this bug is about.

**Comment by austin987** [comment]
Not a winetricks issue.
