### ISSUE TITLE
Incorrect vcrun2017 download link?

### ISSUE THREAD

**Issue by innovate-invent** [Winetricks/winetricks#2301]
https://github.com/Winetricks/winetricks/blob/a06ea8795482d2f49a5461ab5f23e0036e38d12b/src/winetricks#L13844

I am trying to sort out a hash validation issue and it looks like this line is downloading vcrun2015 binary by mistake. Is this correct?

**Comment by austin987** [comment]
It's correct, blame Microsoft and their silly naming conventions ;).

If you download and run it, you'll see 2017 in the first window.
