### ISSUE TITLE
Note: Some native vcrun DLLs wont be installed.

### ISSUE THREAD

**Issue by Alexander88207** [Winetricks/winetricks#2309]
Hello,

i just want to point out that verbs like vcrun needs to be tweaked to delete related DLLs that do got versioning in Wine 10 like msvcp140.

Otherwise the installer just skips installing them and the native windows DLLs wont get installed.

**Comment by austin987** [comment]
Linking the relevant wine bug https://bugs.winehq.org/show_bug.cgi?id=57518#c6
