### ISSUE TITLE
tahoma verb broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#247]
```
What steps will reproduce the problem?
1.Open up winetricks, navigate to install a font.
2.Install tahoma.
3.sha1sum mismatch! Caused by 
http://download.microsoft.com/download/office97pro/fonts/1/w95/en-us/tahoma32.ex
e pointing to a non-existent address.

What is the expected output? What do you see instead?
It is supposed to download Tahoma32 but instead it tries to download it from a 
404 webpage.

What version of the product are you using? On what operating system?
The one that came with Wine 1.5, on Ubuntu 12.04 LTS.

Please provide any additional information below.

```

Original issue reported on code.google.com by `Theglues...@gmail.com` on 8 Aug 2012 at 11:38

**Comment by Arek75** [comment]
As of 16 Feb, 2016 the tahoma verb is broken again.  winetricks attempts to download it from ftp://64.4.17.176/Softlib/MSLFILES/tahoma32.exe (yes, by the IP address), which doesn't work (it just hangs trying to connect - it didn't timeout, but it probably would have if I'd left it alone).  I was, however, able to manually download tahoma32.exe from http://download.microsoft.com/download/office97pro/fonts/1/w95/en-us/tahoma32.exe, and place it in ~/.cache/winetricks/tahoma, after which the verb worked fine.

winetricks SHA1: d0ce4d638e882ecbfd72047f8991be4c8df32769
downloaded from https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks earlier today.

**Comment by qwertychouskie** [comment]
It would probably be best to open a new issue, as this is already closed and won't get much attention.
