### ISSUE TITLE
dotnet40 fails in 64 bit prefix

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#272]
```
In quiet mode, dotnet40 currently only works when WINEARCH=win32, ie 32-bit 
prefixes

The error reported by winetricks is "ngen.exe" not found, but there is likely 
more going on.
```

Original issue reported on code.google.com by `YokoZar` on 18 Sep 2012 at 10:33
- Blocking: #210

**Comment by sjuxax** [comment]
DxO Optics Pro will not install in a 32-bit prefix. It requires .NET 4.0+. Is it possible to install a 64-bit dotnet40 via winetricks yet? http://www.dxo.com/us/photography/photo-software/dxo-opticspro

**Comment by austin987** [comment]
No, and not expected anytime soon. It's a long standing upstream issue.

**Comment by qwertychouskie** [comment]
dotnet40 seems to work in a 64-bit prefix now! (With the die-on-64-bit-prefix removed, of course.)

**Comment by austin987** [comment]
On Oct 21, 2016 8:43 PM, "QwertyChouskie" <notifications@github.com> wrote:
>
> dotnet40 seems to work in a 64-bit prefix now! (With the
die-on-64-bit-prefix removed, of course.)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

Any chance you could bisect to find what fixed it?

**Comment by qwertychouskie** [comment]
Looking at https://github.com/Winetricks/winetricks/blame/master/src/winetricks#L6240, I doubt it was a change in Winetricks, but a change in Wine.

**Comment by austin987** [comment]
I realize that, sorry I wasn't clear. I meant bisect wine to figure out what wine commit/version fixed it.

**Comment by Ocirne94** [comment]
> dotnet40 seems to work in a 64-bit prefix now! (With the die-on-64-bit-prefix removed, of course.)
Sounds like a big big improvement to me - any documentation on how for users to actually install it (especially the die-on-64-bit-prefix remove part)?

**Comment by qwertychouskie** [comment]
Just remove [lines 6400-6403](https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L6400), and run `winetricks dotnet40`.  Only tested using the latest Wine staging.

**Comment by simbalion** [comment]
This no longer works. Lines 6400-6403 are changed, and if you try to remove the die function it will throw dozens of errors about missing 32bit things.

It's 2017 and really 64 bit support should be first priority for all things WINE, not second priority.

**Comment by qwertychouskie** [comment]
Now line 6603.

**Comment by qwertychouskie** [comment]
Also, I was using Wine Staging for the tests, it may be a Staging-specific change that allows it to work.

**Comment by simbalion** [comment]
That is the line I tried removing, however it did not result in a successful installation. As I said there were a ton of errors about missing prefixes.

**Comment by austin987** [comment]
On Mar 25, 2017 11:38 AM, "Simba" <notifications@github.com> wrote:

This no longer works. Lines 6400-6403 are changed, and if you try to remove
the die function it will throw dozens of errors about missing 32bit things.

It's 2017 and really 64 bit support should be first priority for all things
WINE, not second priority.


I'm pretty much the only one working on winetricks development at this
point, on a volunteer basis. I'd appreciate it if you didn't dictate my
priorities. With as many users as have been affected, you'd think at least
one would have uploaded a patch, but so far, nothing.

I've got a preliminary patch written, that needs wider testing, I'll try to
upload it next week.

**Comment by simbalion** [comment]
You're awesome, I commend your dedication and service. I would love to help but this is not my expertise, so I apologize. I wonder why more people have not stepped up to help?

**Comment by austin987** [comment]
Please test #757

**Comment by austin987** [comment]
ddf5c7c should fix this.

**Comment by madduci** [comment]
Hi, 
it seems like in Wine 5-stable, dotnet40 doesn't work anymore in 64 Bit.

`Note: command wine dotNetFx40_Full_x86_x64.exe /q /c:install.exe /q returned status 67. Aborting.`

It is unfortunately required by dotnet45 as well.
