### ISSUE TITLE
Install MFC40

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#352]
```
Trying to install MFC40 and I get the following message. Can someone help 
please?

sha1sum mismatch! Rename /home/creid/.cache/winetricks/mfc40/ole2v.exe and try 
again.

Thanks

Charles Reid

```

Original issue reported on code.google.com by `cwre...@gmail.com` on 16 Sep 2013 at 1:24

**Comment by austin987** [comment]
This was already fixed by https://github.com/Winetricks/winetricks/commit/c4a0d31afe6777ca3a85388a890196c41eeda7ee when reported, so this was invalid.
