### ISSUE TITLE
New verb: npp

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#367]
```
Verb for Notepad++

See attached.

```

Original issue reported on code.google.com by `damage3...@gmail.com` on 23 Oct 2013 at 4:48

Attachments:
* [npp.verb](https://storage.googleapis.com/google-code-attachments/winetricks/issue-367/comment-0/npp.verb)

**Comment by austin987** [comment]
Committed an updated version here: https://github.com/Winetricks/winetricks/commit/aab7db809329cdc69e9c0c6cc4b0976b4953e4ca
