### ISSUE TITLE
Cube World winetricks verb

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#436]
```
Hi, I've made a Cube World winetricks verb, I look forward to it being added to 
winetricks. I've attached it below, let me know if it's approved to be added to 
winetricks, thanks.
```

Original issue reported on code.google.com by `alfonsoj...@gmail.com` on 6 Aug 2014 at 7:43

Attachments:
* [cubeworld.verb](https://storage.googleapis.com/google-code-attachments/winetricks/issue-436/comment-0/cubeworld.verb)

**Comment by austin987** [comment]
I'm not going to commit a broken verb..is there a workaround?
