### ISSUE TITLE
Force CLR optimization on .NET to finish so mscorsvw.exe can go away

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#480]
```
What steps will reproduce the problem?
1. dotnet40
2. Start wine
3. Check tasks (top, htop) for mscorsvw.exe

What is the expected output? What do you see instead?
No long-term mscorsvw.exe process when Wine is used after initial .NET 
Framework installation.

What version of the product are you using? On what operating system?
20140302 on Xubuntu 14.04 x86_64

Please provide any additional information below.

http://blogs.msdn.com/b/davidnotario/archive/2005/04/27/what-is-mscorsvw-exe-and
-why-is-it-eating-up-my-cpu-what-is-this-new-clr-optimization-service.aspx

Workaround: .../ngen.exe executequeueditems

Mostly a nuisance problem during app installation troubleshooting or when 
making a backup of a new Wine directory after third-party components are 
installed (before a problematic app install is started).
```

Original issue reported on code.google.com by `jhanso...@gmail.com` on 19 Feb 2015 at 12:08

**Comment by austin987** [comment]
From Google Code Issue 480:
 #3 jhansonxi
(sorry for the late follow-up)

It doesn't appear to work with dotnet40 at least.  I think the command line is the problem.

If I execute "wine ngen.exe executequeueditems" then ngen loads but eventually exits without doing much.

If I execute "wine $WINEPREFIX/drive_c/windows/Microsoft.NET/Framework/v4.0.30319/ngen.exe executequeueditems" then I see a bunch of sub-processes triggered that look like pre-compiling.  Subsequent executions result in it just exiting.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/b61d6a9c781ceafc02f8b6ef3c13775e915e2e3d
