### ISSUE TITLE
Simplified Chinese localization request 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#481]
```
I creat a diff file, can you merge it to winetricks?


```

Original issue reported on code.google.com by `hillwood...@gmail.com` on 19 Feb 2015 at 9:04

Attachments:
* [simplified_Chinese_localization.diff](https://storage.googleapis.com/google-code-attachments/winetricks/issue-481/comment-0/simplified_Chinese_localization.diff)

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/accc7841631dc473b08677a3afb26b6ccec582b7
