### ISSUE TITLE
add verb citavi3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#482]
```
ease the installation of .NET-Software Citavi V 3.4.1 (latest Version 4 doesn't 
run ATM): https://appdb.winehq.org/objectManager.php?sClass=version&iId=31005
by adding new verb citavi3 - see attached diff


```

Original issue reported on code.google.com by `hor...@gmail.com` on 11 Mar 2015 at 7:43

Attachments:
* [citavi3.diff](https://storage.googleapis.com/google-code-attachments/winetricks/issue-482/comment-0/citavi3.diff)

**Comment by austin987** [comment]
I don't think this is useful to enough people to be maintained in winetricks.
