### ISSUE TITLE
Add intro page which explains how to get winetricks

### ISSUE THREAD

**Issue by Beep6581** [Winetricks/winetricks#487]
Is this the new repo of http://www.kegel.com/wine/winetricks or something entirely different? You should create an intro page for https://github.com/Winetricks/winetricks and describe what this is and how to get it.

**Comment by austin987** [comment]
@dankegel, I believe you'll have to, I don't see that capability to me (or upgrade my permissions and I will).

**Comment by slackner** [comment]
@austin987: The intropage can be created by adding a `README` (plain text) or `README.md` (markdown) to the top level directory.  See https://gist.github.com/jxson/1784669 for a minimal example. Just take a look at existing repos, when you see how they do interesting formatting. ;)

Explaination for the markdown format can be found here:
* https://help.github.com/articles/markdown-basics/
* http://tmpvar.com/markdown.html can be used for live preview

**Comment by austin987** [comment]
Fixed by:
https://github.com/Winetricks/winetricks/commit/c047d61f89406682b19edbda5007c739912e2007
and
https://github.com/Winetricks/winetricks/commit/f65bcb320f4b5c831bade7025cfd093fbfdf43b9
