### ISSUE TITLE
Wrong Takao font url

### ISSUE THREAD

**Issue by reedy** [Winetricks/winetricks#489]
winetricks currently uses a url of http://launchpad.net/takao-fonts/003.02/003.02.01/+download/takao-fonts-ttf-003.02.01.zip which gives a 404

From https://launchpad.net/takao-fonts/+download it seems the url is now http://launchpad.net/takao-fonts/trunk/003.02.01/+download/takao-fonts-ttf-003.02.01.zip

Will submit a PR

**Comment by Carbsta** [comment]
issue still doesn't seem fixed as I get the exact same error message, any workaround to install using the new url?

**Comment by qwertychouskie** [comment]
What version of Winetricks?

**Comment by austin987** [comment]
@Carbsta this was fixed nearly two years ago:
https://github.com/Winetricks/winetricks/commit/7a28448deade3dcc17e3d9c6f5e8251775d9c96a
