### ISSUE TITLE
Disable/Remove winetricks isolated prefixes feature

### ISSUE THREAD

**Issue by slackner** [Winetricks/winetricks#494]
Based on my experience and the feedback from other people the "feature" to isolate installed applications from each other is very confusing and should be disabled by default, imho. A couple of reasons why it is useless / counterintuitive:

* When a user passes multiple arguments, then usually he means that they all should be installed into the same prefix - but this is not what happens. Each app gets installed into a separate prefix, and library overrides applied on top of the default prefix.

* Lets assume multiple Wine versions are used in parallel. The default prefix is running with version 1, the user tries to install an isolated app with version 2. This will fail with a wineserver mismatch error, because winetricks always queries information about the default wineprefix (WINEPREFIX variable or ~/.wine), no matter if its actually used later.

* The similar issue also occurs when the user specifies the WINEARCH environment variable, and it doesn't match the architecture of the default prefix (WINEPREFIX or ~/.wine). Winetricks will abort with a "wine: WINEARCH set to win64 but ... is a 32-bit installation." message, although the wineprefix should not be used at all.

* Winetricks doesn't offer any help to run those separately installed applications. People need to have internal knowledge about Winetricks to find out, that it is actually in `~/.local/share/wineprefixes`. To run those applications they have to be aware how to define the `WINEPREFIX` environment variable - but if they know how to do that, they'll also be able to pass it directly to `winetricks`.

I would vote for disabling (or even completely removing) this feature.  I am opening this bug report to collect more opinions and hopefully the majority will agree. ;)

**Comment by deri82** [comment]
+1

**Comment by austin987** [comment]
I'm in favor of removing it (I personally symlink ~/.local/share/wineprefixes to /dev/null, so that if I forget --no-isolate, it bombs out and I'm reminded).

I'd like @dankegel's opinion first though.

**Comment by austin987** [comment]
This is fixed by https://github.com/Winetricks/winetricks/commit/ff3024f169165a81519f0fbae9041545c147f6ff

**Comment by jianguooo** [comment]
你好，我用OSX版本的winetricks生成了同花顺，但是界面上的工具栏是空白的（能点击）。请问要怎么处理才能正常显示？
