### ISSUE TITLE
microsoft FTP IP 64.4.17.176 wont work for me!

### ISSUE THREAD

**Issue by chipotng** [Winetricks/winetricks#499]
The static IP 64.4.17.176 inside the script wont get a connection.
ftp.microsoft.com resolves to 134.170.188.232 and works for me.
Provider: Telecolumbus, Germany

A trace just for Info :)

layer 4 traceroute to ftp.microsoft.com (134.170.188.232), 30 hops max, 60 byte packets
 
sudo lft ftp.microsoft.com -d 21 -H 255
---- internal
 7  cable-62-117-4-11.cust.telecolumbus.net (62.117.4.11)  8.643 ms  9.913 ms
 8  82.82.1.189 (82.82.1.189)  8.573 ms  9.118 ms
 9  92.79.203.157 (92.79.203.157)  20.927 ms  21.048 ms
10  92.79.201.225 (92.79.201.225)  27.628 ms  27.485 ms
11  188.111.129.245 (188.111.129.245)  23.856 ms  23.917 ms
12  92.79.213.138 (92.79.213.138)  23.831 ms  23.363 ms
13  ams-ix-1.microsoft.com (80.249.209.20)  21.790 ms  21.814 ms
14  ae11-0.amb-96cbe-1a.ntwk.msn.net (191.234.81.177)  23.962 ms  23.714 ms
15  ae0-0.amb-96cbe-1b.ntwk.msn.net (207.46.43.203)  24.126 ms  22.929 ms
16  ae4-0.lts-96cbe-1a.ntwk.msn.net (204.152.141.123)  26.178 ms  25.944 ms
17  ae4-0.lon04-96cbe-1a.ntwk.msn.net (191.234.81.154)  27.682 ms  26.940 ms
18  ae11-0.lon04-96cbe-1b.ntwk.msn.net (207.46.44.155)  28.921 ms  28.323 ms
19  191.234.85.31 (191.234.85.31)  95.458 ms ae5-0.atb-96cbe-1a.ntwk.msn.net (207.46.34.84)  113.157 ms
20  ae10-0.was01-96cbe-1c.ntwk.msn.net (191.234.84.138)  102.643 ms  102.301 ms
21  ae2-0.was01-96cbe-1a.ntwk.msn.net (191.234.81.224)  102.384 ms *
22  ae9-0.atb-96cbe-1a.ntwk.msn.net (191.234.84.190)  115.460 ms  114.576 ms
23  ae4-0.lax-96cbe-1a.ntwk.msn.net (191.234.83.150)  158.714 ms ae0-0.atb-96cbe-1b.ntwk.msn.net (191.234.81.167)  113.404 ms
24  * *
25  * *
26  ae2-0.lax-96cbe-1a.ntwk.msn.net (191.234.83.148)  159.300 ms  157.996 ms
27  ae9-0.by2-96c-1a.ntwk.msn.net (207.46.42.176)  167.512 ms  165.559 ms
28  134.170.188.232 (134.170.188.232)  165.317 ms  165.579 ms

sudo lft  64.4.17.176 -d 21 -H 255
---- internal
 7  cable-62-117-4-11.cust.telecolumbus.net (62.117.4.11)  8.094 ms  8.806 ms
 8  82.82.1.189 (82.82.1.189)  8.232 ms  8.580 ms
 9  92.79.203.169 (92.79.203.169)  26.665 ms  24.026 ms
10  92.79.202.49 (92.79.202.49)  28.330 ms  28.464 ms
11  92.79.201.189 (92.79.201.189)  25.543 ms  24.876 ms
12  188.111.129.26 (188.111.129.26)  27.405 ms  26.984 ms
13  ams-ix-1.microsoft.com (80.249.209.20)  25.149 ms  26.489 ms
14  ae17-0.ams-96c-1b.ntwk.msn.net (191.234.84.55)  27.230 ms ae16-0.ams04-96cbe-1b.ntwk.msn.net (191.234.81.188)  27.978 ms
15  ae11-0.amb-96cbe-1b.ntwk.msn.net (191.234.81.179)  27.794 ms  27.190 ms
16  ae3-0.lts-96cbe-1a.ntwk.msn.net (204.152.141.117)  30.457 ms ae10-0.pra-96cbe-1b.ntwk.msn.net (204.152.141.225)  36.515 ms
17  ae5-0.ash-96cbe-1b.ntwk.msn.net (207.46.38.211)  109.109 ms  109.435 ms
18  ae10-0.was01-96cbe-1c.ntwk.msn.net (191.234.84.138)  108.640 ms ae4-0.ash-96cbe-1a.ntwk.msn.net (207.46.36.172)  107.628 ms
19  ae3-0.was01-96cbe-1b.ntwk.msn.net (191.234.81.227)  108.894 ms  109.594 ms
20  204.152.141.181 (204.152.141.181)  108.730 ms  108.042 ms
21  * *
22  * *
23  ae11-0.lax-96cbe-1a.ntwk.msn.net (204.152.141.136)  166.003 ms  171.123 ms
24  * *
25  ae2-0.lax-96cbe-1a.ntwk.msn.net (191.234.83.148)  165.036 ms  166.872 ms
26  ae18-0.bay-96c-1a.ntwk.msn.net (191.234.80.16)  174.887 ms ae8-0.lax-96cbe-1b.ntwk.msn.net (191.234.84.29)  167.976 ms
27  * *
28  * ae19-0.bay-96c-1b.ntwk.msn.net (191.234.81.63)  176.194 ms
29  * *
...
255  * *

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/568fed69102c5de141102259d8259bb39ce82866
