### ISSUE TITLE
"mv: cannot stat" error on failed SHA1 checksum

### ISSUE THREAD

**Issue by tomasstorck** [Winetricks/winetricks#505]
For programs where the SHA1 checksum does not match the provided checksum, an error is returned, likely related to a wrongly concatenated path.

**How to reproduce**
Install a program where the checksum does not match the actual file, such as Steam per issue #502:
```
$ winetricks steam                                                                                                                                                                                     
Executing w_do_call steam
Executing load_steam
------------------------------------------------------
Checksum for /home/tomas/.cache/winetricks/steam//home/tomas/.cache/winetricks/steam/SteamSetup.exe did not match, retrying download
------------------------------------------------------
mv: cannot stat ‘/home/tomas/.cache/winetricks/steam//home/tomas/.cache/winetricks/steam/SteamSetup.exe’: No such file or directory
```

**What was the expected result**
No error should be reported related to a failed "mv".

**What is the actual result**
An error is returned:
```
mv: cannot stat ‘/home/tomas/.cache/winetricks/steam//home/tomas/.cache/winetricks/steam/SteamSetup.exe’: No such file or directory
```
This does not negatively affect the installation of the program. It still fails because of the difference in checksum, as it should.

I have proposed a fix and submitted a pull request (request #504)

**Comment by austin987** [comment]
Merged, thanks.
