### ISSUE TITLE
Small ortographic bug

### ISSUE THREAD

**Issue by WielkiZielonyMelon** [Winetricks/winetricks#508]
When running: winetricks dotnet45

there's an error in Polish translation. There is: Proszę pobrać plik netframework3.exe z http://www.oldversion.com/download-.Net-Framework-3.0.html, następnie umieścić go w /home/melon/.cache/winetricks/dotnet30, a na końcu uruchomić ponownie ten skrytp.

It should be "...ponownie ten skrypt."

**Comment by austin987** [comment]
Fixed by ab5f5a51420c1ed2daef7f9e338839bc5aefbbdb
