### ISSUE TITLE
error checksum DroidSans-Bold.ttf debian 8

### ISSUE THREAD

**Issue by drunkwolfs** [Winetricks/winetricks#511]
Downloading https://github.com/android/platform_frameworks_base/blob/master/data/fonts/DroidSans-Bold.ttf?raw=true to /home/nbome/.cache/winetricks/droid

sha1sum mismatch!  Rename /home/nbome/.cache/winetricks/droid/DroidSans-Bold.ttf and try again.

nbome@amine:~$ winetricks --version
20140817 - sha1sum: fb1d7184dc186313cf26e1a65a8e6ff3c5fadc50

**Comment by austin987** [comment]
> 20140817 - sha1sum: fb1d7184dc186313cf26e1a65a8e6ff3c5fadc50

You're running a very out of date winetricks, invalid.
