### ISSUE TITLE
Issues downloading with aria2

### ISSUE THREAD

**Issue by jashandeep-sohi** [Winetricks/winetricks#524]
I have ``aria2`` installed on my system and make use of it regularly to download stuff, so I appreciate ``winetricks`` supporting it.
I also have a conf file at ``~/.aria2/aria2.conf`` in which I've defined the ``--dir`` option to point to a folder in which all my downloads go. Unfortunately, the way things are right now ``winetricks`` downloads files relative to this folder and then complains when it can't find the file in the folder where it thought it was saving it.

Is there some way to force ``winetricks`` to use ``wget``? Or better yet still use ``aria2`` but ignore the ``--dir`` option?

I'm currently getting around the problem by forcing aria2 to ignore the entire conf by adding ``--no-conf`` to the ``aira2c`` command:
   
    ...
    if [ -x "`which aria2c 2>/dev/null`" ]
         then
             # Basic aria2c support.
             aria2c --no-conf -o "$_W_file" "$_W_url"
    ...

Any better ideas/solutions?

**Comment by ShannonVanWagner** [comment]
Using specific override for the download dir in the command seems like another option. This might help to avoid any other problems that might arise from ignoring the aria2.conf file entirely, e.g., some user-specified proxy settings.
...
if [ -x "`which aria2c 2>/dev/null`" ]
     then
         # Basic aria2c support.
         aria2c -c -d "$_W_cache" -o "$_W_file" "$_W_url"
...

**Comment by austin987** [comment]
Fixed by 4ea5d13370e3c43cae989798d7b96c40f02ecece, thanks Shannon.

**Comment by jashandeep-sohi** [comment]
Thanks for the fix. Probably best to close this now.
