### ISSUE TITLE
share the files between crossover, winetricks and POL avoid duplication

### ISSUE THREAD

**Issue by deri82** [Winetricks/winetricks#535]
I have crossover installed, it downloads files into

username/.cxoffice/installers/

the naming of files is a bit odd. For example steamsetup.exe shows

02b06496faddb50f8a8911566d57117b.SteamSetup.exe

Pol installers are at user/.PlayOnLinux/ressources/

**Comment by austin987** [comment]
I don't think it's appropriate for winetricks to depend on external projects like that (especially when both are consumers of winetricks itself, they could instead use winetricks cached file when available, if they choose).
