### ISSUE TITLE
Provide verb for esent.dll

### ISSUE THREAD

**Issue by tjnycum** [Winetricks/winetricks#538]
esent.dll, the Extensible Storage Engine runtime, is required by CCleaner, for example, but not included in wine. I've gotten CCleaner to work by simply extracting that file from the Win7 SP1 download used by the gdiplus verb and putting it in windows/system32.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/45fa4e7d3b61c1243e8db234017f015eb01c95da, thanks for reporting.
