### ISSUE TITLE
Add the ability to use winetricks within a wine cmd shell

### ISSUE THREAD

**Issue by alesliehughes** [Winetricks/winetricks#540]
If you run winetricks within a wine cmd, It fails to properly setup the WINE and WINEPREFIX variables.

The following check causes the WINE/WINEPREFIX to be cleared
case "$OS" in
"WIndows_NT"
....
...
The main purpose of this is so an application can use winetricks to install any DLL's that it requires to run smoothly.  This for me, would stop users from have to use a console.

**Comment by austin987** [comment]
On Sep 2, 2015 9:47 PM, "Alistair Leslie-Hughes" <notifications@github.com>
wrote:
>
> If you run winetricks within a wine cmd, It fails to properly setup the
WINE and WINEPREFIX variables.
>
> The following check causes the WINE/WINEPREFIX to be cleared
> case "$OS" in
> "WIndows_NT"
> ....
> ...
> The main purpose of this is so an application can use winetricks to
install any DLL's that it requires to run smoothly. This for me, would stop
users from have to use a console.
>
> —
> Reply to this email directly or view it on GitHub.

I'm having trouble seeing a use case for an application to invoke
winetricks itself instead of bundling the dlls it needs. Do you have an
example?

**Comment by alesliehughes** [comment]
>I'm having trouble seeing a use case for an application to invoke winetricks itself instead of bundling > the dlls it needs. Do you have an example?
If an application requires MDAC28, for example, It cannot be installed in a merge module since it requires an windows version <= W2K.  This also applies to dll's like msxml3/4/6 where the merge module thinks that the version installed is good enough, and even if they do overwrite them, builtin is used by default.

**Comment by austin987** [comment]
I'm not clear what you mean by 'merge module'

**Comment by austin987** [comment]
@alesliehughes could you please explain how you're calling winetricks? e.g., how can I reproduce this?

**Comment by alesliehughes** [comment]
I want to have program that uses ShellExecute, to be able to use winetricks to install all dlls requirements that can't be shipped due to license restrictions.

**Comment by austin987** [comment]
Could you try this branch? https://github.com/Winetricks/winetricks/tree/wine-cmd-support

There are likely some bugs, but depending on what verbs you use, they may or may not affect you ;)

**Comment by austin987** [comment]
@alesliehughes ping?

**Comment by alesliehughes** [comment]
I've done some basic testing and it appears to do what I require.

**Comment by austin987** [comment]
Thanks, committed as https://github.com/Winetricks/winetricks/commit/c527086c86625ec6dfc7e534c83ec9d0184a65bc
