### ISSUE TITLE
Installing native XAudio broken since Wine 1.7.51 (updated regsvr32 exitcodes)

### ISSUE THREAD

**Issue by slackner** [Winetricks/winetricks#545]
With a current version of Wine installing `xact` fails:

```
Executing wine regsvr32 xaudio2_8.dll
regsvr32: 'DllRegisterServer' nicht in DLL 'xaudio2_8.dll' implementiert
------------------------------------------------------
Note: command 'wine regsvr32 xaudio2_8.dll' returned status 4.  Aborting.
------------------------------------------------------
```

Exitcode 4 was added in the following commit:
http://source.winehq.org/git/wine.git/patch/68a5642d5c9fce440aa8679614771af93b62034f

It basically means that no registration is required. Winetricks should probably just accept exitcode `4` as success.

Alternatively dlls which do not require a registration should be skipped. Especially loops like the following one are problematic, because they enumerate also builtin dlls:

```
for x in "$W_SYSTEM32_DLLS"/xactengine* "$W_SYSTEM32_DLLS"/xaudio*
```

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/50f28a31a2cdea4d56ff39f093f805390ab4379b

**Comment by Zanzibar82** [comment]
Same problem on wine 1.8

**Comment by austin987** [comment]
@Zanzibar82 ```winetricks --version``` ?

**Comment by MetaiR** [comment]
same problem on `xinput` on wine 2.4
