### ISSUE TITLE
Cannot install corefonts via winetricks due to download location being unreachable

### ISSUE THREAD

**Issue by slyscorpion** [Winetricks/winetricks#555]
I am using the command "winetricks corefonts" and I receive the following in terminal: 

Connecting to surfnet.dl.sourceforge.net (surfnet.dl.sourceforge.net)|130.59.138.21|:80... failed: Connection timed out.
Connecting to surfnet.dl.sourceforge.net (surfnet.dl.sourceforge.net)|2001:620:0:1b::21|:80... failed: Network is unreachable.

I have checked my connection and winetricks is able to pull gdiplus which is approximately 540 MB in size. I am not sure if this is a temporary issue or not but I figured I'd report it here.

According to winetricks --version I am using version 20140302 of winetricks.

**Comment by slyscorpion** [comment]
Fixed with latest version of winetricks and user self-education.

**Comment by hughgrigg** [comment]
For anyone else encountering this, you can get the latest version of winetricks by following the instructions here: https://wiki.winehq.org/Winetricks#Getting_winetricks
