### ISSUE TITLE
vcrun2012/vcrun2013 need 64-bit support

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#559]
Mentioned here https://bugs.winehq.org/show_bug.cgi?id=39181#c3

vcrun2012 also lacks it.

**Comment by austin987** [comment]
Fixed.

**Comment by nyov** [comment]
Sadly the fix in #560 does not work as the 32bit installer fails and winetricks terminates before ever trying the 64bit download.

**Comment by dufferzafar** [comment]
Yeah, I'm facing this issue as well.
