### ISSUE TITLE
winetricks doesn't display shit

### ISSUE THREAD

**Issue by baptistepouget** [Winetricks/winetricks#563]
I don't know which version broke it but winetricks doesn't display any option anymore.
I'm using fedora 22

**Comment by austin987** [comment]
Can't help without any info..screenshot/terminal output/winetricks version? Does command line winetricks work?

**Comment by baptistepouget** [comment]
Yeah sorry, I will try to do that, just need to reboot on linux.
But the window displays correctly but there is nothing to select excepting accept and back at the bottom right if I remember correclty.
About the console an error message about a pixel box or something like that prints sometimes.i give you a screenshot in about 10 minuts

**Comment by baptistepouget** [comment]
![capture d ecran de 2015-10-22 00-23-56](https://cloud.githubusercontent.com/assets/13153084/10652022/6b2e2ad4-7853-11e5-859f-f1f64f91f118.png)
baptiste@fedora-baptiste:~/.wine$ wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
--2015-10-22 00:22:43--  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
Résolution de raw.githubusercontent.com (raw.githubusercontent.com)… 185.31.18.133
Connexion à raw.githubusercontent.com (raw.githubusercontent.com)|185.31.18.133|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 682460 (666K) [text/plain]
Sauvegarde en : « winetricks »

winetricks          100%[=====================>] 666,46K   941KB/s   ds 0,7s   

2015-10-22 00:22:46 (941 KB/s) — « winetricks » sauvegardé [682460/682460]

baptiste@fedora-baptiste:~/.wine$ chmod +x winetricks 
baptiste@fedora-baptiste:~/.wine$ ./winetricks 
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------

(zenity:3107): GLib-GObject-WARNING **: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.

(zenity:3107): GLib-GObject-WARNING **: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

**Comment by baptistepouget** [comment]
Thanks for answering, i'm going to sleep now so if you need additional info, I give them tomorrow :+1:

**Comment by birdie-github** [comment]
It looks like zenity in Fedora was/is broken. This bug has nothing to do with winetricks.

**Comment by austin987** [comment]
Thanks @birdie-github, I suspected that.
