### ISSUE TITLE
Dotnet30 fails to install on 32 bit prefix, Ubuntu

### ISSUE THREAD

**Issue by Adrellisartar** [Winetricks/winetricks#564]
Hello. Did some searching online, and before you moved to Github, this was a problem..that was solved. However, I see to have the problem again.

Using Wine 1.7.50 and Winetricks 205-08-26, by using wget on the Github's link, I cannot get .NET 3.0 to install.

I am trying to install .NET 4.5, so I do that directly. 2.0 installs, then tries 3.0. It fails and says:
Note: command 'wine dotnetfx3.exe' returned status 67.  Aborting.

Well, searching for this, it was fixed!...years ago. But I have it today. Using that Wine and Winetricks.

Steps: 
Add the PPA for Wine into the terminal
Download Wine 1.7.50 by "sudo apt-get install wine1.7". Update and upgrade
wget on the link on the Github to get winetricks
"chmod +x winetricks"
"export WINEARCH=win32"
"./winetricks"
"./winetricks corefonts vcrun6 dotnet45"

Those are my steps. Not used Wine before, but the "solution" dead ends with a past version. And, trying to manually install 3.0 after 2.0, gives the same error. Placing 2.0 SP 1 in between, gives:
"error: dotnet30 conflicts with dotnet20sp1, which is already installed."

I am at a loss. Sorry this is more like a forum post.

**Comment by austin987** [comment]
On Oct 23, 2015 1:07 AM, "Adrellisartar" <notifications@github.com> wrote:
>
> Hello. Did some searching online, and before you moved to Github, this
was a problem..that was solved. However, I see to have the problem again.
>
> Using Wine 1.7.50 and Winetricks 205-08-26, by using wget on the Github's
link, I cannot get .NET 3.0 to install.
>
> I am trying to install .NET 4.5, so I do that directly. 2.0 installs,
then tries 3.0. It fails and says:
> Note: command 'wine dotnetfx3.exe' returned status 67. Aborting.
>
> Well, searching for this, it was fixed!...years ago. But I have it today.
Using that Wine and Winetricks.
>
> Steps:
> Add the PPA for Wine into the terminal
> Download Wine 1.7.50 by "sudo apt-get install wine1.7". Update and upgrade
> wget on the link on the Github to get winetricks
> "chmod +x winetricks"
> "export WINEARCH=win32"
> "./winetricks"
> "./winetricks corefonts vcrun6 dotnet45"
>
> Those are my steps. Not used Wine before, but the "solution" dead ends
with a past version. And, trying to manually install 3.0 after 2.0, gives
the same error. Placing 2.0 SP 1 in between, gives:
> "error: dotnet30 conflicts with dotnet20sp1, which is already installed."
>
> I am at a loss. Sorry this is more like a forum post.
>
> —
> Reply to this email directly or view it on GitHub.

Please post the terminal output with a clean prefix.

**Comment by Gunstick** [comment]
Same problem, even dotnet20 does not install.

$ env|grep WINE
$ 
$ rm -rf ~/.wine
$ winetricks dotnet20
Executing w_do_call dotnet20
Executing load_dotnet20
Executing w_do_call remove_mono
Executing load_remove_mono
------------------------------------------------------
Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call fontfix
Executing load_fontfix
Setting Windows version to win2k
Executing winetricks_early_wine regedit C:\windows\Temp\_dotnet20\set-winver.reg
Current wine does not have wine bug 10467, so not applying workaround
Current wine does not have wine bug 30845, so not applying workaround
------------------------------------------------------
Working around wine bug 30845 -- Using native fusion while installing...
------------------------------------------------------
Executing env WINEDLLOVERRIDES=mscoree,fusion=n wine dotnetfx.exe
fixme:advapi:DecryptFileA "C:\\users\\georges\\Temp\\IXP000.TMP\\" 00000000
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:advapi:LsaOpenPolicy ((null),0x33f310,0x00000001,0x33f2fc) stub
fixme:advapi:LsaClose (0xcafe) stub
fixme:storage:create_storagefile Storage share mode not implemented.
err:msi:msi_load_all_components can't initialize assembly caches
err:msi:msi_load_all_components can't initialize assembly caches
fixme:msi:MsiGetLastErrorRecord 
err:msi:ITERATE_Actions Execution halted, action L"SxsInstallCA" returned 1603
fixme:imm:ImmDisableIME (-1): stub
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
err:ole:CoUninitialize Mismatched CoUninitialize
err:ole:CoUninitialize Mismatched CoUninitialize
------------------------------------------------------
Note: command 'env WINEDLLOVERRIDES=mscoree,fusion=n wine dotnetfx.exe' returned status 67.  Aborting.
------------------------------------------------------

**Comment by austin987** [comment]
On Dec 24, 2015 3:23 PM, "Gunstick" <notifications@github.com> wrote:
>
> Same problem, even dotnet20 does not install.
>
> $ env|grep WINE
> $
> $ rm -rf ~/.wine
> $ winetricks dotnet20
> Executing w_do_call dotnet20
> Executing load_dotnet20
> Executing w_do_call remove_mono
>
> Executing load_remove_mono
> Mono does not appear to be installed.
>
> Executing w_do_call fontfix
> Executing load_fontfix
> Setting Windows version to win2k
> Executing winetricks_early_wine regedit
C:\windows\Temp_dotnet20\set-winver.reg
> Current wine does not have wine bug 10467, so not applying workaround
>
> Current wine does not have wine bug 30845, so not applying workaround
> Working around wine bug 30845 -- Using native fusion while installing...
>
> Executing env WINEDLLOVERRIDES=mscoree,fusion=n wine dotnetfx.exe
> fixme:advapi:DecryptFileA "C:\users\georges\Temp\IXP000.TMP\" 00000000
> err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated.
Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find
it in the winbind package of your distribution.
> fixme:advapi:LsaOpenPolicy ((null),0x33f310,0x00000001,0x33f2fc) stub
> fixme:advapi:LsaClose (0xcafe) stub
> fixme:storage:create_storagefile Storage share mode not implemented.
> err:msi:msi_load_all_components can't initialize assembly caches
> err:msi:msi_load_all_components can't initialize assembly caches
> fixme:msi:MsiGetLastErrorRecord
> err:msi:ITERATE_Actions Execution halted, action L"SxsInstallCA" returned
1603
> fixme:imm:ImmDisableIME (-1): stub
> err:ole:CoInitializeEx Attempt to change threading model of this
apartment from multi-threaded to apartment threaded
> err:ole:CoInitializeEx Attempt to change threading model of this
apartment from multi-threaded to apartment threaded
> fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
> fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
> err:ole:CoUninitialize Mismatched CoUninitialize
>
> err:ole:CoUninitialize Mismatched CoUninitialize
> Note: command 'env WINEDLLOVERRIDES=mscoree,fusion=n wine dotnetfx.exe'
returned status 67. Aborting.

**Comment by austin987** [comment]
Install winbind and retry

**Comment by Gunstick** [comment]
Nope: 
```
$ sudo apt-get install winbind
[...]
The following NEW packages will be installed:
  winbind
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
[...]
[ ok ] Starting the Winbind daemon: winbind.

$ which ntlm_auth
/usr/bin/ntlm_auth

$ ntlm_auth -V
Version 4.0.12-Debian

$ winetricks dotnet20
Executing w_do_call dotnet20
Executing load_dotnet20
Executing w_do_call remove_mono
Executing load_remove_mono
------------------------------------------------------
Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call fontfix
Executing load_fontfix
Setting Windows version to win2k
Executing winetricks_early_wine regedit C:\windows\Temp\_dotnet20\set-winver.reg
Current wine does not have wine bug 10467, so not applying workaround
Current wine does not have wine bug 30845, so not applying workaround
------------------------------------------------------
Working around wine bug 30845 -- Using native fusion while installing...
------------------------------------------------------
Executing env WINEDLLOVERRIDES=mscoree,fusion=n wine dotnetfx.exe
fixme:advapi:DecryptFileA "C:\\users\\georges\\Temp\\IXP000.TMP\\" 00000000
fixme:advapi:LsaOpenPolicy ((null),0x33f310,0x00000001,0x33f2fc) stub
fixme:advapi:LsaClose (0xcafe) stub
fixme:storage:create_storagefile Storage share mode not implemented.
err:msi:msi_load_all_components can't initialize assembly caches
err:msi:msi_load_all_components can't initialize assembly caches
fixme:msi:MsiGetLastErrorRecord 
err:msi:ITERATE_Actions Execution halted, action L"SxsInstallCA" returned 1603
fixme:imm:ImmDisableIME (-1): stub
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
err:ole:CoUninitialize Mismatched CoUninitialize
err:ole:CoUninitialize Mismatched CoUninitialize
------------------------------------------------------
Note: command 'env WINEDLLOVERRIDES=mscoree,fusion=n wine dotnetfx.exe' returned status 67.  Aborting.
------------------------------------------------------
```

**Comment by austin987** [comment]
Is that a clean prefix? It doesn't appear to be.

Wine version?

**Comment by Gunstick** [comment]
You mean to start with an empty ~/.wine?
I did that just before I tried the fist install, then I added winbind and retried the install.

Maybe it's of use to know what I get an "Microsoft .NET Setup" window from wine, but it crashes. "... encountered a problem during setup ..."

**Comment by austin987** [comment]
On Sat, Dec 26, 2015 at 3:04 PM, Gunstick <notifications@github.com> wrote:

> You mean to start with an empty ~/.wine?
>
Yes.

> I did that just before I tried the fist install, then I added winbind and
> retried the install.
>
Ok, but that means the prefix was initialized without winbind. While it
should only be used at runtime, not prefix creation, to be sure I'd like to
see a clean prefix used for testing (that applies to any wine/winetricks
bug).

> Maybe it's of use to know what I get an "Microsoft .NET Setup" window from
> wine, but it crashes. "... encountered a problem during setup ..."
>
Not really, but thanks for the info :). The actual wine version would help,
though. If it's not 1.8 or 1.8.1, please update. Also note that winetricks
has been updated since your original report, make sure you're using the
latest version.

-- 
-Austin

**Comment by next-mad-hatter** [comment]
I experienced same issue with wine 1.8 (x86) and winetricks 20151227 on multilib slackware 14.1.
What worked in the end was `winetricks -q --unattended msxml3 mfc42 dotnet45 corefonts` (did not investigate adding which of the two if not both was instrumental).

**Comment by austin987** [comment]
Probably msxml3, which is used by dotnet35 (but works for me).

What version of lixml2 do you have? It works for me without native:
[austin@localhost ~]$ winetricks --version
20151227 - sha1sum: 3fc2069dc2a865562442b2b10e9a71a073f92675
[austin@localhost ~]$ wine --version
wine-1.8-97-gb30167e
[austin@localhost ~]$ dnf list | grep libxml2
libxml2.i686                             2.9.2-3.fc22                    @System

**Comment by next-mad-hatter** [comment]
winetricks 20151227 - sha1sum: ad565c9abd0b26308b8ace7e6b44fc20f81d2034  (tried before with multiple versions), wine 1.8 (winehq/sg package), libxml 2.9.1 (slackware-14.1/compat32).

Strangely, I cannot reproduce the issue today (`winetricks dotnet45` just works, installs msxml3 along the way) although no component was changed (I might be mistaken, of course).

**Comment by austin987** [comment]
What about testing dotnet20/dotnet30 instead of dotnet45?

**Comment by Fluffkin** [comment]
Possibly related (or further confusion).
I was having errors on installing dotnet30. It was failing on decompressing a file from a D:\ location.
Tried winecfg to delete the D: drive .. and instantly it gets put back (it's a link to my sdd1 partition). That's not winetricks fault, I know. But! After a bit of messing around and cursing...
Unmount sdd1 entirely, re-run the winetricks dotnet30 install, and hey!
Wine *still* makes a dosdevices/d: link to sdd1 even though it's unmounted O.o! But..
Winetricks now makes a new y: drive back to ~/.cache during the install, and it all works correctly.
(Wine 1.9.7 - winetricks-20160329)
Actually, looking back. Unrelated to Gunstick, don't know if related Adrellisartar problem (no info), and possibly why next-mad-hatter found it working one day and not the other.
Anyway. Hope it helps someone!

**Comment by edwin-v** [comment]
There is still a major issue with dotnet30 when installing dotnet45.

On a brand new Ubuntu 16.10 with wine-staging-1.9,21 the following happens:

- Clean wine32 prefix with win7. Wine want to install wine-mono, but I decline.
- Use winetricks and select dotnet45 for a full install of all dependencies.
Problem 1: winetricks keeps spawning windows that mono is not installed. Even though that appear to be a good thing.
- At dotnet3.0 I get a warning that the finish dialog may be hidden.
Problem 2: All I see is a tool tip that you can click away, but no dialog anywhere. It's so hidden, it can't be shown.
- Kill the installer process -> winetricks exits because of an error.
- Restart install with winetricks to continue after dotnet30.
Problem 3: error that dotnet45 in NOT compatible with dotnet20. Uh what? Wasn't that a dependency?

Luckily, there is a workaround. Set wine to a virtual desktop so you get the taskbar icon to open up the window and exit the installer normally. It's probably a good idea to force this while installing dotnet30 because it appears that those tray icons go nowhere these days.

**Comment by austin987** [comment]
-q mode would be an easier workaround.

**Comment by jgedri** [comment]
Trying to install .Net 4.5, this is what happens:
`Executing w_do_call dotnet45
Executing load_dotnet45
Executing w_do_call remove_mono
Executing load_remove_mono
------------------------------------------------------
Mono does not appear to be installed.
------------------------------------------------------
The operation completed successfully
Executing rm -f /home/tiger/.wine/dosdevices/c:/windows/system32/mscoree.dll
Executing w_do_call dotnet35
Executing load_dotnet35
------------------------------------------------------
dotnet35 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
Executing w_do_call dotnet30sp1
Executing load_dotnet30sp1
------------------------------------------------------
dotnet30sp1 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
Executing w_do_call dotnet30
Executing load_dotnet30
------------------------------------------------------
If install fails, set /proc/sys/kernel/yama/ptrace_scope to 0.  See http://bugs.winehq.org/show_bug.cgi?id=30410
------------------------------------------------------
Executing w_do_call dotnet20
dotnet20 already installed, skipping
------------------------------------------------------
Installing .net 3.0 runtime takes 3 minutes on a very fast machine, and the Finished dialog may hide in the taskbar.
------------------------------------------------------
Setting Windows version to winxp
Executing winetricks_early_wine regedit C:\windows\Temp\_dotnet30\set-winver.reg
/usr/bin/winetricks: 1716: test: wine-2.0-rc1: unexpected operator
/usr/bin/winetricks: 1720: test: wine-2.0-rc1: unexpected operator
------------------------------------------------------
Working around wine bug 30845 -- Using native fusion...
------------------------------------------------------
Executing wine netframework3.exe
wine: Bad EXE format for Y:\dotnet30\netframework3.exe.
------------------------------------------------------
Note: command 'wine netframework3.exe' returned status 193.  Aborting.`

Wine is version 2.0~rc1~ubuntu14.04.1 and winetricks is 20140302 (it's a 32-bit system).

**Comment by slyscorpion** [comment]
@jgedri 

>winetricks is 20140302

Your winetricks version is over 2 years old. Please update wintricks to the latest version.

**Comment by jgedri** [comment]
What files do I download? Is there a repository I can add to make things easier?

**Comment by slyscorpion** [comment]
@jgedri  here's how to get the latest version of winetricks on Ubuntu: 

http://askubuntu.com/questions/755059/how-do-i-get-the-latest-version-of-winetricks-on-ubuntu

Once you've done that and you have a newer version you will be able to update winetricks with the 

winetricks --self-update 

command and you will no longer have to worry about repositories and the like :)

**Comment by jgedri** [comment]
Thanks. I'm hoping to get a particular game, "The Aetherlight", to run on
my system, but when I run the installer through Wine it says it failed to
install .Net 4.5. That's why I'm trying to work around the problem with
winetricks.

**Comment by qwertychouskie** [comment]
After updating Winetricks, I would also recommend deleting and re-creating your wineprefix (`~/.wine`).  Also, you could consider upgrading your version of Ubuntu, as some applications don't work right with older versions, e.g. the Lego Mindstorms EV3 software doesn't seem to work on Ubuntu 14.04 for some reason, but newer versions of Ubuntu work.

**Comment by jgedri** [comment]
So I just delete the folder, then run winecfg?

**Comment by qwertychouskie** [comment]
Yes, or `WINEARCH=win32 winecfg` for a 32-bit prefix (recommended if the application supports it).
