### ISSUE TITLE
Update the old winetricks download URL

### ISSUE THREAD

**Issue by boltronics** [Winetricks/winetricks#565]
I've been using Winetricks for years. I have the following in a cron job to update my system once a week with the newest release:

```
#!/bin/bash

declare -r winetricks_bin="${HOME}/opt/winetricks/bin/winetricks"
declare old_md5
declare new_md5

function get_md5()
{
    declare file="${1}"
    md5sum "${file}" | cut -d ' ' -f 1
}

old_md5="$(get_md5 ${winetricks_bin})"
wget -O "${winetricks_bin}" http://winetricks.org/winetricks 
new_md5="$(get_md5 ${winetricks_bin})"

if [ "${old_md5}" != "${new_md5}" ]
then
    echo "Winetricks updated."
else
    echo "No winetricks update."
fi
```

Since this script has always continued to run successfully, I figured that since I haven't been getting updates all year, winetricks simply is no longer under active development. I didn't think too much about it, until https://bugs.winehq.org/show_bug.cgi?id=34643 implied there was something wrong with my development when testing dotnet40 - hard to believe since my entire setup (including Wine 64-bit compilation) is automated.

Eventually I decided to head over to winetricks.org in case there was a fork or something, and to my astonishment I was redirected to this GitHub repository where the master branch was updated just two days ago!

It seems that http://winetricks.org/ returns a 301 redirect to the GitHub project page, but http://winetricks.org/winetricks does not and just returns the old copy of the script. If this were updated to redirect to https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks it would have saved me many hours of confusion.

Please update the URL.

**Comment by HogynCymraeg** [comment]
+1. This is affecting a lot of OSX users as this is the URL used by http://winebottler.kronenberg.org/

**Comment by austin987** [comment]
I don't have access to that, @dankegel, could you update it?

**Comment by austin987** [comment]
This should be done now.
