### ISSUE TITLE
Install Metatrader 4 platform via winetricks

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#572]
I would like to propose headless installation of [Meta Trader 4 platform](https://download.mql5.com/cdn/web/metaquotes.software.corp/mt4/mt4setup.exe) via `winetricks`.

Created [bounty](https://www.bountysource.com/issues/28268472-install-metatrader-4-platform-via-winetricks) of $20.

Here is example how it's done via [`xdotool`](https://github.com/EA31337/FX-MT-VM/blob/master/scripts/install_mt4.sh).

**Comment by austin987** [comment]
Winetricks uses AutoHotKey (w_ahk_do()) for automating GUI tasks, fyi.

I don't really want to add random applications unless they're useful for development or a wide audience. I don't know that I'd consider MetaTrader 4 in either category..

**Comment by kenorb** [comment]
It's one of the most popular FX trading platform and it's published at wine site in:

[Main > Productivity > Finance/Accounting/Project/CRM > MetaTrader > 4.x](https://appdb.winehq.org/objectManager.php?sClass=version&iId=2893)

category with bunch of bugs against it, so I think it's worth to have.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/774a45b6fd22d8b6ea1384144f11b2a1698ee69c

**Comment by kenorb** [comment]
@austin987 Thank you. You may claim the [bounty](https://www.bountysource.com/issues/28268472-install-metatrader-4-platform-via-winetricks).
