### ISSUE TITLE
Visual 2015 C++ - missing DLLS (Workaround/Patch for Winetricks)

### ISSUE THREAD

**Issue by rboxeur** [Winetricks/winetricks#575]
We met this error for vcrun2015 for multiple programs

"Visual Studio 2015-compiled C++ programs do not run (unimplemented function api-ms-win-crt-runtime-l1-1-0.dll._initialize_onexit_table)"

A ticket was opened on winehq bugzilla  https://bugs.winehq.org/show_bug.cgi?id=39437 

Solution/Workaround
=================
Solution is to add missing DLLS through winetricks while installing vcrun2015.  Below (file vcrun2015.txt)  is a patch for winetricks to add missing DLLs while installing vcrun2015

[vcrun2015.txt](https://github.com/Winetricks/winetricks/files/40820/vcrun2015.txt)

How to reproduce this bug?
=====================
1) Install vcrun2015
winetricks -q vcrun2015
2) For example download a nigthly build for PS2 at http://buildbot.orphis.net/pcsx2/ . For example download this versions http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.3.1-1473-gdf87b64&platform=windows-x86 

7z x pcsx2-v1.3.1-1473-gdf87b64-windows-x86.7z 
cd pcsx2-v1.3.1-1473-gdf87b64-windows-x86/
wine pcsx2.exe
And you will get this error.

If patch is applied to winetricks 
patch -p1 < vcrun2015.txt
then reinstall forcing installation 
winetricks --force -q vcrun2015 
and it should OK

**Comment by austin987** [comment]
I committed a modified version of the patch here:
https://github.com/Winetricks/winetricks/commit/d1c5fb28c90b22c05dde44ea6d01ffd1461ce5c1

**Comment by garpu** [comment]
Is this one bugged again? I bought Grim Dawn (uses vcrun2015) on 2/8. 2/15 was the last time I played it.  2/16 it crashed every time I tried playing it.  Maintainer said something changed with the vcredist on 12/2? (I installed vcrun2015 via winetricks, most recent version.)

**Comment by austin987** [comment]
This bug is closed, you should open a separate bug report.

In any case, without any info, I can't say if there's a bug (i.e., wine --version, terminal output, winetricks --version).
