### ISSUE TITLE
Faulty xmllite prereqs

### ISSUE THREAD

**Issue by jhansonxi** [Winetricks/winetricks#579]
Aborts if Windows version is 7 (needs to set WinXP).  ~~Also is not detected by list-installed.~~
20151110 - sha1sum: 6fc9fe96fe632a082e65cd446eff0bf901fe0954

Edit: Detection is working.  Mixed up my multiple WINEPREFIXs.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/ca1a031aeaf9a3c3655b9addf17450055c9d33aa

**Comment by qwertychouskie** [comment]
If this is fixed, why hasn't it been closed?

**Comment by austin987** [comment]
Missed it, thanks.
