### ISSUE TITLE
PATH and ClearType

### ISSUE THREAD

**Issue by evgenyz99** [Winetricks/winetricks#580]
We offer you to make setting the PATH environment variable. You also need create menu for enable font smoothing.

**Comment by austin987** [comment]
Please, one issue per ticket.

I don't understand what your request is about PATH.

**Comment by evgenyz99** [comment]
Environment variable - PATH.

**Comment by austin987** [comment]
Yes, I know what it is. What is the bug about %PATH%?

**Comment by evgenyz99** [comment]
I need to set this with GUI of Winetricks.

**Comment by austin987** [comment]
Use 'regedit' for that, it provides a GUI. I don't think that is something that winetricks should expose to users, it's not commonly edited and the edits are variable per instance, not generic enough to script in most cases (which winetricks already has support for, i.e., adding a path to %PATH%).

I haven't checked if fontsmoothing is supported in the GUI or not. I don't use the GUI and lack time to investigate/fix bugs in it. If you've got a patch I'll review and apply it, however.

**Comment by evgenyz99** [comment]
Well, what about enable ClearType?
