### ISSUE TITLE
ie7 fails to install int wine-1.8.1+

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#582]
After https://source.winehq.org/git/wine.git/commitdiff/bda46cc6fd5fa0f3c9db947108b685533662037a, ie7 fails to install since a newer version is already installed. I tried a few workarounds (attached), but none of that worked.

[ie7.txt](https://github.com/Winetricks/winetricks/files/72803/ie7.txt)

**Comment by AndreRH** [comment]
Hi,
winetricks ie6 seems to work around it, but there are other problems with ie[678] then

**Comment by phcole** [comment]
I wrote a patch to fix this
https://github.com/Winetricks/winetricks/pull/588

**Comment by austin987** [comment]
Fixed by:
50cfa5c
f78602a
f2c7a05
