### ISSUE TITLE
 comctl32 download error

### ISSUE THREAD

**Issue by GregMint62** [Winetricks/winetricks#585]
HI my first post I installed Winetricks to fix Faststone error missing Comctl32. I kept getting SHA1 checksum error and I noticed that nothing had been downloaded and file was 0 bytes after a few tries.

Here is the dead SourceForge link http://surfnet.dl.sourceforge.net/sourceforge/pocmin/Win%2095_98%20Controls/Win%2095_98%20Controls/CC32inst.exe.

Thanks.

**Comment by austin987** [comment]
Thanks, fixed by https://github.com/Winetricks/winetricks/commit/1e91d5c0f2013a2a43b6d572019e544e4babcdd3
