### ISSUE TITLE
Winetricks prefix path via env issue

### ISSUE THREAD

**Issue by Keridos** [Winetricks/winetricks#594]
When you start Winetricks with 

```
WINEPREFIX=/path/to/prefix winetricks
```

and then select another prefix in the GUI (f.ex one from ~/.local/share/wineprefixes) the following happens:
When you try to install something, it installs the files into the prefix set via WINEPREFIX, but tries to find the files (some check after installation?) in the selected prefix and then errors out due to them not being present. Using v. 20160109 commit sha1sum: 6394e6fa9a5353a77fd3ff7cbd71e3d8b7c31612 (cannot find that commit though)

**Comment by austin987** [comment]
How are you selecting another prefix?  I.e., could you please give the list of steps you're running. I think you're probably missing --no-isolate.

See https://github.com/Winetricks/winetricks/issues/494 for more info

**Comment by Keridos** [comment]
I select them in the GUI.

**Comment by austin987** [comment]
On Jan 13, 2016 9:27 AM, "Keridos" <notifications@github.com> wrote:
>
> I select them in the GUI.

I've never used the GUI, so if you want this fixed I'll either need a patch
or clear steps to reproduce (i.e., what buttons to press in what order).
