### ISSUE TITLE
Latest Winetricks does not create new prefix for app installation

### ISSUE THREAD

**Issue by qwertychouskie** [Winetricks/winetricks#596]
The latest version of Winetricks (20160109) does not create a new prefix for app installation.  In older versions it would, but now it won't.

**Comment by eli-schwartz** [comment]
This happened by design, see ff3024f169165a81519f0fbae9041545c147f6ff
(Personally, I like it better this way.)

If you want to create separate wineprefixes for each app, use the `--isolate` switch.

**Comment by qwertychouskie** [comment]
When creating a verb, how do I set that verb to install in an isolated prefix even if --isolate is not specified?  Also, how do I set WINEARCH=win32 for that verb?

**Comment by austin987** [comment]
You couldn't previously, --isolate was required. After https://github.com/Winetricks/winetricks/commit/8988d4fb3da4b4e8adea135a41bd2a51a2526839, you can set WINETRICKS_OPT_SHAREDPREFIX=0 in your environment and it will act as it did before.

To set WINEARCH, put it on the command line before winetricks, e.g.,:
WINEARCH=win32 WINETRICKS_OPT_SHARED_PREFIX=0 winetricks -q firefox

WINEARCH only has effect when a prefix is first created, fyi.

**Comment by qwertychouskie** [comment]
I get:
WINEARCH=win32 WINETRICKS_OPT_SHARED_PREFIX=0 ./winetricks ev3.verb
------------------------------------------------------
wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: WINEARCH set to win32 but '/home/qwerty/.wine' is a 64-bit installation." 
------------------------------------------------------

**Comment by austin987** [comment]
Please open a new issue for that, it's an unrelated issue that I've been
meaning to track down.

On Mon, Jan 25, 2016 at 9:10 PM, qwertychouskie <notifications@github.com>
wrote:

> I get:
> WINEARCH=win32 WINETRICKS_OPT_SHARED_PREFIX=0 ./winetricks ev3.verb wine
> cmd.exe /c echo '%ProgramFiles%' returned empty string, error message
> "wine: WINEARCH set to win32 but '/home/qwerty/.wine' is a 64-bit
> installation."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Winetricks/winetricks/issues/596#issuecomment-174793537>
> .
>



-- 
-Austin
