### ISSUE TITLE
When using WINEARCH=win32 I get wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: WINEARCH set to win32 but '/home/username/.wine' is a 64-bit installation." 

### ISSUE THREAD

**Issue by qwertychouskie** [Winetricks/winetricks#599]
When using WINEARCH=win32 I get:
```
wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: WINEARCH set to win32 but '/home/username/.wine' is a 64-bit installation."
```

**Comment by austin987** [comment]
I think I misread when you originally reported this. Are you trying to set WINEARCH to win32 for an already existing 64-bit prefix? That won't work. WINEARCH only has effect when creating a prefix.

Please paste the full command line you're using

**Comment by qwertychouskie** [comment]
WINEARCH=win32 winetricks --isolate ev3.verb

**Comment by austin987** [comment]
On Jan 30, 2016 6:43 PM, "qwertychouskie" <notifications@github.com> wrote:
>
> WINEARCH=win32 winetricks --isolate ev3.verb
>
> —
> Reply to this email directly or view it on Github.com

Can you paste ev3.verb here please?

**Comment by qwertychouskie** [comment]
w_metadata ev3 apps \
    title="Lego Mindstorms EV3 Home Edition" \
    publisher="Lego" \
    year="2014" \
    media="download" \
    file1="LMS-EV3-WIN32-ENUS-01-01-01-full-setup.exe" \
    installed_exe1="$W_PROGRAMS_X86_WIN/LEGO Software/LEGO MINDSTORMS EV3 Home Edition/MindstormsEV3.exe"

load_ev3()
{
    w_call vcrun2005
    w_call ie8
    w_call dotnet40
    w_download http://esd.lego.com.edgesuite.net/digitaldelivery/mindstorms/6ecda7c2-1189-4816-b2dd-440e22d65814/public/LMS-EV3-WIN32-ENUS-01-01-01-full-setup.exe
    cd "$W_CACHE"/ev3
    w_try "$WINE" LMS-EV3-WIN32-ENUS-01-01-01-full-setup.exe
    w_declare_exe "$W_PROGRAMS_X86_WIN\\LEGO\ Software\\LEGO MINDSTORMS\ EV3\ Home\ Edition" MindstormsEV3.exe
}

**Comment by austin987** [comment]
On Feb 1, 2016 12:39 AM, "qwertychouskie" <notifications@github.com> wrote:
>
> w_metadata ev3 apps \
> title="Lego Mindstorms EV3 Home Edition" \
> publisher="Lego" \
> year="2014" \
> media="download" \
> file1="LMS-EV3-WIN32-ENUS-01-01-01-full-setup.exe" \
> installed_exe1="$W_PROGRAMS_X86_WIN/LEGO Software/LEGO MINDSTORMS EV3
Home Edition/MindstormsEV3.exe"
>
> load_ev3()
> {
> w_call vcrun2005
> w_call ie8
> w_call dotnet40
> w_download
http://esd.lego.com.edgesuite.net/digitaldelivery/mindstorms/6ecda7c2-1189-4816-b2dd-440e22d65814/public/LMS-EV3-WIN32-ENUS-01-01-01-full-setup.exe
> cd "$W_CACHE"/ev3
> w_try "$WINE" LMS-EV3-WIN32-ENUS-01-01-01-full-setup.exe
> w_declare_exe "$W_PROGRAMS_X86_WIN\LEGO\ Software\LEGO MINDSTORMS\ EV3\
Home\ Edition" MindstormsEV3.exe
> }

Thanks,  in currently on vacation but this all help when I get back. I
strongly suspect this is related to using a loaded verb rather than a
builtin one.

To verify, try editing your local winetricks and adding ev3, then call
winetricks ev3 instead of ev3.verb. It will likely work,  assuming you use
--isolate, of course.

**Comment by qwertychouskie** [comment]
Same problem still.  Also, same problem with other built-in verbs, e.g. Abiword.

**Comment by qwertychouskie** [comment]
Also confirmed for old version WINETRICKS_VERSION=20140817

**Comment by austin987** [comment]
I'm now able to reproduce, I'll take a look when I have some free time (the trivial fix I thought might do it did not).

**Comment by austin987** [comment]
[patch.txt](https://github.com/Winetricks/winetricks/files/131970/patch.txt)

This hack fixes the issue whenever --isolate is used, but I need to think about it a bit more before committing.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/6b449c6a5f7172899400262e2bed862fcc059e5d
