### ISSUE TITLE
WindowsXP-KB835935-SP2-ENU.exe failed (--> winetricks crypt32)

### ISSUE THREAD

**Issue by nephilim1973** [Winetricks/winetricks#605]
To reproduce error, do:

winetricks crypt32

Result:

Downloading http://download.microsoft.com/download/1/6/5/165b076b-aaa9-443d-84f0-73cf11fdcdf8/WindowsXP-KB835935-SP2-ENU.exe failed

Related to https://github.com/Winetricks/winetricks/issues/248

**Comment by austin987** [comment]
Fixed by a5e32a8
