### ISSUE TITLE
Visual 2015 C++ - missing DLLS (Workaround/Patch for Winetricks)

### ISSUE THREAD

**Issue by Algor88** [Winetricks/winetricks#607]
With solving Bug #575 some missing dlls has been added to vcrun2015, but still some dlls are missing.
To run Grim Dawn e.g. following dll is missing:
api-ms-win-crt-conio-l1-1-0

I have created a patch file wich adds that dll
run "patch -p1 < [vcrun2015.txt](https://github.com/Winetricks/winetricks/files/137185/vcrun2015.txt)" to apply patch

**Comment by austin987** [comment]
Please send a pull request instead of an attached patch.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/8681123d75382b4a755a4a8b2c4dfea1e3ba2ac7
