### ISSUE TITLE
Winetricks and WINE64

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [Winetricks/winetricks#608]
How to work on it with wine64!!??

**Comment by austin987** [comment]
Same as you do with wine(32). Some verbs won't work, e.g., dotnet11 and others that require a 32-bit prefix. These will abort if you try to install them.

**Comment by Yrij-Zhavoronkov** [comment]
Do you speak Russian?

Same as you do with wine(32)..... no

command: env WINEARCH="win64" WINEPREFIX="......" ./winetricks
wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "wine: '/home/programmeur/.wine64' is a 64-bit installation, it cannot be used with a 32-bit wineserver."

**Comment by austin987** [comment]
I do not.

Please paste the full command line you ran, including WINEPREFIX. Sounds like #599

**Comment by Yrij-Zhavoronkov** [comment]
env WINEARCH="win64" WINEPREFIX="$HOME/.wine64" ./winetricks

**Comment by austin987** [comment]
Sounds like your wine binary is a 32 bit one.

**Comment by Yrij-Zhavoronkov** [comment]
Of course? I have dual wine. wine64 and wine32.

**Comment by austin987** [comment]
What happens if you use wine64 instead of wine?

**Comment by austin987** [comment]
What distribution are you on? Where did you get wine from? I am only able to reproduce this if wine is a 32-bit wine. With a proper 64-bit setup, I don't see this.

**Comment by Yrij-Zhavoronkov** [comment]
1) Debian GNU/Linux Stretch x86_64
2) Wine 32 build in /usr/local
3) Wine 64 build in /usr/local/wine64
version = 1.9.4

**Comment by austin987** [comment]
That's not how wine64 should be bulit, see https://wiki.winehq.org/Building_Wine#Shared_WoW64. wine64 needs access to wine32, they're not separated.

**Comment by Yrij-Zhavoronkov** [comment]
My wine64 have access to wine32. For test, run something 32-bit windows application. For e.x. wine64 ./TESV ...... ok / TESV is 32-bit application

**Comment by austin987** [comment]
You're calling wine64, not wine

**Comment by austin987** [comment]
What does:
WINEARCH=win64 wineboot

show?

**Comment by Yrij-Zhavoronkov** [comment]
programmeur@pingvinius:~$ WINEARCH=win64  WINEPREFIX="$HOME/.wine64"  wineboot
wine: '/home/programmeur/.wine64' is a 64-bit installation, it cannot be used with a 32-bit wineserver.

**Comment by austin987** [comment]
As I suspected. Your wine build is not properly set up for multiarch.

**Comment by Yrij-Zhavoronkov** [comment]
cd ~/wine-dirs/wine64-build/
../wine-source/configure --enable-win64
make

cd ~/wine-dirs/wine32-build/
../wine-source/configure --with-wine64=../wine64-build
make

compiled sucs, but don't include wine.... it's very strange

**Comment by austin987** [comment]
Please use https://forum.winehq.org/ if you need help building wine beyond the link I provided.

**Comment by Yrij-Zhavoronkov** [comment]
zaebis'...

**Comment by Yrij-Zhavoronkov** [comment]
ок...... repeat it...
../src/configure --enable-win64 --disable-win16 --disable-tests -prefix=/usr/local/wine64 
make -j5

**Comment by Yrij-Zhavoronkov** [comment]
WINEARCH=win64  WINEPREFIX="$HOME/.wine64" ./winetricks
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

it's worket after winecfg64  ONLY... and this strange...

**Comment by jkroepke** [comment]
Set to `WINELOADER=/usr/local/bin/wine64` work for me.

**Comment by DrEVILish** [comment]
Anyone coming from macOS, this worked for me

```
mv /usr/local/bin/wine /usr/local/bin/wine32
ln -s /Applications/Wine\ Stable.app/Contents/Resources/wine/bin/wine64 wine
```
