### ISSUE TITLE
link broken: Q811493_W2K_SP4_X86_EN.exe

### ISSUE THREAD

**Issue by chipotng** [Winetricks/winetricks#609]
This link wont work :(
http://download.microsoft.com/download/8/d/c/8dc79965-dfbc-4b25-9546-e23bc4b791c6/Q811493_W2K_SP4_X86_EN.exe

alternatives that worked :D

ftp://ftp.sunet.se/pub/security/vendor/microsoft/win2000/Security_Bulletins/Q811493_W2K_SP4_X86_EN.exe

ftp://ftp.fu-berlin.de/pc/security/ms-patches/win2000/Security_Bulletins/Q811493_W2K_SP4_X86_EN.exe

**Comment by austin987** [comment]
After a5e32a8a4329ec663690a4a8cf40e3ab071aad2d, this shouldn't matter, but I updated the link anyway ;)

Fixed by https://github.com/Winetricks/winetricks/commit/868317c4fe8707b417db52960d4ce2bf641e4cce

**Comment by AnonymousWebHacker** [comment]
cool
