### ISSUE TITLE
Aria2c issues due to user config.

### ISSUE THREAD

**Issue by kkartaltepe** [Winetricks/winetricks#612]
I have an aria2c runing in the background as a daemon with an RPC interface bound on localhost. When winetricks tries to start ariac to download files it will try to set up another daemon with RPC interface.

I noticed there was another issue with aria2 earlier where it was decided not to use `--no-conf` so it would probably be best to specify `--daemon=false --enable-rpc=false` to ensure aria2c doesnt go into the background after starting and prevent any attempts to rebind on the RPC interface specified in someones config.

Another issue found while attempting to find a solution was that if the user config has a `input-file` specified then aria2 will read it and attempt to download everything in that input file again. specifying `--input-file=''` appears to work.

Finally if the user has specified `save-session` their session will be ovewritten by this new aria2 process. And can be avoided using `--save-session=''`

So to get aria2c working with winetricks I had to change the aria2c download line to this
```sh
aria2c --daemon=false --enable-rpc=false --input-file='' --save-session='' -c -d "$_W_cache" -o "$_W_file" "$_W_url"
```

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/c2234e790122d1a7214941a843cea2a4acadcd6b
