### ISSUE TITLE
mspaint download broken again

### ISSUE THREAD

**Issue by geoffreydebelie** [Winetricks/winetricks#613]
[geoffrey@msi-laptop ~]$ LANG=en WINEARCH=win32 WINEPREFIX=$HOME/.mspaint-winetricks winetricks mspaint
Executing w_do_call mspaint
Executing load_mspaint
------------------------------------------------------
Working around wine bug 657 -- Native mspaint.exe from XP requires mfc42.dll
------------------------------------------------------
Executing w_do_call mfc42
Executing load_mfc42
Executing cabextract -q /home/geoffrey/.cache/winetricks/vcrun6/vcredist.exe -d /home/geoffrey/.mspaint-winetricks/dosdevices/c:/windows/system32 -F mfc42*.dll
Downloading http://download.microsoft.com/download/0/A/4/0A40DF5C-2BAE-4C63-802A-84C33B34AC98/WindowsXP-KB978706-x86-ENU.exe to /home/geoffrey/.cache/winetricks/mspaint
--2016-02-28 11:24:01--  http://download.microsoft.com/download/0/A/4/0A40DF5C-2BAE-4C63-802A-84C33B34AC98/WindowsXP-KB978706-x86-ENU.exe
Resolving download.microsoft.com (download.microsoft.com)... 2a02:26f0:60:487::e59, 2a02:26f0:60:483::e59, 23.65.43.48
Connecting to download.microsoft.com (download.microsoft.com)|2a02:26f0:60:487::e59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-28 11:24:01 ERROR 404: Not Found.

------------------------------------------------------
Downloading http://download.microsoft.com/download/0/A/4/0A40DF5C-2BAE-4C63-802A-84C33B34AC98/WindowsXP-KB978706-x86-ENU.exe failed
------------------------------------------------------

**Comment by geoffreydebelie** [comment]
The file is available on:
* http://web.archive.org/web/20130328151803/http://download.microsoft.com/download/0/A/4/0A40DF5C-2BAE-4C63-802A-84C33B34AC98/WindowsXP-KB978706-x86-ENU.exe
* ftp://cbvk.cz/programy_pro_knihovny/update-pack/Windows%20XP%20x86%20ENU/Security%20Updates/WindowsXP-KB978706-x86-ENU.exe

**Comment by austin987** [comment]
Update your winetricks, this should no longer be an issue since winetricks now falls back to archive.org for missing links.

**Comment by qwertychouskie** [comment]
Can this be closed?

**Comment by austin987** [comment]
Sure.
