### ISSUE TITLE
winhttp fails to download

### ISSUE THREAD

**Issue by mattkennedynz** [Winetricks/winetricks#615]
Hey there,

Just a heads up: `winhttp` fails to download and install. I'm using the latest version found at: https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

I then tried selecting just `wininet` to download/install and it successfully fell-back to the Internet Archive download link. If my spidey-senses are correct, this is the same file as required for `winhttp`?

Here's my terminal dump, if it helps:

```
[mk@mk-ThinkPad ~]$ winetricks
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Executing w_do_call winhttp
Executing load_winhttp
------------------------------------------------------
Checksum for /home/mk/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE did not match, retrying download
------------------------------------------------------
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Downloading http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE to /home/mk/.cache/winetricks/win2ksp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1245  100  1245    0     0   1462      0 --:--:-- --:--:-- --:--:--  1461
------------------------------------------------------
Checksum for /home/mk/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE did not match, retrying download
------------------------------------------------------
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by austin987** [comment]
What does 'winetricks --version' say? This should already be fixed.

**Comment by mattkennedynz** [comment]
`20160219 - sha1sum: 05e8b04016a0af4595678ef548f4792b8a928683`

**Comment by austin987** [comment]
Please run as:
winetricks -q -v winhttp &>> output.txt

and attach that log here (or email it to me directly if github makes it difficult). It should be trying to get it from archive.org on the second try.

**Comment by mattkennedynz** [comment]
Sure thing, here it is: [output.txt](https://github.com/Winetricks/winetricks/files/156715/output.txt)

I should say that by installing `wininet` (as per the above) it also installed/enabled `winhttp`. The problem was if I checked the boxes of both the `winhttp` and `wininet` DLLs at the same time.

**Comment by austin987** [comment]
That log didn't attempt to download, since winhttp was already installed. Please use a clean WINEPREFIX (and either delete that file from cache or temporarily move it) and get a new log.

**Comment by mattkennedynz** [comment]
Hmmm it seemed to have worked this time: 
[output.txt](https://github.com/Winetricks/winetricks/files/159865/output.txt)

When it failed to work the first time, I used the dialogue menu and selected `ie8`, `vcrun2008`, `winhttp` and `wininet` to all download and install. Then I remember seeing two checksum errors in relation to `winhttp` as dialogue messages.

**Comment by austin987** [comment]
You likely had a (slightly) old version of winetricks. The fallback to archive.org was recently added (after Microsoft removed a lot of older files).

**Comment by rik-shaw** [comment]
@austin987 could  you confirm which version of winetricks added the fallback to archive.org?  Thanks!

**Comment by austin987** [comment]
@rik-shaw 20160219
