### ISSUE TITLE
vcrun2008 installed in a diff. folder

### ISSUE THREAD

**Issue by hyukz** [Winetricks/winetricks#616]
On installing Ragnarok via winetricks:

First, Visual C++ 6 installation runs smoothly.
When trying to install Visual C++ 2008, installation is completed normally on the Microsoft GUI but winetricks halts showing the following error:

> vcrun2008 install completed, but installed file /home/mia/.wine/dosdevices/c:/Program Files (x86)/Common Files/Microsoft Shared/VC/msdia90.dll not found

I checked my files and the installation for Visual C++ 2008 was completed on /Program Files/ instead of /Program Files (x86)/. I am using wine32 and made sure that the arch was set up correctly in the command line. Thank you!

**Comment by austin987** [comment]
Can you try in a clean wineprefix, and set WINEARCH=win32 before creating the prefix?

**Comment by hyukz** [comment]
Thank you! The installation has now forwarded to the next step.

**Comment by austin987** [comment]
Cool. So WINEARCH=win64 fails for you, but WINEARCH=win32 works, correct?

**Comment by hyukz** [comment]
Exactly. In fact, the first time I tried the command _winetricks ragnarok_ I didn't specify anything (since I had been using wine32 for every other installation --- silly me). After that, even if I did specify over and over WINEARCH=win32 and my (default) wineprefix (which was created as 32bit), it kept trying to install vcrun2008 at the very same folder (I did uninstall and install vcrun2008 over again a few times in the Microsoft GUI, re-running the winetricks script). For fun I asked for WINEARCH=win64 at one point, and it halted from the very beginning saying that my wine folder was 32bit.

**Comment by austin987** [comment]
What wine version are you running? The only 64-bit build I have handy is wine-1.9.4-staging, which works (i.e. winetricks --verify vcrun2008 works).

**Comment by slackner** [comment]
The winetricks `vcrun2008` recipe also works fine here (tested with both the development and staging version of Wine 1.9.4 in a 64-bit wineprefix). Besides the wine version, it would also be useful to know which packages you use (distro packages, WineHQ packages, ...).

Btw, your last comment "For fun I asked for WINEARCH=win64 at one point, and it halted from the very beginning saying that my wine folder was 32bit." sounds a bit like you tried with WINEARCH=win64 without deleting wine prefix or setting the WINEPREFIX environment variable. It is expected to fail then.
