### ISSUE TITLE
Trojan in some of the microsoft.com downloads

### ISSUE THREAD

**Issue by mkondel** [Winetricks/winetricks#624]
ClamAV reports trojans in downloads from microsoft.com.  Their servers is not something this project can control, but maybe remove these from the list of libs downloaded by winetricks?

./IE8-WindowsXP-x86-ENU.exe: Win.Trojan.Ramnit-6496 FOUND
./msvbvm50.exe: Win.Trojan.Poebot-44 FOUND

My system is OSX and wine/winetricks are from mac ports.

**Comment by austin987** [comment]
Neither of those checksums have changed in years. Can you check this with other tools? I suspect it is a clamav bug.

**Comment by mkondel** [comment]
I'll post to clamav to see if someone there can look at a possible bug.  I
just have this mac and some ubuntu boxes, but if I get a chance i'll try
with anti-virus on someone's windows machine.

**Comment by birdie-github** [comment]
@austin987 

This bug is invalid, ClamAV is not really an AV (misses more than 90% current in the wild viruses).

**Comment by austin987** [comment]
https://www.virustotal.com/en/file/5a2c6c82774bfe99b175f50a05b05bcd1fac7e9d0e54db2534049209f50cd6ef/analysis/

2/57, one of them being ClamAV.
