### ISSUE TITLE
Update ev3 verb with latest version of software

### ISSUE THREAD

**Issue by qwertychouskie** [Winetricks/winetricks#626]
There is a new version of the EV3 software out, verb needs to be updated accordingly.  Download link:

http://esd.lego.com.edgesuite.net/digitaldelivery/mindstorms/6ecda7c2-1189-4816-b2dd-440e22d65814/public/LMS-EV3-WIN32-ENUS-01-02-01-full-setup.exe

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/0d337cb7c38b49c96051697a9d3e19e32a642066
