### ISSUE TITLE
problems with web.archive.org fallback

### ISSUE THREAD

**Issue by kmike** [Winetricks/winetricks#628]
Hey,

It'd be nice to have another fallback because web.archive.org is blocked in Russia; `allfonts` doesn't install because of that

```
response reading failed
Downloading https://web.archive.org/web/ftp://ftp.fi.debian.org/gentoo/distfiles/arialb32.exe to /Users/kmike/.cache/winetricks/corefonts
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) Unknown SSL protocol error in connection to web.archive.org:-9847
------------------------------------------------------
Downloading https://web.archive.org/web/ftp://ftp.fi.debian.org/gentoo/distfiles/arialb32.exe failed
```

**Comment by austin987** [comment]
Do you have an alternative suggestion (that works in Russia)?

**Comment by kmike** [comment]
Hm, I don't think there is a general archive.org alternative, and if there is it'd be likely banned as well. There may be mirrors for individual files (e.g. for corefonts google shows https://sourceforge.net/projects/corefonts/files/the%20fonts/final/).

What strikes me is that these ftp links work if I try them manually. So maybe there is some rate limiting (and delays between download requests will help), or maybe retrying it a few times will help.

**Comment by austin987** [comment]
Finding a mirror for corefonts is easy, but the majority of microsoft.com stuff isn't :/

**Comment by kmike** [comment]
Yeah; my actual issue is with secur32 now - even microsoft.com own search returns a broken link for Windows2000-KB959426-x86-ENU.EXE file

**Comment by austin987** [comment]
Heh, nice.

We can fix corefonts pretty easily, but I don't know of a solution for most of these, unfortunately. I'd recommend a VPN (or use Tor to access archive.org and place those files in ~/.cache/winetricks manually).

**Comment by kmike** [comment]
Thanks for the suggestion!

**Comment by qwertychouskie** [comment]
Maybe an option to automatically use Tor or a free VPN service would help.  May be of use: http://linuxaria.com/howto/how-to-anonymize-the-programs-from-your-terminal-with-torify

**Comment by birdie-github** [comment]
There are no alternatives to wayback machine unfortunately, so let's leave it as it is.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/05aef56d2c863ab720c12ffa71d4961943cdfd83 implements a -t / --torify option, which should provide a workaround.
