### ISSUE TITLE
Add `--use-torify` flag

### ISSUE THREAD

**Issue by qwertychouskie** [Winetricks/winetricks#630]
It would be nice have a flag to prefix download commands with `torify`.  Also, the message in https://github.com/Winetricks/winetricks/pull/629 should be changed from:
"Your IP address has been determined to belong to Russia. If you encounter a certificate error while downloading, please use VPN or download files manually."
to:
"Your IP address has been determined to belong to Russia. If you encounter a certificate error while downloading, please make sure tor is installed and relaunch with the `--use-torify` option, or use a VPN to download files manually."

More info on the `torify` command in this article: http://linuxaria.com/howto/how-to-anonymize-the-programs-from-your-terminal-with-torify

Also, this would solve bug https://github.com/Winetricks/winetricks/issues/628

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/05aef56d2c863ab720c12ffa71d4961943cdfd83

Thanks for the suggestion and bug report, this was a neat feature to get to implement.
