### ISSUE TITLE
allfonts doesn't install, some font links aren't working

### ISSUE THREAD

**Issue by riclas** [Winetricks/winetricks#631]
ricardo@ricardo-N55SF:~/Downloads$ bash winetricks allfonts
Executing w_do_call allfonts
Executing load_allfonts
Executing w_do_call baekmuk
Executing load_baekmuk
Downloading http://ftp.debian.org/debian/pool/main/t/ttf-baekmuk/ttf-baekmuk_2.2.orig.tar.gz to /home/ricardo/.cache/winetricks/baekmuk
--2016-04-03 15:59:44--  http://ftp.debian.org/debian/pool/main/t/ttf-baekmuk/ttf-baekmuk_2.2.orig.tar.gz
Resolving ftp.debian.org (ftp.debian.org)... 2001:610:1908:b000::148:12, 130.89.148.12
Connecting to ftp.debian.org (ftp.debian.org)|2001:610:1908:b000::148:12|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-03 15:59:44 ERROR 404: Not Found.

------------------------------------------------------
Downloading http://ftp.debian.org/debian/pool/main/t/ttf-baekmuk/ttf-baekmuk_2.2.orig.tar.gz failed
------------------------------------------------------

lucida and tahoma links are broken too

**Comment by qwertychouskie** [comment]
You are using an old version, use the latest version.

**Comment by riclas** [comment]
you are right, i messed up replacing the old version. sorry
