### ISSUE TITLE
helper_xpsp3 isn't working anymore

### ISSUE THREAD

**Issue by vitor251093** [Winetricks/winetricks#632]
xpsp3 used to be downloaded from that link:
http://download.microsoft.com/download/d/3/0/d30e32d8-418a-469d-b600-f32ce3edf42d/WindowsXP-KB936929-SP3-x86-ENU.exe

Which could be found at that page in Microsoft website:
http://www.microsoft.com/en-us/download/details.aspx?id=24

Both are unavailable now, probably due to the end of Windows XP support. That file is needed for some winetricks, which might be a problem. The link should be changed to a functional one which match its checksum (c81472f7eeea2eca421e116cd4c03e2300ebfde4).

Googling a bit I could find some websites with the file available, but I still haven't checked the checksum to be sure that the file is trustful so I prefer to don't share any link yet.

**Comment by vitor251093** [comment]
That file matches the checksum, but I'm not sure if it's possible to create a direct link to a Google Drive file:
https://drive.google.com/file/d/0B4GtfimCCTp2eDRmWUZ3TEdOc3c/view?pref=2&pli=1

In case someone has a domain where it can be hosted, that one has the same SHA1 checksum than the original file.

**Comment by qwertychouskie** [comment]
If you have the latest version of winetricks, it should automatically fall back to web.archive.org.

**Comment by vitor251093** [comment]
Ah yeah, sorry about that. I use a crawler in the winetricks file so I can download the winetricks manually and show the progress in a GUI, and I haven't noticed that WebArchive part. 

Still, it wouldn't be more safe to update that link? If Microsoft change their robots.txt file it will affect WebArchive backups, and may even remove that file from their website. I'm not saying it should be done now, but at least there should be a plan C, since apparently WebArchive was already the plan B :P

**Comment by qwertychouskie** [comment]
The problem is trying to find trustworthy links.  @austin987 can this be closed for now, as it is not currently a problem?

**Comment by austin987** [comment]
Yes, I think so.
