### ISSUE TITLE
Still having issue with: Call from to unimplemented function api-ms-win-crt-math-l1-1-0.dll._except1, aborting

### ISSUE THREAD

**Issue by alexforbes** [Winetricks/winetricks#641]
The crash still occurred after trying this fix https://github.com/Winetricks/winetricks/issues/597

I suspect that this person had a similar experience: http://ubuntuforums.org/showthread.php?t=2312935

The main menu looks correct.
The crash and error only appear during the loading screen after the opening cinematic.

I am using the Good Old Games, not the Steam version of Grim Dawn, though I don't think it really makes a difference.

I have included the output of "winetricks --force -v vcrun2015" here:
[issue.txt](https://github.com/Winetricks/winetricks/files/268698/issue.txt)

**Comment by austin987** [comment]
AFAICT, it looks fine:
+ test api-ms-win-crt-math-l1-1-0.dll != 
+ [ native,builtin = default ]
+ echo "*api-ms-win-crt-math-l1-1-0.dll"="native,builtin"
...
+ cp /home/fungu5/.PlayOnLinux//wineprefix/GrimDawn/dosdevices/c:/windows/temp/_vcrun2015/api_ms_win_crt_math_l1_1_0.dll /home/fungu5/.PlayOnLinux//wineprefix/GrimDawn/dosdevices/c:/windows/system32/api-ms-win-crt-math-l1-1-0.dll

does it show as native,builtin in winecfg?

Also note that you're using old wine/winetricks versions:
Wine is 'wine'; Wine version is + wine --version
wine-1.8
+ echo winetricks is /home/fungu5/workspace/winetricks/winetricks ; winetricks version is 20160109
winetricks is /home/fungu5/workspace/winetricks/winetricks ; winetricks version is 20160109

wine-1.8.2 is latest stable / 1.9.9 development. Winetricks is also out of date (but I don't think anything recent explicitly fixed this). I'm also wondering if PlayOnLinux is a factor here.

**Comment by qwertychouskie** [comment]
The Winetricks version is 20160109, while the commit was made on the 21st, 20 days afterward.

**Comment by austin987** [comment]
The winetricks version isn't incremented with every commit. The commit was made when WINETRICKS_VERSION was 20160109, and the log confirms that patch is applied.

But yes, in general older versions are unsupported.

**Comment by jschueller** [comment]
maybe this is fixed by 37230c5 which overrides api-ms-win-crt-math for 32 bits prefix too

**Comment by slyscorpion** [comment]
Isn't this fixed now? https://github.com/Winetricks/winetricks/issues/597#issuecomment-247779407

**Comment by qwertychouskie** [comment]
@alexforbes Can you test and see if this is still a problem?

**Comment by austin987** [comment]
Should be fixed, and it's been a year and a half with no reply, so closing. Reopening if still in current winetricks.
