### ISSUE TITLE
Does not work when invoked from the standard input

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#645]
I'm trying to run `winetricks` with the following fancy way by reading its input and parsing directly in Bash, e.g.

    curl https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks | bash /dev/stdin mt4

This doesn't work and stops on:

> Using winetricks 20160425 - sha1sum: f155c28123531a28fdd2b914f3a2c8937e54bfd7 with wine-1.6.2

When executed with `-x` it stops on:

```
Using winetricks 20160425 - sha1sum: f155c28123531a28fdd2b914f3a2c8937e54bfd7 with wine-1.6.2
+ winetricks_cleanup
+ test ''
+ set +e
+ test -f /tmp/winetricks.IvfH9BOx/w.kenorb.26573/dd-pid
+ test /home/kenorb/.wine/dosdevices/y:
+ rm -f /home/kenorb/.wine/dosdevices/y:
+ test '' = 1
+ rm -rf /tmp/winetricks.IvfH9BOx/w.kenorb.26573
+ test '' = 1
+ test 1 = 1
+ rm -rf /tmp/winetricks.IvfH9BOx
```

Basically I'm writing a script to install app with a simple one-liner and I'm doing it to avoid at least 3 separate commands (plus some current path calculation, depending from where the script was run) as below which works fine:

    curl -o winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
    chmod +x winetricks
    ./winetricks mt4

**Comment by austin987** [comment]
I took a quick look and can't figure out why this would fail. It's failing here:
`# Must initialize variables before calling w_metadata
if ! test "$WINETRICKS_LIB"
then
    WINETRICKS_SRCDIR=`dirname "$0"`
    WINETRICKS_SRCDIR=`cd "$WINETRICKS_SRCDIR"; pwd`

    # Which GUI helper to use (none/zenity/kdialog).  See winetricks_detect_gui.
    WINETRICKS_GUI=none
    # Default to a shared prefix:
    WINETRICKS_OPT_SHAREDPREFIX=${WINETRICKS_OPT_SHAREDPREFIX:-1}

    # Handle options before init, to avoid starting wine for --help or --version
    while winetricks_handle_option $1
    do
        shift
    done

    # Workaround for https://github.com/Winetricks/winetricks/issues/599
    # If --isolate is used, pass verb to winetricks_init, so it can set the wineprefix using winetricks_set_wineprefix()
    # Otherwise, an arch mismatch between ${WINEPREFIX:-$HOME/.wine} and the prefix to be made for the isolated app would cause it to fail
    case $WINETRICKS_OPT_SHAREDPREFIX in
        0) winetricks_init $1 ;;
        *) winetricks_init ;;
    esac
fi
`

the entire code block runs, and if I insert an echo before/after the final 'fi', then I see winetricks exiting after that code block (second echo never runs).

I'd recommending doing something like this instead:
winetricks_dir=$(mktemp -d)
curl -o ${winetricks_dir}/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x ${winetricks_dir}/winetricks
${winetricks_dir}/winetricks mt4

**Comment by kenorb** [comment]
Ok, it seems this syntax works:

    curl -s https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks | sh -s mt4

basically the previous wasn't recognising the argument properly.

However this error shows:

> sh: line 524: sh: No such file or directory

Line 524:

    _W_gotsum=`$WINETRICKS_SHA1SUM < "$_W_file" | sed 's/(stdin)= //;s/ .*//'`

This is because winetricks expect `$_W_file` to be file, but `sh` is set, because the script is invoked from the context.

The fix could be to check whether the file exists, e.g.

    _W_gotsum=`[ -f "$_W_file" ] && $WINETRICKS_SHA1SUM < "$_W_file" | sed 's/(stdin)= //;s/ .*//'`

**Comment by austin987** [comment]
Thanks for tracking down. Fixed by https://github.com/Winetricks/winetricks/commit/32a87de664eb7da92cfff0b72d382cdb69c95bcf
