### ISSUE TITLE
winetricks: ar: command not found for load_opensymbol

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#652]
I've winetricks already installed (_winetricks is already the newest version_) on Ubuntu, so I assume I've got all the required dependencies.

Now I'm downloading the version from GitHub:

    wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

Now I'm running this command (which uses the winetricks from the current dir):

    $ bash -x winetricks mt4

however it fails with:

```
Executing w_do_call opensymbol
Executing load_opensymbol
Executing ar x /home/ubuntu/.cache/winetricks/opensymbol/fonts-opensymbol_102.6+LibO4.3.3-2+deb8u3_all.deb data.tar.xz
winetricks: line 289: ar: command not found
------------------------------------------------------
Note: command 'ar x /home/ubuntu/.cache/winetricks/opensymbol/fonts-opensymbol_102.6+LibO4.3.3-2+deb8u3_all.deb data.tar.xz' returned status 127.  Aborting.
```

I've tried `sudo apt-get install ar` but it says it cannot locate such package. I believe this is the issue for all apps which are calling `load_opensymbol`.

How do I install `ar` command, and should winetricks add this command as dependency somehow?

**Comment by qwertychouskie** [comment]
Make sure you have `binutils` installed.

**Comment by kenorb** [comment]
It seems it works, thanks. I assume winetricks would expect that this should be already installed?

**Comment by austin987** [comment]
On Jun 12, 2016 2:04 PM, "Rafal" <notifications@github.com> wrote:
>
> It seems it works, thanks. I assume winetricks would expect that this
should be already installed?

Yes,  it's usually installed on most distros afaik. What are you running?

In any case, it could warn better. I'll add a fix when I get back to a pc.

**Comment by kenorb** [comment]
I'm running fresh AWS EC2 instance of Ubuntu 14.04.3 LTS (ami-fce3c696) with the following provisioning script: [`provision.sh`](https://github.com/EA31337/FX-MT-VM/blob/c05ac893deabc5f0e50c3909e6e5a194cf5bd269/scripts/provision.sh) (before adding binutils), so basically `winetricks` is installed with `wine1.8` package by the following commands:

```
sudo dpkg --add-architecture i386
sudo add-apt-repository -y ppa:ubuntu-wine/ppa
sudo apt-get update
sudo apt-get install -y wine1.8
```

> Get:432 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe winetricks all 0.0+20140302-0ubuntu2 [131 kB]
> Preparing to unpack .../winetricks_0.0+20140302-0ubuntu2_all.deb ...
> Setting up winetricks (0.0+20140302-0ubuntu2) ...
> ...

```
$ winetricks --version
20140302

```

**Comment by austin987** [comment]
Thanks for the info. You should get a better error message after https://github.com/Winetricks/winetricks/commit/900f58df591d364a4728cec826341bc0c229d0a8.

Unfortunately 7zip has a bug (I think, haven't verified yet), so I can't add a fallback to 7zip.

**Comment by austin987** [comment]
Feature not a bug...

Really fixed by https://github.com/Winetricks/winetricks/commit/060ec5bb2496d8a1cdc3063941dc571dbfd861d1
