### ISSUE TITLE
winetricks fails to load custom .verb files that start with 'install'

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#653]
When I run:

    winetricks install_mt5.verb

I've got the following error:

```
Unknown arg install_mt5
Usage: /usr/local/bin/winetricks [options] [command|verb|path-to-verb] ...
```

However it works when I rename the file to `winetricks_mt5.verb`.

Is that the expected behaviour that the file needs to be with specific pattern? Or this can be corrected?

--

I'm using winetricks 20160219.

**Comment by qwertychouskie** [comment]
Try:
    winetricks ./install_mt5.verb

**Comment by kenorb** [comment]
The same when specifying with `./` and with full path.

**Comment by austin987** [comment]
Works for me with 20160614, please update and retest.

**Comment by austin987** [comment]
Also, if still present, attach the full output, including the winetricks command.

**Comment by kenorb** [comment]
Master branch has `20160425` the latest (as per `WINETRICKS_VERSION` variable), where I can find `20160614`?

**Comment by kenorb** [comment]
Here are the steps to reproduce on empty folder with the version from **master**:

```
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
wget -O install_mt5.verb https://raw.githubusercontent.com/EA31337/FX-MT-VM/master/scripts/winetricks_mt5.verb
sh -x winetricks install_mt5.verb
```

Error:

> Unknown arg install_mt5

It says it's using `20160425`.

**Comment by austin987** [comment]
I tested with some basic .verb files, which work. A few things I noticed
A) your .verb file starts with #!/bin/bash, which isn't needed (and that's not valid bash on its own).
B) The real problem is that winetricks doesn't like verbs that start with install_. That may or may not be a valid bug, I haven't dug into it yet. The .verb handling is kind of a mess, I don't have time right now to dig into that rabbit hole.

**Comment by austin987** [comment]
Btw, here's what I mean by a basic verb:
```
w_metadata true app
load_true()
{
    echo "true should succeed"
    true
}
```

**Comment by austin987** [comment]
Okay, so I found out what's going on. .verbs aren't really documented (they were on google code, but I don't think the wiki was moved. Anyway, what's going on is your verb's name and your command must match. Your command was winetricks_mt5, so when you had install_mt5.verb, it failed. Renaming to winetricks_mt5, which makes, worked around it. if you use asdf_mt5, or mf1.verb, it would also fail.

On that note, winetricks_ shouldn't be used in a verb's name. Just use 'mt5' and 'mt5.verb', and remove #!/bin/bash

**Comment by kenorb** [comment]
@austin987 Thanks for your help, I'll try changing the command name. Btw. the [wiki pages](https://code.google.com/archive/p/winetricks/wikis) can be still exported I think.

**Comment by austin987** [comment]
I added a note on the readme:
https://github.com/Winetricks/winetricks/commit/75eb191b7630336a5b5822d3ebb41039977e54f9

and some tests, to prevent future breakage:
https://github.com/Winetricks/winetricks/commit/6c734f1023d50f8f09811aa7ea42469a13b4c148

**Comment by qwertychouskie** [comment]
BTW, the wiki is here: https://github.com/Winetricks/winetricks/tree/wiki
