### ISSUE TITLE
echo '%ProgramFiles%' returned unexpanded string '%ProgramFiles%'

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#654]
This is related to the old bugs #90 & #163, but this is still happening in recent winetricks 20140302.

Here are the reproducible steps on clean Ubuntu 14.04 (Note: `~/.wine` doesn't exist yet):

1. Run: `winetricks winhttp` from the Terminal.
2. Instead of install, this popup is shown:

  <img width="388" alt="screen shot 2016-06-13 at 00 45 08" src="https://cloud.githubusercontent.com/assets/266306/15994581/ab44ba00-3100-11e6-8d3c-1c57ee69bf9a.png">

3. Now I've changed my mind, because I don't want to install Mono package, so I'm either pressing Cancel or Control-C in terminal.
4. If popup doesn't get killed, kill it by: `wineserver -k`.
5. Now when I run `winetricks winhttp` again, I've got this error:

  > wine cmd.exe /c echo '%ProgramFiles%' returned unexpanded string '%ProgramFiles%' ... can be caused a corrupt wineprefix, an old wine, or by not owning /home/ubuntu/.wine

This is the edge-case and the only workaround is to remove the whole `~/.wine` folder.

**Comment by austin987** [comment]
If you ctrl+c wineboot, you won't get a valid prefix.

**Comment by qwertychouskie** [comment]
Also, version 20140302 is not recent, but **extremely** old.  Download the latest version directly from GitHub, as the version in the Ubuntu repos is ancient.
