### ISSUE TITLE
File ttf-opensymbol_3.2.1-11+squeeze8_all.deb is missing.

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#655]
I've this [verb file](https://github.com/EA31337/FX-MT-VM/blob/mt5/scripts/winetricks_mt5.verb) which fails with when downloading fonts via `w_call opensymbol`:

```
Executing w_do_call opensymbol
Executing load_opensymbol
Executing mkdir -p /home/travis/.cache/winetricks/opensymbol
Downloading http://ftp.us.debian.org/debian/pool/main/o/openoffice.org/ttf-opensymbol_3.2.1-11+squeeze8_all.deb to /home/travis/.cache/winetricks/opensymbol
--2016-06-13 15:06:39--  http://ftp.us.debian.org/debian/pool/main/o/openoffice.org/ttf-opensymbol_3.2.1-11+squeeze8_all.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 64.50.236.52, 128.30.2.26, 128.61.240.89, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-06-13 15:06:39 ERROR 404: Not Found
```

Missing file: `ttf-opensymbol_3.2.1-11+squeeze8_all.deb`.

This file is available at: http://ubuntu.snet.uz/debian-security/pool/updates/main/o/openoffice.org/

See this CI build: [#137268366](https://travis-ci.org/EA31337/FX-MT-VM/jobs/137268366)

- Using winetricks 20160425 - sha1sum: 5911c0e8be07f9aba56f4a4cd154f3dce93b2b32 with wine-1.8.0
- Related: #308

**Comment by austin987** [comment]
I don't think you're using 20160425. This link was fixed in 20160311:
https://github.com/Winetricks/winetricks/commit/ca7dae70186fcd904908b28c39a902857d08a518
