### ISSUE TITLE
Add WMV9 ("vidc WMV3") codec

### ISSUE THREAD

**Issue by abbradar** [Winetricks/winetricks#659]
Installation sequence (based on [this manual](https://appdb.winehq.org/objectManager.php?sClass=version&iId=33129)):

1. Download an update which contains `wmv9vcm.dll`: https://www.microsoft.com/en-us/download/details.aspx?id=39486
2. Use `cabextract`
3. Place `wm64/wmv9vcm.dll` into `%SYSTEM32%`
3. Add the following registry key:
```
[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Drivers32]
"vidc.WMV3"="wmv9vcm.dll"
```

Proposed package name: `wmv9codec`. I've tested that it makes a difference without `quartz` or any other packages, so there's no prerequisites.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/2236992c3f145a5c9f3e2778cf58af125f6c92ef

**Comment by abbradar** [comment]
That was fast! Thank you very much.
