### ISSUE TITLE
add support yad and qarma

### ISSUE THREAD

**Issue by sixsixfive** [Winetricks/winetricks#661]
since both are zenity compatible it should be very easy.

see also:

* [qarma](https://github.com/luebking/qarma)
* [yad](https://sourceforge.net/projects/yad-dialog/)

**Comment by austin987** [comment]
Can you please test https://github.com/Winetricks/winetricks/commit/aff70bb3f7ef033da3986bb67a644537d2c54a90

Note that it's in a branch, not in master

**Comment by sixsixfive** [comment]
qarma-qt5 works for me, yad seems to use a slightly different syntax here

for example:

```
qarma|yad \
            --title 'a' \
            --text 'b' \
            --list \
            --radiolist \
            --column '' \
            --column '' \
            --column '' \
            --height 600 \
            --width 800 \
            --hide-column 2 \
            FALSE help       'c' \
            FALSE apps       'd' \
            FALSE benchmarks 'd' \
            FALSE games      'e' \
            TRUE  main       'f' \
```

apps selection qarma output:

    apps

apps selection yad output:

    TRUE|apps|d|

so to get the same output as qarma i would need something like:

    echo "$?"|cut -d'|' -f2

or add those flags:

    --print-column=2 --separator=''

**Comment by austin987** [comment]
I did that. Some stuff works, but it's still failing when e.g., changing settings.

**Comment by sixsixfive** [comment]
if I add 

    --print-column=2 --separator=''  

to the command [@line3004](https://github.com/Winetricks/winetricks/blob/714bf886c8a9b05b1e68b3b404cd37fd3dab72f9/src/winetricks#L3004) yad works too(I havent checked all, just ddr=gdi)

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/1da81f8dafc6c0de853463c2d5d6779ff094fac6 fixes settings, but dlls do not work.

**Comment by austin987** [comment]
@sixsixfive could you please test when you get a chance?

**Comment by sixsixfive** [comment]
sorry I'm currenly a bit busy but i tried this today, however im still unsure (the script is a bit messy ;), 

i assume 

    LANG=C sh winetricks dlls 

calls line [3101]( https://github.com/Winetricks/winetricks/blob/1da81f8dafc6c0de853463c2d5d6779ff094fac6/src/winetricks#L3101) ?

if so even with zenity it will not display more than the first 3 columns so there is probably a bug somewhere @[Line3251](https://github.com/Winetricks/winetricks/blob/1da81f8dafc6c0de853463c2d5d6779ff094fac6/src/winetricks#L3251)

------------------------------------
PS: to detect the possible guis something like this would be much smaller:

```
winetricks_detect_gui() {
	WINETRICKS_MENU_HEIGHT=500
	WINETRICKS_MENU_WIDTH=1010
	_guis="kdialog zenity yad qarma"
        for _gui in $_guis; do
            type $_gui &>/dev/null && WINETRICKS_GUI=$_gui && printf "GUI will be $_gui\n" 
        done
		if [ "$_gui" = "kdialog" ];then
			printf "Zenity not found! Using kdialog as poor substitute.\n"
		fi
		if [ -z $WINETRICKS_GUI ];then
            cat <<EOF

No arguments given, so tried to start GUI, but zenity not found.
Please install zenity if you want a graphical interface, or
run with --help for more options."

EOF
			exit 1
		fi
}
```

**Comment by sixsixfive** [comment]
I clode this now since winetricks is now working fine with qarma ;)

**Comment by austin987** [comment]
Those changes aren't in master..

**Comment by sixsixfive** [comment]
no but there was an update for qarma and it usually installs a symlink as zenity

**Comment by austin987** [comment]
Even better, thanks for info.
