### ISSUE TITLE
404 error upon using winetricks allfonts command

### ISSUE THREAD

**Issue by Starguise** [Winetricks/winetricks#662]
I was trying to use the winetricks allfonts command to install fonts for a windows application I was trying to use with wine, and this error occured:

Executing w_do_call allfonts
Executing load_allfonts
Executing w_do_call baekmuk
Executing load_baekmuk
Downloading http://ftp.debian.org/debian/pool/main/t/ttf-baekmuk/ttf-baekmuk_2.2.orig.tar.gz to /home/(My User Name)/.cache/winetricks/baekmuk
--2016-08-01 19:14:30--  http://ftp.debian.org/debian/pool/main/t/ttf-baekmuk/ttf-baekmuk_2.2.orig.tar.gz
Resolving ftp.debian.org (ftp.debian.org)... 130.89.148.12, 2001:610:1908:b000::148:12
Connecting to ftp.debian.org (ftp.debian.org)|130.89.148.12|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-01 19:14:30 ERROR 404: Not Found.

------------------------------------------------------
Downloading http://ftp.debian.org/debian/pool/main/t/ttf-baekmuk/ttf-baekmuk_2.2.orig.tar.gz failed
------------------------------------------------------

**Comment by qwertychouskie** [comment]
You are using an old version, use the version directly from this repo. (You are probably trying to use the version packaged in Ubuntu, which is like 2 years old.)
