### ISSUE TITLE
Previously working program freezes after installing C++ vrun apps

### ISSUE THREAD

**Issue by cliffsloane555** [Winetricks/winetricks#663]
Forgive me, I know this question has undoubtedly been answered, but I am rather new to WINE and Winetricks, so I need a bit more help. A link to a previous post would be much appreciated.
I installed a Windows program on Ubuntu 16.04 using WINE with a .32 prefix. (Don't ask me how! Can I remember?) It has been working well for several months.
Yesterday, I tried to install Nero DiskSpeed the same way. The error message said that two versions of Microsoft VCRedist 2010 were missing, as well as the Windows verification tool.
I dug around and found posts explaining that these were versions of C++ VC Run.
So I went to Winetricks, install apps and I installed the four C++ apps in the list.
It updated a few times, then said it was installed. 
Of course, my DiskSpeed failed to install, because it failed the Windows Verification step. But that is a separate issue.
Since then, my previous program keeps freezing, requiring a reboot and not just restarting the program.
I went back into Winetricks and cannot find a choice for uninstalling those offending programs.

Can you help? Thanks much.

Cliff

**Comment by austin987** [comment]
You want https://forum.winehq.org/
