### ISSUE TITLE
Winetricks vcrun2015 post configuration prevent Battle.net to run in some case

### ISSUE THREAD

**Issue by ceric35** [Winetricks/winetricks#666]
Hi,

I finally found that this bug (https://bugs.winehq.org/show_bug.cgi?id=41121) is caused for me by a strange configuration of wine cfg lib tab after winetricks vcrun2015.

After installation, it contains following libs:
api-ms-win-crt-conio-l1-1-0
api-ms-win-crt-heap-l1-1-0
api-ms-win-crt-locale-l1-1-0
api-ms-win-crt-math-l1-1-0
api-ms-win-crt-runtime-l1-1-0
api-ms-win-crt-stdio-l1-1-0
atl140
msvcp140
ucrtbase
vcomp140
vcruntime140

After removing all lib but msvcp140 (as mentionned here https://appdb.winehq.org/objectManager.php?iId=28855&sClass=version), it's working.

**Comment by austin987** [comment]
That's not strange, it was needed in older versions of wine.

Does it really need all of them removed? It may be helpful to see what wine commit changed this behavior, if you can run a regression test.

**Comment by ceric35** [comment]
Installation note in https://appdb.winehq.org/objectManager.php?iId=28855&sClass=version as just been updated. vcrun2015 is no longer required with new Battle.net client.

If vcrun2015 is no longer needed with recent wine, maybe this issue a not a bug anymore ?

**Comment by Chiitoo** [comment]
This is an odd one.  The 'Battle.net Launcher' does work OK here, with the following existing overrides:

- api-ms-win-crt-conio-l1-1-0
- api-ms-win-crt-heap-l1-1-0
- api-ms-win-crt-locale-l1-1-0
- api-ms-win-crt-math-l1-1-0.dll
- api-ms-win-crt-runtime-l1-1-0
- api-ms-win-crt-stdio-l1-1-0
- atl140
- msvcp140
- msvcr140
- ucrtbase
- vcomp140
- vcruntime140

All set to (native, builtin), in a fresh prefix with the following 'winetricks.log':

```
sandbox
w_workaround_wine_bug-37781
vcrun2015
corefonts
```
Tested with Wine 1.9.16 and winetricks 20160724 - sha1sum: 92adb723b78d09317d373a17ae9a4932abe64923

Some discussion on this can also be found over at the Gentoo forums: [World Of Warcraft Support UPDATED 2016 Edition](https://forums.gentoo.org/viewtopic-p-7953306.html#7953306)
