### ISSUE TITLE
Winetricks project on Launchpad not linked to GitHub

### ISSUE THREAD

**Issue by qwertychouskie** [Winetricks/winetricks#668]
<https://launchpad.net/winetricks>'s trunk is an import of an SVN branch of Google Code.  This may be the reason the winetricks package in Ubuntu is SOOOO old, and should be fixed.

**Comment by austin987** [comment]
I'll need @dankegel to handle this, I don't have permission on there.

I'll also email him privately.

**Comment by qwertychouskie** [comment]
Just created a "winetricks-issues" bug tracker link on Launchpad to the GitHub issue tracker for Winetricks, this can replace the current default link to Google Code issues.  Example of use in a bug report: https://bugs.launchpad.net/ubuntu/+source/winetricks/+bug/718643

**Comment by austin987** [comment]
@qwertychouskie Dan gave me access a bit ago, and I've gone through and updated everything I could find. I'm not familiar at all with Launchpad, so I'm sure I missed something. I didn't touch package links, as I'm not sure what that would affect.

LMK what else you need done there.

**Comment by qwertychouskie** [comment]
The code import failed, it says that no repository exists at that location???

**Comment by austin987** [comment]
It's at master, not trunk:
https://code.launchpad.net/winetricks

**Comment by qwertychouskie** [comment]
At https://launchpad.net/winetricks/master, it has the wrong branch registered.

**Comment by austin987** [comment]
Took several tries, LP is confusing. https://code.launchpad.net/winetricks show shows code.
I asked about the master link, apparently it's a LP bug (no # given yet), but apparently it's not supposed to be shown for git projects:

<wgrant> austin987: The https://launchpad.net/winetricks/master bug is already filed, but I forget the number. We will probably hide that section of the page for Git.

A bug was filed about showing the original github link on LP, that's:
https://bugs.launchpad.net/launchpad/+bug/1650109

Is there anything else you need from my end? if not, please close.

**Comment by qwertychouskie** [comment]
Looks good.
