### ISSUE TITLE
Winetricks saying "Prefix Creation Aborted"

### ISSUE THREAD

**Issue by KCric12** [Winetricks/winetricks#669]
Hi guys, i recenty started using wine to play some windows games on my mac. It has worked perfectly so far, except for this particular instance. In order to play a game, i apparently need to apply winetricks directplay, directmusic and d3dx9_36. But whenever i try to do that it gives me a warning "Prefix creation aborted" and then gives me this error log below. Is there any way to get around this issue? Been looking on the internet for ages but no one seems to have a solution. Additionally, all the other prefixes have the same issue. :( I would really appreciate any help at all. Thanks guys.

###BOTTLING### applywinetricks.sh
###BOTTLING### Gathering debug Info...

Versions
OS...........................: darwin15
Wine.........................: 1.6.1
WineBottler..................: 1.6.1

Environment
PWD..........................: '/Applications/Wine.app/Contents/Resources/bin'
PATH.........................: /Applications/Wine.app/Contents/Resources/bin:/usr/bin:/bin:/usr/sbin:/sbin
USER.........................: kynan.campbell
HOME.........................: /Users/kynan.campbell
BUNDLERESOURCEPATH...........: /Applications/Wine.app/Contents/Frameworks/WBottler.framework/Resources
WINEPATH.....................: /Applications/Wine.app/Contents/Resources/bin
LD_LIBRARY_PATH..............: 
DYLD_FALLBACK_LIBRARY_PATH...: 
FONTCONFIG_FILE..............: /Applications/Wine.app/Contents/Resources/etc/fonts/fonts.conf
SILENT.......................: 
http_proxy...................: 
https_proxy..................: 
ftp_proxy....................: 
socks5_proxy.................: 

Bottle
TEMPLATE.....................: 
BOTTLE.......................: /Users/kynan.campbell/Wine Files
INSTALLER_URL................: 
INSTALLER_IS_ZIPPED..........: 0
INSTALLER_NAME...............: 
INSTALLER_ARGUMENTS..........: 
WINETRICKS_ITEMS.............:  art2kmin d3dx9_36
DLL_OVERRIDES................: 
EXECUTABLE_PATH..............: notneeded
EXECUTABLE_ARGUMENTS.........: 
EXECUTABLE_VERSION...........: 1.0
BUNDLE_IDENTIFIER............: org.kronenberg.winebottler
SILENT.......................: 

Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: MacBookAir6,2
      Processor Name: Intel Core i5
      Processor Speed: 1.3 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 3 MB
      Memory: 8 GB
      Boot ROM Version: MBA61.0099.B22
      SMC Version (system): 2.13f15
      Serial Number (system): C02LW4FZF6T6
      Hardware UUID: 2A55101F-C734-51BF-A2D6-F538227497FA

###BOTTLING### installing art2kmin
------------------------------------------------------
/private/tmp/winebottler_1473685788/nospace/wine cmd.exe /c echo '%ProgramFiles%' returned unexpanded string '%SystemDrive%\Program Files' ... this can be caused by a corrupt wineprefix, by an old wine, or by not owning /private/tmp/winebottler_1473685788/nospace/wineprefix
------------------------------------------------------
### LOG ### Command 'sh /private/tmp/winebottler_1473685788/nospace/winetricks.sh --no-isolate art2kmin' returned status 1.

Task returned with status 1.

**Comment by qwertychouskie** [comment]
Wine 1.6.1?!?  Start by updating to at least Wine 1.8.4.

**Comment by austin987** [comment]
This issue should be filed with WineBottler.
