### ISSUE TITLE
winetricks seems to require bash but uses hash bang sh 

### ISSUE THREAD

**Issue by miesi** [Winetricks/winetricks#672]
Downloaded winetricks today (2016-SEP-27) on my openindiana box. Started it and got confusing messages about "command 'local' not found in line 522".

First line of winetricks reads #!/bin/sh

/bin/sh on openindiana is really stoneage SysV Bourne Shell. It does not have a local builtin.

Changed sh to bash, now winetricks works fine.

Is there a chance to modify #!/bin/sh to #!/bin/bash in upstream?

**Comment by austin987** [comment]
'local' isn't a bash builtin, but you're right that it's not POSIX.

I'd rather just avoid uses of local than require bash.

**Comment by austin987** [comment]
@miesi could you tell me if 'command -v' works on OpenIndiana's /bin/sh? E.g., 'command -v sh' should return /bin/sh with exit code of 0, 'command -v sh123' should return null with an exit code of 1.

**Comment by miesi** [comment]
@austin987 Thanks for looking into this.

/usr/bin/command is available on OpenIndiana and tagged as Interface Stability: Committed. It is probably available on Solaris too.

'/usr/bin/command -v sh' returns /bin/sh

/bin/sh is a link to ksh93.

'command -v sh123' exits with a rc of 1.

**Comment by austin987** [comment]
Ok, https://github.com/Winetricks/winetricks/commit/2fda60f4782c6c36b640933597242f1fd8417292 and https://github.com/Winetricks/winetricks/commit/94d899e716100ff308146d46e0e26751d64b7532 should help.

Please report any further issues as separate bugs.

**Comment by miesi** [comment]
@austin987 works fine, thanks for your prompt reaction.
I still have issues to install dotnet452. But I guess it is unrelated to this issue.
