### ISSUE TITLE
Installing wmp9 cause services.exe crash on Wine any job (wmp10 and codecs for wmp could be affected too)

### ISSUE THREAD

**Issue by Crazy-Yuri** [Winetricks/winetricks#673]
**Test suite:**
- Latest Ubuntu Mate LTS
- Latest Wine staging
- Latest winetricks

**Steps to reproduce:**

1. Download and install latest Wine staging (1.9.19)
2. Download latest winetricks
3. Install wmp9
4. Try to install something more

**About:**
It isn't a "hard" fault but annoying. You need to repeatedly close that error window to do something.

**Additional info:**
[WineHQ Forum thread](https://forum.winehq.org/viewtopic.php?f=8&t=27605)

**Solution:**
[MS Support page](https://support.microsoft.com/en-us/kb/315345)

**Comment by slackner** [comment]
This is actually a Wine bug, and not an issue in winetricks itself.
I have sent a patch to fix it: http://source.winehq.org/patches/data/126748

**Comment by austin987** [comment]
Committed upstream, thanks @slackner 
https://source.winehq.org/git/wine.git/commitdiff/2035a8c7c84a5375144fdd70f951949ba7c5d818
