### ISSUE TITLE
/usr/bin/winetricks: line 9003: w_workaround_bug: command not found when installing dotnet40 xna40 verbs

### ISSUE THREAD

**Issue by slyscorpion** [Winetricks/winetricks#674]
Hi, 

I have just updated to the latest version of winetricks ( 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 ) and I ran the following command: 

`winetricks dotnet40 xna40`

on a clean 32-bit prefix for Wine 1.9.20. 

I looked at the terminal output and I noticed this line: 

/usr/bin/winetricks: line 9003: w_workaround_bug: command not found

Full terminal output is in this pastebin: http://pastebin.com/WLeEQekL

I am not sure if it's a bug or not but I thought I'd mention it in case it might affect something else.

**Comment by austin987** [comment]
Thanks for reporting!
