### ISSUE TITLE
riched30 404 error

### ISSUE THREAD

**Issue by reckus** [Winetricks/winetricks#675]
> Executing w_do_call riched30
> Executing load_riched30
> Downloading http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe to /home/lesbeauxxx/.cache/winetricks/riched30
> --2016-10-03 15:27:46--  http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe
> Resolving download.microsoft.com (download.microsoft.com)... 184.25.25.72, 2001:218:3003:29f::e59, 2001:218:3003:292::e59
> Connecting to download.microsoft.com (download.microsoft.com)|184.25.25.72|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2016-10-03 15:27:46 ERROR 404: Not Found.
> 
> ------------------------------------------------------
> Downloading http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe failed
> ------------------------------------------------------

As you may see above, there occurs a 404 error wile installing riched30.
I tried to download the file through another route but was in vain.
I hope the link of files gets repaired soon.

Thanks in advance.

**Comment by austin987** [comment]
Update your winetricks, it will download it from archive.org if the link is dead.
