### ISSUE TITLE
Unable to install dotnet40

### ISSUE THREAD

**Issue by alexal** [Winetricks/winetricks#677]
Using winetricks 20161005 - sha1sum: eb7868b98a664744f033a98f22179ff797bde56a with wine-1.9.20-59-g7756d6b
Executing w_do_call dotnet40
## dotnet40 does not yet fully work or install on wine.  Caveat emptor.

Executing w_do_call remove_mono
## Mono does not appear to be installed.

The operation completed successfully
Executing rm -f /Users/allyse/.wine/dosdevices/c:/windows/system32/mscoree.dll
Executing cd /Users/allyse/.cache/winetricks/dotnet40
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
fixme:process:SetProcessDEPPolicy (3): stub
fixme:clusapi:OpenCluster ((null)) stub!
fixme:clusapi:ClusterOpenEnum (0xdeadbeef, 4) stub!
fixme:clusapi:ClusterEnum (0xdeadbeef, 0, 0x32f850, 0x1461b0, 261) stub!
fixme:clusapi:ClusterCloseEnum (0xdeadbeef) stub!
fixme:clusapi:CloseCluster (0xdeadbeef) stub!
fixme:advapi:DecryptFileW (L"C:\eaf5d720c1dd1468822860\", 00000000): stub
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:ntdll:EtwRegisterTraceGuidsW (0x6cd15f38, 0x6cd20180, {e2821408-c59d-418f-ad3f-aa4e792aeb79}, 1, 0x33fb40, (null), (null), 0x6cd20188): stub
fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2821408-c59d-418f-ad3f-aa4e792aeb79}
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
fixme:process:SetProcessDEPPolicy (1): stub
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
fixme:thread:SetThreadStackGuarantee (0x33fb58): stub
fixme:advapi:LsaOpenPolicy ((null),0x33f410,0x00000001,0x33f42c) stub
fixme:advapi:LsaClose (0xcafe) stub
err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111
err:ole:create_server class {88d96a05-f192-11d4-a65f-0040963251e5} not registered
fixme:ole:CoGetClassObject CLSCTX_REMOTE_SERVER not supported
err:ole:CoGetClassObject no class object {88d96a05-f192-11d4-a65f-0040963251e5} could be created for context 0x17
Assertion failed: (i<len), function ME_SplitByBacktracking, file ../../../wine-source/dlls/riched20/wrap.c, line 500.
fixme:advapi:LsaOpenPolicy ((null),0x338350,0x00000001,0x33836c) stub
fixme:advapi:LsaClose (0xcafe) stub
fixme:thread:NtQueryInformationThread Cannot get kerneltime or usertime of other threads
fixme:advapi:RegisterEventSourceW ((null),L"VSSetup"): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00001388,0x0,0x000b,0x000000f6,0x3009b09c,0x6bd204): stub
err:eventlog:ReportEventW L"vssetup"
err:eventlog:ReportEventW L"microsoft .net framework 4 setup"
err:eventlog:ReportEventW L"4.0.30319"
err:eventlog:ReportEventW L"10.0.30319.1"
err:eventlog:ReportEventW L"1"
err:eventlog:ReportEventW L" "
err:eventlog:ReportEventW L"none_ui_interactive_crash"
err:eventlog:ReportEventW L"0x80000101"
err:eventlog:ReportEventW L"0"
err:eventlog:ReportEventW L" "
err:eventlog:ReportEventW L"NIL"
fixme:advapi:DeregisterEventSource (0xcafe4242) stub
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
fixme:richedit:ME_HandleMessage EM_SETMARGINS: stub
Using native override for following DLLs: mscoree
Executing winetricks_early_wine regedit C:\windows\Temp_dotnet40\override-dll.reg
The operation completed successfully

**Comment by austin987** [comment]
Did this work for you previously? I just did a bunch of changes for shellcheck/checkbashisms, so some  breakage wouldn't surprise me, but make check passes here..

In any case, please install winbind:
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

I suspect that may be your issue.

**Comment by slyscorpion** [comment]
I just checked version 20161005 - sha1sum: eb7868b98a664744f033a98f22179ff797bde56a and 

`winetricks dotnet40`

worked just fine on a clean 32-bit prefix set to Windows XP.

**Comment by qwertychouskie** [comment]
> In any case, please install winbind:
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.

On Ubuntu, this message can be gotten rid of by installing the `libntlm0` package.

**Comment by jre-wine** [comment]
> On Ubuntu, this message can be gotten rid of by installing the libntlm0 package.

@qwertychouskie are you sure? Here (on Debian, which has the exact same libntlm0 package) installing libntlm0 and libntlm0:i386 doesn't seem to change anything. Installing  winbind however does. Can you please test if/where exactly libntlm0 helps?

Sorry for hijacking this thread.

**Comment by qwertychouskie** [comment]
Maybe both are needed?

**Comment by jre-wine** [comment]
@qwertychouskie No, I uninstalled libntlm0:i386 again and just kept winbind. (I don't want to go into nitpicking here, but as packager I'm very interested to hear about any scenario where libntlm0:i386 is definitely helping.)

**Comment by alexal** [comment]
@austin987,

>> Did this work for you previously? 

No, this is the first time I've tried to install dotnet.

>> In any case, please install winbind:

I'm on macOS Sierra and I've installed libntlm through homebrew, but that didn't resolve the problem.

**Comment by austin987** [comment]
It works for me on El Capitan, I'll try to test in a Sierra VM later in the week.

I recently reworked a lot of stuff, I don't think it broke dotnet40 on macs, but it may have. Could you try:
https://raw.githubusercontent.com/Winetricks/winetricks/3932c05451a144dc827e6a791f3bd655d12a3fec/src/winetricks

and see if it makes a difference at all?

**Comment by alexal** [comment]
@austin987 I was able to install dotnet46 by using that version.

**Comment by austin987** [comment]
@alexal dotnet46 or dotnet40? Your original report was for dotnet40.

**Comment by alexal** [comment]
@austin987 both.

**Comment by bkuczenski** [comment]
I can confirm this problem on stock ubuntu 16.04.1, which runs wine-1.6.2. 
I installed 1.8.5 stable and the error persists. The application is Quicken 2014 deluxe, which requires dotnet40.

**Comment by bkuczenski** [comment]
Here is an error report:
http://pastebin.com/x0piFm2c

**Comment by bkuczenski** [comment]
So I went ahead and installed dotnet46, and the installer ran through a whole bunch of upstream dependencies (all the way back to dotnet 2.0) that were not invoked for dotnet4-- including dotnet4 itself which was successful. Suggests a problem in the dotnet4 dependencies?

**Comment by austin987** [comment]
@bkuczenski can you try dotnet40 in a clean WINEPREFIX and see if it works? Note that master has a fix for dotnet30 sometimes getting hidden in the GUI (if you weren't using -q)

**Comment by aaronfranke** [comment]
Is a clean Wineprefix the only solution to this problem? The installer for .NET Framework claims "Same or higher version of .NET Framework 4 has already been installed on this computer" and therefore won't install, but indeed `ngen.exe` is missing.

**Comment by aaronfranke** [comment]
I used a clean Wineprefix and .NET Framework 4.0 still refuses to install with the message "Same or higher version of .NET Framework 4 has already been installed on this computer". I literally deleted `~/.wine` before running `winetricks dotnet40` and it still doesn't work.

OS: Ubuntu 18.04 64-bit, Wine 4.9 installed from WineHQ repo.

**Comment by austin987** [comment]
Hard to say since i don't know your situation. Are you installing with winetricks or manually? Mono may not have been removed. --force may help, as well.

In any case, this bug is closed. If you have a bug, open a new issue, or try the wine forums if you need user support.
