### ISSUE TITLE
the new download url of win2ksp4 and xpsp3.

### ISSUE THREAD

**Issue by ghost** [Winetricks/winetricks#678]
Because the 2k and xp is out of product lifecycle,the orignal url is out of date.
The newer url of xpsp3 and 2ksp4 is 
"http://download.windowsupdate.com/msdownload/update/software/svpk/2008/04/windowsxp-kb936929-sp3-x86-enu_c81472f7eeea2eca421e116cd4c03e2300ebfde4.exe" .
"http://ftp.anadolu.edu.tr/Service_Packs/Windows_2000/W2ksp4_EN.exe" .

**Comment by tuuc** [comment]
In my opinion,five dlls which were decompression from win2ksp4 is best to decompression from xpsp3.
[atmlib.dll hid.dll msasn1.dll mspatcha.dll winhttp.dll wininet.dll]
Also the win2ksp4 will be useless and no need to download.

**Comment by tuuc** [comment]
It makes me big trouble that instMsiW.exe failed.
The software needs riched20.dll and msls31.dll .
I should get the dlls by decompressing the IE8 installer.which make me nervous and angried.

**Comment by tuuc** [comment]
I'm  expecting you make a newer winetricks script.
Thanks

**Comment by austin987** [comment]
On Oct 9, 2016 1:34 AM, "tuuc" <notifications@github.com> wrote:
>
> Because the 2k and xp is out of product lifecycle,the orignal url is out
of date.
> The newer url of xpsp3 and 2ksp4 is
> "
http://download.windowsupdate.com/msdownload/update/software/svpk/2008/04/windowsxp-kb936929-sp3-x86-enu_c81472f7eeea2eca421e116cd4c03e2300ebfde4.exe"
.
> "http://ftp.anadolu.edu.tr/Service_Packs/Windows_2000/W2ksp4_EN.exe" .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

What version of winetricks, it should be retrieved from archive.org
automatically.

**Comment by austin987** [comment]
On Oct 9, 2016 1:39 AM, "tuuc" <notifications@github.com> wrote:
>
> In my opinion,five dlls which were decompression from win2ksp4 is best to
decompression from xpsp3.
> [atmlib.dll hid.dll msasn1.dll mspatcha.dll winhttp.dll wininet.dll]
> Also the win2ksp4 will be useless and no need to download.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

File a separate issue for that.

**Comment by austin987** [comment]
On Oct 9, 2016 1:46 AM, "tuuc" <notifications@github.com> wrote:
>
> It makes me big trouble that instMsiW.exe failed.
> The software needs riched20.dll and msls31.dll .
> I should get the dlls by decompressing the IE8 installer.which make me
nervous and angried.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

I don't understand what this comment is about at all. This is about bugs in
winetricks, not your emotions.
