### ISSUE TITLE
gui won't work anymore

### ISSUE THREAD

**Issue by sixsixfive** [Winetricks/winetricks#679]
eg:

```
winetricks --gui --verbose mfc40
```

its working fine without the gui flag however with gui there is only an empty progressbar shown

**Comment by austin987** [comment]
On Oct 9, 2016 5:23 AM, "sixsixfive" <notifications@github.com> wrote:
>
> eg:
>
> winetricks --gui --verbose mfc40
>
> its working fine without the gui flag however with gui there is only an
empty progressbar shown
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Sorry about that. Which GUI/what version of it?

**Comment by sixsixfive** [comment]
zenity 3.8 / qarma git

**Comment by austin987** [comment]
That's a zenity bug as far as I can tell. It works here in zenity-3.18.1.1

**Comment by austin987** [comment]
Also works here in zenity-3.20.0

**Comment by sixsixfive** [comment]
weird i updated zenity and it worked - also there was a bug in qarma hat was almost instantly fixed
