### ISSUE TITLE
Cannot install 64-bit versions of Visual C++ Redists

### ISSUE THREAD

**Issue by bi0shacker001** [Winetricks/winetricks#686]
Winetricks only includes support for 32-bit Visual C++ Redistributables.
64-bit installers for Visual C++ redistributables require unpacking with 7z, followed by installing using "msiexec /i vc_red.msi" in the extracted directory. This functions properly for every iteration of the Visual C++ runtimes, but has only been tested using Wine version 1.9.21.
Please add this functionality for other users, as it is required for certain applications (in my case, it allowed me to successfully install and run Adobe Premiere CS6, which is 64-bit only)

**Comment by qwertychouskie** [comment]
This support already exists, please use the latest version of Winetricks from the repo.

**Comment by bi0shacker001** [comment]
I have run winetricks with --self-update within the last week. Is this not an appropriate way to update the winetricks script?

**Comment by bi0shacker001** [comment]
I have checked my version of winetricks, and it is 20161012. I have confirmed that it only includes options to install the x86 versions of the Visual C++ Redistributables, not the x64 versions, which are required for 64-bit applications, which make the majority of adobe CS6.

**Comment by qwertychouskie** [comment]
https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L8441

**Comment by bi0shacker001** [comment]
The same support does not exist for the 2008 redistributables and earlier, which are required for the CS6 applications.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/0aec016f5300e3f1255f3e4b2c5a96f08c3cb0ea adds 64-bit support to vcrun2008. Please test and reopen if it's not enough.

**Comment by qwertychouskie** [comment]
What about vcrun2005?  That has a 64-bit version too...

**Comment by austin987** [comment]
If someone has an app that needs it, sure. I'm not going to spend the time for no reason though. Open a new issue please.
