### ISSUE TITLE
W2KSP4_EN.EXE no longer available

### ISSUE THREAD

**Issue by samrocketman** [Winetricks/winetricks#691]
Opening a new issue.  This is a continuation of #600.

I have checked out the latest master of winetricks and installed it.  d1c3d3f53491a4534368ba06a3f5ecf005a32936

I still get this exact error as #600.

To get the error I executed:
```
winetricks dlls msasn1
```

```
$ winetricks -V
20140817 - sha1sum: b6ad9287523453a33e443ef2f4bd77f2f7f49e21
$ wine --version
wine-1.9.22
$ uname -rms
Linux 4.4.0-45-generic x86_64
$ head -n1 /etc/issue
Ubuntu 16.04.1 LTS
```

**Comment by qwertychouskie** [comment]
> 20140817 - sha1sum: b6ad9287523453a33e443ef2f4bd77f2f7f49e21
You are still using the old version, upgrade.

**Comment by austin987** [comment]
Additionally, you shouldn't include 'dlls', just `winetricks msasn1`
