### ISSUE TITLE
If wine prefix initialised to win32 at setup, then winetricks checks for installed DLL in syswow64 instead of system32

### ISSUE THREAD

**Issue by brewmanz** [Winetricks/winetricks#693]
bryan@ASUS-K75DE:~$ winetricks
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20161107 - sha1sum: b15c9ab269963a9d51ac7b3193fec4ff34a56fe6 with wine-1.9.22-74-g76e4706
Executing cd /tmp/winetricks.aaUqH5FE
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /tmp/winetricks.aaUqH5FE
--2016-11-08 16:40:07--  https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.100.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.100.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9 [text/plain]
Saving to: ‘LATEST’

100%[======================================================>] 9           --.-K/s   in 0s      

2016-11-08 16:40:08 (1.06 MB/s) - ‘LATEST’ saved [9/9]

Executing cd /home/bryan
Executing w_do_call wininet
Executing load_wininet 
Executing cabextract -q -d /home/bryan/.local/share/wineprefixes/AlpUK32/dosdevices/c:/windows/temp/_wininet -L -F i386/wininet.dl_ /home/bryan/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
Executing cabextract -q --directory=/home/bryan/.local/share/wineprefixes/AlpUK32/dosdevices/c:/windows/system32 /home/bryan/.local/share/wineprefixes/AlpUK32/dosdevices/c:/windows/temp/_wininet/i386/wininet.dl_
Using native,builtin override for following DLLs: wininet
Executing winetricks_early_wine regedit C:\windows\Temp\_wininet\override-dll.reg
------------------------------------------------------
wininet install completed, but installed file /home/bryan/.local/share/wineprefixes/AlpUK32/dosdevices/c:/windows/syswow64/wininet.dll not found
------------------------------------------------------
bryan@ASUS-K75DE:~$

**Comment by austin987** [comment]
@brewmanz I wasn't able to reproduce this. Could you please give instructions, starting with an empty/no WINEPREFIX, on how to create one this see this problem?

**Comment by brewmanz** [comment]
@austin987 
 # ignore crazy formatting (how do you turn off Markdown doing its thing?)
 # Steps to reproduce are:
ls ~/.local/share/wineprefixes # confirm DeleteMe not there
WINEPREFIX=~/.local/share/wineprefixes/DeleteMe WINEARCH=win32 winecfg # create empty win32 called DeleteMe
winetricks # start winetricks
[Select DeleteMe - OK]
[Install a Windows DLL.. - OK]
[Click winhttp - OK]
[note console log about cabextract DLL into windows/system32]
[note error message 'winhttp install completed but installed file ...windows/syswow64/winhttp.dll not found']
[consider that it installed winhttp into windows/system32 but then looked for it in windows/syswow64]
ls ~/.local/share/wineprefixes # confirm DeleteMe has been created

terminal log follows:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
bryan@ASUS-K75DE:~$ ls ~/.local/share/wineprefixes
AlpUK32  _AlpUK_Downloads  IG  MQ  _MQ_Downloads
bryan@ASUS-K75DE:~$ WINEPREFIX=~/.local/share/wineprefixes/DeleteMe WINEARCH=win32 winecfg
wine: created the configuration directory '/home/bryan/.local/share/wineprefixes/DeleteMe'
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
err:mscoree:LoadLibraryShim error reading registry key for installroot
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0cb608, context 0xa48710, init_notify 0, handle 0x127e7b4): stub
wine: configuration in '/home/bryan/.local/share/wineprefixes/DeleteMe' has been updated.
bryan@ASUS-K75DE:~$ winetricks
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20161107 - sha1sum: b15c9ab269963a9d51ac7b3193fec4ff34a56fe6 with wine-1.9.22-113-gb32a0ea
Executing cd /tmp/winetricks.0lo5IaVG
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /tmp/winetricks.0lo5IaVG
--2016-11-10 09:25:22--  https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.100.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.100.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9 [text/plain]
Saving to: ‘LATEST’

100%[===========================================>] 9           --.-K/s   in 0s      

2016-11-10 09:25:23 (1.41 MB/s) - ‘LATEST’ saved [9/9]

Executing cd /home/bryan
Executing w_do_call winhttp
Executing load_winhttp 
Executing cabextract -q -d /home/bryan/.local/share/wineprefixes/DeleteMe/dosdevices/c:/windows/temp/_winhttp -L -F i386/new/winhttp.dl_ /home/bryan/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
Executing cabextract -q --directory=/home/bryan/.local/share/wineprefixes/DeleteMe/dosdevices/c:/windows/system32 /home/bryan/.local/share/wineprefixes/DeleteMe/dosdevices/c:/windows/temp/_winhttp/i386/new/winhttp.dl_
Using native,builtin override for following DLLs: winhttp
Executing winetricks_early_wine regedit C:\windows\Temp\_winhttp\override-dll.reg
------------------------------------------------------
winhttp install completed, but installed file /home/bryan/.local/share/wineprefixes/DeleteMe/dosdevices/c:/windows/syswow64/winhttp.dll not found
------------------------------------------------------
bryan@ASUS-K75DE:~$ ls ~/.local/share/wineprefixesAlpUK32  _AlpUK_Downloads  DeleteMe  IG  MQ  _MQ_Downloads
bryan@ASUS-K75DE:~$

**Comment by Chiitoo** [comment]
**brewmanz**,

Unfortunately, I'm not sure there is a way to turn it off, but one can at least preserve the formatting by using the 'syntax highlighting' of the crazy [GitHub-Flavoured Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

For example:

```
# ignore crazy formatting (how do you turn off Markdown doing its thing?)
# Steps to reproduce are:
ls ~/.local/share/wineprefixes # confirm DeleteMe not there
WINEPREFIX=~/.local/share/wineprefixes/DeleteMe WINEARCH=win32 winecfg # create empty win32 called DeleteMe
winetricks # start winetricks
```

This is done by adding three backticks (```) before and after the block of text you want to preserve (also done by the '<>' (Insert code) button).

**Comment by austin987** [comment]
@brewmanz that works for me. Could you get a log with -v please?

**Comment by austin987** [comment]
@brewmanz, please follow #717. I was able to reproduce with clearer instructions. I'm still working on the fix.
