### ISSUE TITLE
OSX El Capitan compatibility

### ISSUE THREAD

**Issue by Robotex** [Winetricks/winetricks#695]
After the last update I'm getting the following errors when running winetricks vc2015 or any other package

```
Using winetricks 20161107 - sha1sum: 0e15d200b721f4f3bfcab4a527c0673eb357c289 with wine-1.9.21
pathchk: illegal option -- P
usage: pathchk [-p] pathname...
Executing mkdir -p /Users/Robotex/.cache/winetricks//var/folders/55/n0ll7bpx0yx6n9w8qlkbqgvr0000gn/T//winetricks.kuVjpIy8
Executing cd /Users/Robotex/.cache/winetricks//var/folders/55/n0ll7bpx0yx6n9w8qlkbqgvr0000gn/T//winetricks.kuVjpIy8
Downloading https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /Users/Robotex/.cache/winetricks//var/folders/55/n0ll7bpx0yx6n9w8qlkbqgvr0000gn/T//winetricks.kuVjpIy8
curl: option --retry=3: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
Executing cd /Users/Robotex/.cache/winetricks//var/folders/55/n0ll7bpx0yx6n9w8qlkbqgvr0000gn/T//winetricks.kuVjpIy8
Downloading https://web.archive.org/web/https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST to /Users/Robotex/.cache/winetricks//var/folders/55/n0ll7bpx0yx6n9w8qlkbqgvr0000gn/T//winetricks.kuVjpIy8
curl: option --retry=3: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
------------------------------------------------------
Downloading https://web.archive.org/web/https://raw.githubusercontent.com/Winetricks/winetricks/master/files/LATEST failed
------------------------------------------------------



 Winetricks Commands Finished!!
```

**Comment by austin987** [comment]
Sorry about that, I'll look Monday. What's your curl version?

**Comment by Robotex** [comment]
```
MBP-di-Robotex:~ Robotex$ curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tufts
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
``` 
I temporary went past the errors by manually correcting the parameters in the script, lowercase p for pathchk and replacing
`--retry="$WINETRICKS_DOWNLOADER_RETRIES" \` 
with 
`--retry "$WINETRICKS_DOWNLOADER_RETRIES" \`

**Comment by austin987** [comment]
Thanks for the info. Fyi, pathchk p and P are different, I'll have to
investigate further on that.

On Nov 13, 2016 6:56 AM, "Robotex" <notifications@github.com> wrote:

MBP-di-Robotex:~ Robotex$ curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps
pop3 pop3s rtsp smb smbs smtp smtps telnet tufts
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM
NTLM_WB SSL libz UnixSockets

I temporary went past the errors by manually correcting the parameters in
the script, lowercase p for pathchk and replacing
--retry="$WINETRICKS_DOWNLOADER_RETRIES" \
with
--retry "$WINETRICKS_DOWNLOADER_RETRIES" \

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Winetricks/winetricks/issues/695#issuecomment-260184676>,
or mute the thread

**Comment by Robotex** [comment]
I had used -p because it's the only option that man pathchk returned me and seemed working so I didn't look further at the -P option.
Thanks for the heads up!

**Comment by austin987** [comment]
Right, -P isn't supported on BSD/OSX, but -p is on both, but they're
different.

**Comment by austin987** [comment]
Apparently -P is supported on newer BSD:
https://www.freebsd.org/cgi/man.cgi?query=pathchk&sektion=1

I didn't check when it was added. It's not in OSX, but is in some AIX
versions (not that winetricks supports it ;) ).

Regardless, I plan to add a fallback today/tomorrow.

On Nov 13, 2016 11:15 AM, "Austin English" <austinenglish@gmail.com> wrote:

Right, -P isn't supported on BSD/OSX, but -p is on both, but they're
different.

**Comment by austin987** [comment]
I've pushed fixes for pathchk and curl options here:
https://github.com/Winetricks/winetricks/tree/w_download_fixes

Link to winetricks:
https://raw.githubusercontent.com/Winetricks/winetricks/w_download_fixes/src/winetricks

I'm running the tests for all three downloads, so it will be a while..Once those finish/pass, I'll merge to master.

**Comment by austin987** [comment]
Curl problem is fixed by:
https://github.com/Winetricks/winetricks/commit/12f3209609a15993ac21036c9911ad65dbad684f

pathchk problem by:
https://github.com/Winetricks/winetricks/commit/d2ff9ce0882ca8e1f898f5b98505bad014602e30
