### ISSUE TITLE
mt4 doesn't install for > 4.0.0.1010

### ISSUE THREAD

**Issue by kenorb** [Winetricks/winetricks#698]
Example: [#174469897](https://travis-ci.org/EA31337/FX-MT-VM/jobs/174469897), [#176440439](https://travis-ci.org/EA31337/FX-MT-VM/builds/176440439)

Fail:
```
Executing cd /home/travis/.cache/winetricks/mt4
Executing wine y:\ahk\AutoHotkey.exe C:\windows\Temp\_mt4\tmp.ahk
err:winhttp:netconn_secure_connect send failed
No output has been received in the last 10m0s
```

Steps:

    winetricks mt4

or:

    sh -s mt4 < <(wget -qO- https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks)

Probably sequence of keys has been changed and needs to be updated.

[![bountysource](https://api.bountysource.com/badge/issue?issue_id=39329002)](https://www.bountysource.com/issues/39329002-mt4-doesn-t-install-for-4-0-0-1010)

**Comment by austin987** [comment]
The installer window title changed, fixed by https://github.com/Winetricks/winetricks/commit/f0b4fa10816aa2477dd093aa928230eab15262bf
