### ISSUE TITLE
winetricks allfonts fails with 404 when trying to downlod DroidSans-Bold.ttf

### ISSUE THREAD

**Issue by Culted** [Winetricks/winetricks#701]
http://pastebin.com/dw2GvX8g

getting this error when trying to do winetricks allfonts my winetricks version is

20161107 - sha1sum: ee6251b73e02901cf09738419cd3ae973749770f

downloaded today from github

**Comment by kenorb** [comment]
Based on your log, sounds like there is some extra apostrophe.

    Downloading https://web.archive.org/web/https://github.com/android/platform_frameworks_base/blob/feef9887e8f8eb6f64fc1b4552c02efb5755cdc1/data/fonts/DroidSans-Bold.ttf'?raw=true' failed

It seems to work without it when accessing the URL directly.
