### ISSUE TITLE
.NET 3.5 conflicts with .NET 2.0

### ISSUE THREAD

**Issue by Primalus** [Winetricks/winetricks#703]
Okay so I've looked through some of the other issues with a similar problem as me, and I didn't understand a thing.  I'm using Wineskin to install a program that requires .NET 3.5.  Every time I try and install it, Winetricks installs each previous version of .NET (which is expected).  When I get to .NET 3.5, the installer crashes and I get this error.

```
Executing w_do_call dotnet35

error: dotnet35 conflicts with dotnet20, which is already installed.

Winetricks Commands Finished!!
```

I have no clue as to what I'm doing wrong.  I don't quite understand if Winetricks supports .NET 3.5 (which it should, I assume, since it's in the list of things you can install) or if I'm just doing something wrong.  I've tried creating new wrappers (which I think is somewhat similar to a prefix?), but I still end up with the same error.  I know a little bit about Terminal and how to use it, so if need be, I can try doing it through there.  Any help is greatly appreciated, and sorry if I'm being a total idiot about all of this.

EDIT: I forgot to mention that I'm currently using the latest version of Wineskin (WS9Wine1.9.24) and I'm running macOS Sierra (10.12.1).

**Comment by slyscorpion** [comment]
Try updating your winetricks to the latest version. Also, are you installing dotnet20 via winetricks? The reason I ask is because if you run winetricks dotnet35 (without installing dotnet20) it should pull all the other versions of dotnet including 2.0 on its own...

**Comment by slyscorpion** [comment]
I have just ran "winetricks dotnet35" on a clean 32-bit prefix and here's my terminal output: 

http://pastebin.com/HxRJLik7

In short, the installation was successful. With dotnet it's best to install it first before installing anything into a given Wine prefix as dotnet versions installed by Windows programs may not register properly in Wine.

**Comment by Primalus** [comment]
Alright so I've made a new 32-bit prefix and did the command that you mentioned after launching Wine Devel (winetricks dotnet35).  My winetricks is already updated.  Here's my terminal output

http://pastebin.com/rt6T6kee

**Comment by austin987** [comment]
That's definitely not the latest winetricks (it may be the latest release, but it's missing OS X fixes that are in master).

*** error for object 0x401c1500: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

is also concerning, that may be from wineskin, not sure, I'm not familiar with it.

Anyway, there's nothing about a conflict in that output. Definitely looks like a buggy wine build, IMO, but I'm not certain.

Try asking Wineskin?

**Comment by Primalus** [comment]
I've given up on Wineskin for now and I'm only using Terminal.  I thought I had the latest winetricks, turns out I didn't (thanks for telling me).  I installed the latest (I hope) via Terminal and wget and created a new prefix once more and ran the command again.  This time, I got

http://pastebin.com/fhAg3qUJ

I took a look at the messages it was spitting out and saw that I could try adding '--no-check-certificate' to attempt to get it without viewing the certificate.  I tried typing it in like
```
winetricks dotnet35 --no-check-certificate
```
and got the exact same error.

I also did ask Wineskin a few days ago on their forums.  No response yet.

**Comment by Primalus** [comment]
Alright, so I was finally able to install .NET 3.5.  I re-installed Homebrew, Wine, and winetricks (some of that was probably unnecessary).  It turns out I had to install it in a regular Terminal window, and not through the Wine Staging Terminal window.  So that means that `winetricks dotnet35` works.  Thanks for all of your help!
