### ISSUE TITLE
dotnet30 installation fails with status 8

### ISSUE THREAD

**Issue by rajeshthangaswamy** [Winetricks/winetricks#705]
I need to install Visual C++ 2008sp1 and dotnet is a prerequsite for it. Dotnet20 is getting installed, but dotnet30 always fails with the error "wine netframework3.exe /q /c:install.exe /q' returned status 8.  Aborting". I checked the netframework3.exe, which doesn't have "install.exe" file, instead it has "setup.exe". So I changed the file name in winetricks and tried, still the installation exists with status 8. Could you please help me to solve this issue?. I am using wine version 1.7.14 and winetricks 20141130.

**Comment by slyscorpion** [comment]
Your winetricks and Wine versions are VERY old. Please update to the latest versions of both and try again :)

**Comment by rajeshthangaswamy** [comment]
Thanks for the suggestion.

**Comment by rajeshthangaswamy** [comment]
I am working with a client machine connected to a group of linux servers, where wine version 1.7.14 is installed. There are some difficulties in updating the wine version in the servers. Instead someone suggested that I can install updated version of wine in some other standalone computer and copy the created folder(.wine) to the server and then it will work with the updated version. I tried this way, but still its working with the old version of the wine(1.7.14) only. Is this way works? or is there any any alternate solution? it will be a great help!

**Comment by austin987** [comment]
In theory copying the WINEPREFIX between machines could work, but it's not guaranteed. Especially if you take a prefix made with a newer version of wine and move it to an older one.

Note that 1.7.14 is not supported upstream any more, either. I can't provide help with it either.

**Comment by rajeshthangaswamy** [comment]
Thanks for the information!

**Comment by lucmp** [comment]
I am having the same problem:

Note: command wget -q -O - http://ipinfo.io/Executing wget -q -O - http://ipinfo.io/ip
[MY_ACTUAL_IP] returned status 8.  Aborting.

I am running Wine Staging 3.21.0. What can I do about it, and why does it need to collect my IP?

**Comment by lucmp** [comment]
$ winetricks --gui --country=unknown
------------------------------------------------------
unknown option --country=unknown
------------------------------------------------------

$ winetricks --country=unknown
------------------------------------------------------
unknown option --country=unknown
------------------------------------------------------

**Comment by austin987** [comment]
See 8d334db8a526f4e4bf906c136b23c45ad4e2f65a. Report this to Debian.
