### ISSUE TITLE
w_wine_version() doesn't support 2.x: integer expression expected

### ISSUE THREAD

**Issue by slyscorpion** [Winetricks/winetricks#708]
Hi, 

I am currently using Wine Staging 2.0-rc2 and when I attempted to install dotnet35sp1 in a 32-bit prefix I received this line in my terminal output just before winetricks started installing msxml3: 

/usr/bin/winetricks: line 2209: test: wine-2.0-rc2 (Staging): integer expression expected

winetricks version 20161228 - sha1sum: b44733e769f77065651db99584ea59c772714d2f

**Comment by austin987** [comment]
Oh boy. This is because w_wine_version() doesn't know how to handle 2.x. It's not a simple change, given the major bump. I'll look after I get back from holiday, unless someone sends a PR first ;)

**Comment by austin987** [comment]
This should be fixed by https://github.com/Winetricks/winetricks/commit/f79f74e85ca1941bfbec821d944849b78334b659
