### ISSUE TITLE
dotnet35sp1: winetricks cannot find the logo.bmp file

### ISSUE THREAD

**Issue by slyscorpion** [Winetricks/winetricks#709]
Steps to reproduce: 

1. Use Wine Staging 2.0-rc2.
2. Make a clean 32-bit prefix
3. run "winetricks dotnet35sp1" 
4. Receive the following message at the end: 

dotnet35sp1 install completed, but installed file /home/mint/.wine/dosdevices/c:/windows/Microsoft.NET/Framework/v3.5/Microsoft .NET Framework 3.5 SP1/logo.bmp not found

winetricks 20161228 - sha1sum: b44733e769f77065651db99584ea59c772714d2f

**Comment by austin987** [comment]
Is this still an issue?
