### ISSUE TITLE
concrt140 override needed after vcrun2015 install to be able run Kontakt 5.6 Player

### ISSUE THREAD

**Issue by karmux** [Winetricks/winetricks#713]
After installing vcrun2015 I was unable to run Kontakt 5.6 Player. I see that vcrun2015 added bunch of overrides to winecfg but one of them was missing. After overriding `concrt140` I was able to run Kontakt 5.6 Player. Probably fixes running other programs as well that use this dll.

**Comment by karmux** [comment]
Installing second time after deleting ~/.wine it didn't need it anymore.

**Comment by austin987** [comment]
I filed a couple wine bugs:
https://bugs.winehq.org/show_bug.cgi?id=42239
https://bugs.winehq.org/show_bug.cgi?id=42240

and pushed a fix for this, https://github.com/Winetricks/winetricks/commit/4c8d07697931d37afe29adfd19907315dc4a9e5e
