### ISSUE TITLE
[Request] Winetrick to manipulate CheckFloatConstants registry value

### ISSUE THREAD

**Issue by Brainzyy** [Winetricks/winetricks#715]
More info about this setting can be found here: https://wiki.winehq.org/Useful_Registry_Keys

Would it be possible?

**Comment by austin987** [comment]
Here you go:
https://github.com/Winetricks/winetricks/commit/1791ec1f5cdb5ae4682d525e8360eeabd7e12c40

cfc=enabled / cfc=disable

**Comment by Brainzyy** [comment]
@austin987 Thank you very much!
