### ISSUE TITLE
xmllite is broken

### ISSUE THREAD

**Issue by winetaste** [Winetricks/winetricks#719]
I have a localized desktop(german), so winetricks tries to download WindowsXP-KB915865-v11-x86-DEU.exe for xmllite. The links are broken(microsoft.com and archive.org). Links for FRA and JPN from winetricks are broken, too.

Doesn't WindowsXP-KB915865-v11-x86-ENU.exe work for this?

With a english localized desktop download works, but there is an error executing WindowsXP-KB915865-v11-x86-ENU.exe

[winetricks_xmllite.txt](https://github.com/Winetricks/winetricks/files/717804/winetricks_xmllite.txt)

Anyway there is still an official download from microsoft.com for 64 bit:
https://www.microsoft.com/en-US/download/details.aspx?id=12186

You don't need to execute those setups like the x86 versions, just unzip and you find four versions: winxp and win2003, both 32 and 64 bit. The 32 bit version is namend wxmllite.dll. I don't know if it is enough to change the name to xmllite.dll. There is a ENU and a JPN exe. Comparing the dlls: same size, but different sha1sum.

**Comment by qwertychouskie** [comment]
Which Winetricks version?

**Comment by winetaste** [comment]
Using winetricks 20170101 - sha1sum: ed948de8a10666cab5fe393765a9804c532639d0 with wine-2.0-rc5 and WINEARCH=win32

See winetricks_xmllite.txt for the output.

**Comment by qwertychouskie** [comment]
Try unmounting any removable drives and extra partitions and try again. (The log mentions drive "Y")

**Comment by winetaste** [comment]
There was nothing mounted but root and swap. I even plugged out the wireless usb device. I tried again several times with new prefixes and always deleting .cache/winetricks/xmllite/. Now I got the same issue with "c:\\" instead of "y:\\".

Tested on another device(but both with Ubuntu 16.10 64 bit) ummounted everything, but root/swap (and usb mouse and keyboard ;) ). Sometimes it is "c.\\", sometimes it is "y:\\"(this I cannot see in winecfg or explorer though), but always the same: 

[xmllite_error2.txt](https://github.com/Winetricks/winetricks/files/718726/xmllite_error2.txt)

**Comment by winetaste** [comment]
Should I file this bug at winehq.org? Can I try anything more to check, if this is just a matter of my settings(on both systems)?

**Comment by austin987** [comment]
@winetaste, you can file a wine bug for whatever doesn't work with builtin xmllite, but the issue you reported isn't a wine bug but winetricks'.

I just haven't had a chance to look at it yet

**Comment by austin987** [comment]
win7sp1 has xmllite, so let's try using that and see if it works (patch coming shortly)

**Comment by austin987** [comment]
Tested using https://bugs.winehq.org/show_bug.cgi?id=40910

Should be fixed by https://github.com/Winetricks/winetricks/commit/ab24b7a1e94de78a16cd5f01d44e1a421fa5a343.

Please file wine bugs for anything that doesn't work with builtin xmlite. if winetricks xmllite doesn't work, then it's likely a winetricks bug.
