### ISSUE TITLE
Installation of .NET 4.6 (i.e. dotnet46) Fails on my Ubuntu Trusty 16.05

### ISSUE THREAD

**Issue by pmo-19** [Winetricks/winetricks#720]
The problem appears when winetricks installs dotnet30. After clicking the Install button I do see the yellow balloons at start and at the end telling the install was successful, however I do not see anything in the systray (Unity Dash) to click on then I cannot see the window to click on for winetricks to go on to install dotnet46.
The Terminal is waiting for such an event (from the end install window) which does not happen.
Typing `<Ctrl><C>` Will end the winetricks process but later as expected if I restart winetricks to install dotnet46 then I get:

error: dotnet46 conflicts with dotnet20sp1, which is already installed.

It looks like there is then no way to get through ...
Does anyone have a clue on how to get the successful install window for .NET 3.0 in Ubuntu displayed ? Is there a possible way for winetricks to install dotnet46 if I have to relaunch the process ?
It looks like there is then no way to get through ...
Does anyone have a clue on how to get the successful install window for .NET 3.0 in Ubuntu displayed ? Is there a possible way for winetricks to install dotnet46 if I have to relaunch the process ?

**Comment by qwertychouskie** [comment]
Try recreating the prefix, then running `winetricks -q dotnet46`.

**Comment by qwertychouskie** [comment]
Also, what wine and winetricks versions are you using?

**Comment by pmo-19** [comment]
I am creating a new prefix, using winetricks to remove the previous one.
`$ winetricks`
Select the default wineprefix
Delete ALL DATA AND APPLICATIONS INSIDE THIS WINEPREFIX
(this will remove the prefix e.g. ~/.wine)
`$ export WINEPREFIX="$HOME/.wine" WINEARCH=win32`
`$ winecfg`
Install dotnet46 with winetricks:
$ winetricks
I use the latest winetrick script available here., and as well the latest wine-staging:
`$ wine --version`
`wine-2.0-rc5 (Staging)`

When winetricks is aborted you get a dotnet20 or dotnet20sp1 which block any .NET 3.5 or 4.5 or 4.6 anyway. Then you have to restart from scratch.

**Comment by qwertychouskie** [comment]
Does deleting the prefix, then running `WINEARCH=win32 winetricks -q dotnet46` work?

**Comment by austin987** [comment]
Likely a dupe of #708, or the other staging bugs

**Comment by austin987** [comment]
Can you see if https://github.com/Winetricks/winetricks/commit/f79f74e85ca1941bfbec821d944849b78334b659 helps at all?

dotnet20sp2 fails to install for me with staging, but not with vanilla wine, so this may be a staging regression. I've asked slackner to look at it (there are other reports too).

**Comment by sl1pkn07** [comment]
i have a accient version of wine-stagging (1.9.21, from git) and have the same issue. the dotnet20 (pulled by dotnet46) refuse to install due missmatch architecture (install 64bits, found 32) on multiarch prefix

creating a only win32 prefix seems solve the issue

**Comment by austin987** [comment]
@sl1pkn07, so with 1.9.21-staging and a 32 bit prefix, it works? But with 2.0-rc5 and a 32 bit prefix it fails? How does it fail there? What's your version of winetricks?

**Comment by sl1pkn07** [comment]
builded from git today, so is the latet commit

i dont have any other version of wine

**Comment by austin987** [comment]
Last commit isn't helpful information on a bug tracker.

Exact version please, 'winetricks --version'

How did it fail before? The 64 bit prefix warning, or something else? It sounds like you may have hit the hidden dotnet30 installer, such should have a fix now, but the report is unclear so hard to say.

**Comment by sl1pkn07** [comment]
20170101 - sha1sum: 641f73bf60e03b9d946ae36047282efd261228ae

**Comment by pmo-19** [comment]
Well thank you guys for all the feedback, and @austin987 for his intuition of a staging bug.
I have solved the issue on my `Ubuntu Xenial 16.04` (by the way not Trusty and not 16.05) by changing the version of `wine-staging` installed on my Linux to `wine-staging 1.9.24` from `wine-2.0-rc5 (staging)`. This was the last version 9 available. In fact I used the source from `wine-devel` changed the prefix in this source and compiled in my [PPA](https://launchpad.net/~anton+/+archive/ubuntu/miscellaneous) with a `staging debian folder`.
I've read that in order to install `dotnet46` I need to have at least version `1.9.19`.
Today `staging` moved to `wine-2.0-rc6` but I didn't test it, and didn't report a bug yet.

**Comment by austin987** [comment]
@sl1pkn07 that's why you get a warning very early that it  probably won't work. If you're concerned about dotnet30sp1 not warning you, phrase file a separate dedicated bug

@pmo-19, fyi I informed staging, Sebastian suspects a race condition, that staging may expose more. There was a problem with 2.x wine in winetricks, but I fixed it a couple days ago.

**Comment by pmo-19** [comment]
@sl1pkn07 In order to have a clean 32 bit install of wine, may be you should follow the steps I described in my second post:
Use `winetricks` to remove all data and apps in your current wine prefix (beware it will delete the prefix altogether like `$ rm -rf ./wine` but properly with links to installed programs removed as seen from `classicmenu-indicator`).
Then in the Terminal window you will use to install a brand new wine prefix type:
`$ export WINEPREFIX="$HOME/.wine" WINEARCH=win32`
The WINEARCH statement is the one that matter for the 32 bit architecture only.

**Comment by sl1pkn07** [comment]
this prefix is a clear/new prefix created only for this issue

**Comment by austin987** [comment]
And it's 64 bit, which won't work..

**Comment by sl1pkn07** [comment]
then need make refuse install dotnet in a 64bits prefix instead try to install and wait to fail, rigth?

**Comment by sl1pkn07** [comment]
and when python2 reatches the EOL?

https://www.python.org/dev/peps/pep-0373/

**Comment by austin987** [comment]
@sl1pkn07 as I said, don't hijack this thread for your bug. File a new issue for other problems (one bug per issue).

**Comment by sl1pkn07** [comment]
is not the same issue? the OP can't install dotnet46, like me....
