### ISSUE TITLE
err:module:import_dll Library DNSAPI.dll

### ISSUE THREAD

**Issue by Gibbz** [Winetricks/winetricks#722]
Reporting this bug for winetricks.
https://bugs.winehq.org/show_bug.cgi?id=18986#c1 with the solution posted at the bottom.

Basically received the following errror:
fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
err:module:import_dll Library DNSAPI.dll (which is needed by L"C:\\Games\\Siegecraft Commander\\SiegecraftCommander.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Games\\Siegecraft Commander\\SiegecraftCommander.exe" failed, status c0000135

The fix was to edit user.reg:
"*dnsapi"="native" <- replace this line
"*dnsapi"="builtin" < - with this line

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/9f48718e105e46162cef59e12a54c035e06e4b2a
