### ISSUE TITLE
Issue installing MS .NET 3.5 (Dotnet30) on Sierra

### ISSUE THREAD

**Issue by AidanMaps** [Winetricks/winetricks#723]
So I'm attempting to run an .exe using winebottler using the dotnet35 setting - I'll admit that I know nothing about this (just following the recommended install), but couldn't find any fixes on a web search. My computer is a MacBook Pro 2016, running on the Sierra Os, so I'm wondering if it's possibly the OS, but as I said I really have no clue.

<img width="1016" alt="screen shot 2017-01-22 at 8 29 09 pm" src="https://cloud.githubusercontent.com/assets/7908240/22193891/d2e24b4e-e0e2-11e6-90d9-6239f03670dc.png">
These is the initial settings.

<img width="1009" alt="screen shot 2017-01-22 at 8 31 56 pm" src="https://cloud.githubusercontent.com/assets/7908240/22193941/2fd72bee-e0e3-11e6-8cbd-e4f7cfd5649f.png">
Everything runs fine up through here - the wizard works well etc.

<img width="761" alt="screen shot 2017-01-22 at 8 45 30 pm" src="https://cloud.githubusercontent.com/assets/7908240/22194026/c6459c50-e0e3-11e6-89dd-b41c756e5367.png">
The wizard works ok here up until the end - then it minimizes...

<img width="878" alt="screen shot 2017-01-22 at 8 49 13 pm" src="https://cloud.githubusercontent.com/assets/7908240/22194139/933b453e-e0e4-11e6-9fc2-f4f008eceb48.png">
... then this wine window/app? rapidly opens and closes for a couple seconds. After that everything just sits still and nothing changes - I've left it running a couple hours and nothing changes, so I usually just hit the "x" and cancel the install.

[Error Log.pdf](https://github.com/Winetricks/winetricks/files/722805/Error.Log.pdf)
This is the error log if that helps at all.

Hopefully this is enough information for a fix - anything would be appreciated even if it's confirmation that it won't work!
Thanks!

**Comment by slyscorpion** [comment]
Can you try the latest version of Wine without Winebottler https://dl.winehq.org/wine-builds/macosx/download.html and the latest version of winetricks and see if dotnet35 installs without failing?

**Comment by austin987** [comment]
Hi @AidanMaps,

I suspect you're running an older winetricks. Could you try the _really_ latest version, it has a fix (https://github.com/Winetricks/winetricks/commit/ac3d56d3cf8f5a8d5a3bdd484a092d55f01a34e9) that I think will help here.

You can update using winetricks --self-update.

**Comment by AidanMaps** [comment]
I'm so sorry for my ignorance, but how do you install Winetricks via wine? I tried to follow the instructions at https://wiki.winehq.org/Winetricks but the command line they recommended didn't work.

Sorry again!

**Comment by austin987** [comment]
You'll have to ask someone more familiar with winebottler

**Comment by qwertychouskie** [comment]
Try:
```
cd /usr/bin
sudo rm winetricks
sudo wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
sudo chmod +x winetricks
```

**Comment by qwertychouskie** [comment]
Also, make sure you are using the latest Winebottler (1.8-rc4).

**Comment by AidanMaps** [comment]
@qwertychouskie Thanks for replying! I installed home-brew to use Wget, ran those commands in terminal, made sure I had the latest winebottler, and still the same glitch happened. Did I do something wrong possibly?

**Comment by AidanMaps** [comment]
Also, I tried installing dotnet35 via terminal using wine, but just got this:

Aidans-16ish:bin$ wine /Users//Downloads/dotNetFx35setup.exe 
err:module:attach_process_dlls "gdi32.dll" failed to initialize, aborting
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\system32\\winemenubuilder.exe" failed, status c0000005
err:module:DelayLoadFailureHook failed to delay load shell32.dll.SHGetFolderPathW
wine: Call from 0x7b427241 to unimplemented function shell32.dll.SHGetFolderPathW, aborting
wine: Unimplemented function shell32.dll.SHGetFolderPathW called at address 0x7b427241 (thread 000b), starting debugger...
err:module:DelayLoadFailureHook failed to delay load comctl32.dll.InitCommonControlsEx
wine: Call from 0x7b427241 to unimplemented function comctl32.dll.InitCommonControlsEx, aborting
err:module:attach_process_dlls "gdi32.dll" failed to initialize, aborting
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\Users\\\\Downloads\\dotNetFx35setup.exe" failed, status c0000005
Aidans-16ish:bin$ winedevice.exe(9546,0x404ed000) malloc: *** error for object 0x41202a60: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by austin987** [comment]
That's a broken wine build, for sure.

**Comment by AidanMaps** [comment]
Ok, I'll start from scratch. Is there anything other than the .wine folder I should delete before I restart?

**Comment by austin987** [comment]
I'd reinstall / recompile wine, as those functions are definitely implemented and have been for a long time.

Deleting ~/.wine is sufficient, or use a separate WINEPREFIX. Of course, also ensure you have the latest winetricks.

**Comment by AidanMaps** [comment]
Ok, gonna go step by step.
1. I deleted ~/.wine. When I typed in wine, it still said I had wine 2.0.
2. I ran the commands that qwertychouskie provided above. 
3. I tried winetricks --self-update, but it said I didn't have permission, so I ran sudo winetricks --self-update instead, which worked.
4. I ran wine /Users/aidan/Downloads/dotNetFx35setup.exe
5. It gave me this:

err:module:DelayLoadFailureHook failed to delay load shell32.dll.SHGetFolderPathW
wine: Call from 0x7b427241 to unimplemented function shell32.dll.SHGetFolderPathW, aborting
wine: Unimplemented function shell32.dll.SHGetFolderPathW called at address 0x7b427241 (thread 000b), starting debugger...
err:seh:start_debugger Couldn't start debugger ("winedbg --auto 10 36") (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger
err:module:attach_process_dlls "gdi32.dll" failed to initialize, aborting
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\Users\\aidantribble\\Downloads\\dotNetFx35setup.exe" failed, status c0000005


Did I do something wrong?

**Comment by austin987** [comment]
Where did you get wine? Does 'wine notepad' work?

Aside from that, you shouldn't run the exe directly, let winetricks do it for you, as you'll need some workarounds for it to work (otherwise, what's the point of updating/having winetricks ;) )

**Comment by AidanMaps** [comment]
I believe I had it via PlayOnMac a while ago, but I uninstalled that. And no, it doesn't.

My bad! That's a good point, what command would I run to install it?

Thanks again for your patience. :D

**Comment by austin987** [comment]
You'll want to make sure you uninstall that broken wine first.

See https://wiki.winehq.org/MacOS

I don't use OSX so I can't help much beyond that. Try the wine forums if you need more help with it.

**Comment by AidanMaps** [comment]
Ok, got it fully deleted and installed wine 2.0! Ran the wget for winetricks as above, what next?

**Comment by austin987** [comment]
A) Make sure you installed plain wine, not staging (staging seems to have regressed for .Net recently)
B) Delete ~/.wine
C) Ensure 'wine notepad' works
D) I assume you put winetricks in /usr/bin. If not, cd to wherever it is, and chmod it +x.
E) If it's in $PATH (/usr/bin or similar), run 'winetricks -q dotnet35'. If it's not, use './winetricks -q dotnet35'
F) Report results. If it fails, please attach the entire terminal output.

**Comment by AidanMaps** [comment]
Seems like it worked (at least no errors at the end)! Thanks so much! I should be able to go ahead and use winebottler now to install the .EXE, correct?

**Comment by austin987** [comment]
I'd assume so, but I'm not familiar with it :p
