### ISSUE TITLE
Winetricks wininet failing - Wine 2.0

### ISSUE THREAD

**Issue by sysads** [Winetricks/winetricks#724]
Hi

I just installed wine 2.0 and when I run this command "**winetricks wininet**", I get the following error:

------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing w_do_call wininet
Executing load_wininet
Downloading http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE to /home/osboxes/.cache/winetricks/win2ksp4
--2017-01-26 11:26:51--  http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Resolving download.microsoft.com (download.microsoft.com)... 104.105.50.56, 2a02:26f0:d9:29f::e59, 2a02:26f0:d9:288::e59
Connecting to download.microsoft.com (download.microsoft.com)|104.105.50.56|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-26 11:26:51 ERROR 404: Not Found.

Any workaround to this?

**Comment by sysads** [comment]
Never mind, got it working. Workaround can be found in this [post](http://www.linuxhint.com/hearthstone-heroes-warcraft-linux/)

**Comment by qwertychouskie** [comment]
You are using a very old version of Winetricks, upgrading should fix the issue.

**Comment by sysads** [comment]
@qwertychouskie yes I discovered that but the latest update is only available for Ubuntu 16.10 but it also appeared to work for 16.04 and likely 14.04

**Comment by austin987** [comment]
@sysads you can manually updated it, it's a single file to update, see https://wiki.winehq.org/Winetricks

**Comment by christiansiewert** [comment]
The url http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE gives a 404. anyone know what to do?
