### ISSUE TITLE
not able to install dotnet >= 45

### ISSUE THREAD

**Issue by gso** [Winetricks/winetricks#734]
Ref. following issue:

Installation of .NET 3.0 (dotnet30) fails
https://github.com/Winetricks/winetricks/issues/700#issuecomment-279733112

'netframework3.exe' can fail also in a similar manner to 'dotnetfx3.exe', executing the command that failed using wine on the command line alone works fine.

'dotnet40' installs OK (depending only on dotnet30), however dotnet45 and above pulls in dotnet35sp1, and also dotnet20 (which conflicts with dotnet >= 45), before failing in one of the ways as outlined above.

Applies to the current default wine and winetricks install on Ubuntu (wine 1.8), however also stable 2.0, and devel and staging 2.1 (with the latest winetricks).

A workaround:

```
$ wineboot --init
$ wine winecfg  # [ ] change OS to Windows 7
$ wine uninstaller  # [ ] uninstall mono if installed
$ # download .NET 4.52 https://www.microsoft.com/en-gb/download/details.aspx?id=42642
$ wine /opt/NDP452-KB2901907-x86-x64-AllOS-ENU.exe
```
.NET 4.62 will install likewise from what I can gather but with a workaround (involves an alternate download).

**Comment by Turbito** [comment]
I'm not able to install .NET 4.62, installing with silent mode doesn't work neither

In a clean wine 32 prefix
`winetricks dotnet46`
installs .Net 2.0 and
error: dotnet46 conflicts with dotnet20, which is already installed.

**Comment by gso** [comment]
See the workaround in this post 
https://github.com/Winetricks/winetricks/issues/734 - winetricks is not 
able to do this at the moment, however installing manually works OK.

**Comment by gso** [comment]
You need to download an 'un-official re-packed version' by the looks, see the WineHQ DB entry https://appdb.winehq.org/objectManager.php?sClass=version&iId=34702 - you will need also to install it manually (ref. workaround steps outlined above).

4.0 installs fine, for some reason though higher than this pulls in 3.x which installs 2.0 which conflicts with the original version;.NET > 4.0 can though be installed standalone (i,.e., does not actually need 3.x or 2.0, unless they are included by winetricks for other misc. components).

**Comment by caseywatts** [comment]
+1 that `winetricks dotnet45` seems to install `dotnet20`, and then later says `error: dotnet45 conflicts with dotnet20, which is already installed.` 

I'm interested to see where the script that `winetricks dotnet45` is lives - I didn't see it when I searched through this repo.

**Comment by austin987** [comment]
Please test #757

**Comment by austin987** [comment]
@caseywatts https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L6660

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/ddf5c7c059ebc9b78031584cb82332e091c52d28 should fix this.

**Comment by caseywatts** [comment]
I haven't been able to test this, sorry
I thought I could power through, but I don't grok wine/winetricks/etc enough to figure out how to test a branch :x

I think it seems pretty likely that not calling `w_call dotnet35` will fix this issue, I'm hopeful! :)

**Comment by krisives** [comment]
For anyone else having this problem a workaround is to run:

    winetricks --force dotnet452

The installer for .NET 4.0 will run first, which will ask if you want to remove or repair the installation - either option seems to work fine (selecting remove will give you an error that you cannot remove 4.0 in this context, which then proceeds to install 4.5.2 fine)

**Comment by Zibri** [comment]
Whatever I do I get this:
![image](https://user-images.githubusercontent.com/855176/53154916-899ada80-35c4-11e9-9e96-ff24ed610a68.png)

**Comment by qwertychouskie** [comment]
@Zibri If I remember correctly, this does actually mean you need more disk space, despite the error not showing correctly.

**Comment by austin987** [comment]
@Zibri what kind of file system is your prefix on?

**Comment by Zibri** [comment]
Normal root file system on ubuntu standard installation. (ext4)

**Comment by mirh** [comment]
https://bugs.winehq.org/show_bug.cgi?id=33392
In my testing 1.6GB of free space (at least as reported by df) should be about what you need to make the installers happy.
