### ISSUE TITLE
Switching to sha256 checksums instead of sha1

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#737]
Sha1 is considered broken at this point, so we should switch (as @vszakats pointed out in #725). It's something I've considered before, as well.

I was thinking of what that could look like, without breaking compatibility.

Today it occurred to me that we could simply check the length of the checksum. 40->sha1, 64->sha256 (128 for sha512, though I don't think the extra character length is necessary, though in non-scientific tests I just ran on my laptop, 512 was faster than 256). The check would fail for unsupported lengths. After a majority of things are moved from sha1 to sha256, we could add a warning for anything that takes the sha1 code path (i.e., the games..).

I don't have a timeline for this, but it's something I'd like to see done in the near future.

**Comment by austin987** [comment]
@vszakats @lifanov, I've made an alpha patch for this, only tested on Linux for irfranview. I'd appreciate your feedback before I go further (@lifanov particuarly if this works on FreeBSD, I can test Mac next week).

If you have this checked out, simply doing:
$ winetricks -q -v irfranview

will test it. If that works, it's good.

**Comment by vszakats** [comment]
@austin987 Which one is the test branch to check out?

**Comment by austin987** [comment]
@vszakats sorry about that! It's on my personal fork:
https://github.com/austin987/winetricks/tree/sha256sum

as I mentioned, only 'winetricks -q irfranview' is worth testing at this point. But i'd appreciate your appreciate your feedback for FreeBSD (I added a sha256 fallback)

**Comment by vszakats** [comment]
Thanks! (I should have checked there :)

On Mac, it says `unsupported shasum..bug`. It is because `_W_sum_length` gets the value ` 64` (note the leftmost space). If that's trimmed (also in the verification phase), it works fine.

**Comment by austin987** [comment]
Cool. Like I said, I'll test mac next week when I'm in the office.

Glad it works on FreeBSD! I appreciate your quick testing!

I'll likely do more testing (and hopefully get solaris tester), before pushing to master.

**Comment by vszakats** [comment]
Just to clarify: I didn't test on FreeBSD, only on Mac.

**Comment by austin987** [comment]
Sorry, I mixed up you and @lifanov. Thanks for testing on Mac though!

**Comment by lifanov** [comment]
This works on FreeBSD!

**Comment by lifanov** [comment]
Hold on, I tested the wrong thing. Retesting...

**Comment by lifanov** [comment]
I don't see $WINETRICKS_SHA256SUM defined anywhere...
There is this for sha1sum:

```
winetricks_get_sha1sum_prog() {
    # Mac folks tend to not have sha1sum, but we can make do with openssl
    if [ -x "$(which sha1sum 2>/dev/null)" ]
    then
        WINETRICKS_SHA1SUM="sha1sum"
    elif [ -x "$(which openssl 2>/dev/null)" ]
    then
        WINETRICKS_SHA1SUM="openssl dgst -sha1"
    else
        w_die "No sha1sum utility available."
    fi
}
```

**Comment by lifanov** [comment]
Note that macOS and FreeBSD share the same utilities for sha1 and sha256 (these are just hardlinks for md5, which implements all checksum types).

**Comment by austin987** [comment]
@lifanov sorry about that. I had some more fixes locally that I thought I had committed, but were sitting there when I ran git diff :/

I've just done a force push that should work (at least, it does on Debian)

**Comment by lifanov** [comment]
Getting close! I still get this: "Unknown arg irfranview"

**Comment by austin987** [comment]
Should be irfanview, not irfranview

**Comment by vszakats** [comment]
Answer on the `wc` leading space issue on certain *nix systems (AIX, macOS, Solaris): https://stackoverflow.com/questions/30927590/wc-on-osx-return-includes-spaces/30927885#30927885

**Comment by vszakats** [comment]
It seems my report was misunderstood. OSX does have `shasum`, that the original patch required, but the return value of `wc -c` did not match with `64` because of the leading space `_64` it returned. If this is fixed, `shasum` works just fine, and it's part of the OS (as of Sierra). The subsequent update tries to use `sha256sum`, which in turn DOES NOT exist on macOS.

**Comment by vszakats** [comment]
Example code:
```shell
#!/bin/sh

sum="$(printf '%s' "$(shasum -b -a 256 "$0" | grep -i -o -E '^[0-9a-f]{64}')")"
echo "__${sum}__"
len="$(printf '%s' "${sum}" | wc -c)"
echo "__${len}__"

echo 'FAIL'
case "${len}" in
   64) echo 'sha256';;
   *) echo 'unrecognized';;
esac

echo 'OK'
case "${len}" in
   *64) echo 'sha256';;
   *) echo 'unrecognized';;
esac
```

[Probably there exist more elegant fixes than `*64`]

**Comment by lifanov** [comment]
OK, so before I had this:
```
+ _W_sum_length='      64'
+ w_die 'unsupported shasum..bug'
+ w_warn 'unsupported shasum..bug'
```

Doing either one of these makes "./src/winetricks -q -v irfanview" pass:
```
-    _W_sum_length="$(echo "$_W_sum" | tr -d "\n" | wc -c)"
+    _W_sum_length="$(echo "$_W_sum" | tr -d "\n" | wc -c | tr -d ' ')"
```

```
-    case "$_W_sum_length" in
+    case "${_W_sum_length##* }" in
```

**Comment by vszakats** [comment]
@lifanov This should work fine on Mac, too. (if applied to the _original_ patch)

**Comment by lifanov** [comment]
This works even better and is POSIX-compliant (already tested too):
```
diff --git a/src/winetricks b/src/winetricks
index f7b301c..8382a16 100755
--- a/src/winetricks
+++ b/src/winetricks
@@ -835,8 +835,7 @@ w_download_to()
     fi
 
     # fixme not ready yet
-    _W_sum_length="$(echo "$_W_sum" | tr -d "\n" | wc -c)"
-    case "$_W_sum_length" in
+    case "${#_W_sum}" in
          40) _W_shatype="sha1" ;;
          64) _W_shatype="sha256" ;;
          # 128) sha512..
```

**Comment by austin987** [comment]
I prefer the tr -d ' ' approach, as I find it more readable (this isn't on embedded, so an extra tr on a desktop isn't a big deal..).

I've pushed some fixes that work for me on linux (tested with irafanview and steam). I can test this on OSX on Tuesday. https://github.com/austin987/winetricks/commit/1345fb7175403d8b33ab06a5b4e3750dd5a1e481

(I suspect it will work based on the patches flying by here, but the discussion has gotten a bit muddled).

**Comment by vszakats** [comment]
Just to confirm that https://github.com/austin987/winetricks/commit/1345fb7175403d8b33ab06a5b4e3750dd5a1e481 does work correctly on macOS Sierra.

**Comment by austin987** [comment]
Great, thanks for testing @vszakats!

**Comment by austin987** [comment]
I've pushed initial sha256 support:
https://github.com/Winetricks/winetricks/commit/bc39895d3fdcbfa3344ddc62b79efd7550c7063b
and converted irfanview:
https://github.com/Winetricks/winetricks/commit/b964bfaf78a8ab1f4a57ff743af6d4155d32621e

I'll migrate the rest as I have time. If anyone reading this is considering helping, please do one package per commit (one PR is fine).

**Comment by lifanov** [comment]
Hi! https://github.com/Winetricks/winetricks/commit/bc39895d3fdcbfa3344ddc62b79efd7550c7063b reverts the mention that "fetch" now works. Can you add it back please?

**Comment by lifanov** [comment]
Another nitpick: OS X has been rebranded to macOS.

**Comment by austin987** [comment]
@lifanov sorry about that. Technically it was still there, the line was duplicated during a rebase and I missed it. Fixed that in 539034f146646c2e189796ff8da45e892feb148c.

Regarding OSX/OS X/macOS, technically, only Sierra is macOS. According to Wikipedia:
10.5 - 10.7 are Mac OS X
10.8 - 10.11 are OS X
10.12 is macOS

I don't particularly feel like keeping up with Apple's renaming merry go round (especially since it's only in a comment, not anything user visible). (Mac) OS X is still widely used and recognized, e.g., today I noticed that golang still uses it: https://golang.org/, as does Chrome: https://www.google.com/intl/en/chrome/browser/desktop/index.html?platform=mac.

**Comment by vszakats** [comment]
This was well-timed :)
https://shattered.it/

**Comment by austin987** [comment]
This is mostly done, as of https://github.com/Winetricks/winetricks/commit/378acce23f47332b6ab7b6c0cf9bb54cd084f8b4

I need to add warnings, and clean up some remaining bits. Verbs that don't have downloads are still vulnerable, however.

**Comment by austin987** [comment]
Warnings added. All that's left on sha1 is gog stuff, and a purchase only monkey island game. The rest were converted or removed.
My rough grep count shows 99 sha256, 10 sha1:
austin@debian-laptop:~/src/winetricks$ grep -w -E '[0-9a-f]{40}' src/winetricks | grep -v -e DROID_URL -e file1=  | wc -l
10
austin@debian-laptop:~/src/winetricks$ grep -w -E '[0-9a-f]{64}' src/winetricks | grep -v -e DROID_URL -e file1=  | wc -l
299

https://github.com/Winetricks/winetricks/commit/0938309c84100b7720971bf0c6b03055818f935e

I plan to remove anything still on sha1 in roughly a year, if no one updates it.

**Comment by MinecrafterWael** [comment]
I keep getting this bug :(

$ winetricks -q "./unity3d.verb"
Using winetricks 20190615-next - sha256sum: 47304e177f259d6f9c05af01ab42c06531fd8a9716e2751d2fadcd664130feea with wine-4.0.1 and WINEARCH=win32
Executing w_do_call unity3d
Executing load_unity3d 
Executing w_do_call tahoma
tahoma already installed, skipping
Executing w_do_call corefonts
corefonts already installed, skipping
------------------------------------------------------
unsupported shasum..bug
------------------------------------------------------

**Comment by austin987** [comment]
It's a custom verb so you'll have to update it to sha256sum. sha1sum has been deprecated for 2 years.
