### ISSUE TITLE
comctl32 download url is gone

### ISSUE THREAD

**Issue by frostworx** [Winetricks/winetricks#739]
the 
https://web.archive.org/web/ftp://ftp.ie.debian.org/disk1/download.sourceforge.net/pub/sourceforge/p/po/pocmin/Win%2095_98%20Controls/Win%2095_98%20Controls/CC32inst.exe
url is broken -> 404

sourceforge mirror md5 from here is ok:
https://de.osdn.net/projects/sfnet_pocmin/downloads/Win%2095_98%20Controls/Win%2095_98%20Controls/CC32inst.exe/

**Comment by austin987** [comment]
Thanks for the report. I updated to a link found on http://www.filewatcher.com/m/CC32inst.exe.587496-0.html

Fixed by https://github.com/Winetricks/winetricks/commit/cf2a3cb2a01163892a1c657845498470318b92c1
