### ISSUE TITLE
'winetricks allfonts' gets stuck at arial32.exe

### ISSUE THREAD

**Issue by adriansnetlis** [Winetricks/winetricks#740]
I tried downloading the microsoft fonts(tried both - allfonts and corefonts - resulted in the same) and during installation it got stuck in an infinite loop of attempting to install arial32.exe. This is what it outputs:
```
Downloading ftp://ftp.fi.debian.org/gentoo/distfiles/arial32.exe to /home/adriansnetlis/.cache/winetricks/corefonts
--2017-02-22 19:32:57--  ftp://ftp.fi.debian.org/gentoo/distfiles/arial32.exe
           => ‘arial32.exe’
Resolving ftp.fi.debian.org (ftp.fi.debian.org)... 130.230.54.99, 2001:708:310:54::99
Connecting to ftp.fi.debian.org (ftp.fi.debian.org)|130.230.54.99|:21... failed: Connection timed out.
Connecting to ftp.fi.debian.org (ftp.fi.debian.org)|2001:708:310:54::99|:21... failed: Network is unreachable.
Retrying.

--2017-02-22 19:35:07--  ftp://ftp.fi.debian.org/gentoo/distfiles/arial32.exe
  (try: 2) => ‘arial32.exe’
Connecting to ftp.fi.debian.org (ftp.fi.debian.org)|130.230.54.99|:21... 
```
What is weird is that all the other fonts before this one install fine. Also it won't continue with the next fonts, but instead just infinetly loop at this one. Is there a solution for this?

**Comment by austin987** [comment]
Works here, probably a temporary issue on Debian's end (or your ISP).

**Comment by adriansnetlis** [comment]
Can you see if that link is valid and online? I am not quite sure what ftp is and how to check that link...

**Comment by austin987** [comment]
It's File Transfer Protocol, and old protocol for transferring files over a network.

You can test it in any browser. This worked for me in Chromium, as well as downloading (after removing the old files) with aria2c with winetricks.

**Comment by adriansnetlis** [comment]
When I try to open ftp://ftp.fi.debian.org/gentoo/distfiles/arial32.exe in browser it just loads, loads, loads, loads... *zzz*

**Comment by austin987** [comment]
Right. And it works here. It's likely something with your ISP.

If you have torify installed, you can use -t/--torify to download over tor, which should bypass your ISP's DNS problem.

**Comment by adriansnetlis** [comment]
Where to download it for Ubuntu 16.10? I looked in synaptic package manager and didn't find it...

**Comment by qwertychouskie** [comment]
sudo apt install tor

**Comment by adriansnetlis** [comment]
OK! Installed it. Not clear, though, how to use it...

**Comment by austin987** [comment]
winetricks -q -t allfonts

**Comment by adriansnetlis** [comment]
To be honest, now it stucks at the Resolving part even not getting to connecting.

**Comment by qwertychouskie** [comment]
I would recommend setting your router to use different DNS servers, e.g. 80.80.80.80 or 8.8.4.4
