### ISSUE TITLE
Do we need both xact and xact_jun2010?

### ISSUE THREAD

**Issue by ColdPie1** [Winetricks/winetricks#747]
I wanted to install native xact DLLs, so I ran "winetricks xact". There were two issues:

1) load_xact expects 2_7 to be installed (see for-loop near the end), but only 2_0 through 2_6 are installed with this verb.

2) More importantly, I wanted all available xact DLLs to be installed. For that I needed xact_jun2010. Is it useful to separate these verbs? If so, should jun2010 be the default since it "does more"?

**Comment by austin987** [comment]
So I dig some digging, the only differences seem to be xaudio2_7.dll is added, along with xactengine3_7.dll, xapofx1_5.dll's sha1sum changes:

austin@debian-laptop:/tmp$ diff -ur xact xact_jun2010 
--- xact	2017-03-22 03:02:33.240150013 -0500
+++ xact_jun2010	2017-03-22 03:02:25.372156813 -0500
@@ -599,12 +599,13 @@
 07976c294808651ac8e835154956b7b3e01957f5  xactengine3_4.dll
 c39d7f266b5a8090b95632dfb620d4066d3c078c  xactengine3_5.dll
 56da1a5a1cf78c414dda190a3bf55cbb2ae7bbb1  xactengine3_6.dll
+ceed5e9e80626e67ae5be98ba8aa8d63a6731bfd  xactengine3_7.dll
 9f1ae4dd23913ec43d5c32eaafeca282aafdfb1a  xapofx1_0.dll
 158194d11db048be5fe12cb6c4abe46e6ea807fa  xapofx1_1.dll
 55c01dbb39e6fd682ab9f77e4ccec06f5d81f370  xapofx1_2.dll
 f8c937c62774502960df9321ad1f1d7d0999cddd  xapofx1_3.dll
 3f951a9eb2d50cdd7a0d2210391e14ce9acacc63  xapofx1_4.dll
-3fefad89d458005f361321b4e48d93c464042eed  xapofx1_5.dll
+6edf107e02bf7db7193d1d724cfd2ea5beb3fa8c  xapofx1_5.dll
 f4961e75dc4878ec52ced7a562312c7ea732be1a  xaudio2_0.dll
 546c8566475682e7c55e8140e3e17eddd6f6486f  xaudio2_1.dll
 a3536eb1f08f6ecbc3e15948e67c5f85203a966b  xaudio2_2.dll
@@ -612,7 +613,7 @@
 d62bccc7cf95295ff235a261613b8f7b6fb386a7  xaudio2_4.dll
 40a908b9043699c2a91e67aa132a678463d620c7  xaudio2_5.dll
 a2b70fc91e5e598d1e63ae6f563f4c1f511e2327  xaudio2_6.dll
-b2e19392dc9ef65a51f9922c955b3e7947399b3a  xaudio2_7.dll
+a4113b07de75a83cf1481ea92a3b98e7c1778783  xaudio2_7.dll
 8ef0e56adb3a8292f997320d6821b036c46d1a3f  xaudio2_8.dll
 8f91ef32650a808500118fec2420ea1507484a62  xcopy.exe
 849a25cccafcba51aeb73c9f22ae5a2f532c9506  xinput1_1.dll

Anywho, I think getting rid of xact() and using xact_jun2010 makes sense. I'll push a fix shortly.

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/4381f598a6a29b6f0b437df49fd66877779710d2

**Comment by mirh** [comment]
Remind me again why you aren't switching ***everything*** to jun2010?
