### ISSUE TITLE
comctl32 error 404

### ISSUE THREAD

**Issue by Gibbz** [Winetricks/winetricks#749]
using the commandline 
winetricks -q comctl32

get a 404 error on the download:

Executing cd /home/bronson/.cache/winetricks/comctl32
Downloading https://web.archive.org/web/ftp://ftp.ie.debian.org/disk1/download.sourceforge.net/pub/sourceforge/p/po/pocmin/Win%2095_98%20Controls/Win%2095_98%20Controls/CC32inst.exe to /home/bronson/.cache/winetricks/comctl32
--2017-03-22 21:19:32--  https://web.archive.org/web/ftp://ftp.ie.debian.org/disk1/download.sourceforge.net/pub/sourceforge/p/po/pocmin/Win%2095_98%20Controls/Win%2095_98%20Controls/CC32inst.exe
Resolving web.archive.org (web.archive.org)... 207.241.225.186
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-22 21:19:35 ERROR 404: Not Found.

**Comment by austin987** [comment]
This was addressed as part of b7b7d12486b0f2fc96f065bd0b096f96d2ce72a2
