### ISSUE TITLE
Winetricks freezes trying to set wine-ver to win2k on dotnet45 installation.

### ISSUE THREAD

**Issue by dkanada** [Winetricks/winetricks#756]
I have tried reinstalling multiple times, but when I try to install dotnet45 winetricks will stop on the following command.

`Executing winetricks_early_wine regedit C:\windows\Temp\_dotnet20sp1\set-winver.reg`

It stops there on bspwm and openbox, which ruled out an issue I had a while ago that was due to bspwm not showing a floating window for one of the dotnet installations.

**Comment by austin987** [comment]
I've seen this as well on Gentoo, with 4.9.7 kernel, gcc 4.9.4, but not consistently. Others I've asked have been unable.

What's your distro/kernel/compiler?

**Comment by dkanada** [comment]
Distro: Arch
Kernel: 4.10.6-1
Compiler: gcc 6.3.1-2

Let me know if you need more information or want me to test something.

**Comment by austin987** [comment]
Please test #757, it's not specifically for this, but it likely avoids this problem.

**Comment by dkanada** [comment]
That fixed my issue, thanks for the help!

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/ddf5c7c059ebc9b78031584cb82332e091c52d28 fixes this
