### ISSUE TITLE
[Newbie] Problems on 64-bit prefix

### ISSUE THREAD

**Issue by Flix01** [Winetricks/winetricks#762]
Hello,

- I'm (still?) using Wine 1.7 on Ubuntu 64 bit 16.04.
- I'm using two different wine prefixes: one for 32 bit and another for 64 bit Windows.
- When I use winetricks on my 32 bit prefix, everything works as expected (for example I got direct3d9 and directsound installed and working properly).

My problem is the following:
- When I run winetricks on the 64 bit prefix, winetricks still seems to tell me that all the libraries that are installed on my 32 bit prefix are installed as well (they are still checked). 
However when I try to run 64 bit Windows programs that are using those libraries, the libraries cannot be found (for example:```err:module:import_dll Library DSOUND.dll (...) not found```).

Am I doing something wrong ?

P.S. I know that I'm running winetricks on my 64 bit prefix, because I see the message:
```
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
```

**Comment by Flix01** [comment]
Never mind.

For dsound.dll, I've just placed a 64 bit dsound.dll in the same folder as the exe file and it worked.
I think this approach is good enough for me.

**Comment by EvanSunde** [comment]
where did you find the 64bit dsound.dll 
I am having same problem.

**Comment by Flix01** [comment]
At the time, I had a dual boot system with both Windows and Linux, so I've probably just copied (or linked) the correct dll from my Windows partition.

P.S. I didn't remember posting this... it was more than 7 years ago...
Will you remember having asked me this in 2031?
