### ISSUE TITLE
Cannot run Mine-imator after installing DirectX with winetricks

### ISSUE THREAD

**Issue by cges30901** [Winetricks/winetricks#763]
If I manually install [DirectX runtime](https://www.microsoft.com/en-us/download/details.aspx?id=8109), Mine-imator can run, but if I install directx9 or d3dx9 with winetricks, Mine-imator says DirectX runtime is missing. Do I need to install other verb or is this a bug of winetricks?

**Comment by austin987** [comment]
Does this have a free download?

**Comment by cges30901** [comment]
Yes, you can download Mine-imator from http://www.mineimator.com/dl/mineimator-zip.
I am using wine 2.5 and winetricks 20170327 on Manjaro.

**Comment by austin987** [comment]
winetricks directx9 doesn't help here (nor does -q directx9).

It needs winetricks d3dcompiler_43. That's a wine bug, https://bugs.winehq.org/show_bug.cgi?id=24417
