### ISSUE TITLE
Please revert the commit "Remove Split Second Demo"

### ISSUE THREAD

**Issue by birdie-github** [Winetricks/winetricks#764]
URL: https://www.fileplanet.com/212404/210000/fileinfo/Split/Second-Demo
Direct URL: http://download.fileplanet.com/ftp1/052010/SplitSecondDemo_FilePlanet.exe

SHA1SUM: 72b070712cfe951297263fae143521b45dae16b4
SHA256SUM: 8bd25e16676f50674b173aca81bfc027b97d79f2a4458b59920a2dc6ac9f3a90

Thank you!

**Comment by austin987** [comment]
Send a pr, please

**Comment by birdie-github** [comment]
I've just played this demo - it's beyond awful and equally limited. Let's drop it.
