### ISSUE TITLE
[Suggestion]Would a csmt=on csmt=off setting be a possibility in winetricks?

### ISSUE THREAD

**Issue by slyscorpion** [Winetricks/winetricks#767]
Hi Austin, 

As you may already know, Wine 2.6 has implemented the D3D command stream or CSMT but instead of giving users a nice checkbox toggle like in Wine Staging, it's a registry setting now that has to be edited by going into Wine's registry. 

With that in mind, would it be possible to have a pair of settings in the "Settings" section of winetricks such as 

"csmt=off (default)"
"csmt=on"

This way those of us who are slightly less skilled or wary of diving into the registry can have an easy setting for turning CSMT off or on in Wine 2.6.

**Comment by austin987** [comment]
Sure, https://github.com/Winetricks/winetricks/commit/3f50cf9e6b142b1ed31739f7b7f14bfd07ce7ae0

**Comment by slyscorpion** [comment]
Awesome, thank you very much!

**Comment by slyscorpion** [comment]
Hi Austin, 

Last night I updated my winetricks to the latest version using the --self-update flag and when I set "csmt=on" using winetricks it worked great as an application that I am testing would crash without csmt=on. 

The issue that I am having is actually ensuring that CSMT is turned off after I select "csmt=off" in winetricks. The reason I wanted to turn off CSMT is so I could get the application to crash so I could collect the terminal output and any backtraces to add them to a bug report but now I cannot get the application to crash the way it did before. 

I'll try to summarize this: 

1. Without "csmt=on" the application crashes. 
2. Run winetricks, set "csmt=on", the application works and does not crash. 
3. Now I need the application to crash like it did before I set CSMT to "on" so I run winetricks again and set "csmt=off" and the application continues to work as if I had CSMT set to "on" despite me setting it to "csmt=off"

Am I missing something here? Is there a different way to ensure that the CSMT functions are truly off in Wine 2.6 (non-Staging)?

**Comment by austin987** [comment]
I think I know what's wrong (it should be a DWORD). I'll fix later today.

**Comment by slyscorpion** [comment]
Thank you!

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/35eb15ff45656165dff5e9e173ec5d162144ee2c should fix that
