### ISSUE TITLE
dotnet35sp1 failed

### ISSUE THREAD

**Issue by aligator** [Winetricks/winetricks#770]
Downloading https://web.archive.org/web/https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe failed

**Comment by frostworx** [comment]
https://web.archive.org/web/20061130220825/https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe
looks correct

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/8978b5a0d1683516bbc8197e221d8b857df6b9b7
