### ISSUE TITLE
Needs an online list of wine tricks

### ISSUE THREAD

**Issue by MrStonedOne** [Winetricks/winetricks#771]
I'm on windows trying to help a user use my program in wine, and i need to find the list to jog my memory of the required trick because i know i'll recognize it by name but i can't find a fucking online list any where.

**Comment by austin987** [comment]
Would a .txt file checked into got suffice? That should be easy enough to do for releases

**Comment by austin987** [comment]
Also, in the meantime, here you go:
https://paste.debian.net/928152/

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/f192124d74dac6ab6ed6139501551914e034d198
