### ISSUE TITLE
WinHTTP  sha256sum mismatch

### ISSUE THREAD

**Issue by Talmeron** [Winetricks/winetricks#772]
sha256sum mismatch!  Rename /home/exaurdon/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE and try again.

Which I have done. No go. 

20170327-next - sha256sum: 8721748bd3741238caa6ee22c696dafe24371942351765eb81a42519689efbf7

**Comment by hlx98007** [comment]
It looks like web.archive.org does not store microsoft files required by winetricks anymore.

**Comment by tgharib** [comment]
That's a shame. You would think an archive would be for long-term storage...

**Comment by austin987** [comment]
What app did you need this for? I could move this to use the win7 version, but I'd like to test it against an app that needs it.

**Comment by Talmeron** [comment]
Swtor (star wars the old republic) requires it.

**Comment by austin987** [comment]
Can you point me to a download?  I just keep finding links to sign up. Does it require an account?

**Comment by austin987** [comment]
Or better yet, could you just test this patch from my branch?
https://github.com/austin987/winetricks/commit/d6a81c0fc9a4508e5098c2d13d6202d793df2a05

**Comment by Talmeron** [comment]
Seems to be functioning

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/17dd1fb82953b40c8a5167d8a68249589c1acd34
