### ISSUE TITLE
Some(not sure if all) archive.org links appear to be broken.

### ISSUE THREAD

**Issue by WardenUnleashed** [Winetricks/winetricks#773]
It would appear that many of the archive.org links used to download setup files are no longer functional. Many of the links will work if a date farther back is chosen however as it stands its tedious to have to manually locate each setup file and put it into ./cache

**Comment by psycho23** [comment]
./winetricks ie6
./winetricks msls31

Both times it tries to download this:
Downloading https://web.archive.org/web/https://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe failed

**Comment by austin987** [comment]
I've fixed a couple of these, but a mega bug report isn't nearly as helpful to me as individual bug reports.

FYI, dotnet30 and anything using winxpsp3 are fixed.

**Comment by psycho23** [comment]
> a mega bug report isn't nearly as helpful to me as individual bug reports.

But I thought this bug report was about the missing archive.org links. This is just proof that we have some missing. Unless you desire specific archive.org links, however, the author was pretty broad about which ones are affected:

>It would appear that many of the archive.org links used to download
>setup files are no longer functional.

**Comment by WardenUnleashed** [comment]
Sorry about the broadness. The ones that I specifically had to grab were:

- winxpsp3
- InstMsiW.exe
- msxml3.exe

Sounds like you have it handled!

**Comment by austin987** [comment]
Thanks, I didn't know aobut InstMsiW.exe yet.

I'll fix the rest eventually, but individual (non-duplicate) bug reports are still helpful since then I know what people are actually using ;)
