### ISSUE TITLE
Failed to install wininet W2KSP4

### ISSUE THREAD

**Issue by as3mbus** [Winetricks/winetricks#774]
tried to install wininet 
but keep failing to download the file needed
version : 
20170327-next - sha256sum: 53990170fe073b513d7771b0f97092575e7bb1d6d7df5c537cf951f50a8fabfa
thx :)

**Comment by KaivoAnastetiks** [comment]
I successfully bypassed the error by manually downloading the file from web.archive.org and placing it in `~/.cache/winetricks/win2ksp4/`. It worked from that point. However, it could never download the entire file from web.archive.org through winetricks. Maybe there are more details in #600. 

I tried with the master version on arch linux.

**Comment by 1354092549** [comment]
I can't download the file from web.archive.org
And I find a good download url from #600: 
http://x3270.bgp.nu/download/specials/W2KSP4_EN.EXE

**Comment by as3mbus** [comment]
it works now :+1:

**Comment by austin987** [comment]
A proper fix:
https://github.com/Winetricks/winetricks/commit/3d8e614ac4b498abf70b8604093d3c3f6cd280af
