### ISSUE TITLE
Unable to install dotnet452 or self-update due to certificate errors?

### ISSUE THREAD

**Issue by EeveeEmma** [Winetricks/winetricks#778]
Hi, I'm trying to install .NET 4.5.2 into a fresh wine prefix, but I'm unable to because Winetricks can't verify ssl certificates for some reason. I'm using wine and winetricks installed on OS X 10.12.4 through Homebrew. I also have the latest version of OpenSSL through Homebrew. The specific error I get is: 
```
Self-signed certificate encountered.
To connect to download.microsoft.com insecurely, use `--no-check-certificate'.
```
I wondered if the error was because I didn't have the latest version of Winetricks for some reason, but trying to use the self-updater command produced the same error.
Terminal output of `WINEPREFIX=~/.wine-dotnet452 winetricks dotnet452`: [output.txt](https://github.com/Winetricks/winetricks/files/963714/output.txt)

**Comment by austin987** [comment]
This seems like a more general problem with your system, given that none of the sites have working certs, and there GitHub version check fails..

**Comment by EeveeEmma** [comment]
If it's a problem with my system, do you know how I would go about diagnosing/fixing it? I don't encounter this issue with regular web browsing or other tools I use (for example, Homebrew still works perfectly).

**Comment by EeveeEmma** [comment]
Solved: something was weird with wget, which I solved by reinstalling it through Homebrew.

**Comment by EeveeEmma** [comment]
Solved: something was weird with wget, which I fixed by simply reinstalling it through Homebrew.
