### ISSUE TITLE
Can't install .NET 3.5

### ISSUE THREAD

**Issue by IvanFon** [Winetricks/winetricks#783]
Version:
```
❯ winetricks -V
20170327 - sha256sum: 14b41daecb79991f4b304366720ce41529e992ec7bbacea4ed9b753ecb71620d
```

Console output:
```
Executing cd /home/ivan/.cache/winetricks/dotnet30
Downloading https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe to /home/ivan/.cache/winetricks/dotnet30
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Executing cd /home/ivan/Documents/gms
Executing cd /home/ivan/.cache/winetricks/dotnet30
Downloading https://web.archive.org/web/https://download.microsoft.com/download/3/F/0/3F0A922C-F239-4B9B-9CB0-DF53621C57D9/dotnetfx3.exe to /home/ivan/.cache/winetricks/dotnet30
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Executing cd /home/ivan/Documents/gms
------------------------------------------------------
sha256sum mismatch!  Rename /home/ivan/.cache/winetricks/dotnet30/dotnetfx3.exe and try again.
```

**Comment by qwertychouskie** [comment]
You're using an old version of Winetricks, please update `sudo winetricks --self-update` and try again.

**Comment by IvanFon** [comment]
Thanks, that fixes it. Sorry for the stupid issue, I'll remember to update in the future.

**Comment by qwertychouskie** [comment]
No problem. (Though I think you forgot to close the issue)

**Comment by Tchaikovic** [comment]
> ### 
> 
> > version: 20170823-next - sha256sum: c7201209847509f1ae4bb5a90e622dad5ffb7ca1465091033305c8c558271560
> > 
> > Console output: 
> > DELETE - HKLM\Software\Microsoft\.NETFramework\v2.0.50727\SBSDisabled (null) 0 0 1
> > Error: The system was unable to find the specified registry key or value
> > DELETE - HKLM\Software\Microsoft\NET Framework Setup\NDP\v3.5 (null) 0 0 1
> > Error: The system was unable to find the specified registry key or value
> > DELETE - HKLM\Software\Microsoft\NET Framework Setup\NDP\v4 (null) 0 0 1
> > Error: The system was unable to find the specified registry key or value
> > Executing rm -f /home/lmi5604/.wine/dosdevices/c:/windows/system32/mscoree.dll
> > Executing w_do_call dotnet30
> > Executing load_dotnet30 
> > Executing cd /home/lmi5604/.cache/winetricks/dotnet30
> > Downloading ftp://ftp.softlab-nsk.com/pub/ForwardTxSoftware/DotNetFX123/DotNet_v3/dotnetfx3.exe to /home/lmi5604/.cache/winetricks/dotnet30
> > ^TExecuting cd /home/lmi5604
> > Executing cd /home/lmi5604/.cache/winetricks/dotnet30
> > Downloading https://web.archive.org/web/2000/ftp://ftp.softlab-nsk.com/pub/ForwardTxSoftware/DotNetFX123/DotNet_v3/dotnetfx3.exe to /home/lmi5604/.cache/winetricks/dotnet30
> > Executing cd /home/lmi5604
> > ------------------------------------------------------
> > sha256sum mismatch! Rename /home/lmi5604/.cache/winetricks/dotnet30/dotnetfx3.exe and try again.
