### ISSUE TITLE
[Suggestion]please add a "d3dx9_38" verb if possible

### ISSUE THREAD

**Issue by slyscorpion** [Winetricks/winetricks#784]
Hi Austin, 

I have an application that has this Wine bug https://bugs.winehq.org/show_bug.cgi?id=22682 but in d3dx9_38 rather than d3dx9_36. 

I noticed that winetricks has a verb for d3dx9_36 but not d3dx9_38 and I was wondering if it would be possible to add a d3dx9_38 verb so I can test my application with Wine-git rather than Wine Staging. 

Thanks in advance!

**Comment by austin987** [comment]
Looks like it is in https://github.com/Winetricks/winetricks/blob/master/misc/filelists/directx-jun2010.txt, so simple enough to add.

I'm on holiday, will do when I get back.

**Comment by slyscorpion** [comment]
@austin987  thanks a lot!

**Comment by austin987** [comment]
@slyscorpion here you go:
https://github.com/Winetricks/winetricks/commit/40abf327a0601731b6ca4a4feb5de1c6dcedb5c5

**Comment by slyscorpion** [comment]
@austin987 awesome, thank you!
