### ISSUE TITLE
opensymbol package installation failed

### ISSUE THREAD

**Issue by twdragon** [Winetricks/winetricks#786]
`Executing w_do_call opensymbol
Executing load_opensymbol 
Executing cd /home/twdragon/.cache/winetricks/opensymbol
Downloading http://security.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.2+LibO3.5.4+dfsg2-0+deb7u8_all.deb to /home/twdragon/.cache/winetricks/opensymbol
--2017-05-08 19:05:30--  http://security.debian.org/debian-security/pool/updates/main/libr/libreoffice/fonts-opensymbol_102.2+LibO3.5.4+dfsg2-0+deb7u8_all.deb
Распознаётся security.debian.org (security.debian.org)... 195.20.242.89, 212.211.132.250, 217.196.149.233, ...
Подключение к security.debian.org (security.debian.org)|195.20.242.89|:80... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа... 404 Not Found
2017-05-08 19:05:30 ОШИБКА 404: Not Found.
`

**Comment by qwertychouskie** [comment]
You seem to be using a very old version, please update manually:

    cd /usr/bin
    sudo rm ./winetricks
    sudo wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
    sudo chmod +x ./winetricks

**Comment by austin987** [comment]
This was fixed by https://github.com/Winetricks/winetricks/commit/e17abe557a4d47c8f217a5f147d1f0f0e0878677
