### ISSUE TITLE
unable to install python2.6 

### ISSUE THREAD

**Issue by d78ui98** [Winetricks/winetricks#788]
I am trying to install python26 using `winetricks python26` but, its not working.
here is a small clip of the problem - https://www.youtube.com/watch?v=GiDzry9WBSY&feature=youtu.be

Now my guess is c drive does not exist on kali linux so I tried installing on drive_c but still not working.

**Comment by slyscorpion** [comment]
What version of winetricks do you have?

**Comment by d78ui98** [comment]
1.6.2

**Comment by austin987** [comment]
That would be the version of wine, not winetricks. In any case, it's outdated and no longer supported upstream. I suspect your winetricks is also very old.

You could try using -q, but I'd strongly advise updating.

**Comment by d78ui98** [comment]
doing `winetricks -V` gives this
`20170327-next - sha256sum: 23bd900acd2303cfa6ad2c23a1f76f67e378d1cc930d9a68d99fb8ab5c8b21df`

**Comment by qwertychouskie** [comment]
Why is Winetricks offering 2.6 rather than 2.7?

**Comment by austin987** [comment]
IIRC, originally it was used by Python comtypes, which needed 2.6.

Since then, no one has sent a PR to add 2.7 or 3.x. I'm not sure how much it is used anyway.

**Comment by troizky** [comment]
It's pretty simple to add trick for Python 2.7:
```sh
w_metadata python27 dlls \
    title="Python interpreter 2.7.14" \
    publisher="Python Software Foundaton" \
    year="2017" \
    media="download" \
    file1="python-2.7.14.msi" \
    installed_exe1="c:/Python27/python.exe"

load_python27()
{
    w_download $ABAGY_WINE_DOWNLOAD/python-2.7.14.msi 450bde0540341d4f7a6ad2bb66639fd3fac1c53087e9844dc34ddf88057a17ca

    w_try_cd "$W_CACHE/$W_PACKAGE"
    w_try "$WINE" msiexec /i python-2.7.14.msi ALLUSERS=1 /qn
}
```
