### ISSUE TITLE
winetricks sha256sum mismatch on wininet

### ISSUE THREAD

**Issue by tapwag** [Winetricks/winetricks#789]
Hello everyone,

I am not sure if this is a valid bugreport but I tried:

winetricks wininet

with

Using winetricks 20170327-next

and wine 2.7 on openSUSE Tumbleweed (Rolling Release)

and got the following output:

sha256sum mismatch!  Rename /home/mwagner/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE and try again.

**Comment by qwertychouskie** [comment]
I would try `sudo winetricks --self-update`, as there was a fix merged about two weeks ago (https://github.com/Winetricks/winetricks/pull/775) that should fix your problem.
P.S. don't forget to `rm /home/mwagner/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE`

**Comment by austin987** [comment]
@qwertychouskie it doesn't. https://github.com/Winetricks/winetricks/commit/3d8e614ac4b498abf70b8604093d3c3f6cd280af fixes it properly, though.
