### ISSUE TITLE
dotnet462: link for unofficial download is dead

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#790]
@jasminsehic the link for http://repacks.net/uploads/dotNetFx462_Full_x86_x64_Slim.exe is dead. Please update, or it will need to be removed.

**Comment by jasminsehic** [comment]
@austin987 I have a backup of the file. The author has removed this file in favour of .NET Framework 4.7 which has been released now. I can supply the v4.6.2 somewhere.

**Comment by austin987** [comment]
I have one too, but I don't have a good place to host it. Unfortunately, archive.org didn't cache it, and I'm not aware of another mirror. If you've got a place to host it, that would be fine (I don't want to put binaries in the repo).

**Comment by jasminsehic** [comment]
@austin987 I have added a pull request https://github.com/Winetricks/winetricks/pull/791
File in on my Google Drive now.

**Comment by austin987** [comment]
@jasminsehic I commented on the PR, but the link is giving me 403

**Comment by austin987** [comment]
#791 was merged, thanks
