### ISSUE TITLE
Failed to install qq

### ISSUE THREAD

**Issue by XanthusL** [Winetricks/winetricks#793]
Note: command cabextract -q -d /home/liyiheng/.wine/dosdevices/c:/windows/temp/_riched20 -L -F i386/riched20.dl_ /home/liyiheng/.cache/winetricks/win2ksp4/w2ksp4_en.exe returned status 1.  Aborting.

**Comment by austin987** [comment]
Sorry about that, should be fixed by https://github.com/Winetricks/winetricks/commit/ebdc0685bbf90128b3e21c6db8b82ac15e0dd2e8
