### ISSUE TITLE
Setting Windows versions does not work on win64

### ISSUE THREAD

**Issue by qwertychouskie** [Winetricks/winetricks#795]
Any version sets it to Windows 2008 R2.

**Comment by austin987** [comment]
I don't suppose you could bisect winetricks to see what broke it (or perhaps there was a wine change)?

**Comment by qwertychouskie** [comment]
It seems to only affect 64-bit prefixes.  I tested with WINETRICKS_VERSION=20170101 (from Ubuntu archives) with the same results.

**Comment by austin987** [comment]
@qwertychouskie does https://github.com/Winetricks/winetricks/commit/b7fa9388b9dffd462d0519624d9299c15ae42d39 help for you? In a quick test here it seems to, but it's late..

**Comment by qwertychouskie** [comment]
@austin987 It seems fixed now, thanks!

**Comment by austin987** [comment]
Excellent. That was a fun one to track down..
