### ISSUE TITLE
Add 64-bit support for vcrun2005

### ISSUE THREAD

**Issue by qwertychouskie** [Winetricks/winetricks#799]
Needed for Solidworks.

**Comment by austin987** [comment]
Could you please test https://github.com/austin987/winetricks/commit/eb1d3ba7130955adb416ceb9dbad77dbd30fbe82? Note I didn't find atl80 or vcomp80 in 64-bit versions. If you know of a download, that would be helfpufl.

**Comment by qwertychouskie** [comment]
That only seems to install 3 of the dlls, and why are they extracted from win7sp1 rather than vcredist_x64?  If it is a matter of a download link, here is a copy (from the prereqs folder of the Solidworks 2016 SP2.0 installer):
[vcredist_x64.zip](https://github.com/Winetricks/winetricks/files/1027357/vcredist_x64.zip)

**Comment by austin987** [comment]
Apparently I sucked at googling last night.

It's at https://www.microsoft.com/en-us/download/details.aspx?id=21254, https://www.microsoft.com/en-us/download/confirmation.aspx?id=21254. Working on it.

**Comment by qwertychouskie** [comment]
No problem.  Finding the download you need from Microsoft's website isn't exactly easy...

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/60ef48767ffecf472175352290360a3725c4a475
