### ISSUE TITLE
Installing tahoma fonts fails

### ISSUE THREAD

**Issue by vboufleur** [Winetricks/winetricks#802]
Steps to reproduce:

- Using a clean wineprefix, start winetricks.
- Choose "Install a font"
- Choose "tahoma"
- Installation fails with: ```sha256sum mismatch!  Rename /home/YOUR_USER_NAME/.cache/winetricks/tahoma/tahoma32.exe and try again.```

**Comment by austin987** [comment]
Thanks for the report. Fixed by https://github.com/Winetricks/winetricks/commit/ba7bb0ba92da3f648335867de8aea40b23f7bf42
