### ISSUE TITLE
binkw32/controlspy links are broken

### ISSUE THREAD

**Issue by hunterforcode** [Winetricks/winetricks#803]
https://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa0d76/mdac_typ.exe
https://download.microsoft.com/download/8/d/c/8dc79965-dfbc-4b25-9546-e23bc4b791c6/Q811493_W2K_SP4_X86_EN.exe
http://www.down-dll.com/dll/b/__32-binkw32.dll3.0.0.0.zip
https://download.microsoft.com/download/d/2/a/d2a7430c-6d5b-48e9-96c4-3c751be7bffe/sct10en.exe
https://download.microsoft.com/download/platformsdk/wmi9x/1.5/W9X/EN-US/wmi9x.exe
https://download.microsoft.com/download/IE60/Patch/Q318089/W9XNT4Me/EN-US/vbs56men.exe
https://download.microsoft.com/download/a/3/1/a315b133-03a8-4845-b428-ec585369b285/ControlSpy.msi
https://download.microsoft.com/download/0/A/4/0A40DF5C-2BAE-4C63-802A-84C33B34AC98/WindowsXP-KB978706-x86-ENU.exe

https://download.microsoft.com/download/1/E/5/1E5F1C0A-0D5B-426A-A603-1798B951DDAE/VS2010Express1.iso
https://download.microsoft.com/download/8/1/f/81f9402f-efdd-439d-b2a4-089563199d47/WMEncoder.exe
http://static-akm.imvu.com/imvufiles/installers/InstallIMVU_465.0_st_c.exe
https://download.microsoft.com/download/9/f/6/9f6a95f0-f34a-4312-9749-77b81d3de245/Zoo2Trial.exe

Recent winetricks version got from [here](https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks).

**Comment by austin987** [comment]
I just pushed fixes for most of these, but haven't found suitable mirrors for binkw32 or controlspy

**Comment by slyscorpion** [comment]
Would the RAD Video Tools have the required binkw32.dll file, by any chance? 

http://www.radgametools.com/down/Bink/RADTools.exe

**Comment by austin987** [comment]
Deosn't appear to:
austin@austin2:/tmp/tmp.1c7GoYp7aE$ 7z l RADTools.exe  | grep dll
                    .....         7168      1309031  $PLUGINSDIR/StartMenu.dll
2017-05-18 00:34:54 .....       173568               binkmake.dll
2017-05-18 00:35:00 .....       804864               radutil.dll

there are other versions around, with a different sha256sum. They appear to be more common though, so maybe we were using a bad version. I haven't had time to find an app that needed it and to test the new dll with it yet.

**Comment by slyscorpion** [comment]
@austin987 I am not sure it will help but I think the Tex Murphy: Tesla Effect demo requires bink32 to play the FMV videos. I know the full game requires "winetricks binkw32" in order to play the videos last time I checked...

AppDB entry: https://appdb.winehq.org/objectManager.php?sClass=version&iId=34059

**Comment by barry-denby** [comment]
the links for binkw32.dll no longer exist. thus this does not install correctly

**Comment by austin987** [comment]
Looks like ControlSpyV6 is at https://github.com/pywinauto/pywinauto/blob/master/apps/ControlSpy_20/ControlSpyV6.exe (sha256sum caaa708a7b8d4673508e9ea07e2583a8b463f61fc649c5a2cb45a56c795b9bbf) which matches original).

I'll try to either look at bink32 at same time, or if not, move it to its own bug.

**Comment by austin987** [comment]
Controlspy:
https://github.com/Winetricks/winetricks/commit/742e1215aabed7b43f4e2cdee13f869a2e85bf16

Binkw32: has its own bug now, #1210
