### ISSUE TITLE
winetricks steam won't work

### ISSUE THREAD

**Issue by felixletsplayYT** [Winetricks/winetricks#811]
When I use `winetricks steam` it won't work:

 `2017-06-27 16:32:41 (8,46 MB/s) - »SteamSetup.exe« gespeichert [1446792/1446792]
sha1sum mismatch!  Rename /home/felix/.cache/winetricks/steam/SteamSetup.exe and try again.
`

**Comment by austin987** [comment]
You're running an old version, 6f91e92edd7646c4140d25b03e202b848c308e34 fixed that in October
