### ISSUE TITLE
why is winetricks downloading  mfc42.dll  in german ?

### ISSUE THREAD

**Issue by marxenegls** [Winetricks/winetricks#817]
My location isn't Germany and the language setup on my machine defaults to English . How can i change this to suit my env?  Cmd [dlls list] shows no language options nor does [settings list] .
Or maybe it's just the installer and other lang options are available once dlls re installed ? doubt it though : \ 
thanx

**Comment by austin987** [comment]
Everyone gets the _deu version, it's not langauge specific. The _en download died long ago, this was all that was left.

**Comment by marxenegls** [comment]
aah thanks , i thought it could be something like that but then google found an english version in a heartbeat so the theory kind of subsided .  bon i managed it manually. after downloading it and pushing into the vcrun6 dir then used wine to launch it ,not winetricks cause it would pull the same version again.
