### ISSUE TITLE
`winetricks adobeair` gets stuck on "Installing..."

### ISSUE THREAD

**Issue by seirl** [Winetricks/winetricks#821]
Hello!

When I do `winetricks adobeair` or when I try to install it with AdobeAirInstaller.exe, the installer hangs during the "Installing..." step:

![2017-07-26-104733_496x247_scrot](https://user-images.githubusercontent.com/4927883/28612539-ee626fd6-71ef-11e7-9ab4-274c0544d665.png)

Winetricks version: 20170614 - sha256sum: e641a983e0f9be2602d512292966d07932118ce71354d4ce058847725bfc8fbd

Wine version: wine-2.13

Test setup:

`WINEARCH=win32 WINEPREFIX=~/.wine/prefix/adobeair winetricks adobeair`

There's absolutely nothing interesting in the warnings or debug logs of wine, and I couldn't pinpoint it to anything in the trace either, although I could give them to you if you can't reproduce the bug.

Thanks!

**Comment by seirl** [comment]
The problem seems to disappear after doing `winetricks ie8`.

**Comment by austin987** [comment]
Hi @seirl, I can confirm that it hangs when invoked normally, and ie8 works around it. Another workaround is to use -q for adobeair.

FYI, I filed https://bugs.winehq.org/show_bug.cgi?id=43506 upstream for this.

**Comment by austin987** [comment]
And I added a workaround to winetricks, https://github.com/Winetricks/winetricks/commit/b5a00481ab17ec297dffd90793a468eed0e3486f, that  works w/o requiring IE8
