### ISSUE TITLE
Unable to install dotnet452

### ISSUE THREAD

**Issue by xThatsNotMyName** [Winetricks/winetricks#823]
When I try to install dotnet452 I get this message:

"404 Not Found

The command 'bin/sh -c winetricks dotnet452' returned a non-zero code: 1
"

I´m using the latest version winetricks.
 20170614

![errormessage](https://user-images.githubusercontent.com/30670287/28895086-46be3c54-77d7-11e7-805b-b730a8aa6505.png)

**Comment by forwov** [comment]
winetricks --version
20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924
just update to the latest version. everything is working now. suppose the author or moderator can close this issue.
