### ISSUE TITLE
Kindle for PC is outdated

### ISSUE THREAD

**Issue by prcastro** [Winetricks/winetricks#825]
The version provided by Winetricks isn't supported by Amazon anymore, so it's not possible to login anymore.

**Comment by austin987** [comment]
This is blocked by https://bugs.winehq.org/show_bug.cgi?id=43508 or finding some workaround

**Comment by prcastro** [comment]
Upgrading for a version like 1.16 should solve the issue. While this isn't the most recent version, at least it's possible to login into Amazon's account. Isn't this possible?

**Comment by austin987** [comment]
Probably. I don't use the app personally, couldn't say. Do you have a link to the download, or better yet,  could you send a PR?

**Comment by slyscorpion** [comment]
@austin987  would a filehippo link work? 

http://filehippo.com/download_kindle_for_pc/tech/67858/

AFAIK, they are one of the safer sites for downloading older versions of software...

**Comment by austin987** [comment]
AFAIK they can't be used for automated downloads, it would be manual

**Comment by austin987** [comment]
Does Amazon not have it somewhere? They have the older version that doesn't login, I suspect there's a working link around.

**Comment by slyscorpion** [comment]
@austin987 I believe this is an Amazon link for the installer: 

https://s3.amazonaws.com/kindleforpc/44025/KindleForPC-installer-1.16.44025.exe

**Comment by austin987** [comment]
Looks like it. I won't have time to look until next week at the earliest

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/b1d882fa4082c67ac3f461555bc39694a7c52031
