### ISSUE TITLE
How do I update Winetricks?

### ISSUE THREAD

**Issue by Yoshimaster96** [Winetricks/winetricks#827]
`winetricks -V` gives me:
`20140302`

However, I need Visual C++ Runtime 2015 for a certain application (vcrun2015). How do I update Winetricks so it can find this package?

I'm on Linux Mint 17.3 Cinnamon 64-bit, Cinnamon version 2.8.8, Linux Kernal 3.19.0-32-generic.

**Comment by Chiitoo** [comment]
There might be a source somewhere (probably unofficial), that you could use with the package manager of Linux Mint, but I don't know of one at this time.

I usually don't recommend installing things outside of the package manager, but considering that 'winetricks' doesn't really need to be installed, it might be easiest for you to do it manually.

See for example: https://wiki.winehq.org/Winetricks

The up-to-date version has a '--self-update' option, which one might find useful as well.  :]

**Comment by austin987** [comment]
I update the README:
https://github.com/Winetricks/winetricks/commit/9fe62fc9ad849619edc0b40f07c05e68534c1f81
