### ISSUE TITLE
Firefox only works properly on initial install

### ISSUE THREAD

**Issue by jacklenox** [Winetricks/winetricks#828]
I have installed Firefox using Winetricks, and everything works great. However, if I close it and reopen it, it doesn't seem as though it's able to connect to the internet. There's no startup page, it's just blank. And trying to navigate to a URL results in effectively no response and the browser window remains blank.

If I uninstall and reinstall Firefox, it works again, but only up until I close it again. Any thoughts?

(I'm using Ubuntu 16.04, `wine-2.0.2`)

**Comment by austin987** [comment]
That would be a bug in wine. Note that winetricks is installing an older version, you might try upgrading firefox to see if that helps.
