### ISSUE TITLE
liberation-fonts-1.04.tar.gz URL is no longer working

### ISSUE THREAD

**Issue by mettacrawler** [Winetricks/winetricks#833]
Hi,

This URL downloads an HTML document, not the tarball with the fonts:

https://fedorahosted.org/releases/l/i/liberation-fonts/liberation-fonts-1.04.tar.gz

This URL still works:

http://pkgs.fedoraproject.org/repo/pkgs/liberation-fonts/liberation-fonts-1.04.tar.gz/4846797ef0fc70b0cbaede2514677c58/liberation-fonts-1.04.tar.gz

Thanks,
MC

**Comment by austin987** [comment]
Thanks, https://github.com/Winetricks/winetricks/commit/63bc6dbe612d017a0cb6bf6e4cde265162d75bca

**Comment by mettacrawler** [comment]
You're welcome! :+1:
