### ISSUE TITLE
 Unable to install dotnet35sp1. Some of the download links are broken.

### ISSUE THREAD

**Issue by Rencer** [Winetricks/winetricks#836]
OS: Ubuntu MATE 17.04 64bit
Wine version: wine-2.16 (Staging)

First I made a new 32bit wineprefix, using the "env WINEARCH=win32 WINEPREFIX=~/.wine32 wineboot" commad.
Log: https://pastebin.com/chL5Ad7y

Then, I set this wine installation to Windows XP, using "env WINEARCH=win32 WINEPREFIX=~/.wine32 winecfg".
Log: https://pastebin.com/M6xP29rM

And after this I try to install .Net Frameworks 3.5 SP1 using the command; "env WINEARCH=win32 WINEPREFIX=~/.wine32 winetricks dotnet35sp1".
Log: https://pastebin.com/3KSUEay4

The installation process doesn't eve can start, because some of the download links (see at the end of my winetricks log which are those) are broken so the whole process fail, can't download those files.

PS_1: I run into this broken download links in many other case, when using winetricks.
Some of those links are donwload links from offical Microsoft download page. If I go to MS download page and search them manully, it seems they are there and can be downloaded, but the URL that winetricks using are not correct. The working links are different.

PS_2: EVERY TIME I using winetricks to install something, and the download link is a link to a Wayback Machine (aka web.archive.org) page, those links are ALWAYS broken.
The funny part of this, is that, if I go to the official MS Download, MOSTLY those CAN BE FOUND and can be downloaded from the official Microsoft page,so I don't get the point, why using those (in my case always 100% broken) WaybackMachine links.
Anyway this is really mysterious to me, why all those webarchive links never work for me.

**Comment by austin987** [comment]
A) Your winetricks is out of date:
```
Using winetricks 20170101 - sha1sum: c844fda0cca25ac9ed0ed1b55cd138cab6a4af16 with wine-2.16 (Staging) and WINEARCH=win32
```

B) The wayback machine is a fallback and only called if the original URL is unavailable or has a different checksum. If you know of a specific broken link (in the latest version) and a working link,  please file a bug so I can be updated.
