### ISSUE TITLE
vc2010express unable to install due to unavailability

### ISSUE THREAD

**Issue by jristz** [Winetricks/winetricks#837]
I already tested latest version so the issue persist.

vc2010express.iso was taked down (checked on Sept 16 00:08 +0300) from the lockation that was boing downloaded, there no waybackmachine source so now any program or anything in need of download this it just cant.

The solution is check someother place to download.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/fcfd655fedd9497ff6aca2538f5cbffad6a54eb8
