### ISSUE TITLE
vcrun2017 does not exist in winetricks

### ISSUE THREAD

**Issue by iPenguin67** [Winetricks/winetricks#840]
I am running winetricks version 20170823, and noticed when trying to install the Visual C++ 2017 redistributables through winetricks vcrun2017, that they don't currently exist in winetricks. These appear to be necessary for certain newer games to function (e.g. on Steam).

**Comment by austin987** [comment]
For me later:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e653a57a-bc32-4134-87bf-df33058f0531/download-microsoft-visual-c-2017-redistributable?forum=vssetup

**Comment by austin987** [comment]
@iPenguin67 can you give a sample application which needs this? Preferably one with a free demo/download.

**Comment by iPenguin67** [comment]
The one that led me here was Life is Strange: Before the Storm, though I do not know if that one has a demo. Its predecessor Life is Strange does have a free download, but I'm not sure if that one requires vcrun2017, as it runs natively on Mac.

**Comment by kholbekj** [comment]
Some users are having problems with crashing steamhelpers, and Visual C++ redist has been reported to fix this http://steamcommunity.com/discussions/forum/1/1334600128975781771/#c2741975115074522537

**Comment by BeauBouchard** [comment]
I am very interested in this :D

**Comment by gverm** [comment]
@BeauBouchard this should already have been fixed with: https://github.com/Winetricks/winetricks/commit/471f1bd4aa4235e4b1cb78590d56aff50a9c35e9

**Comment by austin987** [comment]
Yep, already done in 471f1bd4aa4235e4b1cb78590d56aff50a9c35e9. Please open a *new* issue for any problems with it.
