### ISSUE TITLE
Please check dxsdk_jun2010

### ISSUE THREAD

**Issue by tjackson** [Winetricks/winetricks#841]
Hi there. Can you please check the sums on dxsdk_jun2010? 

On my version of winetricks:
20170823-next - sha256sum: c18b8b2d11e74867ea8395dd25f0e88727345dc32673bc01a5061bb344bf56e1 it seems to be wrong.

This is what I got: 9f818a977c32b254af5d649a4cec269ed8762f8a49ae67a9f01101a7237ae61a  .cache/winetricks/dxsdk_jun2010/DXSDK_Jun10.exe

**Comment by austin987** [comment]
I got 
f6914d53cc6c22541782bed1b0350c0e273a2f44252557f3c86c4b74367cc457  /home/austin/.cache/winetricks/dxsdk_jun2010/DXSDK_Jun10.exe

from web.archive.org. I'll have to look into this more later.

**Comment by eplgr** [comment]
Uh, does this mean there's no way to install DXSDK_Jun10.exe right now?
I get the sha256sum mismatch error message when trying to.
@austin987 

>Using winetricks 20171018-next - sha256sum: 9aa6c79e4bfc493c2c769dfd3b60e686c55e5ea2a77ccf91ec6d3b838f6dfdad with wine-2.19 (Staging) and WINEARCH=win32

Which is the latest.

**Comment by AndrewRussellNet** [comment]
Just to add some details here:

I get 9f818a977c32b254af5d649a4cec269ed8762f8a49ae67a9f01101a7237ae61a as the hash for the file, seemingly successfully downloaded from Microsoft.

This **same** file gives the SHA1 hash 8fe98c00fde0f524760bb9021f438bd7d9304a69 -- this is the **same** hash as was replaced in this commit: https://github.com/Winetricks/winetricks/commit/8f780371a3ce3c6f43a240ca5cffdaa5844a467d

So it looks to me like the new hash from that commit is simply wrong (ie: 11a0ddeb...). Recommend simply replacing it with the hash given by myself and @tjackson.

Furthermore, the file on archive.org at https://web.archive.org/web/2000/https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe is simply a different file -- the size does not match (something like 9.5MB vs 571MB) -- and it gives the same hash you listed @austin987. It looks like the file is corrupt (maybe truncated, haven't checked).

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/7e851fabc038848203c61130486fe764cdddce67, sorry about that.
