### ISSUE TITLE
Untranslatable buttons in statistics' window

### ISSUE THREAD

**Issue by TotalCaesar659** [Winetricks/winetricks#847]
In the window with the qustion about statistics reporting, buttons "No" and "Yes" are not translatable on another languages.
![2](https://user-images.githubusercontent.com/14265316/31312335-dcbe4b5c-abc8-11e7-874f-9ee818a566fb.png)
But it's alright on another windows with buttons "Cancel" and "OK".
![1](https://user-images.githubusercontent.com/14265316/31312340-fa7f1694-abc8-11e7-87bc-870bc7815fc8.png)
Could you fix it?

**Comment by austin987** [comment]
Afaict, that's a Zenity issue. You'll notice that the first dialog has 'ok', which isn't Russian.

See also https://stackoverflow.com/questions/24656022/how-to-translate-language-strings-zenity-command-line-utility, which says the Zenity provided portions are translated automatically.

I'd suggest reporting to Zenity, who can likely point you to what needs to be translated on their end. Feel free to CC me (if it's on gnome, I should have a login) or link here and I can help provide more info if needed.

I appreciate your translations!
