### ISSUE TITLE
Depending on your language the installation of dotnet462 fails

### ISSUE THREAD

**Issue by Xalalau** [Winetricks/winetricks#856]
Hello!

"winetricks dotnet462" is crashing with a translation related error here.

Some infos:
- My system is a Linux Mint 18.2 Cinnamon 64-bit set to Brazilian Portuguese (PT-BR);
- The prefix used was a clean .wine folder set to 32-bit;
- The Wine version is 2.17 from [this PPA](https://launchpad.net/~commendsarnex/+archive/ubuntu/winedri3); and
- I got the latest winetricks from the repository ([this version](https://github.com/Winetricks/winetricks/blob/2dcf55e9ee3d7446e297ef78086c4083df7c1904/src/winetricks), to be more accurate).

Well, I started 4.6.2 installation in the quiet mode because .NET 4.6.1 only works this way for me:
```bash
winetricks -q dotnet461
```
The fallowing error appeared on 4.6.2: [https://i.imgur.com/HbfJd1n.jpg](https://i.imgur.com/HbfJd1n.jpg)
Where "Arquivo não encontrado" means "File not found".

So I decided to split the job recreating the prefix, installing .NET from version 4.0 to 4.6.1 on the quiet mode, removing 4.6.2 conflict checks and normally starting its installation:
```bash
winetricks -q dotnet461
sudo sed -i 's/conflicts="dotnet20 dotnet20sdk dotnet20sp1 dotnet20sp2 dotnet35sp1 dotnet40 dotnet46 dotnet461 vjrun20" \\/\\/g' '/usr/bin/winetricks'
winetricks dotnet462
```
The same error: [https://i.imgur.com/j7SwmQc.jpg](https://i.imgur.com/j7SwmQc.jpg)
Anyway, this was just a stupid test driven by curiosity...

Looking at what was inside load_dotnet462() I noticed that we are using an alternative "slim" version because of [a bug in the normal package](https://bugs.winehq.org/show_bug.cgi?id=42170). There is [workaround](https://bugs.winehq.org/show_bug.cgi?id=42170#c8) for it, but I have no idea on how to handle these certificate things.

Since I'm stuck with the slim, I went to check the program parameters. /sfxlang was about the language selection, but the dev didn't supply any detailed information... Therefore I opened the [provided source link](https://repacks.net/forum/viewtopic.php?f=6&t=7) (referenced in winetricks) and instantly found two things: 1) the creator moved the project to .NET 4.7; 2) [the mirror to 4.6.2 was dead](https://repacks.net/forum/viewtopic.php?f=6&t=7&start=20#p600). Also, there was a [comment about some kind of language packs and an old better installer](https://repacks.net/forum/viewtopic.php?f=6&t=7&sid=6045ed35a288be9258e235cce2bcdadf&start=40#p883).

I thought I could solve the problem with these packs so I forgot about the parameters and started digging around a bit more. There I found a preserved [main page containing a lot of language stuff](https://web.archive.org/web/20161211045051/https://repacks.net/forum/viewtopic.php?f=6&t=7), all broken, in addition to, for my surprise, a download of the quoted [older and more stable version of the installer](https://web.archive.org/web/20160827035416/http://my.repacks.space/dotNetFx462_Full_x86_x64_Slim.exe). It didn't crash on my tests!

Sadly I don't like to use aged software, so I decided to took a closer look again at the /sfxlang parameter. The example of usage was /sfxlang:1031, meaning German, and I tried it. OK, I got German and there were no crashes during the installation, so I started to decrement the value until English appeared - luckily it was 1027.

New prefix,  added /sfxlang:1027 to winetricks, ran the full installation on quiet mode:
```bash
sudo sed -i 's/WINEDLLOVERRIDES=fusion=b "$WINE" "$file_package" ${W_OPT_UNATTENDED:+$unattended_args}/WINEDLLOVERRIDES=fusion=b "$WINE" "$file_package" \/sfxlang:1027 ${W_OPT_UNATTENDED:+$unattended_args}/g' '/usr/bin/winetricks'
winetricks -q dotnet462
```
Done, no problems.

[.NET Framework Setup Verification Tool](https://blogs.msdn.microsoft.com/astebner/2008/10/13/net-framework-setup-verification-tool-users-guide/) now gives me only positive results.

After someone confirms this bug, I suggest we include the /sfxlang:1027 parameter in the [winetricks dotnet462 slim installation line](https://github.com/Winetricks/winetricks/blob/2dcf55e9ee3d7446e297ef78086c4083df7c1904/src/winetricks#L7203) or change it by the [older version](https://web.archive.org/web/20160827035416/http://my.repacks.space/dotNetFx462_Full_x86_x64_Slim.exe) I found.

Sorry about any English errors.
Thx!

[EDIT]

[Wine 2.19 was just released](https://www.winehq.org/announce/2.19) with "new Microsoft root certificate". Maybe it can install dotnet462 with the official installer.

**Comment by austin987** [comment]
This was fixed by https://github.com/Winetricks/winetricks/commit/c570ef43263d03bd44a41ff8fae4d4dd8d3817ce (I installed a Brazilian Portugese locale to verify).
