### ISSUE TITLE
Cannot install dotnet462 with winetricks, while I can with plain wine and official installer

### ISSUE THREAD

**Issue by kLeZ** [Winetricks/winetricks#862]
Hi, I tried to install dotnet462 in a win32 prefix, and failed with notorious message "dotnet462 cannot be installed because conflicts with dotnet40".

Then I tried to install the official version download from microsoft.com, and it installed properly, without any single tweak, except for the unattended install (/q).

I tried with wine 2.19 and wine-staging 2.19, both working.

Installed dlls list:
allfonts
msxml3
dotnet40

Using winetricks 20171018-next - sha256sum: 8bad5b1303b91164424b37b21fa67ddea27bd945207751f022c3c9865a1ebdc3 with wine-2.19 (Staging) and WINEARCH=win32

**Comment by frenchiveruti** [comment]
I just realized that even winetricks say:

```
Working around wine bug 38959 
------------------------------------------------------
This installer will fail unless run in quiet mode.
```
When trying to install any dotnet.
Maybe it should halt if the -q option wasn't given.

**Comment by austin987** [comment]
Fixed a while ago by https://github.com/Winetricks/winetricks/commit/cc1126f93b472f1513d65c033c0a02f55c0dd7d4
