### ISSUE TITLE
eufonts doesn't overwrite corefonts, creating duplicates

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#865]
The `corefonts` package copies the following fonts under `.wine/drive_c/windows/Fonts/`:
```
Arialbd.TTF
Arialbi.TTF
Ariali.TTF
Arial.TTF
AriBlk.TTF
Comicbd.TTF
Comic.TTF
courbd.ttf
courbi.ttf
couri.ttf
cour.ttf
Georgiab.TTF
Georgiai.TTF
Georgia.TTF
Georgiaz.TTF
Impact.TTF
Timesbd.TTF
Timesbi.TTF
Timesi.TTF
Times.TTF
Trebucbd.ttf
trebucbi.ttf
trebucit.ttf
trebuc.ttf
Verdanab.TTF
Verdanai.TTF
Verdana.TTF
Verdanaz.TTF
Webdings.TTF
```

Because some of their extensions have caps (`.TTF`), the `eufonts` package (which gets installed by the `allfonts` package) does not overwrite them, since it contains the following font files:
```
ArialBd.ttf
ArialBI.ttf
ArialI.ttf
Arial.ttf
TimesBd.ttf
TimesBI.ttf
TimesI.ttf
Times.ttf
trebucbd.ttf
trebucbi.ttf
trebucit.ttf
trebuc.ttf
Verdanab.ttf
Verdanai.ttf
Verdana.ttf
Verdanaz.ttf
```

Since we'll end up with 2 copies of the same file under `.wine/drive_c/windows/Fonts/`, I'm not sure which one Wine will pick up.

**Comment by austin987** [comment]
@mihaitodor I'm beginning to think that the simplest fix would be to forcibly rename all fonts to lowercase (in all verbs). Given that you work with fonts more extensively than I, do you see any issue with that approach?

**Comment by mihaitodor** [comment]
I have thought about this option too and it's probably a good idea. I doubt Windows / Wine cares about font names having upper or lower case characters, but I can't guarantee. I don't mind doing it and asking for forgiveness later, if you fancy this solution :)

Still, there is still room for error if the user installs some font packages without using winetricks and then tries to install some other font packages via winetricks. To address this issue in a robust manner, my idea is to do something like this:

```shell
w_try_force_cp_files()
{
    # $1 - source files
    # $2 - destination directory

    _W_src_files="$1"
    _W_dest_dir="$2"
    shift 2

    if test -z "$_W_src_files"; then
        w_die "bug: empty $_W_src_files"
    fi

    if test ! -d "$_W_dest_dir"; then
        w_die "bug: missing $_W_dest_dir"
    fi

    _W_src_files=$(echo "$_W_src_files" | sed 's/ /\\ /g')
    _W_src_files=$(ls $_W_src_files)

    for file in $_W_src_files; do
        file_name=$(basename "$file")
        find "$_W_dest_dir" -maxdepth 1 -type f -iname "$file_name" -exec rm '{}' ';'

        w_try cp -f "$file" "$_W_dest_dir/$file_name"
    done

    unset _W_src_files _W_dest_dir
}
```

The `sed` trick might be superfluous, since there will probably be other issues in the caller functions if there are any spaces in the paths (font names don't have spaces in them as far as I can tell, but I'm no expert).

If you like this approach, I wouldn't mind doing a refactor throughout winetricks to call this function instead of direct invocations to `cp -f`.

**Comment by austin987** [comment]
I'd appreciate it. That's roughly what I was thinking about doing, so the
idea sounds great in theory. Thanks for tackling this!

**Comment by mihaitodor** [comment]
@austin987 I'm OK to close this.

**Comment by austin987** [comment]
Kk
