### ISSUE TITLE
winetricks ie7 & ie8 script try to download from dead sites

### ISSUE THREAD

**Issue by orelbon** [Winetricks/winetricks#869]

**Comment by Chiitoo** [comment]
Both, 'ie7' and 'ie8' seem to work here.

Please make sure you're using an up-to-date version of Winetricks.

That said, I'll go ahead and close this.  If the issue still remains, however, feel free to re-open (and please provide the version of Winetricks and Wine that you're using, as well as the terminal output showing a failed run).

Thanks!

**Comment by orelbon** [comment]
My bad, i was using an outdated version.
