### ISSUE TITLE
Winetricks breaks under firejail

### ISSUE THREAD

**Issue by HeraKumi** [Winetricks/winetricks#870]
The issus is I am using Line: Parrot OS and I've installed the latest wine & winetricks but when I use winetricks or winetricks --gui it gives me a error saying

> `Your version of wine 2.20
> Parent
> 
> Parent is no longer supported upstream. You should upgrade to 2.x`

``bug: w_metadata adobeair corrupt, might need forward slashes?`
`

full output
```
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
Your version of wine 2.20
Parent

Parent is no longer supported upstream. You should upgrade to 2.x
------------------------------------------------------
Using winetricks 20171018-next - sha256sum: e6de52519575a6b40ee41164a664f9cc08c8d346d2dfcce87173af589b609dae with wine-2.20 (Debian 2.20-1)
Parent pid 20655, child pid 20660

Parent is shutting down, bye... and WINEARCH=win64
installed_file1="C:\Program Files (x86)\Common Files
Parent pid 20353, child pid 20358
------------------------------------------------------
bug: w_metadata adobeair corrupt, might need forward slashes?
------------------------------------------------------
```

**Comment by austin987** [comment]
A) what does `wine --version` report?
B) pleasantly run winetricks with -v and attach the output.

**Comment by B1gBlu3** [comment]
Same here...

winetricks python26
------------------------------------------------------
Your version of wine 2.0.3
Parent
The

Parent is no longer supported upstream. You should upgrade to 2.x
------------------------------------------------------
Using winetricks 20171018 - sha256sum: b5755e73d886ab161895ee8e33644b19862f65e713ce2384bfe10fac281fe188 with wine-2.0.3 (Debian 2.0.3-1)
Parent pid 96920, child pid 96925
The new log directory is /proc/96925/root/var/log

Parent is shutting down, bye... and WINEARCH=win32
installed_file1="C:\Program Files\Common Files
Parent pid 96593, child pid 96598
The new log directory is /proc/96598/root/var/log
------------------------------------------------------
bug: w_metadata adobeair corrupt, might need forward slashes?
------------------------------------------------------
┌─[✗]─[root@parrot]─[~/.wine-fuzzbunch/drive_c/fuzzbunch-debian/installers]
└──╼ #wine --version
Reading profile /etc/firejail/wine.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: noroot option is not available
Parent pid 97419, child pid 97420
The new log directory is /proc/97420/root/var/log
Child process initialized in 45.63 ms
wine-2.0.3 (Debian 2.0.3-1)

Parent is shutting down, bye...

**Comment by austin987** [comment]
So the problem is firejail spitting out extra information when wine runs, breaking the output format that winetricks expects:
Parent pid 97419, child pid 97420
The new log directory is /proc/97420/root/var/log
Child process initialized in 45.63 ms
wine-2.0.3 (Debian 2.0.3-1).

It's doable, but it would be a decent amount of work.

**Comment by austin987** [comment]
I suspect just running firejail with the quiet setting would improve things; but this will need someone running firejail to debug it:
https://jlk.fjfi.cvut.cz/arch/manpages/man/firejail-profile.5

**Comment by Bebef** [comment]
https://community.parrotsec.org/t/winetricks-bug-w-metadata/1124/3

**Comment by Askmewho** [comment]
this is still a thing winetricks_0.0+20200412-1 ...this was resolved or we have to kept using that firejail?? @austin987

**Comment by austin987** [comment]
@Askmewho I don't quite understand your question; but it's not a winetricks bug. See https://community.parrotsec.org/t/winetricks-bug-w-metadata/1124/3, you need to use `firejail --quiet`
