### ISSUE TITLE
dotnet452 conflicts with dotnet20, which is already installed (again)

### ISSUE THREAD

**Issue by motatuc** [Winetricks/winetricks#873]
Hello,

trying to install dotnet20 and dotnet452 together. Winetricks gives me an error saying: dotnet452 conflicts with dotnet20, which is already installed.

Tried both variants: 

`env WINEARCH=win32 WINEPREFIX=/home/wine/dotnet winetricks  -q dotnet20 dotnet452`

and

`env WINEARCH=win32 WINEPREFIX=/home/wine/dotnet winetricks  dotnet20 dotnet452`

Same thing, dotnet452 never finished. The prefix is clean though. It always hangs at this message which repeats forever: `err:ntdll:RtlpWaitForCriticalSection section 0x110be8 "services.c: scmdatabase" wait timed out in thread 0053, blocked by 0041, retrying (60 sec)
`

Setup: `winetricks 20171018-next - sha256sum: 0b98bc8ff8067004c00fa80a1406449a77a93e30fe067dbbb4db1d0fdd2fbf68 with wine-2.22 and WINEARCH=win32`

**Comment by austin987** [comment]
That's by design.
