### ISSUE TITLE
Download link for dotnetfx3.exe stopped working

### ISSUE THREAD

**Issue by calebeby** [Winetricks/winetricks#874]
ftp://ftp.softlab-nsk.com/pub/ForwardTxSoftware/DotNetFX123/DotNet_v3/dotnetfx3.exe
no longer works. Can you change it to use a different one from this list:
http://www.filewatcher.com/m/dotnetfx3.exe.52770576-0.html

Thanks!

**Comment by NeverMine17** [comment]
Annual bump @calebeby @reedy @adrianbroher @naderhen @scarmiglione

**Comment by NeverMine17** [comment]
## GitHub mirror:
All archives are split using `split` utility. Ignore `.txt` at the end. SHA-1 sum of final exe file is `f3d2c3c7e4c0c35450cf6dab1f9f2e9e7ff50039`.
To merge all these files you can use cat:

    $ cat dotnetfx3.exe-part* > dotnetfx3.exe

[**dotnetfx3.exe-part00.txt**](https://github.com/Winetricks/winetricks/files/1793244/dotnetfx3.exe-part00.txt)
[**dotnetfx3.exe-part01.txt**](https://github.com/Winetricks/winetricks/files/1793245/dotnetfx3.exe-part01.txt)
[**dotnetfx3.exe-part02.txt**](https://github.com/Winetricks/winetricks/files/1793246/dotnetfx3.exe-part02.txt)
[**dotnetfx3.exe-part03.txt**](https://github.com/Winetricks/winetricks/files/1793247/dotnetfx3.exe-part03.txt)
[**dotnetfx3.exe-part04.txt**](https://github.com/Winetricks/winetricks/files/1793248/dotnetfx3.exe-part04.txt)
[**dotnetfx3.exe-part05.txt**](https://github.com/Winetricks/winetricks/files/1793249/dotnetfx3.exe-part05.txt)
