### ISSUE TITLE
cannot install dotnet20sp1 after dotnet20

### ISSUE THREAD

**Issue by JuanPotato** [Winetricks/winetricks#877]
On a clean 32bit prefix with winetricks version 20171018-next `c80d4584a6848ba6c7fc04ed48f5e1610b522a5ff458a712e8509ea7417f13af` and wine 2.22

Arch Linux 4.13.12

When I run `winetricks install dotnet35` it keeps installing things and then the last lines it prints are 
```
------------------------------------------------------
Setting Windows version to win2k
Executing wine regedit /S C:\windows\Temp\_dotnet20sp1\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/juan/.wine32-halo terminate
------------------------------------------------------
```

And then nothing happens. I saw an issue about this before but that was fixed apparently and I am on the latest

edit: Installing `dotnet30` works fine, so this seems to be specific to 35
edit2: Installing `dotnet30sp1` has the same issue as `dotnet35` as it stalled, the issue may be because of it and `dotnet35` is fine
Looking in the script, obviously it has to do with `dotnet20sp1` since its in my log and `dotnet30sp1` calls it

**Comment by JuanPotato** [comment]
I installed `dotnet30` then installed `dotnetsp1` through the official exe from microsoft's site https://www.microsoft.com/en-us/download/details.aspx?id=3005 and it installed without error.

Couldn't install `dotnet35` through winetricks as it conflicted with `dotnet20` so I installed it through microsoft's site https://www.microsoft.com/en-us/download/details.aspx?id=21 as before and it worked.

**Comment by JuanPotato** [comment]
Aight, pretty sure I narrowed it down to trying to install `dotnet20` then `dotnet20sp1`.

Installing `dotnet20sp2` after `dotnetsp1` (without having `dotnet20` prior) resulted in hanging on a similar message as the first.
```
Setting Windows version to winxp
Executing wine regedit /S C:\windows\Temp\_dotnet20\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/juan/.wine32-halo terminate
------------------------------------------------------
```

Installing `dotnet20sp1` without any prior `dotnet20` installation is perfectly fine though.

Installing `dotnet20sp2` was fine until I got an error form `RegScvs.exe` in a little window
```
CLR error: 80004005.
The program will now terminate.
```
but it still finishes successfully and doesnt seem to care what happened.


I might end up booting a live cd to test these cleanly

**Comment by JuanPotato** [comment]
Tested installing dotnet20sp1 after dotnet20 in a clean chroot and it doesnt finish. 

dotnet35 calls dotnet30sp1 which calls dotnet20sp1 which calls dotnet20 which completes but then causes dotnet20sp1 not to and then everything is stuck.

**Comment by patrick-brian-mooney** [comment]
Affects me too, on several x64 Linux distros, for all versions of dotnet available for installing. The script hangs on completion every single time, including on freshly created winebottles and even after purging and reinstalling all wine-related packages on my system.

**Comment by spvkgn** [comment]
I have same issue on Ubuntu 18.04 x64 with wine-stable 3.0.1 (WINEARCH=win32).

**Comment by ConsciousHacker** [comment]
Same issue on wine-3.0 (Debian 3.0-1, WINEARCH=win32)

**Comment by harleyQu1nn** [comment]
I have the same issue on wine-3.0 (Debian 3.0-1, WINEARCH=win32)

**Comment by ChrisTruncer** [comment]
I've run into this issue also on the same exact version info as @ConsciousHacker (wine-3.0 (Debian 3.0-1, WINEARCH=win32))

**Comment by mattgrandy** [comment]
Similar issue using wine-3.0 (Debian 3.0-1, WINEARCH=win32)

**Comment by leewdch** [comment]
Same issue. Wine-3.11, win32 and latest winetricks build from github. I'll try installing dotnet30 first and the sp1 from microsoft as suggested in the first posts

**Comment by leewdch** [comment]
Nope, same problem it hangs at the dotnet20sp1 part

```
0012:fixme:msvcrt:__clean_type_info_names_internal (0x64083a50) stub
Executing w_do_call dotnet20sp1
Executing load_dotnet20sp1 
Executing w_do_call remove_mono
Executing load_remove_mono 
000f:err:service:process_send_command receiving command result timed out
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053
------------------------------------------------------
Mono does not appear to be installed.
------------------------------------------------------
------------------------------------------------------
Working around wine bug 34803 
------------------------------------------------------
reg: The system was unable to find the specified registry key or value
reg: The system was unable to find the specified registry key or value
The operation completed successfully
Executing rm -f /home/leewdch/vn/dosdevices/c:/windows/system32/mscoree.dll
Executing w_do_call dotnet20
dotnet20 already installed, skipping
------------------------------------------------------
Setting windows version so installer works
------------------------------------------------------
------------------------------------------------------
Running /usr/bin/wineserver -k. This will kill all running wine processes in prefix=/home/leewdch/vn
------------------------------------------------------
Setting Windows version to win2k
Executing wine regedit C:\windows\Temp\_dotnet20sp1\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/leewdch/vn terminate
------------------------------------------------------
```

**Comment by leewdch** [comment]
After a retry with a clean prefix and replacing the exe files in the .cache/winetricks path whenever a download failed I solved winetricks hanging on the sp1 install opening a new terminal and manually killing the wineserver with `WINEPREFIX=/path/to/prefix wineserver -k`. It went on installing the remaining stuff and it finally tried to install dotnet20 sp2 but an error at the very end occurred. I think the only dll it could not install is the sp2 but everything else should be ok

```
------------------------------------------------------
dotnet20sp2 install completed, but installed file /home/leewdch/vn/dosdevices/c:/windows/winsxs/manifests/x86_Microsoft.VC80.CRT_1fc8b3b9a1e18e3b_8.0.50727.3053_x-ww_b80fa8ca.cat not found
------------------------------------------------------
```
