### ISSUE TITLE
TrueType Collection fonts are not registered as True Type

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#880]
[This code](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/src/winetricks#L2762) doesn't take TrueType Collection font files (extension `.ttc`) into account.

**Comment by austin987** [comment]
Are there are any .ttc files currently installed? Does wine handle them?

**Comment by mihaitodor** [comment]
> Are there are any .ttc files currently installed?
[Yep](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/src/winetricks#L10089)! Also [this one](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/src/winetricks#L10679) and [this one](https://en.wikipedia.org/wiki/Meiryo) (which will be made available by #883).

> Does wine handle them?
[It seems to](https://github.com/wine-mirror/wine/blob/eebf1181f91bbef003dd519f2c2f4ee33f0acc0c/dlls/gdi32/freetype.c#L4572-L4584), but I'll have to do some testing...
