### ISSUE TITLE
Consolas font name typo

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#882]
MS Consolas console font is mistakenly registered as "Consoleas" [here](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/src/winetricks#L10133-L10136).

**Comment by austin987** [comment]
Should be fixed by https://github.com/Winetricks/winetricks/commit/c63979438f894bff8f7730be31855058815a4f1c
