### ISSUE TITLE
Not all fonts from PowerPointViewer.exe are available as verbs

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#883]
`PowerPointViewer.exe` contains additional fonts that I think winetricks should register: [Calibri](https://en.wikipedia.org/wiki/Calibri), [Candara](https://en.wikipedia.org/wiki/Candara), [Corbel](https://en.wikipedia.org/wiki/Corbel_(typeface)) and [Meiryo](https://en.wikipedia.org/wiki/Meiryo). Is there any reason not to register them?

**Comment by austin987** [comment]
No particular reason, though I wonder if the fonts should have their own verb, in case someone just wants those fonts, but not ppt.

Liberation fonts should be its own bug.

**Comment by mihaitodor** [comment]
> though I wonder if the fonts should have their own verb
I could create an extra verb, like `pptfonts`, which installs all of them. WDYT?

> Liberation fonts should be its own bug.
Done: #886
