### ISSUE TITLE
Update Ubuntu fonts and register all of them

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#884]
On Ubuntu, Wine does a good job at picking up the installed Ubuntu fonts and registering them automatically when creating the WINEPREFIX:

![screen shot 2017-12-06 at 14 21 31](https://user-images.githubusercontent.com/788216/33666107-e595e680-da90-11e7-8bca-6ec9f4e52f26.png)

The Ubuntu Font pack includes [13 fonts](https://en.wikipedia.org/wiki/Ubuntu_(typeface)#History_and_features) in total, but Winetricks [registers only 4 of them](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/src/winetricks#L10629-L10632) from an outdated package (version 0.70.1). I think we should update to [version 0.83](https://assets.ubuntu.com/v1/fad7939b-ubuntu-font-family-0.83.zip) and register all of them.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/4bdd67c9b79fba976a986b11570a3676ae84a43b
