### ISSUE TITLE
winetricks_is_installed doesn't work if the verb doesn't create any new files

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#885]
I was reviewing [`winetricks_is_installed`](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/src/winetricks#L3904), which looks at the contents of `installed_file1` in `w_metadata` and, if that file is present, it returns true. However, this prevents verbs which only overwrite existing files from running (try running `eufonts` after `corefonts` when #865 gets fixed).

What would be a good way to fix this? Would you consider parsing `winetricks.log` (which gets created by `winetricks_stats_log_command`) in `winetricks_is_installed` to determine if a verb has been executed before?

**Comment by austin987** [comment]
@mihaitodor I think parsing winetricks.log is a good solution.
