### ISSUE TITLE
Trebuchet MS fonts typos

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#887]
I just noticed that the Trebuchet MS fonts are registered wrong (in different ways) in both corefonts and eufonts.

In corefonts, "Trebuchet" is [misspelled as "Trebucet"](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/src/winetricks#L10211-L10214).

In eufonts, the "MS" part [is missing](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/src/winetricks#L10288-L10291).

**Comment by austin987** [comment]
Fixed by https://github.com/Winetricks/winetricks/commit/7969722a8d48eff211ff5461799bb51a55e7a116

**Comment by mihaitodor** [comment]
Thanks Austin! :)
