### ISSUE TITLE
tests/shell-checks issue with missing shellcheck

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#889]
The output of `tests/shell-checks` on OSX is misleading if `shellcheck` is not installed:
```shell
> ./tests/shell-checks
+ command checkbashisms
+ command shellcheck --version
```

**Comment by austin987** [comment]
What does `command shellcheck ---version` give you on OSX?

**Comment by mihaitodor** [comment]
```
➜  ~ command shellcheck --version
ShellCheck - shell script analysis tool
version: 0.4.7
license: GNU General Public License, version 3
website: http://www.shellcheck.net
```

... But I just realised the issue is [`set -e`](https://github.com/Winetricks/winetricks/blob/aaa1a2454a3c61fd26a69a07912e4fb5576d9828/tests/shell-checks#L12). See here for details: http://mywiki.wooledge.org/BashFAQ/105 Basically, `set -e` makes the script die right [here](https://github.com/Winetricks/winetricks/blob/aaa1a2454a3c61fd26a69a07912e4fb5576d9828/tests/shell-checks#L30).

Is there any good reason to have `set -e` in that script? Commands are wrapped into `w_try`, which  calls `w_die` if something goes wrong.

**Comment by austin987** [comment]
In general, set -e is desirable. In this case, it was trivial to refactor the code to handle set -e: https://github.com/Winetricks/winetricks/commit/4fbeee3a9a8cc20ffd0dd5c6fb6b0c3b253ed73d

**Comment by mihaitodor** [comment]
Ah, cool! I'm not that experienced in Bash and I saw that some people prefer not to use it. Thanks for sorting it out!
