### ISSUE TITLE
winetricks-test assumes that winetricks is located in the same folder

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#891]
See [here](https://github.com/Winetricks/winetricks/blob/389d1ed6810cab5a54be2d68c2c6b4752a04f272/tests/winetricks-test#L73).

Since they are located in different folders, users won't be able to simply run `winetricks-test` without some manual steps, like copying winetricks around.

**Comment by austin987** [comment]
Confirmed, I'll look at some point in the near future.

**Comment by austin987** [comment]
This was fixed a while back and never closed:

```
commit 62426e87c60c30a97c072dc0d1e97d48c0fbe509
Author: Austin English <austinenglish@gmail.com>
Date:   Sun Aug 12 01:21:27 2018 -0500

    tests/winetricks-test: don't depend on being in src/ to run
```

and another for linkcheck.sh:
```
commit cf53698820c44de50c91ab446cac4f7e8ecabb89
Author: Austin English <austinenglish@gmail.com>
Date:   Sun Aug 12 01:52:34 2018 -0500

    src/linkcheck.sh: don't depend on being in src/ to run
```
