### ISSUE TITLE
shellcheck 0.4.7 turned SC1117 on

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#895]
The new shellcheck (ver 0.4.7) is now moaning about [SC1117](https://github.com/koalaman/shellcheck/blob/c36f6d89baae1d4e76312ff76f580a8709801b44/CHANGELOG.md#v047---2017-12-08) under Travis.

I wouldn't mind converting some double quotes to single quotes (about 90 occurrences), but maybe it's saner to simply add this check to the [list of disabled ones](https://github.com/Winetricks/winetricks/blob/a864b065339551995b9ecdfd9ea3a4be85c5da93/src/winetricks#L2).

What would you prefer to do?

**Comment by austin987** [comment]
I went with double backslashes. Patch is ready, just waiting on tests to finish.

Thanks for reporting, I fixed it when I noticed Travis complaining on osx

**Comment by mihaitodor** [comment]
Thanks for that! :)

**Comment by austin987** [comment]
Should be fixed by https://github.com/Winetricks/winetricks/commit/3c2532c654c7b26bae673ab25593734819f9fac1, see https://travis-ci.org/Winetricks/winetricks/builds/317277554

Thanks again for reporting!

**Comment by mihaitodor** [comment]
Thanks & you're welcome! :)
