### ISSUE TITLE
liberation seems to not register fonts properly in the registry

### ISSUE THREAD

**Issue by mihaitodor** [Winetricks/winetricks#896]
Looking more into #886, I noticed that the liberation verb stomps over the fonts that Wine registers automatically on Ubuntu (see Ubuntu_original.png) and registers its fonts with the wrong name (see Ubuntu_with_liberation_installed.png).

Wine seems to be able to automagically re-cache "Liberation Sans Narrow" under HKCU\Software\Wine\Fonts\Cache after [this code](https://github.com/Winetricks/winetricks/blob/a864b065339551995b9ecdfd9ea3a4be85c5da93/src/winetricks#L10546) copies liberationsansnarrow-regular.ttf to C:\windows\Fonts, but, for some reason, it deletes it from HKLM\Software\Microsoft\Windows\CurrentVersion\Fonts and from HKLM\Software\Microsoft\Windows NT\CurrentVersion\Fonts, which doesn't make much sense. Could this be a bug in Wine?

The above makes me wonder what is the actual point of writing these font registry entries manually from Winetricks. Maybe we should let Wine do it as described in the last comment [here](https://forum.winehq.org/viewtopic.php?t=13933)? Do you have any insight into this? I recall seeing a more detailed discussion on this topic somewhere, but I can't seem to find it any more.

![ubuntu_original](https://user-images.githubusercontent.com/788216/34052380-0940dff6-e1ba-11e7-8751-ce13d0b82870.png)

![ubuntu_with_liberation_installed](https://user-images.githubusercontent.com/788216/34052401-22f9f9be-e1ba-11e7-859d-136f77a703f7.png)

**Comment by austin987** [comment]
I don't see fonts automatically registering from C:\windows\fonts. I suspect that only works for stuff in /usr/share/fonts (or whatever fontconfig reports, I suspect).

I think the proper fix would be to write a full windows path to the registry. I'm looking at it.

**Comment by mihaitodor** [comment]
@austin987 I spent more time digging into this and I can confirm there is some logic somewhere which automagically populates `HKCU\Software\Wine\Fonts\Cache` but not `HKLM\Software\Microsoft\Windows[\ NT]?\CurrentVersion\Fonts` when copying font files into `.wine/drive_c/windows/Fonts/`. The magic seems to be based on [inotify](https://en.wikipedia.org/wiki/Inotify), but I don't understand well enough how it works ([this](https://github.com/wine-mirror/wine/blob/b34ea10112227a0d8554c81fc093c0cf6e1bc1b7/server/change.c#L69) seems to be the Wine code that manages inotify subscriptions).

Now, there seems to be a race issue between apps like regedit and notepad and the above mechanism. For example, if I have the corefonts installers cached under `.cache/winetricks/` and I run `winetricks corefonts` and I start notepad.exe immediately after, I notice that the new fonts are not available. Worse, most times (not sure yet how to reproduce it all the time), the new fonts never get added to `HKCU\Software\Wine\Fonts\Cache`, which seems to be the place from where Wine lists fonts through EnumFontFamiliesEx (try running [this code](https://github.com/kamwoods/FontAnalysis/blob/d894c082221912e72653ae76804a72f70c181861/FontFinder/FontFinder/FontFinder.cpp)).

The main issue here is that something needs to wait for whatever background process to finish writing to `HKCU\Software\Wine\Fonts\Cache` before granting access to the registry. I have created #900, which seems to solve this.

Another problem would be to understand why Wine only populates `HKCU\Software\Wine\Fonts\Cache` automatically when a font file is manually added to `.wine/drive_c/windows/Fonts/`. Why not also add it to `HKLM\Software\Microsoft\Windows[\ NT]?\CurrentVersion\Fonts`?

I can try posting this investigation on wine-devel as well to see if somebody can clarify what should be the expected behaviour. WDYT?

**Comment by austin987** [comment]
I was thinking of the same fix, so sgtm.

Re: wine/wine-devel, yes, I think that's a good idea. Huw/AJ are the most likely to know, or maybe Nikolay.

**Comment by mihaitodor** [comment]
@austin987 Done: #900 and done: https://www.winehq.org/pipermail/wine-devel/2017-December/120671.html Thanks! :)

**Comment by mihaitodor** [comment]
Fixed by #901 and #900.
