### ISSUE TITLE
Uplay crashes a lot with win7 due to winhttp

### ISSUE THREAD

**Issue by vitor251093** [Winetricks/winetricks#903]
I receive that error message while running Uplay with a Windows 7 prefix:

`err:module:import_dll Library webio.dll (which is needed by L"C:\\windows\\system32\\WINHTTP.dll") not found`

The commit below, which reverted the change, is the probable cause of the issue. I guess that reverting that commit fixed the problem for `vista` and lower versions, but broke it for `win7` and superior versions. This can be checked because the error above (and the constant crashes) do not happen if Uplay is being run as `vista` instead of `win7`.
https://github.com/austin987/winetricks/commit/afe0d2bee5ac8b08290a3f646272927f8541f5e8

Since `win7` is the default prefix for Wine now, maybe the most proper solution would be to add a second winetrick (i.e. winhttp_winxp) to use the older method, while winhttp keeps the newer method.

Referring to my comment in that issue:
https://github.com/Winetricks/winetricks/issues/831#issuecomment-352852116

**Comment by oott123** [comment]
No, I think that you meet the extractly same issue as #831 and 254cb28 will fix that issue.
Are you using the latest version of winetricks?

**Comment by vitor251093** [comment]
Yup, I'm using the latest winetricks, that's why I think it isn't the same issue

**Comment by mirh** [comment]
EtwEventActivityIdControl has been stubbed in https://github.com/wine-mirror/wine/commit/f535bcb2e66153301f1927a9a323c1e989c49cd5
Is win7 winhttp still a problem?
