### ISSUE TITLE
Does .NET 4.5 still require a clean prefix (absense of previous of versions of .NET) ?

### ISSUE THREAD

**Issue by Kakadu** [Winetricks/winetricks#910]
Some time ago it was true but now with latest `wine-3.0-rc3` and latest winetricks (`20171222-next`) after a command `winetricks dotnet45` it downloads and tries to install .NET 4.5 without installing old versions. And then something goes terribly wrong.

````
3497:err:msi:ACTION_CallDllFunction Custom action (L"C:\\users\\kakadu\\Temp\\msi1e8e.tmp":L"InstallAssembly") caused a page fault: c0000005
340a:err:ntdll:RtlpWaitForCriticalSection section 0x5b1010 "?" wait timed out in thread 340a, blocked by 3499, retrying (60 sec)
340a:err:ntdll:RtlpWaitForCriticalSection section 0x5b1010 "?" wait timed out in thread 340a, blocked by 3499, retrying (60 sec)
````

**Comment by austin987** [comment]
Depends on what version, dotnet45 conflicts with:
    conflicts="dotnet20 dotnet20sdk dotnet20sp1 dotnet20sp2 dotnet35sp1 dotnet40 vjrun20"

note that there's been a lot of work recently on wine and winetricks, so things should be a lot more stable in latest versions. (winetricks isn't released yet, probably later today or tomorrow, wine would be 4.0-rc1, out Friday, but anything from 3.18+ should be much better).
