### ISSUE TITLE
Gksu is deprecated, should use pkexec instead

### ISSUE THREAD

**Issue by austin987** [Winetricks/winetricks#912]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885548 for background.

Pull requests appreciated, otherwise I'll look at the end of January when I get back from holiday.

**Comment by ShannonVanWagner** [comment]
So long as gksudo is not included.. here's one for gksu.. 
https://github.com/Winetricks/winetricks/pull/915
