### ISSUE TITLE
.Net Install seizes up at 4.0  (installing 4.0 framework Profiles)

### ISSUE THREAD

**Issue by masternetra** [Winetricks/winetricks#917]
Was trying to install dotnet and it got to .Net 40 and or whatever and was was installing the 4.0 Framework Client Profile and is unable to finish it. It just seizes up (eventually) and just repeats this error on and on until to the point where it just stops: 

`3ec8:err:msi:ACTION_CallDllFunction Custom action (L"C:\\users\\mrkline67\\Temp\\msi1fd5.tmp":L"InstallAssembly") caused a page fault: c0000005`

The "3ec8" section changes, but the rest is the same.

I initiated the Dotnet installation of things by installing 4.6.2 and letting it install all it needed before hand.
O.S: Peppermint OS (Ubuntu 16.04) (64Bit)
(32bit Wine Prefix)
  
(Update): ran again it got down to repeating after repeating the errors mentioned prior for a good long while:
`7280:err:ntdll:RtlpWaitForCriticalSection section 0x5b0a50 "?" wait timed out in thread 7280, blocked by 72c3, retrying (60 sec)
`

**Comment by frenchiveruti** [comment]
I had the same errors.
`7280:err:ntdll:RtlpWaitForCriticalSection section 0x5b0a50 "?" wait timed out in thread 7280, blocked by 72c3, retrying (60 sec)`

**Comment by ryanmusante** [comment]
https://appdb.winehq.org/objectManager.php?sClass=version&iId=36818

Method to install dotnet 4.5 on 64bit prefix:
First make a fresh prefix:
` WINEPREFIX=~/.wine/prefix wineboot --init`
Remove mono if it's installed:
```
 WINEPREFIX=~/.wine/prefix wine uninstaller --remove '{E45D8920-A758-4088-B6C6-31DBB276992E}'

 WINEPREFIX=~/.wine/prefix wine64 uninstaller --remove '{E45D8920-A758-4088-B6C6-31DBB276992E}'
```
Switch the prefix to Windows XP to get .NET Framework 4.0 installed (required for newer .NET Framework installation to work on wine):
`WINEPREFIX=~/.wine/prefix winecfg`
Download and install .NET Framework 4.0 :
```
wget 'http://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe'

 WINEPREFIX=~/.wine/prefix wine dotNetFx40_Full_x86_x64.exe /q && WINEPREFIX=~/.wine/prefix wineserver -k
```
Change the prefix back to Windows 7 and set mscoree to native in the dll overrides for .NET Framework 4.7.1 installer to work:
` WINEPREFIX=~/.wine/prefix winecfg`
Download and install .NET Framework 4.7.1 :
```
 wget 'http://download.microsoft.com/download/9/E/6/9E63300C-0941-4B45-A0EC-0008F96DD480/NDP471-KB4033342-x86-x64-AllOS-ENU.exe'

 WINEPREFIX=~/.wine/prefix wine NDP471-KB4033342-x86-x64-AllOS-ENU.exe /q && WINEPREFIX=~/.wine/prefix wineserver -k
```

**Comment by AccountOneOff** [comment]
@Tk-Glitch also made a patch for winetricks: https://github.com/Tk-Glitch/PKGBUILDS/blob/master/winetricks-git/dotnet471.patch

**Comment by ryanmusante** [comment]
@AccountOneOff 
So, selecting 4.71 alone will grab all necessary dependenices?

**Comment by Tk-Glitch** [comment]
@ryanmusante The only "dependency" is dotnet 4.0, and yes it will be installed by the script.

**Comment by ryanmusante** [comment]
Is this only in winetricks-git from AUR?

**Comment by Tk-Glitch** [comment]
Actually it's not in the current AUR pkgbuild. As far as I know, it's only found in my pkgbuild, and as a pending pull request in lutris next branch.

**Comment by ryanmusante** [comment]
@Tk-Glitch I apologize for my ignorance but, how do I apply this patch?

**Comment by Tk-Glitch** [comment]
@ryanmusante cd to your winetricks source clone, and apply with whatever method you prefer.

For example with git :
git apply /path/to/patch.patch

Or with patch :
patch -Np1 < /path/to/patch.patch

**Comment by austin987** [comment]
Is this still an issue? dotnet40 installs fine here in 32 and 64 bit prefixes (wine-4.5).

**Comment by Tk-Glitch** [comment]
It doesn't seem to be an issue anymore.

**Comment by sTiKyt** [comment]
![image](https://user-images.githubusercontent.com/35602029/96389991-f2739500-11a1-11eb-94b9-fc48d14ce754.png)

**Comment by dustinpianalto** [comment]
I am still getting this error as well.
![image](https://user-images.githubusercontent.com/16179393/97533567-484bf800-196d-11eb-932e-21b5916a8200.png)

**Comment by ardarandir** [comment]
same here while installing .NET 4.5.2

```
003f:err:ntdll:RtlpWaitForCriticalSection section 0x100a8 "heap.c: main process heap section" wait timed out in thread 003f, blocked by 01e2, retrying (60 sec)
003f:err:ntdll:RtlpWaitForCriticalSection section 0x100a8 "heap.c: main process heap section" wait timed out in thread 003f, blocked by 01e2, retrying (60 sec)
003f:err:ntdll:RtlpWaitForCriticalSection section 0x100a8 "heap.c: main process heap section" wait timed out in thread 003f, blocked by 01e2, retrying (60 sec)
003f:err:ntdll:RtlpWaitForCriticalSection section 0x100a8 "heap.c: main process heap section" wait timed out in thread 003f, blocked by 01e2, retrying (60 sec)
```

**Comment by sTiKyt** [comment]
Well, as we can see it happens to multiple people... Maybe reopen issue?

**Comment by abramsba** [comment]
I'm having this issue on arch, using winetricks version `20201206-next`, wine `wine-6.0`. A clean or 32-bit prefix has not fixed the issue. 

```
> winetricks dotnet40
0104:err:ntdll:RtlpWaitForCriticalSection section 7BC62360 "../wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0104, blocked by 0024, retrying (60 sec)
0108:err:ntdll:RtlpWaitForCriticalSection section 7BC62360 "../wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0108, blocked by 0024, retrying (60 sec)
010c:err:ntdll:RtlpWaitForCriticalSection section 7BC62360 "../wine/dlls/ntdll/loader.c: loader_section" wait timed out in thread 010c, blocked by 0024, retrying (60 sec)
```

**Comment by benedetto** [comment]
Same over here.
