### ISSUE TITLE
Running wineserver -w

### ISSUE THREAD

**Issue by 601t** [Winetricks/winetricks#919]
OS:Linux mint 18.3
Kernel:4.4.0-104
Winetricks version:20171222
Wine version:2.0.4(Stable), 2.21.0(Staging) and 3.0-rc5(Development)

Error message:
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/USERNAME/.wine terminate

Maybe, regedit will not work properly.
Please tell me how to fix this problem.

**Comment by 601t** [comment]
Rewrite it.

**Comment by austin987** [comment]
I don't see any bug here. If winetricks needs to wait for wineserver, it will warn you so that you can gracefully close running apps rather than wondering why winetricks hung.

If you have a suggestion for better wording, fine. Otherwise, there's no bug here.

**Comment by Alkaris** [comment]
its very annoying that this message has to popup while installing things, it should automatically close running apps instead of popping up a window with that message and letting wineserver hang like that, or at the very least have an option to add a flag to zap the message and automatically continue without user input.

**Comment by austin987** [comment]
You can use -q in console made to avoid the pop-up.

I'm not going to kill things without notice, that could cause user data loss or registry corruption.

If you have GUI suggestions, send a patch, but posting on closed bugs is not the way to do it.

**Comment by neurogroups** [comment]
open another terminal and kill the blocking wine process with wineserver -k

**Comment by TheSilent351** [comment]
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/thesilent35/.wine/office terminate



What should I do
