### ISSUE TITLE
trying to wine '/root/Desktop/camtasia.exe' on kali linux

### ISSUE THREAD

**Issue by mosesAnonymous** [Winetricks/winetricks#923]
wine: Call from 0x7b43c44c to unimplemented function mscoree.dll.CorIsLatestSvc, aborting
wine: Unimplemented function mscoree.dll.CorIsLatestSvc called at address 0x7b43c44c (thread 001b), starting debugger...
err:module:import_dll Library MSVCR120_CLR0400.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
err:service:process_send_command service protocol error - failed to write pipe!
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow The explorer process failed to start.
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded
err:ole:CoInitializeEx Attempt to change threading model of this apartment from multi-threaded to apartment threaded

**Comment by qwertychouskie** [comment]
Why are you running Wine as root?  This is a very bad idea...

https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F

**Comment by slyscorpion** [comment]
@qwertychouskie

Kali Linux runs as root by default and AFAIK there's no way to run anything as a user in that particular OS.

**Comment by austin987** [comment]
I'm willing to be 'su' works.

Anyway. I don't see winetricks being used here. .Net doesn't fully work on 64-bit yet, and aside from that, your $DISPLAY is messed up.

**Comment by leka45** [comment]
> Why are you running Wine as root? This is a very bad idea...
> 
> https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F

Why ?

**Comment by qwertychouskie** [comment]
@leka45 Because any application running in Wine can change critical system files (Wine maps / to the Z drive).  Big security risk.
