### ISSUE TITLE
"Help" option in GUI directs to 404'd google code page

### ISSUE THREAD

**Issue by hughesjs** [Winetricks/winetricks#925]
It links here: **winetricks.googlecode.com**

I've tried searching the repo to find where this is stored so I can fix it myself and get you to pull it but I can't find it.

**Comment by Chiitoo** [comment]
The 'View help' option?

Takes me here: https://github.com/Winetricks/winetricks/wiki

Are you perhaps using a more or less ancient Winetricks version?  :]

**Comment by hughesjs** [comment]
Could be... It's the latest version provided in the default linux mint repositories, how do I find out which version it is?

**Comment by slyscorpion** [comment]
In your terminal type: 

winetricks --version 

and you will get the version number of winetricks.

**Comment by hughesjs** [comment]
Yeah... my bad 
`20140817 - sha1sum: b6ad9287523453a33e443ef2f4bd77f2f7f49e21
`
Sorry for wasting your time. I guess I'll have to rebuild it from source and reinstall the latest.
