### ISSUE TITLE
'list-installed' does not list verbs installed from the category 'settings'

### ISSUE THREAD

**Issue by Asta1986** [Winetricks/winetricks#936]
Hello, command 'list-installed' seems to show only verbs installed from categories like 'apps' and 'fonts' but not those from the 'settings' one.
'settings list' displays all the available ones and not only those applied to a given prefix. 
I'm using winetricks version 20171222.
Regards.

**Comment by austin987** [comment]
So I'm thinking about simplifying the whole thing and just displaying winetricks.log. Can you try this patch?

https://github.com/austin987/winetricks/commit/7fbf374b61b2b6aba304750741718c6b8472c1da

**Comment by Asta1986** [comment]
Hello. I tried this by installing one verb in each of the following categories:
  apps
  benchmarks
  dlls
  fonts
  settings
and 'list-installed' displayed all of them (including the one from the settings category).
A couple of things I noticed are:
Perhaps the output would be more useful if it were in chronological order and not alphabetical, so one gets the changes in the order they were applied to the prefix and can easily see at the top for instance which videomemorysize value is currently set.
If one runs the command 'list-installed' before installing any verbs, a file not found error from cat is displayed, that might not be very clear to everyone:
`cat: winetricks.log: No such file or directory`
Regards.

**Comment by austin987** [comment]
Good points, thanks for the feedback. I'll pick something new in a few hours.

**Comment by austin987** [comment]
@Asta1986 updated

**Comment by austin987** [comment]
New link is https://github.com/Winetricks/winetricks/commit/bc5e108763c2fdbce95a76a516b5a5d46c14c311

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/5881efdb924ef5cfad7042493832347804f6c804

**Comment by Asta1986** [comment]
Hi. I tried the new patch with the same test as mentioned above and it worked as expected. If nothing was installed the new warning was displayed.
Thank you. Regards.
