### ISSUE TITLE
Office 2013

### ISSUE THREAD

**Issue by ukos-git** [Winetricks/winetricks#937]
I was just installing Office 2013 pro, following some guides from the internet and built a [script for it using a winetricks verb file](https://gist.github.com/ukos-git/5bb3564496b444e919c4ea2d3963a3ea).

I think it would be good to have support for the installation process upstream in winetricks. The latest supported Office version in winetricks is 2007. If we want to add support, there is one missing piece regarding the mount process.

Office 2013 Pro is installing from a `.img` file. By now, `w_mount` only supports iso files.
I was able to mount the file using `gnome-disk-image-mounter` without any problems but it's obviously a nasty workaround and not suitable for pure winetricks.

Is there a possibility to mount the img file using winetricks to add office2013 support?

**Comment by kakurasan** [comment]
Hi.

Fortunately, the file you mentioned is ISO 9660 image and we already support it.

```
$ file OfficeProfessionalPlus_x86_en-us.img 
OfficeProfessionalPlus_x86_en-us.img: ISO 9660 CD-ROM filesystem data '15.0.4420.1017'

$ sha256sum OfficeProfessionalPlus_x86_en-us.img 
236f8faae3f979ec72592a63784bba2f0d614916350c44631221b88ae9dae206  OfficeProfessionalPlus_x86_en-us.img
```

**Comment by kakurasan** [comment]
The following verb `office2013pro.verb` works for me. Could you test this?

```sh
w_metadata office2013pro apps \
    title="Microsoft Office 2013 Professional" \
    publisher="Microsoft" \
    year="2013" \
    media="cd" \
    file1="setup.exe" \
    installed_file1="$W_PROGRAMS_X86_WIN/Microsoft Office/Office15/WINWORD.EXE"

load_office2013pro()
{
    if ! test -f "$W_CACHE"/office2013pro/15.0.4420.1017.iso; then
        w_download http://care.dlservice.microsoft.com/dl/download/2/9/C/29CC45EF-4CDA-4710-9FB3-1489786570A1/OfficeProfessionalPlus_x86_en-us.img 236f8faae3f979ec72592a63784bba2f0d614916350c44631221b88ae9dae206 "15.0.4420.1017.iso"
    fi

    w_set_winver win7

    w_call corefonts
    w_call msxml6
    w_call riched20

    # As of Wine 3.0, D3D11 works without this setting on Intel HD Graphics 510
    if w_wine_version_in 3.0, ; then
        cat > "$W_TMP"/MaxVersionGL.reg <<EOF
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\Direct3D]
"MaxVersionGL"=dword:00030002
EOF
        w_try_regedit "$W_TMP_WIN"\\MaxVersionGL.reg
    fi

    # "mount + sudo" and fuseiso work
    # archivemount has path-related issue in access.en-us/ and cannot finish installation
    w_mount 15.0.4420.1017

    # TODO: unattended installation
    w_try "$WINE" "${W_ISO_MOUNT_LETTER}:setup.exe"

    w_umount
    w_wineserver -w
}
```

**Comment by ukos-git** [comment]
@kakurasan Renaming to iso works.

I see that you were taking the verb file [from my gist](https://gist.github.com/ukos-git/5bb3564496b444e919c4ea2d3963a3ea) as base and added support for mounting. I created a MR for it. The second commit are your changes, if you want to take over ownership of it, go ahead.

Lets do the discussion of the code on the [MR](https://github.com/Winetricks/winetricks/pull/939).
