### ISSUE TITLE
Feature Request -- Tree Level Interface Design

### ISSUE THREAD

**Issue by ryanmusante** [Winetricks/winetricks#942]
Request add buttons for back and forward to the interface and/or a tree format for returning to the main configuration section. As of now, being several levels deep requires "x"ing out several times to return to beginning.

**Comment by ryanmusante** [comment]
Possible status update?

**Comment by austin987** [comment]
None. I'm not working on it and don't plan to do so (which is why I tagged it 'help wanted').

If someone else wants to work on it, I'll review the PR.
