### ISSUE TITLE
InstMsi.exe fails to download - timeout

### ISSUE THREAD

**Issue by WtfJoke** [Winetricks/winetricks#943]
I use latest winetricks:
`20180217-next - sha256sum: 6dd23a6c59febc56a2c5a31aabc0c1b92545ec176c64b494aa088c5d993bf588
`

I try to install riched20. Already manually downlaoded and copied w2ksp4_en.exe (see #600)
It fails when trying to download InstMsiW.exe.

Download fails: 
Download-Timeout of:  `ftp://ftp.hp.com/pub/softlib/software/msi/InstMsiW.exe`

`Downloading https://web.archive.org/web/2000/ftp://ftp.hp.com/pub/softlib/software/msi/InstMsiW.exe failed`

same issue as #780 

EDIT: Download from here seems to work:
https://web.archive.org/web/20160710055851/https://download.microsoft.com/download/WindowsInstaller/Install/2.0/NT45/EN-US/InstMsiW.exe

**Comment by kakurasan** [comment]
The FTP URL works for me and HTTPS URL `https://ftp.hp.com/pub/softlib/software/msi/InstMsiW.exe` also works.

Does the HTTPS URL work? If not, is there any working URL in http://www.filewatcher.com/m/InstMsiW.exe.1822848-0.html ?

**Comment by WtfJoke** [comment]
Maybe it was a temporary issue. 
Now all the url works (ftp and the https url and my provided link as well).

Will close this issue
Thanks you for your answer kakurasan.
