### ISSUE TITLE
Bad url to download Visual Studio 2010 Express

### ISSUE THREAD

**Issue by Duckissime** [Winetricks/winetricks#950]
In /src/winetricks at line 12814 the link is dead "w_download https://web.archive.org/web/20140227220734/download.microsoft.com/download/1/E/5/1E5F1C0A-0D5B-426A-A603-1798B951DDAE/VS2010Express1.iso "

**Comment by austin987** [comment]
Unfortunately archive.org isn't super reliable. Do you know of a better URL?

**Comment by austin987** [comment]
For that matter, it's working for me now.

**Comment by kakurasan** [comment]
I found some URLs (institutions of higher education?):
```
https://debian.fmi.uni-sofia.bg/~aangelov/VS2010Express1.iso
http://disi.unal.edu.co/~gjhernandezp/HeterParallComp/GPU/windows/VS2010Express1.iso
http://cloud.politala.ac.id/politala/1.%20Jurusan/Teknik%20Informatika/1.%20Data%20Dosen%20dan%20Staff/14.%20Agustian%20Noor,%20M.Kom/Visual%202/VS2010Express1.iso
```
Hope this helps.

**Comment by Duckissime** [comment]
It seems to randomly work

First try with `wget -c "https://web.archive.org/web/20140227220734/download.microsoft.com/download/1/E/5/1E5F1C0A-0D5B-426A-A603-1798B951DDAE/VS2010Express1.iso"`

    Enregistre : «VS2010Express1.iso»

    VS2010Express1.iso                          [     <=>     ]     424  --.-KB/s    ds 95s     

    2018-03-17 11:25:48 (4,47 B/s) - «VS2010Express1.iso» enregistré [424]

I tried again after removing the file and this time the file was retrieved.

SHA512 sum :

4b9a07cc14ff93dd5adae24fb672a7ccc769f03a6abeccbfd936827cc2cc3f3d1913e4cff22e34e318442b0a048b47bf1a374df4ef85af72406282b06284b0b4  VS2010Express1.iso

**Comment by kakurasan** [comment]
@Duckissime Does one of the URLs in my previous comment (not archive.org) work? If yes, we will change the URL in the verb.

**Comment by Duckissime** [comment]
@kakurasan The first link is alright, checksums match.
