### ISSUE TITLE
Will winetricks supports dotNetFx471 (Slim) soon ?

### ISSUE THREAD

**Issue by pmo-19** [Winetricks/winetricks#953]
I have seen that dotnet471 is available as a Slim exe on this [website](http://repacks.net/forum/viewtopic.php?t=7#p9). Do you plan an update in winetricks to support its install within wine ?

As I have no problem installing it in a 32 bit wine prefix which sports .NET 4.6.2 (dotnet462) installed by the latest git of `winetricks`.

`$ env WINEPREFIX="/home/ubuntu-xenial/pascal/.wine32" wine start /unix dotNetFx471_Full_x86_x64_Slim.exe`

**Comment by pmo-19** [comment]
I have seen that dotnet471 is available as a Slim exe on this [website](http://repacks.net/forum/viewtopic.php?t=7#p9). Do you plan an update in `winetricks` to support its install within wine ?

**Comment by austin987** [comment]
I don't have any immediate plans. It would help if someone pointed to an app that needs 4.7.1 (and/or sends a PR).

**Comment by rik-shaw** [comment]
@austin987 one software example is Logos: https://www.logos.com/basic  The bootstrap installer there doesn't work in wine due to it using the BITSAdmin.exe Windows Update process (?? I think I understand this correctly ??) but after I did a test install to a Virtual W7 32bit system the installer can be extracted from AppData\Local\Logos\Install\Installers.  DotNet 4.7.1 is a requirement.

**Comment by timqian** [comment]
This is necessary for running programs written based on dotnet 4.7.1

**Comment by ImperatorS79** [comment]
Paint.net also needs 4.7.1

**Comment by rik-shaw** [comment]
There is work being done on dotnet472 that would meet the needs of dotnet471 applications.  See #1062

**Comment by gverm** [comment]
There is a patch for 4.7.1 available here: https://github.com/Tk-Glitch/PKGBUILDS/blob/master/winetricks-tkg-git/dotnet471.patch
Haven't tested it myself, but I remember hearing that it works on the DXVK Discord.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/6ad67c1f4e33eb5f10ca03f2be7c52396967c2db
