### ISSUE TITLE
windowscodecs verb broken as it doesn't remove 'WMPhoto.dll'

### ISSUE THREAD

**Issue by apemberton** [Winetricks/winetricks#955]
https://github.com/Winetricks/winetricks/blob/8d334db8a526f4e4bf906c136b23c45ad4e2f65a/src/winetricks#L10099

To my understanding, WMPhoto.dll also needs to be removed in this line, otherwise wic_x86_enu.exe consistently fails with error 67 "WIC Setup canceled".

**Comment by apemberton** [comment]
@austin987 looks like I'm a moron and 7 hours late. :) should have refreshed the page before creating the PR. looks good! 👍

**Comment by austin987** [comment]
@apemberton no worries, thanks for the good report. I had started to run a bisect, but hadn't had time yet to figure out the reason, so you saved me plenty of time ;).

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/f4d7b0ac35ae6bd1e23f2d904b31c9739ce3fc88
