### ISSUE TITLE
Download URL for winxpsp3 seems to have become 404

### ISSUE THREAD

**Issue by mk-pmb** [Winetricks/winetricks#960]
> 2018-04-02 13:28:53 ERROR 404: NOT FOUND.
> […]
> Downloading https://web.archive.org/web/2000/ftp://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/winxp/Service_Packs/WindowsXP-KB936929-SP3-x86-ENU.exe failed

Possible replacement: https://web.archive.org/web/20180402113029/http://caesar.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/winxp/Service_Packs/WindowsXP-KB936929-SP3-x86-ENU.exe

**Comment by 4llan** [comment]
Better location: http://www.download.windowsupdate.com/msdownload/update/software/dflt/2008/04/windowsxp-kb936929-sp3-x86-enu_c81472f7eeea2eca421e116cd4c03e2300ebfde4.exe

[Source: http://www.catalog.update.microsoft.com/Search.aspx?q=kb936929]

**Comment by austin987** [comment]
@4llan the sha256 and filename don't match.

**Comment by austin987** [comment]
@4llan the sha256 and filename don't match.

**Comment by mk-pmb** [comment]
Indeed, in function `helper_winxpsp3` the expected SHA-256 is `62e524a552db9f6fd22d469010ea4d7e28ee06fa615a1c34362129f808916654` whereas my download has `abde3a963a9c3093900b853733ce9ddce22d94efcd53dfb112b7b893d113a070`.

In that function I also found a [mirror list URL](http://www.filewatcher.com/m/WindowsXP-KB936929-SP3-x86-ENU.exe.331805736-0.html).

**Comment by 4llan** [comment]
So, www.catalog.update.microsoft.com isn't a realible download source. Maybe the download fails in the meantime. All the downloads that I made using this service has valid hashes.

Cheers!

**Comment by austin987** [comment]
Fixed by cd8052dfff056ab5db8aae4053890421b08caf81

**Comment by austin987** [comment]
It's been stable for a while (though #982 is an option that I'm evaluating).
