### ISSUE TITLE
Winetricks adding extra '64' suffix to wine path

### ISSUE THREAD

**Issue by johnramsden** [Winetricks/winetricks#964]
Winetricks adds an extra 64 suffix to the WINE variable.

I'm getting the following error message:

```
Executing /app/bin/wine6464 regedit /S C:\windows\Temp\_d3dx11_43\override-dll.reg
/app/bin/winetricks: line 355: /app/bin/wine6464: No such file or directory
```

My wine environment variable is set to `WINE="/app/bin/wine64"`.

**Comment by austin987** [comment]
https://github.com/Winetricks/winetricks/commit/94163951d8f1120e41d1c6897c1a3638e69c751a
