### ISSUE TITLE
Trying to make SideSync Application work on Wine, where do I start?

### ISSUE THREAD

**Issue by pavitran** [Winetricks/winetricks#965]
I have executable file of [SideSync](http://www.samsung.com/in/support/convergence/sidesync/) application, which I'm trying to run on Ubuntu(16.04) using Wine. But every time I run it, it starts and gives a notice saying "error running the application". Can anyone tell me how can debug it and make it work..

**Comment by gverm** [comment]
@pavitran This is not the right place for wine bug reports. (Winetricks and wine are not the same thing)
Go here: https://bugs.winehq.org/
