### ISSUE TITLE
Winetricks 64-bit issue with windowscodecs

### ISSUE THREAD

**Issue by apemberton** [Winetricks/winetricks#970]
Ran into an interesting problem. Haven't quite root-caused it but thought to open an issue early in case it's a known issue.

If I run a simple winetricks command (any command, eg: `winetricks winxp`) before attempting to install WindowsCodecs (wic_x64_enu.exe) on a 64-bit prefix / 64-bit wine binary, the installer consistently fails.

If I use `winecfg` to set windows to winxp before installing the same `wic_x64_enu.exe`, things work fine. 

It's as though winetricks is causing some corruption or not properly setting things in a 64 bit prefix.

**Comment by austin987** [comment]
What winetricks version?

Please include the output.

**Comment by apemberton** [comment]
```
$ winetricks --version
20180217 - sha256sum: 59c0c463152738d673bbbb044f8c379cf878d4c6575ad7888d7cf063a9a16d3f
```

**Comment by slyscorpion** [comment]
Try the following command 

`sudo winetricks -self--update`

and then see if you still have the same issue once you have the latest version of winetricks.

**Comment by austin987** [comment]
@qwertychouskie https://github.com/Winetricks/winetricks/issues/795

**Comment by austin987** [comment]
I'm not able to reproduce this:
Using winetricks 20180217-next - sha256sum: 8c32bb4e5c61ba435ad632cfa6a825662fddd7f69d02ed0a52c8f0497b38fd24 with wine-3.0 and WINEARCH=win64|

both winetricks winxp and winetricks win10 work for me (verified in winecfg)

**Comment by apemberton** [comment]
@austin987 same - the os is indeed changed, but as stated in description, the issue is actually that downstream windowscodecs verb fails for unknown reason @ this point.

**Comment by austin987** [comment]
@apemberton from your initial description it seemed that setting the windows version was the problem.

In any case, you may be hitting the wmphoto problem, can't say without seeing the output. If so, https://github.com/Winetricks/winetricks/commit/f4d7b0ac35ae6bd1e23f2d904b31c9739ce3fc88 would fix that.

**Comment by apemberton** [comment]
Ha. No. Not that one. (That's the one I sent you a duplicate PR, remember?
:)

I'll investigate this one more soon when I can. My bigger fish to fry is
the dotnet461 problem with 64 bit.

**Comment by zfigura** [comment]
I suspect the difference is due to the different reporting of XP versions. 64-bit XP is 5.2, but 32-bit is 5.1, and winetricks just uses the latter for both. Using win2k3 instead of winxp in the verb seems to work universally.

**Comment by gverm** [comment]
@zfigura using the winxp64 override instead of winxp in a 64bit prefix will work too. See #1025 for an explanation. According to the info posted there, winxp64 is 5.2.

**Comment by zfigura** [comment]
winxp64 is basically 2k3 anyway, so I doubt it matters much.

**Comment by bobwya** [comment]
Hmmm... Many moons ago I ran Windows XP (64-bit). Applications would detect it as **Windows 2003 Server**.

**Comment by jp7677** [comment]
I have the same issue on win64. While windowcodecs installs fine for a win32 prefix, I had to hack my winetricks script to install windowcodecs on a win64 prefix. What I did was to comment the version override in the winetricks script so that it no longer overrides the windows version and used winecfg beforehand to select "Windows 2003" manually.

**Comment by jp7677** [comment]
All good now, thanks a lot!
