### ISSUE TITLE
remove_mono should also remove for 64 bit

### ISSUE THREAD

**Issue by apemberton** [Winetricks/winetricks#972]
https://github.com/Winetricks/winetricks/blob/131fc83bf9852f95bd753eb42d54bde7f7b401d7/src/winetricks#L9137

This line should also attempt to remove from syswow64 right?

**Comment by austin987** [comment]
Makes sense to me. I reached out to wine-mono maintainer to see if this will have any unintended consequences.

If you can, try winetricks-test dotnet with/without this change and compare results

**Comment by austin987** [comment]
@apemberton talked to Vincent, it should be removed. Please send a PR if you can.
