### ISSUE TITLE
vb6run

### ISSUE THREAD

**Issue by kd7adg** [Winetricks/winetricks#974]
I needed to install Visual Basic 6 in Wine. I used Winetricks and got the message sha256sum mismatch. I was able to download Visual Basic 6 from Microsoft and that installed correctly and works so I suspect the file Winetricks downloaded has become corrupted.

Tim     KD7ADG

**Comment by austin987** [comment]
What winetricks version? What sha256 do you have now? It works fine for me in 20180217-33-gef6672b
