### ISSUE TITLE
add a list all option for command line users

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Winetricks/winetricks#98]
```
It used to be possible to get a complete, straightforward list of all the 
winetricks verbs with one simple command (--help), but command line users now 
have to hunt through the capriciously-organized submenus to find the right 
verb. Please give us a command line option to list all the verbs at once. 
```

Original issue reported on code.google.com by `dime...@gmail.com` on 23 Jun 2011 at 1:06

**Comment by qwertychouskie** [comment]
This has been added (winetricks list-all), can this be closed?

**Comment by austin987** [comment]
Thanks.

**Comment by MrStonedOne** [comment]
How about a online list?

I'm on windows trying to help a user use my program in wine, and i need to find the list to jog my memory of the required trick because i know i'll recognize it by name but i can't find a fucking online list any where.
